### ISSUE TITLE
ET: cluster management over remote jmx doesn't work at EC2

### ISSUE THREAD

**Issue by patriknw** [akka/akka#13304]
imported from https://www.assembla.com/spaces/akka/tickets/3304

As already pointed out in the mailinglist. I think it was Evan.

<pre><code>
bin/akka-cluster localhost:9999 cluster-status
Querying cluster status
05/02/2013 15:11:22 +0000 akka.jmx.Client ClusterStatus:
Members:
  {Member(address = akka.tcp://TestApp@10.33.194.3:2552, status = Up)
  {Member(address = akka.tcp://TestApp@10.33.198.176:2552, status = Up)
  {Member(address = akka.tcp://TestApp@10.34.163.77:2552, status = Up)
</code></pre>

<pre><code>
bin/akka-cluster 10.33.194.3:9999 members
Akka cluster node is not available on 10.33.194.3:9999, due to Exception in thread "main" java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is:
  java.net.ConnectException: Connection refused
  at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
  at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
  at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
  at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:128)
  at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source)
  at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2343)
  at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:296)
  at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:267)
  at akka.jmx.Client.getJMXConnector(Client.java:216)
  at akka.jmx.Client.execute(Client.java:305)
  at akka.jmx.Client.execute(Client.java:274)
  at akka.jmx.Client.execute(Client.java:252)
  at akka.jmx.Client.main(Client.java:159)
Caused by: java.net.ConnectException: Connection refused
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
  at java.net.Socket.connect(Socket.java:546)
  at java.net.Socket.connect(Socket.java:495)
  at java.net.Socket.<init>(Socket.java:392)
  at java.net.Socket.<init>(Socket.java:206)
  at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
  at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:146)
  at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
  ... 12 more
</code></pre>

**Comment by rkuhn** [comment]
Closed due to lack of complaints.
