### ISSUE TITLE
FAILED: UnreachableNodeJoinsAgainSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#15003]
Jenkins build: https://jenkins.akka.io:8498/job/akka-multi-node/748

Failures:
```
[JVM-4] Coroner Thread Count started at 24, ended at 8, peaked at 26 in akka.cluster.UnreachableNodeJoinsAgainMultiJvmNode4
[JVM-4] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (14 seconds, 788 milliseconds)[0m
[JVM-4] [31m  Set(akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a4.moxie:54912, akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:43671, akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a6.moxie:51575) did not contain element akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783 (UnreachableNodeJoinsAgainSpec.scala:174)[0m
[JVM-4] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-4] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-4] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-4] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6026)[0m
[JVM-4] [31m  at 
```

```
[JVM-1] [WARN] [04/14/2014 14:01:45.977] [UnreachableNodeJoinsAgainSpec-akka.actor.default-dispatcher-15] [akka://UnreachableNodeJoinsAgainSpec/system/endpointManager] unhandled message from Actor[akka://UnreachableNodeJoinsAgainSpec/system/cluster/core/daemon/heartbeatSender#255893770]: Remote message Some(Actor[akka://UnreachableNodeJoinsAgainSpec/system/cluster/core/daemon/heartbeatSender#255893770]) -> Actor[akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783/]
[JVM-1] [WARN] [04/14/2014 14:01:45.978] [UnreachableNodeJoinsAgainSpec-akka.actor.default-dispatcher-15] [akka://UnreachableNodeJoinsAgainSpec/system/endpointManager] unhandled message from Actor[akka://UnreachableNodeJoinsAgainSpec/system/cluster/core/daemon/heartbeatSender#255893770]: Remote message Some(Actor[akka://UnreachableNodeJoinsAgainSpec/system/cluster/core/daemon/heartbeatSender#255893770]) -> Actor[akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a6.moxie:51575/]
[JVM-2] [INFO] [04/14/2014 14:01:46.012] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-6] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-2] [INFO] [04/14/2014 14:01:46.211] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-6] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-1] [ERROR] [04/14/2014 14:01:46.344] [UnreachableNodeJoinsAgainSpec-akka.actor.default-dispatcher-3] [akka://UnreachableNodeJoinsAgainSpec/user/controller/barriers] unannounced disconnect of RoleName(second) (akka.remote.testconductor.BarrierCoordinator$ClientLost)
[JVM-2] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 886 milliseconds)[0m
[JVM-2] [31m  3 was not equal to 4 (MultiNodeClusterSpec.scala:289)[0m
[JVM-2] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-2] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-2] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-2] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6014)[0m
```

```
[JVM-2] [31m  at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2525)[0m
[JVM-2] [31m  at scala.collection.immutable.List.foreach(List.scala:318)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2525)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1019)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1018)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2672)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1018)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.main(Runner.scala:835)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner.main(Runner.scala)[0m
[JVM-1] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 913 milliseconds)[0m
[JVM-1] [31m  java.lang.RuntimeException: barrier failed: after_4[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$4.applyOrElse(Player.scala:208)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$4.applyOrElse(Player.scala:184)[0m
[JVM-1] [31m  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)[0m
[JVM-1] [31m  at akka.actor.FSM$class.processEvent(FSM.scala:604)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)[0m
[JVM-1] [31m  at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)[0m
[JVM-1] [31m  at akka.actor.Actor$class.aroundReceive(Actor.scala:465)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)[0m
[JVM-1] [31m  at akka.actor.ActorCell.invoke(ActorCell.scala:487)[0m
[JVM-1] [31m  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:241)[0m
[JVM-1] [31m  at akka.dispatch.Mailbox.run(Mailbox.scala:223)[0m
[JVM-1] [31m  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[0m
[JVM-3] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 902 milliseconds)[0m
[JVM-3] [31m  3 was not equal to 4 (MultiNodeClusterSpec.scala:289)[0m
[JVM-3] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-3] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-3] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-3] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6014)[0m
[JVM-3] [31m  at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(MultiNodeClusterSpec.scala:289)[0m
[JVM-3] [31m  at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeClusterSpec.scala:289)[0m
```

```
[JVM-2] [WARN] [04/14/2014 14:01:36.176] [UnreachableNodeJoinsAgainSpec-akka.actor.default-dispatcher-2] [akka://UnreachableNodeJoinsAgainSpec/system/endpointManager/reliableEndpointWriter-akka.trttl.gremlin.tcp%3A%2F%2FUnreachableNodeJoinsAgainSpec%40a5.moxie%3A42783-4/endpointWriter] received dead letter from Actor[akka://UnreachableNodeJoinsAgainSpec/deadLetters]: Timer(AckIdleTimer,AckIdleCheckTimer,true,0)
[JVM-4] [INFO] [04/14/2014 14:01:36.183] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-5] [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783/system/remoting-terminator] Remoting shut down.
[JVM-3] [INFO] [04/14/2014 14:01:36.165] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-6] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-3] [INFO] [04/14/2014 14:01:36.166] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-5] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-4] Coroner Thread Count started at 24, ended at 8, peaked at 26 in akka.cluster.UnreachableNodeJoinsAgainMultiJvmNode4
[JVM-4] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (14 seconds, 788 milliseconds)[0m
[JVM-4] [31m  Set(akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a4.moxie:54912, akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:43671, akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a6.moxie:51575) did not contain element akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783 (UnreachableNodeJoinsAgainSpec.scala:174)[0m
[JVM-4] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-4] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-4] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-4] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6026)[0m
[JVM-4] [31m  at 
```

```
[JVM-2] [INFO] [04/14/2014 14:01:46.012] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-6] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-2] [INFO] [04/14/2014 14:01:46.211] [UnreachableNodeJoinsAgainSpec-akka.remote.default-remote-dispatcher-6] [Remoting] Quarantined address [akka.trttl.gremlin.tcp://UnreachableNodeJoinsAgainSpec@a5.moxie:42783] is still unreachable or has not been restarted. Keeping it quarantined.
[JVM-1] [ERROR] [04/14/2014 14:01:46.344] [UnreachableNodeJoinsAgainSpec-akka.actor.default-dispatcher-3] [akka://UnreachableNodeJoinsAgainSpec/user/controller/barriers] unannounced disconnect of RoleName(second) (akka.remote.testconductor.BarrierCoordinator$ClientLost)
[JVM-2] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 886 milliseconds)[0m
[JVM-2] [31m  3 was not equal to 4 (MultiNodeClusterSpec.scala:289)[0m
[JVM-2] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-2] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-2] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-2] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6014)[0m
```

```
[JVM-2] [31m  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1018)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2672)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1018)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner$.main(Runner.scala:835)[0m
[JVM-2] [31m  at org.scalatest.tools.Runner.main(Runner.scala)[0m
[JVM-1] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 913 milliseconds)[0m
[JVM-1] [31m  java.lang.RuntimeException: barrier failed: after_4[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$4.applyOrElse(Player.scala:208)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$4.applyOrElse(Player.scala:184)[0m
[JVM-1] [31m  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)[0m
[JVM-1] [31m  at akka.actor.FSM$class.processEvent(FSM.scala:604)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)[0m
[JVM-1] [31m  at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)[0m
[JVM-1] [31m  at akka.actor.Actor$class.aroundReceive(Actor.scala:465)[0m
[JVM-1] [31m  at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)[0m
[JVM-1] [31m  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)[0m
[JVM-1] [31m  at akka.actor.ActorCell.invoke(ActorCell.scala:487)[0m
[JVM-1] [31m  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:241)[0m
[JVM-1] [31m  at akka.dispatch.Mailbox.run(Mailbox.scala:223)[0m
[JVM-1] [31m  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)[0m
[JVM-1] [31m  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)[0m
[JVM-3] [31m- must allow fresh node with same host:port to join again when the network is plugged back in *** FAILED *** (24 seconds, 902 milliseconds)[0m
[JVM-3] [31m  3 was not equal to 4 (MultiNodeClusterSpec.scala:289)[0m
[JVM-3] [31m  org.scalatest.exceptions.TestFailedException:[0m
[JVM-3] [31m  at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)[0m
[JVM-3] [31m  at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:5980)[0m
[JVM-3] [31m  at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6014)[0m
```

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
