### ISSUE TITLE
FAILED: akka.persistence.LeveldbProcessorPersistentChannelSpec

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15203]
From the logs it looks like the persistence tests are executed in parallel. Is that correct? Or is it just that the Coroner doesn't get shut down properly when the test aborts?

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1047/consoleFull

```
Coroner Thread Count started at 12, ended at 7, peaked at 18 in akka.persistence.InmemProcessorChannelSpec
[info] LeveldbProcessorPersistentChannelSpec:
Coroner Thread Count starts at 11 in akka.persistence.LeveldbProcessorPersistentChannelSpec
[info] A processor that uses a channel
[info] Exception encountered when attempting to run a suite with class name: akka.persistence.LeveldbProcessorPersistentChannelSpec *** ABORTED ***
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg:
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:355)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:718)
[info]   at akka.persistence.ProcessorChannelSpec.setupTestProcessorData(ProcessorChannelSpec.scala:114)
[info]   at akka.persistence.ProcessorChannelSpec.beforeEach(ProcessorChannelSpec.scala:78)
[info]   at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:154)
[info]   at akka.persistence.ProcessorChannelSpec.beforeEach(ProcessorChannelSpec.scala:71)
[info]   at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:173)
[info]   at akka.persistence.ProcessorChannelSpec.beforeEach(ProcessorChannelSpec.scala:71)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:253)
[info]   ...
```

**Comment by patriknw** [comment]
This is about PersistentChannel, we will not spend any time on that.
