### ISSUE TITLE
FAILED: LeveldbPersistentActorSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#15407]
"A persistent actor must reply to the original sender() of a command, even when using persistAsync"

It seems like a timeout:

```
[info] - must reply to the original sender() of a command, even when using persistAsync *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: block took 8.530 seconds, exceeding 3.000 seconds
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:310)
[info]   at akka.testkit.TestKit.within(TestKit.scala:718)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:319)
[info]   at akka.testkit.TestKit.within(TestKit.scala:718)
[info]   at akka.persistence.PersistentActorSpec$$anonfun$33$$anonfun$apply$mcV$sp$23.apply$mcV$sp(PersistentActorSpec.scala:608)
[info]   at akka.persistence.PersistentActorSpec$$anonfun$33$$anonfun$apply$mcV$sp$23.apply(PersistentActorSpec.scala:594)
[info]   at akka.persistence.PersistentActorSpec$$anonfun$33$$anonfun$apply$mcV$sp$23.apply(PersistentActorSpec.scala:594)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1110/testReport/akka.persistence/LeveldbPersistentActorSpec/A_persistent_actor_must_reply_to_the_original_sender___of_a_command__even_when_using_persistAsync/

**Comment by drewhk** [comment]
Another one: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1952/consoleFull

**Comment by patriknw** [comment]
Doesn't happen often (7 months ago). Closing.
