### ISSUE TITLE
FAILED: ActorModelSpec

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15420]
```
     org.scalatest.exceptions.TestFailedException: Failed to count down within 1500 millis (count at 1). Processed message when allowed
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:493)
      at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1382)
      at org.scalatest.Assertions$class.fail(Assertions.scala:1172)
      at org.scalatest.Assertions$.fail(Assertions.scala:1382)
      at akka.actor.dispatch.ActorModelSpec$.assertCountDown(ActorModelSpec.scala:175)
      at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ActorModelSpec.scala:308)
      at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ActorModelSpec.scala:295)
      at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ActorModelSpec.scala:295)
      at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
      at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:945)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
      at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:942)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:954)
      at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1013)
      at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:54)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1059)
      at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
      at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
      at sbt.TestRunner.runTest$1(TestFramework.scala:84)
      at sbt.TestRunner.run(TestFramework.scala:94)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
      at sbt.TestFunction.apply(TestFramework.scala:224)
      at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
      at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
      at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
      at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
      at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
      at sbt.std.Transform$$anon$4.work(System.scala:64)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
      at sbt.Execute.work(Execute.scala:244)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
      at java.util.concurrent.FutureTask.run(FutureTask.java:166)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
      at java.util.concurrent.FutureTask.run(FutureTask.java:166)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:701)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1129/testReport/junit/akka.actor.dispatch/DispatcherModelSpec/A_Dispatcher_must_process_messages_one_at_a_time/

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
