### ISSUE TITLE
Failure during top level system actor creation is not logged

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15947]
When creating a top level actor and there is a failure during mailbox verification it is not logged.

**Comment by patriknw** [comment]
I tried this, and it's logged when I throw from `create` of the `MailboxType`:

```
[ERROR] [03/15/2016 18:46:44.790] [ActorMailboxSpec-akka.actor.default-dispatcher-18] [akka.actor.LocalActorRefProvider(akka://ActorMailboxSpec)] guardian failed, shutting down system
java.lang.RuntimeException: simulated
	at akka.actor.ActorMailboxSpec$MyUnboundedMailbox.create(ActorMailboxSpec.scala:256)
	at akka.dispatch.Dispatcher$$anon$1.<init>(Dispatcher.scala:88)
	at akka.dispatch.Dispatcher.createMailbox(Dispatcher.scala:88)
	at akka.actor.dungeon.Dispatch$class.init(Dispatch.scala:48)
	at akka.actor.ActorCell.init(ActorCell.scala:374)
	at akka.actor.RepointableActorRef.newCell(RepointableActorRef.scala:115)
	at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:100)
```

@bantonsson do you recall what this issue was about?

**Comment by rkuhn** [comment]
This has been mitigated accidentally, but there are some bugs in this behavior; most importantly the `/user` guardian should not fail (and suspend the whole hierarchy) every time a top-level actor fails its mailbox requirement.
