### ISSUE TITLE
FAILED: FSMTimingSpec failed in master

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#15972]
FSMTimingSpec failed in master

https://jenkins.akka.io:8498/job/akka-multi-node/895/consoleFull

```
[info] FSMTimingSpec:
Coroner Thread Count starts at 33 in akka.actor.FSMTimingSpec
[info] A Finite State Machine
[info] - must receive StateTimeout (1 second, 1 millisecond)
[info] - must cancel a StateTimeout (1 second, 1 millisecond)
[info] - must allow StateTimeout override (403 milliseconds)
[info] - must receive single-shot timer (2 seconds, 1 milliseconds)
[info] - must resubmit single-shot timer (2 seconds, 503 milliseconds)
[info] - must correctly cancel a named timer (619 milliseconds)
[info] - must not get confused between named and state timers *** FAILED *** (523 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (500 milliseconds) during expectMsg while waiting for Tick
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:348)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:334)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:733)
[info]   at akka.actor.FSMTimingSpec$$anonfun$3$$anonfun$apply$mcV$sp$12.apply$mcV$sp(FSMTimingSpec.scala:102)
[info]   at akka.actor.FSMTimingSpec$$anonfun$3$$anonfun$apply$mcV$sp$12.apply(FSMTimingSpec.scala:99)
[info]   at akka.actor.FSMTimingSpec$$anonfun$3$$anonfun$apply$mcV$sp$12.apply(FSMTimingSpec.scala:99)
...
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.3/199/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1134/consoleFull

**Comment by patriknw** [comment]
timeout (500 milliseconds) during expectMsg

on a0

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
