### ISSUE TITLE
Failed ScalaUdpMulticastSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#16262]
There was a failure on [akka-nightly](https://jenkins.akka.io:8498/job/akka-nightly/1701/)
```
[info] ScalaUdpMulticastSpec:
[info] listener
[info] - should send message back to sink *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.io.Udp$Bound
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:433)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:406)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:733)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalaUdpMulticastSpec.scala:36)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

Previous issues with this test (#15772, #15785) seem to be unrelated.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4408/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4419/consoleFull

**Comment by ktoso** [comment]
This seems to fail a lot suddenly https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4429/console

**Comment by johanandren** [comment]
Looking into it, current suspicions is that it is related to that we started running docker on the jenkins servers.

**Comment by ktoso** [comment]
Hmm... But we're stopping the containers hmhm

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3388/consoleFull

**Comment by drewhk** [comment]
This still fails

**Comment by rkuhn** [comment]
It fails consistently on my Mac:
~~~
[info] ScalaUdpMulticastSpec:
[info] listener
[INFO] [01/22/2016 15:34:15.319] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-3] [akka://ScalaUdpMulticastSpec/user/$a] Bound to /0:0:0:0:0:0:0:0:59760
[INFO] [01/22/2016 15:34:15.334] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-4] [akka://ScalaUdpMulticastSpec/user/$b] Sending message to /ff02:0:0:0:0:0:a486:647a%en0:59760
[info] - should send message back to sink *** FAILED *** (3 seconds, 113 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ohi
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalaUdpMulticastSpec.scala:44)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
~~~

**Comment by johanandren** [comment]
And again:
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5005/console

**Comment by johanandren** [comment]
And two more times. ![rageguy](https://cloud.githubusercontent.com/assets/666915/12611473/f6e6cee2-c4ec-11e5-8f8c-4c28033dae08.png)

**Comment by johanandren** [comment]
Test disabled for now, but issue not fixed.

**Comment by johanandren** [comment]
We meet again, old UDP multicast spec.
