### ISSUE TITLE
Failed: DisallowJoinOfTwoClustersSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#16304]
Two successive failures of multi-node-nightly:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1707/
```
[JVM-3]   Cause: java.lang.RuntimeException: unexpected transition: Transition(Actor[akka://DisallowJoinOfTwoClustersSpec/user/TestConductorClient#1548638953],Connecting,Failed)
[JVM-3]   at akka.remote.testconductor.Player$$anonfun$6$$anon$1$$anonfun$receive$1.applyOrElse(Player.scala:65)
[JVM-3]   at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[JVM-3]   at akka.remote.testconductor.Player$$anonfun$6$$anon$1.aroundReceive(Player.scala:56)
[JVM-3]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[JVM-3]   at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[JVM-3]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-3]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-3]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/1706/
```
[info] * akka.contrib.pattern.ClusterSharding
[error] Connection closed by 10.0.1.235
[error] Failed: akka.contrib.pattern.ClusterShardingMultiJvmNode2 sync
[info] * sample.cluster.stats.StatsSampleSingleMasterSpec
```

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
