### ISSUE TITLE
IllegalStateException in akka.dispatch.BatchingExecutor$Batch.run

### ISSUE THREAD

**Issue by maxcom** [akka/akka#16327]
Our application provides REST interface to database storage. User uploads data via HTTP interface, we store it to JDBC and then do some additional logic that processes uploaded data. HTTP interface is implemented via Spray 1.3.2; Akka version 2.3.6 (but I have seen this problem in previous 2.3.x). We do not use akka-streams.

We create and then stop an some number of actors per upload; also we use transformation operations on Future in context dispatcher.

Sometimes we see this exception in our logs:

```
[incident-daemon-system-akka.actor.default-dispatcher-233] ERROR akka.dispatch.Dispatcher - exception in sameThreadExecutionContext (a.d.Dispatcher)
java.lang.IllegalStateException: exception in sameThreadExecutionContext
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:76)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:207)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:55)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:76)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74)
        at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:110)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:73)
        ... 19 common frames omitted
```

We see this exception when client continuously uploads large number of objects (about a million). I do not know the way to reproduce this bug (other that posting a lot of data and waiting before the problem occurs).

**Comment by skisel** [comment]
Hello, I was able to reproduce this issue in the test provided in the PR. The problem happens because of using sameThreadExecutionContext, which runs the batch in the same thread.

P.S. This is my first contribution to open source ever, dont judge me too harshly.

**Comment by skisel** [comment]
@rkuhn I suppose this issue may be closed?

**Comment by rkuhn** [comment]
Yes, for some reason this was lacking a link from #16761, thanks for the diligence!

**Comment by maxcom** [comment]
After update to 2.3.10, I see following problem in my logs:

```
2015-04-27 14:06:06.498502500 [incident-daemon-system-akka.actor.default-dispatcher-35] ERROR akka.dispatch.Dispatcher - exception in sameThreadExecution
Context (a.d.Dispatcher)
2015-04-27 14:06:06.498504500 java.lang.IllegalStateException: Illegal transition attempted from: Closed with failure count = 10 to Open
2015-04-27 14:06:06.498505500 	at akka.pattern.CircuitBreaker.transition(CircuitBreaker.scala:229)
2015-04-27 14:06:06.498506500 	at akka.pattern.CircuitBreaker.akka$pattern$CircuitBreaker$$tripBreaker(CircuitBreaker.scala:236) 2015-04-27 14:06:06.498524500 	at akka.pattern.CircuitBreaker$Closed$.callFails(CircuitBreaker.scala:369) 
2015-04-27 14:06:06.498525500 	at akka.pattern.CircuitBreaker$State$$anonfun$callThrough$1.apply(CircuitBreaker.scala:299) 
2015-04-27 14:06:06.498526500 	at akka.pattern.CircuitBreaker$State$$anonfun$callThrough$1.apply(CircuitBreaker.scala:297) 
2015-04-27 14:06:06.498529500 	... 25 common frames omitted
2015-04-27 14:06:06.498529500 Wrapped by: java.lang.IllegalStateException: exception in sameThreadExecutionContext
2015-04-27 14:06:06.498530500 	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:77) 
2015-04-27 14:06:06.498535500 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) 
2015-04-27 14:06:06.498535500 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) 
2015-04-27 14:06:06.498536500 	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73) 
2015-04-27 14:06:06.498539500 	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74) 
2015-04-27 14:06:06.498539500 	at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:120) 
2015-04-27 14:06:06.498540500 	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:73) 
2015-04-27 14:06:06.498543500 	... 19 common frames omitted
2015-04-27 14:06:06.498543500 Wrapped by: java.lang.IllegalStateException: exception in sameThreadExecutionContext
2015-04-27 14:06:06.498544500 	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:77) 
2015-04-27 14:06:06.498544500 	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) 
2015-04-27 14:06:06.498548500 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) 
2015-04-27 14:06:06.498549500 	at scala.concurrent.Promise$class.complete(Promise.scala:55) 
2015-04-27 14:06:06.498550500 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) 
2015-04-27 14:06:06.498550500 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) 
2015-04-27 14:06:06.498553500 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) 
2015-04-27 14:06:06.498554500 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) 
2015-04-27 14:06:06.498554500 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) 
2015-04-27 14:06:06.498555500 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:90) 
2015-04-27 14:06:06.498565500 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88) 
2015-04-27 14:06:06.498566500 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88)
2015-04-27 14:06:06.498572500 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) 
2015-04-27 14:06:06.498573500 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:88)
2015-04-27 14:06:06.498573500 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) 
2015-04-27 14:06:06.498576500 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)2015-04-27 14:06:06.498577500 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
2015-04-27 14:06:06.498577500 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 
2015-04-27 14:06:06.498580500 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
2015-04-27 14:06:06.498581500 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
```

I'm not sure is it a problem in Akka, Or I am doing something wrong with circuit breaker. I'll re-check my code to see if there is something wrong there.

**Comment by ktoso** [comment]
Thanks for reporting, I'm not sure at first sight where the problem lies - I'll open the ticket and investigate later. Please let us know what you find!

**Comment by benmccann** [comment]
I'm getting this in Play 2.4 as well. See https://github.com/playframework/playframework/issues/4372

**Comment by benmccann** [comment]
It looks like it's only happening in 2.3.10. I forced my project to use 2.3.9 and I stopped getting the errors. I'm going to downgrade Play

**Comment by rkuhn** [comment]
@maxcom The exception you are seeing is unrelated to the BatchingExecutor, it is the CircuitBreaker that gets confused. However, since the CircuitBreaker did not change for 1.5 years, could you let us know from which version you switched to 2.3.10?

**Comment by maxcom** [comment]
2.3.9

**Comment by rkuhn** [comment]
Can you tell us a bit more about your observation? Have you never seen this error before? How often do you see it now? Has anything else changed besides Akka version?

**Comment by maxcom** [comment]
Nothing was changed in actors and circuit breaker usage, but there was minor changes in application logic.

Problem happens in large batch process after some number of application level exceptions that opens circuit breaker. That exceptions are caused by overload of external service.

Here is source code of actor that uses CircuitBreaker: https://gist.github.com/maxcom/1d06b2cc4f5c604d568e

**Comment by rkuhn** [comment]
The issue that this ticket is about has been fixed.

@maxcom Let’s continue the investigation in #17415.
