### ISSUE TITLE
akka-build: setup jenkins build with akka.test.sigar=true

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [akka/akka#16369]
after #16354 makes new property available: ```akka.test.sigar```

per Patrik https://github.com/akka/akka/pull/16354#discussion_r20719701

please setup extra jenkins build with 
```
akka.test.sigar=true
```

it can be limited to ```akka-cluster``` and cluster dependencies

**Comment by Andrei-Pozolotin** [comment]
related todo list

https://github.com/akka/akka/blob/master/project/Dependencies.scala#L68
```TODO remove from "test" config```

https://github.com/akka/akka/blob/master/project/SigarLoader.scala#L41
```TODO remove Sigar form test:test* classpath, it is provided by Sigar agent.```

https://github.com/akka/akka/blob/master/akka-cluster-metrics/src/test/scala/akka/cluster/metrics/TestUtil.scala#L95
```TODO change factory after https://github.com/akka/akka/issues/16369```

**Comment by Andrei-Pozolotin** [comment]
need this answer from sbt team
http://stackoverflow.com/questions/27045920/sbt-include-into-testcompile-but-exclude-from-testtest

**Comment by patriknw** [comment]
thanks

**Comment by patriknw** [comment]
also, silence or remove stack trace from the logs:

    [JVM-1] no libsigar-universal64-macosx.dylib in java.library.path
    [JVM-1] org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
    [JVM-1]     at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
    [JVM-1]     at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
    [JVM-1]     at akka.cluster.metrics.SigarProvider$class.verifiedSigarInstance(Provision.scala:48)
    [JVM-1]     at akka.cluster.metrics.DefaultSigarProvider.verifiedSigarInstance(Provision.scala:92)
    [JVM-1]     at akka.cluster.metrics.SigarProvider$$anonfun$createSigarInstance$2.apply(Provision.scala:67)
    [JVM-1]     at akka.cluster.metrics.SigarProvider$$anonfun$createSigarInstance$2.apply(Provision.scala:67)
    [JVM-1]     at akka.cluster.metrics.TryNative$.apply(Provision.scala:101)
    [JVM-1]     at akka.cluster.metrics.SigarProvider$class.createSigarInstance(Provision.scala:66)
    [JVM-1]     at akka.cluster.metrics.DefaultSigarProvider.createSigarInstance(Provision.scala:92)
    [JVM-1]     at akka.cluster.metrics.SigarMetricsCollector.<init>(MetricsCollector.scala:202)
    [JVM-1]     at akka.cluster.metrics.SigarMetricsCollector.<init>(MetricsCollector.scala:207)

**Comment by patriknw** [comment]
The new jenkins job is: https://jenkins.akka.io:8498/job/akka-nightly-sigar/
It fails a lot. I have not looked at what kind of failures.

**Comment by ktoso** [comment]
Example failure is: https://jenkins.akka.io:8498/job/akka-nightly-sigar/4/consoleFull

```
 must merge an existing metric set for a node and update node ring *** FAILED *** (6 milliseconds)
[info]   Some(Set(Metric(heap-memory-used,116444560,Some(EWMA(1.1644456E8,0.18181818181818182))), Metric(heap-memory-max,7497842688,None), Metric(cpu-combined,1.0,Some(EWMA(1.0,0.18181818181818182))), Metric(processors,16,None), Metric(system-load-average,2.14,None), Metric(heap-memory-committed,481820672,Some(EWMA(4.81820672E8,0.18181818181818182))), Metric(cpu-stolen,0.0,Some(EWMA(0.0,0.18181818181818182))))) did not equal Some(Set(Metric(heap-memory-used,116444560,Some(EWMA(1.1644456E8,0.18181818181818182))), Metric(heap-memory-max,7497842688,None), Metric(processors,16,None), Metric(system-load-average,2.14,None), Metric(heap-memory-committed,481820672,Some(EWMA(4.81820672E8,0.18181818181818182))))) (MetricSpec.scala:187)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[info]   at akka.cluster.metrics.MetricsGossipSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply$mcV$sp(MetricSpec.scala:187)
[info]   at akka.cluster.metrics.MetricsGossipSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(MetricSpec.scala:172)
[info]   at akka.cluster.metrics.MetricsGossipSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(MetricSpec.scala:172)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:56)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:56)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:56)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:56)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:56)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:56)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info] - must get the current NodeMetrics if it exists in the local nodes (2 milliseconds)
```

**Comment by patriknw** [comment]
The first sample contains less entries than the first. That is probably because sometimes Sigar will not be able to return a valid value (NaN and such). I have created a test fix in PR https://github.com/akka/akka/pull/18506

**Comment by patriknw** [comment]
The tests seems alright now.
