### ISSUE TITLE
FAILED: ClientServerSpec: 

### ISSUE THREAD

**Issue by drewhk** [akka/akka#16405]
[info] - should properly complete a chunked request/response cycle *** FAILED *** (340 milliseconds)
    [info]   Vector(Chunk(ByteString(97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108),), LastChunk(,List())) did not equal List(Chunk(ByteString(97, 98, 99),), Chunk(ByteString(100, 101, 102, 103),), Chunk(ByteString(104, 105, 106, 107, 108),), LastChunk(,List())) (ClientServerSpec.scala:120)

Does not seem to fail on validation.
/cc @jrudolph @sirthias

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3047/consoleFull

```
info] ClientServerSpec:
[info] The low-level HTTP infrastructure
[info] - should properly bind a server (21 milliseconds)
[WARN] [06/26/2015 14:10:42.376] [ClientServerSpec-akka.actor.default-dispatcher-7] [akka://ClientServerSpec/system/IO-TCP-STREAM/server-1-localhost%2F127.0.0.1%3A45897] received dead letter from Actor[akka://ClientServerSpec/system/IO-TCP/selectors/$a/0#550896291]: Unbound
[ERROR] [06/26/2015 14:10:42.422] [ClientServerSpec-akka.actor.default-dispatcher-7] [akka://ClientServerSpec/system/IO-TCP/selectors/$a/2] Bind failed for TCP channel on endpoint [localhost/127.0.0.1:58640]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:53)
	at akka.io.TcpListener.<init>(TcpListener.scala:50)
	at sun.reflect.GeneratedConstructorAccessor46.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [06/26/2015 14:10:42.433] [ClientServerSpec-akka.actor.default-dispatcher-6] [akka://ClientServerSpec/system/IO-TCP/selectors/$a/3] Bind failed for TCP channel on endpoint [localhost/127.0.0.1:58640]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:53)
	at akka.io.TcpListener.<init>(TcpListener.scala:50)
	at sun.reflect.GeneratedConstructorAccessor46.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info] - should report failure if bind fails (71 milliseconds)
[info] - should run with bindAndHandleSync (22 milliseconds)
[info] - should prevent more than the configured number of max-connections with bindAndHandle (1 second, 76 milliseconds)
[info]   should log materialization errors in `bindAndHandle` which
[WARN] [06/26/2015 14:10:44.599] [ClientServerSpec-akka.actor.default-dispatcher-3] [akka://ClientServerSpec/system/IO-TCP/selectors/$a/1] received dead letter from Actor[akka://ClientServerSpec/system/IO-TCP-STREAM/client-2-localhost%2F127.0.0.1%3A45236#-792626288]: ResumeReading
[WARN] [06/26/2015 14:10:44.600] [ClientServerSpec-akka.actor.default-dispatcher-3] [akka://ClientServerSpec/system/IO-TCP/selectors/$a/1] received dead letter from Actor[akka://ClientServerSpec/system/IO-TCP-STREAM/client-2-localhost%2F127.0.0.1%3A45236#-792626288]: Abort
[info]   - are triggered in `transform` *** FAILED *** (1 second, 241 milliseconds)
[info]     java.lang.AssertionError: Received 1 messages too many on ErrorFilter(class java.lang.RuntimeException,None,Left(BOOM),true)
[info]     at akka.testkit.EventFilter.intercept(TestEventListener.scala:106)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply$mcV$sp(ClientServerSpec.scala:158)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply(ClientServerSpec.scala:143)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply(ClientServerSpec.scala:143)
[info]     at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply$mcV$sp(ClientServerSpec.scala:160)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(ClientServerSpec.scala:160)
[info]     at akka.http.scaladsl.ClientServerSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply(ClientServerSpec.scala:160)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]     at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]     at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:318)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:318)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:318)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]     at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]     at akka.http.scaladsl.ClientServerSpec.org$scalatest$BeforeAndAfterAll$$super$run(ClientServerSpec.scala:29)
[info]     at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]     at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]     at akka.http.scaladsl.ClientServerSpec.run(ClientServerSpec.scala:29)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]     at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]     at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]     at sbt.TestRunner.run(TestFramework.scala:94)
[info]     at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]     at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]     at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]     at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]     at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]     at sbt.TestFunction.apply(TestFramework.scala:224)
[info]     at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
[info]     at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]     at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]     at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]     at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]     at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]     at sbt.Execute.work(Execute.scala:244)
[info]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]     at java.lang.Thread.run(Thread.java:745)
[WARN] [06/26/2015 14:10:45.850] [ClientServerSpec-akka.actor.default-dispatcher-17] [
```
