### ISSUE TITLE
FAILED: dbuild fails to extract and build akka

### ISSUE THREAD

**Issue by bantonsson** [akka/akka#16478]
https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-Java8/87/console

```
[akka] --== Extracting dependencies for akka ==--
[akka] Fetching https://github.com/akka/akka.git
[akka] into /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/clones/6a06c693d070a06224673b7e010e55b9d0ba80c2
[akka] Took: 00h 00m 13.2s
[akka] Fetching /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/clones/6a06c693d070a06224673b7e010e55b9d0ba80c2
[akka] into /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536
[akka] Took: 00h 00m 24.5s
[akka] Extracting dependencies for: akka
[akka] Using Scala 2.11.0-RC1 during extraction.
[akka] Using sbt version: 0.13.5
[akka:error] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=640m; support was removed in 8.0
[akka] [info] Loading project definition from /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project/project
[akka] [info] Updating {file:/localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project/project/}root-78951c9bb906d205320a1510d3c245fbea9e9536-build-build...
[akka] [info] Done updating.
[akka] [info] Loading project definition from /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project
[akka] [info] Resetting onLoad... in one scope
[akka] [info] Loading project definition from /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project
[akka] [info] Dependencies among subprojects:
[akka] [info] default-sbt-project -> 
[akka] [info] Aggregates of subprojects:
[akka] [info] default-sbt-project -> 
[akka] [info] Building graph...
[akka] [info] sorting...
[akka] [info] These subprojects will be built: default-sbt-project
[akka] [info] Updating {file:/localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project/}root-78951c9bb906d205320a1510d3c245fbea9e9536-build...
[akka] [info] Done updating.
[akka] [info] Compiling 17 Scala sources to /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/project/target/scala-2.10/sbt-0.13/classes...
[akka] [warn] there were 21 deprecation warning(s); re-run with -deprecation for details
[akka] [warn] there were 7 feature warning(s); re-run with -feature for details
[akka] [warn] two warnings found
[akka:error] /localhome/jenkinsdbuild4/workspace/Community-2.11.x-Java8/target-0.9.1/extraction/58db0d1acc9a23c6cf149297ae51408465c1296b/projects/78951c9bb906d205320a1510d3c245fbea9e9536/build.sbt:1: error: not found: value enablePlugins
[akka:error] enablePlugins(akka.RootSettings)
[akka:error] ^
[akka] [error] Type error in expression
[akka] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[akka:error] java.lang.RuntimeException: 
[akka:error] 	at scala.sys.package$.error(package.scala:27)
[akka:error] 	at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[akka:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[akka:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[akka:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[akka:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[akka:error] 	at sbt.IO$.withTemporaryFile(IO.scala:311)
[akka:error] 	at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[akka:error] 	at distributed.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:99)
[akka:error] 	at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:58)
[akka:error] 	at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:18)
[akka] --== End Extracting dependencies for akka ==--
```

**Comment by rkuhn** [comment]
Is this still an issue? Seems to work from what 2m reports right now.

**Comment by 2m** [comment]
It is not. [Last community-build](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/420/consoleFull) build akka just fine:
```
[info] Project akka--------------------: SUCCESS (project rebuilt ok)
```

This is fixed since https://github.com/scala/community-builds/issues/80

**Comment by gkossakowski** [comment]
Yep, it's fixed.
