### ISSUE TITLE
FlexiMerge completionHandling doesn't catch thrown exceptions

### ISSUE THREAD

**Issue by sirthias** [akka/akka#16577]
Throwing an exception in the CompletionHandling::onComplete handler results in

```
java.lang.IllegalStateException: Processor actor terminated abruptly
	at akka.stream.impl.FanIn.postStop(FanIn.scala:224)
	at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
...
```

**Comment by l15k4** [comment]
Hey,

I'm getting this exception when `process` Flow throws FlowException that should be handled by decider and the element should be skipped : 
```scala
  val decider: Supervision.Decider = {
    case FlowException(_) =>
      Supervision.Resume
    case ex =>
      log.error(ex, "Unexpected exception in flow execution occurred")
      Supervision.Stop
  }

  implicit val materializer = ActorFlowMaterializer(
    ActorFlowMaterializerSettings(context.system).withSupervisionStrategy(decider)
  )

source.via(process).via(store).runWith(sink)
```

But instead this happens : 

```
[info]     Cause: java.lang.IllegalStateException: Processor actor terminated abruptly
[info]     at akka.stream.impl.fusing.ActorInterpreter.postStop(ActorInterpreter.scala:288)
[info]     at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundPostStop(ActorInterpreter.scala:271)
[info]     at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
[info]     at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
[info]     at akka.actor.ActorCell.terminate(ActorCell.scala:369)
[info]     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
[info]     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[info]     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:220)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Does it relate to this issue ?
