### ISSUE TITLE
java.lang.IllegalStateException in akka.stream.ssl.SslTlsCipherActor

### ISSUE THREAD

**Issue by Alien2150** [akka/akka#16648]
Hi,

i just wrote a simple Server Application where i am establishing a TLS connection to the client. But after a while i got an error message and the tcp-connections gets dropped. These are the log - entries:

```
java.lang.IllegalStateException
        at akka.stream.ssl.SslTlsCipherActor$$anonfun$6.apply$mcV$sp(SslTlsCiphe
r.scala:345)
        at akka.stream.impl.Pump$class.pump(Transfer.scala:163)
        at akka.stream.ssl.SslTlsCipherActor.pump(SslTlsCipher.scala:93)
        at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcess
or.scala:78)
        at akka.stream.impl.MultiStreamInputProcessor$SubstreamInput.substreamOn
Next(StreamOfStreamProcessors.scala:279)
        at akka.stream.impl.MultiStreamInputProcessorLike$$anonfun$2.applyOrElse
(StreamOfStreamProcessors.scala:303)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at akka.stream.ssl.SslTlsCipherActor.aroundReceive(SslTlsCipher.scala:93
)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
[INFO] [01/14/2015 15:36:22.094] [app-akka.actor.default-dispatcher-19] [akka.tc
p://app@10.10.101.28:2552/user/$e] Received: Cancel class akka.stream.actor.Acto
rPublisherMessage$Cancel$
[INFO] [01/14/2015 15:36:22.097] [app-akka.actor.default-dispatcher-16] [akka.tc
p://app@10.10.101.28:2552/user/$f] foo: class akka.stream.actor.ActorSubscriberM
essage$OnError
[INFO] [01/14/2015 15:36:22.098] [app-akka.actor.default-dispatcher-19] [akka.tc
p://app@10.10.101.28:2552/user/$b] received class class akka.stream.actor.ActorS
ubscriberMessage$OnError
```

**Comment by Alien2150** [comment]
The problem seems to be the MTU-size in case i am sending a large packet using TLS. Is there anything i can do to fix the problem?

**Comment by drewhk** [comment]
This class is being worked on, we will look at this, but might take some time.

**Comment by Alien2150** [comment]
I think i found a way to fix it temporary: https://gist.github.com/Alien2150/9cb43a28dfee087bdf2e 
The code is not optimized yet but it works fine for me.

**Comment by rkuhn** [comment]
Thanks for the gist, that will be helpful!

**Comment by Alien2150** [comment]
No problem. The code overall is not optimized i can send you the exact problem /details if you like

**Comment by rkuhn** [comment]
It would be best if you could describe the problem and solution in this ticket so that it is easy to find, thanks!

**Comment by Alien2150** [comment]
Sure. 

The overall problem is the BufferUnderflow handling in the doUnwrap method. Regarding the SSLEngine documentation (http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html) the buffer underflows means that the TLSRecord is larger than there are bytes available (src buffer). So to fix this you need to do three things:
1.) Store the current data from cipherTextInboundBytes in a buffer and append all incoming data to this buffer
2.) Know the TLS/SSL Record Size. This is a tricky one. The problem is that the SSLEngine sadly does not provide any method of how many data are needed to run the unwrap - method. The Netty developers do this in their SSLHandler class as well (See decode method): https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/SslHandler.java )
3.) Put in the exactly amount of data into the unwrap method and you won't receive any Exceptions.

Let me know if you need more information

Regards,
Thomas

**Comment by Alien2150** [comment]
@raboof was solved a short while after. Can be closed
