### ISSUE TITLE
NullPointerException in LocalSnapshotStore  

### ISSUE THREAD

**Issue by raboof** [akka/akka#16737]
While running our tests, I sometimes (but rarely) see the following exception:

```
2015-01-28 13:11:02,081 ERROR [OneForOneStrategy > akka://rfs-rebb-ohm-api-UnparsableContentRoutesSpec/system/snapshot-store]: null
java.lang.NullPointerException: null
        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.SeqLike$class.size(SeqLike.scala:106) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:186) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:22) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:241) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.11.5.jar:0.13.5]
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186) ~[scala-library-2.11.5.jar:0.13.5]
        at akka.persistence.snapshot.local.LocalSnapshotStore.snapshotMetadata(LocalSnapshotStore.scala:108) ~[akka-persistence-experimental_2.11-2.3.9.jar:na]
        at akka.persistence.snapshot.local.LocalSnapshotStore.loadAsync(LocalSnapshotStore.scala:47) ~[akka-persistence-experimental_2.11-2.3.9.jar:na]
        at akka.persistence.snapshot.SnapshotStore$$anonfun$receive$1.applyOrElse(SnapshotStore.scala:27) ~[akka-persistence-experimental_2.11-2.3.9.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.persistence.snapshot.local.LocalSnapshotStore.aroundReceive(LocalSnapshotStore.scala:26) ~[akka-persistence-experimental_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[akka-actor_2.11-2.3.9.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40-internal]
```

As far as I can see akka.persistence.snapshot-store.local.dir is "target/snapshots" and this directory seems to remain empty (indeed we don't use snapshots heavily).

I'm not sure what to look for, any pointers?

**Comment by rkuhn** [comment]
Thanks for the report, it might help to also attach the configuration you are using.

**Comment by klunnii** [comment]
Hi! Our application is based on version 2.3.6 and uses persistence. Faced this exception as well. Is there any workaround we can apply before release of 2.4?

**Comment by patriknw** [comment]
listFiles will return null if the directory does not exist, and that will result in a similar (but not same) exception.

The directory is created on startup, but if it is removed later there will be trouble.

**Comment by ktoso** [comment]
Resolved in https://github.com/akka/akka/issues/17127
