### ISSUE TITLE
ERROR akka.io.TcpListener - Accept error: could not accept new connection java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by liu-hongwei** [akka/akka#16872]
hi,

i am using Spray (https://github.com/spray/spray/wiki ) as HTTP server to serves the REST APIs for my project,

in the stress test, i got tons of this error. my config as this:

akka {
  # Use SLF4J/logback for deployed environment logging
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel="DEBUG"
  log-config-on-start = on
  stdout-loglevel = "DEBUG"
  jvm-exit-on-fatal-error = on

  io
    {
      tcp
        {
          trace-logging = on
        }

      udp
        {
          trace-logging = on
        }

      udp-connected
        {
          trace-logging = on
        }
    }

  actor
    {
      debug
        {
          autoreceive = on
          lifecycle = on
          fsm = on
          unhandled: on
          receive: on
          event-stream = on
        }
    }

  remote {
    log-sent-messages = on
    log-received-messages = on
  }

}

# check the reference.conf in spray-can/src/main/resources for all defined settings
spray.can.server {
  # uncomment the next line for making this an HTTPS example
  # ssl-encryption = on
  idle-timeout = 20 s
  request-timeout = 15 s
  pipelining-limit = 2 # for maximum performance (prevents StopReading / ResumeReading messages to the IOBridge)
  # Needed for HTTP/1.0 requests with missing Host headers
  default-host-header = "spray.io:8765"

  verbose-error-messages = on

}

[2015-02-13 01:59:17,883] ERROR akka.io.TcpListener [] [akka://JobServer/system/IO-TCP/selectors/$a/0] - Accept error: could not accept new connection
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241)
        at akka.io.TcpListener.acceptAllPending(TcpListener.scala:96)
        at akka.io.TcpListener$$anonfun$bound$1.applyOrElse(TcpListener.scala:76)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[

**Comment by drewhk** [comment]
Hi, have you tried to change the number of selectors used by io?

**Comment by hepin1989** [comment]
@liu-hongwei could you please list the result of ```ulimit -n```

**Comment by liu-hongwei** [comment]
ulimit -n 

1024

but i saw the error even after i just submitted around 100 requests from spark job server.

**Comment by hepin1989** [comment]
are you running other services on the same machine？

**Comment by liu-hongwei** [comment]
yes, i have the spark cluster(both master and worker node) and spark job server running on a single machine(8 cores, 14 G memory, Ubuntu VM on Azure)

**Comment by hepin1989** [comment]
the spark is using netty,then that will consume some fd.you could change the ulimit and re-run the sample.I think that will work.

**Comment by bantonsson** [comment]
I assume that this was a Linux configuration issue.
