### ISSUE TITLE
FAILED: LeaderDowningNodeThatIsUnreachableSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#16890]
`LeaderDowningNodeThatIsUnreachableSpec` seems to have been fleaky. 
in 2060 it failed, in 2061 it was OK again.

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2060/consoleFull

```
[JVM-3] - must be able to DOWN a 'last' node that is UNREACHABLE *** FAILED *** (6 seconds, 531 milliseconds)
[JVM-3]   java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[JVM-3]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
[JVM-3]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-3]   at scala.concurrent.Await$.result(package.scala:116)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec$AwaitHelper.await(MultiNodeSpec.scala:263)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.node(MultiNodeSpec.scala:364)
[JVM-3]   at akka.cluster.MultiNodeClusterSpec$class.address(MultiNodeClusterSpec.scala:156)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.address(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LeaderDowningNodeThatIsUnreachableSpec.scala:52)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(LeaderDowningNodeThatIsUnreachableSpec.scala:49)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(LeaderDowningNodeThatIsUnreachableSpec.scala:49)
[JVM-3]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-3]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:945)
[JVM-3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:171)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.withFixture(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:942)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:954)
[JVM-3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-3]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:954)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.runTest(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1013)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[JVM-3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[JVM-3]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1013)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.runTests(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.org$scalatest$WordSpecLike$$super$run(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1059)
[JVM-3]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[JVM-3]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1059)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.org$scalatest$BeforeAndAfterAll$$super$run(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[JVM-3]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[JVM-3]   at akka.cluster.LeaderDowningNodeThatIsUnreachableSpec.run(LeaderDowningNodeThatIsUnreachableSpec.scala:37)
[JVM-3]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[JVM-3]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[JVM-3]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[JVM-3]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
```

**Comment by patriknw** [comment]
here is another one: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2571/consoleFull

**Comment by patriknw** [comment]
and here: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2569/consoleFull

**Comment by patriknw** [comment]
and here: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2578/consoleFull

 I wonder why this suddenly has started failing. Both on master and release-2.3.

**Comment by patriknw** [comment]
ah, it might be related to that I changed to a java8 jvm for running the multi-node tests in the pr-validator job
I never changed back that part, because I thought it would be harmless.
I'll change it back to java6, and we can test more in another branch/job.

**Comment by patriknw** [comment]
changed, next pending job is 2583

**Comment by drewhk** [comment]
Still: https://jenkins.akka.io:8498/job/akka-nightly/2297/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2298/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/2299/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2304/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/2305/consoleFull
Fails very often now, I stop pinging

**Comment by patriknw** [comment]
annoying, I wonder what we changed?

**Comment by drewhk** [comment]
system message delivery?

**Comment by patriknw** [comment]
nope, that is not even merged yet

**Comment by drewhk** [comment]
That is good news :)

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/25/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2344/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2547/consoleFull

**Comment by patriknw** [comment]
Interesting. All these failures are at LeaderDowningNodeThatIsUnreachableSpec.scala:52, which is an ordinary `val fourthAddress = address(fourth)`, right in the beginning of the test.

It looks like `fourth` jvm just exits without reason. Previously I wrote something about that this started when we switched to jdk8, maybe that is actually true.

**Comment by patriknw** [comment]
Here is a failure after the jdk update: https://jenkins.akka.io:8498/job/akka-nightly/2354/consoleFull
The jvm does not exit.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2363/consoleFull

**Comment by patriknw** [comment]
this is weird, it is still an ordinary `address(fourth)` that fails 

I'm starting a repeat job with debug logging: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/

**Comment by patriknw** [comment]
argh, how could I have missed this before. Banging head into something hard.
There is no barrier before `testConductor.exit(fourth, 0).await`
