### ISSUE TITLE
FAILED: RemoteNodeRestartDeathWatchSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#16907]
https://jenkins.akka.io:8498/job/akka-nightly/1994/

Looks like a real port conflict.

    [info] * akka.remote.RemoteNodeRestartDeathWatch
    [JVM-1] [INFO] [02/17/2015 21:52:05.693] [ScalaTest-main] [akka.remote.Remoting] Starting remoting
    [JVM-1] [WARN] [02/17/2015 21:52:06.007] [RemoteNodeRestartDeathWatchSpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://RemoteNodeRestartDeathWatchSpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.
    [JVM-1] [INFO] [02/17/2015 21:52:06.057] [ScalaTest-main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.trttl.gremlin.tcp://RemoteNodeRestartDeathWatchSpec@localhost:33533]
    [JVM-1] [ERROR] [02/17/2015 21:52:06.561] [RemoteNodeRestartDeathWatchSpec-akka.actor.default-dispatcher-2] [akka://RemoteNodeRestartDeathWatchSpec/user/controller] null
    [JVM-1] akka.actor.ActorInitializationException: exception during creation
    [JVM-1]     at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
    [JVM-1]     at akka.actor.ActorCell.create(ActorCell.scala:596)
    [JVM-1]     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
    [JVM-1]     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    [JVM-1]     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
    [JVM-1]     at akka.dispatch.Mailbox.run(Mailbox.scala:223)
    [JVM-1]     at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    [JVM-1]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    [JVM-1]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    [JVM-1]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    [JVM-1]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    [JVM-1] Caused by: java.lang.reflect.InvocationTargetException
    [JVM-1]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [JVM-1]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    [JVM-1]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    [JVM-1]     at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
    [JVM-1]     at akka.util.Reflect$.instantiate(Reflect.scala:66)
    [JVM-1]     at akka.actor.ArgsReflectConstructor.produce(Props.scala:341)
    [JVM-1]     at akka.actor.Props.newActor(Props.scala:252)
    [JVM-1]     at akka.actor.ActorCell.newActor(ActorCell.scala:552)
    [JVM-1]     at akka.actor.ActorCell.create(ActorCell.scala:578)
    [JVM-1]     ... 9 more
    [JVM-1] Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:4711
    [JVM-1]     at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
    [JVM-1]     at akka.remote.testconductor.RemoteConnection$.apply(RemoteConnection.scala:65)
    [JVM-1]     at akka.remote.testconductor.Controller.<init>(Conductor.scala:391)
    [JVM-1]     ... 18 more
    [JVM-1] Caused by: java.net.BindException: Address already in use
    [JVM-1]     at sun.nio.ch.Net.bind0(Native Method)
    [JVM-1]     at sun.nio.ch.Net.bind(Net.java:174)
    [JVM-1]     at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:139)
    [JVM-1]     at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:77)
    [JVM-1]     at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
    [JVM-1]     at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
    [JVM-1]     at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
    [JVM-1]     at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
    [JVM-1]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    [JVM-1]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [JVM-1]     at java.lang.Thread.run(Thread.java:701)

**Comment by patriknw** [comment]
I don't think there is much we can do here. 4711 is the test conductor port and we are not supposed to run several of these at the same time. Don't know what was going on there.
