### ISSUE TITLE
FAILED: ReliableProxyMultiJvm

### ISSUE THREAD

**Issue by 2m** [akka/akka#16946]
```
[JVM-1] - must stop proxy if target stops and no reconnection *** FAILED ***
[JVM-1]   akka.actor.InvalidActorNameException: actor name [proxy] is not unique!
[JVM-1]   at akka.actor.dungeon.ChildrenContainer$TerminatingChildrenContainer.reserve(ChildrenContainer.scala:192)
[JVM-1]   at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76)
[JVM-1]   at akka.actor.ActorCell.reserveChild(ActorCell.scala:369)
[JVM-1]   at akka.actor.dungeon.Children$class.makeChild(Children.scala:202)
[JVM-1]   at akka.actor.dungeon.Children$class.attachChild(Children.scala:41)
[JVM-1]   at akka.actor.ActorCell.attachChild(ActorCell.scala:369)
[JVM-1]   at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:586)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anonfun$apply$mcV$sp$39.apply$mcV$sp(ReliableProxySpec.scala:292)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply$mcV$sp(ReliableProxySpec.scala:288)
[JVM-1]   ...
[JVM-1] [ERROR] [02/26/2015 08:36:18.495] [ReliableProxySpec-akka.actor.default-dispatcher-3] [akka://ReliableProxySpec/user/controller/barriers] RoleName(local) tried to enter 'after-each' while we were waiting for 'test7a' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier)
[JVM-1] [WARN] [02/26/2015 08:36:18.501] [ReliableProxySpec-akka.actor.default-dispatcher-14] [akka://ReliableProxySpec/user/controller/barriers] cannot remove RoleName(local): no client to remove
[JVM-2] - must stop proxy if target stops and no reconnection *** FAILED ***
[JVM-2]   java.lang.RuntimeException: barrier failed: test7a
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-2]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-2]   at akka.actor.FSM$class.processEvent(FSM.scala:621)
[JVM-2]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-2]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:752)
[JVM-2]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-2]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:615)
[JVM-2]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:609)
[JVM-2]   at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2109

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2012

**Comment by patriknw** [comment]
note that there was an attempt to re-enable the OSD daemons again on Feb 23

**Comment by rkuhn** [comment]
Are you implying that supernatural beings are messing with our CI builds? Spooky …

**Comment by bantonsson** [comment]
Failed again
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2120/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2121/consoleFull

No supernatural GC pauses in sight

**Comment by bantonsson** [comment]
And once more
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2132/consoleFull

**Comment by patriknw** [comment]
one more: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2154/consoleFull

**Comment by 2m** [comment]
One more: https://jenkins.akka.io:8498/job/akka-multi-node/997/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2205/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2215/consoleFull
