### ISSUE TITLE
FAILED: ClusterSingletonManager

### ISSUE THREAD

**Issue by 2m** [akka/akka#16948]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2058/

Multiple barrier failures starting with:

```
[JVM-3] - must startup 6 node cluster *** FAILED ***
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[JVM-3]   at scala.Predef$.assert(Predef.scala:165)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:438)
...
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2272/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3649/consoleFull
