### ISSUE TITLE
ClusterSingletonManger PostRestartException

### ISSUE THREAD

**Issue by patriknw** [akka/akka#17077]
if it is restarted during cluster shutdown:

    [first] akka.actor.PostRestartException: exception post restart (class akka.contrib.pattern.ClusterSingletonManagerIsStuck)
    [first]     at akka.actor.dungeon.FaultHandling$$anonfun$6.apply(FaultHandling.scala:249)
    [first]     at akka.actor.dungeon.FaultHandling$$anonfun$6.apply(FaultHandling.scala:247)
    [first]     at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:302)
    [first]     at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:297)
    [first]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
    [first]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
    [first]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
    [first]     at akka.actor.dungeon.FaultHandling$class.finishRecreate(FaultHandling.scala:247)
    [first]     at akka.actor.dungeon.FaultHandling$class.handleChildTerminated(FaultHandling.scala:290)
    [first]     at akka.actor.ActorCell.handleChildTerminated(ActorCell.scala:369)
    [first]     at akka.actor.dungeon.DeathWatch$class.watchedActorTerminated(DeathWatch.scala:63)
    [first]     at akka.actor.ActorCell.watchedActorTerminated(ActorCell.scala:369)
    [first]     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:455)
    [first]     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    [first]     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
    [first]     at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    [first]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
    [first]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    [first]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    [first]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    [first]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    [first]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    [first] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
    [first]     at scala.Predef$.require(Predef.scala:233)
    [first]     at akka.contrib.pattern.ClusterSingletonManager.preStart(ClusterSingletonManager.scala:394)
    [first]     at akka.actor.Actor$class.postRestart(Actor.scala:547)
    [first]     at akka.contrib.pattern.ClusterSingletonManager.postRestart(ClusterSingletonManager.scala:337)
    [first]     at akka.actor.Actor$class.aroundPostRestart(Actor.scala:485)
    [first]     at akka.contrib.pattern.ClusterSingletonManager.aroundPostRestart(ClusterSingletonManager.scala:337)
    [first]     at akka.actor.dungeon.FaultHandling$class.finishRecreate(FaultHandling.scala:238)
    [first]     ... 14 more

Harmless, but might cause confusion.

**Comment by patriknw** [comment]
Already fixed in https://github.com/akka/akka/commit/2a88f4fb2935d790f6c637be863cdb6287dc8c11#diff-f0ae95c926a050aecf45dba3e08d1c77R545

There can be a race between cluster shutdown and restart, but it is harmless anyway. If it fails to start it will be stopped.
