### ISSUE TITLE
FAILED: ResponseParserSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17199]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2311/consoleFull

```
[info] ResponseParserSpec:
[info] The response parsing logic should
[info]   properly parse
[info]   - a 200 response to a HEAD request *** FAILED *** (630 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$2.run(Interpreter.scala:394)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$2.progress(Interpreter.scala:392)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$unsafeFork(Interpreter.scala:594)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.pushAndFinish(Interpreter.scala:311)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.pushAndFinish(Interpreter.scala:417)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary.onPull(ActorInterpreter.scala:78)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary.onPull(ActorInterpreter.scala:25)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.run(Interpreter.scala:423)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.progress(Interpreter.scala:417)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPull(Stage.scala:73)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary.akka$stream$impl$fusing$ActorOutputBoundary$$tryPutBallIn(ActorInterpreter.scala:199)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary$$anonfun$downstreamRunning$1.applyOrElse(ActorInterpreter.scala:279)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a 204 response *** FAILED *** (31 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPull(Stage.scala:73)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary.akka$stream$impl$fusing$ActorOutputBoundary$$tryPutBallIn(ActorInterpreter.scala:199)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary$$anonfun$downstreamRunning$1.applyOrElse(ActorInterpreter.scala:279)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a response with a custom status code *** FAILED *** (32 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:141)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a response funky `Transfer-Encoding` header *** FAILED *** (38 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$2.run(Interpreter.scala:394)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$2.progress(Interpreter.scala:392)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$unsafeFork(Interpreter.scala:594)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.pushAndFinish(Interpreter.scala:311)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.pushAndFinish(Interpreter.scala:417)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary.onPull(ActorInterpreter.scala:78)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary.onPull(ActorInterpreter.scala:25)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.run(Interpreter.scala:423)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$3.progress(Interpreter.scala:417)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPull(Stage.scala:73)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary.akka$stream$impl$fusing$ActorOutputBoundary$$tryPutBallIn(ActorInterpreter.scala:199)
[info]     at akka.stream.impl.fusing.ActorOutputBoundary$$anonfun$downstreamRunning$1.applyOrElse(ActorInterpreter.scala:279)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a response with one header, a body, but no Content-Length header *** FAILED *** (75 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:141)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a response with one header, no body, and no Content-Length header *** FAILED *** (29 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:141)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a response with 3 headers, a body and remaining content *** FAILED *** (39 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:141)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   - a split response (parsed byte-by-byte) *** FAILED *** (42 milliseconds)
[info]     java.lang.UnsupportedOperationException: empty.head
[info]     at scala.collection.immutable.Vector.head(Vector.scala:192)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.http.util.package$SourceWithHeadAndTail$$anonfun$headAndTail$extension$1$$anonfun$apply$1.apply(package.scala:46)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:21)
[info]     at akka.stream.impl.fusing.Map.onPush(Ops.scala:20)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:387)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:214)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:385)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:530)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:210)
[info]     at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:605)
[info]     at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
[info]     at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:141)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
[info]     at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
[info]     at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
[info]     at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
[info]     at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
[info]     at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
[info]     at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
[info]     at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:328)
[info]     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[info]     at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[info]     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:221)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   properly parse a chunked
```

**Comment by ktoso** [comment]
Was a bug in my impl in https://github.com/akka/akka/pull/17196 not a spurious failure - closing.
