### ISSUE TITLE
fix open-coded spinlock in DirectByteBufferPool

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17216]
from Akara on the mailing list:
---
Scala 2.11.6, Akka 2.3.9, Spray 1.3.2.

When testing a particular workload, we ran into CPU spikes. The avg CPU load is less than 5% but about 6-7 minutes into the run, we start to see CPU spiking to near 100% lasting for several seconds. This repeats itself every 6-7 minutes. We can't correlate this with a particular GC activity just yet. We tested against Java 7_45 but tried Java 8 without much change.

Spray is configured on the default-dispatcher (Spray default).

Trying to capture thread dumps at the time spikes happening reveal 9 threads spinning on the followings:
~~~
"default-akka.actor.default-dispatcher-11" prio=10 tid=0x0000000001b2b800 nid=0x3752 runnable [0x00007f1191d40000]
   java.lang.Thread.State: RUNNABLE
	at akka.io.DirectByteBufferPool.takeBufferFromPool(DirectByteBufferPool.scala:41)
	at akka.io.DirectByteBufferPool.acquire(DirectByteBufferPool.scala:31)
	at akka.io.TcpConnection.doRead(TcpConnection.scala:231)
	at akka.io.TcpConnection$$anonfun$connected$1.applyOrElse(TcpConnection.scala:87)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
~~~
2 threads show this spinning:
~~~
"default-akka.actor.default-dispatcher-8" prio=10 tid=0x0000000001d6f000 nid=0x374f runnable [0x00007f11928d2000]
   java.lang.Thread.State: RUNNABLE
	at akka.io.DirectByteBufferPool.offerBufferToPool(DirectByteBufferPool.scala:66)
	at akka.io.DirectByteBufferPool.release(DirectByteBufferPool.scala:34)
	at akka.io.TcpConnection.doRead(TcpConnection.scala:245)
	at akka.io.TcpConnection$$anonfun$connected$1.applyOrElse(TcpConnection.scala:87)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
~~~
1 thread is on I/O:

~~~
"default-akka.actor.default-dispatcher-4" prio=10 tid=0x0000000001be2800 nid=0x36ff runnable [0x00007f11924b0000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:295)
	- locked <0x00000007d3b7e940> (a java.lang.Object)
	at akka.io.TcpConnection.innerRead$1(TcpConnection.scala:216)
	at akka.io.TcpConnection.doRead(TcpConnection.scala:232)
	at akka.io.TcpConnection$$anonfun$connected$1.applyOrElse(TcpConnection.scala:87)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:28)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
~~~

All in all, during this time there is no app logic being executed on the default dispatcher at all (12 threads on the default-dispatcher).

**Comment by rkuhn** [comment]
Discussion is [here](https://groups.google.com/d/msg/akka-user/dRxTX8WmWlA/jVf2uStTNS4J). Solution: remove the spinlock, either make it lock-free or use a proper lock. `synchronized` is the best option in the latter case, just FTR.

**Comment by ScrapCodes** [comment]
@rkuhn Can you also take the time to explain how synchronized is best option ?

**Comment by rkuhn** [comment]
Well, if you use a blocking lock then you’d better use the one that is the most heavily optimized, and especially since Java 7/8 `synchronized` has gotten some love. There is simply no reason to try and be clever because you won’t beat the JVM at its own game. If you need different semantics, though, the case is obviously different.

**Comment by ScrapCodes** [comment]
Thanks !, I suspected this.

**Comment by jrudolph** [comment]
Interesting. I ported the spinlock from spray.io's version of the buffer pool (which was introduced here: https://github.com/spray/spray/commit/b937111db5535e674e7631039641924e051e53ca). We have never seen such an effect in our benchmarks but as you say, @rkuhn, it probably depends on the actual scheduling behavior of the OS. Having a fat server with lots of cores probably will create the amount of contention which throws the system into this temporary gridlock we are seeing here.

Another thing to try (in addition to using a real lock or something lock-free) would be adding a thread local cache for buffers to try first before going to the shared pool to reduce contention (this is also what the JVM internal direct buffer pool is doing).

/cc @sirthias

**Comment by sirthias** [comment]
This is interesting.

@rkuhn's analysis from the mailing list:

> To the casual observer the code in DirectByteBufferPool looks like a CAS loop, but it actually is an open-coded primitive spinlock. If you have more threads competing for this lock than you have CPUs it might well happen that the kernel decides to schedule out a thread that was holding this lock, and since it is not a normal, honest lock, the kernel has no idea why the other threads now all are spinning like mad.

For my understanding: In what way does a "real" CAS loop differ from this "open-coded primitive spinlock"? I'm asking because I'd like to avoid introducing the same problem in other places and apparently haven't yet understood the core of the issue. Why isn't a CAS loop prone to the same problem?

**Comment by rkuhn** [comment]
@sirthias The difference is in what causes the spinning: if a certain state will always spin, you have a spin-lock. A proper CAS loop will only retry if someone changed the value during its execution, not if it is the fundamentally “wrong” value. Lock-free means that your progress does not depend on someone else making progress, but you may still be hindered by others continually making progress. Wait-free means that you will make progress independently of all other activity in the system.

**Comment by jrudolph** [comment]
I guess it depends on the actual amount of work done. The only thing you try to do during a CAS loop is actual switching the value (or noticing that you start condition was changed behind your back) which should just be a few CPU instructions.

**Comment by sirthias** [comment]
Ok, I see. Thanks!
So this issue is a general problem of all spinlocks.

The reason we went for the spinlock in the `DirectByteBufferPool` is that the amount of logic to be protected is very small and can likely be execute in a few cycles.
Fully blocking another thread, which is likely to be able to proceed only a few ns later, seemed like a bad tradeoff.
So the take-away is: never use spinlocks and got for a full `synchronized` instead?

**Comment by jrudolph** [comment]
Btw. AFAIK the JVM locking code will also spin for a while (also maybe depending on the profile for this lock)  before suspending the thread, so in the cases where it worked now it may still work with similar performance while in the cases of major contention threads will be properly suspended.

**Comment by sirthias** [comment]
@jrudolph Ok, that sounds good. I didn't know that. Do remember a pointer to some background material on that type of JVM optimizations?

**Comment by jrudolph** [comment]
Incidentally, in the context of spray we once discovered a similarly badly performing spinlock inside the linux kernel: the port allocator for local TCP ports for client sockets also uses a spin lock to guard the unused ports table. Once the table is almost empty (too many open connections to one host/port, a common scenario in a localhost load test) different threads trying to open new client sockets will start to busy-wait for ports coming available:

http://lists.openwall.net/netdev/2013/03/06/68

**Comment by hepin1989** [comment]
for the thread local cache,I think this one is nice to see
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/Recycler.java.
for the spin lock,the skynet https://github.com/cloudwu/skynet/ chagne the spin lock back to the synchronized in some commit.cause they say that ,on very high load the spin lock cause much CPU usage .

**Comment by sirthias** [comment]
If the JVM really performs the kind of lock profiling that @jrudolph described then I really see no reason to ever use a spinlock in JVM code.

**Comment by jrudolph** [comment]
@sirthias I tried to find something but it is hard to come up with information that is backed by authoritative sources from oracle/hotspot devs. 

Here's a summary from a blog (which probably simplifies things too much): http://slava-technical.blogspot.de/2011/04/how-does-jvm-handle-locks.html

Before Java 8 there was a flag "-XX:-UseSpinning" which according to some other site is automatically enabled starting from Java 8. 

Here are some infos from HotSpotInternals (but they don't mention spinning):

https://wikis.oracle.com/display/HotSpotInternals/Synchronization

Then there's this presentation from Dave Dice about Java 6 locking with information about Adaptive Spinning:

http://home.comcast.net/~pjbishop/Dave/MustangSync.pdf

**Comment by rkuhn** [comment]
The basic take-away is that a spinlock without a slow path (i.e. a plan B that does not spin) is viable only in kernel code, and even that is thwarted when running on virtualized hardware. Proper locks tell the kernel what they are waiting for when they back off, making it possible to react to the other thread releasing the resource, and also possibly boosting the other thread’s priority (although care needs to be taken to avoid priority inversion).

**Comment by sirthias** [comment]
Ok, thank you, @jrudolph and @rkuhn!

Since this is not the only spinlock that I have introduced into Akka we should also convert the other ones.
There is at least this one here:
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/AskSupport.scala#L266

Also, there is one in my current code for the HTTP connection pool, which I'll change as well.

**Comment by rkuhn** [comment]
Yes, I was going to suggest an audit as well.

**Comment by drewhk** [comment]
@mathias, here are additional information about JVM lock optimizations:

https://wiki.openjdk.java.net/display/HotSpot/Synchronization (lock biasing, etc)
http://www.oracle.com/technetwork/java/6-performance-137236.html#2.1.3 (mentions adaptive spinning, lock coarsening)

**Comment by drewhk** [comment]
Ah, @jrudolph was quicker :)

**Comment by sirthias** [comment]
Excellent. Thanks, Endre!

**Comment by patriknw** [comment]
don't close until its on all branches
