### ISSUE TITLE
FAILED: ConnectionPoolSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17284]
```
[info] ConnectionPoolSpec:
[info] The host-level client infrastructure
[info] - should automatically shutdown after configured timeout periods *** FAILED *** (2 seconds, 553 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [1500 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:107)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$8$$anon$12.<init>(ConnectionPoolSpec.scala:157)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$8.apply$mcV$sp(ConnectionPoolSpec.scala:150)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$8.apply(ConnectionPoolSpec.scala:150)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$8.apply(ConnectionPoolSpec.scala:150)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:55)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.stream.testkit.AkkaSpec.run(AkkaSpec.scala:55)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]   at sbt.TestRunner.run(TestFramework.scala:94)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFunction.apply(TestFramework.scala:224)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]   at sbt.Execute.work(Execute.scala:244)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:701)
[info] - should transparently restart after idle shutdown *** FAILED *** (1 second, 537 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [1500 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:107)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$9$$anon$13.<init>(ConnectionPoolSpec.scala:165)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$9.apply$mcV$sp(ConnectionPoolSpec.scala:160)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$9.apply(ConnectionPoolSpec.scala:160)
[info]   at akka.http.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$9.apply(ConnectionPoolSpec.scala:160)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:55)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.stream.testkit.AkkaSpec.run(AkkaSpec.scala:55)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:84)
[info]   at sbt.TestRunner.run(TestFramework.scala:94)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
[info]   at sbt.TestFunction.apply(TestFramework.scala:224)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:211)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:217)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[info]   at sbt.Execute.work(Execute.scala:244)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:701)
```

https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/2442/

**Comment by ktoso** [comment]
I noticed that it fails for me locally now... Investigating :-/

**Comment by ktoso** [comment]
Pretty sure that it's a rebase gone wrong, I'll fix it.

**Comment by ktoso** [comment]
I've tracked these failures to the change in `ActorPublisher` (that it now stops itself after completion)

**Comment by sirthias** [comment]
Ok. That's indeed something that might be interfering with the current impl.
I'm pretty sure that I can get this fixed tonight.
Should I give it a try, @ktoso? (Since you assigned yourself I don't want to interfere...)

**Comment by ktoso** [comment]
I have it "fixed" (or band-aided) by supplying `onComplete / onCompleteThenStop` etc. 
Did not dig into your implementation deep enough yet to see how to adjust it.

If you'd like to give it a shot with a proper fix that'd be great :) 
Let us know if that "stops after oncomplete" is too much of a limitation or not.

**Comment by sirthias** [comment]
> Let us know if that "stops after oncomplete" is too much of a limitation or not.

For this particular implementation it is, because the actor acts a publisher *as well as* subscriber for the same internal flow. So it signals `onComplete` to its (internal) downstream and then waits for the completion to appear on the other (ActorSubscriber) side that it also implements.
I think ideally there'd be a way for me to override the automatic stopping, if required.

**Comment by ktoso** [comment]
Maybe the separate methods are the way to go for now...? We need to re-think ActorPublisher and friends in depth anyway when we meet face to face next week (one of the meeting items).

**Comment by sirthias** [comment]
Yes, the `onComplete() / onCompleteThenStop()` separation should fix things for now. If you already have that working then I don't think another patch is required at this time.

**Comment by ktoso** [comment]
See: https://github.com/ktoso/akka/commit/5d2f0345882e450e67b5793d6cd48cc0e53c4dc9 in https://github.com/akka/akka/pull/17273/commits

**Comment by ktoso** [comment]
Pushed the solution we discussed (separate method for "do X and stop")
