### ISSUE TITLE
FAILED: SynchronousFileSourceSpec - too small timeout for jenkins

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17308]
Too small timeout for heavy IO I guess:

```
[info] File Source
[info] - must read contents from a file (340 milliseconds)
[info] - must complete only when all contents of a file have been signalled *** FAILED *** (3 seconds, 20 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.StreamTestKit$OnSubscribe
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:396)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectSubscription(StreamTestKit.scala:194)
[info]   at akka.stream.io.SynchronousFileSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8.apply(SynchronousFileSourceSpec.scala:120)
[info]   at akka.stream.io.SynchronousFileSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8.apply(SynchronousFileSourceSpec.scala:108)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:23)
[info]   at akka.stream.io.SynchronousFileSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(SynchronousFileSourceSpec.scala:108)
[info]   at akka.stream.io.SynchronousFileSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(SynchronousFileSourceSpec.scala:108)
[info]   at akka.stream.io.SynchronousFileSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(SynchronousFileSourceSpec.scala:108)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:55)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.stream.testkit.AkkaSpec.run(AkkaSpec.scala:55)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run.runTest(ForkMain.java:243)
[info]   at sbt.ForkMain$Run.runTestSafe(ForkMain.java:214)
[info]   at sbt.ForkMain$Run.runTests(ForkMain.java:190)
[info]   at sbt.ForkMain$Run.run(ForkMain.java:257)
[info]   at sbt.ForkMain.main(ForkMain.java:99)
```

**Comment by drewhk** [comment]
Hmm, this times out on expectSubscription.

**Comment by drewhk** [comment]
my dual SSD setup is probably not the best for debugging this :)

**Comment by drewhk** [comment]
@ktoso I think the issue could be that you prefetch from the file in preStart, and since that is a blocking operation, subscriptions can be delayed by the IO. I think we should only prefetch after we have a subscription.

**Comment by ktoso** [comment]
Agree, good idea to move the prefetch out of preStart directly

**Comment by ktoso** [comment]
I'll take this task a bit later then :)

**Comment by drewhk** [comment]
I took it, I just removed the prefetch from preStart(). That should be enough I think. The first request will kick-off everything automagically.

**Comment by drewhk** [comment]
but feel free to take a second look, I can drop my work (removing one line :))

**Comment by ktoso** [comment]
Cool, thanks!
