### ISSUE TITLE
FAILED failure while attaching new conductor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17317]
```
[info] * akka.remote.RemoteNodeDeathWatchSlow
[JVM-2] [INFO] [04/27/2015 01:13:31.327] [ScalaTest-main] [akka.remote.Remoting] Starting remoting
[JVM-2] [INFO] [04/27/2015 01:13:31.644] [ScalaTest-main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://RemoteNodeDeathWatchSpec@a5.local:57475]
[JVM-3] [INFO] [04/27/2015 01:13:34.928] [ScalaTest-main] [akka.remote.Remoting] Starting remoting
[JVM-3] [INFO] [04/27/2015 01:13:36.124] [ScalaTest-main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://RemoteNodeDeathWatchSpec@a6.local:36278]
[JVM-1] [INFO] [04/27/2015 01:13:39.020] [ScalaTest-main] [akka.remote.Remoting] Starting remoting
[JVM-1] [INFO] [04/27/2015 01:13:41.963] [ScalaTest-main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://RemoteNodeDeathWatchSpec@a0.local:54866]
[JVM-2] *** RUN ABORTED *** (11 seconds, 651 milliseconds)
[JVM-2]   java.lang.RuntimeException: failure while attaching new conductor
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.attachConductor(MultiNodeSpec.scala:387)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:392)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:252)
[JVM-2]   at akka.remote.RemoteNodeDeathWatchSpec.<init>(RemoteNodeDeathWatchSpec.scala:79)
[JVM-2]   at akka.remote.RemoteNodeDeathWatchSlowSpec.<init>(RemoteNodeDeathWatchSpec.scala:73)
[JVM-2]   at akka.remote.RemoteNodeDeathWatchSlowMultiJvmNode2.<init>(RemoteNodeDeathWatchSpec.scala:71)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[JVM-2]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-2]   at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
[JVM-2]   at java.lang.Class.newInstance(Class.java:379)
[JVM-2]   at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:2644)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2461)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2460)
[JVM-2]   at scala.collection.immutable.List.map(List.scala:273)
[JVM-2]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2460)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[JVM-2]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[JVM-2]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[JVM-2]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
[JVM-2]   at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-2]   Cause: java.lang.RuntimeException: unexpected transition: Transition(Actor[akka://RemoteNodeDeathWatchSpec/user/TestConductorClient#-1349795305],Connecting,Failed)
[JVM-2]   at akka.remote.testconductor.Player$$anonfun$6$$anon$1$$anonfun$receive$1.applyOrElse(Player.scala:65)
[JVM-2]   at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
[JVM-2]   at akka.remote.testconductor.Player$$anonfun$6$$anon$1.aroundReceive(Player.scala:56)
[JVM-2]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
[JVM-2]   at akka.actor.ActorCell.invoke(ActorCell.scala:487)
[JVM-2]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-2]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-2]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
some kind of ConnectionFailure, probably not a real problem, close if it does not happen again within one month

**Comment by drewhk** [comment]
I have seen these a couple of times

**Comment by patriknw** [comment]
we have seen this again, several times

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2549/consoleFull

ran on a0 (not multi-node)

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/100/consoleFull
a0

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2837/consoleFull
a3

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/104/consoleFull
a0

**Comment by patriknw** [comment]
In one case (with -XX:ReservedCodeCacheSize=256m) the JVM1 "Starting remoting" log entry was much later (8 seconds) than JVM2 and JVM3.

In another case (but that was with -XX:ReservedCodeCacheSize=128m):

    [JVM-1] [ERROR] [08/31/2015 00:04:40.038] [ScalaTest-main] [akka.remote.Remoting] Remoting error: [Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.] [
    [JVM-1] akka.remote.RemoteTransportException: Startup timed out. This is usually related to actor system host setting or host name resolution misconfiguration.
    [JVM-1]     at akka.remote.Remoting.akka$remote$Remoting$$notifyError(Remoting.scala:136)
    [JVM-1]     at akka.remote.Remoting.start(Remoting.scala:198)
    [JVM-1]     at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:184)
    [JVM-1]     at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:663)
