### ISSUE TITLE
Akka HTTP client (streams and HTTP 1.0-RC1) fails on literal IPv6 addresses

### ISSUE THREAD

**Issue by reavowed** [akka/akka#17404]
The following code throws an exception:
```scala
implicit val system = ActorSystem()
implicit val materializer = ActorFlowMaterializer()

val bindingFuture = Http(system)
  .bind(interface = "0.0.0.0", port = 80)
  .to(Sink.foreach { _ handleWithSyncHandler { _ => HttpResponse() } })
  .run()

Await.result(bindingFuture, Duration.Inf)

val request = HttpRequest(uri = "http://[::1]:80")
val responseFuture = Http().singleRequest(request)

Await.result(responseFuture, Duration.Inf)
```
The exception details are as follows:
```
akka.http.scaladsl.model.IllegalUriException: Illegal URI host: Invalid input ':', expected '.', lower-reg-name-char, UPPER_ALPHA, '%' or 'EOI' (line 1, column 2): 0:0:0:0:0:0:0:1
 ^
	at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40)
	at akka.http.scaladsl.model.Uri$.fail(Uri.scala:748)
	at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:61)
	at akka.http.impl.model.parser.UriParser.parseHost(UriParser.scala:51)
	at akka.http.scaladsl.model.Uri$Host$.apply(Uri.scala:350)
	at akka.http.scaladsl.model.headers.Host$.apply(headers.scala:95)
	at akka.http.scaladsl.model.headers.Host$.apply(headers.scala:93)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.renderHeaders$1(HttpRequestRendererFactory.scala:96)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.onPush(HttpRequestRendererFactory.scala:125)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.onPush(HttpRequestRendererFactory.scala:28)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:390)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:216)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:388)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:533)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:212)
	at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:608)
	at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:63)
	at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:147)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:339)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
	at akka.dispatch.Mailbox.run(Mailbox.scala:221)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
```
The exception can be fixed by changing the HttpRequest construction to the following:
```scala
val request = HttpRequest(uri = "http://[::1]:80", headers = Host("[::1]") :: Nil)
```
The issue appears to be in HttpRequestRenderer where it fills in a default Host header for the request. It fetches the value from RequestRenderingContext.serverAddress, which is an InetSocketAddress wrapping an Inet6Address. Calling Inet6Address.getHostName() returns the raw IPv6 address (e.g. "0:0:0:0:0:0:0:1"), whereas UriParser.parseHost expects it to be wrapped in square brackets.

**Comment by jrudolph** [comment]
Thanks for the report and the analysis, @reavowed. You are right this seems like a bug that we need to fix.

/cc @sirthias
