### ISSUE TITLE
CircuitBreaker throws IllegalStateException

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#17415]
from #16327:
~~~
2015-04-27 14:06:06.498502500 [incident-daemon-system-akka.actor.default-dispatcher-35] ERROR akka.dispatch.Dispatcher - exception in sameThreadExecution
Context (a.d.Dispatcher)
2015-04-27 14:06:06.498504500 java.lang.IllegalStateException: Illegal transition attempted from: Closed with failure count = 10 to Open
2015-04-27 14:06:06.498505500   at akka.pattern.CircuitBreaker.transition(CircuitBreaker.scala:229)
2015-04-27 14:06:06.498506500   at akka.pattern.CircuitBreaker.akka$pattern$CircuitBreaker$$tripBreaker(CircuitBreaker.scala:236) 2015-04-27 14:06:06.498524500     at akka.pattern.CircuitBreaker$Closed$.callFails(CircuitBreaker.scala:369) 
2015-04-27 14:06:06.498525500   at akka.pattern.CircuitBreaker$State$$anonfun$callThrough$1.apply(CircuitBreaker.scala:299) 
2015-04-27 14:06:06.498526500   at akka.pattern.CircuitBreaker$State$$anonfun$callThrough$1.apply(CircuitBreaker.scala:297) 
2015-04-27 14:06:06.498529500   ... 25 common frames omitted
2015-04-27 14:06:06.498529500 Wrapped by: java.lang.IllegalStateException: exception in sameThreadExecutionContext
2015-04-27 14:06:06.498530500   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:77) 
2015-04-27 14:06:06.498535500   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) 
2015-04-27 14:06:06.498535500   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) 
2015-04-27 14:06:06.498536500   at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73) 
2015-04-27 14:06:06.498539500   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74) 
2015-04-27 14:06:06.498539500   at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:120) 
2015-04-27 14:06:06.498540500   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:73) 
2015-04-27 14:06:06.498543500   ... 19 common frames omitted
2015-04-27 14:06:06.498543500 Wrapped by: java.lang.IllegalStateException: exception in sameThreadExecutionContext
2015-04-27 14:06:06.498544500   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.reportFailure(Future.scala:77) 
2015-04-27 14:06:06.498544500   at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) 
2015-04-27 14:06:06.498548500   at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) 
2015-04-27 14:06:06.498549500   at scala.concurrent.Promise$class.complete(Promise.scala:55) 
2015-04-27 14:06:06.498550500   at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) 
2015-04-27 14:06:06.498550500   at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) 
2015-04-27 14:06:06.498553500   at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) 
2015-04-27 14:06:06.498554500   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) 
2015-04-27 14:06:06.498554500   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) 
2015-04-27 14:06:06.498555500   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:90) 
2015-04-27 14:06:06.498565500   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88) 
2015-04-27 14:06:06.498566500   at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88)
2015-04-27 14:06:06.498572500   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) 
2015-04-27 14:06:06.498573500   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:88)
2015-04-27 14:06:06.498573500   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) 
2015-04-27 14:06:06.498576500   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)2015-04-27 14:06:06.498577500  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
2015-04-27 14:06:06.498577500   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 
2015-04-27 14:06:06.498580500   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
2015-04-27 14:06:06.498581500   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
~~~

**Comment by maxcom** [comment]
Problem happens in large batch process after some number of application level exceptions that opens circuit breaker. That exceptions are caused by overload of external service.

Here is source code of actor that uses CircuitBreaker: https://gist.github.com/maxcom/1d06b2cc4f5c604d568e

**Comment by maxcom** [comment]
I reproduced this problem in separate test program, I'll post it to github in an hour.

**Comment by maxcom** [comment]
Here is test program: https://github.com/maxcom/circuit-breaker-stress-test/blob/master/src/main/scala/com/example/ApplicationMain.scala

Clone https://github.com/maxcom/circuit-breaker-stress-test/ and run `sbt run` there to run it.

**Comment by patriknw** [comment]
Thanks for the reproducer. I can confirm that it fails for 2.3.7-2.3.10 and 2.3-SNAPSHOT (release-2.3 branch).
