### ISSUE TITLE
FAILED: SynchronousFilePublisherTest TCK

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17564]
```
info] - required_createPublisher1MustProduceAStreamOfExactly1Element *** FAILED ***
[info]   java.lang.AssertionError: Publisher akka.stream.impl.VirtualPublisher@5543ab1 produced no elements expected:<true> but was:<false>
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.testng.Assert.failNotEquals(Assert.java:480)
[info]   at org.testng.Assert.assertTrue(Assert.java:37)
[info]   at org.reactivestreams.tck.PublisherVerification$1.run(PublisherVerification.java:152)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   at org.reactivestreams.tck.PublisherVerification.required_createPublisher1MustProduceAStreamOfExactly1Element(PublisherVerification.java:148)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:483)
[info]   at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
[info]   at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
[info]   at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
[info]   at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
[info]   at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[info]   at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
[info]   at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
[info]   at org.testng.TestRunner.privateRun(TestRunner.java:749)
[info]   at org.testng.TestRunner.run(TestRunner.java:600)
[info]   at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
[info]   at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
[info]   at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
```

**Comment by ktoso** [comment]
On second thought this may have been due to the issues Bjorn found on a0 today - this failed on a0. Closing for now, reopen if happens again.
