### ISSUE TITLE
FAILED: akka.contrib.pattern.ReliableProxy

### ISSUE THREAD

**Issue by 2m** [akka/akka#17599]
When validating https://github.com/akka/akka/pull/17532

```
[info] * akka.contrib.pattern.ReliableProxy
[JVM-2] 0.098: [GC (Allocation Failure) [PSYoungGen: 512K->480K(1024K)] 512K->496K(65024K), 0.0045641 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[JVM-2] 0.129: [GC (Allocation Failure) [PSYoungGen: 991K->496K(1536K)] 1007K->578K(65536K), 0.0083455 secs] [Times: user=0.03 sys=0.00, real=0.00 secs] 
[JVM-2] 0.177: [GC (Allocation Failure) [PSYoungGen: 1520K->505K(1536K)] 1602K->895K(65536K), 0.0053332 secs] [Times: user=0.02 sys=0.01, real=0.01 secs] 
[JVM-2] 0.215: [GC (Allocation Failure) [PSYoungGen: 1529K->492K(2560K)] 1919K->1128K(66560K), 0.0023678 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[JVM-2] 0.283: [GC (Allocation Failure) [PSYoungGen: 2540K->496K(2560K)] 3176K->1661K(66560K), 0.0031861 secs] [Times: user=0.01 sys=0.00, real=0.01 secs] 
[JVM-2] 0.348: [GC (Allocation Failure) [PSYoungGen: 2544K->1203K(5632K)] 3709K->2376K(69632K), 0.0135185 secs] [Times: user=0.09 sys=0.03, real=0.01 secs] 
[JVM-1] 0.399: [GC (Allocation Failure) [PSYoungGen: 512K->512K(1024K)] 512K->528K(65024K), 0.0537597 secs] [Times: user=0.88 sys=0.02, real=0.05 secs] 
[JVM-1] 0.479: [GC (Allocation Failure) [PSYoungGen: 1024K->496K(1536K)] 1040K->722K(65536K), 0.0033751 secs] [Times: user=0.02 sys=0.00, real=0.00 secs] 
[JVM-2] 0.484: [GC (Allocation Failure) [PSYoungGen: 5299K->1332K(5632K)] 6472K->2841K(69632K), 0.0057262 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[JVM-1] 0.522: [GC (Allocation Failure) [PSYoungGen: 1516K->508K(1536K)] 1743K->1022K(65536K), 0.0041492 secs] [Times: user=0.01 sys=0.01, real=0.01 secs] 
[JVM-1] 0.558: [GC (Allocation Failure) [PSYoungGen: 1532K->512K(2560K)] 2045K->1318K(66560K), 0.0054290 secs] [Times: user=0.02 sys=0.00, real=0.00 secs] 
[JVM-2] 0.607: [GC (Allocation Failure) [PSYoungGen: 5406K->1455K(9216K)] 6916K->3013K(73216K), 0.0041148 secs] [Times: user=0.01 sys=0.01, real=0.00 secs] 
[JVM-1] 0.627: [GC (Allocation Failure) [PSYoungGen: 2560K->512K(2560K)] 3366K->1959K(66560K), 0.0048567 secs] [Times: user=0.05 sys=0.00, real=0.00 secs] 
[JVM-2] 0.851: [GC (Allocation Failure) [PSYoungGen: 9135K->1877K(9728K)] 10693K->3530K(73728K), 0.0044218 secs] [Times: user=0.01 sys=0.01, real=0.00 secs] 
[JVM-1] 0.690: [GC (Allocation Failure) [PSYoungGen: 2560K->1521K(5120K)] 4007K->3178K(69120K), 0.1775707 secs] [Times: user=3.20 sys=1.19, real=0.18 secs] 
[JVM-1] 0.975: [GC (Allocation Failure) [PSYoungGen: 5105K->1640K(5632K)] 6762K->3649K(69632K), 0.0044195 secs] [Times: user=0.02 sys=0.00, real=0.00 secs] 
[JVM-2] 1.104: [GC (Allocation Failure) [PSYoungGen: 9557K->2032K(13312K)] 11210K->4663K(77312K), 0.0300677 secs] [Times: user=0.11 sys=0.05, real=0.03 secs] 
[JVM-1] 1.061: [GC (Allocation Failure) [PSYoungGen: 5191K->2025K(8704K)] 7200K->4155K(72704K), 0.2493422 secs] [Times: user=7.07 sys=0.44, real=0.25 secs] 
[JVM-2] 1.414: [GC (Allocation Failure) [PSYoungGen: 13284K->3046K(14336K)] 15914K->6664K(78336K), 0.0073148 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[JVM-1] 1.513: [GC (Allocation Failure) [PSYoungGen: 8681K->2544K(9216K)] 10811K->4841K(73216K), 0.0129993 secs] [Times: user=0.18 sys=0.01, real=0.01 secs] 
[JVM-2] [WARN] [05/28/2015 12:00:23.200] [ReliableProxySpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://ReliableProxySpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.
[JVM-2] 1.711: [GC (Allocation Failure) [PSYoungGen: 14306K->3190K(21504K)] 17924K->7458K(85504K), 0.0162669 secs] [Times: user=0.06 sys=0.02, real=0.02 secs] 
[JVM-1] 1.764: [GC (Allocation Failure) [PSYoungGen: 9200K->2567K(13824K)] 11497K->5257K(77824K), 0.2663578 secs] [Times: user=4.57 sys=2.58, real=0.27 secs] 
[JVM-1] 2.305: [GC (Allocation Failure) [PSYoungGen: 13319K->3059K(13824K)] 16009K->7088K(77824K), 0.0162766 secs] [Times: user=0.25 sys=0.01, real=0.02 secs] 
[JVM-1] [WARN] [05/28/2015 12:00:24.166] [ReliableProxySpec-akka.actor.default-dispatcher-4] [akka.remote.transport.FailureInjectorTransportAdapter(akka://ReliableProxySpec)] FailureInjectorTransport is active on this system. Gremlins might munch your packets.
[JVM-1] 2.580: [GC (Allocation Failure) [PSYoungGen: 13795K->3559K(20992K)] 17824K->8357K(84992K), 0.8841529 secs] [Times: user=17.45 sys=4.83, real=0.88 secs] 
[JVM-2] Run starting. Expected test count is: 9
[JVM-2] ReliableProxyMultiJvmNode2:
[JVM-2] A ReliableProxy
[JVM-1] 3.912: [GC (Allocation Failure) [PSYoungGen: 20455K->4606K(21504K)] 25253K->11007K(85504K), 1.1503249 secs] [Times: user=8.14 sys=7.96, real=1.15 secs] 
[JVM-1] Run starting. Expected test count is: 9
[JVM-1] ReliableProxyMultiJvmNode1:
[JVM-1] A ReliableProxy
[JVM-2] 5.309: [GC (Allocation Failure) [PSYoungGen: 21110K->4078K(22016K)] 25378K->10044K(86016K), 0.0275196 secs] [Times: user=0.15 sys=0.04, real=0.02 secs] 
[JVM-1] - must initialize properly
[JVM-2] - must initialize properly
[JVM-1] 5.700: [GC (Allocation Failure) [PSYoungGen: 21502K->4040K(33280K)] 27903K->11500K(97280K), 0.8754320 secs] [Times: user=0.18 sys=5.36, real=0.88 secs] 
[JVM-2] 6.717: [GC (Allocation Failure) [PSYoungGen: 21998K->1842K(33280K)] 27964K->8831K(97280K), 0.0243961 secs] [Times: user=0.09 sys=0.06, real=0.03 secs] 
[JVM-1] - must forward messages in sequence
[JVM-2] - must forward messages in sequence
[JVM-2] - must retry when sending fails
[JVM-1] - must retry when sending fails
[JVM-1] 8.437: [GC (Allocation Failure) [PSYoungGen: 31176K->1088K(33280K)] 38636K->9451K(97280K), 0.6068480 secs] [Times: user=4.06 sys=1.77, real=0.60 secs] 
[JVM-2] - must retry when receiving fails *** FAILED ***
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (4820403 nanoseconds) during expectMsg while waiting for 90
[JVM-2]   at scala.Predef$.assert(Predef.scala:165)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$expectN$1.apply$mcVI$sp(ReliableProxySpec.scala:73)
[JVM-2]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec.expectN(ReliableProxySpec.scala:73)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$20$$anonfun$apply$mcV$sp$21.apply$mcV$sp(ReliableProxySpec.scala:178)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$20$$anonfun$apply$mcV$sp$21.apply(ReliableProxySpec.scala:178)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$20$$anonfun$apply$mcV$sp$21.apply(ReliableProxySpec.scala:178)
[JVM-2]   ...
[JVM-2] 9.175: [GC (Allocation Failure) [PSYoungGen: 30514K->416K(33792K)] 37503K->7796K(97792K), 0.0034346 secs] [Times: user=0.02 sys=0.00, real=0.01 secs] 
[JVM-1] [ERROR] [05/28/2015 12:00:31.030] [ReliableProxySpec-akka.actor.default-dispatcher-4] [akka://ReliableProxySpec/user/controller/barriers] RoleName(local) tried to enter 'test3a' while we were waiting for 'after-each' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier)
[JVM-1] - must retry when receiving fails *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: test3a
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:652)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:788)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:646)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:640)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
[JVM-1]   ...
[JVM-1] [WARN] [05/28/2015 12:00:31.057] [ReliableProxySpec-akka.actor.default-dispatcher-2] [akka://ReliableProxySpec/user/controller/barriers] cannot remove RoleName(local): no client to remove
[JVM-1] [ERROR] [05/28/2015 12:00:31.093] [ReliableProxySpec-akka.remote.default-remote-dispatcher-5] [akka.trttl.gremlin.tcp://ReliableProxySpec@a0.moxie:41115/system/endpointManager/reliableEndpointWriter-akka.trttl.gremlin.tcp%3A%2F%2FReliableProxySpec%40a5.moxie%3A42938-0/endpointWriter] AssociationError [akka.trttl.gremlin.tcp://ReliableProxySpec@a0.moxie:41115] -> [akka.trttl.gremlin.tcp://ReliableProxySpec@a5.moxie:42938]: Error [Shut down address: akka.trttl.gremlin.tcp://ReliableProxySpec@a5.moxie:42938] [
[JVM-1] akka.remote.ShutDownAssociation: Shut down address: akka.trttl.gremlin.tcp://ReliableProxySpec@a5.moxie:42938
[JVM-1] Caused by: akka.remote.transport.Transport$InvalidAssociationException: The remote system terminated the association because it is shutting down.
[JVM-1] ]
[JVM-2] Exception encountered when invoking run on a nested suite - barrier failed: after-each *** ABORTED ***
[JVM-2]   java.lang.RuntimeException: barrier failed: after-each
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-2]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-2]   at akka.actor.FSM$class.processEvent(FSM.scala:652)
[JVM-2]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-2]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:788)
[JVM-2]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-2]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:646)
[JVM-2]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:640)
[JVM-2]   at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
[JVM-2]   ...
[JVM-2] Run completed in 8 seconds, 985 milliseconds.
[JVM-2] Total number of tests run: 4
[JVM-2] Suites: completed 0, aborted 1
[JVM-2] Tests: succeeded 3, failed 1, canceled 0, ignored 0, pending 0
[JVM-2] *** 1 SUITE ABORTED ***
[JVM-2] *** 1 TEST FAILED ***
[JVM-1] [WARN] [05/28/2015 12:00:31.161] [ReliableProxySpec-akka.actor.default-dispatcher-14] [akka://ReliableProxySpec/user/controller/10.0.1.230:55324-server1] received dead letter from Actor[akka://ReliableProxySpec/deadLetters]: ClientDisconnected
[JVM-2] Heap
[JVM-2]  PSYoungGen      total 33792K, used 19121K [0x00000000fd580000, 0x0000000100000000, 0x0000000100000000)
[JVM-2]   eden space 28672K, 65% used [0x00000000fd580000,0x00000000fe7c4590,0x00000000ff180000)
[JVM-2]   from space 5120K, 8% used [0x00000000ff180000,0x00000000ff1e8000,0x00000000ff680000)
[JVM-2]   to   space 5120K, 0% used [0x00000000ffb00000,0x00000000ffb00000,0x0000000100000000)
[JVM-2]  ParOldGen       total 64000K, used 7380K [0x00000000f8000000, 0x00000000fbe80000, 0x00000000fd580000)
[JVM-2]   object space 64000K, 11% used [0x00000000f8000000,0x00000000f87353d8,0x00000000fbe80000)
[JVM-2]  Metaspace       used 24755K, capacity 25016K, committed 25344K, reserved 1071104K
[JVM-2]   class space    used 3654K, capacity 3742K, committed 3840K, reserved 1048576K
[JVM-1] Exception encountered when invoking run on a nested suite - barrier failed: after-each *** ABORTED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-each
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:211)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:186)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:652)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:147)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:788)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:147)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:646)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:640)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
[JVM-1]   ...
[JVM-1] Run completed in 8 seconds, 606 milliseconds.
[JVM-1] Total number of tests run: 4
[JVM-1] Suites: completed 0, aborted 1
[JVM-1] Tests: succeeded 3, failed 1, canceled 0, ignored 0, pending 0
[JVM-1] *** 1 SUITE ABORTED ***
[JVM-1] *** 1 TEST FAILED ***
[JVM-1] Heap
[JVM-1]  PSYoungGen      total 33280K, used 14941K [0x00000000fd580000, 0x0000000100000000, 0x0000000100000000)
[JVM-1]   eden space 27136K, 51% used [0x00000000fd580000,0x00000000fe3076a0,0x00000000ff000000)
[JVM-1]   from space 6144K, 17% used [0x00000000ff000000,0x00000000ff110010,0x00000000ff600000)
[JVM-1]   to   space 6144K, 0% used [0x00000000ffa00000,0x00000000ffa00000,0x0000000100000000)
[JVM-1]  ParOldGen       total 64000K, used 8363K [0x00000000f8000000, 0x00000000fbe80000, 0x00000000fd580000)
[JVM-1]   object space 64000K, 13% used [0x00000000f8000000,0x00000000f882aee8,0x00000000fbe80000)
[JVM-1]  Metaspace       used 25737K, capacity 26088K, committed 26240K, reserved 1071104K
[JVM-1]   class space    used 3821K, capacity 3910K, committed 3968K, reserved 1048576K
[error] Failed: akka.contrib.pattern.ReliableProxyMultiJvmNode1
[error] Failed: akka.contrib.pattern.ReliableProxyMultiJvmNode2
```

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2766/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2295/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2771/consoleFull

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
