### ISSUE TITLE
Akka HTTP Client Connection-level (1.0-RC3) fails the documentation code example

### ISSUE THREAD

**Issue by pjan** [akka/akka#17600]
The code given in the documentation [here](http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC3/scala/http/client-side/connection-level.html) throws an exception:

```scala
import scala.concurrent.Future
import akka.stream.ActorFlowMaterializer
import akka.stream.scaladsl._
import akka.http.scaladsl.model._
import akka.http.scaladsl.Http
 
implicit val system = ActorSystem()
implicit val materializer = ActorFlowMaterializer()
 
val connectionFlow: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] =
  Http().outgoingConnection("http://akka.io")
val responseFuture: Future[HttpResponse] =
  Source.single(HttpRequest(uri = "/"))
    .via(connectionFlow)
    .runWith(Sink.head)
```

The exception details and trace are as follows:

```
[ERROR] [05/28/2015 23:34:30.669] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Outgoing request stream error
akka.http.scaladsl.model.IllegalUriException: Illegal URI host: Invalid input ':', expected lower-reg-name-char, UPPER_ALPHA, '%' or 'EOI' (line 1, column 5): http://akka.io
    ^
	at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40)
	at akka.http.scaladsl.model.Uri$.fail(Uri.scala:748)
	at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:61)
	at akka.http.impl.model.parser.UriParser.parseHost(UriParser.scala:51)
	at akka.http.scaladsl.model.Uri$Host$.apply(Uri.scala:350)
	at akka.http.scaladsl.model.headers.Host$.apply(headers.scala:95)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.renderHeaders$1(HttpRequestRendererFactory.scala:110)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.onPush(HttpRequestRendererFactory.scala:139)
	at akka.http.impl.engine.rendering.HttpRequestRendererFactory$HttpRequestRenderer.onPush(HttpRequestRendererFactory.scala:42)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.run(Interpreter.scala:436)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.progress(Interpreter.scala:245)
	at akka.stream.impl.fusing.OneBoundedInterpreter$$anon$1.progress(Interpreter.scala:434)
	at akka.stream.impl.fusing.OneBoundedInterpreter.akka$stream$impl$fusing$OneBoundedInterpreter$$execute(Interpreter.scala:580)
	at akka.stream.impl.fusing.OneBoundedInterpreter$State$class.execute(Interpreter.scala:241)
	at akka.stream.impl.fusing.OneBoundedInterpreter$EntryState.execute(Interpreter.scala:666)
	at akka.stream.stage.AbstractStage.enterAndPush(Stage.scala:64)
	at akka.stream.impl.fusing.BatchingActorInputBoundary$$anonfun$upstreamRunning$1.applyOrElse(ActorInterpreter.scala:143)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorInterpreter.aroundReceive(ActorInterpreter.scala:352)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by drewhk** [comment]
Thanks for reporting!

/cc @jrudolph @sirthias

**Comment by jrudolph** [comment]
This fails even when fixed (i.e. using the correct `Http().outgoingConnection("akka.io")`) because the request sent by akka-http looks like this:

```
GET / HTTP/1.1
Host: akka.io:80
User-Agent: akka-http/2.3.11
```

which is answered by github aka akka.io as

```
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Thu, 28 May 2015 16:34:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 9116
ETag: "5519ee21-239c"
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'

[...]
```

Sending a `Host: akka.io:80` header isn't illegal AFAIR but I remember that we discussed this in the context of spray before and IIRC spray doesn't render the port if it's the standard one.

**Comment by jrudolph** [comment]
It seems it's the same behavior as in spray at least when managing a connection manually.

**Comment by jrudolph** [comment]
I created #17656 to track the improvement not to add default ports to the Host header.

**Comment by kolotyluk** [comment]
I am still getting
`
akka.http.scaladsl.model.IllegalUriException: Illegal URI host: Invalid input ':', expected lower-reg-name-char, UPPER_ALPHA, pct-encoded or 'EOI' (line 1, column 5): http://geoip.nekudo.com
`
Even though I am using akka-http-core-experimental_2.11 v 2.0.4.

**Comment by ktoso** [comment]
Works on Akka 2.4.3 (on which Akka HTTP is no longer experimental). In general I'd strongly suggest upgrading to Akka 2.4 (along with streams/http) by the way – would you be able to do that?

**Comment by kolotyluk** [comment]
I am trying the micro service example from Activator, which is using Akka 2.4.1... I'll try fussing with the build.sbt a little more...

**Comment by ktoso** [comment]
Which Activator template specifically? If ours we should upgrade it, and if not, we should ask the maintainer to upgrade it :)

**Comment by kolotyluk** [comment]
akka-http-microservice - whatever came when I installed activator a week ago

**Comment by kolotyluk** [comment]
Do you have an example build.sbt I can follow. I tried bumping the akkaV to 2.4.3, but same problem. The other coordinates may still need changing.

**Comment by ktoso** [comment]
Now I'm rather confused, the build of the project you mention is already updated to Akka 2.4: https://github.com/theiterators/akka-http-microservice/blob/master/build.sbt
You also mention usage of ` akka-http-core-experimental_2.11 v 2.0.4` which is a bit weird, Akka 2.4.2+ comes with `akka-http-core_2.11 v 2.4.2+`, please make sure your build looks like the linked one (well it could use 2.4.3 already_

**Comment by kolotyluk** [comment]
Here is what I have now...
`
   libraryDependencies ++= {
   
     val akkaV       = "2.4.3"
     //val akkaStreamV = "2.0.1"
     val akkaStreamV = "2.0.4"
     val scalaTestV  = "2.2.5"
     Seq(
       "com.typesafe.akka" %% "akka-actor"                           % akkaV,
       "com.typesafe.akka" %% "akka-stream-experimental"             % akkaStreamV,
       "com.typesafe.akka" %% "akka-http-core-experimental"          % akkaStreamV,
       "com.typesafe.akka" %% "akka-http-experimental"               % akkaStreamV,
       "com.typesafe.akka" %% "akka-http-spray-json-experimental"    % akkaStreamV,
       "com.typesafe.akka" %% "akka-http-testkit-experimental"       % akkaStreamV,
       "org.scalatest"     %% "scalatest"                            % scalaTestV % "test"
     )
   }
`

**Comment by kolotyluk** [comment]
I am just using the template that came with activator. I can't really say much more than that.

**Comment by ktoso** [comment]
I see, I'll ping the guys maintaining the repo to update it in Activator, in the mean time have a look at he build file I linked and try that (http-core is no longer experimental, use version 2.4.3 there).

**Comment by kolotyluk** [comment]
Ok, I rebuilt my project with the coordinates you gave me, but I am still getting the same error.

As an aside, I had to reboot my mac twice because activator hosed my system badly.

**Comment by kolotyluk** [comment]
enablePlugins(JavaAppPackaging)

    name         := """akka-http-microservice"""
    organization := "com.theiterators"
    version      := "1.0"
    scalaVersion := "2.11.7"

    scalacOptions := Seq("-unchecked", "-deprecation", "-encoding", "utf8")

    libraryDependencies ++= {
      val akkaV       = "2.4.3"
      val scalaTestV  = "2.2.5"
      Seq(
        "com.typesafe.akka" %% "akka-actor"                           % akkaV,
        "com.typesafe.akka" %% "akka-stream"                          % akkaV,
        "com.typesafe.akka" %% "akka-http-experimental"               % akkaV,
        "com.typesafe.akka" %% "akka-http-spray-json-experimental"    % akkaV,
        "com.typesafe.akka" %% "akka-http-testkit"                    % akkaV,
        "org.scalatest"     %% "scalatest"                            % scalaTestV % "test"
      )
    }
    
    Revolver.settings
    
    
    fork in run := true

**Comment by kolotyluk** [comment]
Also, the template uses freegeopio.net, which no longer seems to work, so I have been trying to get it working with geopip.nekudo.com

**Comment by ktoso** [comment]
The guys bumped the dependencies btw https://github.com/theiterators/akka-http-microservice/issues/20#event-625655956 you can now create the activator template anew

**Comment by kolotyluk** [comment]
OK, problem solved. I had configured 
    services {
      // freeGeoIpHost = "freegeoip.net"
      freeGeoIpHost = "http://geoip.nekudo.com"
      freeGeoIpPort = 80
    }
instead of
    services {
      // freeGeoIpHost = "freegeoip.net"
      freeGeoIpHost = "geoip.nekudo.com"
      freeGeoIpPort = 80
    }
Is it possible to make the diagnostics a little more clear in this case?

**Comment by DSRYhh** [comment]
`host` shouldn't include `http://`. `http` is called `scheme`
See [The URI model](http://doc.akka.io/docs/akka-http/10.0.8/scala/http/common/uri-model.html#parsing-a-uri-string) for more details
