### ISSUE TITLE
ReceivePipeline can cause MatchError in decorated actor

### ISSUE THREAD

**Issue by jeremystone** [akka/akka#17670]
If an interceptor using the ReceivePipeline pattern directly calls its inner Receive's apply method with a (possible transformed) message, but the actor that finally receives the message does not handle it, a MatchError can be thrown.

For example, the following:
```scala
import akka.actor._
import akka.contrib.pattern._

implicit val system = ActorSystem("actorSystem")

class SomeActor extends Actor with ReceivePipeline { def receive: Actor.Receive = { case m: String => }  }

trait Interceptor { this: ReceivePipeline =>
    pipelineOuter(inner => { case n: Int => inner(n) })
}

class Decorated extends SomeActor with Interceptor

val decorated = system.actorOf(Props(new Decorated))

decorated ! 1
```

results in:
```
[ERROR] [06/06/2015 11:24:01.525] [actorSystem-akka.actor.default-dispatcher-7] [akka://actorSystem/user/$a] 1 (of class java.lang.Integer)
scala.MatchError: 1 (of class java.lang.Integer)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:251)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$SomeActor$$anonfun$receive$1.applyOrElse(<console>:21)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$Interceptor$$anonfun$1$$anonfun$apply$1.applyOrElse(<console>:22)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$SomeActor.akka$contrib$pattern$ReceivePipeline$$super$aroundReceive(<console>:21)
	at akka.contrib.pattern.ReceivePipeline$class.aroundReceive(ReceivePipeline.scala:45)
	at $line14.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$SomeActor.aroundReceive(<console>:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:256)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I have additional test cases with a fix for this and can send pull request if you like.
Thanks,
Jeremy Stone

**Comment by ktoso** [comment]
Hi Jeremy,
thanks for reporting! It would be awesome if you could send in a PR of what you have prepared :-)
