### ISSUE TITLE
Seeing ClassCastException within Inbox.create()

### ISSUE THREAD

**Issue by Alex-Ikanow** [akka/akka#17691]
This is possibly a dup of #15409?

    java.lang.ClassCastException: akka.actor.UnstartedCell cannot be cast to akka.actor.ActorCell
    	at akka.actor.ActorDSL$Extension.mkChild(ActorDSL.scala:106)
    	at akka.actor.dsl.Inbox$InboxExtension$class.newReceiver(Inbox.scala:55)
    	at akka.actor.ActorDSL$Extension.newReceiver(ActorDSL.scala:89)
    	at akka.actor.dsl.Inbox$Inbox.<init>(Inbox.scala:169)
    	at akka.actor.dsl.Inbox$class.inbox(Inbox.scala:165)
    	at akka.actor.ActorDSL$.inbox(ActorDSL.scala:75)
    	at akka.actor.Inbox$.create(ActorDSL.scala:151)
    	at akka.actor.Inbox.create(ActorDSL.scala)

We have seen this with 2.4-M1 of 2.11 (2.4-M1 is referenced in the above issue as a milestone) - very intermittently from our Travis CI, never yet when running JUnit from the IDE.

Like the above issue, we are creating an inbox as part of a unit test very soon after the system has been created.

Is there any check that can be made before getting the inbox, or a max sleep time that we can apply?

**Comment by Alex-Ikanow** [comment]
Confirmation of the version we're running:

    Downloading: http://repo.maven.apache.org/maven2/com/typesafe/akka/akka-actor_2.11/2.4-M1/akka-actor_2.11-2.4-M1.pom
    Downloaded: http://repo.maven.apache.org/maven2/com/typesafe/akka/akka-actor_2.11/2.4-M1/akka-actor_2.11-2.4-M1.pom (2 KB at 68.0 KB/sec)

**Comment by patriknw** [comment]
Thanks for reporting.

**Comment by patriknw** [comment]
@Alex-Ikanow I suspect that you don't run 2.4-M1. The line number for `at akka.actor.Inbox$.create(ActorDSL.scala:151)` in your stack trace does not match the source code for 2.4-M1 https://github.com/akka/akka/blob/v2.4-M1/akka-actor/src/main/scala/akka/actor/ActorDSL.scala#L156
