### ISSUE TITLE
FAILED: ConnectionPoolSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#17784]
```
[info] ConnectionPoolSpec:
Coroner Thread Count starts at 18 in akka.http.impl.engine.client.ConnectionPoolSpec
[info] The host-level client infrastructure
[info] - should properly complete a simple request/response cycle (123 milliseconds)
[info] - should open a second connection if the first one is loaded (78 milliseconds)
[info] - should open a second connection if the request on the first one is dispatch but not yet completed (96 milliseconds)
[info] - should not open a second connection if there is an idle one available *** FAILED *** (3 seconds, 57 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.StreamTestKit$OnNext
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:423)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:396)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:223)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4$$anon$7.<init>(ConnectionPoolSpec.scala:126)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply$mcV$sp(ConnectionPoolSpec.scala:115)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:115)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:115)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
...
```
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/2959/consoleFull
while validating https://github.com/akka/akka/pull/17783

//cc @sirthias @jrudolph

**Comment by drewhk** [comment]
Another one
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4108/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4461/consoleFull

**Comment by ktoso** [comment]
Again

```
[info] ConnectionPoolSpec:
Coroner Thread Count starts at 17 in akka.http.impl.engine.client.ConnectionPoolSpec
[info] The host-level client infrastructure
[info] - should properly complete a simple request/response cycle (1 second, 887 milliseconds)
[info] - should open a second connection if the first one is loaded (168 milliseconds)
[info] - should open a second connection if the request on the first one is dispatch but not yet completed (230 milliseconds)
[info] - should not open a second connection if there is an idle one available *** FAILED *** (3 seconds, 93 milliseconds)
[info]   java.lang.AssertionError: expected OnNext, found null
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:256)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4$$anon$7.<init>(ConnectionPoolSpec.scala:125)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply$mcV$sp(ConnectionPoolSpec.scala:114)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:114)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$7$$anonfun$apply$mcV$sp$4.apply(ConnectionPoolSpec.scala:114)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.stream.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:54)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
```

**Comment by ktoso** [comment]
I'll look into it.

**Comment by rkuhn** [comment]
The test definitely is a little racy, but I also recently fixed some things in the slot selector, so closing until it recurs.
