### ISSUE TITLE
FAILED: TcpSpec - Outgoing TCP stream - must properly full-close if requested

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17804]
Quite possibly just a timing issue?

Connection failed:

```
[info] Outgoing TCP stream
[info] - must work in the happy case (280 milliseconds)
[WARN] [06/22/2015 14:49:51.174] [TcpSpec-akka.actor.default-dispatcher-4] [akka://TcpSpec/user/$b] received dead letter from Actor[akka://TcpSpec/system/IO-TCP/selectors/$a/0#-2115634180]: Unbound
[info] - must be able to write a sequence of ByteStrings (65 milliseconds)
[info] - must be able to read a sequence of ByteStrings (83 milliseconds)
[WARN] [06/22/2015 14:49:51.388] [TcpSpec-akka.actor.default-dispatcher-2] [akka://TcpSpec/user/$e/$a] received dead letter from Actor[akka://TcpSpec/deadLetters]: PingClose(Actor[akka://TcpSpec/system/testActor199#-252353423])
[info] - must work when client closes write, then remote closes write (73 milliseconds)
[info] - must work when remote closes write, then client closes write (69 milliseconds)
[WARN] [06/22/2015 14:49:52.830] [TcpSpec-akka.actor.default-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/17] received dead letter from Actor[akka://TcpSpec/user/$g/$a#1430473875]: ResumeReading
[info] - must work when client closes read, then client closes write (1 second, 373 milliseconds)
[WARN] [06/22/2015 14:49:52.906] [TcpSpec-akka.actor.default-dispatcher-3] [akka://TcpSpec/user/$h/$a] received dead letter from Actor[akka://TcpSpec/deadLetters]: PingClose(Actor[akka://TcpSpec/system/testActor214#-1204101801])
[info] - must work when client closes write, then client closes read (73 milliseconds)
[WARN] [06/22/2015 14:49:52.972] [TcpSpec-akka.actor.default-dispatcher-3] [akka://TcpSpec/system/IO-TCP/selectors/$a/22] received dead letter from Actor[akka://TcpSpec/deadLetters]: ChannelReadable
[info] - must work when client closes read, then server closes write, then client closes write (66 milliseconds)
[info] - must shut everything down if client signals error (67 milliseconds)
[info] - must shut everything down if client signals error after remote has closed write (66 milliseconds)
[WARN] [06/22/2015 14:49:53.170] [TcpSpec-akka.actor.default-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/31] received dead letter from Actor[akka://TcpSpec/system/IO-TCP-STREAM/client-11-%2F127.0.0.1%3A44447#876543870]: ResumeReading
[WARN] [06/22/2015 14:49:53.171] [TcpSpec-akka.actor.default-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/31] received dead letter from Actor[akka://TcpSpec/system/IO-TCP-STREAM/client-11-%2F127.0.0.1%3A44447#876543870]: Abort
[info] - must shut down both streams when connection is aborted remotely (64 milliseconds)
[info] - must materialize correctly when used in multiple flows (93 milliseconds)
[WARN] [06/22/2015 14:49:53.266] [TcpSpec-akka.actor.default-dispatcher-5] [akka://TcpSpec/user/$m] received dead letter from Actor[akka://TcpSpec/system/IO-TCP/selectors/$a/33#-236407515]: Unbound
[WARN] [06/22/2015 14:49:53.269] [TcpSpec-akka.actor.default-dispatcher-3] [akka://TcpSpec/system/IO-TCP/selectors/$a/36] received dead letter from Actor[akka://TcpSpec/system/IO-TCP-STREAM/client-13-%2F127.0.0.1%3A38869#290974405]: ResumeReading
[WARN] [06/22/2015 14:49:53.269] [TcpSpec-akka.actor.default-dispatcher-3] [akka://TcpSpec/system/IO-TCP/selectors/$a/36] received dead letter from Actor[akka://TcpSpec/system/IO-TCP-STREAM/client-13-%2F127.0.0.1%3A38869#290974405]: Abort
[info] - must properly full-close if requested *** FAILED *** (62 milliseconds)
[info]   akka.stream.StreamTcpException: Connection failed.
[info] - must Echo should work even if server is in full close mode (475 milliseconds)
[info] TCP listen stream
[info] - must be able to implement echo (26 milliseconds)
[info] - must work with a chain of echoes (33 milliseconds)
[ERROR] [06/22/2015 14:49:53.920] [TcpSpec-akka.actor.default-dispatcher-2] [akka://TcpSpec/system/IO-TCP/selectors/$a/56] Bind failed for TCP channel on endpoint [localhost/127.0.0.1:36321]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:53)
	at akka.io.TcpListener.<init>(TcpListener.scala:50)
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [06/22/2015 14:49:53.924] [TcpSpec-akka.actor.default-dispatcher-15] [akka://TcpSpec/system/IO-TCP/selectors/$a/57] Bind failed for TCP channel on endpoint [localhost/127.0.0.1:36321]
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:53)
	at akka.io.TcpListener.<init>(TcpListener.scala:50)
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:352)
	at akka.actor.Props.newActor(Props.scala:252)
	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
	at akka.actor.ActorCell.create(ActorCell.scala:578)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by drewhk** [comment]
moving to next milestone.

**Comment by viktorklang** [comment]
This reproduces always on my box

**Comment by drewhk** [comment]
The sad reality is, that this probably needs to be fixed at the akka.io level, which means another akka 2.3 release.

**Comment by viktorklang** [comment]
Yep, but bugs needs fixin' :)

**Comment by drewhk** [comment]
no argument about that one :)

**Comment by drewhk** [comment]
There are different failures here, not all of them is the same. This ticket is about the bind failure "address in use" which is not the same you have found. That one is about subscription timeouts, and I think it can be just a too short timeout. I don't see so far anything wrong with the full-close.

**Comment by drewhk** [comment]
And there is another one about the fullClose.

**Comment by drewhk** [comment]
Fixed via the other fixes.
