### ISSUE TITLE
FAILED: ConsumerIntegrationTest (camel)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#17813]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2557/consoleFull

```
[info] ConsumerIntegrationTest
1194.870: [GC (Allocation Failure) [PSYoungGen: 605824K->9434K(651264K)] 1212881K->616508K(2049536K), 0.0224312 secs] [Times: user=0.12 sys=0.00, real=0.02 secs] 
[info] - must Consumer must throw FailedToCreateRouteException, while awaiting activation, if endpoint is invalid (135 milliseconds)
[info] - must Consumer must support in-out messaging (196 milliseconds)
[info] - must Consumer must time-out if consumer is slow *** FAILED *** (1 second, 190 milliseconds)
[info]   Expected exception org.apache.camel.CamelExecutionException to be thrown, but java.lang.AssertionError was thrown. (ConsumerIntegrationTest.scala:60)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:496)
[info]   at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
[info]   at org.scalatest.Assertions$class.intercept(Assertions.scala:1004)
[info]   at org.scalatest.WordSpec.intercept(WordSpec.scala:1881)
[info]   at akka.camel.ConsumerIntegrationTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(ConsumerIntegrationTest.scala:60)
[info]   at akka.camel.ConsumerIntegrationTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ConsumerIntegrationTest.scala:50)
[info]   at akka.camel.ConsumerIntegrationTest$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(ConsumerIntegrationTest.scala:50)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.camel.ConsumerIntegrationTest.org$scalatest$BeforeAndAfterEach$$super$runTest(ConsumerIntegrationTest.scala:25)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:
```

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
