### ISSUE TITLE
sbt error during import of release-2.3-dev into idea

### ISSUE THREAD

**Issue by 2beaucoup** [akka/akka#17924]
"Settings logger used after project was loaded."

```
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[warn] Java 8 installation has not been found. Java 8 tasks will not be run.
[info] Set current project to akka (in build file:/[...]/akka/)
[info] Defining akka/*:artifactPath
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
java.lang.RuntimeException: Settings logger used after project was loaded.
	at scala.sys.package$.error(package.scala:27)
	at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:111)
	at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:111)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.LogManager$$anon$1.slog(LogManager.scala:111)
	at sbt.LogManager$$anon$1.log(LogManager.scala:116)
	at sbt.Logger$class.warn(Logger.scala:123)
	at sbt.LogManager$$anon$1.warn(LogManager.scala:110)
	at akka.AkkaBuild$$anonfun$defaultSettings$18$$anonfun$apply$305.apply(AkkaBuild.scala:1110)
	at akka.AkkaBuild$$anonfun$defaultSettings$18$$anonfun$apply$305.apply(AkkaBuild.scala:1110)
	at scala.Option.orElse(Option.scala:257)
	at akka.AkkaBuild$$anonfun$defaultSettings$18.apply(AkkaBuild.scala:1110)
	at akka.AkkaBuild$$anonfun$defaultSettings$18.apply(AkkaBuild.scala:1097)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:134)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:66)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:75)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

All is well after [this log statement](https://github.com/akka/akka/blob/release-2.3-dev/project/AkkaBuild.scala#L1110) is removed.

**Comment by drewhk** [comment]
Oh. I reported this back then: https://youtrack.jetbrains.com/issue/SCL-8780
But I couldn't trace it to that log statement.

**Comment by 2beaucoup** [comment]
Why do I have to provide the path at all? Why not simply check if the *current* JDK is Java 8 compatible?

That being siad `sys.props("java.version").startsWith("1.8")` is currently checked three times in that file and therefore deserves its own method IMO.

**Comment by jrudolph** [comment]
@2beaucoup It's because this way you can use Java 6 or 7 to build Akka without risking to use JDK 7/8 features and still have some subprojects use Java 8.

**Comment by 2beaucoup** [comment]
@jrudolph Makes sense. Also ran into Java version issues before. ;)

Wouldn't Jenkins complain in such cases anyway? But I'm drifting into OT territory...

**Comment by jrudolph** [comment]
Yes, the same reasoning applies to Jenkins. It should not yet build with Java 8 as a default but should be able to test Java 8 examples.

**Comment by jrudolph** [comment]
I.e. AFAIU

**Comment by drewhk** [comment]
Anyway, I pinged the Scala plugin ticket linking to this one.

**Comment by 2beaucoup** [comment]
Although the Idea ticket is still open, the log statement doesn't seem to crash the sbt import anymore (on 14.1.5).

Generated source files never worked for me in Idea. An `sbt compile` seems neccesery before importing.

**Comment by drewhk** [comment]
For me it failed just as before on 15 today
