### ISSUE TITLE
ContentNegotiationSpec almost fails completely if tests are properly enabled

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#17984]
The syntax `(exampleName: String) in (f: String => U)` doesn't actually run `f`. Once that is fixed 13 out of 16 tests fail.

From a glance I cannot say if the implementation is more wrong or the tests. WDYT, @sirthias?

I'll push a PR shortly which enables the tests but fails them.

**Comment by jrudolph** [comment]
#17987 enables the tests.

**Comment by 2beaucoup** [comment]
In the first test:

https://github.com/spray/akka/blob/w/17984-enable-content-negotiation-tests/akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala#L123

calls

https://github.com/spray/akka/blob/w/17984-enable-content-negotiation-tests/akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala#L24

`withFixedCharset()` -> `withOpenCharset()`

Could that be the cause?

Stack:
```
  at akka.http.scaladsl.marshalling.Marshaller$.withOpenCharset(Marshaller.scala:112)
	  at akka.http.scaladsl.marshalling.PredefinedToEntityMarshallers$class.byteArrayMarshaller(PredefinedToEntityMarshallers.scala:24)
	  at akka.http.scaladsl.marshalling.Marshaller$.byteArrayMarshaller(Marshaller.scala:66)
	  at akka.http.scaladsl.marshalling.PredefinedToEntityMarshallers$class.$init$(PredefinedToEntityMarshallers.scala:16)
	  at akka.http.scaladsl.marshalling.Marshaller$.<init>(Marshaller.scala:67)
	  at akka.http.scaladsl.marshalling.Marshaller$.<clinit>(Marshaller.scala:-1)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$testHeaders$1$$anonfun$2.apply(ContentNegotiationSpec.scala:123)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$testHeaders$1$$anonfun$2.apply(ContentNegotiationSpec.scala:122)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$testHeaders$1.apply(ContentNegotiationSpec.scala:122)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$testHeaders$1.apply(ContentNegotiationSpec.scala:120)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ContentNegotiationSpec.scala:20)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(ContentNegotiationSpec.scala:18)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$AddStringToIn$$anonfun$test$1$$anonfun$apply$mcV$sp$19.apply(ContentNegotiationSpec.scala:148)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$AddStringToIn$$anonfun$test$1$$anonfun$apply$mcV$sp$19.apply(ContentNegotiationSpec.scala:148)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec.testHeaders(ContentNegotiationSpec.scala:120)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$AddStringToIn$$anonfun$test$1.apply$mcV$sp(ContentNegotiationSpec.scala:148)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$AddStringToIn$$anonfun$test$1.apply(ContentNegotiationSpec.scala:136)
	  at akka.http.scaladsl.marshalling.ContentNegotiationSpec$AddStringToIn$$anonfun$test$1.apply(ContentNegotiationSpec.scala:136)
```

**Comment by ktoso** [comment]
AFAICS this is also resolved now right?

**Comment by jrudolph** [comment]
Yep, exactly.
