### ISSUE TITLE
FAILED: FlowTest#mustBeAbleToRecover timing issue

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18002]
It slightly went over-time in: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3231/consoleFull // https://github.com/akka/akka/pull/17988

```
rror] Test akka.stream.javadsl.FlowTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1, took 3.044 sec
[error]     at scala.Predef$.assert(Predef.scala:179)
[error]     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[error]     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[error]     at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[error]     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
[error]     at akka.stream.javadsl.FlowTest.mustBeAbleToRecover(FlowTest.java:548)
[error]     ...
```

**Comment by jrudolph** [comment]
This still happens with high probability.

**Comment by ktoso** [comment]
Thanks for reopening // cc @agolubev

**Comment by agolubev** [comment]
Got it. Will check on weekend.

**Comment by agolubev** [comment]
Ok, there are two tests mustBeAbleToRecover. One for Flow and one for Source. So need to fix the second one.
