### ISSUE TITLE
FAILED: Diagrams not generated (wat)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18053]
Diagram generation failed for scaladoc on nightly, need to check why;

```
java.lang.RuntimeException: ScalaDoc diagrams not generated!
	at scala.sys.package$.error(package.scala:27)
	at akka.Scaladoc$.scaladocVerifier(Doc.scala:72)
	at akka.Scaladoc$$anonfun$projectSettings$5$$anonfun$apply$1.apply(Doc.scala:34)
	at akka.Scaladoc$$anonfun$projectSettings$5$$anonfun$apply$1.apply(Doc.scala:31)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (akka-docs/compile:doc) ScalaDoc diagrams not generated!
```

https://jenkins.akka.io:8498/job/akka-multi-node/1131/console

**Comment by 2m** [comment]
This is now failing constantly:
https://jenkins.akka.io:8498/job/akka-multi-node/1129/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1130/consoleFull

**Comment by patriknw** [comment]
Still failing: https://jenkins.akka.io:8498/job/akka-multi-node/1137/console

**Comment by patriknw** [comment]
Strange. Fails in https://jenkins.akka.io:8498/job/akka-multi-node/ but works fine in https://jenkins.akka.io:8498/job/akka-multi-node-nightly/
Compared the jvm arguments and everything is the same.

**Comment by patriknw** [comment]
Two successful builds on a4
https://jenkins.akka.io:8498/job/akka-multi-node/1139/
https://jenkins.akka.io:8498/job/akka-multi-node/1140/

**Comment by patriknw** [comment]
Looks like this is working now

**Comment by ktoso** [comment]
:+1:
