### ISSUE TITLE
FAILED: TcpSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18099]
`Expected exception akka.stream.StreamTcpException to be thrown, but java.util.concurrent.TimeoutException was thrown`
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3304/consoleFull
```
[info] - must handle when connection actor terminates unexpectedly *** FAILED *** (3 seconds, 36 milliseconds)
[info]   Expected exception akka.stream.StreamTcpException to be thrown, but java.util.concurrent.TimeoutException was thrown. (TcpSpec.scala:384)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:496)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1538)
[info]   at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1572)
[info]   at org.scalatest.words.ResultOfBeWordForAType.thrownBy(ResultOfBeWordForAType.scala:39)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$27.apply$mcV$sp(TcpSpec.scala:397)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$27.apply(TcpSpec.scala:384)
[info]   at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$27.apply(TcpSpec.scala:384)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
```

**Comment by 2m** [comment]
[Same spec failed](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3542/consoleFull) while PR validating #18352 on a4.

```
[info] - must shut down properly even if some accepted connection Flows have not been subscribed to *** FAILED *** (3 seconds, 29 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:107)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$34$$anonfun$apply$mcV$sp$35.apply$mcV$sp(TcpSpec.scala:518)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$34$$anonfun$apply$mcV$sp$35.apply(TcpSpec.scala:504)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$34$$anonfun$apply$mcV$sp$35.apply(TcpSpec.scala:504)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$34.apply$mcV$sp(TcpSpec.scala:504)
```

**Comment by drewhk** [comment]
Thanks to @agolubev, this can be closed.
