### ISSUE TITLE
FAILED: akka.cluster.ddata.PerformanceSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18235]
Just a bit fleaky IMO: https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/86/consoleFull

```
[info] * akka.cluster.ddata.PerformanceSpec
[JVM-1] PerformanceSpecMultiJvmNode1:
[JVM-1] Performance
[JVM-2] PerformanceSpecMultiJvmNode2:
[JVM-2] Performance
[JVM-5] PerformanceSpecMultiJvmNode5:
[JVM-3] PerformanceSpecMultiJvmNode3:
[JVM-5] Performance
[JVM-3] Performance
[JVM-4] PerformanceSpecMultiJvmNode4:
[JVM-4] Performance
[JVM-2] - must setup cluster (2 seconds, 634 milliseconds)
[JVM-5] - must setup cluster (2 seconds, 626 milliseconds)
[JVM-1] - must setup cluster (2 seconds, 727 milliseconds)
[JVM-3] - must setup cluster (2 seconds, 624 milliseconds)
[JVM-4] - must setup cluster (2 seconds, 619 milliseconds)
[JVM-1] - must be great for ORSet Update WriteLocal *** FAILED *** (6 seconds, 216 milliseconds)
[JVM-1]   java.util.concurrent.TimeoutException: Timeout of 6 seconds with time factor of 1.0
[JVM-1]   at akka.testkit.TestLatch.ready(TestLatch.scala:41)
[JVM-1]   at akka.testkit.TestLatch.ready(TestLatch.scala:26)
[JVM-1]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[JVM-1]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[JVM-1]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-1]   at scala.concurrent.Await$.ready(package.scala:169)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1$$anonfun$apply$1.apply$mcV$sp(PerformanceSpec.scala:91)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1.apply(PerformanceSpec.scala:82)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1.apply(PerformanceSpec.scala:80)
[JVM-1]   at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[JVM-1]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[JVM-1]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[JVM-1]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec.repeat(PerformanceSpec.scala:80)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(PerformanceSpec.scala:143)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(PerformanceSpec.scala:139)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(PerformanceSp
```

**Comment by ktoso** [comment]
This was `a0`

**Comment by ktoso** [comment]
Another one https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/85/consoleFull

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3490/consoleFull

```
[JVM-1] - must be great for ORSet Update WriteLocal *** FAILED *** (6 seconds, 24 milliseconds)
[JVM-1]   java.util.concurrent.TimeoutException: Timeout of 6 seconds with time factor of 1.0
[JVM-1]   at akka.testkit.TestLatch.ready(TestLatch.scala:41)
[JVM-1]   at akka.testkit.TestLatch.ready(TestLatch.scala:26)
[JVM-1]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[JVM-1]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[JVM-1]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-1]   at scala.concurrent.Await$.ready(package.scala:169)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1$$anonfun$apply$1.apply$mcV$sp(PerformanceSpec.scala:91)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:338)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1.apply(PerformanceSpec.scala:82)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$repeat$1.apply(PerformanceSpec.scala:80)
[JVM-1]   at scala.collection.Iterator$class.foreach(Iterator.scala:750)
[JVM-1]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[JVM-1]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[JVM-1]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec.repeat(PerformanceSpec.scala:80)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(PerformanceSpec.scala:143)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(PerformanceSpec.scala:139)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(PerformanceSpec.scala:139)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[JVM-1]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec.withFixture(PerformanceSpec.scala:58)
[JVM-1]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-1]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-1]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[JVM-1]   at akka.cluster.ddata.PerformanceSpec.runTest(PerformanceSpec.scala:58)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/95/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2813/consoleFull

**Comment by patriknw** [comment]
I noticed that the extra merge introduced by #18328 makes the local write very slow compared to not merging. That might be the reason why this test started failing. I will increase the timeout in this issue and we can do performance optimizations in #18328
