### ISSUE TITLE
FAILED: LeveldbJournalJavaSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18237]
Seems like to aggressive timeouts https://jenkins.akka.io:8498/job/akka-nightly/2526/consoleFull

```
info] LeveldbJournalJavaSpec:
[info] A journal
[info] - must replay all messages (601 milliseconds)
[info] - must replay messages using a lower sequence number bound (7 milliseconds)
[info] - must replay messages using an upper sequence number bound (6 milliseconds)
[info] - must replay messages using a count limit (154 milliseconds)
[info] - must replay messages using a lower and upper sequence number bound (6 milliseconds)
[info] - must replay messages using a lower and upper sequence number bound and a count limit (5 milliseconds)
[info] - must replay a single if lower sequence number bound equals upper sequence number bound (4 milliseconds)
[info] - must replay a single message if count limit equals 1 (3 milliseconds)
[info] Exception encountered when attempting to run a suite with class name: akka.persistence.journal.leveldb.LeveldbJournalJavaSpec *** ABORTED *** (7 seconds, 376 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 1 second expired:
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:242)
[info]   at akka.testkit.TestKitBase$class.awaitCond(TestKit.scala:248)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:738)
[info]   at akka.testkit.TestKitBase$class.$init$(TestKit.scala:133)
[info]   at akka.testkit.TestKit.<init>(TestKit.scala:738)
[info]   at akka.testkit.TestProbe.<init>(TestKit.scala:795)
[info]   at akka.testkit.TestProbe.<init>(TestKit.scala:797)
[info]   at akka.testkit.TestProbe$.apply(TestKit.scala:831)
[info]   at akka.persistence.journal.JournalSpec.beforeEach(JournalSpec.scala:42)
[info]   at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:154)
[info]   at akka.persistence.PluginSpec.beforeEach(PluginSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:173)
[info]   at akka.persistence.PluginSpec.beforeEach(PluginSpec.scala:11)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:253)
[info]   at akka.persistence.PluginSpec.runTest(PluginSpec.scala:11)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
```

**Comment by ktoso** [comment]
This was `a0`

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
