### ISSUE TITLE
FAILED: LeveldbPersistentFsm

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18236]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/2780/consoleFull

```
[info] PersistentFSM
[info] - must function as a regular FSM  (1 second, 30 milliseconds)
[info] - must function as a regular FSM on state timeout *** FAILED *** (1 second, 940 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (1899411097 nanoseconds) during expectMsg while waiting for Transition(Actor[akka://PersistenceSpec/user/$b#1445175300],Shopping,Inactive,Some(2 seconds))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:353)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:330)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:738)
[info]   at akka.persistence.fsm.PersistentFSMSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$9.apply(PersistentFSMSpec.scala:76)
[info]   at akka.persistence.fsm.PersistentFSMSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$9.apply(PersistentFSMSpec.scala:76)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:311)
[info]   at akka.testkit.TestKit.within(TestKit.scala:738)
[info]   at akka.persistence.fsm.PersistentFSMSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(PersistentFSMSpec.scala:75)
[info]   at akka.persistence.fsm.PersistentFSMSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(PersistentFSMSpec.scala:61)
[info]   at akka.persistence.fsm.PersistentFSMSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(PersistentFSMSpec.scala:61)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:56)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.persistence.PersistenceSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(PersistenceSpec.scala:24)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:255)
[info]   at akka.persistence.PersistenceSpec.runTest(PersistenceSpec.scala:24)
```

**Comment by ktoso** [comment]
This was `a3`

**Comment by patriknw** [comment]
I guess this is the same as #18162

**Comment by ktoso** [comment]
Yes, seems so - closing this one
