### ISSUE TITLE
FAILED: sample.cluster.transformation.TransformationSampleSpec (weird)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18240]
Seems a bit weird: https://jenkins.akka.io:8498/job/akka-nightly/2527/consoleFull

```
[JVM-3] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-3] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
[JVM-3] 	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
```

Did not happen in other runs on that node (`a0`)

```
[info] * sample.cluster.transformation.TransformationSampleSpec
[JVM-3] no libsigar-amd64-linux.so in java.library.path
[JVM-3] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-3] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
[JVM-3] 	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
[JVM-3] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-3] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-3] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-3] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-3] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
[JVM-3] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-3] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
[JVM-3] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-3] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-3] 	at scala.util.Success.flatMap(Try.scala:230)
[JVM-3] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
[JVM-3] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:712)
[JVM-3] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:717)
[JVM-3] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-3] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-3] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-3] 	at akka.cluster.MetricsCollector$.apply(ClusterMetricsCollector.scala:792)
[JVM-3] 	at akka.cluster.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:67)
[JVM-3] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-3] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-3] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-3] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-3] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[JVM-3] 	at akka.actor.ArgsReflectConstructor.produce(Props.scala:345)
[JVM-3] 	at akka.actor.Props.newActor(Props.scala:256)
[JVM-3] 	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
[JVM-3] 	at akka.actor.ActorCell.create(ActorCell.scala:578)
[JVM-3] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
[JVM-3] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[JVM-3] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:281)
[JVM-3] 	at akka.dispatch.Mailbox.run(Mailbox.scala:222)
[JVM-3] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
[JVM-3] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-3] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-3] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-3] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-1] no libsigar-amd64-linux.so in java.library.path
[JVM-1] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-1] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
[JVM-1] 	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
[JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-1] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-1] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-1] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
[JVM-1] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-1] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
[JVM-1] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-1] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-1] 	at scala.util.Success.flatMap(Try.scala:230)
[JVM-1] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
[JVM-1] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:712)
[JVM-1] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:717)
[JVM-1] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-1] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-1] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-1] 	at akka.cluster.MetricsCollector$.apply(ClusterMetricsCollector.scala:792)
[JVM-1] 	at akka.cluster.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:67)
[JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-1] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-1] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-1] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[JVM-1] 	at akka.actor.ArgsReflectConstructor.produce(Props.scala:345)
[JVM-1] 	at akka.actor.Props.newActor(Props.scala:256)
[JVM-1] 	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
[JVM-1] 	at akka.actor.ActorCell.create(ActorCell.scala:578)
[JVM-1] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
[JVM-1] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[JVM-1] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:281)
[JVM-1] 	at akka.dispatch.Mailbox.run(Mailbox.scala:222)
[JVM-1] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
[JVM-1] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-1] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-1] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-1] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-4] no libsigar-amd64-linux.so in java.library.path
[JVM-4] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-4] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
[JVM-4] 	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
[JVM-4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-4] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-4] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-4] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
[JVM-4] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-4] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
[JVM-4] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-4] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-4] 	at scala.util.Success.flatMap(Try.scala:230)
[JVM-4] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
[JVM-4] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:712)
[JVM-4] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:717)
[JVM-4] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-4] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-4] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-4] 	at akka.cluster.MetricsCollector$.apply(ClusterMetricsCollector.scala:792)
[JVM-4] 	at akka.cluster.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:67)
[JVM-4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-4] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-4] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-4] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[JVM-4] 	at akka.actor.ArgsReflectConstructor.produce(Props.scala:345)
[JVM-4] 	at akka.actor.Props.newActor(Props.scala:256)
[JVM-4] 	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
[JVM-4] 	at akka.actor.ActorCell.create(ActorCell.scala:578)
[JVM-4] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
[JVM-4] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[JVM-4] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:281)
[JVM-4] 	at akka.dispatch.Mailbox.run(Mailbox.scala:222)
[JVM-4] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
[JVM-4] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-4] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-4] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-4] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-5] no libsigar-amd64-linux.so in java.library.path
[JVM-5] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-5] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
[JVM-5] 	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
[JVM-5] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-5] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-5] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-5] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-5] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
[JVM-5] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-5] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
[JVM-5] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-5] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
[JVM-5] 	at scala.util.Success.flatMap(Try.scala:230)
[JVM-5] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
[JVM-5] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:712)
[JVM-5] 	at akka.cluster.SigarMetricsCollector.<init>(ClusterMetricsCollector.scala:717)
[JVM-5] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-5] 	at akka.cluster.MetricsCollector$$anonfun$7.apply(ClusterMetricsCollector.scala:792)
[JVM-5] 	at scala.util.Try$.apply(Try.scala:191)
[JVM-5] 	at akka.cluster.MetricsCollector$.apply(ClusterMetricsCollector.scala:792)
[JVM-5] 	at akka.cluster.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:67)
[JVM-5] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-5] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-5] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-5] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-5] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[JVM-5] 	at akka.actor.ArgsReflectConstructor.produce(Props.scala:345)
[JVM-5] 	at akka.actor.Props.newActor(Props.scala:256)
[JVM-5] 	at akka.actor.ActorCell.newActor(ActorCell.scala:552)
[JVM-5] 	at akka.actor.ActorCell.create(ActorCell.scala:578)
[JVM-5] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
[JVM-5] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
[JVM-5] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:281)
[JVM-5] 	at akka.dispatch.Mailbox.run(Mailbox.scala:222)
[JVM-5] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
[JVM-5] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-5] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-5] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-5] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-2] no libsigar-amd64-linux.so in java.library.path
[JVM-2] org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
[JVM-2] 	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
```

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
