### ISSUE TITLE
[akka-streams] Java DSL: Flow.of(MyClass.class).via(otherFlow) throws ClassCastException

### ISSUE THREAD

**Issue by jypma** [akka/akka#18275]
```
import akka.stream.javadsl.Flow;

Flow<MyClass,Object,?> otherFlow = ...

Flow<MyClass,Object,?> myFlow = Flow.of(MyClass.class).via(otherFlow)
```
results in
```
akka.stream.javadsl.Flow cannot be cast to akka.stream.scaladsl.Flow	
	at  akka.stream.scaladsl.Flow.viaMat(Flow.scala:78)
	at akka.stream.scaladsl.Flow.via(Flow.scala:59)
	at akka.stream.javadsl.Flow.via(Flow.scala:99)
```
because `scaladsl.Flow:78` assumes that if `this.isIdentity` is true (which it is on the Java version), that `this` must in fact be an instance of `scalads.Flow` (which it isn't).

**Comment by ktoso** [comment]
Ouch, thanks for reporting!
