### ISSUE TITLE
persistence batch delete throws exception

### ISSUE THREAD

**Issue by kpbochenek** [akka/akka#18327]
Tried to use akka 2.4.0-RC1 with akka-persistence and during deletion from actor I can see exception:

scala.MatchError: Success(DeleteMessagesSuccess(5)) (of class scala.util.Success)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$applyOrElse$11.apply(AsyncWriteJournal.scala:156) ~[akka-persistence_2.11-2.4.0-RC1.jar:na]
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$applyOrElse$11.apply(AsyncWriteJournal.scala:156) ~[akka-persistence_2.11-2.4.0-RC1.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.4.0-RC1.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0-RC1.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0-RC1.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.0-RC1.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.6.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.4.0-RC1.jar:na]

Could this be caused by faulty implementation of persistence-plugin or could this be related to some issue with akka-persistence?

I will try to check my plugin on minimalistic example but in meantime maybe this is known thing?
Or can you help me narrow what could cause that?

**Comment by patriknw** [comment]
What journal plugin are you using? Note that you must use one that has been released for 2.4.0-RC1. 2.3.x plugins will not work.

**Comment by kpbochenek** [comment]
Adjusted CassandraPersistencePlugin to work with 2.4.0-RC1.
Possibly messed up something but can't see anything in stacktrace regarding plugin :/
Mentioned faulty line also looks okay

**Comment by kpbochenek** [comment]
Okay I should have tried with SNAPSHOT.

In 2.4.0-RC1 is a line: case _ if publish ⇒ context.system.eventStream.publish(d)
In snapshot is: case _ ⇒ if (publish) context.system.eventStream.publish(d)
It failed because of not found match case in 2.4.0-RC1 

Sorry for troubles (solved by Konrad in commit e185718189eb746c97505485cbd8c0435f961aaf)

**Comment by patriknw** [comment]
right, a workaround is that you define config property:

    akka.persistence.publish-plugin-commands = on
