### ISSUE TITLE
HTTPS client: Unexpected disconnect

### ISSUE THREAD

**Issue by francisdb** [akka/akka#18334]
What I try to do using akka-http

```bash
curl -i -X POST https://api.netatmo.net/oauth2/token --data "grant_type=password"
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 27 Aug 2015 08:03:45 GMT
Content-Type: application/json
Content-Length: 26
Connection: keep-alive
X-Powered-By: NetatmoAPI
Cache-Control: no-store
Access-Control-Allow-Origin: *

{"error":"invalid_client"}
```

My code

```scala
  val data = FormData(
    "grant_type" -> "password"
  )

  val req = Post(uri = "https://api.netatmo.net/oauth2/token", data)

  val responseFuture = Http().singleRequest(req).flatMap { response =>
    println(response.status)
    Unmarshal(response.entity).to[String]
  }
  ...
```

Resulting Exception

```
root[ERROR] java.lang.RuntimeException: Unexpected disconnect
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8$$anonfun$9.apply(PoolSlot.scala:181)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8$$anonfun$9.apply(PoolSlot.scala:181)
root[ERROR] 	at scala.Option.fold(Option.scala:158)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8.apply(PoolSlot.scala:181)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8.apply(PoolSlot.scala:179)
root[ERROR] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
root[ERROR] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
root[ERROR] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
root[ERROR] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
root[ERROR] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.handleDisconnect(PoolSlot.scala:184)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$running$1.applyOrElse(PoolSlot.scala:173)
root[ERROR] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorSubscriber$$super$aroundReceive(PoolSlot.scala:86)
root[ERROR] 	at akka.stream.actor.ActorSubscriber$class.aroundReceive(ActorSubscriber.scala:199)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorPublisher$$super$aroundReceive(PoolSlot.scala:86)
root[ERROR] 	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:309)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.aroundReceive(PoolSlot.scala:86)
root[ERROR] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
```

**Comment by francisdb** [comment]
Anything I can do to help debugging this?

**Comment by francisdb** [comment]
Just tried databinder dispatch and that also works without issues so this clearly is a bug in akka-http

**Comment by ktoso** [comment]
@jrudolph, Could this be related to the yet pending HTTPS tickets?

**Comment by ktoso** [comment]
@francisdb if you could run the same example with debug logging turned on we should see more details about the failure. Thanks for the help in advance!

**Comment by jrudolph** [comment]
@ktoso, you mean #18058? This could be, it would let the HTTP layer see just a connection closure instead of an HTTPs error. In any case, the pool slot message could probably also be a bit more informative :)

**Comment by francisdb** [comment]
This is what is logged (exception printed with e.printStackTrace)

```
root 13:26:57.215 INFO          akka.event.slf4j.Slf4jLogger - Slf4jLogger started
root 13:26:57.222 DEBUG               akka.event.EventStream - logger log1-Slf4jLogger started
root 13:26:57.226 DEBUG               akka.event.EventStream - Default Loggers started
root 13:26:57.549 DEBUG    a.h.i.e.client.PoolInterfaceActor - (Re-)starting host connection pool to api.netatmo.net:443
root 13:26:57.789 DEBUG        akka.io.TcpOutgoingConnection - Attempting connection to [api.netatmo.net/62.210.178.168:443]
root 13:26:57.816 DEBUG        akka.io.TcpOutgoingConnection - Connection established to [api.netatmo.net/62.210.178.168:443]
root 13:26:57.908 DEBUG     a.h.i.e.c.PoolSlot$SlotProcessor - Slot 0 disconnected after regular connection close
root 13:26:57.912 DEBUG             akka.io.SelectionHandler - received AutoReceiveMessage Envelope(Terminated(Actor[akka://foo-bridge/system/IO-TCP/selectors/$a/0#-624221224]),Actor[akka://foo-bridge/system/IO-TCP/selectors/$a/0#-624221224])
root[ERROR] java.lang.RuntimeException: Unexpected disconnect
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8$$anonfun$9.apply(PoolSlot.scala:181)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8$$anonfun$9.apply(PoolSlot.scala:181)
root[ERROR] 	at scala.Option.fold(Option.scala:158)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8.apply(PoolSlot.scala:181)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$8.apply(PoolSlot.scala:179)
root[ERROR] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
root[ERROR] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
root[ERROR] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
root[ERROR] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
root[ERROR] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
root[ERROR] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.handleDisconnect(PoolSlot.scala:184)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$running$1.applyOrElse(PoolSlot.scala:173)
root[ERROR] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorSubscriber$$super$aroundReceive(PoolSlot.scala:86)
root 13:26:57.917 INFO            akka.actor.ActorSystemImpl - Initiating orderly shutdown of all active host connections pools...
root[ERROR] 	at akka.stream.actor.ActorSubscriber$class.aroundReceive(ActorSubscriber.scala:199)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorPublisher$$super$aroundReceive(PoolSlot.scala:86)
root[ERROR] 	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:309)
root[ERROR] 	at akka.http.impl.engine.client.PoolSlot$SlotProcessor.aroundReceive(PoolSlot.scala:86)
root[ERROR] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
root[ERROR] 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
root[ERROR] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
root[ERROR] 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
root[ERROR] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
root[ERROR] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
root[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
root[ERROR] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
root[ERROR] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
root 13:26:57.919 DEBUG    a.h.i.e.client.PoolInterfaceActor - Shutting down host connection pool to api.netatmo.net:443
root 13:26:57.922 DEBUG    a.h.i.e.client.PoolInterfaceActor - Host connection pool to api.netatmo.net:443 has completed orderly shutdown
root 13:26:57.923 DEBUG    a.h.i.e.client.PoolInterfaceActor - received AutoReceiveMessage Envelope(PoisonPill,Actor[akka://foo-bridge/user/PoolInterfaceActor-0#1888282409])
root 13:26:57.926 DEBUG LocalActorRefProvider$SystemGuardian - received AutoReceiveMessage Envelope(Terminated(Actor[akka://foo-bridge/user]),Actor[akka://foo-bridge/user])
root 13:26:57.927 DEBUG               akka.event.EventStream - shutting down: StandardOutLogger started
```

**Comment by francisdb** [comment]
@ktoso you can easily run the code locally as that netatmo api is publicly accessible

**Comment by ktoso** [comment]
As @jrudolph noticed, the lack of nice error message is related to the #18058 ticket which is being worked on right now.

I was able to obtain the actual error causing the disconnection, here it is:

```
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at akka.stream.impl.io.SslTlsCipherActor.akka$stream$impl$io$SslTlsCipherActor$$doUnwrap(SslTlsCipherActor.scala:373)
	at akka.stream.impl.io.SslTlsCipherActor.akka$stream$impl$io$SslTlsCipherActor$$doInbound(SslTlsCipherActor.scala:297)
	at akka.stream.impl.io.SslTlsCipherActor$$anonfun$1.apply$mcV$sp(SslTlsCipherActor.scala:233)
	at akka.stream.impl.Pump$class.pump(Transfer.scala:199)
	at akka.stream.impl.io.SslTlsCipherActor.pump(SslTlsCipherActor.scala:44)
	at akka.stream.impl.BatchingInputBuffer.enqueueInputElement(ActorProcessor.scala:90)
	at akka.stream.impl.BatchingInputBuffer$$anonfun$upstreamRunning$1.applyOrElse(ActorProcessor.scala:141)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.FanIn$InputBunch$$anonfun$subreceive$1.applyOrElse(FanIn.scala:224)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:16)
	at akka.stream.impl.SubReceive.apply(Transfer.scala:12)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
	at akka.stream.impl.SubReceive.applyOrElse(Transfer.scala:12)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.io.SslTlsCipherActor.aroundReceive(SslTlsCipherActor.scala:44)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1506)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
	at akka.stream.impl.io.SslTlsCipherActor.runDelegatedTasks(SslTlsCipherActor.scala:408)
	at akka.stream.impl.io.SslTlsCipherActor.akka$stream$impl$io$SslTlsCipherActor$$doUnwrap(SslTlsCipherActor.scala:377)
	... 30 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1493)
	... 38 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 44 more
```

I'll have a look why it doesn't can't validate the cert, and the other part of the ticket about a proper error message would be handled by the other ticket.

**Comment by ktoso** [comment]
I also checked with `spray-client` and it's the same problem: 

```
[ERROR] [09/03/2015 12:24:58.905] [spray-client-Testing-akka.actor.default-dispatcher-2] [akka://spray-client-Testing/user/IO-HTTP/group-0/0] Aborting encrypted connection to api.netatmo.net/195.154.199.173:443 due to [SSLHandshakeException:General SSLEngine problem] -> [SSLHandshakeException:General SSLEngine problem] -> [ValidatorException:PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target] -> [SunCertPathBuilderException:unable to find valid certification path to requested target]
[WARN] [09/03/2015 12:24:58.920] [spray-client-Testing-akka.actor.default-dispatcher-3] [akka://spray-client-Testing/user/IO-HTTP/host-connector-0/0] Aborted in response to POST request to /oauth2/token with no retries left, dispatching error...
```

Will have a look at WS and differences in SSL context configurations then.

**Comment by francisdb** [comment]
WS as in play WS?

**Comment by ktoso** [comment]
Yeah, since I believe they've spent much more time configuring the ssl context there.

// cc @wsargent - anything obvious in the errors above I should look into here?

**Comment by jrudolph** [comment]
I'd say the most likely cause is that the root certificates aren't picked up or are not properly configured for the JDK / machine running the example. Try running with `-Djavax.net.debug=all` to show more info about what's going on internally.

**Comment by ktoso** [comment]
Indeed, that's where I got to eventually: 

One can add them manually, as explained here: https://www.playframework.com/documentation/2.4.x/WSQuickStart so with a properly configured (i.e. including the cert for that page for example) it's all good. I'm currently thinking how/if/when we can make this simpler to configure or explain or extract these bits of configuration logic from WS entirely actually.

**Comment by francisdb** [comment]
I wonder why dispatch is not failing

**Comment by francisdb** [comment]
@ktoso have you tried play WS and is that one also failing?

**Comment by ktoso** [comment]
@francisdb, yes; It's both failing with default config, as well as working once the additional certificate is configured.
It's most likely that the libs which fail are somewhat more strict in their configuration than dispatch, I'll dig around to try to find the difference.

**Comment by jrudolph** [comment]
Btw. it seems to work for me with akka-http as well.

**Comment by jrudolph** [comment]
AFAICS no additional certificate should be required because the root certificate for the above site is usually trusted (Are we talking about the same certificate? The one I am seeing has this SHA1 fingerprint: 48:85:D1:A8:4C:E4:62:87:02:FF:1D:8B:EE:E7:8B:D4:2F:23:16:DF).

I'm somewhat confident that running with `-Djavax.net.debug=all` may already give some info about where certificate verification is going wrong. Otherwise, you can also extract the most nested exception which contains fields that contain information about the certificate chain.

**Comment by ktoso** [comment]
Huh, that's not the SHA1 I'm seeing, it's `#0: E:C6:78:CF:7B:1A:B2:2E:AB:3A:1C:B9:81:5F:71:14:2E:4D:9C:2D` and `#1: A1:AC:E4:04:6B:6E:33:22:32:B8:7E:CF:B6:F3:7A:07:63:72:01:47` for me.

**Comment by francisdb** [comment]
@ktoso I think you can just drop this as Using java UrlConnection also fails with `SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by francisdb** [comment]
can I somehow tell akka-http to ignore ssl issues for this host?

**Comment by francisdb** [comment]
see also
https://github.com/openhab/openhab/wiki/Netatmo-Binding
http://forum.netatmo.com/viewtopic.php?f=5&t=1141&p=2315

sorry to not have looked further first

a workaround per host would be welcome

**Comment by jrudolph** [comment]
FWIW in Ubuntu/Debian there's the package `ca-certificates-java` and also you can run `update-ca-certificates -f` which will synchronize the java root certificates with the root certificates from the system.

**Comment by francisdb** [comment]
This is a workaround on host level, but of course not recommended.

```scala
  // WARNING: This is dangerous, only use on host level, never globally
  val trustfulSslContext: SSLContext = {

    object NoCheckX509TrustManager extends X509TrustManager {
      override def checkClientTrusted(chain: Array[X509Certificate], authType: String) = ()
      override def checkServerTrusted(chain: Array[X509Certificate], authType: String) = ()
      override def getAcceptedIssuers = Array[X509Certificate]()
    }

    val context = SSLContext.getInstance("TLS")
    context.init(Array[KeyManager](), Array(NoCheckX509TrustManager), null)
    context
  }
  val noCertificateCheckContext = HttpsContext(trustfulSslContext)

  val netatmoApiPoolClientFlow = Http().cachedHostConnectionPoolTls[Int]("api.netatmo.net", httpsContext = Some(noCertificateCheckContext))
```

**Comment by jrudolph** [comment]
Btw. there's a test that shows how to add single (root) certificates to the trust manager:

https://github.com/akka/akka/blob/a3c22e2bffd50b66515f47247ecd7111c9b19e91/akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala#L36

**Comment by francisdb** [comment]
@jrudolph thanks, even better :+1:

**Comment by francisdb** [comment]
@jrudolph using that test code I get 
```
java.lang.RuntimeException: Delegated task threw Exception/Error
root 	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1429)
root 	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
root 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
root 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
root 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
root 	at akka.stream.impl.io.SslTlsCipherActor.akka$stream$impl$io$SslTlsCipherActor$$doUnwrap(SslTls.scala:376)
...
Caused by: java.lang.NullPointerException: null
root 	at sun.net.util.IPAddressUtil.textToNumericFormatV4(IPAddressUtil.java:48)
root 	at sun.net.util.IPAddressUtil.isIPv4LiteralAddress(IPAddressUtil.java:238)
root 	at sun.security.util.HostnameChecker.isIpAddress(HostnameChecker.java:124)
root 	at sun.security.util.HostnameChecker.match(HostnameChecker.java:92)
root 	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
```

Want me to create a new ticket for this?
Found this related stackoverflow [issue](http://stackoverflow.com/questions/13390964/java-ssl-fatal-error-80-unwrapping-net-record-after-adding-the-https-en) that points to `SSLContext.createSSLEngine(targetHost, targetPort)` needing non-null host and port

**Comment by ktoso** [comment]
Since we have a discussion going here, I'll recopen this ticket

**Comment by jrudolph** [comment]
This looks as if you are trying to use `setEndpointIdentificationAlgorithm` (as hinted to in the example). In theory, this is correct (and important for custom https configurations to be secure) but does not yet work with akka-http 1.0 and will likely lead to the exception you are getting.

**Comment by francisdb** [comment]
@jrudolph I can confirm this works using HttpsContext(context) without that custom SSLParameters but then could you be a bit more specific on what might not be secure?

**Comment by jrudolph** [comment]
See #18062. The hostname in the certificate is not checked against the expected one without that line.

**Comment by francisdb** [comment]
Thanks. Anything left for this ticket, I think we can close it?

**Comment by francisdb** [comment]
In fact 2 of the 3 api's I tried connecting to had this issue. The first one is mentioned above. The second one was a certificate using an unavailable cypher suite due to import control restrictions (JDK8).
Fixed by patching the JDK using "(JCE) Unlimited Strength Jurisdiction Policy Files"

**Comment by ktoso** [comment]
I'll keep it open as a reminder of making the `SSLContext ` config simpler or documenting it more. 
Thanks!

**Comment by francisdb** [comment]
I can confirm that with 2.0-M1 this now throws a proper exception instead of  `RuntimeException: Unexpected disconnect`

**Comment by ktoso** [comment]
Excellent, thanks for confirming @francisdb! So I assume this ticket as resolved
