### ISSUE TITLE
doc: Akka persistence complains about missing configuration which is present

### ISSUE THREAD

**Issue by reinierl** [akka/akka#18342]
When I configure akka-persistence to use a LevelDB journal plugin as documented on e.g. http://doc.akka.io/docs/akka/2.4.0-RC1/scala/persistence.html#Local_LevelDB_journal, it fails with:

```
[info] [ERROR] [08/27/2015 16:23:14.630] [nuvveproxysystem-akka.actor.default-dispatcher-6] [akka://nuvveproxysystem/user/cpmanager] requirement failed: 'reference.conf' is missing persistence plugin config path: 'leveldb'
[info] akka.actor.ActorInitializationException: exception during creation
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:605)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:460)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:482)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

the relevant reference.conf part is:

```
akka {
  persistence {
    journal {
      plugin = "leveldb"

      leveldb {
        dir = "target/persistence/journal"
      }
    }

    snapshot-store.local.dir = "target/persistence/snapshots"
  }
}
```

If I add the full leveldb plugin configuration at the root level in the config, it starts working. That is when the reference.conf contains this:

```
akka {
  persistence {
    journal {
      plugin = "leveldb"

      leveldb {
        dir = "target/persistence/journal"
      }
    }

    snapshot-store.local.dir = "target/persistence/snapshots"
  }
}

leveldb {
  dir = "target/persistence/journal"
  checksum: "off"
  class: "akka.persistence.journal.leveldb.LeveldbJournal"
  dir: "target/persistence/journal"
  fsync: "on"
  native: "on"
  plugin-dispatcher : "akka.persistence.dispatchers.default-plugin-dispatcher"
  replay-dispatcher : "akka.persistence.dispatchers.default-replay-dispatcher"
}
```
Either the documentation or the configuration validation is broken here. This looks like it has something to do with the resolution of #18153.

**Comment by patriknw** [comment]
The documentation must be outdated. It should be the full config path, i.e.

    plugin = akka.persistence.journal.leveldb

Where exactly did you see `plugin = leveldb` in the documentation?

I couldn't find that setting at all in the leveldb section of the docs, so we should add that.

**Comment by aamir-f** [comment]
Sometime,  we had not set the resources directory as Resources Root.
