### ISSUE TITLE
asyncWriteMessages calls with empty messages param

### ISSUE THREAD

**Issue by prettynatty** [akka/akka#18704]
I am using akka-persistence 2.4.0 with dnvriend/akka-persistence-jdbc.
Sometimes I catch weird problems when my application falls into ask-timeout hell.
I noticed that problems start right after SQL error log about invalid query, like (simplified): `INSERT INTO journal VALUES`. More here: dnvriend/akka-persistence-jdbc/pull/27. After that – no more akka-level or persistence-level exceptions, jsut applicaiton-level ask timeouts.
So, it seems that sometimes `asyncWriteMessages` is being called with empty `messages` param. To ensure and see stacktrace, I  added `throw new AbstractMethodError("wow")` in `asyncWriteMessages` in case when `messages` are empty. Here is stacktrace:
```
22:19:45.864UTC ERROR a.a.ActorSystemImpl akka.actor.ActorSystemImpl(actor-server-test)   Uncaught error from thread [actor-server-test-akka.persistence.dispatchers.default-plugin-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: wow
	at akka.persistence.jdbc.journal.JdbcSyncWriteJournal$class.asyncWriteMessages(JdbcSyncWriteJournal.scala:32) ~[akka-persistence-jdbc_2.11.jar:1.2.1-SNAPSHOT]
	at akka.persistence.jdbc.journal.PostgresqlSyncWriteJournal.asyncWriteMessages(Journals.scala:35) ~[akka-persistence-jdbc_2.11.jar:1.2.1-SNAPSHOT]
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66) ~[akka-persistence_2.11-2.4.0.jar:na]
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66) ~[akka-persistence_2.11-2.4.0.jar:na]
	at akka.pattern.CircuitBreaker$State$class.materialize$1(CircuitBreaker.scala:298) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:315) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:363) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:371) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:115) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1.liftedTree1$1(AsyncWriteJournal.scala:66) ~[akka-persistence_2.11-2.4.0.jar:na]
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1.applyOrElse(AsyncWriteJournal.scala:66) ~[akka-persistence_2.11-2.4.0.jar:na]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:0.13.8]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.persistence.jdbc.journal.PostgresqlSyncWriteJournal.aroundReceive(Journals.scala:35) ~[akka-persistence-jdbc_2.11.jar:1.2.1-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:494) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.11-2.4.0.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.11-2.4.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
```

In further investigation I found that it happens each time I use my helper:

```scala
final def persistStashingReply[R](es: immutable.Seq[Event], state: State)(f: immutable.Seq[Event] ⇒ Future[R]): Unit = {
    val replyTo = sender()

    log.debug("[persistStashingReply], events {}", es)
    context become stashing(state)

    persistAllAsync(es)(_ ⇒ ())

    deferAsync(()) { _ ⇒
      f(es) pipeTo replyTo onComplete {
        case Success(_) ⇒
          unstashAndWorkBatch(es, state)
        case Failure(e) ⇒
          log.error(e, "Failure while processing event {}", e)
          unstashAndWorkBatch(es, state)
      }
    }
  }

private final def unstashAndWorkBatch(es: immutable.Seq[Event], state: State): Unit = self ! UnstashAndWorkBatch(es, state)

protected final def stashingBehavior: Receive = {
    case UnstashAndWork(evt, s) ⇒
      context become working(updatedState(evt, s))
      unstashAll()
    case UnstashAndWorkBatch(es, s) ⇒
      val newState = es.foldLeft(s) {
        case (acc, e) ⇒
          log.debug("Updating state: {} with event: {}", acc, e)
          updatedState(e, acc)
      }
      context become working(newState)
      unstashAll()
    case msg ⇒
      log.warning("Stashing: {}", msg)
      stash()
  }
```

Callback `f` passed to `persistStashingReply` does nothing with actor state, it just makes some async DB queries.

**Comment by prettynatty** [comment]
Worth to be noted that events passed to `persistStashingReply` are saved ok, empty `asyncWriteMessages` follows this successful write, according to logs:
```
22:19:45.844UTC DEBUG i.a.s.g.GroupProcessor akka.tcp://actor-server-test@127.0.0.1:5920/system/sharding/GroupProcessor/10/1912101810   [persistStashingReply], events Vector(TSEvent(2015-10-12T01:19:45.842+03:00,BecamePublic()), TSEvent(2015-10-12T01:19:45.843+03:00,AboutUpdated(Some(Public group description))))
22:19:33.650UTC DEBUG s.StatementExecutor$$anon$1 akka.persistence.Persistence(akka://actor-server-test)   SQL execution completed

  [SQL Execution]
   INSERT INTO public.journal (persistence_id, sequence_number, marker, message, created) VALUES ('Group-1912101810',3,'A','ChgIgBsSEwhkEg8Isvbzx4UqEgYI+qsBEgAQAxoQR3JvdXAtMTkxMjEwMTgxMGokOGYzN2VmZGQtMzQ0MC00MzExLWIyMzItZDFm... (112)', current_timestamp),('Group-1912101810',4,'A','CjIIgBsSLQhkEikIs/bzx4UqEiAI+6sBEhoKGFB1YmxpYyBncm91cCBkZXNjcmlwdGlvbhAEGhBHcm91cC0xOTEyMTAxODEwaiQ4... (148)', current_timestamp); (5 ms)

  [Stack Trace]
    ...
    akka.persistence.jdbc.journal.GenericStatements$class.writeMessages(Statements.scala:88)
    akka.persistence.jdbc.journal.PostgresqlSyncWriteJournal.writeMessages(Journals.scala:35)
    akka.persistence.jdbc.journal.JdbcSyncWriteJournal$$anonfun$asyncWriteMessages$1.apply(JdbcSyncWriteJournal.scala:30)
    akka.persistence.jdbc.journal.JdbcSyncWriteJournal$$anonfun$asyncWriteMessages$1.apply(JdbcSyncWriteJournal.scala:30)
    scala.util.Try$.apply(Try.scala:192)
    akka.persistence.jdbc.journal.JdbcSyncWriteJournal$class.asyncWriteMessages(JdbcSyncWriteJournal.scala:30)
    akka.persistence.jdbc.journal.PostgresqlSyncWriteJournal.asyncWriteMessages(Journals.scala:35)
    akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66)
    akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66)
    akka.pattern.CircuitBreaker$State$class.materialize$1(CircuitBreaker.scala:298)
    akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:315)
    akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:363)
    akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:371)
    akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:115)
    akka.persistence.journal.AsyncWriteJournal$$anonfun$1.liftedTree1$1(AsyncWriteJournal.scala:66)
    ...

Uncaught error from thread [actor-server-test-akka.persistence.dispatchers.default-plugin-dispatcher-19] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[actor-server-test]
java.lang.AbstractMethodError: wow
```

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by patriknw** [comment]
Where does `java.lang.AbstractMethodError: wow` come from? Do you use incompatible versions?

**Comment by prettynatty** [comment]
As I said, I've put it into `asyncWriteMessages` of akka-persistence-jdbc to see a stacktrace.

**Comment by prettynatty** [comment]
Unfortunately I have to use insane debug methods as Intellij Idea has some problems with making scala projects which contain generated sources :)

**Comment by ddispaltro** [comment]
I noticed that when an exception in a PersistentActor was thrown, the same behavior would occur, empty messages sent to journal.  The way the leveldb driver is written it maps over the list so basically nothing would happen.  Whereas in the jdbc journals it constructs an insert over the flattened batch, which would throw the error. Light on details but here's the issue, okumin/akka-persistence-sql-async#10 

Side note, I don't use `persistAsync`

**Comment by patriknw** [comment]
@prettynatty is this still a relevant issue? We fixed something to persistAll(Nil) in https://github.com/akka/akka/issues/18728 in 2.4.1
