### ISSUE TITLE
groupedWithin throws ClassCastException when called from Flow

### ISSUE THREAD

**Issue by goldv** [akka/akka#18701]
The following works ok:

`Source(1 to 10).groupedWithin(10, 10 seconds)`

This however throws ClassCastException

`Flow[Int].groupedWithin(10, 10 seconds)`

Exception in thread "main" java.lang.ClassCastException: akka.stream.stage.GraphStageWithMaterializedValue$$anon$1 cannot be cast to akka.stream.scaladsl.Flow
	at akka.stream.scaladsl.Flow.viaMat(Flow.scala:40)
	at akka.stream.scaladsl.Flow.viaMat(Flow.scala:26)
	at akka.stream.scaladsl.FlowOps$class.via(Flow.scala:339)
	at akka.stream.scaladsl.Flow.via(Flow.scala:26)
	at akka.stream.scaladsl.FlowOps$class.groupedWithin(Flow.scala:628)
	at akka.stream.scaladsl.Flow.groupedWithin(Flow.scala:26)
	at StreamLab$.delayedEndpoint$StreamLab$1(StreamLab.scala:47)
	at StreamLab$delayedInit$body.apply(StreamLab.scala:15)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at StreamLab$.main(StreamLab.scala:15)
	at StreamLab.main(StreamLab.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by ktoso** [comment]
Ouch, I can confirm this is a problem on the current streams `HEAD` - thanks for reporting!

**Comment by drewhk** [comment]
Yes, I know what is the issue. It is actually fixed, but the PR has not yet been merged.

**Comment by patriknw** [comment]
@drewhk if this is fixed please close

**Comment by drewhk** [comment]
not yet, it is still in my mega-PR

**Comment by viktorklang** [comment]
Works on release-2.3-dev right now:

scala> startSystem(false)
[DEBUG] [10/26/2015 12:35:40.945] [run-main-0] [EventStream(akka://repl)] logger log1-Logging$DefaultLogger started
[DEBUG] [10/26/2015 12:35:40.946] [run-main-0] [EventStream(akka://repl)] Default Loggers started
don’t forget to system.shutdown()!

scala> import akka.stream._
import akka.stream._

scala> import akka.stream.scaladsl._
import akka.stream.scaladsl._

scala> Flow[Int].groupedWithin(10, 10 seconds)
res1: akka.stream.scaladsl.Flow[Int,scala.collection.immutable.Seq[Int],Unit] = akka.stream.scaladsl.Flow@1cb50b44

scala> implicit val m = ActorMaterializer()
m: akka.stream.ActorMaterializer = ActorMaterializerImpl(akka://repl,akka.stream.ActorMaterializerSettings@77d5970e,akka.dispatch.Dispatchers@132d965e,Actor[akka://repl/user/$a#-1267129239],false,0,flow,Optimizations(false,false,false,false))

scala> Source(1 to 10) via res1 to Sink.foreach(println)
res2: akka.stream.scaladsl.RunnableGraph[Unit] =
RunnableGraph(
 Module: unnamed
 Modules:    iterableSource
   groupedWithin
   akka.stream.impl.StreamLayout$CopiedModule
 Downstreams:
    SingleSource.out -> Flow.in
   Flow.out -> in
   out -> Flow.in
 Upstreams:
    Flow.in -> SingleSource.out
   in -> Flow.out
   Flow.in -> out
      )

**Comment by viktorklang** [comment]
I presume that #18700 fixed it.

**Comment by drewhk** [comment]
Ah, yes, the fix is in your PR actually

**Comment by viktorklang** [comment]
Long live #18700!
