### ISSUE TITLE
peristAll throws when nil

### ISSUE THREAD

**Issue by ahjohannessen** [akka/akka#18728]
If one invokes `persistAll` with an empty sequence it will cause the persistent actor to crash. Repro:

```scala
import scala.io.StdIn
import akka.actor.{Props, ActorSystem}
import akka.persistence.PersistentActor

object OhNoes extends App {

  val system = ActorSystem("Crash")
  system.actorOf(Props[Persister]) ! "Oh Noes"

  StdIn.readLine()
  system.terminate()

  class Persister extends PersistentActor {
    def persistenceId  = "crash-bob"
    def receiveCommand = { case "Oh Noes" ⇒ persistAll(Nil)(_ ⇒ ()) }
    def receiveRecover = { case x ⇒ }
  }
}
```

Exception being thrown:

```
[ERROR] [...] [Crash-akka.actor.default-dispatcher-4] [akka://Crash/user/$a] tail of empty list
java.lang.UnsupportedOperationException: tail of empty list
	at scala.collection.immutable.Nil$.tail(List.scala:422)
	at scala.collection.immutable.Nil$.tail(List.scala:417)
	at akka.persistence.AtomicWrite.<init>(Persistent.scala:44)
	at akka.persistence.Eventsourced$class.persistAll(Eventsourced.scala:310)
...
```

One can imagine that `C => S => Err \/ Seq[E]` is a common use case where issuing a command may result in no event. The fix is easily done in user land like:

```scala
    if(evts.isEmpty) done else {
      persistAll(evts)(applyEvent)
      deferAsync()(_ ⇒ done)
    }
```

But why not let Akka do the right thing and allow for the user to:

```scala
  persistAll(evts)(applyEvent)
  deferAsync()(_ ⇒ done)
```

ping @ktoso @patriknw

**Comment by patriknw** [comment]
Good catch.

**Comment by ktoso** [comment]
Thanks for reporting @ahjohannessen, great catch!

**Comment by ahjohannessen** [comment]
:+1:

**Comment by ahjohannessen** [comment]
:+1:
