### ISSUE TITLE
FAILED: RecipeKeepAlive

### ISSUE THREAD

**Issue by ktoso** [akka/akka#18735]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3923/consoleFull

```
info] Recipe for injecting keepalive messages
[info] - must work *** FAILED *** (43 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(ByteString(11)), found OnNext(ByteString(3))
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:339)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:252)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RecipeKeepAlive.scala:55)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:11)
[info]   at docs.stream.cookbook.RecipeKeepAlive$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RecipeKeepAlive.scala:11)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
```

**Comment by viktorklang** [comment]
@ktoso I think I fixed this with #18700

**Comment by ktoso** [comment]
Ok let's close it, and if it pops up again we'll open a new itcket and investigate

**Comment by viktorklang** [comment]
@ktoso I'm almost 100% sure

**Comment by rkuhn** [comment]
This test cannot be fixed, the recipe itself is flawed in that its quantitative behavior depends on random (un)fairness of the GraphInterpreter. The recipe and tests shall be replaced.

**Comment by drewhk** [comment]
There should be a built in op for this instead (pseudocode):

    idleInject[B >: T](maxIdlePeriod: FiniteDuration, inject: () => B): Source[B]
