### ISSUE TITLE
FAILED: GraphZipSpec

### ISSUE THREAD

**Issue by rkuhn** [akka/akka#18756]
possibly flaky: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/3901/consoleFull

~~~
[info] Zip
[info] - must work in the happy case *** FAILED *** (3 seconds, 32 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:319)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply(GraphZipSpec.scala:48)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply(GraphZipSpec.scala:25)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(GraphZipSpec.scala:25)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(GraphZipSpec.scala:25)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(GraphZipSpec.scala:25)
~~~

**Comment by ktoso** [comment]
Another one

```
nfo] - must work in the happy case *** FAILED *** (3 seconds, 37 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:319)
[info]   at akka.stream.scaladsl.FlowZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$6.apply(FlowZipSpec.scala:36)
[info]   at akka.stream.scaladsl.FlowZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$6.apply(FlowZipSpec.scala:22)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.FlowZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FlowZipSpec.scala:22)
[info]   at akka.stream.scaladsl.FlowZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FlowZipSpec.scala:22)
[info]   at akka.stream.scaladsl.FlowZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FlowZipSpec.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
```

**Comment by drewhk** [comment]
Closing this as this might be one of the bugs that @rkuhn fixed (especially the double-completion one). Reopen if happens again.

**Comment by ktoso** [comment]
Failed again on fresh PR:


```
[info] GraphZipSpec:
Coroner Thread Count starts at 18 in akka.stream.scaladsl.GraphZipSpec
[info] Zip
[info] - must work in the happy case *** FAILED *** (3 seconds, 34 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:329)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply(GraphZipSpec.scala:50)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply(GraphZipSpec.scala:25)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(GraphZipSpec.scala:25)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(GraphZipSpec.scala:25)
[info]   at akka.stream.scaladsl.GraphZipSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(GraphZipSpec.scala:25)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:55)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
```

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4085/consoleFull

**Comment by drewhk** [comment]
Ok, will look into it.
