### ISSUE TITLE
FAILED: SurviveNetworkInstabilitySpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18767]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/154/consoleFull

```
[JVM-1] - must heal after unreachable when ring is changed *** FAILED *** (59 seconds, 941 milliseconds)
[JVM-1]   Set(Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:33066, status = Up)) did not equal Set() (MultiNodeClusterSpec.scala:300)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitAllReachable$1.apply$mcV$sp(MultiNodeClusterSpec.scala:300)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitAllReachable$1.apply(MultiNodeClusterSpec.scala:300)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitAllReachable$1.apply(MultiNodeClusterSpec.scala:300)
[JVM-1]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
[JVM-1]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
[JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:735)
[JVM-1]   at akka.cluster.MultiNodeClusterSpec$class.awaitAllReachable(MultiNodeClusterSpec.scala:300)
[JVM-1]   at akka.cluster.SurviveNetworkInstabilitySpec.awaitAllReachable(SurviveNetworkInstabilitySpec.scala:79)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3378/consoleFull

**Comment by johanandren** [comment]
Was different test case though.

```
- must continue and move Joining to Up after downing of one half *** FAILED *** (59 seconds, 905 milliseconds)
[JVM-3]   Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:48642, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:56942, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:33661, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a3.moxie:38500, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:41308, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:59914, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:40527) did not equal Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a3.moxie:38500, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a6.moxie:41308, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:48642, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@a5.moxie:40527) (SurviveNetworkInstabilitySpec.scala:333)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-3]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41$$anonfun$apply$mcV$sp$47$$anonfun$apply$mcV$sp$48.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:333)
```

**Comment by ktoso** [comment]
Here we go again: 


```
[JVM-4] - must continue and move Joining to Up after downing of one half *** FAILED *** (59 seconds, 920 milliseconds)
[JVM-4]   Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:47007, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:33309, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:49844, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:59612, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:50063, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:46698, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:57077) did not equal Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:46698, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:50063, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:49844, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:33309) (SurviveNetworkInstabilitySpec.scala:333)
[JVM-4]   org.scalatest.exceptions.TestFailedException:
[JVM-4]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-4]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41$$anonfun$apply$mcV$sp$47$$anonfun$apply$mcV$sp$48.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:333)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41$$anonfun$apply$mcV$sp$47$$anonfun$apply$mcV$sp$48.apply(SurviveNetworkInstabilitySpec.scala:333)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41$$anonfun$apply$mcV$sp$47$$anonfun$apply$mcV$sp$48.apply(SurviveNetworkInstabilitySpec.scala:333)
[JVM-4]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:265)
[JVM-4]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:276)
[JVM-4]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:734)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41$$anonfun$apply$mcV$sp$47.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:333)
[JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:335)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41.apply$mcV$sp(SurviveNetworkInstabilitySpec.scala:330)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41.apply(SurviveNetworkInstabilitySpec.scala:302)
[JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$1$$anonfun$apply$mcV$sp$40$$anonfun$apply$mcV$sp$41.apply(SurviveNetworkInstabilitySpec.scala:302)
```

https://jenkins.akka.io:8498/job/akka-nightly/3221/consoleFull

**Comment by drewhk** [comment]
` must continue and move Joining to Up after downing of one half`

https://jenkins.akka.io:8498/job/akka-nightly/3238/consoleFull

**Comment by patriknw** [comment]
I have been analyzing this. Rather interesting.

The test does this:
* splits the cluster into [1,3,4,8][5,6,7].
* 8 is joining to 3
* 5,6,7 is downed on 4

1 is leader, and then 8 becomes new leader

```
[fourth] [WARN] [04/16/2016 04:30:01.031] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-15] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, status = Up)]
[third] [WARN] [04/16/2016 04:30:01.060] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-2] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth, status = Up)]
[fourth] [INFO] [04/16/2016 04:30:01.376] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth] - Marking unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth] as [Down]
[fourth] [INFO] [04/16/2016 04:30:01.378] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth] - Marking unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth] as [Down]
[fourth] [INFO] [04/16/2016 04:30:01.379] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth] - Marking unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh] as [Down]
[third] [INFO] [04/16/2016 04:30:01.518] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third] - Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] is JOINING, roles []
[first] [INFO] [04/16/2016 04:30:01.582] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Leader is moving node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] to [Up]
[first] [INFO] [04/16/2016 04:30:01.582] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Leader is removing unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth]
[first] [INFO] [04/16/2016 04:30:01.582] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Leader is removing unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth]
[first] [INFO] [04/16/2016 04:30:01.582] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Leader is removing unreachable node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh]
[eighth] [INFO] [04/16/2016 04:30:01.637] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Welcome from [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third]
[third] [WARN] [04/16/2016 04:30:02.059] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-17] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth, status = Up)]
[third] [WARN] [04/16/2016 04:30:05.060] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, status = Up)]
[eighth] [INFO] [04/16/2016 04:30:06.047] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Leader can currently not perform its duties, reachability status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (12), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (13), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (14)], member status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth Up seen=true]
[first] [WARN] [04/16/2016 04:30:07.079] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-15] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh, status = Up)]
[fourth] [WARN] [04/16/2016 04:30:07.531] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-14] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, status = Up)]
[first] [WARN] [04/16/2016 04:30:07.580] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-4] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth, status = Up)]
[eighth] [WARN] [04/16/2016 04:30:07.644] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-2] [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth/system/cluster/core/daemon] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Marking node(s) as UNREACHABLE [Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth, status = Up), Member(address = akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth, status = Up)]
[eighth] [INFO] [04/16/2016 04:30:14.042] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Leader can currently not perform its duties, reachability status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (1), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (2), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (25), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (26), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (12), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (13), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (14), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (11), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (12)], member status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth Up seen=true]
[eighth] [INFO] [04/16/2016 04:30:26.041] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Leader can currently not perform its duties, reachability status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (1), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (2), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (25), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (26), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (12), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (13), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (14), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (11), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (12)], member status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth Up seen=true]
[eighth] [INFO] [04/16/2016 04:30:38.041] [SurviveNetworkInstabilitySpec-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://SurviveNetworkInstabilitySpec)] Cluster Node [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth] - Leader can currently not perform its duties, reachability status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (1), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (2), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (25), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (26), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (12), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth: Unreachable [Unreachable] (13), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (14), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh: Unreachable [Unreachable] (11), akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth -> akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth: Unreachable [Unreachable] (12)], member status: [akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@seventh Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@eighth Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@first Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fifth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@third Up seen=true, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@sixth Up seen=false, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@fourth Up seen=true]
```

The problem is that the removal is reverted, probably due to some gossip merge, and then the test is stuck because the unreachable nodes on the other side are "back" in the membership.

This is probably not very serious, since in a real system you would perform the downing again, but it's worth investigating and the scenario is rather minimized.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6404/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3989/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1634/consoleFull

**Comment by patriknw** [comment]
I'm pretty sure this is the same as found in https://github.com/akka/akka/pull/21247#issuecomment-241646963

One scenario when this can happen:

* two Joining nodes, node-4 and node-5 and two old Up node-1 and node-3.
* the oldest node-1 is killed
* node-1 is auto-downed and removed as expected
* node-4 receives a Gossip that is in conflict its local
  * the local contains node-1 Up, the remote doesn't contain node-1, since it was removed
  * the merge for that means that node-1 Up wins and that adds node-1 back to the membership
  * note that if node-1 had status Down or Exiting it would not come back

The reason node-1 is removed without node-4 and node-5 seeing it as Down is that Joining nodes are excluded in the `convergence` rule (for other good reasons).

I don't see an easy way to improve that part without introducing some kind of removed tombstones. I don't think it's a big deal that the removal was reverted.
