### ISSUE TITLE
UntypedProducerActor stops sending messages for 5 minutes?

### ISSUE THREAD

**Issue by khoanguyen123** [akka/akka#18794]
I am using akka java API 2.4.0 and have the following producer:

    public class ProvisioningResponseWriter extends UntypedProducerActor {
        private final String uri;

        public ProvisioningResponseWriter(String uri) {
            this.configProxy();  // configure http(s) proxy on camel context
            this.uri = uri;
        }

        public Object onTransformOutgoingMessage(Object msg) {
            if (msg instanceof String) {
                log.debug("Received: {}", (String) msg);
            }
            return msg;
        }

        @Override
        public String getEndpointUri() {
            return this.uri;
        }

    }
The uri is something like http://somewhere.com

When the host at the URI is not responding for any reason, my app catches a "Stream Closed" exception and restarts the actor, which is fine and good. The problem is that if the "Stream Closed" happens more than a couple times, this actor doesn't seem to send any more message to the camel endpoint for about 5 minutes (confirmed by watching packets on the wire.) Is this an expected behavior? If yes, how do I change this behavior to always send message or reduce the back-off to just a few seconds?

**Comment by khoanguyen123** [comment]
Some stack trace captured in our production environment this morning. After this, no more outgoing messages seen on the wire even though the UntypedProducerActor did receive all messages. We had to restart our app!


[2015-10-27 07:53:54.081] - 14029  WARN [pim-akka.actor.default-dispatcher-7] --- o.a.c.c.h.HttpProducer: Cannot close: Extracting response body. Reason: Stream closed
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170) ~[na:1.8.0_51]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:184) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:369) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ContentLengthInputStream.close(ContentLengthInputStream.java:118) ~[commons-httpclient-3.1.jar:na]
        at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.AutoCloseInputStream.notifyWatcher(AutoCloseInputStream.java:194) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.AutoCloseInputStream.close(AutoCloseInputStream.java:158) ~[commons-httpclient-3.1.jar:na]
        at org.apache.camel.util.IOHelper.close(IOHelper.java:326) ~[camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.component.http.HttpProducer.doExtractResponseBodyAsStream(HttpProducer.java:322) [camel-http-2.15.2.jar:2.15.2]
[2015-10-27 07:53:54.081] - 14029  WARN [pim-akka.actor.default-dispatcher-7] --- o.a.c.c.h.HttpProducer: Cannot close: Extracting response body. Reason: Stream closed
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170) ~[na:1.8.0_51]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:170) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ContentLengthInputStream.read(ContentLengthInputStream.java:184) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ChunkedInputStream.exhaustInputStream(ChunkedInputStream.java:369) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.ContentLengthInputStream.close(ContentLengthInputStream.java:118) ~[commons-httpclient-3.1.jar:na]
        at java.io.FilterInputStream.close(FilterInputStream.java:181) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.AutoCloseInputStream.notifyWatcher(AutoCloseInputStream.java:194) ~[commons-httpclient-3.1.jar:na]
        at org.apache.commons.httpclient.AutoCloseInputStream.close(AutoCloseInputStream.java:158) ~[commons-httpclient-3.1.jar:na]
        at org.apache.camel.util.IOHelper.close(IOHelper.java:326) ~[camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.component.http.HttpProducer.doExtractResponseBodyAsStream(HttpProducer.java:322) [camel-http-2.15.2.jar:2.15.2]
        at org.apache.camel.component.http.HttpProducer.extractResponseBody(HttpProducer.java:294) [camel-http-2.15.2.jar:2.15.2]
        at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:206) [camel-http-2.15.2.jar:2.15.2]
        at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:156) [camel-http-2.15.2.jar:2.15.2]
        at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) [camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:129) [camel-core-2.15.2.jar:2.15.2]
        at akka.camel.ProducerSupport$ProducerChild.produce(Producer.scala:137) [akka-camel_2.11-2.3.12.jar:na]
        at akka.camel.ProducerSupport$ProducerChild$$anonfun$receive$1.applyOrElse(Producer.scala:111) [akka-camel_2.11-2.3.12.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) [akka-actor_2.11-2.3.12.jar:na]
        at akka.camel.ProducerSupport$ProducerChild.aroundReceive(Producer.scala:108) [akka-camel_2.11-2.3.12.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.5.jar:na]
[2015-10-27 07:53:54.083] - 14029 ERROR [pim-akka.actor.default-dispatcher-7] --- a.a.OneForOneStrategy: Stream closed
akka.camel.AkkaCamelException: Stream closed
        at akka.camel.ProducerSupport$$anonfun$produce$1.applyOrElse(Producer.scala:73) ~[akka-camel_2.11-2.3.12.jar:na]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.5.jar:na]
        at akka.camel.javaapi.UntypedProducerActor.onReceive(UntypedProducerActor.scala:51) ~[akka-camel_2.11-2.3.12.jar:na]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[akka-actor_2.11-2.3.12.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[akka-actor_2.11-2.3.12.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.5.jar:na]
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159) ~[na:1.8.0_51]
        at java.io.BufferedInputStream.available(BufferedInputStream.java:410) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.ContentLengthInputStream.available(ContentLengthInputStream.java:213) ~[commons-httpclient-3.1.jar:na]
        at java.io.FilterInputStream.available(FilterInputStream.java:168) ~[na:1.8.0_51]
        at org.apache.commons.httpclient.AutoCloseInputStream.available(AutoCloseInputStream.java:143) ~[commons-httpclient-3.1.jar:na]
        at org.apache.camel.util.IOHelper.copy(IOHelper.java:179) ~[camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.util.IOHelper.copy(IOHelper.java:169) ~[camel-core-2.15.2.jar:2.15.2]
        at org.apache.camel.util.IOHelper.copy(IOHelper.java:165) ~[camel-core-2.15.2.jar:2.15.2]

**Comment by rkuhn** [comment]
What’s the supervisorStrategy you apply to this Actor?

**Comment by khoanguyen123** [comment]
I use the default strategy, so it will be restarted. Even so, no messages are sent after the restart. I've spent a little more time on this, and have some updates:

My producer --> HTTPS proxy --> destination

If destination is not reachable, the proxy can't establish the 2nd leg of the connection and reset the 1st leg connection. My producer caught "Stream closed" exception and restarted, After a couple more of "Stream closed" exceptions, the producer is kind of stuck. No messages are sent to the wire. I have to bounce the whole application to get the flow working again...

**Comment by rkuhn** [comment]
I don’t have a good idea here; @RayRoestenburg what’s your take? Is this a Camel problem?
