### ISSUE TITLE
Exception thrown in akka-http 2.0-M1

### ISSUE THREAD

**Issue by jknight12882** [akka/akka#18882]
The following route worked fine with akka-http 1.0, scala 2.11.7, akka-actors 2.4.0

    path("api" / "v1.0" / "user") {
      get {
        complete("Success")
      }
    }

Exception with akka-http 2.0-M1

    16:25:46.395 [xxx-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorSystemImpl - Error during processing of request HttpRequest(HttpMethod(GET),http://localhost:50171/api/v1.0/user,List(Host: localhost:50171, Connection: keep-alive, Cache-Control: no-cache, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36, Postman-Token: b677162a-343f-b32b-ccd9-8c88cacbcbe3, Accept: */*, DNT: 1, Accept-Encoding: gzip, deflate, sdch, Accept-Language: en-US, en;q=0.8),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
    java.lang.NullPointerException: null
    at akka.http.scaladsl.server.Route$$anonfun$seal$1.apply(Route.scala:29) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.Route$$anonfun$seal$1.apply(Route.scala:29) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.Directive$$anonfun$addByNameNullaryApply$1$$anonfun$apply$11.apply(Directive.scala:122) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.Directive$$anonfun$addByNameNullaryApply$1$$anonfun$apply$11.apply(Directive.scala:122) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:27) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:23) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.Route$$anonfun$asyncHandler$1.apply(Route.scala:64) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.http.scaladsl.server.Route$$anonfun$asyncHandler$1.apply(Route.scala:63) ~[akka-http-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.MapAsync$$anon$7$$anon$8.onPush(Ops.scala:596) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:537) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:548) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:511) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$runBatch(ActorGraphInterpreter.scala:399) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:344) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.0.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:291) ~[akka-stream-experimental_2.11-2.0-M1.jar:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525) [akka-actor_2.11-2.4.0.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:494) [akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.0.jar:na]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.0.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by ktoso** [comment]
Thanks for reporting @jknight12882!
I can't confirm it's a problem with the route itself, could you paste the surrounding context of the directive? Any implicit error handlers? is it a `val`? are other things a `val`?

// minimal reproducer test I tried:

```scala
/*
 * Copyright (C) 2009-2014 Typesafe Inc. <http://www.typesafe.com>
 */

package akka.http.scaladsl.server.directives

import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport
import akka.http.scaladsl.marshallers.xml.ScalaXmlSupport
import akka.stream.scaladsl.Sink
import org.scalatest.FreeSpec
import scala.concurrent.{ Future, Promise }
import akka.http.scaladsl.marshallers.xml.ScalaXmlSupport._
import akka.http.scaladsl.marshalling._
import akka.http.scaladsl.server._
import akka.http.scaladsl.model._
import akka.http.impl.util._
import headers._
import StatusCodes._
import MediaTypes._
import scala.xml.NodeSeq
import akka.testkit.EventFilter

class RouteDirectivesSpec extends FreeSpec with GenericRoutingSpec {

  "The `complete` directive should" - {
    "do the thing" in {
      val routes = path("api" / "v1.0" / "user") {
        get {
          complete("Success")
        }
      }

      Get("/api/v1.0/user") ~> routes ~> check {
        status should ===(StatusCodes.OK)
        responseAs[String] should ===("Success")
      }
    }
  }
}

```

**Comment by jknight12882** [comment]
Here's some scaffolding code

    abstract class HttpService(implicit system: ActorSystem) {
      implicit val materializer = ActorMaterializer(namePrefix = Some("http-service"))
    
      def route: Flow[HttpRequest, HttpResponse, Unit]
    
      def runRoute(route: Route)(implicit exceptionHandler: ExceptionHandler = null,
                                 rejectionHandler: RejectionHandler = null): Flow[HttpRequest, HttpResponse, Unit] =
        Route.handlerFlow(route)
    
      def bindAndHandle(interface: String, port: Int = -1): Future[Http.ServerBinding] = {
        Http().bindAndHandle(route, interface = interface, port = port)
      }
    }

and 

    object UserHttpService {
      def apply(userService: ActorRef)(implicit system: ActorSystem): UserHttpService =
        new UserHttpService(userService)
    }
    
    class UserHttpService(val userService: ActorRef)(implicit system: ActorSystem) extends HttpService with UserRoute {
      def route = runRoute {
        userRoute
      }
    }
    
    trait UserRoute {
      def userService: ActorRef
    
      def userRoute: Route =
        path("api" / "v1.0" / "user") {
          get {
            complete("Success")
          }
        }
    }

**Comment by jknight12882** [comment]
Ah, figured it out. `Route.handlerFlow` signature changed. In 1.0, `rejectionHandler: RejectionHandler = null`. Now it's `rejectionHandler: RejectionHandler = RejectionHandler.default`

**Comment by ktoso** [comment]
Right exactly :-)
Seems like we can close this.

Be warry of nulls! For almost all things we have there's "default" or "no-op" defaults you can set instead of null (Actor.noSender being one notable omission in that rule, an unfortunate one but well...).

Happy hakking!
