### ISSUE TITLE
failed: MetricsBasedResizer

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18938]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3141/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/205/consoleFull

```
[info] - must record the performance log with the correct process speed *** FAILED *** (8 milliseconds)
[info]   java.util.NoSuchElementException: key not found: 2
[info]   at scala.collection.MapLike$class.default(MapLike.scala:228)
[info]   at scala.collection.AbstractMap.default(Map.scala:59)
[info]   at scala.collection.MapLike$class.apply(MapLike.scala:141)
[info]   at scala.collection.AbstractMap.apply(Map.scala:59)
[info]   at akka.routing.MetricsBasedResizerSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply$mcV$sp(MetricsBasedResizerSpec.scala:235)
[info]   at akka.routing.MetricsBasedResizerSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(MetricsBasedResizerSpec.scala:219)
[info]   at akka.routing.MetricsBasedResizerSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(MetricsBasedResizerSpec.scala:219)
```

**Comment by patriknw** [comment]
we fixed something in https://github.com/akka/akka/pull/19874

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3645/consoleFull
