### ISSUE TITLE
failed: LeveldbPersistentActorSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#18940]
some timing issue:

```
[info] - must reply to the original sender() of a command, even when using persistAsync *** FAILED *** (3 seconds, 500 milliseconds)
[info]   java.lang.AssertionError: assertion failed: block took 3.385 seconds, exceeding 3.000 seconds
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:313)
[info]   at akka.testkit.TestKit.within(TestKit.scala:735)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:322)
```

**Comment by patriknw** [comment]
closing because it has not reoccurred in a long time
