### ISSUE TITLE
FAILED: TcpSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19025]
(this was before merging the Fused tcp).

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4329/consoleFull

```
[info] - must shut down properly even if some accepted connection Flows have not been subscribed to *** FAILED *** (3 seconds, 31 milliseconds)
[WARN] [11/26/2015 16:11:31.439] [TcpSpec-akka.actor.default-dispatcher-15] [akka://TcpSpec/system/IO-TCP/selectors/$a/67] received dead letter from Actor[akka://TcpSpec/deadLetters]: ChannelReadable
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:107)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35$$anonfun$apply$mcV$sp$36.apply$mcV$sp(TcpSpec.scala:531)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35$$anonfun$apply$mcV$sp$36.apply(TcpSpec.scala:510)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35$$anonfun$apply$mcV$sp$36.apply(TcpSpec.scala:510)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35.apply$mcV$sp(TcpSpec.scala:510)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35.apply(TcpSpec.scala:510)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$35.apply(TcpSpec.scala:510)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.fo
```

**Comment by 2m** [comment]
Failed once after a long quiet period:

(Feb 27, 2016 2:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3539/consoleFull

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3606/consoleFull

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (1 second, 41 milliseconds)
[info]   akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

**Comment by ktoso** [comment]
Again here:

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (1 second, 29 milliseconds)
[info]   akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

**Comment by patriknw** [comment]
I also noticed this:
`[info] - must not thrown on unbind after system has been shut down *** FAILED *** (15 milliseconds)
[info]   akka.stream.StreamTcpException: Tcp command [Connect(localhost/127.0.0.1:35780,None,List(),None,true)] failed
`

In https://github.com/akka/akka/pull/20289

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3297/consoleFull

Another one case of `must not thrown on unbind after system has been shut down`
