### ISSUE TITLE
FAILED: MetricsBasedResizerSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19056]
```
- must stop an underutilizationStreak when fully utilized *** FAILED *** (18 milliseconds)
[info]   Some(UnderUtilizationStreak(2015-11-30T02:26:11.177,1)) was not empty (MetricsBasedResizerSpec.scala:140)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6589)
[info]   at akka.routing.MetricsBasedResizerSpec$$anonfun$3$$anonfun$apply$mcV$sp$7.apply$mcV$sp(MetricsBasedResizerSpec.scala:140)
```

https://jenkins.akka.io:8498/job/akka-nightly/2842/consoleFull

**Comment by patriknw** [comment]
we fixed something in https://github.com/akka/akka/pull/19874
