### ISSUE TITLE
errors from FlattenMerge during WS client Autobahn tests

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19072]
I'm setting up Autobahn tests on jenkins, and on the first run noticed some errors being printed from FlattenMerge.
It would seem they're harmless, the tests seem to have passed, though perhaps worth investigating nevertheless:

```
OK                64 ms 9.2.1   - Send binary message message with payload of length 64 * 2**10 (64k). ...
OK                92 ms 9.2.2   - Send binary message message with payload of length 256 * 2**10 (256k). ...
[ERROR] [12/02/2015 19:23:54.513] [default-akka.test.stream-dispatcher-10] [akka://default/user/StreamSupervisor-0/flow-2416-31-ws-message-api-ws-prepare-messages] Error during postStop in [akka.stream.impl.fusing.FlattenMerge@182939a5]
java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
	at akka.stream.stage.GraphStageLogic.interpreter(GraphStage.scala:321)
	at akka.stream.stage.GraphStageLogic$$anon$3.invoke(GraphStage.scala:837)
	at akka.stream.impl.fusing.LocalSink$Logic$1$$anonfun$4.apply(StreamOfStreams.scala:167)
	at akka.stream.impl.fusing.LocalSink$Logic$1$$anonfun$4.apply(StreamOfStreams.scala:167)
	at akka.stream.impl.fusing.LocalSinkSubscription.cancel(StreamOfStreams.scala:142)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1$$anonfun$postStop$1.apply(StreamOfStreams.scala:129)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1$$anonfun$postStop$1.apply(StreamOfStreams.scala:128)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1.postStop(StreamOfStreams.scala:128)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:630)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:607)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$runBatch(ActorGraphInterpreter.scala:408)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:380)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:292)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

cc @rkuhn

**Comment by ktoso** [comment]
We should have it as a jenkins job today I think, almost done.

**Comment by viktorklang** [comment]
Fixed?
