### ISSUE TITLE
Http client causes 'Cannot pull port twice' error

### ISSUE THREAD

**Issue by daniel-trinh** [akka/akka#19094]
I'm not 100% sure pipelining is the cause, although this started occuring when I set akka.http.client.host-connection-pool.pipelining-limit to something greater than 1.

A multi build project has been set up that can reproduce this, with two projects in the link below, one as a dummy echo server to receive http requests, and another sub project that uses akka http client to send requests to the echo server.

https://github.com/daniel-trinh/echo_server

This problem also occurs on sending requests to a server unrelated to akka-http, so I imagine this would be reproducible with any server that can accept requests from the client.

cc @ktoso
```
[ERROR] [12/04/2015 23:02:31.610] [vulcan-loader-akka.actor.default-dispatcher-14] [ActorSystem(vulcan-loader)] Outgoing request stream error
java.lang.IllegalArgumentException: requirement failed: Cannot pull port twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:408)
	at akka.http.impl.engine.client.PoolConductor$SlotSelector$$anon$1$$anonfun$1.apply$mcV$sp(PoolConductor.scala:149)
	at akka.stream.stage.GraphStageLogic$Emitting.followUp(GraphStage.scala:741)
	at akka.stream.stage.GraphStageLogic$EmittingSingle.onPull(GraphStage.scala:790)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:553)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:509)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$runBatch(ActorGraphInterpreter.scala:408)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:350)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:292)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ktoso** [comment]
Thanks for reporting, I've seen it once too during https://github.com/akka/akka/pull/18476
Definitely something we will fix soon. I'm not sure who's doing the illegal pull yet.

**Comment by concerned3rdparty** [comment]
I've encountered same issue when stream completes over websocket. I use the below method to communicate over websocket. 
upgrade.handleMessagesWithSinkSource(sinkUsesActor , basicSource)

**Comment by ktoso** [comment]
I'm trying your reproducer @daniel-trinh but so far with no luck.
Will dive deeper into the code of SlotSelector.

**Comment by ktoso** [comment]
Oh actually, I checked with your entire repo Daniel, and there it fails.
Seems it's using `2.0.M2` so quite some time ago... it may well be that this is now fixed. I'll investigate deeper.

**Comment by ktoso** [comment]
Here is another self contained reproducer:

```scala
/*
 * Copyright (C) 2009-2014 Typesafe Inc. <http://www.typesafe.com>
 */

package akka.http.scaladsl.server

import akka.http.scaladsl.marshallers.xml.ScalaXmlSupport
import akka.http.scaladsl.server.directives.Credentials
import akka.stream.scaladsl._
import com.typesafe.config.{ ConfigFactory, Config }
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.http.scaladsl.Http
import akka.stream.scaladsl.{ Sink, Source, Flow }
import akka.http.scaladsl.model.ws.{ WebsocketRequest, Message, TextMessage }
import scala.concurrent.Await
import scala.concurrent.duration._

object ConsumeWebSockets extends Directives {

  def main(args: Array[String]): Unit = {
    val testConf: Config = ConfigFactory.parseString("""
      akka.loglevel = DEBUG
      akka.log-dead-letters = on
      akka.stream.materializer.debug.fuzzing-mode = off
      """)
    implicit val system = ActorSystem("WebsocketsSystem", testConf)
    implicit val materializer = ActorMaterializer()
    import scala.concurrent.ExecutionContext.Implicits.global

    val bindingFuture = Http().bindAndHandle({
      get {
        handleWebsocketMessages(Flow[Message])
      }
    }, interface = "localhost", port = 8080)
    Await.ready(bindingFuture, 3.seconds)

    val (future, t) = Http().singleWebsocketRequest(
      //      WebsocketRequest("ws://echo.websocket.org"),
      WebsocketRequest("ws://127.0.0.1:8080"),
      Flow.fromSinkAndSource(
        Sink.foreach(println),
        Source.repeat(TextMessage("hello")).log("out").take(100)))

    future.foreach(println)

    readLine()
    bindingFuture.flatMap(_.unbind()).onComplete(_ ⇒ system.shutdown())
    system.shutdown()
  }

}
```

**Comment by drewhk** [comment]
I think this line is the problem

```
val tryPullCtx = () ⇒ if (nextSlot != -1) pull(ctxIn)
```

which is invoked after an emit: 

```
emit(out, SwitchCommand(ctx, slot), tryPullCtx)
```

This looks like a logic bug there, but I have to figure out what is going on.

**Comment by Birdflying1005** [comment]
I also recreated this error based on akka-http 10.0.3  akka 2.4.16 and scala 2.11.8: The error message is:

ERROR] [03/03/2017 15:51:18.270] [ServiceClusterSystem-akka.actor.default-dispatcher-5] [akka://ServiceClusterSystem/user/StreamSupervisor-4/flow-2-0-unknown-operation] Error in stage [akka.http.impl.engine.client.PoolSlot$SlotProcessor@7e0dc802]: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
java.lang.IllegalArgumentException: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1011)
	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1$$anon$4.onPull(PoolSlot.scala:181)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:754)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:660)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:414)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
