### ISSUE TITLE
FAILED: ScalaUdpMulticastSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19114]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3233/consoleFull

```
[info] ScalaUdpMulticastSpec:
[info] listener
[INFO] [12/07/2015 07:17:11.513] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-2] [akka://ScalaUdpMulticastSpec/user/$a] Bound to /0:0:0:0:0:0:0:0:38043
[INFO] [12/07/2015 07:17:11.522] [ScalaUdpMulticastSpec-akka.actor.default-dispatcher-3] [akka://ScalaUdpMulticastSpec/user/$b] Sending message to /ff02:0:0:0:0:0:fac0:ea69%docker0:38043
[info] - should send message back to sink *** FAILED *** (3 seconds, 63 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ohi
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalaUdpMulticastSpec.scala:39)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at docs.io.ScalaUdpMulticastSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ScalaUdpMulticastSpec.scala:21)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at docs.io.ScalaUdpMulticastSpec.withFixture(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at docs.io.ScalaUdpMulticastSpec.org$scalatest$BeforeAndAfter$$super$runTest(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[info]   at docs.io.ScalaUdpMulticastSpec.runTest(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at docs.io.ScalaUdpMulticastSpec.runTests(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at docs.io.ScalaUdpMulticastSpec.org$scalatest$WordSpecLike$$super$run(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at docs.io.ScalaUdpMulticastSpec.org$scalatest$BeforeAndAfter$$super$run(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
[info]   at docs.io.ScalaUdpMulticastSpec.run(ScalaUdpMulticastSpec.scala:18)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
```

**Comment by johanandren** [comment]
Duplicate of #16262 ?

**Comment by ktoso** [comment]
Yup
