### ISSUE TITLE
FAILED: FlowSplitWhenSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19139]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4454/consoleFull

```scala
[info] FlowSplitWhenSpec:
Coroner Thread Count starts at 17 in akka.stream.scaladsl.FlowSplitWhenSpec
[info] splitWhen
[info] - must work in the happy case (257 milliseconds)
[info] - must work when first element is split-by *** FAILED *** (43 milliseconds)
[info]   java.lang.AssertionError: assertion failed: received unexpected message OnComplete
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:566)
[info]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:562)
[info]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:718)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMsg(StreamTestKit.scala:502)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$9$$anon$2.<init>(FlowSplitWhenSpec.scala:91)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$9.apply(FlowSplitWhenSpec.scala:89)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$9.apply(FlowSplitWhenSpec.scala:89)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply$mcV$sp(FlowSplitWhenSpec.scala:88)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(FlowSplitWhenSpec.scala:88)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(FlowSplitWhenSpec.scala:88)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.stream.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
```

**Comment by viktorklang** [comment]
Still relevant?

**Comment by patriknw** [comment]
@drewhk do you think this can have been fixed by other things? Then close.

**Comment by drewhk** [comment]
not sure TBH

**Comment by patriknw** [comment]
ok, it's 5 months old, so closing for now
