### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: Region not registered

### ISSUE THREAD

**Issue by t3hnar** [akka/akka#19282]
Hi guys, sometimes after restarts we can see these exceptions:

```scala
23.12.15 20:45:25,584 ERROR [][][][][][coreservices-akka.actor.default-dispatcher-43][][] a.c.s.PersistentShardCoordinator - Exception in receiveRecover when replaying event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated] with sequence number [3104751] for persistenceId [/sharding/GameTableCoordinator].
java.lang.IllegalArgumentException: requirement failed: Region Actor[akka.tcp://***@***/system/sharding/GameTable#-73988119] not registered: State(Map(),Map(Actor[akka.tcp://***@***/system/sharding/GameTable#-1684526041] -> Vector()),Set(),Set(),false)
	at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.7.jar:na]
	at akka.cluster.sharding.ShardCoordinator$Internal$State.updated(ShardCoordinator.scala:289) ~[akka-cluster-sharding_2.11-2.4.1.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator$$anonfun$receiveRecover$1.applyOrElse(ShardCoordinator.scala:752) ~[akka-cluster-sharding_2.11-2.4.1.jar:na]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:441) ~[akka-persistence_2.11-2.4.1.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.1.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator.akka$persistence$Eventsourced$$super$aroundReceive(ShardCoordinator.scala:718) ~[akka-cluster-sharding_2.11-2.4.1.jar:na]
	at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:484) ~[akka-persistence_2.11-2.4.1.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:158) ~[akka-persistence_2.11-2.4.1.jar:na]
	at akka.cluster.sharding.PersistentShardCoordinator.aroundReceive(ShardCoordinator.scala:718) ~[akka-cluster-sharding_2.11-2.4.1.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.1.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.1.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.1.jar:na]
2
```

However worked fine with akka `2.3.x`, now `2.4.1`

**Comment by t3hnar** [comment]
Sometimes it needs to submit an issue to resolve it :)

**Comment by berardino** [comment]
@t3hnar how did you solve it ? we are experiencing the very same exact issue on latest version of akka 2.4.8 . Any suggestion ?

**Comment by t3hnar** [comment]
@berardino afaik the problem was in how we bind serialisation, thus we basically either serialise or deserialise in wrong way, I cannot recall details.
