### ISSUE TITLE
Websockets do not close socket

### ISSUE THREAD

**Issue by jknight12882** [akka/akka#19285]
Using a complex graph for `handleWebsocketMessages` causes the Websocket to not terminate appropriately when a client disconnects. It is held open until after `idle-timeout` has expired. akka 2.4.1 with akka-streams 2.0.1

Sample graph which demonstrates the issue

    Flow.fromGraph(GraphDSL.create(Source.actorRef[Message](5, OverflowStrategy.fail)) { implicit b =>
      materializedActor =>
        val sink = b.add(Sink.ignore)
        FlowShape(sink.in, materializedActor.out)
    })

The following sample graph DOES close the socket when a client disconnects, however it also causes an exception to be raised

    Flow.fromGraph(GraphDSL.create() { implicit b =>
      val bridge = b.add(Flow[Message].map(identity))

      FlowShape(bridge.in, bridge.out)
    })

Here is the exception that is raised when closing the socket

    2015-12-24 05:08:05,999 [xxx-akka.actor.default-dispatcher-3] ERROR akka.actor.ActorSystemImpl - Websocket handler failed while waiting for handler completion with empty.head
    java.lang.UnsupportedOperationException: empty.head
    at scala.collection.immutable.Vector.head(Vector.scala:193) ~[scala-library-2.11.7.jar:0.13.8]
    at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:90) ~[akka-http-core-experimental_2.11-2.0.1.jar:na]
    at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:89) ~[akka-http-core-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.Map.onPush(Ops.scala:27) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.Map.onPush(Ops.scala:26) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:54) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:617) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:480) ~[akka-actor_2.11-2.4.1.jar:na]
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495) ~[akka-stream-experimental_2.11-2.0.1.jar:na]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.1.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.1.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.1.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.1.jar:na]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.1.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by shayangz** [comment]
Team Akka, it would be great if you could help us out with this issue. Any thoughts/pointers?

**Comment by ktoso** [comment]
Thanks for reporting, I'll have a look as soon as I can squeeze it in.
It's holidays so we're not in full capacity, if you require help with this "right now" – we do that for customers.

**Comment by ktoso** [comment]
Well, I had a skim just now and termination won't propagate through a flow like you created since it consists of two separate parts – the termination is not carried through from the `Sink.ignore` to the `Source.actorRef`.

Visualize it as:

```
     +---------------------------+
     | +------+        +------+  |
In ~~> |      |        |      | ~~> Out
     | | igno |        | acto |  |
     | |      |        |      |  |
     | +------+        +------+  |
     +---------------------------+
```

The termination coming into the the `igno` sink, is not connected to the `acto`, thus the client going away won't terminate the "entire thing", by construction.

**Comment by jknight12882** [comment]
Thanks @ktoso. How would you propagate termination them in this instance?

**Comment by jknight12882** [comment]
Following up on this, `Flow.fromSinkAndSourceMat` is also a disjoint connection of a sink and a source connected by a `Graph`, very similar to what I proposed above, and it is able to propagate stream errors and completion.

**Comment by jrudolph** [comment]
Sorry, I didn't see this and created the likely duplicate ticket #19340.

**Comment by ktoso** [comment]
Looks like the same issue indeed. Let's close as @jrudolph's fix is merged. Thanks for reporting @jknight12882 and the fix @jrudolph !

**Comment by jrudolph** [comment]
I created #19359 to discuss further measures to ensure that WS connection are actually closed when the peer closed the connections.
