### ISSUE TITLE
Flaky test InputStreamSinkSpec

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19327]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4696/consoleFull
```
[info] - must fill up buffer by default *** FAILED *** (38 milliseconds)
[info]   Array(77, 42, -94) did not equal ByteString(-82, 117, -102) (InputStreamSinkSpec.scala:149)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply$mcV$sp(InputStreamSinkSpec.scala:149)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply$mcV$sp(InputStreamSinkSpec.scala:138)
[info]   at akka.stream.io.InputStreamSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(InputStreamSinkSpec.scala:138)
```

**Comment by 2m** [comment]
Fixed in #19329
