### ISSUE TITLE
stream testkit: `remaining` may not be called outside of `within`

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19326]
I think this is only a problem when using Akka 2.4.
The testkit should probably use `remainingOrDeault` instead.

```
[info] - must find existing persistenceIds *** FAILED *** (295 milliseconds)
[info]   java.lang.AssertionError: `remaining` may not be called outside of `within`
[info]   at akka.testkit.TestKitBase$class.remaining(TestKit.scala:198)
[info]   at akka.testkit.TestKit.remaining(TestKit.scala:735)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:254)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectOneOf$1(StreamTestKit.scala:327)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextUnorderedN(StreamTestKit.scala:332)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextUnordered(StreamTestKit.scala:293)
[info]   at akka.persistence.query.journal.leveldb.AllPersistenceIdsSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(AllPersistenceIdsSpec.scala:50)
[info]   at akka.persistence.query.journal.leveldb.AllPersistenceIdsSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(AllPersistenceIdsSpec.scala:39)
```

**Comment by fabriziofortino** [comment]
I have found a possible workaround using expectNextN but now my code fails on the expectComplete

```scala
probe.request(2)
val ps = probe.expectNextN(2)
probe.expectComplete() // it fails here!
```

Here is the stacktrace:
```
assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete
	at scala.Predef$.assert(Predef.scala:165)
	at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
	at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectComplete(StreamTestKit.scala:342)
```

Can these problems be related to each other?

**Comment by felipegutierrez** [comment]
did you find a solution for the error `assertion failed: timeout (3 seconds) during expectMsg while waiting for OnComplete`?
