### ISSUE TITLE
FAILED: akka.pattern.BackoffSupervisorSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19344]
Timeout in "must support manual reset"

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/224/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2939/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2941/consoleFull

**Comment by johanandren** [comment]
And another one of "must support custom supervision strategy": 

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/225/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/230/consoleFull

**Comment by johanandren** [comment]
"must support manual reset"
https://jenkins.akka.io:8498/job/akka-nightly/2958/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2962/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/2964/consoleFull

```
 must support custom supervision strategy *** FAILED *** (3 seconds, 212 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.pattern.BackoffSupervisor$CurrentChild
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:408)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:735)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply$mcV$sp(BackoffSupervisorSpec.scala:85)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply(BackoffSupervisorSpec.scala:82)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply(BackoffSupervisorSpec.scala:82)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:735)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1(BackoffSupervisorSpec.scala:82)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply$mcV$sp(BackoffSupervisorSpec.scala:100)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/234/consoleFull

**Comment by patriknw** [comment]
@RayRoestenburg looks like this spec started fail after your additions. Do you have any spare cycles to take a look at it?

**Comment by drewhk** [comment]
Similar, but not the same:
```
[info] - must support manual reset *** FAILED *** (3 seconds, 217 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for RestartCount(1)
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:735)
```

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/4822/consoleFull

**Comment by drewhk** [comment]
This needs to be fixed, fails too often. I stopped pinging for now, but assigned it to 2.4.2
