### ISSUE TITLE
Websocket user-handler gets error if peer terminates connection

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#19340]
Instead, it should report completion. Occurred while porting the akka-http-websocket-chat to 2.0.1.

Exception:

```
java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:193)
	at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:90)
	at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:89)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:27)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:26)
	at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:617)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jknight12882** [comment]
Seeing a similar thing in #19285
