### ISSUE TITLE
Docs: RecipeByteStrings test failed

### ISSUE THREAD

**Issue by agolubev** [akka/akka#19366]
there is no code to push rest of the buffer to downstream when stream is finishing.
```
[error] Test docs.stream.cookbook.RecipeByteStrings.chunker failed: java.lang.AssertionError: expected:<ByteString(1, 2, 3, 4, 5, 6, 7, 8)> but was:<ByteString(1, 2, 3, 4, 5, 6, 7, 8, 9)>
[error]     at docs.stream.cookbook.RecipeByteStrings$1.<init>(RecipeByteStrings.java:111)
[error]     at docs.stream.cookbook.RecipeByteStrings.chunker(RecipeByteStrings.java:57)
[error]     ...
```

**Comment by drewhk** [comment]
This might have been fixed, checking now.

**Comment by drewhk** [comment]
It seems like this has been fixed by: https://github.com/akka/akka/pull/19768/files#diff-006e97edc96c010e25fa19fd2aafb1c4R102
