### ISSUE TITLE
FAILED: ClusterDeathWatchSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#19383]
```
[info] [akka] [JVM-2] [WARN] [01/07/2016 13:59:14.051] [ClusterDeathWatchSpec-akka.remote.default-remote-dispatcher-6] [akka.remote.Remoting] Tried to associate with unreachable remote address [akka.tcp://ClusterDeathWatchSpec@localhost:52177]. Address is now gated for 5000 ms, all messages to this address will be delivered to dead letters. Reason: [The remote system has quarantined this system. No further associations to the remote system are possible until this system is restarted.] 
[info] [akka] [JVM-4] - must be able to watch actor before node joins cluster, ClusterRemoteWatcher takes over from RemoteWatcher *** FAILED *** (19 seconds, 995 milliseconds)
[info] [akka] [JVM-4]   Some(akka.tcp://ClusterDeathWatchSpec@localhost:50457) did not equal Some(akka.tcp://ClusterDeathWatchSpec@localhost:45087) (MultiNodeClusterSpec.scala:303)
[info] [akka] [JVM-4]   org.scalatest.exceptions.TestFailedException:
[info] [akka] [JVM-4]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info] [akka] [JVM-4]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(MultiNodeClusterSpec.scala:303)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$4.apply(MultiNodeClusterSpec.scala:303)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$4.apply(MultiNodeClusterSpec.scala:303)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
[info] [akka] [JVM-4]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:735)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:303)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:296)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:296)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:308)
[info] [akka] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:735)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:322)
[info] [akka] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:735)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.awaitMembersUp(MultiNodeClusterSpec.scala:296)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.awaitMembersUp(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.awaitClusterUp(MultiNodeClusterSpec.scala:219)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.awaitClusterUp(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$mcV$sp$16.apply$mcV$sp(ClusterDeathWatchSpec.scala:170)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$mcV$sp$16.apply(ClusterDeathWatchSpec.scala:148)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$mcV$sp$16.apply(ClusterDeathWatchSpec.scala:148)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:308)
[info] [akka] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:735)
[info] [akka] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:322)
[info] [akka] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:735)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15.apply$mcV$sp(ClusterDeathWatchSpec.scala:148)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15.apply(ClusterDeathWatchSpec.scala:148)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$15.apply(ClusterDeathWatchSpec.scala:148)
[info] [akka] [JVM-4]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info] [akka] [JVM-4]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info] [akka] [JVM-4]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [akka] [JVM-4]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [akka] [JVM-4]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info] [akka] [JVM-4]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:179)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.withFixture(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.runTest(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info] [akka] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:381)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info] [akka] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:381)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.runTests(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.org$scalatest$WordSpecLike$$super$run(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info] [akka] [JVM-4]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info] [akka] [JVM-4]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.org$scalatest$BeforeAndAfterAll$$super$run(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info] [akka] [JVM-4]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info] [akka] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.run(ClusterDeathWatchSpec.scala:42)
[info] [akka] [JVM-4]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
[info] [akka] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:381)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
[info] [akka] [JVM-4]   at org.scalatest.tools.Runner.main(Runner.scala)
```

This failed in a RP PR validation with Akka 2.4.1+

**Comment by drewhk** [comment]
Haven't been reported in 7 months.

**Comment by raboof** [comment]
Seems to have resurfaced after all.. https://jenkins.akka.io:8498/job/akka-nightly/5225/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5421/consoleFull

**Comment by johanandren** [comment]
I think we should close this then and open a new issue tracking the new one.
