### ISSUE TITLE
Empty.head in Websockets

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19417]
Stacktrace:
```
[ERROR] [01/12/2016 17:34:44.085] [WebsocketsSystem-akka.actor.default-dispatcher-3] [ActorSystem(WebsocketsSystem)] Websocket handler failed while waiting for handler completion with empty.head
java.lang.UnsupportedOperationException: empty.head
        at scala.collection.immutable.Vector.head(Vector.scala:192)
        at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:90)
        at akka.http.impl.engine.ws.Websocket$$anonfun$2.apply(Websocket.scala:89)
        at akka.stream.impl.fusing.Map.onPush(Ops.scala:27)
        at akka.stream.impl.fusing.Map.onPush(Ops.scala:26)
        at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:54)
        at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:575)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:617)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:547)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
```

The reproducer is here: https://github.com/akka/akka/issues/19094#issuecomment-170842246

Originally filed under https://github.com/akka/akka/issues/19094 but that turned out to be a different one.

**Comment by drewhk** [comment]
this is actually in the 2.0 branch
