### ISSUE TITLE
FAILED: StreamTestKitSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19472]
https://jenkins.akka.io:8498/job/akka-nightly/2972/consoleFull

```
- must #toStrict with failing source *** FAILED *** (48 milliseconds)
[info]   "toStrict received OnError while draining stream! Accumulated elements: List(1, 2)" did not include substring "Boom!" (StreamTestKitSpec.scala:40)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[info]   at akka.stream.testkit.StreamTestKitSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(StreamTestKitSpec.scala:40)
[info]   at akka.stream.testkit.StreamTestKitSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(StreamTestKitSpec.scala:24)
[info]   at akka.stream.testkit.StreamTestKitSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(StreamTestKitSpec.scala:24)
```

**Comment by johanandren** [comment]
Duplicate of #19464
