### ISSUE TITLE
FAILED: HighLevelOutgoingConnectionSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19503]
```
[ERROR] [01/18/2016 10:25:47.030] [HighLevelOutgoingConnectionSpec-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(HighLevelOutgoingConnectionSpec)] Outgoing request stream error
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (method)
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:419)
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponseParsingMerge$$anon$3$$anonfun$1.apply$mcV$sp(OutgoingConnectionBlueprint.scala:207)
	at akka.stream.stage.GraphStageLogic$Emitting.followUp(GraphStage.scala:830)
	at akka.stream.stage.GraphStageLogic$EmittingSingle.onPull(GraphStage.scala:879)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:593)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info] - should catch response stream truncation *** FAILED *** (29 milliseconds)
[info]   Expected exception akka.stream.scaladsl.One2OneBidiFlow$OutputTruncationException$ to be thrown, but java.lang.IllegalArgumentException was thrown. (HighLevelOutgoingConnectionSpec.scala:70)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:496)
[info]   at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1538)
[info]   at org.scalatest.Assertions$.checkExpectedException(Assertions.scala:1572)
[info]   at org.scalatest.words.ResultOfBeWordForAType.thrownBy(ResultOfBeWordForAType.scala:39)
[info]   at akka.http.impl.engine.client.HighLevelOutgoingConnectionSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(HighLevelOutgoingConnectionSpec.scala:83)
[info]   at akka.http.impl.engine.client.HighLevelOutgoingConnectionSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HighLevelOutgoingConnectionSpec.scala:70)
[info]   at akka.http.impl.engine.client.HighLevelOutgoingConnectionSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HighLevelOutgoingConnectionSpec.scala:70)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.stream.testkit.AkkaSpec.withFixture(AkkaSpec.scala:58)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.stream.testkit.AkkaSpec.runTest(AkkaSpec.scala:58)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
```

**Comment by drewhk** [comment]
Unfortunately failed again: https://jenkins.akka.io:8498/job/akka-nightly/2979/consoleFull

**Comment by drewhk** [comment]
and others: https://jenkins.akka.io:8498/job/akka-multi-node/1268/consoleFull

(stop pinging now)

**Comment by rkuhn** [comment]
Wrong failure mode, please use a different ticket.

**Comment by drewhk** [comment]
This needs to be backported, isn't it?

**Comment by rkuhn** [comment]
Yes, sorry for overlooking this!

**Comment by 2m** [comment]
Backported.
