### ISSUE TITLE
FAILED: NodeChurnSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19536]
https://jenkins.akka.io:8498/job/akka-nightly/2978/consoleFull

```
[JVM-1] - must join and remove transient nodes without growing gossip payload *** FAILED *** (25 seconds, 160 milliseconds)
[JVM-1]   false was not true (NodeChurnSpec.scala:79)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[JVM-1]   at akka.cluster.NodeChurnSpec$$anonfun$awaitRemoved$1$$anonfun$apply$mcV$sp$6.apply(NodeChurnSpec.scala:79)
```

**Comment by drewhk** [comment]
Similar to https://github.com/akka/akka/issues/18211 but not exactly the same

**Comment by drewhk** [comment]
same here: https://jenkins.akka.io:8498/job/akka-nightly/3158/consoleFull
