### ISSUE TITLE
ResponseParsingMerge: Cannot pull closed port

### ISSUE THREAD

**Issue by drewhk** [akka/akka#19573]
Snippet that seems to reproduce it for longer payloads:

```scala
    val responseFuture: Future[HttpResponse] =
      Http().singleRequest(HttpRequest(...))
  
      responseFuture.flatMap { response =>

      val responsebody = response.entity.dataBytes.runWith(Sink.fold("")((acc, str) => acc + str.decodeString("UTF-8")))
    }
```

And the stacktrace is:

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:419)
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponseParsingMerge$$anon$3$$anonfun$1.apply$mcV$sp(OutgoingConnectionBlueprint.scala:207)
	at akka.stream.stage.GraphStageLogic$Emitting.followUp(GraphStage.scala:830)
	at akka.stream.stage.GraphStageLogic$EmittingSingle.onPull(GraphStage.scala:879)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:593)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:533)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:445)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:400)
```

**Comment by drewhk** [comment]
Reported by client. Should be backported to 2.0.x. I put this on this milestone so we don't miss it, feel free to move it later.

**Comment by drewhk** [comment]
This looks like to have been fixed in https://github.com/akka/akka/issues/19503, but I am not sure if it has been backported or not. It should be though.
