### ISSUE TITLE
Stream errors when response is sent early

### ISSUE THREAD

**Issue by jroper** [akka/akka#19623]
In Akka 2.4.2-RC1, getting the following error when a response is sent before the request body has been read:

```
[WARN] [01/27/2016 12:19:19.448] [application-akka.actor.default-dispatcher-11] [akka.actor.ActorSystemImpl(application)] Sending 2xx response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses!
Consider waiting for the request end before dispatching this response!
[ERROR] [01/27/2016 12:19:19.475] [application-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(application)] Outgoing response stream error
java.lang.IllegalArgumentException: requirement failed: Cannot push port (SubSource.out) twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:439)
	at akka.stream.impl.fusing.SubSource$$anon$3$$anonfun$2.apply(StreamOfStreams.scala:519)
	at akka.stream.impl.fusing.SubSource$$anon$3$$anonfun$2.apply(StreamOfStreams.scala:516)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:557)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:399)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Also getting this, somewhat similar but different error, triggered in a different test:

```
[WARN] [01/27/2016 12:19:20.544] [application-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(application)] Sending 2xx response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses!
Consider waiting for the request end before dispatching this response!
[ERROR] [01/27/2016 12:19:20.563] [application-akka.actor.default-dispatcher-8] [akka.actor.ActorSystemImpl(application)] Internal server error, sending 500 response
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (RequestStartThenRunIgnore.in) twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:351)
	at akka.http.impl.engine.server.HttpServerBluePrint$PrepareRequests$$anon$4$$anon$6.onPull(HttpServerBluePrint.scala:123)
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$5.apply(GraphStage.scala:1027)
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$5.apply(GraphStage.scala:1023)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:557)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:399)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:549)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:495)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jroper** [comment]
@rkuhn I haven't looked into this in depth yet (will do now), and at whether we can work around it (we probably can), but just wanted to ping you to let you know about this issue.

**Comment by jroper** [comment]
A few more details.  Although the actual code looks nothing like this (goes through several other APIs) which is why this code looks so weird and unnecessary, this is essentially the Akka streams calls for the handler for the Akka HTTP server, I suspect you should be able to reproduce the problem if you use this:

```scala
Flow[HttpRequest].mapAsync { request =>

  val sinkSource: Sink[ByteString, Future[Source[ByteString, _]]] = Sink.asPublisher[ByteString](fanout = false).mapMaterializedValue(publisher => Future.successful(Source.fromPublisher(publisher)))

  request.entity.dataBytes.runWith(sinkSource).map { requestSource =>
    HttpResponse(entity = HttpEntity(ContentTypes.`application/octet-stream`, requestSource))
  }
}
```

The above is essentially an echo server that we use for some of our tests.  The reason for not simply returning the `Source` as is is that Play models actions as a Sink of bytes for the request body, hence an action that wants to return the request body as a source must return something that essentially looks like the `sinkSource` above.

In order to get a release of Play compatible with Akka 2.4.2-RC1 for certain other dependent projects to test/migrate to, we'll disable these specific tests for now.

**Comment by johanandren** [comment]
Thanks for the example @jroper, however I can not get that to reproduce either of the exceptions. Will dig into the actual graph stages and see if I can figure them out.

**Comment by johanandren** [comment]
@jroper any hint about what the test that gave the second error was doing?

**Comment by jroper** [comment]
These are the two tests - I think either error is possible for either test:

https://github.com/playframework/playframework/blob/master/framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala#L145
https://github.com/playframework/playframework/blob/master/framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala#L235

**Comment by johanandren** [comment]
Small reproducer for the pull twice error: 

```scala
val flow = Http().bindAndHandle(Flow[HttpRequest].map { request =>
  request.entity.dataBytes.runWith(Sink.foreach(_ => println("chunk")))
  HttpResponse(entity = HttpEntity(ContentTypes.`application/octet-stream`, Source.single(ByteString("cdefg"))))
  }, "127.0.0.1", 8080)

val res = Http().singleRequest(
  HttpRequest(HttpMethods.GET, "http://localhost:8080/",
    entity = HttpEntity(
      ContentTypes.`text/plain(UTF-8)`,
      Source.fromFuture(Future { Thread.sleep(500); ByteString("abcdefghijklmnopqrstuv") })
    )
  )
)

res.foreach(response => response.entity.dataBytes.runForeach(s => println(s.utf8String)))
```

So it seems to happen when response is sent before consuming request, and incoming body is slow

**Comment by prettynatty** [comment]
Is there any work-around for this for those who are on 2.4.2-RC1?
My code does not send response before it reads request (as far as I understand) but throws an error `java.lang.IllegalArgumentException: requirement failed: Cannot pull port (RequestStartThenRunIgnore.in) twice`

```scala
put {
              pathSuffix(IntNumber) { partNumber =>
                log.debug("Upload file part request, fileId: {}, partNumber: {}", fileId, partNumber)
                extractRequest { req =>
                  val writeFu = for {
                    _ <- prepareForPartWrite(fileId, partNumber)
                    _ <- appendPartBytes(req.entity.dataBytes, fileId, partNumber)
                    _ <- Future {}
                  } yield ()
                  onComplete(writeFu) {
                    case Success(_) =>
                      log.debug("Successfully uploaded part #{} of file: {} ", partNumber, fileId)
                      complete(HttpResponse(200))
                    case Failure(e) =>
                      log.error(e, "Failed to upload file: {}", fileId)
                      complete(HttpResponse(500))
                  }
                }
              }
            }
```

**Comment by johanandren** [comment]
@prettynatty The bug should only happen with early response, as it is triggered by the entity `Source` and the server both pulling, so it is weird that you are getting it as well. Would be great if you could see if you can cook it down to smallest possible repeater so I can see if the PR fixes that as well.

**Comment by prettynatty** [comment]
I think it's connected with another problem I found.
After upgrading streams from 2.0.3 to 2.4.2-RC1 we encountered file resource leak.
`appendPartBytes` used to write file via `bs.runWith(FileIO.toFile(partFile.toJava, append = true))`. After migrating this line to the homebrew sync writing on separate threadpool there was no more resource leak. But now this problem.

**Comment by prettynatty** [comment]
@ktoso maybe interested, related to #19635

**Comment by drewhk** [comment]
Can be only closed after backport to 2.0.x

**Comment by prettynatty** [comment]
I see it's merged is there a snapshot published with this fix?

**Comment by drewhk** [comment]
No, but we will release RC2 soon.

**Comment by jroper** [comment]
Just tested against RC2, the error in the Play tests is fixed.

**Comment by prettynatty** [comment]
My case is also fixed
