### ISSUE TITLE
NPE with akka-typed and cluster/remote

### ISSUE THREAD

**Issue by durban** [akka/akka#19683]
Calling `akka.cluster.Cluster.apply` in the PreStart handler of the guardian actor of an `akka.typed.ActorSystem` results in a `NullPointerException` at `akka.remote.RemoteActorRefProvider.transport(RemoteActorRefProvider.scala:144)`. The same seems to work fine with untyped actors.

Looking at the log (see below), there is a "Starting remoting" message _after_ the exception. Maybe the remoting system is started later than the message handler is called? (BTW, I get the same exception, if I try to remote-deploy an actor in the PreStart of a typed actor.) Full code is here: https://github.com/durban/akka-typed-examples/blob/467b0f3cc6a961174adfeae44e8ea321ddb7d6e4/src/main/scala/com/example/actors/TypedCluster.scala (Akka version is 2.4.1).

```
[info] Running com.example.actors.TypedCluster 
[ERROR] [02/03/2016 09:25:33.530] [MySystem-akka.actor.default-dispatcher-4] [akka.actor.LocalActorRefProvider(akka://MySystem)] guardian failed, shutting down system
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at akka.remote.RemoteActorRefProvider.transport(RemoteActorRefProvider.scala:144)
        at akka.cluster.Cluster.<init>(Cluster.scala:71)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:30)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.cluster.Cluster$.apply(Cluster.scala:30)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:14)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:12)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[ERROR] [02/03/2016 09:25:33.530] [MySystem-akka.actor.default-dispatcher-4] [akka.actor.LocalActorRefProvider(akka://MySystem)] guardian failed, shutting down system
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at akka.remote.RemoteActorRefProvider.transport(RemoteActorRefProvider.scala:144)
        at akka.cluster.Cluster.<init>(Cluster.scala:71)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:30)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.cluster.Cluster$.apply(Cluster.scala:30)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:14)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:12)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[ERROR] [02/03/2016 09:25:33.541] [MySystem-akka.actor.default-dispatcher-4] [akka://MySystem/user] null
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at akka.remote.RemoteActorRefProvider.transport(RemoteActorRefProvider.scala:144)
        at akka.cluster.Cluster.<init>(Cluster.scala:71)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:30)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.cluster.Cluster$.apply(Cluster.scala:30)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:14)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:12)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[ERROR] [02/03/2016 09:25:33.541] [MySystem-akka.actor.default-dispatcher-4] [akka://MySystem/user] null
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
        at akka.remote.RemoteActorRefProvider.transport(RemoteActorRefProvider.scala:144)
        at akka.cluster.Cluster.<init>(Cluster.scala:71)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
        at akka.cluster.Cluster$.createExtension(Cluster.scala:30)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.cluster.Cluster$.apply(Cluster.scala:30)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:14)
        at com.example.actors.TypedCluster$$anonfun$guardian$1.apply(TypedCluster.scala:12)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[INFO] [02/03/2016 09:25:33.625] [run-main-0] [akka.remote.Remoting] Starting remoting
[ERROR] [02/03/2016 09:25:33.873] [MySystem-akka.remote.default-remote-dispatcher-8] [akka.remote.Remoting] Remoting system has been terminated abrubtly. Attempting to shut down transports
^C
```

**Comment by patriknw** [comment]
obsolete

**Comment by ranchoiver** [comment]
I'm also getting similar NullPointerException with typed actors because
`@volatile private var _internals: Internals = _` is `null`

My main class goes as follows:
```scala
val root: Behavior[akka.NotUsed] = Actor.deferred { ctx ⇒
       ctx.spawn(MyActor.behavior("MyActor"), "MyActor", Props.empty)

 val system = ActorSystem(guardianBehavior = root, name = "mySystem", config)
```

And in MyActor I do:
```scala
def behavior(info: String): Behavior[Command] =
    Actor.deferred[Command] { ctx ⇒
      implicit lazy val cluster = akka.cluster.Cluster(ctx.system.toUntyped)
      implicit lazy val replicator: ActorRef[Replicator.Command] =
        DistributedData(ctx.system).replicator
      Actor.immutable { (ctx, msg) =>
        //business logic
      }
```

It seemingly fails when trying to create a `Cluster`.

Deps:
```
"com.typesafe.akka" %% "akka-actor"  % "2.5.9" 
"com.typesafe.akka" %% "akka-actor-typed"  % "2.5.9" 
"com.typesafe.akka" %% "akka-cluster-typed"      % "2.5.9"
"com.typesafe.akka" %% "akka-distributed-data"   % "2.5.9"
"com.typesafe.akka" %% "akka-remote" % "2.5.9"       
```

**Comment by ranchoiver** [comment]
Oh, it's related https://github.com/akka/akka/issues/24279 , guess just going to wait for the fix then.
