### ISSUE TITLE
FAILED akka.stream.scaladsl.FlowConflateSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19721]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5135/consoleFull

```
- must restart when `aggregate` throws and a restartingDecider is used *** FAILED *** (32 milliseconds)
[info]   "[on]e" did not equal "[thre]e" (FlowConflateSpec.scala:200)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6303)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply$mcV$sp(FlowConflateSpec.scala:200)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply(FlowConflateSpec.scala:176)
[info]   at akka.stream.scaladsl.FlowConflateSpec$$anonfun$1$$anonfun$apply$mcV$sp$18.apply(FlowConflateSpec.scala:176)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by johanandren** [comment]
Flaky test introduced by me in #19564 :(

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5135/consoleFull
