### ISSUE TITLE
FAILED OutgoingConnectionBlueprint

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19741]
`HighLevelOutgoingConnectionSpec` consistently fails on my machine, with a 

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (ResponsePrep.in) twice
	at scala.Predef$.require(Predef.scala:219)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:351)
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponsePrep$$anon$1.onPull(OutgoingConnectionBlueprint.scala:170)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:600)
...
```

Most likely introduced in #19528

**Comment by johanandren** [comment]
And `HighLevelOutgoingConnectionSpec.scala` as well:

```
The future returned an exception of type: java.lang.IllegalArgumentException, with message: requirement failed: Cannot pull port (ResponsePrep.in) twice. (HighLevelOutgoingConnectionSpec.scala:38)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]   at akka.http.impl.engine.client.HighLevelOutgoingConnectionSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply(HighLevelOutgoingConnectionSpec.scala:38)
...
```
