### ISSUE TITLE
Akka HTTP incompatibility with akka-typed

### ISSUE THREAD

**Issue by durban** [akka/akka#19776]
Calling `akka.http.scaladsl.Http.apply()` with an `ActorSystem` created by `akka-typed` results in an `UnsupportedOperationException` (see log below). The problem seems to be that the actor system created by `akka-typed` has a "custom user guardian", so `akka-http` cannot create its top-level actor. (As a workaround, it seems to be possible to create an untyped actor system, and create the typed actors in a subtree of it.)

```
[info] Running com.example.http.TypedHttp 
[INFO] [02/15/2016 09:15:38.963] [run-main-0] [akka.remote.Remoting] Starting remoting
[INFO] [02/15/2016 09:15:39.388] [run-main-0] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://MySystem@127.0.0.1:2552]
[INFO] [02/15/2016 09:15:39.420] [run-main-0] [akka.cluster.Cluster(akka://MySystem)] Cluster Node [akka.tcp://MySystem@127.0.0.1:2552] - Starting up...
[INFO] [02/15/2016 09:15:39.623] [run-main-0] [akka.cluster.Cluster(akka://MySystem)] Cluster Node [akka.tcp://MySystem@127.0.0.1:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [02/15/2016 09:15:39.623] [run-main-0] [akka.cluster.Cluster(akka://MySystem)] Cluster Node [akka.tcp://MySystem@127.0.0.1:2552] - Started up successfully
[INFO] [02/15/2016 09:15:39.816] [MySystem-akka.actor.default-dispatcher-14] [akka.cluster.Cluster(akka://MySystem)] Cluster Node [akka.tcp://MySystem@127.0.0.1:2552] - Node [akka.tcp://MySystem@127.0.0.1:2552] is JOINING, roles []
[INFO] [02/15/2016 09:15:39.835] [MySystem-akka.actor.default-dispatcher-14] [akka.cluster.Cluster(akka://MySystem)] Cluster Node [akka.tcp://MySystem@127.0.0.1:2552] - Leader is moving node [akka.tcp://MySystem@127.0.0.1:2552] to [Up]
[ERROR] [02/15/2016 09:15:39.974] [MySystem-akka.actor.default-dispatcher-4] [akka.actor.LocalActorRefProvider(akka://MySystem)] guardian failed, shutting down system
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                                                               
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                                                                   
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                                                           
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:592)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:61)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:39)
        at akka.stream.scaladsl.Tcp.<init>(Tcp.scala:67)
        at akka.stream.scaladsl.Tcp$.createExtension(Tcp.scala:60)
        at akka.stream.scaladsl.Tcp$.createExtension(Tcp.scala:21)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.stream.scaladsl.Tcp$.apply(Tcp.scala:54)
        at akka.http.scaladsl.HttpExt.bind(Http.scala:83)
        at akka.http.scaladsl.HttpExt.bindAndHandle(Http.scala:121)
        at com.example.http.TypedHttp$$anonfun$guardian$1.apply(TypedHttp.scala:39)
        at com.example.http.TypedHttp$$anonfun$guardian$1.apply(TypedHttp.scala:25)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[ERROR] [02/15/2016 09:15:39.977] [MySystem-akka.actor.default-dispatcher-4] [akka://MySystem/user] cannot create top-level actor from the outside on ActorSystem with custom user guardian
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:172)
        at akka.actor.ActorCell.create(ActorCell.scala:606)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:592)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:61)
        at akka.stream.ActorMaterializer$.apply(ActorMaterializer.scala:39)
        at akka.stream.scaladsl.Tcp.<init>(Tcp.scala:67)
        at akka.stream.scaladsl.Tcp$.createExtension(Tcp.scala:60)
        at akka.stream.scaladsl.Tcp$.createExtension(Tcp.scala:21)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
        at akka.actor.ExtensionId$class.apply(Extension.scala:79)
        at akka.stream.scaladsl.Tcp$.apply(Tcp.scala:54)
        at akka.http.scaladsl.HttpExt.bind(Http.scala:83)
        at akka.http.scaladsl.HttpExt.bindAndHandle(Http.scala:121)
        at com.example.http.TypedHttp$$anonfun$guardian$1.apply(TypedHttp.scala:39)
        at com.example.http.TypedHttp$$anonfun$guardian$1.apply(TypedHttp.scala:25)
        at akka.typed.ScalaDSL$FullTotal.management(ScalaDSL.scala:162)
        at akka.typed.ActorAdapter.preStart(Impl.scala:62)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:485)
        at akka.typed.ActorAdapter.aroundPreStart(Impl.scala:17)
        at akka.actor.ActorCell.create(ActorCell.scala:590)
        ... 9 more

[INFO] [02/15/2016 09:15:39.993] [MySystem-akka.remote.default-remote-dispatcher-5] [akka.tcp://MySystem@127.0.0.1:2552/system/remoting-terminator] Shutting down remote daemon.
[INFO] [02/15/2016 09:15:39.996] [MySystem-akka.remote.default-remote-dispatcher-5] [akka.tcp://MySystem@127.0.0.1:2552/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [02/15/2016 09:15:40.033] [MySystem-akka.remote.default-remote-dispatcher-6] [akka.tcp://MySystem@127.0.0.1:2552/system/remoting-terminator] Remoting shut down.
```

**Comment by drewhk** [comment]
This seems to be a general issue for all Akka extensions (which HTTP is only one example of).

**Comment by ktoso** [comment]
Relates to https://github.com/akka/akka/issues/16738 I guess

**Comment by patriknw** [comment]
I assume this is solved for now, since we removed the native typed ActorSystem.

**Comment by mihbor** [comment]
This seems to be still/again an issue with latest akka-typed snapshot and akka-http 10.0.11 as well as 10.1.0-RC2.
Using Http.singleRequest from within a MutableBehavior like so:
```
Http.get(Adapter.toUntyped(ctx.getSystem())).singleRequest(HttpRequest.create(url))
```
causes:
java.lang.UnsupportedOperationException: cannot create top-level actor [pool-master] from the outside on ActorSystem with custom user guardian
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:736)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:316)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:928)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:804)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.http.scaladsl.Http$.apply(Http.scala:923)
	at akka.http.scaladsl.Http$.apply(Http.scala:804)
	at akka.http.javadsl.Http.delegate$lzycompute(Http.scala:45)
	at akka.http.javadsl.Http.delegate(Http.scala:45)
	at akka.http.javadsl.Http.singleRequest(Http.scala:658)
...

**Comment by chbatey** [comment]
I think we moved the stream ones under system, might need to do the same here

**Comment by patriknw** [comment]
@mihbor Please create a new issue in https://github.com/akka/akka-http, since the change is needed there.

**Comment by mihbor** [comment]
Done: https://github.com/akka/akka-http/issues/1873
