### ISSUE TITLE
FAILED: BackoffSupervisor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19798]
```
[info] BackoffSupervisor
[info] - must start child again when it stops when using `Backoff.onStop` (211 milliseconds)
[info] - must forward messages to the child (1 millisecond)
[info] - must support custom supervision strategy *** FAILED *** (3 seconds, 210 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.pattern.BackoffSupervisor$CurrentChild
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:408)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:735)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply$mcV$sp(BackoffSupervisorSpec.scala:85)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply(BackoffSupervisorSpec.scala:82)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1$1.apply(BackoffSupervisorSpec.scala:82)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:266)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:277)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:735)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.akka$pattern$BackoffSupervisorSpec$$anonfun$$anonfun$$assertCustomStrategy$1(BackoffSupervisorSpec.scala:82)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply$mcV$sp(BackoffSupervisorSpec.scala:100)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(BackoffSupervisorSpec.scala:88)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(BackoffSupervisorSpec.scala:88)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:110)
[info]   at akka.testkit.package$.filterException(package.scala:37)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(BackoffSupervisorSpec.scala:88)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(BackoffSupervisorSpec.scala:75)
[info]   at akka.pattern.BackoffSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$4.apply(BackoffSupervisorSpec.scala:75)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:56)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
```

**Comment by drewhk** [comment]
when is this from (the failure)?

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1329/consoleFull so (2016-02-12 10:34:06)

**Comment by drewhk** [comment]
I merged the fix 4 days ago, so this has been likely fixed (today is 16)

**Comment by ktoso** [comment]
Ok, let's close and we'll know if it comes back. Thanks
