### ISSUE TITLE
FAILED: (timing, TCK) ConcatTest

### ISSUE THREAD

**Issue by ktoso** [akka/akka#19799]
```
[info] - required_spec309_requestNegativeNumberMustSignalIllegalArgumentException *** FAILED ***
[info]   java.lang.AssertionError: Expected onError(java.lang.IllegalArgumentException) within 800 ms
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:180)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.expectError(TestEnvironment.java:930)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:484)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:476)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:464)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:459)
[info]   at org.reactivestreams.tck.PublisherVerification$22.run(PublisherVerification.java:876)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   at 
```

**Comment by ktoso** [comment]
```
VirtualProcessorTest
```

**Comment by 2m** [comment]
(Mar 7, 2016 4:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3576/consoleFull
(Mar 6, 2016 7:18:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/284/consoleFull
(Mar 6, 2016 4:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3572/consoleFull
(Mar 5, 2016 4:19:00 AM) https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3568/consoleFull

**Comment by patriknw** [comment]
We should increase tck timeouts after https://github.com/reactive-streams/reactive-streams-jvm/pull/309

**Comment by patriknw** [comment]
TCK test timeout, superseded by #20241
