### ISSUE TITLE
akka.typed.ActorRef[T] is not serializable

### ISSUE THREAD

**Issue by durban** [akka/akka#19810]
Instances of `akka.typed.ActorRef[T]` doesn't seem to be serializable, but akka-typed usually requires passing around `ActorRef`s (for the reply address). This makes using akka-typed together with remoting (or akka-cluster) really hard. See an example exception below from a remote message send  (full code is at https://github.com/durban/akka-typed-examples/blob/44306044bd1c417001474ad0941ff375bc1fcec7/src/main/scala/com/example/actors/typedRemote.scala).

```
java.io.NotSerializableException: akka.typed.ActorRef$Combined
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply$mcV$sp(Serializer.scala:234)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:234)
        at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:234)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at akka.serialization.JavaSerializer.toBinary(Serializer.scala:234)
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:37)
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:871)
        at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:871)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:870)
        at akka.remote.EndpointWriter.writeSend(Endpoint.scala:771)
        at akka.remote.EndpointWriter.delegate$1(Endpoint.scala:661)
        at akka.remote.EndpointWriter.writeLoop$1(Endpoint.scala:672)
        at akka.remote.EndpointWriter.sendBufferedMessages(Endpoint.scala:685)
        at akka.remote.EndpointWriter.becomeWritingOrSendBufferedMessages(Endpoint.scala:631)
        at akka.remote.EndpointWriter$$anonfun$initializing$1.applyOrElse(Endpoint.scala:605)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:439)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ktoso** [comment]
FYI @rkuhn

**Comment by rkuhn** [comment]
Using Java Serialization is strongly discouraged, we will remove support for it in Akka 3.0 anyway.

**Comment by patriknw** [comment]
Will be solved by https://github.com/akka/akka/issues/24135
