### ISSUE TITLE
Deceptive akka.actor.OneForOneStrategy exception

### ISSUE THREAD

**Issue by Kml55** [akka/akka#19901]
I am using akka java with playframework. I realized that I am getting a null pointer exception while creating an actor. This exception causes an akka.actor.OneForOneStrategy exception on top level. Why? Is this normal? Normally it is a null pointer exception while creating an actor. Full stack trace is below:

```
[error] - akka.actor.OneForOneStrategy - exception during creation
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_66]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_66]
	at akka.util.Reflect$.instantiate(Reflect.scala:66) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ArgsReflectConstructor.produce(Props.scala:355) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.Props.newActor(Props.scala:255) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:578) ~[akka-actor_2.11-2.3.13.jar:na]
	... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
	at actors.Room.addSocket(WebSocketActor.java:68) ~[classes/:na]
	at actors.WebSocketActor.<init>(WebSocketActor.java:29) ~[classes/:na]
	... 18 common frames omitted
```

**Comment by johanandren** [comment]
It does not cause an exception top level, it is just logged there. Any exceptions in the constructor of an actor will be wrapped in an `ActorInitializationException` and that is then handled by the parent actor supervision strategy. You can read more about supervision in the docs here: http://doc.akka.io/docs/akka/2.4.2/java/fault-tolerance.html

In what way do you think this is "deceptive"?

**Comment by Kml55** [comment]
Hi,
I am not an akka expert. When I see akka.actor.OneForOneStrategy exception on the top of my error log, I feeled like I must learn a detail from akka world. In fact, There was an error on my actor class constructor. I searched what is OneForOneStrategy error instead of controlling my constructor code. This was deceptive for me :).

**Comment by rkuhn** [comment]
While I’m not convinced of the deceptiveness of this log message, I do think that we can improve it: the log message should say that the attached exception occurred while trying to create an actor, and it should point out that child actor’s path.
