### ISSUE TITLE
FAILED FlattenTest

### ISSUE THREAD

**Issue by johanandren** [akka/akka#19994]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3584/consoleFull

```
[info] - required_spec309_requestZeroMustSignalIllegalArgumentException *** FAILED ***
[info]   java.lang.AssertionError: Expected onError(java.lang.IllegalArgumentException) within 800 ms
[info]   at org.testng.Assert.fail(Assert.java:78)
[info]   at org.reactivestreams.tck.TestEnvironment.flopAndFail(TestEnvironment.java:180)
[info]   at org.reactivestreams.tck.TestEnvironment$Receptacle.expectError(TestEnvironment.java:930)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:484)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectError(TestEnvironment.java:476)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:464)
[info]   at org.reactivestreams.tck.TestEnvironment$ManualSubscriber.expectErrorWithMessage(TestEnvironment.java:459)
[info]   at org.reactivestreams.tck.PublisherVerification$21.run(PublisherVerification.java:862)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1092)
[info]   at org.reactivestreams.tck.PublisherVerification.required_spec309_requestZeroMustSignalIllegalArgumentException(PublisherVerification.java:858)
...
```

**Comment by patriknw** [comment]
TCK test timeout, superseded by https://github.com/akka/akka/issues/20241
