### ISSUE TITLE
EntityStreamSizeException should not have null as message

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20013]
There is a really nice and descriptive message in `toString` but message is never set, so when this exception gets logged it will look like this: 

```
akka.http.scaladsl.model.EntityStreamSizeException: null
        at akka.http.scaladsl.model.HttpEntity$$anonfun$limitable$1$$anon$1.onPush(HttpEntity.scala:498) ~[mewe-img.jar:1.0]
        at akka.http.scaladsl.model.HttpEntity$$anonfun$limitable$1$$anon$1.onPush(HttpEntity.scala:478) ~[mewe-img.jar:1.0]
        at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:56) ~[mewe-img.jar:1.0]
...
```

Which isn't very nice. I think we should provide the `toString` as `message`.

**Comment by ktoso** [comment]
I guess the too many http tags are confusing people hm... should we indeed collapse?

**Comment by ktoso** [comment]
I concur.
