### ISSUE TITLE
FAILED: MessageSpec (WS)

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20023]
https://jenkins.akka.io:8498/job/akka-multi-node/1394/consoleFull

```
[info]   reject unexpected frames
[info]     reserved bits set
[info]     - rsv1 (48 milliseconds)
[info]     - rsv2 (47 milliseconds)
[info]     - rsv3 (46 milliseconds)
[ERROR] [03/11/2016 16:25:45.017] [MessageSpec-akka.actor.default-dispatcher-2] [akka://MessageSpec/user/StreamSupervisor-12/flow-103-0-unknown-operation] Error in stage [FrameEventParser]: Highest bit of 64bit length was set
akka.http.impl.engine.ws.ProtocolException: Highest bit of 64bit length was set
	at akka.http.impl.engine.ws.FrameEventParser$$anon$1$ReadFrameHeader$.parse(FrameEventParser.scala:68)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.akka$stream$impl$io$ByteStringParser$ParsingLogic$$doParse(ByteStringParser.scala:40)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic$$anon$2.onPush(ByteStringParser.scala:65)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:582)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:593)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:535)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:442)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:386)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:546)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:492)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info]   - highest bit of 64-bit length is set *** FAILED *** (3 seconds, 66 milliseconds)
[info]     java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class akka.http.impl.engine.ws.ProtocolException,None,Left(),false)
[info]     at akka.testkit.EventFilter.intercept(TestEventListener.scala:113)
[info]     at akka.http.impl.engine.ws.MessageSpec$$anonfun$1$$anonfun$apply$mcV$sp$58$$anonfun$apply$mcV$sp$63$$anon$48.<init>(MessageSpec.scala:745)
[info]     at akka.http.impl.engine.ws.MessageSpec$$anonfun$1$$anonfun$apply$mcV$sp$58$$anonfun$apply$mcV$sp$63.apply$mcV$sp(MessageSpec.scala:722)
[info]     at akka.http.impl.engine.ws.MessageSpec$$anonfun$1$$anonfun$apply$mcV$sp$58$$anonfun$apply$mcV$sp$63.apply(MessageSpec.scala:722)
[info]     at akka.http.impl.engine.ws.MessageSpec$$anonfun$1$$anonfun$apply$mcV$sp$58$$anonfun$apply$mcV$sp$63.apply(MessageSpec.scala:722)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:373)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1740)
[info]     at org.scalatest.FreeSpecLike$class.invokeWithFixture$1(FreeSpecLike.scala:370)
[info]     at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
[info]     at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:382)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:382)
[info]     at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1740)
[info]     at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
[info]     at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:441)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
```

**Comment by johanandren** [comment]
Duplicate of #19995 ?

**Comment by ktoso** [comment]
This looks a bit different: `[ERROR] [03/11/2016 16:25:45.017] [MessageSpec-akka.actor.default-dispatcher-2] [akka://MessageSpec/user/StreamSupervisor-12/flow-103-0-unknown-operation] Error in stage [FrameEventParser]: Highest bit of 64bit length was set
akka.http.impl.engine.ws.ProtocolException: Highest bit of 64bit length was set
`

though the second error here is the same yeah, I'll keep open until we look at it?

**Comment by johanandren** [comment]
Sounds good.

**Comment by ktoso** [comment]
Yes, indeed duplicate.
