### ISSUE TITLE
FAILED PersistentClusterSharding

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20056]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/5521/consoleFull

```
[JVM-3] - must setup shared journal *** FAILED ***
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[JVM-3]   at scala.Predef$.assert(Predef.scala:165)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:434)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:407)
[JVM-3]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:734)
[JVM-3]   at akka.cluster.sharding.ClusterShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(ClusterShardingSpec.scala:308)
...
```

**Comment by patriknw** [comment]
Fails during tests setup when trying to identify an actor. Test looks correct.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6107/consoleFull
