### ISSUE TITLE
Failed Running SimpleClusterApp

### ISSUE THREAD

**Issue by darionyaphet** [akka/akka#20134]
I running `SimpleClusterApp` with `jdk1.8.0_40` and  `libsigar-universal64-macosx.dylib` not found.

Java stack looks like : 

```
no libsigar-universal64-macosx.dylib in java.library.path
org.hyperic.sigar.SigarException: no libsigar-universal64-macosx.dylib in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:174)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:102)
	at akka.cluster.metrics.SigarProvider$class.verifiedSigarInstance(Provision.scala:48)
	at akka.cluster.metrics.DefaultSigarProvider.verifiedSigarInstance(Provision.scala:92)
	at akka.cluster.metrics.SigarProvider$$anonfun$createSigarInstance$2.apply(Provision.scala:67)
	at akka.cluster.metrics.SigarProvider$$anonfun$createSigarInstance$2.apply(Provision.scala:67)
	at akka.cluster.metrics.TryNative$.apply(Provision.scala:101)
	at akka.cluster.metrics.SigarProvider$class.createSigarInstance(Provision.scala:66)
	at akka.cluster.metrics.DefaultSigarProvider.createSigarInstance(Provision.scala:92)
	at akka.cluster.metrics.SigarMetricsCollector.<init>(MetricsCollector.scala:202)
	at akka.cluster.metrics.SigarMetricsCollector.<init>(MetricsCollector.scala:207)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(ReflectiveDynamicAccess.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(ReflectiveDynamicAccess.scala:39)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(ReflectiveDynamicAccess.scala:39)
	at scala.util.Success.flatMap(Try.scala:231)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
	at akka.cluster.metrics.MetricsCollector$$anonfun$akka$cluster$metrics$MetricsCollector$$create$1$1.apply(MetricsCollector.scala:64)
	at akka.cluster.metrics.MetricsCollector$$anonfun$akka$cluster$metrics$MetricsCollector$$create$1$1.apply(MetricsCollector.scala:61)
	at akka.cluster.metrics.TryNative$.apply(Provision.scala:101)
	at akka.cluster.metrics.MetricsCollector$.akka$cluster$metrics$MetricsCollector$$create$1(MetricsCollector.scala:61)
	at akka.cluster.metrics.MetricsCollector$.apply(MetricsCollector.scala:70)
	at akka.cluster.metrics.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:153)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at akka.util.Reflect$.instantiate(Reflect.scala:44)
	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:105)
	at akka.actor.Props.newActor(Props.scala:214)
	at akka.actor.ActorCell.newActor(ActorCell.scala:592)
	at akka.actor.ActorCell.create(ActorCell.scala:620)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:488)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:511)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:292)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

finally using akka's native lib 

```
Sigar library provisioned: /Users/darion.johannes.yaphet/source/akka-2.4.1/target/native/libsigar-universal64-macosx.dylib
```

**Comment by patriknw** [comment]
@darionyaphet Have you tried what is described here: http://doc.akka.io/docs/akka/2.4.3/scala/cluster-metrics.html#Hyperic_Sigar_Provisioning ?

**Comment by patriknw** [comment]
@darionyaphet any update here?
