### ISSUE TITLE
cannot inherit from final class..

### ISSUE THREAD

**Issue by stianSjoli** [akka/akka#20153]
Hey, 
I am suddenly getting this error while trying to follow some of your code in the higher level server API. Any new changes making it a problem? 

Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at akka.http.impl.settings.ParserSettingsImpl$.fromSubConfig(ParserSettingsImpl.scala:63)
	at akka.http.impl.settings.ParserSettingsImpl$.fromSubConfig(ParserSettingsImpl.scala:53)
	at akka.http.impl.util.SettingsCompanion.apply(SettingsCompanion.scala:44)
	at akka.http.scaladsl.settings.ParserSettings$.apply(ParserSettings.scala:122)
	at akka.http.scaladsl.settings.ParserSettings$.apply(ParserSettings.scala:95)
	at akka.http.scaladsl.settings.SettingsCompanion$class.apply(SettingsCompanion.scala:16)
	at akka.http.scaladsl.settings.ParserSettings$.apply(ParserSettings.scala:95)
	at akka.http.scaladsl.settings.SettingsCompanion$class.default(SettingsCompanion.scala:17)
	at akka.http.scaladsl.settings.ParserSettings$.default(ParserSettings.scala:95)
	at HttpAkka$.run(HttpAkka.scala:39)
	at CmdUI$.main(CmdUI.scala:12)

**Comment by ktoso** [comment]
Please include your config and akka version

**Comment by stianSjoli** [comment]
I think maybe I got it to work after all. I will remove the issue, and resubmit if I get it again..

**Comment by ktoso** [comment]
Sure, thanks. Please explain though what the issue was – in case someone bumps into the same thing :wink:

**Comment by ryanskinner** [comment]
I hit this exact same issue.  How was it resolved? @stianSjoli

**Comment by ktoso** [comment]
Most likely you're mixing versions of Akka – please make sure all dependencies are of the same version, i.e. `2.4.3`

**Comment by stianSjoli** [comment]
yes, I believe I changed my dependencies - dependencies are all over the
place (some experimental etc. etc.)

**Comment by ktoso** [comment]
Please keep "the akka version" consistent though, you can't pick and choose "version X actor, but version Y cluster" – that may end up on weird things. 

We do guarantee binary compatibility between versions (which libraries care about mostly), but please don't use werid mixes of versions :)

**Comment by ryanskinner** [comment]
I was able to figure it out as well and it was that I needed to move off of some of the "experimental" jars.  Thanks all for the help.
