### ISSUE TITLE
Stream supervisor strategy ignores exception on inner java stream

### ISSUE THREAD

**Issue by DonMcNamara** [akka/akka#20173]
I'm a bit new to streams, so this might be a misunderstanding of how supervisor strategies are supposed to work.

**Scenario**: A stream is is using flapMapConcat to consume a java input stream. An exception occurs in the java input stream.
**Expected behavior**: The supervision strategy dictates the behavior when an exception occurs. In this case we would like to resume or restart.
**Actual behavior**: The exception is thrown and seems to bypass the supervisor strategy and seems to stop the execution of the stream.

Code to recreate:
```
import akka.actor.ActorSystem
import akka.stream.Supervision.Decider
import akka.stream._
import akka.stream.scaladsl.{Flow, Sink, Source, StreamConverters}

import scala.concurrent.duration.{Duration, _}
import scala.concurrent.{Await, Future}


object Testing {

  class TestStream(items: List[Byte]) extends java.io.InputStream {
    var position = 0

    override def read(): Int = {
      if (!items.isDefinedAt(position))
        -1
      else {
        val currentByte = items(position)
        position += 1
        if (currentByte == 100) throw new Exception("Kapow!")  // this exception seems to skip the supervision strategy
        currentByte
      }
    }
  }

  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem("MyActorSystem")
    val decider: Decider = Supervision.resumingDecider
    implicit val materializer = ActorMaterializer(ActorMaterializerSettings(system).withSupervisionStrategy(decider))

    // To toggle error behavior uncomment one of these lines
    //val innerStreamData = List[Byte](1,1,9,1,1,1,1)   // <-- use a 9 to cause exception in map (handled by decider)
    val innerStreamData = List[Byte](1,1,100,1,1,1,1) // <-- use 100 to cause exception in stream (not handled by decider?)

    val source = Source(List(1))
      .map(i => StreamConverters.fromInputStream(() => new TestStream(innerStreamData)))
      .flatMapConcat(identity)
      .expand(bs => bs.toIterator)
      .map(byte => byte.toInt)
      .map(i => if (i==9) throw new Exception("No nines allowed.") else i)  // an exception here is handled by the supervision strategy

    val sumSink = Sink.fold[Int, Int](0)(_ + _)

    val futureValue: Future[Int] = source.runWith(sumSink)

    val value = Await.result(futureValue, Duration(10, SECONDS))
    println(s"### Value = $value")

    println("done.")
    system.terminate()
  }

}

```

Example output (exception handled by decider) :
```
### Value = 6
done.
[program exits]
```

Example output (exception not handled by decider):
```
[error] (run-main-0) java.lang.Exception: Kapow!
java.lang.Exception: Kapow!
	at Testing$TestStream.read(testing.scala:21)
	at java.io.InputStream.read(InputStream.java:179)
	at java.io.InputStream.read(InputStream.java:101)
	at akka.stream.impl.io.InputStreamPublisher.readAndEmit(InputStreamPublisher.scala:58)
	at akka.stream.impl.io.InputStreamPublisher.readAndSignal(InputStreamPublisher.scala:52)
	at akka.stream.impl.io.InputStreamPublisher$$anonfun$receive$1.applyOrElse(InputStreamPublisher.scala:45)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.stream.impl.io.InputStreamPublisher.akka$stream$actor$ActorPublisher$$super$aroundReceive(InputStreamPublisher.scala:33)
	at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:270)
	at akka.stream.impl.io.InputStreamPublisher.aroundReceive(InputStreamPublisher.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by patriknw** [comment]
We will revisit stream supervision later: https://github.com/akka/akka/issues/19950

Perhaps you can use `recoverWith` for restarting and ordinary try-catch for resuming.

Closing this, but linking to it from the other ticket.
