### ISSUE TITLE
Requests with method 'HEAD' must have an empty entity

### ISSUE THREAD

**Issue by jrudnick** [akka/akka#20175]
Attempted constructing a unit test (leveraging ScalatestRouteTest) for a route to the effect of this:

```
      "handles HEAD requests with 405 Method Not Allowed" in {
        HttpRequest(method = HttpMethods.HEAD, uri = Uri(“/foo”)) ~>
          Route.seal(fooRoute) ~>
          check {
            status shouldBe StatusCodes.MethodNotAllowed
          }
      }
```
The `foo` route to be tested only has support for POST methods.  If I simply change the test above from HEAD to either GET or PUT, the test will pass.  In it's current state it gives back something like: 
```
ERROR akka.actor.ActorSystemImpl - Error during processing of request HttpRequest(HttpMethod(HEAD),http://example.com/foo,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
java.lang.IllegalArgumentException: requirement failed: Requests with method 'HEAD' must have an empty entity
	at scala.Predef$.require(Predef.scala:224)
	at akka.http.scaladsl.model.HttpRequest.<init>(HttpMessage.scala:143)
	at akka.http.scaladsl.model.HttpRequest.copy(HttpMessage.scala:137)
	at akka.http.scaladsl.model.HttpRequest.withEntity(HttpMessage.scala:185)
	...
	at akka.http.scaladsl.server.RequestContextImpl.mapRequest(RequestContextImpl.scala:71)
	at 
        ...
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:24)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:24)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$textract$1$$anonfun$apply$5.apply(BasicDirectives.scala:89)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$textract$1$$anonfun$apply$5.apply(BasicDirectives.scala:89)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWith$1$$anonfun$apply$4.apply(BasicDirectives.scala:36)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWith$1$$anonfun$apply$4.apply(BasicDirectives.scala:36)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$textract$1$$anonfun$apply$5.apply(BasicDirectives.scala:89)
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$textract$1$$anonfun$apply$5.apply(BasicDirectives.scala:89)
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:27)
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:23)
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:27)
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$1.apply(ExecutionDirectives.scala:23)
	at akka.http.scaladsl.testkit.RouteTest$TildeArrow$$anon$1.apply(RouteTest.scala:156)
	at akka.http.scaladsl.testkit.RouteTest$TildeArrow$$anon$1.apply(RouteTest.scala:144)
	at akka.http.scaladsl.testkit.RouteTest$WithTransformation2.$tilde$greater(RouteTest.scala:119)
	at 
        ...
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1079)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1025)
	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1076)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:287)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at 
        ...
	at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
	at 
        ...
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:394)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:382)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:382)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:371)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:408)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:382)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:382)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:371)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:408)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:382)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:382)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:377)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:459)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
	at org.scalatest.Suite$class.run(Suite.scala:1314)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1193)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1193)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:519)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1193)
	at 
        ...
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:214)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:213)
        ...
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:356)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:506)
	at sbt.ForkMain$Run$2.call(ForkMain.java:294)
	at sbt.ForkMain$Run$2.call(ForkMain.java:284)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrudnick** [comment]
This may actually be a bug in the route implementation.  Investigating further and will close if so.

**Comment by jrudnick** [comment]
This is not a bug, rather a bug in the route implementation for the specifics of the test.

**Comment by ktoso** [comment]
Glad you solved it yourself, cheers!
