### ISSUE TITLE
FAILED: AdaptiveLoadBalancingRouter

### ISSUE THREAD

**Issue by 2m** [akka/akka#20179]
https://jenkins.akka.io:8498/job/akka-nightly-sigar/195/consoleFull

```
[JVM-1] - must prefer node with more free heap capacity *** FAILED *** (15 seconds, 733 milliseconds)
[JVM-1]   2554 did not equal 3000 (ClusterMetricsRoutingSpec.scala:216)
[JVM-1]   org.scalatest.exceptions.TestFailedException:
[JVM-1]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-1]   at akka.cluster.metrics.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$7.apply$mcV$sp(ClusterMetricsRoutingSpec.scala:216)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:335)
[JVM-1]   at akka.cluster.metrics.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(ClusterMetricsRoutingSpec.scala:202)
[JVM-1]   at akka.cluster.metrics.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(ClusterMetricsRoutingSpec.scala:190)
[JVM-1]   at akka.cluster.metrics.AdaptiveLoadBalancingRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(ClusterMetricsRoutingSpec.scala:190)
[JVM-1]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3270/consoleFull

failed together with `ActorsLeakSpec`

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3428/consoleFull

**Comment by johanandren** [comment]
Hmmm. It's each time ~50 missing req or replies to the routees. At first I thought network problems but there is no log entries about unreachable nodes. Then I thought about a race with routees not being started yet when it starts firing but that seems covered.

It does count on guaranteed delivery of every of 3000 messages though, so could still be something there.

**Comment by drewhk** [comment]
No activity since 3 months, closing.
