### ISSUE TITLE
FAILED: RemoteReDeploymentSlow

### ISSUE THREAD

**Issue by 2m** [akka/akka#20180]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3658/consoleFull

```
[JVM-2] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (25 seconds, 616 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (15 seconds) during expectMsg while waiting for HelloParent
[JVM-2]   at scala.Predef$.assert(Predef.scala:165)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:349)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:335)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(RemoteReDeploymentSpec.scala:142)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:335)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RemoteReDeploymentSpec.scala:138)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:100)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:100)
[JVM-2]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-2]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-2]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-2]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
```

```
[JVM-1] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (26 seconds, 121 milliseconds)
[JVM-1]   java.lang.RuntimeException: barrier failed: re-deployed
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:661)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:797)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:655)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:649)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
```

**Comment by patriknw** [comment]
Here was another one from another ticket: https://jenkins.akka.io:8498/job/akka-multi-node/1403/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3983/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4005/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3519/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1757/consoleFull

**Comment by patriknw** [comment]
another one, on the artery-dev branch, but it was not with artery: https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7480/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7548/consoleText

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3882/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/12658

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4062/consoleFull

**Comment by jrudolph** [comment]
Here's a similar one in RemoteReDeploymentFast:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4612/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4688/consoleFull

**Comment by bantonsson** [comment]
We have different failure in Cinnamon in the Artery flavours of these tests. Not directly related but I'll try to get to the bottom of the issues with this test.

**Comment by patriknw** [comment]
+1

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/701/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/4371/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4878/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.4/210/consoleFull

**Comment by johanandren** [comment]
Sorry, still unstable
https://jenkins.akka.io:8498/job/akka-nightly/4495/consoleFull

**Comment by raboof** [comment]
Interesting detail:
```
[JVM-1] [WARN] [06/14/2017 04:15:23.947] [RemoteReDeploymentMultiJvmSpec-akka.actor.default-dispatcher-3] [akka.trttl.gremlin.tcp://RemoteReDeploymentMultiJvmSpec@localhost:44784/user/parent] received dead letter from Actor[akka://RemoteReDeploymentMultiJvmSpec/remote/akka.trttl.gremlin.tcp/RemoteReDeploymentMultiJvmSpec@localhost:44784/user/parent/hello#-623210368]: HelloParent
```
on JVM-1

**Comment by raboof** [comment]
Another one: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5051/consoleFull
```
[JVM-2] - must terminate the child when its parent system is replaced by a new one (on node 'second', class akka.remote.RemoteReDeploymentSlowMultiJvmNode2) *** FAILED *** (25 seconds, 618 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (15 seconds) during expectMsg while waiting for HelloParent
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:386)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:372)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:831)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(RemoteReDeploymentSpec.scala:163)
```

**Comment by raboof** [comment]
And again: https://jenkins.akka.io:8498/job/akka-nightly-2.12/257/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5108/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/781/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/2222/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4710/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/334/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2337/consoleFull

**Comment by patriknw** [comment]
Looks like we have several issues for RemoteReDeploymentSpec, which probably/hopefully are all the same. Closing in favor of https://github.com/akka/akka/issues/23838
