### ISSUE TITLE
JUnitRouteTest returns always 500 Internal Server Error with RequestVals.entityAs(Jackson.jsonAs(<Body.class>));

### ISSUE THREAD

**Issue by dialtahi** [akka/akka#20200]
I am executing tests of my components using Akka HTTP Java DSL with JUnitRouteTest but when the route uses a RequestVal to unmarshall the request, JUnitRouteTest always fails with 500 status no executing the route in the request.

```java

private RequestVal<Command> commandVal = RequestVals.entityAs(Jackson.jsonAs(Command.class));

@Override
  public Route createRoute() {

    Route route =
            handleWith1(commandVal, (context, command) -> handleCommand(context, command));

    return
            route(
                    path("api", "entity").route(
                            post(
                                    pathEndOrSingleSlash().route(
                                            route
                                    )
                            )
                    )
            );

  }
```

```java
@Test
  public void shouldAcceptCommandWithPost() throws JsonProcessingException {
    TestRoute appRoute = testAppRoute(new MyService());
    appRoute.run(HttpRequest.POST("/api/entity").withEntity(new ObjectMapper().writeValueAsBytes(
            new Command("some value", "some other value"))))
            .assertStatusCode(200)
            .assertEntity("453543543");
  }
```

```java
java.lang.AssertionError: Unexpected status code! 
Expected :200 OK
Actual   :500 Internal Server Error
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$2.assertEquals(JUnitRouteTest.scala:28)
	at akka.http.javadsl.testkit.TestResponse.assertEqualsKind(TestResponse.scala:160)
	at akka.http.javadsl.testkit.TestResponse.assertStatusCode(TestResponse.scala:93)
	at akka.http.javadsl.testkit.TestResponse.assertStatusCode(TestResponse.scala:87)
	at com.company.services.MyServiceTest.shouldAcceptCommandWithPost(MyServiceTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

Regards,

**Comment by ktoso** [comment]
But what is the actual error? It's hard to say anything given the above, but bear in mind that request vals et all will be removed in the next Akka release (we're about to merge a completely new Java DSL), please try it then.

**Comment by dialtahi** [comment]
Always returns
java.lang.AssertionError: Unexpected status code! 
Expected :200 OK
Actual   :500 Internal Server Error
 <Click to see difference>

The test doesn't give more information. 

I'll wait for the new DSL. Thanks.

**Comment by ktoso** [comment]
I'll close this for now, please report back once we release 2.4.4 and can try the new DSL>

**Comment by ktoso** [comment]
Today I found a bug in the TestKit *itself*, that it would not use the logger but always pass in the `NoLogging` object – which would make it impossible to get the logs about what _really_ caused the 500 response – this is fixed in my new JavaDSL branch and will PR it soon.
