### ISSUE TITLE
java.util.NoSuchElementException in GraphDSL

### ISSUE THREAD

**Issue by 13h3r** [akka/akka#20216]
This happens in 2.4.3, but not in 2.4.2

```scala
import akka.actor.ActorSystem
import akka.stream.scaladsl.{Broadcast, Flow, GraphDSL, Sink, Source, Zip}
import akka.stream.{ActorMaterializer, ActorMaterializerSettings, FlowShape}

object AkkaTest extends App {

  implicit val as = ActorSystem("ReactiveKafka")
  implicit val materializer = ActorMaterializer(
    ActorMaterializerSettings(as)
      .withInputBuffer(16, 16)
      .withAutoFusing(false)
  )
  val subflow = GraphDSL.create() { implicit b =>
    import GraphDSL.Implicits._
    val zip = b.add(Zip[String, String]())
    val bc = b.add(Broadcast[String](2))

    bc.out(0) ~> zip.in0
    bc.out(1) ~> zip.in1

    FlowShape(bc.in, zip.out)
  }.named("subflow")

  val higherLevelFlow = Flow[String].via(subflow).named("higherLevelFlow")

  //fails
  Source(List("")).via(higherLevelFlow).to(Sink.ignore).run()

  //ok
  Source(List("")).via(subflow).to(Sink.ignore).run()
}
```

The flow which uses higherLevelFlow fails with this exception: 

```
Exception in thread "main" java.util.NoSuchElementException: key not found: ZipWith2.in0
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at akka.stream.impl.MaterializerSession.assignPort(StreamLayout.scala:911)
	at akka.stream.impl.MaterializerSession$$anonfun$akka$stream$impl$MaterializerSession$$exitScope$1.apply(StreamLayout.scala:803)
	at akka.stream.impl.MaterializerSession$$anonfun$akka$stream$impl$MaterializerSession$$exitScope$1.apply(StreamLayout.scala:802)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at akka.stream.impl.MaterializerSession.akka$stream$impl$MaterializerSession$$exitScope(StreamLayout.scala:802)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:858)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:850)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:850)
	at akka.stream.impl.MaterializerSession.materializeComposite(StreamLayout.scala:884)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:860)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:850)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:850)
	at akka.stream.impl.MaterializerSession.materializeComposite(StreamLayout.scala:884)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:860)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:850)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:850)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:857)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:850)
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:163)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:850)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:817)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:190)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:79)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:367)
	at casino.kasha.AkkaTest$.delayedEndpoint$casino$kasha$AkkaTest$1(AkkaTest.scala:29)
	at casino.kasha.AkkaTest$delayedInit$body.apply(AkkaTest.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at casino.kasha.AkkaTest$.main(AkkaTest.scala:7)
	at casino.kasha.AkkaTest.main(AkkaTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Flow which uses `subflow` directly works fine.

**Comment by 13h3r** [comment]
Any thoughts how to fix it? Yesterday I take a look into materializer, but was unable to figure out where exactly the problem is.

**Comment by drewhk** [comment]
I think this is caused by the new, optimized materialized value computation. It is not a trivial fix, we will look into it.

**Comment by drewhk** [comment]
No, this is something else, have nothing to do with materialized values.

**Comment by 13h3r** [comment]
Here it is the materialization log:

```
beginning materialization of CompositeModule [1dd92fe2]
  Name: unnamed
  Modules:
    (iterableSource) CompositeModule [3b2c72c2]
      Name: iterableSource
      Modules:
        (singleSource) GraphStage(SingleSource(List())) [491666ad]
        (unnamed) [51931956] copy of GraphStage(StatefulMapConcat) [2b4a2ec7]
      Downstreams: 
        single.out -> StatefulMapConcat.in
      Upstreams: 
        StatefulMapConcat.in -> single.out
      MatValue: Atomic(singleSource[491666ad])
    (higherLevelFlow) [0c8e4bb0] copy of CompositeModule [6279cee3]
      Name: higherLevelFlow
      Modules:
        (subflow) CompositeModule [4206a205]
          Name: subflow
          Modules:
            (unnamed) [29ba4338] copy of GraphStage(Zip) [57175e74]
            (unnamed) [7bb58ca3] copy of GraphStage(Broadcast) [0c540f5a]
          Downstreams: 
            Broadcast.out0 -> ZipWith2.in0
            Broadcast.out1 -> ZipWith2.in1
          Upstreams: 
            ZipWith2.in0 -> Broadcast.out0
            ZipWith2.in1 -> Broadcast.out1
          MatValue: Atomic(akka.stream.impl.StreamLayout$CopiedModule[29ba4338])
      Downstreams: 
      Upstreams: 
      MatValue: Ignore
    (ignoreSink) SinkholeSink [770c2e6b]
  Downstreams: 
    single.out -> StatefulMapConcat.in
    StatefulMapConcat.out -> Broadcast.in
    ZipWith2.out -> SinkholeSink.in
  Upstreams: 
    StatefulMapConcat.in -> single.out
    Broadcast.in -> StatefulMapConcat.out
    SinkholeSink.in -> ZipWith2.out
  MatValue: Atomic(iterableSource[3b2c72c2])
entering module [1dd92fe2] (StreamLayout$CompositeModule)
entering module [3b2c72c2] (StreamLayout$CompositeModule)
entering scope [51931956]
entering module [51931956] (StreamLayout$CopiedModule)
resolving module [51931956] computation Atomic(statefulMapConcat[2b4a2ec7])
  matValSrc = {}
  matVals =
    2b4a2ec7 -> NotUsed
  Atomic(statefulMapConcat[2b4a2ec7])
  result = NotUsed
exiting module [51931956]
exiting scope [51931956]
  subscribers = {StatefulMapConcat.in=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@5d47c63f}
  publishers = {StatefulMapConcat.out=akka.stream.impl.fusing.ActorGraphInterpreter$BoundaryPublisher@5ea434c8}
resolving module [3b2c72c2] computation Atomic(singleSource[491666ad])
  matValSrc = {}
  matVals =
    51931956 -> NotUsed
    491666ad -> NotUsed
  Atomic(singleSource[491666ad])
  result = NotUsed
exiting module [3b2c72c2]
entering scope [0c8e4bb0]
entering module [0c8e4bb0] (StreamLayout$CopiedModule)
entering module [6279cee3] (StreamLayout$CompositeModule)
entering module [4206a205] (StreamLayout$CompositeModule)
entering scope [29ba4338]
entering module [29ba4338] (StreamLayout$CopiedModule)
resolving module [29ba4338] computation Atomic(ZipWith2[57175e74])
  matValSrc = {}
  matVals =
    57175e74 -> NotUsed
  Atomic(ZipWith2[57175e74])
  result = NotUsed
exiting module [29ba4338]
exiting scope [29ba4338]
  subscribers = {ZipWith2.in1=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@4c6e276e, ZipWith2.in0=akka.stream.impl.fusing.ActorGraphInterpreter$BoundarySubscriber@534df152}
  publishers = {ZipWith2.out=akka.stream.impl.fusing.ActorGraphInterpreter$BoundaryPublisher@52e677af}
```

The problem is here:

```
entering scope [0c8e4bb0]
entering module [0c8e4bb0] (StreamLayout$CopiedModule)
entering module [6279cee3] (StreamLayout$CompositeModule)
entering module [4206a205] (StreamLayout$CompositeModule)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
entering scope [29ba4338]
```

We do the second enter into CompositeModule without scope changing. This caused by optimization with identity flow (`Flow.viaMat`). If we call via at non-identity flow materializer will do scope changing at second CompositeModule.

```scala
object AkkaTest extends App {

  implicit val as = ActorSystem("ReactiveKafka")
  implicit val materializer = ActorMaterializer(
    ActorMaterializerSettings(as)
      .withInputBuffer(16, 16)
      .withAutoFusing(false)
  )
  val subflow = GraphDSL.create() { implicit b =>
    import GraphDSL.Implicits._
    val zip = b.add(Zip[String, String]())
    val bc = b.add(Broadcast[String](2))

    bc.out(0) ~> zip.in0
    bc.out(1) ~> zip.in1

    FlowShape(bc.in, zip.out)
  }.named("subflow")

  val higherLevelFlow = Flow[String]
    .map(identity)  //this one gives us non-identity flow
    .via(subflow)
    .named("higherLevelFlow")

  //NOW OK!!!
  Source(List("")).via(higherLevelFlow).to(Sink.ignore).run()
}
```

Unfortunately I am not very familiar how materializer works and therefore not sure how to fix it. My initial though was to fix `viaMat`:
- when `m` is already a `CompositeModule` build flow based on it
- in other case create new `CompositeModule` like now

```scala
      m match {
        case _: CompositeModule => new Flow(m)
        case _ => new Flow(CompositeModule(Set(m), m.shape, empty, empty, mat, Attributes.none))
      }
```

This fix works, but I am not sure about all this attributes for `CompositeModule.

Could you please confirm
- that I am right on the root of the problem
- that this fix is correct

Thanks!

**Comment by patriknw** [comment]
Thanks for your investigations, we will look at this on Monday.

**Comment by drewhk** [comment]
The identity optimization does not copy the module since there is no need to. There are no possible clashes between port identities because it is the only module imported right now. Further modules are added through `via` which will properly copy them, avoiding the port conflict again. Something else is the issue, but related to this new implementation.

**Comment by drewhk** [comment]
Found the actual issue.

**Comment by drewhk** [comment]
There is a fix PR now

**Comment by drewhk** [comment]
The issue was that the MaterializerSession assumed one of the following to hold:
 - the port is wired in the current module *or*
 - the port is exposed in the current scope (interface port)

Obviously, if the port was wired in an enclosing module, and hence not exposed as an interface port at the CopiedModule level, that assumption was violated since the port was neither wired in the current module nor exposed in the current scope.
