### ISSUE TITLE
FAILED akka.cluster.StressSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20223]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3683/consoleFull

```
[JVM-7] - must use routers with high throughput *** FAILED *** (3 seconds, 11 milliseconds)
[JVM-7]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[JVM-7]   at scala.Predef$.assert(Predef.scala:165)
[JVM-7]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:434)
[JVM-7]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:407)
[JVM-7]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:734)
[JVM-7]   at akka.cluster.StressSpec.clusterResultAggregator(StressSpec.scala:790)
```

**Comment by patriknw** [comment]
This is a bit different than failures we "normally" see in this test. Here it fails on an identification of one of the test result actors. I can't see anything wrong with barriers and such.

**Comment by ktoso** [comment]
Again

```
[JVM-3] - must use many actors with high throughput *** FAILED *** (20 seconds, 3 milliseconds)
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (19976982285 nanoseconds) during expectMsgClass waiting for class akka.cluster.StressMultiJvmSpec$WorkResult
[JVM-3]   at scala.Predef$.assert(Predef.scala:165)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:434)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:407)
[JVM-3]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:734)
[JVM-3]   at akka.cluster.StressSpec.awaitWorkResult(StressSpec.scala:1056)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1037)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec.reportResult(StressSpec.scala:943)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18.apply$mcV$sp(StressSpec.scala:1029)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:335)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1.apply$mcV$sp(StressSpec.scala:1028)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1.apply(StressSpec.scala:1023)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1.apply(StressSpec.scala:1023)
[JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:307)
[JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:734)
[JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:321)
[JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:734)
[JVM-3]   at akka.cluster.StressSpec.exerciseRouters(StressSpec.scala:1023)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$4$$anonfun$apply$mcV$sp$47.apply$mcV$sp(StressSpec.scala:1230)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$4$$anonfun$apply$mcV$sp$47.apply(StressSpec.scala:1228)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$4$$anonfun$apply$mcV$sp$47.apply(StressSpec.scala:1228)
[JVM-3]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[JVM-3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-3]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[JVM-3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[JVM-3]   at akka.cluster.StressSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(StressSpec.scala:697)
[JVM-3]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:171)
[JVM-3]   at akka.cluster.StressSpec.withFixture(StressSpec.scala:697)
[JVM-3]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[JVM-3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[JVM-3]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[JVM-3]   at akka.cluster.StressSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(StressSpec.scala:697)
[JVM-3]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:255)
[JVM-3]   at akka.cluster.StressSpec.runTest(StressSpec.scala:697)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[JVM-3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[JVM-3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[JVM-3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[JVM-3]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[JVM-3]   at akka.cluster.StressSpec.runTests(StressSpec.scala:697)
[JVM-3]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[JVM-3]   at akka.cluster.StressSpec.org$scalatest$WordSpecLike$$super$run(StressSpec.scala:697)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[JVM-3]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[JVM-3]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[JVM-3]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[JVM-3]   at akka.cluster.StressSpec.org$scalatest$BeforeAndAfterAll$$super$run(StressSpec.scala:697)
[JVM-3]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[JVM-3]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[JVM-3]   at akka.cluster.StressSpec.run(StressSpec.scala:697)
[JVM-3]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
[JVM-3]   at scala.collection.immutable.List.foreach(List.scala:381)
[JVM-3]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[JVM-3]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[JVM-3]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[JVM-3]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[JVM-3]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
[JVM-3]   at org.scalatest.tools.Runner.main(Runner.scala)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3711/consoleFull

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3827/consoleFull

**Comment by drewhk** [comment]
This is rather old, but probably not old enough to just close especially since it reoccured a few times. Please review if this ticket is likely relevant now.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4071/consoleFull

```
- must use many actors with high throughput *** FAILED *** (10 seconds, 244 milliseconds)
[JVM-3]   55 did not equal 0 (StressSpec.scala:1047)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6356)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1047)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1034)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1034)
[JVM-3]   at akka.cluster.StressSpec.reportResult(StressSpec.scala:948)
...
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3582/consoleFull

**Comment by patriknw** [comment]
This is rather weird. The logs show unexpected dead letters, such as
```
[JVM-1] [WARN] [08/07/2016 00:37:52.328] [StressSpec-akka.actor.default-dispatcher-14] [akka://StressSpec/remote/akka.tcp/StressSpec@a6.moxie:53877/user/master-node-3/workers/c4/tree/2/2/2/2] received dead letter from Actor[akka.tcp://StressSpec@a6.moxie:53877/user/master-node-3#464821887]: (2,SimpleJob(27,[B@8f2ae2d))
```

The tests sends a TreeJob from the Master to the Worker and the Worker creates a hierarchy of local child actors and delegates the job down the hierarchy. If I don't completely misunderstand the above dead letter it means that a local message sent to a newly created child actor is not delivered. How can that be possible?

I have run the failing test 87 times locally without any failures.

**Comment by drewhk** [comment]
also with normal throughput: https://jenkins.akka.io:8498/job/akka-nightly/3818/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/246/consoleFull

**Comment by drewhk** [comment]
Have not happened since a while, but there were multiple occurences before, so keeping open.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4589/consoleFull

Not exactly the same though `must use routers with high throughput`

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1941/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2079/consoleFull
```
[JVM-3] - must use routers with high throughput *** FAILED *** (10 seconds, 59 milliseconds)
[JVM-3]   18 did not equal 0 (StressSpec.scala:1029)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2123/consoleFull

There was some crazy GC going on just a bit before it though.

```
[JVM-3] - must use many actors with normal throughput *** FAILED *** (30 seconds, 108 milliseconds)
[JVM-3]   8 did not equal 0 (StressSpec.scala:1029)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5060/consoleFull

```
[JVM-3] - must use many actors with normal throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (30 seconds, 113 milliseconds)
[JVM-3]   13 did not equal 0 (StressSpec.scala:1029)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
[JVM-3]   at akka.cluster.StressSpec.reportResult(StressSpec.scala:930)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18.apply$mcV$sp(StressSpec.scala:1016)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5063/consoleFull

```
[JVM-2] - must use routers with high throughput (on node 'node-2', class akka.cluster.StressMultiJvmNode10) *** FAILED *** (18 seconds, 48 milliseconds)
[JVM-2]   58 did not equal 0 (StressSpec.scala:1029)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/798/consoleFull

```
[JVM-3] - must use many actors with high throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (10 seconds, 257 milliseconds)
[JVM-3]   21 did not equal 0 (StressSpec.scala:1029)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1029)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4701/consoleFull

```
[JVM-3] - must use routers with normal throughput (on node 'node-3', class akka.cluster.StressMultiJvmNode11) *** FAILED *** (30 seconds, 65 milliseconds)
[JVM-3]   15 did not equal 0 (StressSpec.scala:1029)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply$mcV$sp(StressSpec.scala:1029)
[JVM-3]   at akka.cluster.StressSpec$$anonfun$exerciseRouters$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$mcV$sp$19.apply(StressSpec.scala:1016)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.4/413/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5152/

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5270

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/511/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/556/consoleFull

**Comment by johanandren** [comment]
Stared at this for a while and both this and the artery one (#21810) seems to have 
```
[StressSpec-akka.actor.default-dispatcher-20] [akka.actor.LocalActorRefProvider(akka://StressSpec)] akka://StressSpec/remote trying to remove non-child akka.tcp/StressSpec@localhost:45541/user/master-node-3/workers/c5
```
In the logs while successful runs does not (I'm not 100% sure though). Didn't get anywhere from that though.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5771/consoleText

Note this warning that might be related to https://github.com/akka/akka/issues/24393

```
[info] [JVM-2] [WARN] [08/14/2018 02:36:48.066] [StressSpec-akka.remote.default-remote-dispatcher-16] [akka.tcp://StressSpec@localhost:39259/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FStressSpec%40localhost%3A33149-0/endpointWriter/endpointReader-akka.tcp%3A%2F%2FStressSpec%40localhost%3A33149-0] Discarding inbound message to [unknown] in read-only association to [akka.tcp://StressSpec@localhost:33149]. If this happens often you may consider using akka.remote.use-passive-connections=off or use Artery TCP.
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6386/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6587/log/?start=0

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.11/844/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6470

**Comment by patriknw** [comment]
obsolete

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/442/consoleFull

**Comment by ignasi35** [comment]
I'm closing this in favor of https://github.com/akka/akka/issues/23511 (PS: for artery-specific there's also https://github.com/akka/akka/issues/21810)
