### ISSUE TITLE
Reduce emits null if used with AnyRef and an empty source

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20262]
Reduce initially uses a default value as aggregate:

```Scala
var aggregator: T = _
```

Which means that it is `null` for non-primitives. If upstream closes before emitting any element the `aggregator` value is emitted downstream that emits a `null` downstream which is illegal.

I think it should just close rather than pass the empty value downstream, if you want a seed that is emitted on empty upstream you can always use `fold` instead.

**Comment by viktorklang** [comment]
It should behave just like any empty collection's reduce:

~~~scala
scala> Vector[Int]().reduce(_ + _)
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
  at scala.collection.AbstractTraversable.reduceLeft(Traversable.scala:104)
  at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
  at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
  ... 32 elided

scala> Array[Int]().reduce(_ + _)
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
  at scala.collection.mutable.ArrayOps$ofInt.scala$collection$IndexedSeqOptimized$$super$reduceLeft(ArrayOps.scala:234)
  at scala.collection.IndexedSeqOptimized$class.reduceLeft(IndexedSeqOptimized.scala:74)
  at scala.collection.mutable.ArrayOps$ofInt.reduceLeft(ArrayOps.scala:234)
  at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
  at scala.collection.mutable.ArrayOps$ofInt.reduce(ArrayOps.scala:234)
  ... 32 elided

scala> List.empty[Int].reduce(_ + _)
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.LinearSeqOptimized$class.reduceLeft(LinearSeqOptimized.scala:137)
  at scala.collection.immutable.List.reduceLeft(List.scala:84)
  at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
  at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
  ... 32 elided

scala> new Iterator[Int] { def hasNext = false; def next: Int = Iterator.empty.next }
res7: Iterator[Int] = empty iterator

scala> res7.reduce(_ + _)
java.lang.UnsupportedOperationException: empty.reduceLeft
  at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
  at $anon$1.reduceLeft(<console>:12)
  at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
  at $anon$1.reduce(<console>:12)
  ... 32 elided

~~~

**Comment by ktoso** [comment]
+1 on erroring out like collections, and also its easy to `recover` is one wants to have a "if it was empty then ByteString.empty".

**Comment by viktorklang** [comment]
I'll have a pr ready över the weekend

-- 
Cheers,
√

**Comment by ktoso** [comment]
For a change from TLS/JavaDSL I'd like to make a PR which's production doesn't make me cringe in pain – might want to take a stab at this :wink:

**Comment by ktoso** [comment]
(ping here if you start hacking so I don't duplicate effort)

**Comment by ktoso** [comment]
Oh, funny - it does the right thing if it's Sink.reduce (since it does `toMat(Sink.head)`), but doesnt on a flow I guess).

**Comment by viktorklang** [comment]
@johanandren @ktoso see: https://github.com/akka/akka/pull/20268
