### ISSUE TITLE
FileUploadDirectivesExamplesSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20431]
https://jenkins.akka.io:8498/job/akka-nightly/3282/console

```
[info] - uploadedFile *** FAILED *** (1 second, 67 milliseconds)
[info]   Request was neither completed nor rejected within 1 second (FileUploadDirectivesExamplesSpec.scala:35)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
[info]   at docs.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:12)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:94)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:59)
[info]   at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:40)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:62)
[info]   at docs.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:12)
[info]   at akka.http.scaladsl.testkit.RouteTest$class.status(RouteTest.scala:80)
[info]   at docs.http.scaladsl.server.RoutingSpec.status(RoutingSpec.scala:12)
[info]   at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FileUploadDirectivesExamplesSpec.scala:35)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3283/console

**Comment by 2beaucoup** [comment]
dupe of #20431?

**Comment by johanandren** [comment]
Indeed, thanks, didn't show up while searching, but I had a feeling I'd seen it before...

**Comment by johanandren** [comment]
Hey wait a minute, #20431 is this ticket! :D

**Comment by 2beaucoup** [comment]
That's a recursive duplicate! :smiley:

Pasted the wromg number. Actually meant #19792.

**Comment by johanandren** [comment]
Thanks
