### ISSUE TITLE
Update sbt-git

### ISSUE THREAD

**Issue by magnusart** [akka/akka#20439]
When starting sbt in the akka master branch for the first time I got the following stacktrace

```
java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
	at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:23)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.storage.file.FileRepository
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:23)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
```
Updating the `sbt-plugin` version in `plugins.sbt` to the latest version `addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")` allowed me to continue. I have not tested anything further related to `sbt-git`.

**Comment by patriknw** [comment]
ok, strange. If you open a PR I can we can try a dry-run of the release. I'm not sure where it's used.

**Comment by johanandren** [comment]
I think the problem is a global plugin pulling in a newer version of jgit (this is what I have seen before, clashes between sbt-groll and sbt-git)

I'm not sure we should upgrade because of this, upgrading it may make it clash with some other sbt-plugin someone has got installed. I think an upgrade it should be because of some improvement in the plugin we need.

**Comment by magnusart** [comment]
@johanandren what about the "functionality" of allowing new contributors to build akka without copying someones ivy cache or hacking the plugin file? It wasn't even possible to load the sbt project fully.

**Comment by johanandren** [comment]
What I am saying is that it depends on your specific global sbt config, so if we change it, it may break for other contributors. No intention to be offensive on my part!

**Comment by johanandren** [comment]
I agree on keeping up to date, but it would be nice to know if we even use the plugin somewhere in our infra, and if we don't we should just remove it instead. Not quite sure how to figure that out though.

**Comment by magnusart** [comment]
I can confirm that this is related to Codacy which uses JGit.  [Akka uses Codacy as well](https://www.codacy.com/app/opensource/akka/dashboard), but the plugin is not included in the project plugin file (good). 

I had a look again and I'm suspecting neither of `sbt-dependency-graph` and `sbt-git` are necessary for the build process.

I see your point when considering not updating `sbt-git` because there are not any new features. However I would ask you to also please consider reviewing the akka project plugins and remove plugins that are not strictly necessary for the build. 

This will be an initial inconvenience for developers who have to configure their global plugins, but it makes sense in the long run for such a central project within the Scala ecosystem.

**Comment by patriknw** [comment]
I agree that we should remove plugins that are not directly used. I have problems myself with a conflicting version of sbt-dependency-graph that I sometimes have in my global (for other projects).

**Comment by johanandren** [comment]
@drewhk @2m either of you use or know why we pull in sbt-git and sbt-dependency-graph, can we remove those?

**Comment by patriknw** [comment]
sbt-git was added in https://github.com/akka/akka/commit/293ecb09f971ff5e8039a7ccd4cd3cb09f7cddf8 for the metrics reporting, which I think we have removed now, so that should be possible to remove (including the resolver)

I'm pretty sure sbt-dependency is just for convenience, and should also be removed

**Comment by johanandren** [comment]
`sbt-dependency` seems to be used for the pr-validation

**Comment by drewhk** [comment]
I never used these. And yes, AFAIK sbt-dependency is for smart PR validation.

**Comment by drewhk** [comment]
AKA reduce build times

**Comment by drewhk** [comment]
(misclicked the close button)

**Comment by patriknw** [comment]
ok, thanks

**Comment by ktoso** [comment]
Yup, it's as Johan explains the d pendency plugin we do want to keep, the. Other one not afaics
