### ISSUE TITLE
FAILED: SinkForeachParallelSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20487]
This looks like a genuine failure:

```
[info] - must finish after function thrown exception *** FAILED *** (29 milliseconds)
[info]   java.lang.AssertionError: assertion failed: not found [2] found unexpected [4]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.checkMissingAndUnexpected(TestKit.scala:503)
[info]   at akka.testkit.TestKitBase$class.expectMsgAllOf_internal(TestKit.scala:512)
[info]   at akka.testkit.TestKitBase$class.expectMsgAllOf(TestKit.scala:484)
[info]   at akka.testkit.TestKit.expectMsgAllOf(TestKit.scala:734)
[info]   at akka.stream.scaladsl.SinkForeachParallelSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply$mcV$sp(SinkForeachParallelSpec.scala:108)
[info]   at akka.stream.scaladsl.SinkForeachParallelSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7.apply(SinkForeachParallelSpec.scala:92)
[info]   at 
```

https://jenkins.akka.io:8498/job/akka-nightly/3306/consoleFull

**Comment by lolski** [comment]
The test succeeded with no problem on my local machine. It was performed on master branch (commit https://github.com/akka/akka/commit/fe47d596bc47ec29e97d4bfa5261476baf6dfe94)
