### ISSUE TITLE
java dsl: handleRejections is not working

### ISSUE THREAD

**Issue by relgames** [akka/akka#20534]
Trying to write generic OPTIONS handler in Java DSL, but looks like handleRejections is not working properly. Trying with akka 2.4.4:
```
public class RejectionSample extends HttpApp {
    public static void main(String[] args) {
        ActorSystem akkaSystem = ActorSystem.create();

        RejectionSample rejectionSample = new RejectionSample();
        rejectionSample.bindRoute("localhost", 8080, akkaSystem);
    }

    @Override
    public Route createRoute() {
        return handleRejections(MethodRejection.class,
            (ctx, methodRejection) -> {
                return ctx.complete("NOT SUPPORTED");
            },

            path("test").route(
                get(handleWith(ctx -> ctx.complete("OK")))
            )
        );
    }
}
```
```curl -D -  http://localhost:8080/test -X POST``` fails with 
```
[2016-05-17 00:31:40,206] [  ERROR] [spatcher-5] [akka.actor.ActorSystemImpl(default)] a.a.ActorSystemImpl: Error during processing of request HttpRequest(HttpMethod(POST),http://localhost:8080/test,List(Host: localhost:8080, User-Agent: curl/7.47.1, Accept: */*, Timeout-Access: <function1>),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
java.lang.RuntimeException: Rejection handler still produced new rejections after 8 iterations. Is there an infinite handler cycle? Initial rejections: List(MethodRejection(HttpMethod(GET))) final rejections: List(MethodRejection(HttpMethod(GET)))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.8.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1.akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1(ExecutionDirectives.scala:56) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1$$anonfun$akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1$1.apply(ExecutionDirectives.scala:52) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1$$anonfun$akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1$1.apply(ExecutionDirectives.scala:52) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$recoverRejectionsWith$1.applyOrElse(BasicDirectives.scala:82) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$recoverRejectionsWith$1.applyOrElse(BasicDirectives.scala:82) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWithPF$1.apply(BasicDirectives.scala:70) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWithPF$1.apply(BasicDirectives.scala:70) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.util.FastFuture$.akka$http$scaladsl$util$FastFuture$$strictTransform$1(FastFuture.scala:41) ~[akka-http-core_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45) ~[akka-http-core_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26) ~[akka-http-core_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWith$1$$anonfun$apply$4.apply(BasicDirectives.scala:58) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWith$1$$anonfun$apply$4.apply(BasicDirectives.scala:58) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1.akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1(ExecutionDirectives.scala:52) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1$$anonfun$akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1$1.apply(ExecutionDirectives.scala:52) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.ExecutionDirectives$$anonfun$handleRejections$1$$anonfun$akka$http$scaladsl$server$directives$ExecutionDirectives$class$$anonfun$$handle$1$1.apply(ExecutionDirectives.scala:52) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$recoverRejectionsWith$1.applyOrElse(BasicDirectives.scala:82) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$recoverRejectionsWith$1.applyOrElse(BasicDirectives.scala:82) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWithPF$1.apply(BasicDirectives.scala:70) ~[akka-http-experimental_2.11-2.4.4.jar:na]
	at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResultWithPF$1.apply(BasicDirectives.scala:70) ~[akka-http-experimental_2.11-2.4.4.jar:na]
...
```

**Comment by ktoso** [comment]
We've just released a major update of the JavaDSL, please upgrade – it should work fine with the new APIs: http://akka.io/news/2016/05/17/akka-2.4.5-released.html

**Comment by johanandren** [comment]
Corresponding routes with the new DSL does indeed work
```
    Route router =
      route(
        handleRejections(
          RejectionHandler.newBuilder()
            .handle(MethodRejection.class, (rejection) -> complete("NOT SUPPORTED"))
            .build(),
          () ->
            path("test", () ->
              get(() ->
                complete("OK")
              )
            )
        )
      );
```

I'll close this ticket.

**Comment by ktoso** [comment]
Thanks a lot for checking @johanandren !
So glad we've improved so many things in the new one :-)

**Comment by relgames** [comment]
Indeed, new API works fine. Thanks @johanandren for the example.
