### ISSUE TITLE
Wrong dispatcher inhabitants count

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20567]
```
21:54:45.091UTC ERROR akka.actor.ActorSystemImpl akka.actor.ActorSystemImpl(default) - Uncaught error from thread [default-storage-context-319236]
java.lang.IllegalStateException: ACTOR SYSTEM CORRUPTED!!! A dispatcher can't have less than 0 inhabitants!
at akka.dispatch.MessageDispatcher.akka$dispatch$MessageDispatcher$$addInhabitants(AbstractDispatcher.scala:101) ~[com.typesafe.akka.akka-actor_2.11-2.4.3.jar:na]
at akka.dispatch.MessageDispatcher$$anonfun$1.apply$mcV$sp(AbstractDispatcher.scala:179) ~[com.typesafe.akka.akka-actor_2.11-2.4.3.jar:na]
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) ~[com.typesafe.akka.akka-actor_2.11-2.4.3.jar:na]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405) ~[com.typesafe.akka.akka-actor_2.11-2.4.3.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
```

**Comment by avramirez** [comment]
+1 Can someone explain what is the cause of this?

**Comment by patriknw** [comment]
@avramirez Did you also see the exception? We are very interested in finding a way to reproduce it.

**Comment by aesteppics** [comment]
@patriknw This is from a Play 2.5.4 app runing Slick 3.0.0

[ERROR] [09/23/2016 22:03:35.168] [application-akka.actor.default-dispatcher-618] [akka.actor.ActorSystemImpl(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-618] shutting down ActorSystem [application]
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
        at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:224)
        at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:38)
        at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:201)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
        at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:75)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:38)
        at slick.backend.DatabaseComponent$DatabaseDef$class.run(DatabaseComponent.scala:72)
        at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:38)
        at repositories.PWSql$.emailTemplates(PWSql.scala:236)
        at services.EmailService.emailTemplates(EmailService.scala:68)
        at controllers.EmailController$$anonfun$emailTemplates$1.apply(EmailController.scala:96)
        at controllers.EmailController$$anonfun$emailTemplates$1.apply(EmailController.scala:93)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:371)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:370)
        at play.api.mvc.Action$.invokeBlock(Action.scala:498)
        at play.api.mvc.Action$.invokeBlock(Action.scala:495)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [09/23/2016 22:03:35.607] [application-akka.actor.default-dispatcher-619] [akka.dispatch.Dispatcher] ACTOR SYSTEM CORRUPTED!!! A dispatcher can't have less than 0 inhabitants!
java.lang.IllegalStateException: ACTOR SYSTEM CORRUPTED!!! A dispatcher can't have less than 0 inhabitants!
        at akka.dispatch.MessageDispatcher.akka$dispatch$MessageDispatcher$$addInhabitants(AbstractDispatcher.scala:101)
        at akka.dispatch.MessageDispatcher$$anonfun$1.apply$mcV$sp(AbstractDispatcher.scala:179)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by patriknw** [comment]
Thanks for the info. When there is an OutOfMemoryError no rules are valid. I'll take a closer look with this in mind, but it can be the explanation to this mystery.

**Comment by aesteppics** [comment]
@patriknw I realize this is of limited help but I've been working with Play for a few years and it's always been very stable. The app this error cam from is on 2.5.4.  It's still a ways from production so I haven't been worrying too much about it.  When I first published I was on an aws micro instance.  It was "crashing" regularly.  Now it's on a medium instance and it "crashes" occasionally.  It's a rest api that deals with simple, small sql queries and small result sets and currently gets minimal request.  My guess is if you run against a limited memory pool under load you'll be able to reproduce pretty easily.

**Comment by patriknw** [comment]
@aesteppics I have tried to reproduce, but can't find a way. It can be some combination of `blocking`, `sameThreadExecutionContext` and the `OutOfMemoryError`.

You should use latest Play version, because they have changed the `akka.jvm-exit-on-fatal-error` setting, after our recommendation to do so. In 2.5.4 that is `off`, and that is dangerous, since things may be in an inconsistent state after `OutOfMemoryError`.

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/play/reference-overrides.conf#L18

I'm closing this now, but feel free to re-open and include a reproducer sample application if you see the problem again. OutOfMemoryError can be simulated with `throw new OutOfMemoryError("sim err")`
