### ISSUE TITLE
handle Aeron exceptions

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20561]
Collecting more error scenarios here.

**Comment by patriknw** [comment]
Should handshake attempts to non-existing destination be stopped?
For example when joining non-existing seed-node the handshake attempts will continue forever (or until the destination is available).

Perhaps we can make the materialization of outbound stream lazy until next message is sent, after a stream restart.

**Comment by patriknw** [comment]
when suspending a process `kill -STOP` and resuming `kill -CONT` it after the Aeron liveness timeout we get the following exception repeatedly:

```
[info] io.aeron.exceptions.ConductorServiceTimeoutException: Timeout between service calls over 10000000000ns
[info] 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:356)
[info] 	at io.aeron.ClientConductor.doWork(ClientConductor.java:312)
[info] 	at io.aeron.ClientConductor.doWorkUntil(ClientConductor.java:329)
[info] 	at io.aeron.ClientConductor.releaseSubscription(ClientConductor.java:183)
[info] 	at io.aeron.Subscription.close(Subscription.java:268)
[info] 	at io.aeron.ActiveSubscriptions$$Lambda$40/539897443.accept(Unknown Source)
[info] 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[info] 	at io.aeron.ActiveSubscriptions.close(ActiveSubscriptions.java:69)
[info] 	at io.aeron.ClientConductor.onClose(ClientConductor.java:109)
[info] 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:353)
[info] 	at io.aeron.ClientConductor.doWork(ClientConductor.java:312)
[info] 	at io.aeron.ClientConductor.doWorkUntil(ClientConductor.java:329)
[info] 	at io.aeron.ClientConductor.releaseSubscription(ClientConductor.java:183)
[info] 	at io.aeron.Subscription.close(Subscription.java:268)
[info] 	at io.aeron.ActiveSubscriptions$$Lambda$40/539897443.accept(Unknown Source)
[info] 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[info] 	at io.aeron.ActiveSubscriptions.close(ActiveSubscriptions.java:69)
[info] 	at io.aeron.ClientConductor.onClose(ClientConductor.java:109)
[info] 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:353)
[info] 	at io.aeron.ClientConductor.doWork(ClientConductor.java:312)
[info] 	at io.aeron.ClientConductor.doWorkUntil(ClientConductor.java:329)
[info] 	at io.aeron.ClientConductor.releasePublication(ClientConductor.java:157)
[info] 	at io.aeron.Publication.release(Publication.java:212)
[info] 	at io.aeron.ActivePublications$$Lambda$38/29971250.accept(Unknown Source)
[info] 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[info] 	at io.aeron.ActivePublications.close(ActivePublications.java:75)
[info] 	at io.aeron.ClientConductor.onClose(ClientConductor.java:108)
[info] 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:353)
[info] 	at io.aeron.ClientConductor.doWork(ClientConductor.java:312)
[info] 	at io.aeron.ClientConductor.doWorkUntil(ClientConductor.java:329)
[info] 	at io.aeron.ClientConductor.releasePublication(ClientConductor.java:157)
[info] 	at io.aeron.Publication.release(Publication.java:212)
[info] 	at io.aeron.ActivePublications$$Lambda$38/29971250.accept(Unknown Source)
[info] 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[info] 	at io.aeron.ActivePublications.close(ActivePublications.java:75)
[info] 	at io.aeron.ClientConductor.onClose(ClientConductor.java:108)
[info] 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:353)
[info] 	at io.aeron.ClientConductor.doWork(ClientConductor.java:312)
[info] 	at io.aeron.ClientConductor.doWorkUntil(ClientConductor.java:329)
[info] 	at io.aeron.ClientConductor.releasePublication(ClientConductor.java:157)
```

**Comment by johanandren** [comment]
When under heavy load (reproducible with `akka.cluster.NodeChurn` and `akka.cluster.Stress`) the Aeron driver heartbeating times out leading to:

```
io.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at io.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:291)
 	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:378)
 	at io.aeron.ClientConductor.doWork(ClientConductor.java:309)
```

Which then toggles the inactive flag of the `ClientConductor` leading to:
```
io.aeron.exceptions.DriverTimeoutException: Driver is inactive
```
for further interactions with Aeron.

**Comment by drewhk** [comment]
This is with the embedded driver yes?

**Comment by johanandren** [comment]
Yes

**Comment by patriknw** [comment]
created separate ticket for the handshake attempts to non-existent nodes: https://github.com/akka/akka/issues/21347

**Comment by patriknw** [comment]
I renamed this ticket to be more specific about the Aeron exception cases. I started looking at it but didn't find a nice solution. Asked at https://gitter.im/real-logic/Aeron
