### ISSUE TITLE
FAILED: DontLeakActorsOnFailingConnectionSpecs

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20580]
showed up again

```
 java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://DontLeakActorsOnFailingConnectionSpecs/user/StreamSupervisor-37/flow-0-0-unknown-operation#1027349078]]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Utils.scala:31)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:265)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:276)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:734)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:307)
[info]   at akka.testkit.TestKit.within(TestKit.scala:734)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:321)
[info]   at akka.testkit.TestKit.within(TestKit.scala:734)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.withFixture(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.runTest(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.runTests(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.org$scalatest$WordSpecLike$$super$run(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3846/consoleFull

**Comment by ktoso** [comment]
Again

```
[info] - should not leak connection Actors when hitting non-existing endpoint *** FAILED *** (19 seconds, 998 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://DontLeakActorsOnFailingConnectionSpecs/user/StreamSupervisor-50/flow-0-0-unknown-operation#-1505602400]]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Utils.scala:31)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:265)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:276)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:734)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:307)
[info]   at akka.testkit.TestKit.within(TestKit.scala:734)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:321)
[info]   at akka.testkit.TestKit.within(TestKit.scala:734)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(DontLeakActorsOnFailingConnectionSpecs.scala:40)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.withFixture(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.http.scaladsl.server.DontLeakActorsOnFailingConnectionSpecs.runTest(DontLeakActorsOnFailingConnectionSpecs.scala:23)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1544/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3367/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3369/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1572/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3884/consoleFull

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1572/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3911/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1603/consoleFull

**Comment by johanandren** [comment]
Hasn't happened since June 24, looking into if we merged something that may have fixed it around then.

**Comment by johanandren** [comment]
Nothing obvious but there was some work on bugs in various graph stages, and also some improvements on the http client connection pool, so maybe one of those. 

I'll do the daredevil move closing it (and see how it all of a sudden starts happening again overnight) ;)
