### ISSUE TITLE
FAILED: ResponseRendererSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#20602]
```
 with two chunks *** FAILED *** (155 milliseconds)
[info]     (HTTP/1.1 200 OK

[info]     Server: akka-http/1.0.0

[info]     Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]     Connection: close

[info]     Content-Type: application/json

[info]     
[info]     abcdefg,false) did not equal (HTTP/1.1 200 OK

[info]     Server: akka-http/1.0.0

[info]     Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]     Connection: close

[info]     Content-Type: application/json

[info]     
[info]     abcdefg,true) (ResponseRendererSpec.scala:365)
[info]     org.scalatest.exceptions.TestFailedException:
[info]     at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[info]     at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[info]     at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[info]     at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$mcV$sp$30$$anon$24.<init>(ResponseRendererSpec.scala:365)
[info]     at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$mcV$sp$30.apply$mcV$sp(ResponseRendererSpec.scala:361)
[info]     at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$mcV$sp$30.apply(ResponseRendererSpec.scala:361)
[info]     at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$29$$anonfun$apply$mcV$sp$30.apply(ResponseRendererSpec.scala:361)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
...
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/358/consoleFull

**Comment by ktoso** [comment]
@sirthias @jrudolph I'm digging into the `ResponseRendererSpec` and am somewhat iffy about the 

```scala
// we try to find out if the renderer has already flagged completion even without the upstream being completed
        val wasCompleted =
          try {
            Await.ready(wasCompletedFuture, 500.millis) // lower timing becomes (sometimes) unstable on slow jenkins
            true
          } catch {
            case NonFatal(_) ⇒ false
          }
```

part of the assertion... Seems to be inherently racy. Do you think we can drop this check or shouldn't?
For requests which `Connection: close` we could check that it closes but not for the other ones, WDYT?
