### ISSUE TITLE
FAILED: StreamLayoutSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20627]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6317/consoleFull

```
o]   - when starting from a Source *** FAILED *** (10 seconds, 193 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Queried 36 times, sleeping 15 milliseconds between each query. (StreamLayoutSpec.scala:134)
[info]     org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:546)
[info]     at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:558)
[info]     at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:74)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply$mcV$sp(StreamLayoutSpec.scala:134)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StreamLayoutSpec.scala:128)
[info]     at akka.stream.impl.StreamLayoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$5.apply(StreamLayoutSpec.scala:128)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]     at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]     at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]     at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]     at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]     at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]     at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]     at scala.collection.immutable.List.foreach(List.scala:381)
[info]     at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]     at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]     at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]     at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]     at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:57)
[info]     at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]     at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:57)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]     at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]     at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]     at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:57)
[info]     at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]     at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]     at akka.testkit.AkkaSpec.run(AkkaSpec.scala:57)
[info]     at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(F
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6357/consoleFull

Different test case though

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6359/consoleFull

**Comment by drewhk** [comment]
These tests take sometimes 5-6 seconds and usually cause heavy GC activity. This might be a spurious timeout, especially since the other two successful test cases skirt the timeout, too:

```
[info]   - when starting from a Flow (8 seconds, 530 milliseconds)
[info]   - when using .via (10 seconds, 422 milliseconds)
```
