### ISSUE TITLE
failed: TickSourceSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20638]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6329/consoleText

```
[info] - must be possible to cancel *** FAILED *** (1 second, 853 milliseconds)
[info]   java.lang.AssertionError: assertion failed: received unexpected message OnNext(tick)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:577)
[info]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:573)
[info]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:734)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMsg(StreamTestKit.scala:516)
[info]   at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$11.apply(TickSourceSpec.scala:94)
[info]   at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$11.apply(TickSourceSpec.scala:86)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(TickSourceSpec.scala:86)
[info]   at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(TickSourceSpec.scala:86)
[info]   at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(TickSourceSpec.scala:86)
```

**Comment by drewhk** [comment]
There is very unlikely to be a bug here. What I think is that due to some JVM jitter/GC two pushed ticks happen to "lump" together and arrive immediately one after the other, while the test expects 200.millis between them.
