### ISSUE TITLE
HttpServerBluePrint: Cannot push port (requestPrepOut) twice

### ISSUE THREAD

**Issue by kstokoz** [akka/akka#20642]
as per https://groups.google.com/forum/#!topic/akka-user/0piK_xiq4Qg

During run of my application which is using akka-streams & akka-http of v.2.4.6 sometimes i see following error in the logs:
```
Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@42104288]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:435)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:393)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
```

**Comment by drewhk** [comment]
Do you have a reproducer maybe?

**Comment by kstokoz** [comment]
Unfortunately i don`t have anything, i can try to find anything special in out logs which could be related to this issue.

**Comment by kstokoz** [comment]
Prior this stacktrace i also sometimes see warning, not sure it is related, but maybe it will help you somehow:

```
[2016-05-27 02:54:58.814 +0000] WARN  - Sending 2xx response before end of request was received...
Note that the connection will be closed after this response. Also, many clients will not read early responses!
Consider waiting for the request end before dispatching this response!
[2016-05-27 02:54:58.817 +0000] ERROR - Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@42104288]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
        at scala.Predef$.require(Predef.scala:224)
        at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:435)
        at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:393)
        at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2016-05-27 02:54:58.819 +0000] ERROR - Outgoing response stream error
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
        at scala.Predef$.require(Predef.scala:224)
        at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:435)
        at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:393)
        at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

**Comment by abrighton** [comment]
I am seeing the same error since upgrading to akka*-2.4.7. The errors only occurs when the HTTP server returns a 404 Not Found error . In that case, the client throws an Exception inside a future, in case that makes a difference. This is the error message:

```
20:53:11.123 [ConfigServiceHttpServer-akka.actor.default-dispatcher-16] ERROR akka.actor.RepointableActorRef - Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@77fabea0]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224) ~[scala-library-2.11.8.jar:na]
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:436) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:395) ~[akka-http-core_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
20:53:11.124 [ConfigServiceHttpServerTests-akka.actor.default-dispatcher-4] ERROR ConfigServiceHttpClient - HTTP response code for /create?path=some/test1/TestConfig1&oversize=false&comment=update+1+comment: 404 Not Found
```

I don't have a trivial example for this, but the sources and test case causing the error are on GitHub.

**Comment by ktoso** [comment]
> I don't have a trivial example for this, but the sources and test case causing the error are on GitHub.

Thanks for reporting. Where specifically though?

**Comment by abrighton** [comment]
In this test: https://github.com/tmtsoftware/csw/blob/config3/cs/src/test/scala/csw/services/cs/akka/ConfigServiceHttpServerTests.scala

**Comment by Joe-Edwards** [comment]
I've seen this occasionally in my logs as well, I think I've identified the culrit - around https://github.com/akka/akka/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala#L429

```
// when the client closes the connection, we need to pull onc more time to get the
// request parser to complete
if (close && isEarlyResponse) pull(requestParsingIn)
```

If this is called while requestPrepOut is pushed, it will cause requestParsingIn to be pulled without requestPrepOut being available - producing the titular error when an element arrives.

Thus, if we exhaust all demand from the request preparation (I don't know if you can do this reliably with a real server - I expect it's a race-condition) and then send an early response it'll fail.

I made a stage-level repro: https://gist.github.com/Joe-Edwards/502aabd3eaddfe7ec06275988c542ad5

Which fails with

```
java.lang.AssertionError: assertion failed: received unexpected message OnError(java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:435)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:393)
...
```

**Comment by drewhk** [comment]
Great, @Joe-Edwards thank you for hunting this down. @ktoso is fuzzing enabled on the HTTP project already?

**Comment by ktoso** [comment]
Thanks a lot for hunting this down Joe!
@drewhk Yes, fuzzing is enabled in http tests.

**Comment by drewhk** [comment]
I find it weird then why it does not expose this issue. It is pretty aggressive.

**Comment by Voltir** [comment]
I have encountered a very similar error:

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (Scan.in)
2546 [api-lookup-akka.actor.default-dispatcher-8] ERROR akka.actor.RepointableActorRef - Error in stage [Scan]: requirement failed: Cannot pull closed port (Scan.in) 
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (Scan.in)
	at scala.Predef$.require(Predef.scala:224) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:347) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.Scan$$anon$10.onPull(Ops.scala:322) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:608) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:415) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
```
Mine comes from aws-commons which provides am akka-stream wrapper around the java aws sdk. I was updating code from akka-streams 1.0 to 2.4.7 when I encountered this particular problem. If I can get time, Ill see if I can make a smaller reproducer that hopefully doesn't touch aws at all...

**Comment by ktoso** [comment]
Thanks for reporting, we have a reproducer here: https://github.com/wsargent/reproduce-akka-20642
Uses play but exposes that problem.

**Comment by Voltir** [comment]
My error is a bit different "Cannot Pull" vs "Cannot Push" and I don't think my variant is akka-http related. Do you think it would be worth trying to create a reproducer for my variant, or is it likely that it is infact the same problem?

**Comment by ktoso** [comment]
Oh, sorry I mistook that. Yes, reproducer would be very helpful!

**Comment by Voltir** [comment]
I don't know if its helpful, but I was able to roll back my version of akka to 1.0 and test the equivalent code and I get, well, this:
```
17874 [api-lookup-akka.actor.default-dispatcher-18] INFO  akka.actor.RepointableActorRef - Message [scala.Tuple2] from Actor[akka://api-lookup/user/$a/flow-23-3-singleSource-stageFactory-stageFactory-Zip-actorPublisherSource-actorPublisherSource-actorPublisherSource#947018527] to Actor[akka://api-lookup/user/$a/flow-23-3-singleSource-stageFactory-stageFactory-Zip-actorPublisherSource-actorPublisherSource-actorPublisherSource#947018527] was not delivered. [3] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

I should mention that this problem appears to be nondeterministic - about 40% of the time both the akka 2.4.7 version and the akka 1.0 version display these "equivalent" errors.

**Comment by ktoso** [comment]
1.0 is rather ancient, I'd not spent time on trying it out. 
If you could help out on diving into the existing code base that would be very very helpful.

**Comment by ktoso** [comment]
The `Cannot push port (requestPrepOut` is duplicated in https://github.com/akka/akka/issues/20789 and I worked on and has a PR now: https://github.com/akka/akka/pull/20841

**Comment by ktoso** [comment]
Thanks for the test @Joe-Edwards, I found it did not reproduce the exact problem that Play usage for example exposed, but it's good to keep the test in any case, I'll include it in my PR (with attribution to yourself of course). Thanks.

**Comment by Joe-Edwards** [comment]
No problem, glad I could help :smiley:

**Comment by mingchuno** [comment]
FYI, I encounter similar issue using akka version `2.4.7`
```
2016-07-19 10:35:56:882 ERROR [a.a.RepointableActorRef] [akka 10:35:56.877UTC] Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@6c65b645]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:436) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:395) ~[com.typesafe.akka.akka-http-core_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:424) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530) ~[com.typesafe.akka.akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [com.typesafe.akka.akka-actor_2.11-2.4.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.8.jar:na]
```

**Comment by JamiePullar** [comment]
I have also encounter the same issue in 2.4.8
In my case if I make the request repeatedly, sometimes it will succeed, other times fail.

My error occurs during the Processing of the post request:

`Error during processing of request HttpRequest(HttpMethod(POST),http://{url}:8185/saml-callback/test.co.uk,List(Cache-Control: max-age=0, Connection: Keep-Alive, Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8, Accept-Encoding: gzip, deflate, br, Accept-Language: en-US, en;q=0.8, Cookie: _ga=GA1.3.1579988329.1462450582; XAuthToken=AaRMEQb5PfVHMNWepFoerQ; cookiesEnabled=check; XTabToken=D2BC7E97-0FBD-31AB-B0DE-50BEA8391AEA; XSSOToken=qZdjt4bXTaqhlY1BIyt1Yw, Host: {url}:8185, Max-Forwards: 10, Referer: https://adfs.test.co.uk/adfs/ls/wia?ssoCookie=e28c105a-e28d-4bb9-91a4-f518997a11a9, User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, Origin: https://adfs.test.co.uk, upgrade-insecure-requests: 1, X-Original-URL: /saml-callback/test.co.uk, x-forwarded-for: 127.0.0.1:57912, X-ARR-SSL: 2048|256|CN=CDES-P210.test.com|CN=CDES-P210.test.com, X-ARR-LOG-ID: d5ef0984-8c13-4163-b8c5-96404b864904, Timeout-Access: <function1>),HttpEntity.Default(application/x-www-form-urlencoded; charset=UTF-8,8201,Source(SourceShape(StreamUtils$$anon$2.out), CompositeModule [5aa6a51f]`

`Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@7437577e]: requirement failed: Cannot push port (requestPrepOut) twice`

**Comment by JamiePullar** [comment]
I have also encounter the same issue in 2.4.8 and 2.4.9 RC-1
In my case if I make the request repeatedly, sometimes it will succeed, other times fail.

My error occurs during the Processing of the post request:

`Error during processing of request HttpRequest(HttpMethod(POST),http://{url}:8185/saml-callback/test.co.uk,List(Cache-Control: max-age=0, Connection: Keep-Alive, Accept: text/html, application/xhtml+xml, application/xml;q=0.9, image/webp, */*;q=0.8, Accept-Encoding: gzip, deflate, br, Accept-Language: en-US, en;q=0.8, Cookie: _ga=GA1.3.1579988329.1462450582; XAuthToken=AaRMEQb5PfVHMNWepFoerQ; cookiesEnabled=check; XTabToken=D2BC7E97-0FBD-31AB-B0DE-50BEA8391AEA; XSSOToken=qZdjt4bXTaqhlY1BIyt1Yw, Host: {url}:8185, Max-Forwards: 10, Referer: https://adfs.test.co.uk/adfs/ls/wia?ssoCookie=e28c105a-e28d-4bb9-91a4-f518997a11a9, User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, Origin: https://adfs.test.co.uk, upgrade-insecure-requests: 1, X-Original-URL: /saml-callback/test.co.uk, x-forwarded-for: 127.0.0.1:57912, X-ARR-SSL: 2048|256|CN=CDES-P210.test.com|CN=CDES-P210.test.com, X-ARR-LOG-ID: d5ef0984-8c13-4163-b8c5-96404b864904, Timeout-Access: <function1>),HttpEntity.Default(application/x-www-form-urlencoded; charset=UTF-8,8201,Source(SourceShape(StreamUtils$$anon$2.out), CompositeModule [5aa6a51f]`


`Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@7437577e]: requirement failed: Cannot push port (requestPrepOut) twice`

The body looks like (ellipses represent more binary data)

`SAMLResponse=PHNhbWxwOlJlc3BvbnNlIElEP ... yF2B&RelayState=4cYu8pQARgOanw3dLP9Rag`

**Comment by jypma** [comment]
@ktoso I'm able to reliably trigger this error (`requirement failed: Cannot push port (requestPrepOut) twice`) on akka 2.4.11 by consuming a (big) streaming request, failing the stream halfway, having that exception bubble up into an exception handler, and completing the response with 503 in the exception handler.

 I'll see if I can write a minimal reproducer, and then reopen on `akka-http` repo.

**Comment by jypma** [comment]
Hm. Skip the "reliably" part in my previous message. Error seems to have gone away for now. I'll keep you posted if it shows again.
