### ISSUE TITLE
FAILED ReactiveStreamsDocSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20663]
docs.stream.ReactiveStreamsDocSpec
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6355/consoleFull

```
[info] - source as fanoutPublisher *** FAILED *** (6 seconds, 175 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnSubscribe
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:434)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:407)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:734)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectSubscription(StreamTestKit.scala:225)
[info]   at docs.stream.ReactiveStreamsDocSpec.assertResult(ReactiveStreamsDocSpec.scala:54)
[info]   at docs.stream.ReactiveStreamsDocSpec$$anonfun$4.apply$mcV$sp(ReactiveStreamsDocSpec.scala:120)
[info]   at docs.stream.ReactiveStreamsDocSpec$$anonfun$4.apply(ReactiveStreamsDocSpec.scala:105)
[info]   at docs.stream.ReactiveStreamsDocSpec$$anonfun$4.apply(ReactiveStreamsDocSpec.scala:105)
```

**Comment by drewhk** [comment]
This might be a bug actually, otherwise I can't imagine the above to happen. Instead of trying to figure out what goes wrong here, I would probably prefer to get rid of this old class and its ancient friends in favor if this approach: https://github.com/akka/akka/issues/21261

While the BroadcastHub approach might carry its own bugs, at least it will reuse well tested parts where only the Broadcast logic needs likely more hardening.

**Comment by drewhk** [comment]
Have not happened since. I close it now.
