### ISSUE TITLE
failed: OutputStreamSourceSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20676]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6382/consoleText

```
[info] - must not leave blocked threads when materializer shutdown *** FAILED *** (3 seconds, 587 milliseconds)
[info]   Array("OutputStreamSourceSpec-akka.stream.default-blocking-io-dispatcher-26" Id=5923 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2729b372
[info]   	at sun.misc.Unsafe.park(Native Method)
[info]   	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2729b372
[info]   	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[info]   	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[info]   	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
[info]   	at akka.stream.impl.io.OutputStreamSourceStage$$anon$1$$anon$2$$anonfun$onPull$1.apply(OutputStreamSourceStage.scala:134)
[info]   	at akka.stream.impl.io.OutputStreamSourceStage$$anon$1$$anon$2$$anonfun$onPull$1.apply(OutputStreamSourceStage.scala:130)
[info]   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[info]   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[info]   	...
[info]   
[info]   	Number of locked synchronizers = 1
[info]   	- java.util.concurrent.ThreadPoolExecutor$Worker@1cb29858
[info]   
[info]   , "OutputStreamSourceSpec-akka.stream.default-blocking-io-dispatcher-25" Id=5922 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at sun.misc.Unsafe.park(Native Method)
[info]   	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[info]   	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
[info]   	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
[info]   	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
[info]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   	at java.lang.Thread.run(Thread.java:745)
[info]   
[info]   , "OutputStreamSourceSpec-akka.stream.default-blocking-io-dispatcher-24" Id=5921 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at sun.misc.Unsafe.park(Native Method)
[info]   	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[info]   	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
[info]   	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
[info]   	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
[info]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   	at java.lang.Thread.run(Thread.java:745)
[info]   
[info]   , "OutputStreamSourceSpec-akka.stream.default-blocking-io-dispatcher-23" Id=5920 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at sun.misc.Unsafe.park(Native Method)
[info]   	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@42199ea
[info]   	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[info]   	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
[info]   	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
[info]   	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
[info]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
[info]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   	at java.lang.Thread.run(Thread.java:745)
[info]   
[info]   ) did not equal List() (OutputStreamSourceSpec.scala:51)
[info]
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1559/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3374/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1560/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3871/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3375/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/3376/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3872/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3873/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/370/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1561/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1562/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1563/consoleFull
