### ISSUE TITLE
FAILED: FileSinkSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20726]
https://jenkins.akka.io:8498/job/akka-nightly/3387/consoleFull

```
[info] - must write lines to a file *** FAILED *** (3 seconds, 592 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$13.apply(FileSinkSpec.scala:47)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$13.apply(FileSinkSpec.scala:43)
[info]   at akka.stream.io.FileSinkSpec.akka$stream$io$FileSinkSpec$$targetFile(FileSinkSpec.scala:142)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(FileSinkSpec.scala:43)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FileSinkSpec.scala:43)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(FileSinkSpec.scala:43)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FileSinkSpec.scala:42)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileSinkSpec.scala:42)
[info]   at akka.stream.io.FileSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FileSinkSpec.scala:42)
```

**Comment by johanandren** [comment]
Test case looks alright, stage is simple enough and looks alright. Bad luck with really slow FS?

**Comment by ktoso** [comment]
Yeah touching FS sometimes goes into crazy-snail mode :(
We could use jimfs in tests https://github.com/google/jimfs

**Comment by ktoso** [comment]
Would be a very good thing to do actually hm

**Comment by johanandren** [comment]
Ah, good idea, like I did in streams-contrib last week. I'll look into it.
