### ISSUE TITLE
FAILED: AbstractPersistentFSMTest

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20725]
https://jenkins.akka.io:8498/job/akka-nightly/3387/consoleFull

```
[info] - fsmTimeoutTest *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (2899896539 nanoseconds) during expectMsg: Terminated Actor[akka://PersistentFSMJavaTest/user/$e#67247364]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:368)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:737)
[info]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:380)
[info]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:737)
[info]   at akka.testkit.JavaTestKit.expectTerminated(JavaTestKit.java:491)
[info]   at akka.testkit.JavaTestKit.expectTerminated(JavaTestKit.java:500)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$2$2.run(AbstractPersistentFSMTest.java:140)
[info]   at akka.testkit.JavaTestKit$Within$2.apply(JavaTestKit.java:241)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:308)
[info]   at akka.testkit.TestKit.within(TestKit.scala:737)
[info]   at akka.testkit.JavaTestKit$Within.<init>(JavaTestKit.java:239)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$2$2.<init>(AbstractPersistentFSMTest.java:137)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$2.<init>(AbstractPersistentFSMTest.java:137)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest.fsmTimeoutTest(AbstractPersistentFSMTest.java:112)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at 
```

**Comment by 2m** [comment]
Aug 24, 2016 9:17:00 PM https://jenkins.akka.io:8498/job/akka-nightly/3625/consoleFull

```
[info] - testCorrectStateTimeoutFollowingRecovery *** FAILED ***
Coroner Thread Count starts at 14 in akka.persistence.OptionalSnapshotStoreSpec
[WARN] [08/24/2016 21:35:05.110] [PersistenceSpec-akka.actor.default-dispatcher-5] [akka.persistence.Persistence(akka://PersistenceSpec)] No default snapshot store configured! To configure a default snapshot-store plugin set the `akka.persistence.snapshot-store.plugin` key. For details see 'reference.conf'
Coroner Thread Count started at 14, ended at 9, peaked at 21 in akka.persistence.OptionalSnapshotStoreSpec
[info]   java.lang.AssertionError: assertion failed: timeout (1899963339 nanoseconds) during expectMsgClass waiting for class akka.persistence.fsm.PersistentFSM$Transition
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:422)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:737)
[info]   at akka.testkit.JavaTestKit.expectMsgClass(JavaTestKit.java:397)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6$1.run(AbstractPersistentFSMTest.java:318)
[info]   at akka.testkit.JavaTestKit$Within$2.apply(JavaTestKit.java:241)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:308)
[info]   at akka.testkit.TestKit.within(TestKit.scala:737)
[info]   at akka.testkit.JavaTestKit$Within.<init>(JavaTestKit.java:239)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6$1.<init>(AbstractPersistentFSMTest.java:315)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6.<init>(AbstractPersistentFSMTest.java:315)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest.testCorrectStateTimeoutFollowingRecovery(AbstractPersistentFSMTest.java:286)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

**Comment by jrudolph** [comment]
Oct 16, 2016 during nightly https://jenkins.akka.io:8498/job/akka-nightly/3785/consoleFull

```
[info] - testCorrectStateTimeoutFollowingRecovery *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (1899942455 nanoseconds) during expectMsgClass waiting for class akka.persistence.fsm.PersistentFSM$Transition
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass(TestKit.scala:459)
[info]   at akka.testkit.TestKit.expectMsgClass(TestKit.scala:814)
[info]   at akka.testkit.JavaTestKit.expectMsgClass(JavaTestKit.java:400)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6$1.run(AbstractPersistentFSMTest.java:318)
[info]   at akka.testkit.JavaTestKit$Within$2.apply(JavaTestKit.java:244)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
[info]   at akka.testkit.TestKit.within(TestKit.scala:814)
[info]   at akka.testkit.JavaTestKit$Within.<init>(JavaTestKit.java:242)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6$1.<init>(AbstractPersistentFSMTest.java:315)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$6.<init>(AbstractPersistentFSMTest.java:315)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest.testCorrectStateTimeoutFollowingRecovery(AbstractPersistentFSMTest.java:286)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
[info]   at org.scalatest.junit.JUnitSuiteLike$class.run(JUnitSuiteLike.scala:242)
[info]   at org.scalatest.junit.JUnitSuite.run(JUnitSuite.scala:71)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrudolph** [comment]
Another instance tonight: https://jenkins.akka.io:8498/job/akka-nightly/3792/consoleFull
