### ISSUE TITLE
FAILED: PersistentActorRecoveryTimeoutSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#20728]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/373/consoleFull

```
[info] - should fail recovery if timeout is not met when recovering *** FAILED *** (3 seconds, 144 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.persistence.journal.SteppingInmemJournal$.step(SteppingInmemJournal.scala:30)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(PersistentActorRecoveryTimeoutSpec.scala:51)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(PersistentActorRecoveryTimeoutSpec.scala:43)
[info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(PersistentActorRecoveryTimeoutSpec.scala:43)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
```

**Comment by drewhk** [comment]
@johanandren I think this is your recent fix

**Comment by drewhk** [comment]
I mean the test introduced by your recent fix

**Comment by johanandren** [comment]
Yup. Do'h!

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/376/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3587/consoleFull

**Comment by johanandren** [comment]
This is weird. The first message sent to the persistent actor goes to dead letter, and then the expected interaction with the `SteppingInmemJournal` times out. The only reason for the actor start to fail I could think of is that replay failed, but the journal should be empty and the bound to the actor system lifecycle, so should not be possible that it leaks between tests.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3654/consoleFull

**Comment by johanandren** [comment]
Meh, the increased logging didn't help at all as far as I can see.

**Comment by johanandren** [comment]
Aha! Figured it out. Recovery time out of 100ms in config is too tight and trips sometimes.
