### ISSUE TITLE
GroupBy Graph Stage, tries to pull twice in certain condition

### ISSUE THREAD

**Issue by yoks** [akka/akka#20829]
I'm encountered problem with GroupBy graph stage in very specific env.

I have following flow configured:
```
 Flow[ShardMessage].groupBy(Int.MaxValue, f => f.userId).to(actorGroupFlow) //userId - Int value

val actorGroupFlow = GraphDSL.create() { implicit builder =>
  val fanOut = builder.add(Broadcast[ShardMessage](1))

  fanOut ~> Sink.ignore
  SinkShape(fanOut.in)
}
```

And i receive following exception.
```
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (GroupBy.in) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:348)
	at akka.stream.stage.GraphStageLogic.tryPull(GraphStage.scala:358)
	at akka.stream.impl.fusing.GroupBy$$anon$1.onPull(StreamOfStreams.scala:272)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:608)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:415)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

It only reproduce itself on the very specific HW/SW configuration:
```
CentOS Linux release 7.2.1511 (Core)
java version "1.8.0_92"
```

Machine itself is 32 physical core Hardware server. I cannot reproduce following exception on my local dev or VM machines (much slower machines).

Any attempt to create async boundary around it did not yield any results.

**Comment by ktoso** [comment]
Thanks for reporting!

**Comment by yoks** [comment]
From initial investigation, it looks like substream pulls port here:
` else if (needToPull) pull(in) // 365`

And then this call fail:
`else tryPull(in) // 272`

But i cannot 100% reproduce it.

**Comment by drewhk** [comment]
Looking into it now

**Comment by drewhk** [comment]
Likely a race given how hard it is to reproduce. I will try with fuzzing-mode.

**Comment by drewhk** [comment]
Ok, I can reproduce it now
