### ISSUE TITLE
Scan.in cannot pull closed port

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20843]
Reported by @Voltir in #20642, though it's a separate issue so opening here:

See this comment https://github.com/akka/akka/issues/20642#issuecomment-227596118

-----------

I have encountered a very similar error:

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (Scan.in)
2546 [api-lookup-akka.actor.default-dispatcher-8] ERROR akka.actor.RepointableActorRef - Error in stage [Scan]: requirement failed: Cannot pull closed port (Scan.in) 
java.lang.IllegalArgumentException: requirement failed: Cannot pull closed port (Scan.in)
	at scala.Predef$.require(Predef.scala:224) ~[scala-library-2.11.8.jar:1.0.0-M1]
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:347) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.Scan$$anon$10.onPull(Ops.scala:322) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:608) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:415) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.7.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530) ~[akka-stream_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.7.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.7.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
```
Mine comes from aws-commons which provides am akka-stream wrapper around the java aws sdk. I was updating code from akka-streams 1.0 to 2.4.7 when I encountered this particular problem. If I can get time, Ill see if I can make a smaller reproducer that hopefully doesn't touch aws at all...

**Comment by drewhk** [comment]
Taking it, unless you want to fix it?

**Comment by ktoso** [comment]
Cool, take it. I'll work on some http timeout problems

**Comment by shuttie** [comment]
Got exactly the same problem while updating akka dependency in my project from 2.4.4 to 2.4.5, so the regression happened somewhere in between these versions.

**Comment by drewhk** [comment]
I put this back to the pool as I had no time to get to this ticket.

**Comment by ktoso** [comment]
Thanks a lot @agolubev !
