### ISSUE TITLE
FAILED: FramingSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20887]
Likely a timing issue, GC hit before the test

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/402/consoleFull

```
[info] FramingSpec:
Coroner Thread Count starts at 53 in akka.stream.scaladsl.FramingSpec
[info] Delimiter bytes based framing
2860.080: [GC pause (G1 Evacuation Pause) (young), 3.6822771 secs]
   [Parallel Time: 3662.1 ms, GC Workers: 33]
      [GC Worker Start (ms): Min: 2860080.9, Avg: 2860081.4, Max: 2860081.9, Diff: 0.9]
      [Ext Root Scanning (ms): Min: 0.0, Avg: 5.7, Max: 18.3, Diff: 18.3, Sum: 187.1]
      [Update RS (ms): Min: 0.0, Avg: 3.5, Max: 17.3, Diff: 17.3, Sum: 114.4]
         [Processed Buffers: Min: 0, Avg: 4.1, Max: 17, Diff: 17, Sum: 135]
      [Scan RS (ms): Min: 0.0, Avg: 1.2, Max: 20.4, Diff: 20.4, Sum: 40.5]
      [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.2]
      [Object Copy (ms): Min: 2104.0, Avg: 2141.1, Max: 2190.3, Diff: 86.3, Sum: 70656.1]
      [Termination (ms): Min: 1462.1, Avg: 1507.2, Max: 1539.9, Diff: 77.7, Sum: 49737.4]
      [GC Worker Other (ms): Min: 0.3, Avg: 1.5, Max: 13.8, Diff: 13.5, Sum: 50.9]
      [GC Worker Total (ms): Min: 3659.4, Avg: 3660.2, Max: 3661.1, Diff: 1.6, Sum: 120786.6]
      [GC Worker End (ms): Min: 2863741.3, Avg: 2863741.6, Max: 2863742.1, Diff: 0.8]
   [Code Root Fixup: 0.2 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 9.7 ms]
   [Other: 10.2 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 3.1 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 1.8 ms]
      [Humongous Reclaim: 1.5 ms]
      [Free CSet: 1.3 ms]
   [Eden: 133.0M(133.0M)->0.0B(133.0M) Survivors: 20.0M->20.0M Heap: 1440.5M(3072.0M)->1318.1M(3072.0M)]
 [Times: user=120.01 sys=0.34, real=3.69 secs] 
[info] - must work with various delimiters and test sequences *** FAILED *** (4 seconds, 261 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$18$$anonfun$apply$1.apply$mcVI$sp(FramingSpec.scala:82)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$18.apply(FramingSpec.scala:74)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$18.apply(FramingSpec.scala:74)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(FramingSpec.scala:74)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FramingSpec.scala:74)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FramingSpec.scala:74)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:57)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:57)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:57)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by drewhk** [comment]
Another one, and again after some GC. It should be investigated what causes these GC peaks there, might be a mistake in the test that generates more garbage than necessary?

https://jenkins.akka.io:8498/job/akka-nightly/3592/consoleFull

**Comment by ktoso** [comment]
Still got it last night: 

```
--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must work with various byte orders, frame lengths and offsets *** FAILED *** (6 seconds, 282 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$4.apply(FramingSpec.scala:182)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$4.apply(FramingSpec.scala:174)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply$mcVI$sp(FramingSpec.scala:174)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply(FramingSpec.scala:173)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply(FramingSpec.scala:173)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3.apply(FramingSpec.scala:173)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3.apply(FramingSpec.scala:172)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)

```

Unless I'm reading the dates wrong? This should have included the fix right? `2016-08-24 03:17`

**Comment by drewhk** [comment]
I have no clue. But please don't reopen but open a new FAILED ticket.

**Comment by ktoso** [comment]
Okey, let's open a new one it it comes back once more then.
