### ISSUE TITLE
FAILED: ClusterSingletonManagerSpec likely timing issue

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20886]
https://jenkins.akka.io:8498/job/akka-nightly/3472/consoleFull

```
[JVM-7] - must hand over when oldest leaves in 6 nodes cluster 
[JVM-1] [INFO] [07/03/2016 04:57:44.750] [ScalaTest-main-running-ClusterSingletonManagerMultiJvmNode1] [ClusterSingletonManagerMultiJvmNode1(akka://ClusterSingletonManagerSpec)] Shutdown [akka.tcp://ClusterSingletonManagerSpec@localhost:47283]
[JVM-5] [INFO] [07/03/2016 04:57:47.508] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:43206] - Marking exiting node(s) as UNREACHABLE [Member(address = akka.tcp://ClusterSingletonManagerSpec@localhost:58806, status = Exiting)]. This is expected and they will be removed.
[JVM-2] [INFO] [07/03/2016 04:57:47.523] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:38952] - Marking exiting node(s) as UNREACHABLE [Member(address = akka.tcp://ClusterSingletonManagerSpec@localhost:58806, status = Exiting)]. This is expected and they will be removed.
[JVM-7] [INFO] [07/03/2016 04:57:47.541] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:35686] - Marking exiting node(s) as UNREACHABLE [Member(address = akka.tcp://ClusterSingletonManagerSpec@localhost:58806, status = Exiting)]. This is expected and they will be removed.
[JVM-6] [INFO] [07/03/2016 04:57:48.542] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-16] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:42693] - Marking exiting node(s) as UNREACHABLE [Member(address = akka.tcp://ClusterSingletonManagerSpec@localhost:58806, status = Exiting)]. This is expected and they will be removed.
[JVM-7] [INFO] [07/03/2016 04:57:48.541] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:35686] - Leader is auto-downing unreachable node [akka.tcp://ClusterSingletonManagerSpec@localhost:47283]
[JVM-7] [INFO] [07/03/2016 04:57:48.543] [ClusterSingletonManagerSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterSingletonManagerSpec)] Cluster Node [akka.tcp://ClusterSingletonManagerSpec@localhost:35686] - Marking unreachable node [akka.tcp://ClusterSingletonManagerSpec@localhost:47283] as [Down]
[JVM-1] [INFO] [07/03/2016 04:57:49.785] [ScalaTest-main-running-ClusterSingletonManagerMultiJvmNode1] [ClusterSingletonManagerMultiJvmNode1(akka://ClusterSingletonManagerSpec)] Shutdown [akka.tcp://ClusterSingletonManagerSpec@localhost:43206]
[JVM-1] - must take over when oldest crashes in 5 nodes cluster *** FAILED ***
[JVM-1]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ClusterSingletonManagerSpec/user/controller#-396088125]] after [5000 ms]. Sender[null] sent message of type "akka.remote.testconductor.Terminate".
[JVM-1]   at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
[JVM-1]   at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
[JVM-1]   at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
[JVM-1]   at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
[JVM-1]   at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
[JVM-1]   at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
[JVM-1]   at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
[JVM-1]   at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
[JVM-1]   at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
[JVM-1]   at java.lang.Thread.run(Thread.java:745)
[JVM-1]   ...
```

**Comment by patriknw** [comment]
Looks like the `testConductor.exit` wasn't successful (timeout). I don't think I have seen that before so closing.
