### ISSUE TITLE
Attempted decompression of unknown id

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20880]
Sometimes, the `MaxThroughputSpec`, fails with this exception in the beginning of running it. It's the class manifests. Some race condition that needs fixing.

```
[JVM-2] [ERROR] [07/05/2016 10:44:09.458] [MaxThroughputSpec-akka.remote.default-remote-dispatcher-7] [akka.remote.artery.ArteryTransport(akka://MaxThroughputSpec)] Inbound message stream failed. Restarting it. Attempted decompression of unknown id: [0]! Only 0 ids allocated in table version [0].
[JVM-2] java.lang.IllegalArgumentException: Attempted decompression of unknown id: [0]! Only 0 ids allocated in table version [0].
[JVM-2] 	at akka.remote.artery.compress.DecompressionTable.get(DecompressionTable.scala:14)
[JVM-2] 	at akka.remote.artery.compress.InboundCompression.decompress(InboundCompressions.scala:112)
[JVM-2] 	at akka.remote.artery.compress.InboundCompressionsImpl.decompressClassManifest(ActualCompressions.scala:81)
[JVM-2] 	at akka.remote.artery.HeaderBuilderImpl.manifest(BufferPool.scala:219)
[JVM-2] 	at akka.remote.artery.Decoder$$anon$1.onPush(Codecs.scala:205)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:472)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:418)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:604)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
[JVM-2] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:530)
[JVM-2] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-2] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-2] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-2] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-2] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
might have been fixed by updating the tables atomically, but we have other races in the Encoder also (see FIXME)

**Comment by patriknw** [comment]
It's real: https://jenkins.akka.io:8498/job/akka-artery-perf/229/consoleFull

**Comment by ktoso** [comment]
Pretty sure this is the table being swapped in the middle of a message
write. Documented race in current impl.

Had a poolside vision of how to best solve, basically optimistic insurgency
control during write (get version, write, get version, should have been the
same, of not, write using the new version)

**Comment by patriknw** [comment]
This will be solved via https://github.com/akka/akka/issues/21210
