### ISSUE TITLE
failed: StreamTestKitDocSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#20904]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/6715/

```
[info] - grouped part of infinite stream *** FAILED *** (206 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at docs.stream.StreamTestKitDocSpec$$anonfun$4.apply$mcV$sp(StreamTestKitDocSpec.scala:38)
[info]   at docs.stream.StreamTestKitDocSpec$$anonfun$4.apply(StreamTestKitDocSpec.scala:30)
[info]   at docs.stream.StreamTestKitDocSpec$$anonfun$4.apply(StreamTestKitDocSpec.scala:30)
```

**Comment by patriknw** [comment]
100 millis, too short timeout?

**Comment by drewhk** [comment]
Yes, I think so.
