### ISSUE TITLE
FAILED: akka.stream.scaladsl.FlowRecoverWithSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#20933]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3987/consoleFull

**Comment by johanandren** [comment]
Another failure: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/3987/consoleFull

```
[info] - must terminate with exception after set number of retries *** FAILED *** (35 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(11), found OnError(akka.stream.scaladsl.FlowRecoverWithSpec$$anon$1: ex
[info] )
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:351)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:737)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:330)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:330)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:330)
[info]   at akka.stream.scaladsl.FlowRecoverWithSpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$19.apply(FlowRecoverWithSpec.scala:129)
[info]   at akka.stream.scaladsl.FlowRecoverWithSpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$mcV$sp$19.apply(FlowRecoverWithSpec.scala:131)
```

**Comment by drewhk** [comment]
Shouldn't new tickets be opened instead of old ones reopened for FAILED?

**Comment by drewhk** [comment]
Also, the linked failure is exactly the one I supposedly fixed (3987)

**Comment by patriknw** [comment]
@drewhk if the old closed issue was "released" then open new issue

**Comment by drewhk** [comment]
Since the other linked failure is the same as the previous I close this for now.

**Comment by johanandren** [comment]
Yeah, sorry not sure what happened that made me think it was new again in early oct.

**Comment by drewhk** [comment]
Maybe you wanted to link another failure? Anyway, since there is no *active* failure in this ticket I keep this closed until we see it again.

**Comment by johanandren** [comment]
Sounds good
