### ISSUE TITLE
akka-http singleRequest Error: 

### ISSUE THREAD

**Issue by ultimate1352** [akka/akka#20941]
Hello. I'm Lawrence. 
I'm using akka, akka-http in my apps.

Everything works fine. But I hava a problem with akka-http client side with SingleRequest API.
sometimes I send a lot of requests that expected to receive 400 error continuously.
Then, I meet below exception.

I trying to find a reason. But I could't do that for a days.

my code
```
class MyActor extends Actor with ActorLogging {

  import HttpClient._
  import system.dispatcher

  implicit val system: ActorSystem = context.system
  implicit val materializer: ActorMaterializer = ActorMaterializer(ActorMaterializerSettings(context.system))

  val http = Http(context.system)

  override def receive: Receive = {
    case HttpCall(request) =>
      val f: Future[HttpResponse] = http.singleRequest(request)

      val _sender: ActorRef = sender
      f.onComplete {
        case Success(response) =>
          _sender ! Response(request, response)
        case Failure(e) =>
          log.warning(s"Http Client {} request Fail caused by : {}", request.method, e)
          e.printStackTrace()
      }
  }
}
```

Here is my log and stack trace when I received exception.
```
[PoolSlot$SlotProcessor] Slot 0 disconnected after regular connection close
akka.http.impl.engine.client.PoolSlot$UnexpectedDisconnectException: Unexpected disconnect
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$5$$anonfun$6.apply(PoolSlot.scala:217)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$5$$anonfun$6.apply(PoolSlot.scala:217)
  at scala.Option.fold(Option.scala:158)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$5.apply(PoolSlot.scala:217)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$5.apply(PoolSlot.scala:215)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.Iterator$class.foreach(Iterator.scala:750)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor.handleDisconnect(PoolSlot.scala:221)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anonfun$running$1.applyOrElse(PoolSlot.scala:201)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorSubscriber$$super$aroundReceive(PoolSlot.scala:92)
  at akka.stream.actor.ActorSubscriber$class.aroundReceive(ActorSubscriber.scala:201)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor.akka$stream$actor$ActorPublisher$$super$aroundReceive(PoolSlot.scala:92)
  at akka.stream.actor.ActorPublisher$class.aroundReceive(ActorPublisher.scala:325)
  at akka.http.impl.engine.client.PoolSlot$SlotProcessor.aroundReceive(PoolSlot.scala:92)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[HttpClient] request Fail caused by : akka.http.impl.engine.client.PoolSlot$UnexpectedDisconnectException: Unexpected disconnect
```

Could anyone help me?
Thank you for read.

**Comment by johanandren** [comment]
This will happen when a server disconnects and the max number of times to reconnect has been reached. You could maybe get some more info by enabling debug logging.

As this is more of a question than a bug report I'm going to close it, if you disagree we can re-open it.

Please use the mailing list (http://blog.akka.io/) or the gitter channel (https://gitter.im/akka/akka) for questions and use the issue tracker for bugs and improvement requests, thanks!
