### ISSUE TITLE
FAILED: CircuitBreakerSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#20982]
Timeout was too tight (see the GC message):

```
[info] CircuitBreakerSpec:
2215.391: [GC concurrent-cleanup-end, 0.0001002 secs] <<<<<<<<
[info] - must increment failure count on callTimeout before call finishes *** FAILED *** (152 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 100 milliseconds expired: <<<<<<
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:239)
```

**Comment by ktoso** [comment]
My fixup didn't help, need to look again
