### ISSUE TITLE
Can't set the seed-nodes via system properties

### ISSUE THREAD

**Issue by oleksiys** [akka/akka#20993]
When I try to set the seed-nodes using system property like:
-Dakka.cluster.seed-nodes.0=akka.tcp://ClusterSystem@host1:2552

I get exception:

> play.api.UnexpectedException: Unexpected exception[ValidationFailed: akka-cluster.conf @ file:/.../akka-cluster.conf: 19: akka.cluster.seed-nodes: Wrong value type at 'akka.cluster.seed-nodes', expecting: object with keys [0] but got: list]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:170)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:126)
	at scala.Option.map(Option.scala:146)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:126)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:124)
	at scala.util.Success.flatMap(Try.scala:231)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:124)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.typesafe.config.ConfigException$ValidationFailed: akka-cluster.conf @ file:/.../akka-cluster.conf: 19: akka.cluster.seed-nodes: Wrong value type at 'akka.cluster.seed-nodes', expecting: object with keys [0] but got: list
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:990)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:161)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:522)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:126)
	at play.api.libs.concurrent.ActorSystemProvider$.start(Akka.scala:300)
	at play.api.libs.concurrent.ActorSystemProvider.get$lzycompute(Akka.scala:257)
	at play.api.libs.concurrent.ActorSystemProvider.get(Akka.scala:256)
	at play.api.BuiltInComponents$class.actorSystem(Application.scala:262)
	at play.api.BuiltInComponentsFromContext.actorSystem$lzycompute(ApplicationLoader.scala:100)
	at play.api.BuiltInComponentsFromContext.actorSystem(ApplicationLoader.scala:100)
	at boot.AppComponents.clusterSystem$lzycompute(AppLoader.scala:43)
	at boot.AppComponents.clusterSystem(AppLoader.scala:43)
	at boot.ClusterComponents$class.$init$(ClusterComponents.scala:18)
	at boot.AppComponents.<init>(AppLoader.scala:28)
	at boot.AppLoader.load(AppLoader.scala:23)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:158)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:155)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:155)
	... 14 common frames omitted

**Comment by johanandren** [comment]
The exception is about the config file and not the parameter as far as I can see. Please use the gitter channel or the mailing list for questions and keep the issue tracker for bugs and improvement tickets, thanks!
