### ISSUE TITLE
FAILED: akka.http.AkkaHttpServerLatencyMultiNodeSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21013]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4009/consoleFull

(but also many failures in other builds)

```
[JVM-2] akka.actor.ActorInitializationException: akka://MultiNodeSpecSpec/user/$a: failure while creating ActorCell
[JVM-2] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:174)
[JVM-2] 	at akka.actor.dungeon.Dispatch$class.initWithFailure(Dispatch.scala:90)
[JVM-2] 	at akka.actor.ActorCell.initWithFailure(ActorCell.scala:374)
[JVM-2] 	at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:97)
[JVM-2] 	at akka.actor.ActorCell.handleSupervise(ActorCell.scala:625)
[JVM-2] 	at akka.actor.ActorCell.supervise(ActorCell.scala:617)
[JVM-2] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:468)
[JVM-2] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
[JVM-2] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[JVM-2] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[JVM-2] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-2] Caused by: java.lang.AssertionError: assertion failed: Don't use anonymous actor classes, actor class for Actor[akka://MultiNodeSpecSpec/user/$a#1670666637] was [akka.actor.Actor]
[JVM-2] 	at scala.Predef$.assert(Predef.scala:170)
[JVM-2] 	at akka.stream.testkit.StreamTestDefaultMailbox.create(StreamTestDefaultMailbox.scala:26)
[JVM-2] 	at akka.dispatch.Dispatcher$$anon$1.<init>(Dispatcher.scala:89)
[JVM-2] 	at akka.dispatch.Dispatcher.createMailbox(Dispatcher.scala:89)
[JVM-2] 	at akka.actor.dungeon.Dispatch$class.init(Dispatch.scala:49)
[JVM-2] 	at akka.actor.ActorCell.init(ActorCell.scala:374)
[JVM-2] 	at akka.actor.RepointableActorRef.newCell(RepointableActorRef.scala:119)
[JVM-2] 	at akka.actor.RepointableActorRef.point(RepointableActorRef.scala:93)
[JVM-2] 	... 11 more
[JVM-2] 

...

[JVM-2] *** RUN ABORTED *** (20 minutes, 1 second)
[JVM-2]   java.lang.RuntimeException: failure while attaching new conductor
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.attachConductor(MultiNodeSpec.scala:384)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:389)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:249)
[JVM-2]   at akka.http.MultiNodeSpecSpec.<init>(AkkaHttpServerLatencyMultiNodeSpec.scala:78)
[JVM-2]   at akka.http.AkkaHttpServerLatencyMultiNodeSpecMultiJvmNode2.<init>(AkkaHttpServerLatencyMultiNodeSpec.scala:76)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-2]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-2]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-2]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-2]   at java.lang.Class.newInstance(Class.java:442)
[JVM-2]   at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:2644)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2461)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2460)
[JVM-2]   at scala.collection.immutable.List.map(List.scala:273)
[JVM-2]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2460)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
[JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
[JVM-2]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
[JVM-2]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
[JVM-2]   at org.scalatest.tools.Runner$.main(Runner.scala:860)
[JVM-2]   at org.scalatest.tools.Runner.main(Runner.scala)
[JVM-2]   Cause: java.util.concurrent.TimeoutException: Futures timed out after [1200000 milliseconds]
[JVM-2]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[JVM-2]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[JVM-2]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[JVM-2]   at 
```

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
