### ISSUE TITLE
Out of memory while use sbt compile akka

### ISSUE THREAD

**Issue by huangzhendong** [akka/akka#21052]
I was use sbt to compile akka, but at last it shows : 
the first time: java.util.concurrent.ExecutionException:java.langOutOfMemoryError:Java heap space
the second time: java.util.concurrent.ExecutionException:java.langOutOfMemoryError:GC overhead limit exceeded
so, who can tell me what happened? THANKS

**Comment by huangzhendong** [comment]
C:\Users\hzd\Desktop\Akka\akka-2.4.4>sbt compile
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-camel-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-camel-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-cluster-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-cluster-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-distributed-data-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-distributed-data-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-fsm-java-lambda\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-fsm-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-main-java-lambda\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-main-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-main-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-multi-node-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-persistence-java-lambda\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-persistence-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-persistence-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-remote-java\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-remote-scala\project
[info] Loading project definition from C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-supervision-java-lambda\project
[info] Set current project to akka (in build file:/C:/Users/hzd/Desktop/Akka/akka-2.4.4/)
[info] Compiling 4 Java sources to C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-supervision-java-lambda\target\classes...
[info] Compiling 4 Java sources to C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-samples\akka-sample-fsm-java-lambda\target\classes...
[info] Compiling 13 Scala sources to C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-typed\target\classes...
[info] Compiling 6 Scala sources to C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-stream-testkit\target\classes...
[info] Compiling 156 Scala sources and 120 Java sources to C:\Users\hzd\Desktop\Akka\akka-2.4.4\akka-http-core\target\classes...
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
        at sbt.Execute.next$1(Execute.scala:85)
        at sbt.Execute.processAll(Execute.scala:88)
        at sbt.Execute.runKeep(Execute.scala:68)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:359)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:358)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:378)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:64)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:62)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:314)
        at sbt.Aggregation$.timedRun(Aggregation.scala:62)
        at sbt.Aggregation$.runTasks(Aggregation.scala:71)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:32)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:31)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:153)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:152)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:244)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:241)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:54)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at scala.runtime.ObjectRef.create(ObjectRef.java:22)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform1(SpecializeTypes.scala:1555)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transform$3.apply(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transform$3.apply(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.reportError(SpecializeTypes.scala:1434)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform(SpecializeTypes.scala:1385)
        at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1363)
        at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1361)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17)
        at scala.reflect.internal.Trees$class.itransform(Trees.scala:1360)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform1(SpecializeTypes.scala:1706)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transform$3.apply(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transform$3.apply(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.reportError(SpecializeTypes.scala:1434)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform(SpecializeTypes.scala:1442)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2.transform(SpecializeTypes.scala:1385)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2559)
        at scala.collection.immutable.List.loop$1(List.scala:173)
        at scala.collection.immutable.List.mapConserve(List.scala:189)
        at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2559)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transformTemplate$1$1.apply(SpecializeTypes.scala:1613)
        at scala.tools.nsc.transform.SpecializeTypes$$anon$2$$anonfun$transformTemplate$1$1.apply(SpecializeTypes.scala:1613)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] Use 'last' for the full log.

C:\Users\hzd\Desktop\Akka\akka-2.4.4>

**Comment by johanandren** [comment]
You need to run sbt with more memory, this can be done with the -mem parameter or with the SBT_OPTS environment variable. I run it with ~2Gb.

Please use the gitter channels and mailing lists for questions and keep the issue tracker for bugs and improvement tickets, thanks!

**Comment by hepin1989** [comment]
@johanandren Maybe add some notes to the `CONTRIBUTING.md`

**Comment by johanandren** [comment]
Good idea @hepin1989 
I created a PR: #21055
