### ISSUE TITLE
FAILED: akka.cluster.NodeChurn

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21053]
https://jenkins.akka.io:8498/job/akka-nightly/3545/consoleFull

```
[JVM-2] - must join and remove transient nodes without growing gossip payload *** FAILED *** (44 seconds, 259 milliseconds)
[JVM-2]   false was not true (NodeChurnSpec.scala:82)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3571/consoleFull

```
 - must join and remove transient nodes without growing gossip payload *** FAILED *** (38 seconds, 341 milliseconds)
[JVM-2]   false was not true (NodeChurnSpec.scala:82)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
[JVM-2]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6231)
[JVM-2]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6265)
[JVM-2]   at akka.cluster.NodeChurnSpec$$anonfun$awaitRemoved$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8.apply(NodeChurnSpec.scala:82)
[JVM-2]   at akka.cluster.NodeChurnSpec$$anonfun$awaitRemoved$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8.apply(NodeChurnSpec.scala:81)
...
```
