### ISSUE TITLE
FAILED: ResponseRendererSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21088]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7000/consoleFull

```
[info] - The 'Connection' header should be rendered correctly *** FAILED *** (3 seconds, 18 milliseconds)
[info]   TestFailedException was thrown during property evaluation. (ResponseRendererSpec.scala:573)
[info]     Message: (HTTP/1.0 200 OK

[info]   Server: akka-http/1.0.0

[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]   Connection: close

[info]   Content-Type: text/plain; charset=UTF-8

[info]   
[info]   ENTITY,Some(false)) did not equal (HTTP/1.0 200 OK

[info]   Server: akka-http/1.0.0

[info]   Date: Thu, 25 Aug 2011 09:10:29 GMT

[info]   Connection: close

[info]   Content-Type: text/plain; charset=UTF-8

[info]   
[info]   ENTITY,Some(true))
[info]     Location: (ResponseRendererSpec.scala:582)
[info]     Occurred at table row 71 (zero based, not counting headings), which had values (
[info]       Req Prot = HttpProtocol(HTTP/1.0),
[info]       HEAD Req = false,
[info]       Req CH = Some(Connection: Keep-Alive),
[info]       Res Prot = HttpProtocol(HTTP/1.0),
[info]       Res CH = Some(Connection: Keep-Alive),
[info]       Res CD = true,
[info]       Ren Conn = Some(Connection: close),
[info]       Close = true
[info]     )
[info]   org.scalatest.exceptions.TableDrivenPropertyCheckFailedException:
[info]   at org.scalatest.prop.TableFor8$$anonfun$apply$37.apply(TableFor1.scala:1626)
[info]   at org.scalatest.prop.TableFor8$$anonfun$apply$37.apply(TableFor1.scala:1617)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[info]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
[info]   at org.scalatest.prop.TableFor8.apply(TableFor1.scala:1617)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$class.forAll(TableDrivenPropertyChecks.scala:462)
[info]   at org.scalatest.prop.TableDrivenPropertyChecks$.forAll(TableDrivenPropertyChecks.scala:665)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38$$anon$30.<init>(ResponseRendererSpec.scala:573)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply$mcV$sp(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at akka.http.impl.engine.rendering.ResponseRendererSpec$$anonfun$1$$anonfun$apply$mcV$sp$38.apply(ResponseRendererSpec.scala:461)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:373)
```

**Comment by drewhk** [comment]
This is exactly after my merge of the interpreter, so it is related. Either a bug in my code, or a lurking bug exposed (just like in the chunker)

**Comment by ktoso** [comment]
Would be good to pick this before announcing 2.4.9 stable.

**Comment by johanandren** [comment]
There is a timeout of 100ms waiting for the stream to be closed, if it fails it will return `Some(false)` which is how the test failed, I cannot figure out another reason the test case could fail (looked carefully at the rendering stage).

As it has not failed since, and I cannot get it to repeat locally, I think I will close this and we can re-open if it happens again and figure out if we should increase it.

**Comment by johanandren** [comment]
Darn. That was all I had to do to provoke it to happen again:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4080/consoleFull

**Comment by jrudolph** [comment]
This happened again in https://jenkins.akka.io:8498/job/akka-nightly/3694/consoleFull

Now, tracked as https://github.com/akka/akka-http/issues/332.
