### ISSUE TITLE
Grabbing from closed input port in Merge

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21138]
```
requirement failed: Cannot get element from already empty input port (Merge.in1)
java.lang.IllegalArgumentException: requirement failed: Cannot get element from already empty input port (Merge.in1)
at scala.Predef$.require(Predef.scala:224)
at akka.stream.stage.GraphStageLogic.grab(GraphStage.scala:381)
at akka.stream.scaladsl.Merge$$anon$1.akka$stream$scaladsl$Merge$$anon$$dequeueAndDispatch(Graph.scala:65)
```

**Comment by drewhk** [comment]
Seems like similar to the Balance version
