### ISSUE TITLE
Regression in Cluster Singleton 2.4.9

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21236]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/448/consoleFull

Various failures, it looks like the first one is the "real" and the rest are likely just cascading failures.

```
[JVM-1] - must recover coordinator state after coordinator crash *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-8
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[JVM-1]   ...
```

**Comment by drewhk** [comment]
Two more. This looks like a real issue:

https://jenkins.akka.io:8498/job/akka-nightly/3613/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4110/consoleFull

**Comment by patriknw** [comment]
The suspect is https://github.com/akka/akka/pull/21176
Perhaps the tests are expecting one-by-one rebalance?

**Comment by drewhk** [comment]
I think so. I had 3 more failures during the night but I won't paste them as they look exactly the same. This fails rather reproducibly it seems.

**Comment by patriknw** [comment]
I'll try to fix this
