### ISSUE TITLE
failed: ConnectionPoolSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21231]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7117/consoleFull

```
[info] - should never close hot connections when minConnections key is given and >0 (minConnections = 5) *** FAILED *** (3 seconds, 117 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.stream.testkit.TestSubscriber$OnNext
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:408)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:737)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:317)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$12$$anon$15.<init>(ConnectionPoolSpec.scala:267)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply$mcV$sp(ConnectionPoolSpec.scala:252)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(ConnectionPoolSpec.scala:252)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$1$$anonfun$apply$mcV$sp$12.apply(ConnectionPoolSpec.scala:252)
```

**Comment by patriknw** [comment]
@leachbj Do you think this was fixed in your PR https://github.com/akka/akka/pull/21316 ?

@ktoso this was missing the http label, so if it's still relevant we should move it to akka-http

**Comment by ktoso** [comment]
Thanks, moving
