### ISSUE TITLE
ClusterMetrics always fails to verify Sigar provisioning on Windows 7 and 10

### ISSUE THREAD

**Issue by cessationoftime** [akka/akka#21240]
Running on Windows 10 with Akka 2.4.9 and kamon sigar-loader version 1.6.6-rev002.

In [Provision.scala](https://github.com/akka/akka/blob/v2.4.9/akka-cluster-metrics/src/main/scala/akka/cluster/metrics/Provision.scala#L49).

```scala
  def verifiedSigarInstance: SigarProxy = {
    val sigar = new Sigar()
    sigar.getPid
    sigar.getLoadAverage
    sigar.getCpuPerc
    sigar
  }
```

def verifiedSigarInstance will always throw an exception when it attempts to run sigar.getLoadAvarage.  This causes the ClusterMetrics extension to repeatedly attempt to provision/verify sigar, but it never succeeds. Apparently getLoadAverage simply isn't implemented for the Windows OS in "sigar-loader" % "1.6.6-rev002" which is the most recent version available as of August 21 2016.  This is also the version of sigar-loader referenced in the cluster metrics documentation.

Running a simple program with the following code will reproduce the error under Windows 10, and likely Windows 7 too.

```scala
import java.io.File;
import org.hyperic.sigar.Sigar;
import kamon.sigar.SigarProvisioner;

object ExampleMain extends App {
  
  SigarProvisioner.provision();
   val sigar = new Sigar()
   val loadAverage =  sigar.getLoadAverage 
} 
```
The exception is:

```
Aug 20, 2016 2:52:59 PM kamon.sigar.SigarProvisioner discoverLocation
INFO: Using location provided by hard coded value.
Aug 20, 2016 2:52:59 PM kamon.sigar.SigarProvisioner provision
INFO: Sigar library provisioned: C:\Users\cvanvranken\gits\Example\main\server-metrics\native\sigar-amd64-winnt.dll
Exception in thread "main" org.hyperic.sigar.SigarNotImplementedException: This method has not been implemented on this platform
	at org.hyperic.sigar.SigarNotImplementedException.<clinit>(SigarNotImplementedException.java:28)
	at org.hyperic.sigar.Sigar.getLoadAverage(Native Method)
```

This function should be implemented in the hyperic/sigar repo within file: src/os/win32/win32_sigar.c, for function sigar_loadavg_get.

There is a comment above the function which makes me think they do not intend to fix it, the comment says:  "there is no api for this info. closest i've seen is enumerating the entire process table and calculating an average based on process times."

I think the verifiedSigarInstance function that ClusterMetrics calls should be changed so that the getLoadAverage function is not called when running on Windows, otherwise Sigar will be unuseable there.  Alternatively sigar_loadavg_get needs to be implemented.

I commented on this for the corresponding [issue](https://github.com/hyperic/sigar/issues/72) in the hyperic/sigar repo and someone responded to me. They say that this is implemented in the [Boundary fork of sigar]( https://github.com/boundary/sigar).

**Comment by patriknw** [comment]
Thanks for your findings. It would be great if you can create a pull request to fix this issue. 

It sounds like `sigar.getLoadAverage` doesn't work at all on Windows, and then we should perhaps use the JMX variant as fallback.

**Comment by cessationoftime** [comment]
JMX was running when Sigar wouldn't load for me.  And that function wasn't returning anything useful, always gave a -1 value.  My MetricsListener didn't even receive the metric, I only saw the -1 value when I went in with the debugger.

**Comment by patriknw** [comment]
ah, ok

**Comment by cessationoftime** [comment]
It's unlikely I will end up doing a pull request any time soon.  I intend to deploy to ubuntu server, so at least for now I will develop on ubuntu.

**Comment by patriknw** [comment]
Thanks for reporting!
