### ISSUE TITLE
Akka http and 100 Continue causes a SubscriptionTimeoutException

### ISSUE THREAD

**Issue by huntc** [akka/akka#21251]
Http clients such as `curl` expect a `100 Continue` response in relation to posting a large amount of data. As of Akka 2.4.7, but also observed with 2.4.9, there appears to be a race condition where sub streams formed as part of `prefixAndTail` fail. The problem is hard to reproduce but manifests itself with the following stack trace when it does occur:

```
2016-08-23T04:26:51Z ChristophersMBP.lan ERROR FileSubscriber [sourceThread=conductr-akka.stream.default-blocking-io-dispatcher-219, akkaTimestamp=04:26:51.172UTC, akkaSource=akka.tcp://conductr@127.0.0.1:9004/user/reaper/control-server/StreamSupervisor-9/flow-1262-1-fileSink, sourceActorSystem=conductr] - Tearing down FileSink(/var/folders/7g/ftd7sqz132zcfj_rlpb6xpw00000gn/T/2f522926-3f58-403e-9b5f-ea7923a6a92f6630142131447228655/default/bundle.conf) due to upstream error
akka.stream.impl.SubscriptionTimeoutException: Substream Source has not been materialized in 5000 milliseconds
	at akka.stream.impl.fusing.SubSource.timeout(StreamOfStreams.scala:693)
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet.timeout(GraphStage.scala:1035)
	at akka.stream.impl.fusing.PrefixAndTail$PrefixAndTailLogic.onTimer(StreamOfStreams.scala:130)
	at <snip>
2016-08-23T04:26:51Z ChristophersMBP.lan ERROR RepointableActorRef [sourceThread=conductr-akka.actor.default-dispatcher-5, akkaTimestamp=04:26:51.174UTC, akkaSource=akka://conductr/user/reaper/control-server/StreamSupervisor-9/flow-1253-0-unknown-operation, sourceActorSystem=conductr] - Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@3d1662e9]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:436)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:395)
	at <snip>
```

From a client perspective:

```
curl -v --header "User-Agent: Typesafe ConductR Docker Entrypoint Script" --form "bundleConf=@conductr-grafana/target/bundle/bundle/t37684c33cbd8b075fb837e218bc6eebc2d60671f3ba3cc90f.zip" 127.0.0.1:9005/v2/bundles/0-372d167b74f9ebc3
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9005 (#0)
> POST /v2/bundles/ HTTP/1.1
> Host: 127.0.0.1:9005
> Accept: */*
> User-Agent: Typesafe ConductR Docker Entrypoint Script
> Content-Length: 45461050
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------de24fc60856e2fb5
> 
< HTTP/1.1 100 Continue
< Server: akka-http/2.4.7
< Date: Tue, 23 Aug 2016 04:26:46 GMT
< HTTP/1.1 400 Bad Request
< Server: akka-http/2.4.7
< Date: Tue, 23 Aug 2016 04:26:51 GMT
< Connection: close
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 59
< 
* we are done reading and this is set to close, stop send
* Closing connection 0
```

In the above response times Akka http will respond with the `100` relatively quickly.

In situations where all is well, `100` is also being replied:

```
< HTTP/1.1 100 Continue
< Server: akka-http/2.4.7
< Date: Tue, 23 Aug 2016 04:26:44 GMT
< HTTP/1.1 200 OK
< Server: akka-http/2.4.7
< Date: Tue, 23 Aug 2016 04:26:44 GMT
< Content-Type: application/json
< Content-Length: 98
```

[Possibly related](https://github.com/akka/akka/issues/18013), although I am not suggesting that we should avoid sending a `100 Continue` response. As stated, some clients, such as `curl` expect the `100` status.

As a work-around I can disable `curl`'s expect behaviour with `-H "Expect: ".

Full stack trace: [stack.txt](https://github.com/akka/akka/files/431691/stack.txt)

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
