### ISSUE TITLE
Error noise with ClusterActorRefProvider and TestKit.shutdownActorSystem(system)

### ISSUE THREAD

**Issue by abesanderson** [akka/akka#21296]
Seeing (benign) exceptions that look somewhat similar to #15102, in this case, I am setting up a ClusterActorRefProvider for some tests using cluster sharding.  The exceptions here are thrown after shutting down the actor system associated with the test kit.  The stack indicates something originating from being unable to serialize:
```
15:39:05.757 [default-akka.actor.default-dispatcher-17] ERROR akka.cluster.ClusterActorRefProvider 21:39:05.756UTC akka.cluster.ClusterActorRefProvider - Error while looking up address [akka://all-systems]
akka.remote.RemoteTransportException: No transport is loaded for protocol: [akka], available protocols: [akka.tcp]
  at akka.remote.Remoting$.localAddressForRemote(Remoting.scala:89)
  at akka.remote.Remoting.localAddressForRemote(Remoting.scala:131)
  at akka.remote.RemoteActorRefProvider.actorFor(RemoteActorRefProvider.scala:328)
  at akka.actor.ActorRefFactory$class.actorFor(ActorRefProvider.scala:284)
  at akka.actor.ActorSystem.actorFor(ActorSystem.scala:254)
  at com.twitter.chill.akka.ActorRefSerializer.read(ActorRefSerializer.scala:49)
  at com.twitter.chill.akka.ActorRefSerializer.read(ActorRefSerializer.scala:38)
  at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
  at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
  at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
  at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
  at com.twitter.chill.SerDeState.readClassAndObject(SerDeState.java:61)
  at com.twitter.chill.KryoPool.fromBytes(KryoPool.java:94)
  at com.twitter.chill.akka.AkkaSerializer.fromBinary(AkkaSerializer.scala:72)
  at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:142)
  at scala.util.Try$.apply(Try.scala:192)
  at akka.serialization.Serialization.deserialize(Serialization.scala:142)
  at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:140)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
  at akka.actor.Cell$class.sendMessage(ActorCell.scala:295)
  at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
  at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:171)
  at akka.event.EventStream.akka$event$EventStream$$registerWithUnsubscriber(EventStream.scala:120)
  at akka.event.EventStream.subscribe(EventStream.scala:56)
  at akka.event.EventStream.subscribe(EventStream.scala:28)
  at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:80)
  at akka.event.LoggingBus$$anonfun$setUpStdoutLogger$3.apply(Logging.scala:80)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at akka.event.LoggingBus$class.setUpStdoutLogger(Logging.scala:80)
  at akka.event.LoggingBus$class.stopDefaultLoggers(Logging.scala:156)
  at akka.event.EventStream.stopDefaultLoggers(EventStream.scala:28)
  at akka.actor.LocalActorRefProvider$SystemGuardian.stopWhenAllTerminationHooksDone(ActorRefProvider.scala:460)
  at akka.actor.LocalActorRefProvider$SystemGuardian.stopWhenAllTerminationHooksDone(ActorRefProvider.scala:455)
  at akka.actor.LocalActorRefProvider$SystemGuardian$$anonfun$terminating$1.applyOrElse(ActorRefProvider.scala:450)
  at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
  at akka.actor.LocalActorRefProvider$SystemGuardian.aroundReceive(ActorRefProvider.scala:424)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
Looking at the stack trace `akka.actor.ActorSystem.actorFor(ActorSystem.scala:254)` this must be Akka 2.3.x. We will not fix such an issue in 2.3.x, since it is end-of-life. 

`resolveActorRef` should be used when deserializing ActorRef http://doc.akka.io/docs/akka/2.4/scala/serialization.html#Serializing_ActorRefs

We can take another look if you see the same problem with 2.4

**Comment by abesanderson** [comment]
This was with:

com.twitter:chill-akka_2.11 0.8.0
com.typesafe.akka:akka-actor_2.11 2.4.9
com.typesafe.akka:akka-remote_2.11 2.4.9
com.typesafe.akka:akka-cluster-sharding_2.11 2.4.9
com.typesafe.akka:akka-cluster_2.11 2.4.9
com.typesafe.akka:akka-testkit_2.11 2.4.9

**Comment by abesanderson** [comment]
I think I see the problem now.  It was in the chill package, not akka.  Unfortunately, there is not a newer version of the kryo serializer available and the project is pretty stale. I'll see if I can get their side to accept a pull request.
