### ISSUE TITLE
FAILED: ClusterShardingSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21297]
```
[JVM-4] - must recover coordinator state after coordinator crash *** FAILED ***
[JVM-4]   java.lang.RuntimeException: barrier failed: after-8
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[JVM-4]   ...
[JVM-4] - must rebalance to nodes with less shards *** FAILED ***
[JVM-4]   java.lang.RuntimeException: barrier failed: rebalancing-shards-allocated
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4117/consoleFull

**Comment by patriknw** [comment]
I looked at this. I'm pretty sure it's the singleton issue in 2.4.9, which was fixed in 2.4.10, in https://github.com/akka/akka/pull/21247
