### ISSUE TITLE
IdleTimeout or downstream `completeStage`/`failStage` causes Http client flow to never complete

### ISSUE THREAD

**Issue by derjust** [akka/akka#21304]
This is a very simplified example to show the issue. The general process is
* Create a `Source[HttpRequest]`
* Use this via `http.newHostConnectionPool()` to turn it into `Flow[Future[HttpResponse]]`
* Consume the upstream content via `Flow.mapAsyncUnordered` 
* Do some asset processing and send it as chunked response to the client

The problem appears now as soon as the `IdleTimeout` throws its 

```
java.util.concurrent.TimeoutException: No elements passed in the last X.
	at akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:699) ~[akka-stream_2.11-2.4.9.jar:na]
```

*OR* the stream is aborted before all elements of the `http()/mapAsync` combo are consumed.

I understand why it is happening in my real setup (the chunked response isn't consumed quickly enough)

The issue is, that this exception seems to keep the overall `Flow` - depicted above - in an open state. At least it is not GCed and thus my memory fills up till OOM.
The very same also happens if something behind the `http.pool` Flow (i.e. `httpResponse2Chunk`) issues a complete/fail stage

To reproduce, use the code below, consume the service per

```
curl http://localhost:8080/ --limit-rate 1b > /dev/null
```

Afterwards use the heap dump (`jmap`, `visualvm` etc.) to search for instances of `JustSomeCaseToMakeSearchingInHeapDumpEasier`
Those should not exist as the whole stream should be gone (a `LastChunk` was sent to the client)

**I want to understand why the resources are not removed or what to do to release the resources.**

```
scalaVersion := "2.11.8"
libraryDependencies ++= {
  val akkaV = "2.4.9"
  Seq(
    "com.typesafe.akka"         %% "akka-http-core"              % akkaV,
    "com.typesafe.akka"         %% "akka-http-experimental"      % akkaV,
    "com.typesafe.akka"         %% "akka-actor"                  % akkaV,
    "com.typesafe.akka"         %% "akka-slf4j"                  % akkaV,
    "org.slf4j"                 %  "slf4j-api"                   % "1.7.21",
    "ch.qos.logback"            %  "logback-classic"             % "1.0.7",
    "com.typesafe.akka"         %% "akka-http-testkit"           % akkaV      % "test"
  )
}
```

```
akka {

  http {

    host-connection-pool {
      #This is the mapAsyncUnordered parallelism
      # with max-connections = 1 the issue does not appear at all
      max-connections = 8

      idle-timeout = 45 s

      client = {
        idle-timeout = 45 s
      }
    }
  }
}
```

```scala

object Boot extends App {
  implicit val actorSystem = ActorSystem()
  implicit val ec = actorSystem.dispatcher
  implicit val materializer = ActorMaterializer()

  val routes = new TestService().downloadService
  val serverSource = Http().bindAndHandle(routes, "0.0.0.0", port = 8080)

  println("Ready. Use \n\tcurl http://localhost:8080/ --limit-rate 5k > /dev/null\nto cause the issue")
}

final class SomeDownstreamBusiness(data: List[JustSomeCaseToMakeSearchingInHeapDumpEasier]) extends SimpleLinearGraphStage[ChunkStreamPart] {

  override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) {
    setHandler(in, new InHandler {
      override def onPush(): Unit = push(out, grab(in))
    })

    setHandler(out, new OutHandler {
      override def onPull(): Unit = pull(in)
    })
  }

}

case class JustSomeCaseToMakeSearchingInHeapDumpEasier(file: String)

class TestService(implicit system: ActorSystem, fm: Materializer) {
  def chunkStreamGraphCreator() = {
    Source.fromGraph(GraphDSL.create() { implicit builder =>
      import GraphDSL.Implicits._
      implicit val ec = system.dispatcher
      val baseUrl = Uri("http://devimages.apple.com/iphone/samples/bipbop/gear4/")
      val data =  (for (i <- 0 to 170) yield JustSomeCaseToMakeSearchingInHeapDumpEasier(s"fileSequence$i.ts"))
      val in = Source.fromIterator[JustSomeCaseToMakeSearchingInHeapDumpEasier](() => data.iterator)

      val createRequest = Flow[JustSomeCaseToMakeSearchingInHeapDumpEasier].map(s => {
        val totalUri = Uri(s.file).resolvedAgainst(baseUrl)
        println(totalUri)
        (HttpRequest(uri = totalUri), s)
      })
      val httpClient = Http().newHostConnectionPool[JustSomeCaseToMakeSearchingInHeapDumpEasier](baseUrl.authority.host.address, baseUrl.effectivePort)

      val httpResponse2Chunk = Flow[(Try[HttpResponse], JustSomeCaseToMakeSearchingInHeapDumpEasier)].mapAsyncUnordered(8)({case (response, downloadedFile) =>
        response match {
        // No proper error handling here - it's fine to send a 404 error page down, too
        case Success(httpResponse) => httpResponse.entity.toStrict(1 minute).map(data => {
          ChunkStreamPart(data.data)
        })
        // Upstream error should let the client finish properly
        case _ => Future.successful(LastChunk())
      }})

      val out = in ~> createRequest ~> httpClient ~> httpResponse2Chunk ~> Flow[ChunkStreamPart].takeWithin(5 seconds)

      SourceShape(out.outlet)
    })
  }

  def downloadService = get { complete {
    HttpResponse(entity = HttpEntity.Chunked(ContentType(MediaTypes.`application/octet-stream`), chunkStreamGraphCreator()))
  }}
}
```

The transfer of data will stop after 5 seconds (and should complete the Flow) - but it doesn't.
Also after the idle timer went off, you still can see having alive parts of the flow via `visualvm`:

* There are more `GraphInterpreterShell` than before
* There are `JustSomeCaseToMakeSearchingInHeapDumpEasier` instances that should not be there

According to my `visualvm`, the GC root is:
 
```
this     - value: akkaHttpMemory.JustSomeCaseToMakeSearchingInHeapDumpEasier #1
 <- [31]     - class: java.lang.Object[], value: akkaHttpMemory.JustSomeCaseToMakeSearchingInHeapDumpEasier #1
  <- display0     - class: scala.collection.immutable.VectorIterator, value: java.lang.Object[] #3054
   <- currentIterator     - class: akka.stream.impl.fusing.StatefulMapConcat$$anon$19, value: scala.collection.immutable.VectorIterator #5
    <- [9]     - class: akka.stream.stage.GraphStageLogic[], value: akka.stream.impl.fusing.StatefulMapConcat$$anon$19 #12
     <- logics     - class: akka.stream.impl.fusing.GraphInterpreter, value: akka.stream.stage.GraphStageLogic[] #10
      <- _interpreter     - class: akka.stream.impl.fusing.SubSink$$anon$3, value: akka.stream.impl.fusing.GraphInterpreter #11
       <- $outer     - class: akka.stream.stage.GraphStageLogic$$anon$2, value: akka.stream.impl.fusing.SubSink$$anon$3 #1
        <- value     - class: java.util.concurrent.atomic.AtomicReference, value: akka.stream.stage.GraphStageLogic$$anon$2 #25
         <- akka$stream$impl$fusing$SubSink$$status     - class: akka.stream.impl.fusing.SubSink, value: java.util.concurrent.atomic.AtomicReference #40
          <- _sink     - class: akka.stream.stage.GraphStageLogic$SubSinkInlet, value: akka.stream.impl.fusing.SubSink #1
           <- sinkIn$1     - class: akka.http.impl.engine.rendering.HttpResponseRendererFactory$HttpResponseRenderer$$anon$1$$anon$5, value: akka.stream.stage.GraphStageLogic$SubSinkInlet #1
            <- outHandler     - class: akka.stream.impl.fusing.GraphInterpreter$Connection, value: akka.http.impl.engine.rendering.HttpResponseRendererFactory$HttpResponseRenderer$$anon$1$$anon$5 #1
             <- [6]     - class: akka.stream.impl.fusing.GraphInterpreter$Connection[], value: akka.stream.impl.fusing.GraphInterpreter$Connection #271
              <- connections     - class: akka.stream.impl.fusing.GraphInterpreter, value: akka.stream.impl.fusing.GraphInterpreter$Connection[] #245
               <- _interpreter     - class: akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic, value: akka.stream.impl.fusing.GraphInterpreter #12
                <- $outer     - class: akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anonfun$preStart$2, value: akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic #9
                 <- behaviour     - class: akka.stream.stage.GraphStageLogic$StageActor, value: akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anonfun$preStart$2 #1
                  <- $outer     - class: akka.stream.stage.GraphStageLogic$StageActor$$anonfun$2, value: akka.stream.stage.GraphStageLogic$StageActor #9
                   <- f     - class: akka.actor.FunctionRef, value: akka.stream.stage.GraphStageLogic$StageActor$$anonfun$2 #9
                    <- key     - class: scala.collection.immutable.HashSet$HashSet1, value: akka.actor.FunctionRef #9
                     <- akka$actor$dungeon$DeathWatch$$terminatedQueued     - class: akka.actor.ActorCell, value: scala.collection.immutable.HashSet$HashSet1 #195
                      <- actorCell     - class: akka.actor.LocalActorRef, value: akka.actor.ActorCell #54
                       <- attachment     - class: sun.nio.ch.SelectionKeyImpl, value: akka.actor.LocalActorRef #17
                        <- ski     - class: sun.nio.ch.KQueueSelectorImpl$MapEntry, value: sun.nio.ch.SelectionKeyImpl #9
                         <- value     - class: java.util.HashMap$Node, value: sun.nio.ch.KQueueSelectorImpl$MapEntry #9
                          <- [4]     - class: java.util.HashMap$Node[], value: java.util.HashMap$Node #3464
                           <- table     - class: java.util.HashMap, value: java.util.HashMap$Node[] #571
                            <- fdMap (Java frame)     - class: sun.nio.ch.KQueueSelectorImpl, value: java.util.HashMap #624
```

**Comment by ktoso** [comment]
Thanks for reporting, will have a look soon

**Comment by derjust** [comment]
Might be this comment be the problem:
https://github.com/akka/akka/pull/1335#discussion_r3787234

Because that's how it looks to me: My actors of my stages end up in the `terminatedQueue` and stay there forever. Does anybody has any insights what exactly 
> an actor for which this leak is a problem has bigger design issues 
are the design issues?

**Comment by derjust** [comment]
I found a workaround that seem to work for us. Maybe it helps triaging:
I updated the flow to be:

```scala
val a = Flow[Something, HttpRequest]
val x = KillSwitch.shared("killswitch")
val b = Http().newConnectionPool
val c = Flow.mapAsyncUnordered(5, response => /* error handling stripped*/ response.entity.dataBytes
val y = Flow.map(if downstreamClosed { grab(in); tryPull(in)} else { push(out, grab(in))})  // implemented as custom stage
val d = Flow.map(downloadedEntity => if (businessRule) x.shutdown(); failStage(); else { downloadedEntity}) // Implemented as custom stage

a ~> x ~> b ~> c ~> y ~> d
```
So if I trigger an abort downstream, my killswitch shuts down the supply of `HttpResponse`s. But I still consume everything that's coming out of the Http client flow

**Comment by derjust** [comment]
Re-tested with `2.4.10`
It took way longer to trigger this behavior  (in total like 20 requests, not 2 as before) and the GC root is different now:

```
this     - value: com.comcast.totes.service.DownloadFile #1
 <- akka$stream$scaladsl$Partition$$anon$$outPendingElem     - class: akka.stream.scaladsl.Partition$$anon$5, value: com.comcast.totes.service.DownloadFile #1
  <- [1]     - class: akka.stream.stage.GraphStageLogic[], value: akka.stream.scaladsl.Partition$$anon$5 #1
   <- logics     - class: akka.stream.impl.fusing.GraphInterpreter, value: akka.stream.stage.GraphStageLogic[] #209
    <- _interpreter     - class: akka.stream.impl.fusing.MapAsyncUnordered$$anon$22, value: akka.stream.impl.fusing.GraphInterpreter #189
     <- $outer     - class: akka.stream.impl.fusing.MapAsyncUnordered$$anon$22$$anonfun$22, value: akka.stream.impl.fusing.MapAsyncUnordered$$anon$22 #23
      <- onComplete     - class: scala.concurrent.impl.CallbackRunnable, value: akka.stream.impl.fusing.MapAsyncUnordered$$anon$22$$anonfun$22 #23
       <- head     - class: scala.collection.immutable.$colon$colon, value: scala.concurrent.impl.CallbackRunnable #5
        <- value     - class: scala.concurrent.impl.Promise$DefaultPromise, value: scala.collection.immutable.$colon$colon #16756
         <- result$1     - class: akka.http.scaladsl.HttpExt$$anonfun$clientFlow$1$$anonfun$apply$7, value: scala.concurrent.impl.Promise$DefaultPromise #190
          <- onComplete     - class: scala.concurrent.impl.CallbackRunnable, value: akka.http.scaladsl.HttpExt$$anonfun$clientFlow$1$$anonfun$apply$7 #1
           <- head     - class: scala.collection.immutable.$colon$colon, value: scala.concurrent.impl.CallbackRunnable #4
            <- value     - class: scala.concurrent.impl.Promise$DefaultPromise, value: scala.collection.immutable.$colon$colon #16755
             <- responsePromise     - class: akka.http.impl.engine.client.PoolFlow$RequestContext, value: scala.concurrent.impl.Promise$DefaultPromise #189
              <- [0]     - class: java.lang.Object[], value: akka.http.impl.engine.client.PoolFlow$RequestContext #1
               <- elements     - class: java.util.ArrayDeque, value: java.lang.Object[] #15476
                <- akka$http$impl$engine$client$PoolSlot$SlotProcessor$$anon$$inflightRequests     - class: akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1, value: java.util.ArrayDeque #411
                 <- $outer     - class: akka.stream.stage.GraphStageLogic$$anon$2, value: akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1 #178
                  <- externalCallback     - class: akka.stream.impl.fusing.SubSource, value: akka.stream.stage.GraphStageLogic$$anon$2 #1204
                   <- $outer     - class: akka.stream.impl.fusing.SubSource$$anon$4, value: akka.stream.impl.fusing.SubSource #340
                    <- [13]     - class: akka.stream.stage.GraphStageLogic[], value: akka.stream.impl.fusing.SubSource$$anon$4 #175
                     <- logics     - class: akka.stream.impl.fusing.GraphInterpreter, value: akka.stream.stage.GraphStageLogic[] #200
                      <- _interpreter     - class: akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7, value: akka.stream.impl.fusing.GraphInterpreter #204
                       <- $outer     - class: akka.stream.stage.TimerGraphStageLogic$$anon$3, value: akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7 #171
                        <- runnable$1     - class: akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1, value: akka.stream.stage.TimerGraphStageLogic$$anon$3 #165
                         <- task     - class: akka.actor.LightArrayRevolverScheduler$TaskHolder, value: akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1 #166
                          <- value     - class: akka.dispatch.AbstractNodeQueue$Node, value: akka.actor.LightArrayRevolverScheduler$TaskHolder #89
                           <- value     - class: akka.actor.LightArrayRevolverScheduler$TaskQueue, value: akka.dispatch.AbstractNodeQueue$Node #388
                            <- [33]     - class: akka.actor.LightArrayRevolverScheduler$TaskQueue[], value: akka.actor.LightArrayRevolverScheduler$TaskQueue #407
                             <- akka$actor$LightArrayRevolverScheduler$$anon$$wheel (Java frame)     - class: akka.actor.LightArrayRevolverScheduler$$anon$4, value: akka.actor.LightArrayRevolverScheduler$TaskQueue[] #1
```

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http Rationale for the move discussed here: akka/akka-meta#27
If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
