### ISSUE TITLE
Improve error message when a junction isn't added to a Graph builder

### ISSUE THREAD

**Issue by dotta** [akka/akka#21300]
I've had the following exception reported on a Flow I've created using the `Flow.fromGraph` DSL

```
java.lang.IllegalArgumentException: requirement failed: The inlets [UnzipWith2.in] and outlets [MapAsync.out] must correspond to the inlets [UnzipWith2.in] and outlets [MapAsync.out]
[info]   at scala.Predef$.require(Predef.scala:224)
[info]   at akka.stream.Shape.requireSamePortsAs(Shape.scala:168)
[info]   at akka.stream.impl.StreamLayout$CompositeModule.replaceShape(StreamLayout.scala:426)
[info]   at akka.stream.scaladsl.GraphApply$class.create(GraphApply.scala:19)
[info]   at akka.stream.scaladsl.GraphDSL$.create(Graph.scala:916)
```

The error message is quite obscure, and it turned out that the reason for the error was that I had forgotten to add a `builder.add` to one of the junctions I was using.

```
Flow.fromGraph(GraphDSL.create() { implicit builder =>
  import GraphDSL.Implicits._
  // I forgot to wrap this into a `builder.add` call!
  val flow = Flow[(String, String)].mapAsync(1) { ... }
  ...
}
```

It would be great if the reported error could contain a hint that would help realising what the problem was.

**Comment by drewhk** [comment]
The issue arises when the builder tries to replace the Amorphous (typeless) shape of the underlying module to the typed FlowShape and the ports don't match the expected ones (since they were not added to the module). This is a low-level internal message and should be translated to a more user-friendly message explaining that a module was likely not added to the graph.
