### ISSUE TITLE
FAILED: HttpServerBug2108Spec

### ISSUE THREAD

**Issue by 2m** [akka/akka#21348]
Sep 2, 2016 7:18:01 AM
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/461/

```
[akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@69243a2b]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:459)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:400)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
```

```
[info] - should not cause internal graph failures when consuming a `100 Continue` entity triggers a failure *** FAILED *** (179 milliseconds)
[info]   HttpServerBluePrint.ControllerStage: requirement failed: Cannot pull closed port (requestParsingIn),
[info]   inside HttpRequest(HttpMethod(POST),http://example.com/,List(Host: example.com, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Chunked(application/octet-stream),HttpProtocol(HTTP/1.1)) (HttpServerBug2108Spec.scala:70)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
[info]   at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:57)
[info]   at org.scalatest.Assertions$class.fail(Assertions.scala:1089)
[info]   at akka.testkit.AkkaSpec.fail(AkkaSpec.scala:57)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1$$anon$1$$anonfun$2.applyOrElse(HttpServerBug2108Spec.scala:70)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1$$anon$1$$anonfun$2.applyOrElse(HttpServerBug2108Spec.scala:38)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[info]   at org.scalatest.Inside$class.inside(Inside.scala:128)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec.inside(HttpServerBug2108Spec.scala:18)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1$$anon$1.<init>(HttpServerBug2108Spec.scala:38)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(HttpServerBug2108Spec.scala:28)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(HttpServerBug2108Spec.scala:28)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpServerBug2108Spec.scala:28)
[info]   at akka.http.impl.engine.server.HttpServerBug2108Spec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpServerBug2108Spec.scala:28)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
```

**Comment by ktoso** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
