### ISSUE TITLE
NPE in BroadcastHub

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21362]
Noticed this with Artery tests:

```
[JVM-2] [ERROR] [09/03/2016 08:33:38.982] [RemoteReDeploymentMultiJvmSpec-akka.remote.default-remote-dispatcher-16] [akka://RemoteReDeploymentMultiJvmSpec/system/StreamSupervisor-1/remote-3-0-unknown-operation] Error in stage [akka.stream.scaladsl.BroadcastHub$$anon$3@16198b35]: null
[JVM-2] java.lang.NullPointerException
[JVM-2] 	at akka.stream.scaladsl.BroadcastHub$$anon$3$$anon$5.onPull(Hub.scala:634)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:754)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:660)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:414)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[JVM-2] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
```

`hubCallback` is null

**Comment by drewhk** [comment]
Taking a look at this.
