### ISSUE TITLE
NotSerializableException: spray.can.HttpExt

### ISSUE THREAD

**Issue by lashchenko** [akka/akka#21408]
Hi.

I use 'serialize-creators = on' option during local development.
But I got some unexpected exception `NotSerializableException: spray.can.HttpExt` for field of actor (`val service: SprayApiService = ...`) .
The issue doesn't reproduce if 'serialize-creators = off' option used. In this case cluster works fine.
I have the same issue for functions too (`def service: SprayApiService = ...`)

I would like to clarify why akka throws the exception for the field or for the function?

On [official documentation](http://doc.akka.io/docs/akka/current/scala/serialization.html#Verification) I see:
> If you want to verify that your Props are serializable you can enable the following config option: serialize-creators = on

I prepared example. The project available at https://github.com/lashchenko/demo-akka-spray-serialization/tree/master

Test actor is simple:
```scala
class SprayApiServiceActor extends Actor {
  import context._

  val service: TestSprayApiService = new TestSprayApiService()

  // 'def' will fail
  // def service: TestSprayApiService = new TestSprayApiService()

  // (String => String) will fail too
  // def service: (String => Future[String]) = new TestSprayApiService().get

  override def receive: Receive = {
    case url: String => service.get(url).onComplete(x => println(s"$self : $x"))
//    case url: String => service(url).onComplete(x => println(s"$self : $x"))
  }
}
```

### Run Seed Node (EXPECTED BEHAVIOR)
[SprayApiServiceSeedNodeApp](https://github.com/lashchenko/demo-akka-spray-serialization/blob/master/src/main/scala/ua/akka/serialization/App.scala#L93) without `serialize-creators = on` will produce expected output:
```
API REQUEST: Method GET Endpoint http://google.com with Content:

API RESPONSE:
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=HKTRV_uqOY6Bogaf-oKYAw">here</A>.
</BODY></HTML>

Actor[akka://TestSystem/user/ServiceSupervisorActor/SprayApiService/c1#-394021438] : Success(<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=HKTRV_uqOY6Bogaf-oKYAw">here</A>.
</BODY></HTML>
)
```

### Run another cluster node on random port (EXPECTED BEHAVIOR)
[SprayApiServiceNodeApp](https://github.com/lashchenko/demo-akka-spray-serialization/blob/master/src/main/scala/ua/akka/serialization/App.scala#L106) without `serialize-creators = on` will produce expected output too:
```
API REQUEST: Method GET Endpoint http://google.com with Content:

API RESPONSE:
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=uaTRV4C3LaqhogantoWwBw">here</A>.
</BODY></HTML>

Actor[akka://TestSystem/remote/akka.tcp/TestSystem@127.0.0.1:56117/user/ServiceSupervisorActor/SprayApiService/c2#135729572] : Success(<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.com.ua/?gfe_rd=cr&amp;ei=uaTRV4C3LaqhogantoWwBw">here</A>.
</BODY></HTML>
)
```

### Run node with 'serialize-creators = on' (UNEXPECTED BEHAVIOR)
[SprayApiServiceFailedApp](https://github.com/lashchenko/demo-akka-spray-serialization/blob/master/src/main/scala/ua/akka/serialization/App.scala#L119) with `serialize-creators = on` will throw unexpected exception:
```
[ERROR] [09/08/2016 20:52:49.509] [TestSystem-akka.actor.default-dispatcher-14] [akka://TestSystem/user/ServiceSupervisorActor/SprayApiService] pre-creation serialization check failed at [akka://TestSystem/user/IO-HTTP]
java.lang.IllegalArgumentException: pre-creation serialization check failed at [akka://TestSystem/user/IO-HTTP]
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:260)
	at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:571)
	at spray.can.HttpExt.<init>(Http.scala:152)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(ReflectiveDynamicAccess.scala:32)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
	at akka.actor.ExtensionKey.createExtension(Extension.scala:153)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:737)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.actor.ExtensionKey.apply(Extension.scala:149)
	at akka.io.IO$.apply(IO.scala:26)
	at spray.client.pipelining$.sendReceive(pipelining.scala:35)
	at ua.akka.serialization.TestSprayApiService.pipeline(App.scala:28)
	at ua.akka.serialization.TestSprayApiService.get(App.scala:43)
	at ua.akka.serialization.SprayApiServiceActor$$anonfun$receive$1.applyOrElse(App.scala:68)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at ua.akka.serialization.SprayApiServiceActor.aroundReceive(App.scala:56)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.NotSerializableException: spray.can.HttpExt
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply$mcV$sp(Serializer.scala:235)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:235)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:235)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.serialization.JavaSerializer.toBinary(Serializer.scala:235)
	at akka.actor.dungeon.Children$$anonfun$makeChild$2.apply(Children.scala:250)
	at akka.actor.dungeon.Children$$anonfun$makeChild$2.apply(Children.scala:244)
	at scala.collection.LinearSeqOptimized$class.forall(LinearSeqOptimized.scala:83)
	at scala.collection.immutable.List.forall(List.scala:84)
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:244)
	... 31 more
```

The issue reproduced for field/function with 'Spray' classes only.

**Comment by lashchenko** [comment]
Also I found discussion about [ClusterRouterPool and Actors w/ non-serializable fields](https://groups.google.com/forum/#!topic/akka-user/0_yVCRHosa4) on Akka User Google Group.
User asked:
> So in order to use clustered actors, every member of the Actors being clustered must be serializable?

And @patriknw answered:
> The actor itself doesn't have to be serializable, but the Props and the parameters for the constructor must be serializable.

Thus I don't understand why akka throws the exception.

**Comment by johanandren** [comment]
A common case when you get errors like this is when you accidentally close over more state than you expect with the lambda creating an actor passed to `Props(creator)`, we recommend using a separate `props` factory on the companion object for exactly this reason.

Please use the mailing list or the gitter channel for questions like this and save the issue system for bugs and feature tickets, thanks!

**Comment by lashchenko** [comment]
@johanandren thank you for the response.

I will try to simplify the description of the problem.

## Use NOT SERIALIZABLE CLASS inside actor is ok if you don't pass the class to constructor of the actor.
```scala
class TestClass {
  // THIS IS NOT SERIALIZABLE CLASS.
  def get(request: String): Future[String] = Future.successful("TEST: " + request)
}

object TestActor {
  def props() = Props(classOf[TestActor])
  def name = "TestActor"
}

class TestActor extends Actor {
  import context._

  def service: (String => Future[String]) = new TestClass().get

  override def receive: Receive = {
    case url: String => service(url).onComplete(x => println(s"$self : $x"))
  }
}

object SimpleSuccessfulApp extends App {
  val cfg = ConfigFactory.parseString(s"akka.cluster.roles=[TEST]")

    // ENABLE SERIALIZE CHECK
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-messages = on"))
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-creators = on"))

    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.hostname=127.0.0.1"))
    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.port=0"))
    .withFallback(ConfigFactory.load())

  implicit val system = ActorSystem("TestSystem", cfg)
  val actor = system.actorOf(TestActor.props(), TestActor.name)
  actor ! "1"
  actor ! "2"
  actor ! "3"

  System.in.read
}
```
The SimpleSuccessfulApp will work as expected in this case and will print:
```
Actor[akka://TestSystem/user/TestActor#-1500886999] : Success(TEST: 1)
Actor[akka://TestSystem/user/TestActor#-1500886999] : Success(TEST: 3)
Actor[akka://TestSystem/user/TestActor#-1500886999] : Success(TEST: 2)
```

## Use NOT SERIALIZABLE CLASS inside actor will throw exception if you pass the class to constructor of the actor
```scala
class TestClass {
  // THIS IS NOT SERIALIZABLE CLASS.
  def get(request: String): Future[String] = Future.successful("TEST: " + request)
}

object TestFailedActor {
  def props() = Props(classOf[TestFailedActor], new TestClass)
  def name = "TestFailedActor"
}

class TestFailedActor(handler: TestClass) extends Actor {
  import context._

  def service: (String => Future[String]) = handler.get

  override def receive: Receive = {
    case url: String => service(url).onComplete(x => println(s"$self : $x"))
  }
}

object SimpleFailedApp extends App {
  val cfg = ConfigFactory.parseString(s"akka.cluster.roles=[TEST]")

    // ENABLE SERIALIZE CHECK
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-messages = on"))
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-creators = on"))

    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.hostname=127.0.0.1"))
    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.port=0"))
    .withFallback(ConfigFactory.load())

  implicit val system = ActorSystem("TestSystem", cfg)
  val actor = system.actorOf(TestFailedActor.props(), TestFailedActor.name)
  actor ! "1"
  actor ! "2"
  actor ! "3"

  System.in.read
}
```
The SimpleFailedApp will throw expected exception in this case: `java.io.NotSerializableException: No configured serialization-bindings for class [ua.akka.serialization.TestClass]`

## Use SPRAY inside the actor will trow exception always.
```scala
class TestSprayClass()(implicit val context: ActorContext) {
  implicit lazy val ec: ExecutionContext = context.dispatcher

  def pipeline = (
    sendReceive
      ~> unmarshal[String]
    )

  def get(url: String): Future[String] = {
    pipeline {
      Get(url)
    }
  }

}

object TestUnexpectedFailedActor {
  def props() = Props[TestUnexpectedFailedActor]
  def name = "TestUnexpectedFailedActor"
}

class TestUnexpectedFailedActor extends Actor {
  import context._

  def service: (String => Future[String]) = new TestSprayClass()(context).get

  override def receive: Receive = {
    case url: String => service(url).onComplete(x => println(s"$self : $x"))
  }
}


object SimpleUnexpectedFailedApp extends App {
  val cfg = ConfigFactory.parseString(s"akka.cluster.roles=[TEST]")

    // ENABLE SERIALIZE CHECK
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-messages = on"))
    .withFallback(ConfigFactory.parseString("akka.actor.serialize-creators = on"))

    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.hostname=127.0.0.1"))
    .withFallback(ConfigFactory.parseString("akka.remote.netty.tcp.port=0"))
    .withFallback(ConfigFactory.load())

  implicit val system = ActorSystem("TestSystem", cfg)
  val actor = system.actorOf(TestUnexpectedFailedActor.props(), TestUnexpectedFailedActor.name)
  actor ! "1"
  actor ! "2"
  actor ! "3"

  System.in.read
}
```
The SimpleUnexpectedFailedApp will throw unexpected exception `java.io.NotSerializableException: spray.can.HttpExt`.


## To summarize

Thus we have different cases:

- `def service: (String => Future[String]) = new TestClass().get` inside the actor will work fine and don't throw NotSerializableException. This is expected behavior because:
> The actor itself doesn't have to be serializable ...

- `class TestFailedActor(handler: TestClass) extends Actor` will throw NotSerializableException. This is expected behavior too, because:
> ... but the Props and the parameters for the constructor must be serializable.

- But if I change `def service: (String => Future[String]) = new TestClass().get` to `def service: (String => Future[String]) = new TestSprayClass()(context).get` (*Any class that uses Spray*) then actor will throw UNEXPECTED `java.io.NotSerializableException: spray.can.HttpExt` exception.
This case should be equal to first case and the actor should not throw exception because:
> The actor itself doesn't have to be serializable ...


@johanandren please let me know what am I doing wrong. 

If "The actor itself doesn't have to be serializable ..." and works fine with not serializable "TestClass" then I expect that actor will work fine with not serializable "TestSprayClass" too.
