### ISSUE TITLE
Missing Termination on node down or remove

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21419]
Noted in the multi-node cluster tests (locally it seems to pass):

```
must receive Terminated when watched node becomes Down/Removed *** FAILED *** (2 seconds, 347 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message akka://ClusterDeathWatchSpec@a6.moxie:49874/user/subject
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:579)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:575)
[JVM-1]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:737)
[JVM-1]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(ClusterDeathWatchSpec.scala:90)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:341)
[JVM-1]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ClusterDeathWatchSpec.scala:66)
[JVM-1]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ClusterDeathWatchSpec.scala:62)
[JVM-1]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ClusterDeathWatchSpec.scala:62)
```

@drewhk noted that he saw the same happen in `LatencySpec`

**Comment by drewhk** [comment]
Didn't fail for me either locally. Trying out the magic of fuzzing-mode now.

**Comment by drewhk** [comment]
It looks like actor on third node is Terminated (or there is a duplicate Terminate message, impossible to decide without the log). No luck with reproducing yet.

**Comment by patriknw** [comment]
Let's close this and look at it again if it happens again.
