### ISSUE TITLE
Akka http 2.4.9 and 2.4.10 issue with blocking/timeout on Source[ByteString, Any].runWith(StreamConverters.asInputStream())

### ISSUE THREAD

**Issue by tummybunny** [akka/akka#21410]
This is to re-open issue https://github.com/akka/akka/issues/21008 which has been closed although it is still an issue in 2.4.9 and 2.4.10

```scala
import java.io._
import java.nio.file._
import java.util.concurrent.atomic.AtomicInteger
import akka.actor._
import akka.stream._
import akka.stream.scaladsl.StreamConverters
import akka.util.Timeout
import akka.http.scaladsl.model._
import akka.http.scaladsl.model.StatusCodes._
import akka.http.scaladsl._
import akka.http.scaladsl.server._
import akka.http.scaladsl.server.Directives._

object AkkaTest extends App {

  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  implicit val executionContext = system.dispatcher

  def processUpload(formData: Multipart.FormData) = {
    val sources = formData.parts.map(e => e.entity.dataBytes)
    val i = new AtomicInteger(0)
    val f = sources.runForeach { source =>
      val prefix = s"[FILE #${i.incrementAndGet()}]"
      println(s"$prefix START PROCESSING ")
      val inputStream = source.runWith(StreamConverters.asInputStream())
      try {
        println(s"$prefix WRITING")
        val tmp = Files.createTempFile("a", "b")
        Files.copy(inputStream, tmp, StandardCopyOption.REPLACE_EXISTING)
        Files.delete(tmp)
        println(s"$prefix DONE WRITING")
      } finally {
        inputStream.close()
      }
    }
    f
  }

  def processMultiPartData: Route = {
    pathPrefix("upload") {
      (post & entity(as[Multipart.FormData])) { formData =>
        complete {
          processUpload(formData).map { _ =>
            println("*** DONE ****")
            HttpResponse(StatusCodes.OK, entity = s"Data: datasuccessfully processed.")
          }
        }
      }
    }
  }
  val routes = processMultiPartData
  Http().bindAndHandle(handler = routes, interface = "0.0.0.0", port = 9090)
}
```

Executed this command:
```
$ curl "http://localhost:9090/upload" -F "file=@/whatever.zip"
There was an internal server error.
```

Std out:
```
Produces:
09-09-16 10:29:26:297 [default-akka.actor.default-dispatcher-4] [] INFO  a.e.s.Slf4jLogger - Slf4jLogger started
[FILE #1] START PROCESSING 
[FILE #1] WRITING
09-09-16 10:30:20:761 [default-akka.actor.default-dispatcher-9] [] ERROR a.a.ActorSystemImpl - Error during processing of request HttpRequest(HttpMethod(POST),http://localhost:9090/upload,List(User-Agent: curl/7.37.0, Host: localhost:9090, Accept: */*, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Default(multipart/form-data; boundary=------------------------ae1c9b442e9074c1; charset=UTF-8,272 bytes total),HttpProtocol(HTTP/1.1))
java.io.IOException: Timeout on waiting for new data
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply$mcI$sp(InputStreamSinkStage.scala:144) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.io.InputStreamAdapter$$anonfun$read$1.apply(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:109) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:129) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:120) ~[akka-stream_2.11-2.4.9.jar:na]
	at java.nio.file.Files.copy(Files.java:2908) ~[na:1.8.0_45]
	at java.nio.file.Files.copy(Files.java:3027) ~[na:1.8.0_45]
	at AkkaTest$$anonfun$2.apply(HH.scala:32) ~[classes/:na]
	at AkkaTest$$anonfun$2.apply(HH.scala:25) ~[classes/:na]
	at akka.stream.impl.fusing.Map$$anon$5.onPush(Ops.scala:42) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:755) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:657) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:470) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:422) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:602) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:593) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.9.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:528) ~[akka-stream_2.11-2.4.9.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.9.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.9.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [na:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [na:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [na:na]
```

**Comment by johanandren** [comment]
#21008 about a specific bug in one of the stages, this is probably something else although it manifest in an exception looking the same.

**Comment by johanandren** [comment]
`asInputStream` takes a read timeout which is by default 5 seconds, perhaps your filesystem is just slower than that?

**Comment by johanandren** [comment]
Ran the sample locally, it's failing here as well, so we can rule the slow fs out

**Comment by tummybunny** [comment]
absolutely not. The curl command uses a zip file less than 10kb (a zip of a readme.txt) and it timed out after 30 seconds.

Converting it to future is fine, it took less than a second.

Something like this works fine, i.e. converting the ByteSource into Future[IOResult] and flat map it:

```scala

  def processUpload(formData: Multipart.FormData) = {
    val sources = formData.parts.map(e => e.entity.dataBytes)
    val i = new AtomicInteger(0)
    var fileFut: Future[Any] = Future.successful(Unit)
    val f = sources.runForeach { source =>
      val prefix = s"[FILE #${i.incrementAndGet()}]"
      println(s"$prefix START PROCESSING ")
      val tmp = Files.createTempFile("f-", ".tmp")
      val out = Files.newOutputStream(tmp, StandardOpenOption.WRITE)
      fileFut = fileFut.flatMap{ _ => source.runWith(StreamConverters.fromOutputStream(() => out)).map { _ =>
         out.close()
         println(s"$prefix DONE WRITING")
      }}
    }.flatMap( _ => fileFut)
  }
```

**Comment by tummybunny** [comment]
comment above was reply your second comment ;)

**Comment by johanandren** [comment]
Yeah, seems a bit like a deadlock somewhere in the HTTP graph or possibly in the Multipart.FormData unmarshaller.

**Comment by johanandren** [comment]
Ticket moved to github.com/akka/akka-http
Rationale for the move discussed here: akka/akka-meta#27

If you are interested in contributing or tracking this issue, please comment in akka-http instead from now on :-)
