### ISSUE TITLE
FAILED akka.cluster.NodeChurnSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21424]
https://jenkins.akka.io:8498/job/akka-nightly/3671/consoleFull

```
[JVM-2] - must join and remove transient nodes without growing gossip payload *** FAILED *** (26 seconds, 953 milliseconds)
[JVM-2]   Cluster(s).self: false was not true (NodeChurnSpec.scala:84)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-2]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[JVM-2]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[JVM-2]   at akka.cluster.NodeChurnSpec$$anonfun$awaitRemoved$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8$$anonfun$apply$2.apply(NodeChurnSpec.scala:84)
[JVM-2]   at akka.cluster.NodeChurnSpec$$anonfun$awaitRemoved$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$8$$anonfun$apply$2.apply(NodeChurnSpec.scala:84)
```

**Comment by patriknw** [comment]
I started looking at this but noticed that the NodeChurnSpec was disabled because of Artery. I have enabled it again in https://github.com/akka/akka/pull/21902

**Comment by patriknw** [comment]
Let's close since it was long time since it occurred.
We have another for enabling it with Artery. https://github.com/akka/akka/issues/21483
