### ISSUE TITLE
SplitBrainSpec failing with artery

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21431]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/15/consoleFull

```
[JVM-4] - must detect network partition and mark nodes on other side as unreachable and form new cluster *** FAILED *** (25 seconds, 173 milliseconds)
[JVM-4]   TreeSet(akka://SplitBrainSpec@a4.moxie:53956, akka://SplitBrainSpec@a5.moxie:40321, akka://SplitBrainSpec@a5.moxie:46057, akka://SplitBrainSpec@a6.moxie:45144, akka://SplitBrainSpec@a6.moxie:57400) contained element akka://SplitBrainSpec@a4.moxie:53956 (MultiNodeClusterSpec.scala:292)
[JVM-4]   org.scalatest.exceptions.TestFailedException:
[JVM-4]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-4]   at org.scalatest.words.ResultOfNotWordForAny.contain(ResultOfNotWordForAny.scala:475)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeClusterSpec.scala:292)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(MultiNodeClusterSpec.scala:292)
[JVM-4]   at scala.collection.immutable.Set$Set2.foreach(Set.scala:128)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:292)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$1.apply(MultiNodeClusterSpec.scala:292)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$1.apply(MultiNodeClusterSpec.scala:292)
[JVM-4]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
[JVM-4]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
[JVM-4]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:814)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:292)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:290)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:290)
[JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
[JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:814)
[JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:814)
[JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.awaitMembersUp(MultiNodeClusterSpec.scala:290)
[JVM-4]   at akka.cluster.SplitBrainSpec.awaitMembersUp(SplitBrainSpec.scala:49)
[JVM-4]   at akka.cluster.SplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$6.apply$mcV$sp(SplitBrainSpec.scala:91)
[JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:341)
[JVM-4]   at akka.cluster.SplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(SplitBrainSpec.scala:88)
[JVM-4]   at akka.cluster.SplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(SplitBrainSpec.scala:70)
[JVM-4]   at akka.cluster.SplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(SplitBrainSpec.scala:70)
```

**Comment by patriknw** [comment]
@johanandren I took a look at this and it's fairly easy to reproduce with debug logging and then it can be seen that the blackhole is not black, it's leaking. We send the SetThrottle command to the active OutboundTestStages, but the problem is when an association is created after we introduced the blackhole. It will not know about the blackhole. I have an idea of how we should solve this.

**Comment by patriknw** [comment]
@johanandren I didn't see that you had assigned yourself to this before I implemented it now. https://github.com/akka/akka/issues/21449

**Comment by johanandren** [comment]
No worries, I started looking at it but then decided it was not really a "failed" ticket so postponed. Great that you fixed it.
