### ISSUE TITLE
failed: ReplicatorMessageSerializerSpec with Artery

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21466]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/51/consoleText

```
[info] ReplicatorMessageSerializerSpec:
[info] ReplicatorMessageSerializer
[info] - must serialize Replicator messages *** FAILED *** (112 milliseconds)
[info]   DataEnvelope(GSet(Set(a)),Map(UniqueAddress(akka://ReplicatorMessageSerializerSpec@some.host.org:4711,1) -> PruningState(UniqueAddress(akka://ReplicatorMessageSerializerSpec@other.host.org:4711,2),PruningPerformed), UniqueAddress(akka://ReplicatorMessageSerializerSpec@some.host.org:4712,3) -> PruningState(UniqueAddress(akka://ReplicatorMessageSerializerSpec@other.host.org:4711,2),PruningInitialized(Set(akka://ReplicatorMessageSerializerSpec@some.host.org:4711))))) was not equal to DataEnvelope(GSet(Set(a)),Map(UniqueAddress(akka.tcp://ReplicatorMessageSerializerSpec@some.host.org:4711,1) -> PruningState(UniqueAddress(akka.tcp://ReplicatorMessageSerializerSpec@other.host.org:4711,2),PruningPerformed), UniqueAddress(akka.tcp://ReplicatorMessageSerializerSpec@some.host.org:4712,3) -> PruningState(UniqueAddress(akka.tcp://ReplicatorMessageSerializerSpec@other.host.org:4711,2),PruningInitialized(Set(akka.tcp://ReplicatorMessageSerializerSpec@some.host.org:4711))))) (ReplicatorMessageSerializerSpec.scala:48)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.cluster.ddata.protobuf.ReplicatorMessageSerializerSpec.checkSerialization(ReplicatorMessageSerializerSpec.scala:48)
[info]   at akka.cluster.ddata.protobuf.ReplicatorMessageSerializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ReplicatorMessageSerializerSpec.scala:67)
[info]   at akka.cluster.ddata.protobuf.ReplicatorMessageSerializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ReplicatorMessageSerializerSpec.scala:53)
[info]   at akka.cluster.ddata.protobuf.ReplicatorMessageSerializerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ReplicatorMessageSerializerSpec.scala:53)
```

Probably something simple/stupid due to the new enabled serializers

**Comment by drewhk** [comment]
Ah, an extra "akka.tcp" in there. Wasn't this fixed? At least this does not fail for me locally and this looks like should fail deterministically.
