### ISSUE TITLE
FAILED: ConnectionPoolSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21460]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4181/consoleFull

```
[info] - be able to handle 500 pipelined requests with connection termination *** FAILED *** (30 seconds, 408 milliseconds)
[info]   java.lang.RuntimeException: Failed at pipeliningLimit=4, poolFlow=Flow(FlowShape(MapAsyncUnordered.in,MapAsyncUnordered.out), CompositeModule [4b377db9]
[info]   Name: unnamed
[info]   Modules:
[info]     (mapAsyncUnordered) GraphStage(MapAsyncUnordered(16,<function1>)) [12d857f4]
[info]   Downstreams: 
[info]   Upstreams: 
[info]   MatValue: Transform(Ignore))
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$35$$anon$19$$anonfun$36.apply(ConnectionPoolSpec.scala:394)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$35$$anon$19$$anonfun$36.apply(ConnectionPoolSpec.scala:368)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[info]   at akka.http.impl.engine.client.ConnectionPoolSpec$$anonfun$35$$anon$19.<init>(ConnectionPoolSpec.scala:368)
[info]   at akka.http.impl
```

**Comment by patriknw** [comment]
This should be moved to akka-http.
No new http tickets here, please

**Comment by ktoso** [comment]
Moved
