### ISSUE TITLE
failed: ClusterClientSpec with Artery

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21477]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/57/consoleText

```
[JVM-1] - must re-establish connection to receptionist after server restart *** FAILED ***
[JVM-1]   java.lang.AssertionError: timeout (10 seconds) waiting for 1 messages on InfoFilter(Some(akka://ClusterClientSpec@a0.moxie:42157/user/client4),Left(Connected to),false)
[JVM-1]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$33$$anonfun$apply$mcV$sp$34.apply$mcV$sp(ClusterClientSpec.scala:417)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:341)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$33.apply$mcV$sp(ClusterClientSpec.scala:404)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$33.apply(ClusterClientSpec.scala:403)
[JVM-1]   at akka.cluster.client.ClusterClientSpec$$anonfun$1$$anonfun$apply$mcV$sp$32$$anonfun$apply$mcV$sp$33.apply(ClusterClientSpec.scala:403)
```

**Comment by patriknw** [comment]
Note that this is checking some logging, which might be different with Artery. Should be an easy fix.

`waiting for 1 messages on InfoFilter`
