### ISSUE TITLE
Buffer underflow in the decoder

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21488]
Happens consistently when I run `AeronStreamConsistencySpec` locally. 
```
[JVM-2] java.nio.BufferUnderflowException
[JVM-2] 	at java.nio.Buffer.nextGetIndex(Buffer.java:500)
[JVM-2] 	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:249)
[JVM-2] 	at akka.remote.artery.EnvelopeBuffer.parseHeader(BufferPool.scala:398)
[JVM-2] 	at akka.remote.artery.Decoder$$anon$2.onPush(Codecs.scala:291)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
[JVM-2] 	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
[JVM-2] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
[JVM-2] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
[JVM-2] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-2] 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-2] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-2] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-2] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-2] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
I can confirm that this is failing for me also

**Comment by patriknw** [comment]
@johanandren  I know what this is. It's because we are starting sbt with `-Dakka.remote.artery.enabled=on`. That test is supposed to be run with enabled=off. It's testing raw Aeron streams.

**Comment by ktoso** [comment]
Uff, glad it wasn't a bug in the envelope decoding :)
