### ISSUE TITLE
failed: ArteryRemoteNodeDeathWatchFastSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21500]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7469/consoleText

```
[JVM-1] [INFO] [09/20/2016 12:42:01.733] [ScalaTest-main-running-ArteryRemoteNodeDeathWatchFastMultiJvmNode1] [ArteryRemoteNodeDeathWatchFastMultiJvmNode1(akka://RemoteNodeDeathWatchSpec)] exit third
[JVM-1] - must cleanup when watching node crash *** FAILED *** (5 seconds, 396 milliseconds)
[JVM-1]   java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
[JVM-1]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[JVM-1]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[JVM-1]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[JVM-1]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-1]   at scala.concurrent.Await$.result(package.scala:190)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec$AwaitHelper.await(MultiNodeSpec.scala:266)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23$$anonfun$apply$mcV$sp$25.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:446)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:341)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply$mcV$sp(RemoteNodeDeathWatchSpec.scala:437)
[JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$23.apply(RemoteNodeDeathWatchSpec.scala:425)
```

**Comment by johanandren** [comment]
Weird. The failure is actually about waiting for `testConductor.exit(third, 0).await` which should just system.exit(0) the node, so not really anything artery-related as far as I can see, unless the shutdown hook took longer than 5 seconds.

**Comment by drewhk** [comment]
deadlock in shutdown hook?

**Comment by johanandren** [comment]
Sounds plausible. I can reproduce on my slow server so I'll see what I can figure out.

**Comment by drewhk** [comment]
look at AFR events (or add new ones if necessary)

**Comment by patriknw** [comment]
yes, we wait up to 20 seconds in the shutdown hook. Not sure what would happen with open things if we return too early? At least, files might not be deleted.

One source for blocking is the `materializing` CountDownLatch for the control stream.
That might perhaps not be counted down if materialization fails (e.g. because of shutting down).

**Comment by johanandren** [comment]
Nah, looks like the shutdown hook completed successfully (thanks AFR!), I see two of these that I'm not sure if they are significant though:

```
[JVM-2] [DEBUG] [09/23/2016 13:07:29.871] [RemoteNodeDeathWatchSpec-akka.remote.default-remote-dispatcher-6] [akka.remote.artery.ArteryTransport(akka://RemoteNodeDeathWatchSpec)] onUnavailableImage from 127.0.0.1:63995 session -1699956330
[JVM-2] [DEBUG] [09/23/2016 13:07:29.881] [RemoteNodeDeathWatchSpec-akka.remote.default-remote-dispatcher-8] [akka.remote.artery.ArteryTransport(akka://RemoteNodeDeathWatchSpec)] onUnavailableImage from 127.0.0.1:63995 session -1699956331
```

Could that block JVM exit?

**Comment by drewhk** [comment]
can it also have a shutdownHook that we don't know about??

**Comment by patriknw** [comment]
Aeron has no shutdown hook (I searched its sources)

the `onUnavailableImage` logging should not be the reason

**Comment by johanandren** [comment]
Ah, but wait, it did take more than 5 seconds to shutdown though.

**Comment by johanandren** [comment]
AFR output: 
```
[2016-09-23T11:07:29.710532129Z]    8 Transport: KillSwitch pulled       | 
[2016-09-23T11:07:29.796645525Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.796779029Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.798175204Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.798274669Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.798810212Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.798851185Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:51276
[2016-09-23T11:07:29.872952484Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:49305
[2016-09-23T11:07:29.883033380Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:49305
[2016-09-23T11:07:29.974019743Z]    9 Transport: Stopped                 | 
[2016-09-23T11:07:29.974757537Z]   10 Transport: Aeron errorLog task sto | 
[2016-09-23T11:07:36.386044690Z]   11 Transport: Media file deleted      | 
[2016-09-23T11:07:36.386093848Z]   12 Transport: Flight recorder closed  | 
```
