### ISSUE TITLE
failed: ClusterSingletonManagerLeaveSpec with Artery

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21509]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/94/consoleText

```
[JVM-1] - must hand-over to new instance *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for stopped
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:373)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-1]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(ClusterSingletonManagerLeaveSpec.scala:117)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:341)
[JVM-1]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ClusterSingletonManagerLeaveSpec.scala:116)
[JVM-1]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterSingletonManagerLeaveSpec.scala:96)
[JVM-1]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterSingletonManagerLeaveSpec.scala:96)
```

**Comment by patriknw** [comment]
failed in next build also https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/95/consoleText
might be an regression I introduced in https://github.com/akka/akka/pull/21492
