### ISSUE TITLE
FAILED: DDataClusterShardingLeavingMultiJvm in nightly

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#21518]
See https://jenkins.akka.io:8498/job/akka-nightly/3711:

```
[JVM-2] - must recover after leaving coordinator node *** FAILED ***
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:454)
[JVM-2]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13$$anonfun$apply$mcV$sp$17.apply(ClusterShardingLeavingSpec.scala:208)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13$$anonfun$apply$mcV$sp$17.apply(ClusterShardingLeavingSpec.scala:204)
[JVM-2]   at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
[JVM-2]   at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply$mcV$sp(ClusterShardingLeavingSpec.scala:204)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply(ClusterShardingLeavingSpec.scala:202)
```

**Comment by patriknw** [comment]
I looked at this, but I was not able to find an explanation. It seems like the region on the second node continues to forward messages to the first node even though the first node has been removed from the cluster. Ordinary `watch` between the regions should take care of that.

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4118/consoleFull
