### ISSUE TITLE
FAILED RemoteSendConsistencyWithThreeLanesSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21529]

**Comment by johanandren** [comment]
I need to get that PC-drivers license... anyways.

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7501/consoleFull
```
[info] - must be able to identify a remote actor and ping it *** FAILED *** (3 seconds, 122 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(RemoteSendConsistencySpec.scala:57)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(RemoteSendConsistencySpec.scala:48)
```

**Comment by patriknw** [comment]
No reply within 3 seconds. No other information in the logs. I have started a repeat job with debug logging: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/

**Comment by patriknw** [comment]
That was quick: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/12389/consoleText

**Comment by patriknw** [comment]
After increasing the timeout for the first message there were no more failures. Running on repeat (every 5th min) whole day yesterday. I'll PR that change.
