### ISSUE TITLE
catch exception in AeronSink postStop

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21538]
I think we should catch this exception, since it's only a symptom of something else. This occurred when I killed the media driver.

```
[ERROR] [09/23/2016 14:36:57.762] [ClusterSystem-akka.remote.default-remote-dispatcher-6] [akka://ClusterSystem/system/StreamSupervisor-0/remote-0-0-unknown-operation] Error during postStop in [akka.remote.artery.AeronSource@65a30dc1]: Driver is inactive
io.aeron.exceptions.DriverTimeoutException: Driver is inactive
       	at io.aeron.ClientConductor.verifyDriverIsActive(ClientConductor.java:299)
       	at io.aeron.ClientConductor.releaseSubscription(ClientConductor.java:177)
       	at io.aeron.Subscription.close(Subscription.java:268)
       	at akka.remote.artery.AeronSource$$anon$1.postStop(AeronSource.scala:99)
```

The root cause is logged as:
```
[ERROR] [09/23/2016 14:36:56.697] [aeron-client-conductor] [akka.remote.artery.ArteryTransport(akka://ClusterSystem)] Fatal Aeron error DriverTimeoutException. Have to terminate ActorSystem because it lost contact with the external Aeron media driver. Possible configuration properties to mitigate the problem are 'client-liveness-timeout' or 'driver-timeout'. Driver has been inactive for over 20000ms
io.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 20000ms
       	at io.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:291)
       	at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:378)
```

**Comment by patriknw** [comment]
More important, it caused the ActorSystem not not complete the shutdown. That is because we don't complete the Future in the sink when that exception is thrown.
