### ISSUE TITLE
failed: ClusterShardingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21535]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/121/consoleText

```
[JVM-4] - must recover entities upon restart *** FAILED ***
[JVM-4]   None was equal to None (ClusterShardingSpec.scala:713)
```

**Comment by patriknw** [comment]
This can be an timing issue in the test. Perhaps put that check in an awaitAssert retry:

```
        val counter1 = system.actorSelection(lastSender.path.parent / "1")
        counter1 ! Identify(2)
        expectMsgType[ActorIdentity](3 seconds).ref should not be (None)
```

**Comment by patriknw** [comment]
Here is a new one, not exactly the same I think.
```
[JVM-2] - must recover after journal failure *** FAILED ***
[JVM-2]   java.lang.AssertionError: assertion failed: expected Value(21,1), found Value(21,4)
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:388)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-2]   at akka.cluster.sharding.ClusterShardingFailureSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$12.apply$mcV$sp(ClusterShardingFailureSpec.scala:216)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:345)
[JVM-2]   at akka.cluster.sharding.ClusterShardingFailureSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8.apply$mcV$sp(ClusterShardingFailureSpec.scala:199)
[JVM-2]   at akka.cluster.sharding.ClusterShardingFailureSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8.apply(ClusterShardingFailureSpec.scala:176)
[JVM-2]   at akka.cluster.sharding.ClusterShardingFailureSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8.apply(ClusterShardingFailureSpec.scala:176)
```

https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/165/consoleText
