### ISSUE TITLE
FAILED LatencySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21580]
Seems to fail consistently (three separate runs fails). So something introduced yesterday (likely the  compression table version as byte PR #20872)

```
[JVM-1] - must be low for rate-1000-size-1k, at 1000 msg/s, payloadSize = 1000 *** FAILED *** (40 seconds, 26 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (40 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$p#-975612264]
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:405)
[JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:814)
[JVM-1]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
[JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:814)
[JVM-1]   at akka.remote.artery.LatencySpec$$anonfun$test$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(LatencySpec.scala:312)
[JVM-1]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[JVM-1]   at akka.remote.artery.LatencySpec$$anonfun$test$1.apply$mcV$sp(LatencySpec.scala:262)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:345)
[JVM-1]   at akka.remote.artery.LatencySpec.test(LatencySpec.scala:242)
```

**Comment by johanandren** [comment]
Local repeat failure with debug enabled (I changed the starting version of the tables to 126 to get to the wraparound faster, but I don't think that is relevant, it seemed to wraparound just fine and the error happens much later)
[latencyspecfail.txt](https://github.com/akka/akka/files/497640/latencyspecfail.txt)

**Comment by johanandren** [comment]
Table advertisement just before it fails:

Sending side: 
```
CompressionTable(
  3798165412206995208,
  25,
  Map(
    Actor[akka://LatencySpec/] -> 0,
    Actor[akka://LatencySpec@localhost:54594/system/testActor-1#-1515781731] -> 1,
    Actor[akka://LatencySpec@localhost:54594/user/$g#377434784] -> 2,
    Actor[akka://LatencySpec@localhost:54594/user/$f#1530599489] -> 3,
    Actor[akka://LatencySpec@localhost:54594/user/$e#2038979534] -> 4,
    Actor[akka://LatencySpec@localhost:54594/user/$m#884569048] -> 5,
    Actor[akka://LatencySpec@localhost:54594/user/$l#-77446432] -> 6, 
    Actor[akka://LatencySpec@localhost:54594/user/$b#46608642] -> 7,
    Actor[akka://LatencySpec/user/echo#-1807080855] -> 8,
    Actor[akka://LatencySpec@localhost:54594/user/$c#-194976208] -> 9,
    Actor[akka://LatencySpec@localhost:54594/user/$d#-2041235228] -> 10,
    Actor[akka://LatencySpec@localhost:54594/user/$i#-1892953194] -> 11,
    Actor[akka://LatencySpec@localhost:54594/user/$h#-1376519049] -> 12,
    Actor[akka://LatencySpec@localhost:54594/user/$j#-811258159] -> 13, 
    Actor[akka://LatencySpec@localhost:54594/user/$k#-1266403792] -> 14
    Actor[akka://LatencySpec@localhost:54594/user/$n#-1262281881] -> 15))
```

receiving side:
```
CompressionTable(
  3798165412206995208,
  25,
  Map(
    Actor[akka://LatencySpec@localhost:53175/] -> 0,
    Actor[akka://LatencySpec/system/testActor-1#-1515781731] -> 1,
    Actor[akka://LatencySpec/user/$g#377434784] -> 2,
    Actor[akka://LatencySpec/user/$f#1530599489] -> 3,
    Actor[akka://LatencySpec/user/$e#2038979534] -> 4,
    Actor[akka://LatencySpec/user/$m#884569048] -> 5,
    Actor[akka://LatencySpec/user/$l#-77446432] -> 6,
    Actor[akka://LatencySpec/user/$b#46608642] -> 7,
    Actor[akka://LatencySpec@localhost:53175/user/echo#-1807080855] -> 8,
    Actor[akka://LatencySpec/user/$c#-194976208] -> 9,
    Actor[akka://LatencySpec/user/$d#-2041235228] -> 10,
    Actor[akka://LatencySpec/user/$i#-1892953194] -> 11,
    Actor[akka://LatencySpec/user/$h#-1376519049] -> 12,
    Actor[akka://LatencySpec/user/$j#-811258159] -> 13,
    Actor[akka://LatencySpec/user/$k#-1266403792] -> 14,
    Actor[akka://LatencySpec/user/$n#-1262281881] -> 15))
```

Note entry 8(!!)

**Comment by johanandren** [comment]
Ok, nothing weird with compressing local actorrefs, nvm my last comment.

**Comment by johanandren** [comment]
Patrik likely figured it out
> I think it is the bug. The test assumes no message loss, i.e. the actor will stop when `count ==  totalMessages`. This will cause dropping a few messages when the version is wrapping around. Let's change to `if (math.abs(incomingTableVersion - activeVersion) > 1)`
> that was not the right condition, but you get the point
