### ISSUE TITLE
FAILED akka.remote.artery.compress.CompressionIntegrationSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21616]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/490/consoleFull

```
[info] - wrap around *** FAILED *** (1 second, 453 milliseconds)
[info]   103 did not equal 105 (CompressionIntegrationSpec.scala:306)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply$mcV$sp(CompressionIntegrationSpec.scala:306)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/496/consoleFull

Different failure though:
```
[ERROR] [10/07/2016 07:58:38.450] [ArteryMultiNodeSpec-remote-2-akka.actor.default-dispatcher-2] [TaskInvocation] requirement failed: Compression table should start allocating from 0, yet lowest allocated id was 1
java.lang.IllegalArgumentException: requirement failed: Compression table should start allocating from 0, yet lowest allocated id was 1
	at scala.Predef$.require(Predef.scala:224)
	at akka.remote.artery.compress.CompressionTable.invert(CompressionTable.scala:30)
	at akka.remote.artery.compress.InboundCompression.runNextTableAdvertisement(InboundCompressions.scala:416)
	at akka.remote.artery.compress.InboundCompression$$anonfun$1.apply$mcV$sp(InboundCompressions.scala:291)
	at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:78)
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:104)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info] - wrap around *** FAILED *** (3 seconds, 182 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsgClass waiting for class akka.remote.artery.compress.CompressionProtocol$Events$ReceivedActorRefCompressionTable
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:454)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply$mcV$sp(CompressionIntegrationSpec.scala:299)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3.apply(CompressionIntegrationSpec.scala:262)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3765/consoleFull
