### ISSUE TITLE
akka-http hi level API example fails

### ISSUE THREAD

**Issue by ac2epsilon** [akka/akka#21623]
build.sbt - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
name := "WS1"
version := "1.0"
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
  "com.typesafe.akka" % "akka-stream-experimental_2.11" % "2.0.5",
  "com.typesafe.akka" % "akka-http-experimental_2.11" % "2.4.11"
  )
scalacOptions ++= Seq("-unchecked", "-deprecation", "-Xcheckinit", "-encoding", "utf8", "-feature")

code: (reference example) - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.{ContentTypes, HttpEntity}
import akka.http.scaladsl.server.Directives._
import akka.stream.ActorMaterializer
import scala.io.StdIn
 
object WebServer {
  def main(args: Array[String]) {
    implicit val system = ActorSystem()
    implicit val materializer = ActorMaterializer()
    // needed for the future flatMap/onComplete in the end
    implicit val executionContext = system.dispatcher
 
    val route =
      get {
        pathSingleSlash {
          complete(HttpEntity(ContentTypes.`text/html(UTF-8)`,"<html><body>Hello world!</body></html>"))
        } ~
          path("ping") {
            complete("PONG!")
          } ~
          path("crash") {
            sys.error("BOOM!")
          }
      }
 
    // `route` will be implicitly converted to `Flow` using `RouteResult.route2HandlerFlow`
    val bindingFuture = Http().bindAndHandle(route, "localhost", 9001)
    println(s"Server online at http://localhost:8080/\nPress RETURN to stop...")
    StdIn.readLine() // let it run until user presses return
    bindingFuture
      .flatMap(_.unbind()) // trigger unbinding from the port
      .onComplete(_ => system.terminate()) // and shutdown when done
  }
} 

log - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[info] Running WebServer 
[error] (run-main-0) java.lang.NoSuchMethodError: akka.stream.impl.ConstantFun$.scalaAnyTwoToNone()Lscala/Function2;
java.lang.NoSuchMethodError: akka.stream.impl.ConstantFun$.scalaAnyTwoToNone()Lscala/Function2;
	at akka.http.impl.model.parser.HeaderParser$.Settings$default$3(HeaderParser.scala:178)
	at akka.http.impl.model.parser.HeaderParser$.<init>(HeaderParser.scala:194)
	at akka.http.impl.model.parser.HeaderParser$.<clinit>(HeaderParser.scala)
	at akka.http.scaladsl.model.headers.ProductVersion$.parseMultiple(ProductVersion.scala:31)
	at akka.http.scaladsl.model.headers.User$minusAgent$.apply(headers.scala:903)
	at akka.http.impl.settings.ClientConnectionSettingsImpl$$anonfun$fromSubConfig$1.apply(ClientConnectionSettingsImpl.scala:40)
	at akka.http.impl.settings.ClientConnectionSettingsImpl$$anonfun$fromSubConfig$1.apply(ClientConnectionSettingsImpl.scala:40)
	at scala.Option.map(Option.scala:146)
	at akka.http.impl.settings.ClientConnectionSettingsImpl$.fromSubConfig(ClientConnectionSettingsImpl.scala:40)
	at akka.http.impl.settings.ConnectionPoolSettingsImpl$.fromSubConfig(ConnectionPoolSettingsImpl.scala:44)
	at akka.http.impl.settings.ConnectionPoolSettingsImpl$.fromSubConfig(ConnectionPoolSettingsImpl.scala:35)
	at akka.http.impl.util.SettingsCompanion.apply(SettingsCompanion.scala:47)
	at akka.http.scaladsl.settings.ConnectionPoolSettings$.apply(ConnectionPoolSettings.scala:48)
	at akka.http.scaladsl.settings.ConnectionPoolSettings$.apply(ConnectionPoolSettings.scala:47)
	at akka.http.scaladsl.settings.SettingsCompanion$class.apply(SettingsCompanion.scala:16)
	at akka.http.scaladsl.settings.ConnectionPoolSettings$.apply(ConnectionPoolSettings.scala:47)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:49)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:785)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:661)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:745)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.http.scaladsl.Http$.apply(Http.scala:780)
	at WebServer$.main(WSServer.scala:29)
	at WebServer.main(WSServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by ktoso** [comment]
Don't mix versions please.
2.0-experimental (!) is completely different than 2.4.11, please use:

```
"com.typesafe.akka" % "akka-stream_2.11" % "2.4.11",
"com.typesafe.akka" % "akka-http-experimental_2.11" % "2.4.11"

```
