### ISSUE TITLE
failed: typed.ActorContextSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21653]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7613/consoleText

```
[ERROR] [10/10/2016 20:47:57.868] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-2] [akka://TypedSpec_AdaptedSystem_class/user/basicAdapted-ctx31] timeout of 3 seconds expired while waiting for a message
akka.typed.StepWise$$anon$2: timeout of 3 seconds expired while waiting for a message
    at akka.typed.ActorContextSpec$Tests$MessageStep.stimulate(ActorContextSpec.scala:238)
    at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:498)
    at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:493)
    at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:200)
    at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:192)
    at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:111)
    at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:110)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7876

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7885/consoleFull
