### ISSUE TITLE
Change in ContextAware in 2.4.11

### ISSUE THREAD

**Issue by durban** [akka/akka#21652]
There seems to be a change in the implementation of `akka.typed.ScalaDSL.ContextAware` in 2.4.11. It's unclear to me whether this was intentional. Code similar to [this](https://github.com/durban/akka-typed-examples/blob/35f03e204e4055a2583cc5459dd62880290857a6/src/main/scala/com/example/actors/CtxAware.scala), used to work before. In 2.4.11 it throws the following exception:
```
[ERROR] [10/11/2016 10:05:26.536] [boo-akka.actor.default-dispatcher-14] [akka://boo/user/b] ContextAware must receive PreStart as first message (got Msg(akka.typed.adapter.ActorContextAdapter@1f5884e9,2))
java.lang.IllegalStateException: ContextAware must receive PreStart as first message (got Msg(akka.typed.adapter.ActorContextAdapter@1f5884e9,2))
        at akka.typed.ScalaDSL$$anonfun$ContextAware$1.apply(ScalaDSL.scala:444)
        at akka.typed.ScalaDSL$$anonfun$ContextAware$1.apply(ScalaDSL.scala:442)
        at akka.typed.ScalaDSL$FullTotal.message(ScalaDSL.scala:178)
        at akka.typed.adapter.ActorAdapter$$anonfun$receive$1.applyOrElse(ActorAdapter.scala:32)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.typed.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:9)                                                                                                               
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)                                                                                                                          
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)                                                                                                                                  
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)                                                                                                                           
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)                                                                                                                                      
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)                                                                                                                                     
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Note, that it seems to be possible to work around this exception like [this](https://github.com/durban/akka-typed-examples/blob/54ec06077671cdf330baee6bafcf25a4c4a2ebdf/src/main/scala/com/example/actors/CtxAware2.scala). Is this how `ContextAware` is supposed to be used now?

**Comment by patriknw** [comment]
cc @rkuhn

**Comment by rkuhn** [comment]
Sorry for the delay, which is in part due to my inability to find a clear reasoning. The change was made to be more consistent in that behavior decorators need to be properly “started”, there is a new facility `Behavior.preStart` to do this correctly. On the other hand I am uncertain of the value of this consistency beyond, well, being consistent.

What I like about the situation is that it forced you to make your implementation more allocation efficient by reusing and not always re-extracting the ActorContext. So I’m leaning towards just leaving it as is, perhaps with improved documentation.

What do others think?

**Comment by durban** [comment]
I can live with the current (2.4.11) behavior. Improved documentation would certainly be good.

**Comment by patriknw** [comment]
I think this is or will be obsolete with the new api.
