### ISSUE TITLE
FAILED: FramingSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21673]
https://jenkins.akka.io:8498/job/akka-nightly/3775/consoleFull

```
--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must work with various byte orders, frame lengths and offsets *** FAILED *** (5 seconds, 944 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$4.apply(FramingSpec.scala:182)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1$$anonfun$apply$mcVI$sp$4.apply(FramingSpec.scala:174)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply$mcVI$sp(FramingSpec.scala:174)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply(FramingSpec.scala:173)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3$$anonfun$apply$1.apply(FramingSpec.scala:173)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3.apply(FramingSpec.scala:173)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcVI$sp$3.apply(FramingSpec.scala:172)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcVI$sp(FramingSpec.scala:172)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply$mcV$sp(FramingSpec.scala:171)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(FramingSpec.scala:171)
[info]   at akka.stream.scaladsl.FramingSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(FramingSpec.scala:171)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:57)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
```

**Comment by johanandren** [comment]
GC pause of 3148.6ms explains it.

**Comment by ktoso** [comment]
So we should increase it or something, because it failed again (in validation now) ;-)

**Comment by johanandren** [comment]
oh, so the spec does something that causes the gc you mean?

**Comment by ktoso** [comment]
Timeout is too low simply it seems.
