### ISSUE TITLE
FAILED: CircuitBreakerSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21719]
```
[info] - must increase the reset timeout after it transits to open again *** FAILED *** (1 second, 46 milliseconds)
[info]   false did not equal true (CircuitBreakerSpec.scala:234)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info]   at akka.pattern.CircuitBreakerSpec$$anonfun$7$$anonfun$apply$mcV$sp$38.apply(CircuitBreakerSpec.scala:234)
[info]   at akka.pattern.CircuitBreakerSpec$$anonfun$7$$anonfun$apply$mcV$sp$38.apply(CircuitBreakerSpec.scala:216)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4294/consoleFull

**Comment by ortigali** [comment]
[breaker.openLatch](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala#L229) should be reseted before using it second time

**Comment by ortigali** [comment]
There are many such type of codes in CircuitBreakerSpec test. May I make PR for all?

**Comment by patriknw** [comment]
Excellent if you can help out here, @ortigali
