### ISSUE TITLE
FAILED: ClusterShardingSpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21718]
```
[JVM-5] - must recover coordinator state after coordinator crash *** FAILED ***
[JVM-5]   java.lang.RuntimeException: barrier failed: after-8
[JVM-5]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-5]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-5]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-5]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-5]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-5]   at a
```

https://jenkins.akka.io:8498/job/akka-nightly/3797/consoleFull

**Comment by drewhk** [comment]
Might, or might not be related to https://github.com/akka/akka/issues/21535
