### ISSUE TITLE
FAILED: ClusterStressSpec (Artery tests)

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21735]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/233/consoleFull

```
[JVM-13] - must join nodes one-by-one to large cluster *** FAILED *** (35 seconds, 19 milliseconds)
[JVM-13]   12 did not equal 13 (MultiNodeClusterSpec.scala:310)
[JVM-13]   org.scalatest.exceptions.TestFailedException:
[JVM-13]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-13]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:310)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:310)
[JVM-13]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
[JVM-13]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
[JVM-13]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:814)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:310)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:307)
[JVM-13]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:307)
[JVM-13]   at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
[JVM-13]   at akka.testkit.TestKit.within(TestKit.scala:814)
[JVM-13]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[JVM-13]   at akka.testkit.TestKit.within(TestKit.scala:814)
[JVM-13]   at
```

**Comment by patriknw** [comment]
some unexpected UNREACHABLE during the joining

**Comment by patriknw** [comment]
This is an duplicate of https://github.com/akka/akka/issues/21810
