### ISSUE TITLE
FAILED: LatencySpec

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21751]
https://jenkins.akka.io:8498/job/akka-multi-node/1803/consoleFull

```
[JVM-1] - must be low for rate-20000-size-100, at 20000 msg/s, payloadSize = 100 *** FAILED *** (22 seconds, 29 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (22 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$f#812078036]
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:405)
[JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:814)
[JVM-1]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
[JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:814)
[JVM-1]   at akka.remote.artery.LatencySpec$$anonfun$test$1$$anonfun$apply$mcV$sp$1.apply$mcVI$sp(LatencySpec.scala:312)
[JVM-1]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[JVM-1]   at akka.remote.artery.LatencySpec$$anonfun$test$1.apply$mcV$sp(LatencySpec.scala:262)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:345)
[JVM-1]   at akka.remote.artery.LatencySpec.test(LatencySpec.scala:242)
[JVM-1]   at akka.remote.artery.LatencySpec$$anonfun$2$$anonfun$apply$mcV$sp$4$$anonfun$apply$1.apply$mcV$sp(LatencySpec.scala:340)
[JVM-1]   at 
```

**Comment by drewhk** [comment]
Have not happened since a while, closing.
