### ISSUE TITLE
FAILED: SystemMessageDeliverySpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#21799]
Different failure than previously: https://github.com/akka/akka/issues/21331

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4327/consoleFull

```
[info] - must be flushed on shutdown *** FAILED *** (5 seconds, 334 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg: Terminated Actor[akka://systemC@localhost:34299/user/echo#1151553699]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:405)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:814)
[info]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
[info]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:814)
[info]   at akka.remote.artery.SystemMessageDeliverySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(SystemMessageDeliverySpec.scala:146)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/3859/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.4/25

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5040/
