### ISSUE TITLE
No elements passed in the last 1 minute.

### ISSUE THREAD

**Issue by chauhraj** [akka/akka#21818]
In `akka-http v2.4.11`, I got this following exception:-

`
java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
        at akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
        at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
        at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
        at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
` 
I am not doing anything fancy but just calling Source.single(request) to akka http server. In my case, akka-stream is just a blackbox.

Under what circumstances, will I see this error?

However, when this exception happened, I also see another exception that occurred prior to this.

akka.stream.StreamTcpException: Tcp command [Connect(:,None,List(),Some(10 seconds),true)] failed`

Can this exception manifest the TimeoutException? Strangely, StreamTcpException doesn't have any Stacktrace. Besides, I cannot reproduce any of the above errors. So, I am clueless when it may happen. I do not see any exceptions in my server logs.

> I see a similar [issue](https://github.com/akka/akka/issues/18982) filed for v2.4.3 but that issue was closed. I didn't know how to reopen the existing one so created a new one.

**Comment by johanandren** [comment]
Hi @chauhraj, the Akka HTTP project has split of into a separate repository, please report over here instead https://github.com/akka/akka-http/issues

Thanks!
