### ISSUE TITLE
ClusterSingletonManagerLeaveSpec with artery

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21823]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/261/consoleFull

```
[JVM-3] - must hand-over to new instance *** FAILED ***
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for preStart
[JVM-3]   at scala.Predef$.assert(Predef.scala:170)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-3]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-3]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$13.apply$mcV$sp(ClusterSingletonManagerLeaveSpec.scala:167)
```

**Comment by patriknw** [comment]
I see no reason why this would be different for Artery, so assuming it is fixed by https://github.com/akka/akka/issues/21847
