### ISSUE TITLE
TcpSpec: must handle when connection actor terminates unexpectedly 

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21839]
https://jenkins.akka.io:8498/job/akka-nightly/3870/consoleFull

```[WARN] [11/14/2016 22:06:14.000] [default-akka.actor.default-dispatcher-11] [akka://default/system/IO-TCP/selectors/$a/*] received dead letter from Actor[akka://default/deadLetters]: Kill
[INFO] [11/14/2016 22:06:14.000] [default-akka.actor.default-dispatcher-6] [akka://default/system/IO-TCP/selectors/$a/*] Message [akka.actor.Kill$] from Actor[akka://default/deadLetters] to Actor[akka://default/system/IO-TCP/selectors/$a/*] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must handle when connection actor terminates unexpectedly *** FAILED *** (7 seconds, 43 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100 milliseconds between each query. (TcpSpec.scala:414)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Future
```

**Comment by BayStallion** [comment]
I'd like to take this one.

**Comment by ktoso** [comment]
Thanks, please go ahead :)

**Comment by BayStallion** [comment]
@drewhk Can you give more context on this? How often did you see this happen, what's the easiest way to reproduce it? My first naive attempt to do so by running TcpSpec tests did not lead me anywhere: the tests passed without any exceptions.
