### ISSUE TITLE
sample project akka-sample-camel-scala  run error

### ISSUE THREAD

**Issue by epiphyllum** [akka/akka#21837]
```
17:26:12.643 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.13.4 (CamelContext: some-system) is starting
17:26:12.644 [some-system-akka.actor.default-dispatcher-2] DEBUG o.a.camel.impl.DefaultCamelContext - Using ClassResolver=org.apache.camel.impl.DefaultClassResolver@72f4aaec, PackageScanClassResolver=org.apache.camel.impl.DefaultPackageScanClassResolver@14959c17, ApplicationContextClassLoader=URLClassLoader with NativeCopyLoader with RawResources(
  urls = List(/Users/hary/workspace/scala/akka-samples/akka-sample-camel-scala/target/scala-2.11/classes, /Users/hary/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar, /Users/hary/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.11.jar, /Users/hary/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar, /Users/hary/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar, /Users/hary/.ivy2/cache/com.typesafe.akka/akka-camel_2.11/jars/akka-camel_2.11-2.4.11.jar, /Users/hary/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4.11.jar, /Users/hary/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.16.jar, /Users/hary/.ivy2/cache/org.apache.camel/camel-core/bundles/camel-core-2.13.4.jar, /Users/hary/.ivy2/cache/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.2.6.jar, /Users/hary/.ivy2/cache/org.apache.camel/camel-jetty/bundles/camel-jetty-2.10.3.jar, /Users/hary/.ivy2/cache/org.apache.camel/camel-http/bundles/camel-http-2.10.3.jar, /Users/hary/.ivy2/cache/org.apache.geronimo.specs/geronimo-servlet_2.5_spec/jars/geronimo-servlet_2.5_spec-1.1.2.jar, /Users/hary/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar, /Users/hary/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar, /Users/hary/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.6.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-server/jars/jetty-server-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/javax.servlet/servlet-api/jars/servlet-api-2.5.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-continuation/jars/jetty-continuation-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-http/jars/jetty-http-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-io/jars/jetty-io-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-util/jars/jetty-util-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-security/jars/jetty-security-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-servlet/jars/jetty-servlet-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-servlets/jars/jetty-servlets-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-client/jars/jetty-client-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.eclipse.jetty/jetty-jmx/jars/jetty-jmx-7.5.4.v20111024.jar, /Users/hary/.ivy2/cache/org.apache.camel/camel-quartz/bundles/camel-quartz-2.10.3.jar, /Users/hary/.ivy2/cache/org.quartz-scheduler/quartz/jars/quartz-1.8.5.jar, /Users/hary/.ivy2/cache/javax.transaction/jta/jars/jta-1.1.jar, /Users/hary/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar, /Users/hary/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.7.jar, /Users/hary/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.0.7.jar),
  parent = java.net.URLClassLoader@3cf0c06a,
  resourceMap = Set(app.class.path, boot.class.path),
  nativeTemp = /var/folders/ng/cn1t76jx2xl9jzsrw6jysjg40000gn/T/sbt_c18a749d
)
17:26:12.645 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.camel.impl.DefaultCamelContext - StreamCaching is enabled on CamelContext: some-system
17:26:12.647 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.c.m.DefaultManagementStrategy - JMX is disabled
17:26:12.654 [some-system-akka.actor.default-dispatcher-2] DEBUG o.a.c.impl.SharedProducerServicePool - Starting service pool: org.apache.camel.impl.SharedProducerServicePool@2ed4fa85
17:26:12.655 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.camel.impl.DefaultCamelContext - AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
17:26:12.659 [some-system-akka.actor.default-dispatcher-2] DEBUG o.a.c.i.DefaultStreamCachingStrategy - Created spool directory: /var/folders/ng/cn1t76jx2xl9jzsrw6jysjg40000gn/T/camel/camel-tmp-835f0118-afe5-475e-9288-8347c306e355
17:26:12.660 [some-system-akka.actor.default-dispatcher-2] DEBUG o.a.c.i.DefaultStreamCachingStrategy - StreamCaching configuration DefaultStreamCachingStrategy[spoolDirectory=/var/folders/ng/cn1t76jx2xl9jzsrw6jysjg40000gn/T/camel/camel-tmp-835f0118-afe5-475e-9288-8347c306e355, spoolChiper=null, spoolThreshold=131072, spoolUsedHeapMemoryThreshold=0, bufferSize=4096, anySpoolRules=false]
17:26:12.660 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.c.i.DefaultStreamCachingStrategy - StreamCaching in use with spool directory: /var/folders/ng/cn1t76jx2xl9jzsrw6jysjg40000gn/T/camel/camel-tmp-835f0118-afe5-475e-9288-8347c306e355 and rules: [Spool > 128K body size]
17:26:12.660 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.camel.impl.DefaultCamelContext - Total 0 routes, of which 0 is started.
17:26:12.662 [some-system-akka.actor.default-dispatcher-2] INFO  o.a.camel.impl.DefaultCamelContext - Apache Camel 2.13.4 (CamelContext: some-system) started in 0.017 seconds
17:26:12.710 [some-system-akka.actor.default-dispatcher-6] DEBUG o.a.camel.impl.DefaultCamelContext - Adding routes from builder: Routes: []
17:26:12.722 [some-system-akka.actor.default-dispatcher-5] DEBUG o.a.camel.impl.DefaultCamelContext - Using ComponentResolver: org.apache.camel.impl.DefaultComponentResolver@11096581 to resolve component with name: jetty
17:26:12.723 [some-system-akka.actor.default-dispatcher-5] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: jetty in registry: null
17:26:12.727 [some-system-akka.actor.default-dispatcher-5] DEBUG o.a.c.impl.DefaultComponentResolver - Found component: jetty via type: org.apache.camel.component.jetty.JettyHttpComponent via: META-INF/services/org/apache/camel/component/jetty
17:26:12.885 [some-system-akka.actor.default-dispatcher-6] DEBUG o.apache.camel.impl.DefaultComponent - Creating endpoint uri=[jetty://http://0.0.0.0:8875/], path=[http://0.0.0.0:8875/]
17:26:12.885 [some-system-akka.actor.default-dispatcher-5] DEBUG o.apache.camel.impl.DefaultComponent - Creating endpoint uri=[jetty://http://akka.io/?bridgeEndpoint=true], path=[http://akka.io/]
17:26:12.895 [some-system-akka.actor.default-dispatcher-6] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
17:26:12.906 [some-system-akka.actor.default-dispatcher-6] DEBUG o.e.j.u.component.AbstractLifeCycle - starting CamelJettyClient(0x384779e0){8<=0<=0/254,-1}#STOPPED
17:26:12.911 [some-system-akka.actor.default-dispatcher-6] DEBUG o.e.j.u.component.AbstractLifeCycle - STARTED CamelJettyClient(0x384779e0){8<=7<=8/254,0}#STARTED
17:26:12.927 [some-system-akka.actor.default-dispatcher-6] DEBUG o.a.camel.impl.DefaultCamelContext - jetty://http://0.0.0.0:8875/ converted to endpoint: Endpoint[http://0.0.0.0:8875/] by component: org.apache.camel.component.jetty.JettyHttpComponent@775cab9e
17:26:12.927 [some-system-akka.actor.default-dispatcher-5] DEBUG o.a.camel.impl.DefaultCamelContext - jetty://http://akka.io/?bridgeEndpoint=true converted to endpoint: Endpoint[http://akka.io/?bridgeEndpoint=true] by component: org.apache.camel.component.jetty.JettyHttpComponent@775cab9e
Uncaught error from thread [some-system-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[some-system]
java.lang.NoSuchMethodError: org.apache.camel.util.ObjectHelper.notNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.camel.component.jetty.JettyHttpProducer.<init>(JettyHttpProducer.java:61)
	at org.apache.camel.component.jetty.JettyHttpEndpoint.createProducer(JettyHttpEndpoint.java:63)
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:402)
	at org.apache.camel.impl.ProducerCache.acquireProducer(ProducerCache.java:123)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:202)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at akka.camel.internal.ProducerRegistrar$$anonfun$receive$3.applyOrElse(CamelSupervisor.scala:168)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.camel.internal.ProducerRegistrar.aroundReceive(CamelSupervisor.scala:157)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
17:26:12.957 [some-system-akka.actor.default-dispatcher-6] DEBUG o.apache.camel.impl.DefaultComponent - Creating endpoint uri=[akka://some-system/user/$c?autoAck=true&replyTimeout=60000+milliseconds], path=[some-system/user/$c]
[ERROR] [11/15/2016 17:26:12.950] [some-system-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(some-system)] Uncaught error from thread [some-system-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.apache.camel.util.ObjectHelper.notNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.camel.component.jetty.JettyHttpProducer.<init>(JettyHttpProducer.java:61)
	at org.apache.camel.component.jetty.JettyHttpEndpoint.createProducer(JettyHttpEndpoint.java:63)
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:402)
	at org.apache.camel.impl.ProducerCache.acquireProducer(ProducerCache.java:123)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:202)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at akka.camel.internal.ProducerRegistrar$$anonfun$receive$3.applyOrElse(CamelSupervisor.scala:168)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.camel.internal.ProducerRegistrar.aroundReceive(CamelSupervisor.scala:157)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by epiphyllum** [comment]
I changed  version of some artifacts

name := "akka-sample-camel-scala"

version := "2.4.11"

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.4.11",
  "com.typesafe.akka" %% "akka-camel" % "2.4.11",
  "org.apache.camel" % "camel-jetty" % "2.10.3",
  "org.apache.camel" % "camel-quartz" % "2.10.3",
  "org.slf4j" % "slf4j-api" % "1.7.2",
  "ch.qos.logback" % "logback-classic" % "1.0.7"
)

licenses := Seq(("CC0", url("http://creativecommons.org/publicdomain/zero/1.0")))

**Comment by johanandren** [comment]
Incorrect camel version is the reason, Akka supports Camel 2.13.4, not 2.10.3 and camel is not binary compatible between those versions. 

Do you think you could provide a PR updating the version in akka-sample-camel-scala and akka-sample-camel-java?

**Comment by patriknw** [comment]
I'll fix this, to get rid of a bug classified ticket (it's not really a bug in my classification)
