### ISSUE TITLE
ClusterSingletonManagerLeaveSpec (with classic remoting)

### ISSUE THREAD

**Issue by drewhk** [akka/akka#21847]
https://jenkins.akka.io:8498/job/akka-nightly/3876/consoleFull

```
[JVM-3] - must hand-over to new instance *** FAILED ***
[JVM-3]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for preStart
[JVM-3]   at scala.Predef$.assert(Predef.scala:170)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-3]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-3]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$13.apply$mcV$sp(ClusterSingletonManagerLeaveSpec.scala:167)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:345)
[JVM-3]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ClusterSingletonManagerLeaveSpec.scala:166)
[JVM-3]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterSingletonManagerLeaveSpec.scala:102)
[JVM-3]   at akka.cluster.singleton.ClusterSingletonManagerLeaveSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterSingletonManagerLeaveSpec.scala:102)
[JVM-3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   ...
[JVM-3] [INFO] [11/16/2016 22:58:41.894] [ClusterSingletonManagerLeaveSpec-akka.remote.default-remote-dispatcher-20] 
```

**Comment by drewhk** [comment]
might or might not be related to https://github.com/akka/akka/issues/21823
