### ISSUE TITLE
akka http - singleRequest throws NullPointerException for uri not encoded

### ISSUE THREAD

**Issue by nykolaslima** [akka/akka#21843]
If we create a `HttpRequest` with an `uri` not encoded and then call `singleRequest` method it will throw a `NullPointerException`.

example:
```
val response = Http().singleRequest(HttpRequest(uri = s"http://someapi.com/cars/my nice car"))
```
throws:
```
Error in stage [Map(<function1>)]: null
java.lang.NullPointerException: null
	at akka.stream.impl.fusing.Map$$anon$8.onPush(Ops.scala:44) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.11.jar:na]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529) ~[akka-stream_2.11-2.4.11.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.11.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.11.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.11.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.11.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.8.jar:na]
```

If we use the same code with the uri encoded it works ok:
```
val response = Http().singleRequest(HttpRequest(uri = s"http://someapi.com/cars/my%20nice%20car"))
```

**Comment by johanandren** [comment]
Hi @nykolaslima, the Akka-HTTP bugtracker has moved over here: https://github.com/akka/akka-http/issues

Please reopen the ticket there, thanks!
