### ISSUE TITLE
FAILED akka.stream.io.TcpSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#21903]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4405/consoleFull

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (3 seconds, 248 milliseconds)
[info]   The future returned an exception of type: akka.stream.StreamTcpException, with message: The connection closed with error: Connection reset by peer. (TcpSpec.scala:525)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:523)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39$$anonfun$apply$5.apply(TcpSpec.scala:525)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39$$anonfun$apply$5.apply(TcpSpec.scala:509)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39.apply(TcpSpec.scala:509)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39.apply(TcpSpec.scala:509)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
...
```

**Comment by jrudolph** [comment]
Another one: 

https://jenkins.akka.io:8498/job/akka-nightly-2.12/65

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4537/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4552/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4609/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4629

```
[info] - must not shut down connections after the connection stream cancelled *** FAILED *** (3 seconds, 254 milliseconds)
[info]   The future returned an exception of type: akka.stream.StreamTcpException, with message: The connection closed with error: Connection reset by peer. (TcpSpec.scala:527)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:523)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39$$anonfun$apply$5.apply(TcpSpec.scala:527)
[info]   at akka.stream.io.TcpSpec$$anonfun$2$$anonfun$apply$mcV$sp$39$$anonfun$apply$5.apply(TcpSpec.scala:511)
```

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/624/consoleFull
