### ISSUE TITLE
failed: StepWise

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21909]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/7876

```
[ERROR] [11/29/2016 20:03:18.197] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-7] [akka://TypedSpec_AdaptedSystem_class/user/basicAdapted-ctx31] timeout of 3 seconds expired while waiting for a message
akka.typed.StepWise$$anon$2: timeout of 3 seconds expired while waiting for a message
	at akka.typed.ActorContextSpec$Tests$MessageStep.stimulate(ActorContextSpec.scala:238)
	at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:498)
	at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:493)
	at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:200)
	at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:192)
	at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:111)
	at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:110)
	at akka.typed.ScalaDSL$Full.management(ScalaDSL.scala:161)
	at akka.typed.adapter.ActorAdapter.preStart(ActorAdapter.scala:54)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
	at akka.typed.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:9)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

-> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 3 children
   |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
   |   ⌊-> eventStreamUnsubscriber-13 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
   |   ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=2 no children
   ⌊-> user LocalActorRef class akka.typed.adapter.ActorAdapter status=0 no children
[ERROR] [11/29/2016 20:03:18.203] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-7] [akka://TypedSpec_AdaptedSystem_class/user/basicAdapted-ctx31] unexpected PostStop while waiting for a message
akka.typed.StepWise$$anon$1: unexpected PostStop while waiting for a message
	at akka.typed.ActorContextSpec$Tests$MessageStep.stimulate(ActorContextSpec.scala:238)
	at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:498)
	at akka.typed.ActorContextSpec$Tests$$anonfun$31$u0020must$u0020set$u0020large$u0020receive$u0020timeout$1.apply(ActorContextSpec.scala:493)
	at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:200)
	at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:192)
	at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:111)
	at akka.typed.StepWise$$anonfun$apply$1.applyOrElse(StepWise.scala:110)
	at akka.typed.ScalaDSL$Full.management(ScalaDSL.scala:161)
	at akka.typed.adapter.ActorAdapter.preStart(ActorAdapter.scala:54)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
	at akka.typed.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:9)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

-> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 3 children
   |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
   |   ⌊-> eventStreamUnsubscriber-13 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
   |   ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=2 no children
   ⌊-> user LocalActorRef class akka.typed.adapter.ActorAdapter status=0 no children
```

**Comment by patriknw** [comment]
ah, already reported https://github.com/akka/akka/issues/21653
