### ISSUE TITLE
Failed to serialize Gossip, Unknown address

### ISSUE THREAD

**Issue by patriknw** [akka/akka#21906]
Noticed this when running cluster StressSpec 
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/12497/consoleText

The node 41267 had removed, quarantined.

```
[JVM-3] [ERROR] [11/29/2016 09:03:25.866] [StressSpec-akka.remote.default-remote-dispatcher-8] [Encoder(akka://StressSpec)] Failed to serialize message [ActorSelectionMessage(akka.cluster.GossipEnvelope)].
[JVM-3] java.lang.IllegalArgumentException: Unknown address [UniqueAddress(akka://StressSpec@a2.moxie:41267,-2038974157288582080)] in cluster message
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer.akka$cluster$protobuf$ClusterMessageSerializer$$mapWithErrorMessage(ClusterMessageSerializer.scala:202)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer.akka$cluster$protobuf$ClusterMessageSerializer$$mapUniqueAddress$1(ClusterMessageSerializer.scala:220)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer$$anonfun$19.apply(ClusterMessageSerializer.scala:242)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer$$anonfun$19.apply(ClusterMessageSerializer.scala:242)
[JVM-3] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[JVM-3] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[JVM-3] 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
[JVM-3] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[JVM-3] 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
[JVM-3] 	at scala.collection.SetLike$class.map(SetLike.scala:92)
[JVM-3] 	at scala.collection.AbstractSet.map(Set.scala:47)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer.gossipToProto(ClusterMessageSerializer.scala:242)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer.gossipEnvelopeToProto(ClusterMessageSerializer.scala:264)
[JVM-3] 	at akka.cluster.protobuf.ClusterMessageSerializer.toBinary(ClusterMessageSerializer.scala:68)
[JVM-3] 	at akka.remote.serialization.MessageContainerSerializer.serializeSelection(MessageContainerSerializer.scala:45)
[JVM-3] 	at akka.remote.serialization.MessageContainerSerializer.toBinary(MessageContainerSerializer.scala:34)
[JVM-3] 	at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:84)
[JVM-3] 	at akka.remote.artery.Encoder$$anon$1.onPush(Codecs.scala:124)
```

**Comment by drewhk** [comment]
Interesting, I take a look.

**Comment by drewhk** [comment]
Yes, it seems like a stray gossip arriving after removal. The serializer seems to be confused as it does not find a mapping for the address in the gossip.

**Comment by drewhk** [comment]
In particular the seen table does not contain an entry that allMembers contain. Is this a valid situation?

**Comment by patriknw** [comment]
you mean the reverse "the seen table contain an entry that allMembers doesn't contain"?

that should not happen (it's a bug)

**Comment by drewhk** [comment]
eh, yes, the reverse

**Comment by drewhk** [comment]
To quote relevant code snippets (just to verify):

```scala
  private def mapWithErrorMessage[T](map: Map[T, Int], value: T, unknown: String): Int = map.get(value) match {
    case Some(x) ⇒ x
    case _       ⇒ throw new IllegalArgumentException(s"Unknown $unknown [$value] in cluster message")
  }

  private def gossipToProto(gossip: Gossip): cm.Gossip.Builder = {
    val allMembers = gossip.members.toVector
    val allAddresses: Vector[UniqueAddress] = allMembers.map(_.uniqueAddress)
    val addressMapping = allAddresses.zipWithIndex.toMap
    ...
    def mapUniqueAddress(uniqueAddress: UniqueAddress): Integer = mapWithErrorMessage(addressMapping, uniqueAddress, "address")
    ...
    val seen = gossip.overview.seen.map(mapUniqueAddress)
    ...
```

**Comment by drewhk** [comment]
putting back for now

**Comment by patriknw** [comment]
I think I see what is going on. `a2.moxie:41267` is the problematic entry.

It is removing itself because it's `Down`:
```
[JVM-3] [INFO] [11/29/2016 09:03:20.891] [StressSpec-akka.actor.default-dispatcher-11] [akka.cluster.Cluster(akka://StressSpec)] Cluster Node [akka://StressSpec@a2.moxie:41267] - Leader is removing unreachable node [akka://StressSpec@a2.moxie:41267]
```

I think that is wrong. A node should shutdown itself when it's `Down` but it doesn't make sense to let a node that is `Down` perform any leader actions.

**Comment by ktoso** [comment]
Backport or not?

**Comment by patriknw** [comment]
yes, I'll backport
