### ISSUE TITLE
FAILED: ArteryRemoteScatterGather

### ISSUE THREAD

**Issue by ktoso** [akka/akka#21970]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/44/consoleFull

```
[JVM-4] A remote ScatterGatherFirstCompleted pool
[JVM-2] A remote ScatterGatherFirstCompleted pool
[JVM-1] [ERROR] [12/07/2016 00:13:31.918] [RemoteScatterGatherSpec-akka.actor.default-dispatcher-3] [akka://RemoteScatterGatherSpec/user/controller/barriers] RoleName(node-3) tried to enter 'node-1-started' while we were waiting for 'broadcast-end' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier)
[JVM-3] - must be locally instantiated on a remote node and be able to communicate through its RemoteActorRef *** FAILED *** (3 seconds, 995 milliseconds)
[JVM-3]   java.lang.RuntimeException: barrier failed: broadcast-end
[JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-3]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-3]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-3]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-3]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-3]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-3]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-3]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-3]   at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
[JVM-3]   at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)
[JVM-3]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-3]   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-3]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-3]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-3]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-3]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-4] - must be locally instantiated on a remote node and be able to communicate through its RemoteActorRef *** FAILED *** (3 seconds, 904 milliseconds)
[JVM-4]   java.lang.RuntimeException: barrier failed: broadcast-end
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
[JVM-4]   at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)
[JVM-4]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-4]   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-4]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-4]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-4]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-4]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-4]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-4]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-4]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-1] - must be locally instantiated on a remote node and be able to communicate through its RemoteActorRef *** FAILED *** (4 seconds, 210 milliseconds)
[JVM-1]   java.lang.RuntimeException: barrier failed: broadcast-end
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
[JVM-1]   at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)
[JVM-1]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-1]   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-1]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-1]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-1]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-1]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-1]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-1]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-1]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-2] - must be locally instantiated on a remote node and be able to communicate through its RemoteActorRef *** FAILED *** (3 seconds, 926 milliseconds)
[JVM-2]   java.lang.RuntimeException: barrier failed: broadcast-end
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-2]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-2]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-2]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-2]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:145)
[JVM-2]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-2]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:145)
[JVM-2]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-2]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-2]   at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
[JVM-2]   at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:145)
[JVM-2]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[JVM-2]   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[JVM-2]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-2]   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-2]   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-2]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-1] [WARN] [12/07/2016 00:13:31.977] [RemoteScatterGatherSpec-akka.actor.default-dispatcher-5] [akka://RemoteScatterGatherSpec/user/controller/barriers] cannot remove RoleName(first): no client to remove
[JVM-2] Flight recorder dump from 'target/flight-recorder-c0f28174-82cf-4061-bbae-bd7a42049cab.afr':
[JVM-3] Flight recorder dump from 'target/flight-recorder-75150fff-7752-4a7d-9ed7-c55a077b1b94.afr':
[JVM-2] --- FLIGHT RECORDER LOG
[JVM-3] --- FLIGHT RECORDER LOG
[JVM-4] Flight recorder dump from 'target/flight-recorder-1ca89bdb-a78c-4978-ae12-036a278c57cb.afr':
[JVM-2] [2016-12-06T23:13:25.821040083Z]    0 Transport: Media driver started    | /dev/shm/aeron-jenkinsakka-RemoteScatterGatherSpec-9d09f27b-70e6-4bd6-809e-2ae49619f5a4
[JVM-2] [2016-12-06T23:13:25.854839836Z]    1 Transport: Aeron started           | 
[JVM-2] [2016-12-06T23:13:25.858785737Z]    2 Transport: Aeron error log started | 
[JVM-2] [2016-12-06T23:13:25.859260392Z]    3 Transport: Task runner started     | 
[JVM-2] [2016-12-06T23:13:25.878913677Z]    4 Transport: Unique address set      | akka://RemoteScatterGatherSpec@localhost:43445#50583605454191245
[JVM-2] [2016-12-06T23:13:25.890620985Z]    5 Transport: Materializer started    | 
[JVM-2] [2016-12-06T23:13:26.206478039Z]   70 AeronSource: Started               | aeron:udp?endpoint=localhost:43445
[JVM-2] [2016-12-06T23:13:26.488965103Z]   70 AeronSource: Started               | aeron:udp?endpoint=localhost:43445
[JVM-2] [2016-12-06T23:13:26.493703798Z]    6 Transport: Startup finished        | 
[JVM-2] [2016-12-06T23:13:29.454022905Z]   55 AeronSink: Envelope offered        | 352
[JVM-2] [2016-12-06T23:13:29.456581798Z]   50 AeronSink: Started                 | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:29.695593314Z]   50 AeronSink: Started                 | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.099137464Z]    8 Transport: KillSwitch pulled       | 
[JVM-2] [2016-12-06T23:13:32.112939772Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.113674598Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.115605012Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.115654046Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.121781675Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:43445
[JVM-2] [2016-12-06T23:13:32.123952941Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:43445
[JVM-2] [2016-12-06T23:13:32.125413118Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.125451755Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:55124
[JVM-2] [2016-12-06T23:13:32.157270975Z]    9 Transport: Stopped                 | 
[JVM-2] [2016-12-06T23:13:32.157856322Z]   10 Transport: Aeron errorLog task sto | 
[JVM-2] [2016-12-06T23:13:32.254912157Z]   11 Transport: Media file deleted      | 
[JVM-2] [2016-12-06T23:13:32.254987701Z]   12 Transport: Flight recorder closed  | 
[JVM-4] --- FLIGHT RECORDER LOG
[JVM-2] Run completed in 8 seconds, 425 milliseconds.
[JVM-2] Total number of tests run: 1
[JVM-2] Suites: completed 1, aborted 0
[JVM-2] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[JVM-2] *** 1 TEST FAILED ***
[JVM-3] [2016-12-06T23:13:25.856243623Z]    0 Transport: Media driver started    | /dev/shm/aeron-jenkinsakka-RemoteScatterGatherSpec-d8a3ab27-dcff-4f1f-a95d-3d8852c00cec
[JVM-3] [2016-12-06T23:13:25.906741417Z]    1 Transport: Aeron started           | 
[JVM-3] [2016-12-06T23:13:25.910186762Z]    2 Transport: Aeron error log started | 
[JVM-3] [2016-12-06T23:13:25.910653771Z]    3 Transport: Task runner started     | 
[JVM-3] [2016-12-06T23:13:25.940220249Z]    4 Transport: Unique address set      | akka://RemoteScatterGatherSpec@localhost:46306#-7806746306788098799
[JVM-3] [2016-12-06T23:13:25.971110015Z]    5 Transport: Materializer started    | 
[JVM-3] [2016-12-06T23:13:26.591778062Z]    6 Transport: Startup finished        | 
[JVM-3] [2016-12-06T23:13:26.593819500Z]   70 AeronSource: Started               | aeron:udp?endpoint=localhost:46306
[JVM-3] [2016-12-06T23:13:26.622798449Z]   70 AeronSource: Started               | aeron:udp?endpoint=localhost:46306
[JVM-3] [2016-12-06T23:13:31.173020350Z]   55 AeronSink: Envelope offered        | 353
[JVM-3] [2016-12-06T23:13:31.191062551Z]   50 AeronSink: Started                 | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:31.387161051Z]   50 AeronSink: Started                 | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.103914890Z]    8 Transport: KillSwitch pulled       | 
[JVM-3] [2016-12-06T23:13:32.107016272Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.107591087Z]   51 AeronSink: Task runner removed     | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.112381032Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:46306
[JVM-3] [2016-12-06T23:13:32.115418581Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.115465808Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.119107672Z]   52 AeronSink: Publication closed      | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.119160635Z]   53 AeronSink: Stopped                 | aeron:udp?endpoint=localhost:55124
[JVM-3] [2016-12-06T23:13:32.134604010Z]   71 AeronSource: Stopped               | aeron:udp?endpoint=localhost:46306
[JVM-3] [2016-12-06T23:13:32.141742920Z]    9 Transport: Stopped                 | 
[JVM-3] [2016-12-06T23:13:32.144890053Z]   10 Transport: Aeron errorLog task sto | 
[JVM-3] [2016-12-06T23:13:32.250580897Z]   11 Transport: Media file deleted      | 
[JVM-3] [2016-12-06T23:13:32.250679568Z]   12 Transport: Flight recorder closed  | 
[JVM-4] [2016-12-06T23:13:25.842076366Z]    0 Transport: Media driver started    | /dev/shm/aeron-jenkinsakka-RemoteScatterGatherSpec-a723c0c3-0bca-4d98-92ba-d2516d06c829
[JVM-4] [2016-12-06T23:13:25.895166766Z]    1 Transport: Aeron started           | 
[JVM-4] [2016-12-06T23:13:25.898574027Z]    2 Transport: Aeron error log started | 
[JVM-4] [2016-12-06T23:13:25.898945981Z]    3 Transport: Task runner started     | 
[JVM-4] [2016-12-06T23:13:25.915869224Z]    4 Transport: Unique address set      | akka://RemoteScatterGatherSpec@localhost:55124#5101496167682868309
[JVM-4] [2016-12-06T23:13:25.927242535Z]    5 Transport: Materializer started    | 
[JVM-3] Run completed in 8 seconds, 511 milliseconds.
[JVM-3] Total number of tests run: 1
[JVM-3] Suites: completed 1, aborted 0
```

**Comment by patriknw** [comment]
This doesn't look like a real test failure, more some issue with multi-node. Only barrier failures. Let's see if it happens again, otherwise close after a month or so.
