### ISSUE TITLE
FAILED (Artery) StressSpec IllegalArgumentException

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21986]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/319/consoleFull

Different from the other Artery StressSpec issue #21810:

```
[JVM-5] *** RUN ABORTED *** (1 second, 480 milliseconds)
[JVM-5]   java.lang.IllegalArgumentException: offset=0 length=32 not valid for buffer.capacity()=0
[JVM-5]   at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:198)
[JVM-5]   at org.agrona.concurrent.UnsafeBuffer.<init>(UnsafeBuffer.java:101)
[JVM-5]   at io.aeron.CncFileDescriptor.createMetaDataBuffer(CncFileDescriptor.java:166)
[JVM-5]   at io.aeron.Aeron$Context.connectToDriver(Aeron.java:603)
[JVM-5]   at io.aeron.Aeron$Context.conclude(Aeron.java:294)
[JVM-5]   at io.aeron.Aeron.<init>(Aeron.java:93)
[JVM-5]   at io.aeron.Aeron.connect(Aeron.java:137)
[JVM-5]   at akka.remote.artery.ArteryTransport.startAeron(ArteryTransport.scala:580)
[JVM-5]   at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:398)
[JVM-5]   at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:212)
[JVM-5]   at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
[JVM-5]   at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
[JVM-5]   at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
[JVM-5]   at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
[JVM-5]   at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
[JVM-5]   at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
[JVM-5]   at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
[JVM-5]   at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:259)
[JVM-5]   at akka.cluster.StressSpec.<init>(StressSpec.scala:709)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/321/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/322/consoleFull

**Comment by patriknw** [comment]
There were some "corrupt" aeron files lingering around in /localhome/jenkinsakka/akka-artery-cluster-tests/target/aeron-StressSpec/. I removed that directory on a4, a5 and a6 and now it seems to work.
