### ISSUE TITLE
FAILED ArteryRemoteReDeployment

### ISSUE THREAD

**Issue by johanandren** [akka/akka#21988]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4447/consoleFull

```
[JVM-1] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (5 seconds, 773 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message PostStop
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:616)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:612)
[JVM-1]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:814)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RemoteReDeploymentSpec.scala:177)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:121)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:121)
```

**Comment by patriknw** [comment]
This has been fixed in https://github.com/akka/akka/pull/23069
Missing barrier.
