### ISSUE TITLE
FAILED: akka.cluster.singleton.ClusterSingletonRestartSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#22012]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/8024/consoleFull

```
[info] - must hand-over to next oldest *** FAILED *** (18 seconds, 330 milliseconds)
[info]   TreeSet() did not equal Set(UniqueAddress(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:36349,-401287287)) (ClusterSingletonRestartSpec.scala:97)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info]   at akka.cluster.singleton.ClusterSingletonRestartSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$9.apply(ClusterSingletonRestartSpec.scala:97)
[info]   at akka.cluster.singleton.ClusterSingletonRestartSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$9.apply(ClusterSingletonRestartSpec.scala:97)
```

**Comment by patriknw** [comment]
that's interesting, that is what I had in my coordinated shutdown PR also, but this was for another (i.e. problem is in master)

**Comment by patriknw** [comment]
ah,

```
[ERROR] [12/15/2016 09:51:13.266] [ClusterSingletonRestartSpec-akka.actor.default-dispatcher-4] [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:36349/system/cluster/core] Cluster node [akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:36349] crashed, [Nodes not part of cluster in reachability table, got [UniqueAddress(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:34361,206961896)]] - shutting down...
java.lang.IllegalArgumentException: Nodes not part of cluster in reachability table, got [UniqueAddress(akka.tcp://ClusterSingletonRestartSpec@127.0.0.1:34361,206961896)]
	at akka.cluster.Gossip.assertInvariants(Gossip.scala:77)
	at akka.cluster.Gossip.<init>(Gossip.scala:67)
	at akka.cluster.Gossip.copy(Gossip.scala:62)
	at akka.cluster.ClusterCoreDaemon.leaderActionsOnConvergence(ClusterDaemon.scala:1109)
	at akka.cluster.ClusterCoreDaemon.leaderActions(ClusterDaemon.scala:994)
	at akka.cluster.ClusterCoreDaemon$$anonfun$initialized$1.applyOrElse(ClusterDaemon.scala:428)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:277)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I'll take this
