### ISSUE TITLE
FAILED: RemoteRouterSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22024]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/8043/consoleFull

```
[info] - must deploy dynamic resizable number of children on remote host driven by configuration *** FAILED *** (5 seconds, 336 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 200
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[info]   at akka.remote.RemoteRouterSpec$$anonfun$collectRouteePaths$1.apply(RemoteRouterSpec.scala:96)
[info]   at akka.remote.RemoteRouterSpec$$anonfun$collectRouteePaths$1.apply(RemoteRouterSpec.scala:93)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[info]   at akka.remote.RemoteRouterSpec.collectRouteePaths(RemoteRouterSpec.scala:93)
[info]   at akka.remote.RemoteRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(RemoteRouterSpec.scala:130)
[info]   at akka.remote.RemoteRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(RemoteRouterSpec.scala:127)
[info]   at akka.remote.RemoteRouterSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(RemoteRouterSpec.scala:127)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
```

**Comment by johanandren** [comment]
Logs not available anymore and hasn't happened in almost a year, closing.
