### ISSUE TITLE
failed: DurableDataSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22037]
https://jenkins.akka.io:8498/job/akka-multi-node/1878/

```
[JVM-1] - must work in single node cluster *** FAILED *** (5 seconds, 104 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: expected ReplicaCount(1), found ReplicaCount(0)
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:388)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-1]   at akka.cluster.ddata.DurableDataSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$13.apply(DurableDataSpec.scala:118)
```

I think this is just an init timeout issue

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.4/20

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/568

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/343/consoleText

**Comment by patriknw** [comment]
I have only increased the startup timeout. Let's see if that is enough.
