### ISSUE TITLE
FAILED: ActorModelSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22085]
Very weird failure `ActorModelSpec `

```
[BalancingDispatcherModelSpec$BalancingMessageDispatcherInterceptorConfigurator$$anon$1[test-balancing-dispatcher-5]] actual: stops=3 required: stops=3
java.lang.AssertionError: await failed
	at akka.actor.dispatch.ActorModelSpec$.await(ActorModelSpec.scala:242)
	at akka.actor.dispatch.ActorModelSpec$.assertDispatcher(ActorModelSpec.scala:161)
	at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8.apply$mcVI$sp(ActorModelSpec.scala:418)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(ActorModelSpec.scala:416)
	at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(ActorModelSpec.scala:360)
	at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(ActorModelSpec.scala:360)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[info] - must handle waves of actors *** FAILED *** (24 seconds, 356 milliseconds)
[info]   java.lang.AssertionError: await failed
[info]   at akka.actor.dispatch.ActorModelSpec$.await(ActorModelSpec.scala:242)
[info]   at akka.actor.dispatch.ActorModelSpec$.assertDispatcher(ActorModelSpec.scala:161)
[info]   at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$mcV$sp$8.apply$mcVI$sp(ActorModelSpec.scala:418)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[info]   at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(ActorModelSpec.scala:416)
[info]   at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(ActorModelSpec.scala:360)
[info]   at akka.actor.dispatch.ActorModelSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(ActorModelSpec.scala:360)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
```

**Comment by patriknw** [comment]
@ktoso link to log or it didn't happen.
Isn't it caused by the crazy GC pauses that I was hunting previously without much success?

**Comment by ktoso** [comment]
Link here: https://jenkins.akka.io:8498/view/PR%20Validators/job/pr-validator-per-commit-jenkins/8101/consoleFull

This was today, during the PR validation of the Aeron upgrade. Could indeed just be weird timeouts but this also is weird: `actual: stops=3 required: stops=3 java.lang.AssertionError: await failed`

maybe the message is incorrect anyway?

**Comment by gosubpl** [comment]
The default `shutdown-timeout = 1s` so with `val deadline = System.currentTimeMillis + dispatcher.shutdownTimeout.toMillis * 5` you get timeout after 5s (more or less). Your GC pause was on that order (reported is `real=4.43 secs` but before that, there was 1s pause for concurrent marking and probably nothing managed to run in-between).
