### ISSUE TITLE
FAILED: akka.stream.io.TlsSpec.SslTls must work in mode ClientInitiatesViaTcp while sending EmptyBytesFirst

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22080]
https://jenkins.akka.io:8498/job/akka-nightly/3996/testReport/junit/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiatesViaTcp_while_sending_EmptyBytesFirst/:

```
Error Message

assertion failed: timeout (-588528180 nanoseconds) during expectMsgClass waiting for class akka.stream.impl.StreamSupervisor$Children

Stacktrace

      java.lang.AssertionError: assertion failed: timeout (-588528180 nanoseconds) during expectMsgClass waiting for class akka.stream.impl.StreamSupervisor$Children
      at scala.Predef$.assert(Predef.scala:170)
      at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:472)
      at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:445)
      at akka.testkit.TestKit.expectMsgType(TestKit.scala:814)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Utils.scala:30)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
      at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
      at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
      at akka.testkit.TestKit.awaitAssert(TestKit.scala:814)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(Utils.scala:28)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
      at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
      at akka.stream.io.TlsSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$6$$anonfun$apply$7.apply(TlsSpec.scala:350)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/583/testReport/junit/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ServerInitiates_while_sending_EmptyBytesLast/

**Comment by jrudolph** [comment]
Another one was files as #22079.

**Comment by raboof** [comment]
(closing as outdated rare failure)
