### ISSUE TITLE
FAILED: DurableDataSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22082]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4485/consoleFull:

```
[JVM-1] - stop Replicator if Load fails *** FAILED *** (3 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: expected: Terminated Actor[akka://DurableDataSpec/user/replicator-2#358621399] but got unexpected message UpdateSuccess(durable-C,None)
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:406)
[JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:814)
[JVM-1]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:417)
[JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:814)
[JVM-1]   at akka.cluster.ddata.DurableDataSpec$$anonfun$6$$anonfun$apply$mcV$sp$11.apply$mcV$sp(DurableDataSpec.scala:320)
```

and

```
[JVM-1] - reply with StoreFailure if store fails *** FAILED *** (2 milliseconds)
[JVM-1]   akka.actor.InvalidActorNameException: actor name [replicator-2] is not unique!
[JVM-1]   at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
[JVM-1]   at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)
[JVM-1]   at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)
[JVM-1]   at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)
[JVM-1]   at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)
[JVM-1]   at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
[JVM-1]   at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:729)
[JVM-1]   at akka.cluster.ddata.DurableDataSpec$$anonfun$7$$anonfun$apply$mcV$sp$12.apply$mcV$sp(DurableDataSpec.scala:327)
```

**Comment by patriknw** [comment]
the "[replicator-2] is not unique" is only a symptom of that the previous step is failing

**Comment by patriknw** [comment]
this is the test failure:
```
[second] - work in multi node cluster *** FAILED *** (5 seconds, 611 milliseconds)
[second]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for UpdateSuccess(durable-A,None)
[second]   at scala.Predef$.assert(Predef.scala:170)
[second]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[second]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[second]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[second]   at akka.cluster.ddata.DurableDataSpec$$anonfun$2.apply$mcV$sp(DurableDataSpec.scala:170)
[second]   at akka.cluster.ddata.DurableDataSpec$$anonfun$2.apply(DurableDataSpec.scala:157)
[second]   at akka.cluster.ddata.DurableDataSpec$$anonfun$2.apply(DurableDataSpec.scala:157)
```

Strange

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4608/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/620/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4661/consoleFull

**Comment by patriknw** [comment]
strange, I'll run it in a debug repeat job

**Comment by 2m** [comment]
Got another one https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4668/consoleFull

**Comment by patriknw** [comment]
Thanks, running it on repeat in https://jenkins.akka.io:8498/job/akka-multi-node-repeat/ with debug logging. No luck reproducing so far.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4698/consoleFull

```
[JVM-1] - be durable after gossip update *** FAILED *** (5 seconds, 8 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for UpdateSuccess(durable-C,None)
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:829)
[JVM-1]   at akka.cluster.ddata.DurableDataSpec$$anonfun$3$$anonfun$apply$mcV$sp$7.apply$mcV$sp(DurableDataSpec.scala:206)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/714/consoleFull
```
[JVM-1] - must work in single node cluster *** FAILED *** (5 seconds, 305 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for UpdateSuccess(durable-A,None)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/723/consoleFull

```

```

**Comment by patriknw** [comment]
Looked at the logs. It's the first update that is not completed within the 5 seconds (no UpdateSuccess reply). We should run this more in a repeat job with debug logging, but I suspect that this is just (strange) slowness.

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/730/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/738/consoleFull

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/743/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/747

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/748/consoleText

yeah, I'll enable debug logging on this one

**Comment by patriknw** [comment]
Here is a failure with debug logging https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/749

```
[JVM-1] [INFO] [06/21/2017 08:42:33.385] [DurableDataSpec-akka.cluster.distributed-data.durable.pinned-store-18] [akka.tcp://DurableDataSpec@a0.moxie:45362/user/replicator-0/durableStore] Using durable data in LMDB directory [/localhome/jenkinsakka/akka-multi-node-nightly2/target/DurableDataSpec-1498027351316-ddata-DurableDataSpec-replicator-0-45362]

and much later

[JVM-1] [DEBUG] [06/21/2017 08:42:41.707] [DurableDataSpec-akka.cluster.distributed-data.durable.pinned-store-18] [akka.tcp://DurableDataSpec@a0.moxie:45362/user/replicator-0/durableStore] Init of LMDB in directory [/localhome/jenkinsakka/akka-multi-node-nightly2/target/DurableDataSpec-1498027351316-ddata-DurableDataSpec-replicator-0-45362] took [8321 ms]
```
