### ISSUE TITLE
FAILED: DurablePruningSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22083]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4487/consoleFull

```
[JVM-2] - must move data from removed node *** FAILED *** (16 seconds, 372 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: expected ReplicaCount(3), found ReplicaCount(4)
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:388)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-2]   at akka.cluster.ddata.DurablePruningSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$16.apply(DurablePruningSpec.scala:120)
```

**Comment by patriknw** [comment]
strange, the leaving is not completed, the node is not removed as expected. It might be that the 15 seconds is too little.

**Comment by drewhk** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/1898/consoleFull

Not the exact same test, but I think it is the exact same failure.

**Comment by johanandren** [comment]
This hasn't happened for a year now, I'll close it in hopes that some other change during the year fixed it.
