### ISSUE TITLE
FAILED: ClusterSingletonRestart2Spec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22084]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/355:

```
Error Message

Set(Up, Exiting) did not equal Set(Up)

Stacktrace

      org.scalatest.exceptions.TestFailedException: Set(Up, Exiting) did not equal Set(Up)
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
      at akka.cluster.singleton.ClusterSingletonRestart2Spec$$anonfun$join$1$$anonfun$apply$mcV$sp$4.apply(ClusterSingletonRestart2Spec.scala:66)
```

**Comment by patriknw** [comment]
I think this is due too short timeout, will be changed in https://github.com/akka/akka/pull/21930

**Comment by johanandren** [comment]
Timeout PR merged Jan 16, and this has no repeats since, so I'll close it.
