### ISSUE TITLE
FAILED: BackoffOnRestartSupervisorSpec.BackoffOnRestartSupervisor must restart the child with an exponential back off

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22098]
https://jenkins.akka.io:8498/job/akka-nightly/4022/testReport/junit/akka.pattern/BackoffOnRestartSupervisorSpec/BackoffOnRestartSupervisor_must_restart_the_child_with_an_exponential_back_off/

```
Error Message

assertion failed: timeout (300 milliseconds) during expectMsg while waiting for STARTED

Stacktrace

      java.lang.AssertionError: assertion failed: timeout (300 milliseconds) during expectMsg while waiting for STARTED
      at scala.Predef$.assert(Predef.scala:170)
      at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
      at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:373)
      at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(BackoffOnRestartSupervisorSpec.scala:90)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$3$$anonfun$apply$mcV$sp$6.apply(BackoffOnRestartSupervisorSpec.scala:87)
      at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
      at akka.testkit.TestKit.within(TestKit.scala:814)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$3.apply$mcV$sp(BackoffOnRestartSupervisorSpec.scala:87)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$3.apply(BackoffOnRestartSupervisorSpec.scala:85)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2$$anonfun$3.apply(BackoffOnRestartSupervisorSpec.scala:85)
      at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
      at akka.testkit.package$.filterException(package.scala:35)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anon$2.<init>(BackoffOnRestartSupervisorSpec.scala:85)
      at akka.pattern.BackoffOnRestartSupervisorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(BackoffOnRestartSupervisorSpec.scala:84)
```

**Comment by johanandren** [comment]
150 millis gc pause just before it

**Comment by raboof** [comment]
(closing as outdated rare failure)

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5/20/testReport/junit/akka.pattern/BackoffOnRestartSupervisorSpec/BackoffOnRestartSupervisor_must_restart_the_child_with_an_exponential_back_off/
