### ISSUE TITLE
akka 2.12 < 2.4.16 broken artifacts

### ISSUE THREAD

**Issue by fkowal** [akka/akka#22122]
i am using scala-library 2.12.1 and akka-cluster 2.4.14

i am looking into upgrading to scala 2.12 from scala 2.11
and i am getting an error like this

when debugging java.lang.Class.reflectionData...declaredFields doesn't seem to show a transient modifier for the cache field

```
07:41:35.088  [main] INFO  p.a.f.w.i.a.spring.SpringActorSystem - Starting actor system: actor-system
07:41:35.116  [actor-system-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
07:41:35.132  [actor-system-akka.actor.default-dispatcher-2] INFO  akka.remote.Remoting - Starting remoting
07:41:35.152  [actor-system-akka.actor.default-dispatcher-2] INFO  akka.remote.Remoting - Remoting started; listening on addresses :[akka.tcp://actor-system@127.0.0.1:49998]
07:41:35.152  [actor-system-akka.actor.default-dispatcher-2] INFO  akka.remote.Remoting - Remoting now listens on addresses: [akka.tcp://actor-system@127.0.0.1:49998]
07:41:35.153  [actor-system-akka.actor.default-dispatcher-2] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Starting up...
07:41:35.161  [actor-system-akka.actor.default-dispatcher-6] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Registered cluster JMX MBean [akka:type=Cluster]
07:41:35.161  [actor-system-akka.actor.default-dispatcher-6] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Started up successfully
07:41:35.172  [main] INFO  p.a.f.w.i.a.spring.SpringActorSystem - joining seed-nodes: List(akka.tcp://actor-system@127.0.0.1:49998)
07:41:35.468  [actor-system-akka.actor.default-dispatcher-2] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - No seed-nodes configured, manual cluster join required
07:41:35.468  [actor-system-akka.actor.default-dispatcher-2] WARN  akka.cluster.AutoDown - Don't use auto-down feature of Akka Cluster in production. See 'Auto-downing (DO NOT USE)' section of Akka Cluster documentation.
07:41:35.468  [actor-system-akka.actor.default-dispatcher-2] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Node [akka.tcp://actor-system@127.0.0.1:49998] is JOINING, roles []
07:41:35.468  [actor-system-akka.actor.default-dispatcher-2] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Leader is moving node [akka.tcp://actor-system@127.0.0.1:49998] to [Up]
07:41:35.473  [actor-system-akka.actor.default-dispatcher-2] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Metrics will be retreived from MBeans, and may be incorrect on some platforms. To increase metric accuracy add the 'sigar.jar' to the classpath and the appropriate platform-specific native libary to 'java.library.path'. Reason: java.lang.IllegalArgumentException: java.lang.UnsatisfiedLinkError: org.hyperic.sigar.Sigar.getPid()J
07:41:37.508  [actor-system-akka.actor.default-dispatcher-3] INFO  a.c.Cluster(akka://actor-system) - Cluster Node [akka.tcp://actor-system@127.0.0.1:49998] - Metrics collection has started successfully
07:41:37.509  [actor-system-akka.actor.default-dispatcher-3] ERROR a.c.ClusterDomainEventPublisher - swallowing exception during message send
java.io.NotSerializableException: akka.cluster.Reachability$Cache
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at akka.serialization.JavaSerializer.$anonfun$toBinary$1(Serializer.scala:288)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.serialization.JavaSerializer.toBinary(Serializer.scala:288)
	at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:134)
	at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:124)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
	at akka.actor.Cell.sendMessage(ActorCell.scala:295)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:294)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:374)
	at akka.actor.LocalActorRef.$bang(ActorRef.scala:406)
	at akka.cluster.ClusterCoreDaemon.publish(ClusterDaemon.scala:1159)
	at akka.cluster.ClusterCoreDaemon.leaderActionsOnConvergence(ClusterDaemon.scala:1008)
	at akka.cluster.ClusterCoreDaemon.leaderActions(ClusterDaemon.scala:882)
	at akka.cluster.ClusterCoreDaemon.joining(ClusterDaemon.scala:536)
	at akka.cluster.ClusterCoreDaemon.join(ClusterDaemon.scala:457)
	at akka.cluster.ClusterCoreDaemon$$anonfun$uninitialized$1.applyOrElse(ClusterDaemon.scala:327)
	at akka.actor.Actor.aroundReceive(Actor.scala:484)
	at akka.actor.Actor.aroundReceive$(Actor.scala:484)
	at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:241)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by patriknw** [comment]
@fkowal Are using `akka.actor.serialize-messages=on` for testing purposes? The stack trace shows that this is one of those checks, but I can't understand why it would use Java serializer. The top message is `Gossip`. Have you changed default serialization configuration?

**Comment by fkowal** [comment]
update i was using akka v.2.4.14 not 2.4.16, the problem seems to be solved in 2.4.16 #20641

yes i am using akka.actor.serialize-messages=on
i've also got custom serializers for my messages, but this is an internal message so that falls into the default serializer i guess


during debugging what struck me as strange 
was that akka.cluster.Reachability
@transient private lazy val cache = new Cache
was actually being serialized

this field showed up without **transient** modifier in java.lang.reflect.Field

that would suggest some kind of a scala 2.12.1 bug

**Comment by patriknw** [comment]
`publish(ClusterDaemon.scala:1159)` is sending `Gossip`, which includes `Reachability`. It looks that `Gossip` is serialized with java serialization, which is wrong. It should use the protobuf serializer. I have no clue why it would do that.

To investigate if it's a Scala bug one could try to serialize `Reachability`.

**Comment by fkowal** [comment]
here is what i found
for scala 2.11
```
wget http://repo1.maven.org/maven2/com/typesafe/akka/akka-cluster_2.11/2.4.14/akka-cluster_2.11-2.4.14.jar

javap -p -cp ./akka-cluster_2.11-2.4.14.jar akka.cluster.Reachability
Compiled from "Reachability.scala"
public class akka.cluster.Reachability implements scala.Serializable {
  public static final long serialVersionUID;
  private final scala.collection.immutable.IndexedSeq<akka.cluster.Reachability$Record> records;
  private final scala.collection.immutable.Map<akka.cluster.UniqueAddress, java.lang.Object> versions;
  private transient akka.cluster.Reachability$Cache cache;
```
Everything looks ok: notice the transient modifier on the cache field

For scala 2.12
```
wget http://repo1.maven.org/maven2/com/typesafe/akka/akka-cluster_2.12/2.4.14/akka-cluster_2.12-2.4.14.jar
javap -p -cp ./akka-cluster_2.12-2.4.14.jar akka.cluster.Reachability
Compiled from "Reachability.scala"
public class akka.cluster.Reachability implements scala.Serializable {
  public static final long serialVersionUID;
  private akka.cluster.Reachability$Cache cache;
....
```
the cache field doesn't have the transient modifier

My conclusion would be the artifacts are broken. I don't have any ideas how could that happen.

When i played around with scala 2.12 repl javap works correctly for @transient. So there must be something with the build.

**Comment by patriknw** [comment]
Perhaps it was fixed in Scala 2.12.1? Akka 2.4.14 was maybe compiled with 2.12.0.

**Comment by patriknw** [comment]
By the way, the real remote message is `GossipEnvelope`, so this `Gossip` send is only a local send. That explains why Java serialization is used there.

**Comment by fkowal** [comment]
```
/scala
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> class L { @scala.transient() val trans: Int = 10 }
defined class L

scala> :javap -p L
Compiled from "<console>"
public class $line3.$read$$iw$$iw$L {
  private final transient int trans;
```

scala 2.12.0 doesn't seem to be the problem.

I have no idea what binary compatibility is about, but from what i see it's being check in the build process of akka.

But i'd bet that loosing transient modifier would break binary compatibility.

I don't know how else to help.
Perhaps a blog post about those artifacts being broken would be in order?

Can these artifacts be marked as broken in maven ?

**Comment by patriknw** [comment]
Well, every release will have some bug, this is no different.
This is nothing serious for Akka since it's only a testing facility that doesn't work, and it's fixed in a later version somehow. Thanks for reporting, and investigating.

**Comment by fkowal** [comment]
no prob. thx
