### ISSUE TITLE
ActorSystem startup fails with latest Java 8

### ISSUE THREAD

**Issue by markusjura** [akka/akka#22160]
The ActorSystem does not start up in time with the latest Java 1.8.0_122 version when passing a configuration to the ActorSystem constructor. The startup time of the ActorSystem takes longer than the default `akka.logger-startup-timeout`. With the latest Java version it takes about 6 seconds to start the actor system. With Java 1.8.0_22 the startup is faster, less than 1 secon, and therefore the timeout is not raised.

As far as I read the thread dump (see below) correctly, the increased time in the latest Java version comes from `java.net.InetAddress.getLocalHost(InetAddress.java:1500)`.

So I guess to be compatible with the latest Java version we should increase the `akka.logger-startup-timeout` to 10 seconds or so.

See also this ConductR issue as reference (private repo): https://github.com/typesafehub/conductr/issues/1591

**Test system**
- macOS 10.12.2 (16C67) - Sierrra
- Java 1.8.0_122 (latest)

**Exception**

```
$ conductr/conductr/target/universal/stage/bin/conductr
objc[26954]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java (0x10cc754c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10dcdf4e0). One of the two will be used. Which one is undefined.
ConductR is starting up...
        ████   Typesafe ConductR
    ████
████    ████   Version 0.1.0
    ████
████           Copyright © 2014-2016 Typesafe, Inc. All rights reserved.
[WARN] [01/18/2017 08:16:17.197] [main] [cinnamon.akka.CinnamonActorInstrumentation] Cannot create actor instrumentation. Lightbend Monitoring can be enabled with '-Dcinnamon.instrumentation=on'.
[WARN] [01/18/2017 08:16:22.444] [main] [EventStream(akka://conductr)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
    at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:118)
    at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:117)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Failure.recover(Try.scala:216)
    at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:117)
    at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:112)
    at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
    at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:112)
    at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
    at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
    at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:164)
    at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
    at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:656)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:653)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:653)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:669)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
    at com.typesafe.conductr.ConductR$.startup(ConductR.scala:142)
    at com.typesafe.conductr.ConductR$.com$typesafe$conductr$ConductR$$run(ConductR.scala:109)
    at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:106)
    at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:106)
    at scala.Option.foreach(Option.scala:257)
    at com.typesafe.conductr.ConductR$.main(ConductR.scala:106)
    at com.typesafe.conductr.ConductR.main(ConductR.scala)
Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
    at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:187)
    at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
    at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:115)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
    ... 24 more
Exception in thread "main" akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
    at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:146)
    at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
    at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
    at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:164)
    at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
    at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:656)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:653)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:653)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:669)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
    at com.typesafe.conductr.ConductR$.startup(ConductR.scala:142)
    at com.typesafe.conductr.ConductR$.com$typesafe$conductr$ConductR$$run(ConductR.scala:109)
    at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:106)
    at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:106)
    at scala.Option.foreach(Option.scala:257)
    at com.typesafe.conductr.ConductR$.main(ConductR.scala:106)
    at com.typesafe.conductr.ConductR.main(ConductR.scala)
2017-01-18T07:16:22Z Markuss-MacBook-Pro.local INFO  Slf4jLogger [] - Slf4jLogger started
```

**VisualVM Thread dump**

```
2017-01-18 18:19:33
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.112-b16 mixed mode):

"Attach Listener" #18 daemon prio=9 os_prio=31 tid=0x00007ff9ac5de000 nid=0x6103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"conductr-akka.actor.default-dispatcher-4" #17 prio=5 os_prio=31 tid=0x00007ff9ae07d800 nid=0x5f03 runnable [0x000070000bd6e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        - locked <0x00000007be0bf0f0> (a java.lang.Object)
        at ch.qos.logback.core.util.ContextUtil.getLocalHostName(ContextUtil.java:37)
        at ch.qos.logback.core.util.ContextUtil.addHostNameAsProperty(ContextUtil.java:67)
        at ch.qos.logback.classic.joran.action.ConfigurationAction.begin(ConfigurationAction.java:65)
        at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
        at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
        at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
        at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:155)
        - locked <0x00000007bc8168c8> (a ch.qos.logback.core.spi.LogbackLock)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:142)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:103)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:149)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:390)
        - locked <0x00000007bc5e16e0> (a java.lang.Class for org.slf4j.LoggerFactory)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:340)
        at akka.event.slf4j.Logger$.apply(Slf4jLogger.scala:33)
        at akka.event.slf4j.SLF4JLogging$class.log(Slf4jLogger.scala:22)
        at akka.event.slf4j.Slf4jLogger.log$lzycompute(Slf4jLogger.scala:57)
        - locked <0x00000007bc5a7380> (a akka.event.slf4j.Slf4jLogger)
        at akka.event.slf4j.Slf4jLogger.log(Slf4jLogger.scala:57)
        at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:92)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:57)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run$$original(Mailbox.scala:224)
        at akka.dispatch.Mailbox.run(Mailbox.scala:29)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
        - None

"conductr-akka.actor.default-dispatcher-3" #16 prio=5 os_prio=31 tid=0x00007ff9ae07e800 nid=0x5d03 waiting on condition [0x000070000bc6d000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007bc326640> (a akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool)
        at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
        - None

"conductr-akka.actor.default-dispatcher-2" #15 prio=5 os_prio=31 tid=0x00007ff9ac59c000 nid=0x5b03 waiting on condition [0x000070000bb6a000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007bc326640> (a akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinPool)
        at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
        - None

"conductr-scheduler-1" #14 prio=5 os_prio=31 tid=0x00007ff9ac3bc800 nid=0x5903 sleeping[0x000070000ba67000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at akka.actor.LightArrayRevolverScheduler.waitNanos(LightArrayRevolverScheduler.scala:85)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:266)
        at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:236)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-0" #13 daemon prio=5 os_prio=31 tid=0x00007ff9ac0f2000 nid=0x5503 runnable [0x000070000b861000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-20000" #12 daemon prio=5 os_prio=31 tid=0x00007ff9acd10000 nid=0x1007 runnable [0x000070000b75e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"RMI TCP Accept-0" #11 daemon prio=5 os_prio=31 tid=0x00007ff9ab014800 nid=0x1407 runnable [0x000070000b65b000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
        at java.net.ServerSocket.implAccept(ServerSocket.java:545)
        at java.net.ServerSocket.accept(ServerSocket.java:513)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
        at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007ff9ab03b800 nid=0x5303 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007ff9ac087000 nid=0x5103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007ff9acbe1800 nid=0x4f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007ff9acbe0800 nid=0x4d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007ff9ad804800 nid=0x4b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007ff9aa802800 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007ff9ac03f800 nid=0x3903 in Object.wait() [0x000070000af46000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007be020760> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000007be020760> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007ff9ac03d000 nid=0x3703 in Object.wait() [0x000070000ae43000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007be028390> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000007be028390> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
        - None

"main" #1 prio=5 os_prio=31 tid=0x00007ff9ac003000 nid=0x1c03 waiting on condition [0x000070000a424000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007bc69fb68> (a scala.concurrent.impl.Promise$CompletionLatch)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:208)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:190)
        at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:182)
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:117)
        at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:116)
        at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
        at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:113)
        at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
        at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
        at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:183)
        at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
        at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
        at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
        - locked <0x00000007bae29cc8> (a akka.actor.ActorSystemImpl)
        at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
        at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at com.typesafe.conductr.ConductR$.startup(ConductR.scala:150)
        at com.typesafe.conductr.ConductR$.com$typesafe$conductr$ConductR$$run(ConductR.scala:112)
        at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:109)
        at com.typesafe.conductr.ConductR$$anonfun$main$1.apply(ConductR.scala:109)
        at scala.Option.foreach(Option.scala:257)
        at com.typesafe.conductr.ConductR$.main(ConductR.scala:109)
        at com.typesafe.conductr.ConductR.main(ConductR.scala)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=31 tid=0x00007ff9ac03a000 nid=0x3503 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007ff9ac803800 nid=0x2503 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007ff9ac804000 nid=0x2703 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007ff9ab003800 nid=0x2903 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007ff9ab009800 nid=0x2b03 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007ff9ab00a800 nid=0x2d03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007ff9ab00b000 nid=0x2f03 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007ff9ab012800 nid=0x3103 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007ff9ab013800 nid=0x3303 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007ff9ad00d000 nid=0x5703 waiting on condition 

JNI global references: 395

```

**Comment by drewhk** [comment]
The thread dump only shows Akka using Await on the logger. This does not explain why that wait takes so long unfortunately.

**Comment by patriknw** [comment]
Can you reproduce it from repl?
```
scala> java.net.InetAddress.getLocalHost
```

Googling shows old results about adding to /etc/hosts but that might be outdated.

5 seconds for getLocalHost is not nice, and it might cause other issues.

**Comment by huntc** [comment]
I think that this issue is within logback. I've been able to pause from within a debug session and note that logback calls upon the JDK to perform a reverse DNS lookup.

**Comment by patriknw** [comment]
Yes, that's in the Visual VM dump

**Comment by huntc** [comment]
Possibly related? https://bugs.openjdk.java.net/browse/JDK-8158038?jql=text%20~%20%22lookupAllHostAddr%22%20ORDER%20BY%20created%20DESC

**Comment by huntc** [comment]
When I ran the debugger on this, I also noticed that the name it was trying to resolve was "Christophers-MacBook-Pro-2", as in the name of my machine. Modifying /etc/hosts doesn't appear to help. My understanding there is that the OS X DNS resolver mechanism avoids /etc/hosts, and it is there for tool compatibility.

**Comment by huntc** [comment]
Interesting and related: https://plumbr.eu/blog/java/macos-sierra-problems-with-java-net-inetaddress-getlocalhost

**Comment by markusjura** [comment]
Added the aliases worked for me as well. Closing the issue because it is not Akka related.

**Comment by ktoso** [comment]
Good to know, thanks for the research guys

**Comment by patriknw** [comment]
good, I think I already had such in my /etc/hosts

**Comment by patriknw** [comment]
Let's add a note in the documentation and mention the problem in the log message (when running on osx).
