### ISSUE TITLE
failed: GraphMatValueSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22161]
"not ignore materialized value of indentity flow which is optimized away"

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/8216/consoleFull

How can this be non-deterministic?

```
--- Stream actors debug dump ---
Stream actors alive: List(Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-2-nestedFlow-ZipWith2#-257359050], Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-3-nestedFlow-broadcast#-1516374126], Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-4-ignoreSink#-2000615281])
activeShells (actor: Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-3-nestedFlow-broadcast#-1516374126]):
  GraphInterpreterShell
    GraphAssembly
      [ GraphStage(Broadcast) [1a8cb68c]    []
      ]
      [Broadcast.in,null,null]
      [0,-1,-1]
      [null,Broadcast.out0,Broadcast.out1]
      [-1,0,0]digraph waits {
N0 [label="Broadcast"]
  N0 -> In0 [label=shouldPull; color=blue]
  Out1 -> N0 [label=shouldPull; color=blue]
  Out2 -> N0 [label=shouldPull; color=blue]
}
// (4, 0, 0)() (running=1, shutdown=3)newShells:
activeShells (actor: Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-4-ignoreSink#-2000615281]):
  GraphInterpreterShell
    GraphAssembly
      [ GraphStage(akka.stream.impl.fusing.GraphStages$IgnoreSink$@8347152) [63fb9eb2]    []
      ]
      [Ignore.in]
      [0]
      [null]
      [-1]digraph waits {
N0 [label="akka.stream.impl.fusing.GraphStages$IgnoreSink$@8347152"]
  In0 -> N0 [label=shouldPush; color=red];
}
// (1, 1, 1)() (running=1, shutdown=1)newShells:
activeShells (actor: Actor[akka://GraphMatValueSpec/user/StreamSupervisor-315/flow-26-2-nestedFlow-ZipWith2#-257359050]):
  GraphInterpreterShell
    GraphAssembly
      [ GraphStage(Zip) [0a79c7c1]    []
      ]
      [ZipWith2.in0,ZipWith2.in1,null]
      [0,0,-1]
      [null,null,ZipWith2.out]
      [-1,-1,0]digraph waits {
N0 [label="Zip"]
  In0 -> N0 [label=shouldPush; color=red];
  In1 -> N0 [label=shouldPush; color=red];
  N0 -> Out2 [label=shouldPush; color=red];
}
// (4, 3, 3)() (running=1, shutdown=3)newShells:
[info] - when not ignore materialized value of indentity flow which is optimized away *** FAILED *** (2 seconds, 20 milliseconds)
[info]   java.lang.ClassCastException: akka.NotUsed$ cannot be cast to scala.Tuple2
[info]   at akka.stream.scaladsl.GraphMatValueSpec$$anonfun$2$$anonfun$apply$mcV$sp$16.apply(GraphMatValueSpec.scala:232)
[info]   at akka.stream.scaladsl.GraphMatValueSpec$$anonfun$2$$anonfun$apply$mcV$sp$16.apply(GraphMatValueSpec.scala:230)
```

**Comment by patriknw** [comment]
false alarm, the test was new (and invalid) in that PR
