### ISSUE TITLE
always initialize CoordinatedShutdown

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22191]

**Comment by patriknw** [comment]
Noticed that some remote tests were initiating the CoordinateShutdown extensions from the Artery shutdown hook.

```
[JVM-2] Exception in thread "Thread-0" java.lang.IllegalStateException: Shutdown in progress
[JVM-2] 	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
[JVM-2] 	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
[JVM-2] 	at akka.actor.CoordinatedShutdown.addJvmShutdownHook(CoordinatedShutdown.scala:385)
[JVM-2] 	at akka.actor.CoordinatedShutdown$.initJvmHook(CoordinatedShutdown.scala:103)
[JVM-2] 	at akka.actor.CoordinatedShutdown$.createExtension(CoordinatedShutdown.scala:61)
[JVM-2] 	at akka.actor.CoordinatedShutdown$.createExtension(CoordinatedShutdown.scala:36)
[JVM-2] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:896)
[JVM-2] 	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
[JVM-2] 	at akka.actor.CoordinatedShutdown$.apply(CoordinatedShutdown.scala:36)
[JVM-2] 	at akka.remote.artery.ArteryTransport$$anon$1.run(ArteryTransport.scala:463)
```
