### ISSUE TITLE
FAILED: akka.stream.scaladsl.FlowSpec.A Flow with multiple subscribers (FanOutBox) must call future subscribers' onError when all subscriptions were cancelled

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22265]
https://jenkins.akka.io:8498/job/akka-release-2.4/82/testReport/akka.stream.scaladsl/FlowSpec/A_Flow_with_multiple_subscribers__FanOutBox__must_call_future_subscribers__onError_when_all_subscriptions_were_cancelled/

```
 java.lang.AssertionError: assertion failed: timeout (3 seconds) during fishForMessage, hint: 
      at scala.Predef$.assert(Predef.scala:170)
      at akka.testkit.TestKitBase$class.recv$1(TestKit.scala:435)
      at akka.testkit.TestKitBase$class.fishForMessage(TestKit.scala:439)
      at akka.testkit.TestKit.fishForMessage(TestKit.scala:814)
      at akka.stream.testkit.StreamTestKit$PublisherProbeSubscription.expectCancellation(StreamTestKit.scala:720)
      at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$23$$anon$14.<init>(FlowSpec.scala:526)
      at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$23.apply(FlowSpec.scala:522)
      at akka.stream.scaladsl.FlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$23.apply(FlowSpec.scala:522)
```

**Comment by raboof** [comment]
(closing as outdated one-off failure)
