### ISSUE TITLE
Suggest using 64bit JVM for Artery in docs

### ISSUE THREAD

**Issue by andrievskya** [akka/akka#22303]
Trying a simple test (see attachmet) with a single "server" and multiple "clients" on  a virtual machine (4  CPUs, 4 Gb RAM, Win7x64), found that Artery remoting stops working when there are 4 clients (8 clients when using an external MediaDriver)

It produces a following error:

2017-02-14 09:07:11 ERROR akka://ServerSystem/system/StreamSupervisor-0/remote-1-0-unknown-operation akka.actor.RepointableActorRef  - Error in stage [akka.remote.artery.InboundHandshake@ef1c09]: java.io.IOException: Map failed
io.aeron.exceptions.RegistrationException: java.io.IOException: Map failed
	at io.aeron.ClientConductor.onError(ClientConductor.java:264)
	at io.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:141)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:99)
	at io.aeron.DriverListenerAdapter.pollMessage(DriverListenerAdapter.java:59)
	at io.aeron.ClientConductor.doWork(ClientConductor.java:331)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:350)
	at io.aeron.ClientConductor.addPublication(ClientConductor.java:166)
	at io.aeron.Aeron.addPublication(Aeron.java:178)
	at akka.remote.artery.AeronSink$$anon$1.<init>(AeronSink.scala:103)
	at akka.remote.artery.AeronSink.createLogicAndMaterializedValue(AeronSink.scala:100)
	at akka.stream.impl.fusing.GraphInterpreter$GraphAssembly.materialize(GraphInterpreter.scala:190)
	at akka.stream.impl.ActorMaterializerImpl$$anon$2.matGraph(ActorMaterializerImpl.scala:230)
	at akka.stream.impl.ActorMaterializerImpl$$anon$2.materializeAtomic(ActorMaterializerImpl.scala:217)
	at akka.stream.impl.MaterializerSession.$anonfun$materializeModule$1(StreamLayout.scala:954)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:950)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:917)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:256)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:146)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
	at akka.remote.artery.Association.runOutboundOrdinaryMessagesStream(Association.scala:570)
	at akka.remote.artery.Association.runOutboundStreams(Association.scala:510)
	at akka.remote.artery.Association.associate(Association.scala:502)
	at akka.remote.artery.AssociationRegistry.association(Association.scala:763)
	at akka.remote.artery.AssociationRegistry.setUID(Association.scala:778)
	at akka.remote.artery.ArteryTransport.completeHandshake(ArteryTransport.scala:932)
	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:201)
	at akka.remote.artery.InboundHandshake$$anon$2$$anon$4.onPush(Handshake.scala:192)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:497)
	at akka.actor.Actor.aroundReceive$(Actor.scala:495)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

and a bunch of other similar ones (see server.log for more)

[aeronTest.zip](https://github.com/akka/akka/files/773316/aeronTest.zip)
[aeronTest_logs.zip](https://github.com/akka/akka/files/773319/aeronTest_logs.zip)

Just for comparison, the same test works fine with prevoius remoting system:

[aeronTest_netty.zip](https://github.com/akka/akka/files/773317/aeronTest_netty.zip)
[aeronTest_netty_logs.zip](https://github.com/akka/akka/files/773320/aeronTest_netty_logs.zip)

**Comment by patriknw** [comment]
@andrievskya  Looking at the server.log I think the reason is that you are out of direct memory space. Try with 
`-XX:MaxDirectMemorySize=256M` or more. Please report back. If that is the reason we should mention this in the documentation.

**Comment by andrievskya** [comment]
With 256 and 512M the behavior is generally the same (see attachment) 
[aeronTest_logs_xxMem.zip](https://github.com/akka/akka/files/773477/aeronTest_logs_xxMem.zip)
The only difference is that 7 clients was enough to stop working, so it may be that number of CPUs doesnt affect the situation.

BTW, on a more powerful system (i7 8 cores, 16G RAM) this test works fine, even without -XXMemory magic

**Comment by patriknw** [comment]
See for example http://javarevisited.blogspot.se/2014/11/javaioioexception-map-failed-javalangoutofmemoryerror.html

You could try even larger and also the `-d64` flag. Make sure you start the external media driver with those flags, if that is what you are using.

Perhaps something is scaled depending on the machine size?

**Comment by andrievskya** [comment]
Switching to 64bit java solved the issue. No XX:memory size magic needed.

So, maybe it's worth mentioning in the documentation, that Artery requires 64bit java for reliable work, while netty-based remoting feels fine in 32bit java.

**Comment by patriknw** [comment]
Thanks for testing that, yes that would be good addition to the documentation. Would you be able to create a pull request?

**Comment by ktoso** [comment]
I changed the title and tagged accordingly

**Comment by andrievskya** [comment]
Created a pull request https://github.com/akka/akka/pull/22313

**Comment by jlprat** [comment]
Usually issues are not closed until the PR is merged, maybe you should reopen it :)

**Comment by andrievskya** [comment]
Ok, reopened.

**Comment by ktoso** [comment]
Yeo, indeed - thanks ;)
