### ISSUE TITLE
failed: ActorRefSourceSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22365]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/8453

```
[info] - must buffer when needed *** FAILED *** (5 seconds, 711 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnNext(1)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:303)
[info]   at akka.stream.scaladsl.ActorRefSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(ActorRefSourceSpec.scala:38)
[info]   at akka.stream.scaladsl.ActorRefSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(ActorRefSourceSpec.scala:38)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[info]   at akka.stream.scaladsl.ActorRefSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ActorRefSourceSpec.scala:38)
[info]   at akka.stream.scaladsl.ActorRefSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ActorRefSourceSpec.scala:32)
```

**Comment by ktoso** [comment]
Putting it back, I don't think I actually started debugging this one yet

**Comment by johanandren** [comment]
Logs no longer available :/
Closing, reopen if it happens again and we have something to look at.
