### ISSUE TITLE
Failed: akka.contrib.pattern.ReliableProxy

### ISSUE THREAD

**Issue by 2m** [akka/akka#22366]
Got a bunch of failures this night:

https://jenkins.akka.io:8498/job/akka-nightly/4168/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4665/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/1965/consoleFull
https://jenkins.akka.io:8498/job/akka-nightly/4169/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/634/consoleFull

```
[JVM-2] - must reconnect to target *** FAILED ***
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$expectN$1.apply(ReliableProxySpec.scala:75)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$expectN$1.apply(ReliableProxySpec.scala:75)
[JVM-2]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec.expectN(ReliableProxySpec.scala:75)
[JVM-2]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$37.apply$mcV$sp(ReliableProxySpec.scala:284)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:353)
[JVM-2]   ...
[JVM-1] - must reconnect to target *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for Transition(Actor[akka://ReliableProxySpec/user/proxy1#723009023],Active,Idle)
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:364)
[JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:814)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec.expectTransition(ReliableProxySpec.scala:71)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$31$$anonfun$apply$mcV$sp$36.apply$mcV$sp(ReliableProxySpec.scala:280)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:353)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply$mcV$sp(ReliableProxySpec.scala:278)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(ReliableProxySpec.scala:245)
[JVM-1]   at akka.contrib.pattern.ReliableProxySpec$$anonfun$1$$anonfun$apply$mcV$sp$31.apply(ReliableProxySpec.scala:245)
[JVM-1]   ...
```

**Comment by patriknw** [comment]
This is related to https://github.com/akka/akka/pull/22335 but I don't know what is wrong yet.
