### ISSUE TITLE
Failed: CompressionIntegrationSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#22394]
This spec failed once this night. Looks like even after #22318 we get the same failure.

```
info] - wrap around *** FAILED *** (762 milliseconds)
[info]   33 did not equal 32 (CompressionIntegrationSpec.scala:302)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:302)
[info]   at akka.remote.artery.compress.CompressionIntegrationSpec$$anonfun$3$$anonfun$apply$mcV$sp$23$$anonfun$apply$4.apply(CompressionIntegrationSpec.scala:292)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
[info]   at akka.testkit.TestKit.within(TestKit.scala:814)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[info]   at akka.testkit.TestKit.within(TestKit.scala:814)
```

https://jenkins.akka.io:8498/job/akka-release-2.4/107/consoleFull

**Comment by bantonsson** [comment]
This seem to have failed on release-2.4 where #22318 is not present (AFAICT). Should I forward port the test fix?

**Comment by patriknw** [comment]
yes please
