### ISSUE TITLE
NPE in GraphInterpreter when `GraphStageLogic` never called `setHandler`

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22552]
See https://gitter.im/akka/dev?at=58c7d6ebfef1d2de52ad22b4

It seems the nicer error message we had with the old materializer was lost.

Example:

```scala
      Source.empty[Unit]
        .fold("") { case _ => "" + "" }
        .viaMat(new GraphStageWithMaterializedValue[FlowShape[String, String], String] {
          val in = Inlet[String]("in")
          val out = Outlet[String]("out")
          override val shape: FlowShape[String, String] = FlowShape(in, out)

          override def createLogicAndMaterializedValue(inheritedAttributes: Attributes) =
            new GraphStageLogic(shape) with InHandler with OutHandler {
              override def onPush(): Unit = push(out, grab(in))

              override def onPull(): Unit = pull(in)
            } -> "MAT"
        })(Keep.right)
        .to(Sink.head)
```

```
[info] java.lang.NullPointerException
[info]     at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:507)
[info]     at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:467)
[info]     at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:369)
[info]     at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:570)
[info]     at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540)
[info]     at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:658)
[info]     at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:706)
[info]     at akka.actor.Actor$class.aroundPreStart(Actor.scala:521)
[info]     at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:649)
[info]     at akka.actor.ActorCell.create(ActorCell.scala:574)
[info]     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:445)
[info]     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:467)
[info]     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info]     at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info]     at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
2.4 says:

```
Exception in thread "main" java.lang.IllegalStateException: no handler defined in stage streams.Playground$$anon$2$$anon$1@45d84a20 for port in
	at akka.stream.impl.fusing.GraphInterpreter$GraphAssembly.materialize(GraphInterpreter.scala:214)
	at akka.stream.impl.ActorMaterializerImpl$$anon$2.matGraph(ActorMaterializerImpl.scala:230)
	at akka.stream.impl.ActorMaterializerImpl$$anon$2.materializeAtomic(ActorMaterializerImpl.scala:217)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:954)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:950)
```

**Comment by jrudolph** [comment]
So, this issue is a side-effect of removing `GraphAssembly`.

**Comment by johanandren** [comment]
I think I can sneak in a check just after creating the `GraphStageLogic`
