### ISSUE TITLE
Failed: ReplicatorMapDeltaSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#22631]
A couple of failures of this spec in the nighly runs over the weekend:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4764/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/666/consoleFull

```
[JVM-3] - must be eventually consistent *** FAILED *** (7 seconds, 986 milliseconds)
[JVM-3]   Some(Set()) did not equal None (ReplicatorMapDeltaSpec.scala:271)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-3]   at akka.cluster.ddata.ReplicatorMapDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$15$$anonfun$apply$4$$anonfun$apply$mcV$sp$21.apply(ReplicatorMapDeltaSpec.scala:271)
[JVM-3]   at akka.cluster.ddata.ReplicatorMapDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$15$$anonfun$apply$4$$anonfun$apply$mcV$sp$21.apply(ReplicatorMapDeltaSpec.scala:265)
[JVM-3]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:303)
[JVM-3]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:314)
[JVM-3]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:829)
[JVM-3]   at akka.cluster.ddata.ReplicatorMapDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$15$$anonfun$apply$4.apply$mcV$sp(ReplicatorMapDeltaSpec.scala:265)
[JVM-3]   at akka.cluster.ddata.ReplicatorMapDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$15$$anonfun$apply$4.apply(ReplicatorMapDeltaSpec.scala:265)
[JVM-3]   at akka.cluster.ddata.ReplicatorMapDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$15$$anonfun$apply$15$$anonfun$apply$4.apply(ReplicatorMapDeltaSpec.scala:265)
[JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:345)
[JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:829)
[JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:829)
...
```

**Comment by gosubpl** [comment]
Looking into this.

**Comment by gosubpl** [comment]
Failing script, if you need this:
```

  val operations1 = Vector(Decr(KeyA, 3, WriteLocal), Decr(KeyC, 7, WriteTo(2, 5 seconds)),
    RemoveVD(KeyF, "a", WriteLocal), AddVD(KeyE, "f", WriteLocal), Delay(78),
    Decr(KeyA, 1, WriteLocal), Delay(353), Decr(KeyB, 9, WriteLocal), Incr(KeyC, 78, WriteLocal), Decr(KeyB, 1, WriteTo(2, 5 seconds)),
    Decr(KeyC, 1, WriteLocal), Decr(KeyB, 8, WriteLocal), Delay(361), Delay(399), Delay(480), Decr(KeyB, 2, WriteLocal),
    RemoveVD(KeyF, "f", WriteLocal), Incr(KeyA, 71, WriteLocal), Delay(126), Delay(155), Decr(KeyB, 1, WriteLocal),
    Decr(KeyC, 6, WriteLocal), Delay(467), AddVD(KeyD, "e", WriteLocal), Decr(KeyB, 1, WriteLocal), Decr(KeyC, 6, WriteLocal),
    Delay(337), Delay(103), AddVD(KeyE, "i", WriteLocal), Incr(KeyA, 5, WriteLocal), Decr(KeyB, 5, WriteLocal),
    Decr(KeyB, 9, WriteLocal), Delay(264), Incr(KeyB, 6, WriteLocal), Decr(KeyA, 2, WriteLocal), Delay(170),
    Incr(KeyC, 82, WriteTo(2, 5 seconds)), Incr(KeyC, 31, WriteTo(2, 5 seconds)), Incr(KeyC, 36, WriteLocal), Decr(KeyC, 2, WriteLocal))

  val operations2 = Vector(Delay(102), Incr(KeyB, 73, WriteLocal), Delay(144), AddVD(KeyF, "i", WriteLocal), Delay(165),
    AddVD(KeyD, "g", WriteMajority(5 seconds, 0)), Incr(KeyA, 85, WriteLocal), Incr(KeyC, 78, WriteLocal), Delay(223),
    AddVD(KeyE, "f", WriteLocal), AddVD(KeyD, "i", WriteLocal), Incr(KeyA, 30, WriteLocal), AddVD(KeyF, "d", WriteLocal),
    Decr(KeyA, 9, WriteLocal), AddVD(KeyE, "c", WriteLocal), Delay(83), Incr(KeyB, 97, WriteLocal), Decr(KeyB, 8, WriteLocal),
    Delay(171), Delay(399), Delay(85), Delay(484), Delay(228), AddVD(KeyD, "i", WriteLocal), Delay(172), Delay(434), Delay(154),
    Incr(KeyC, 86, WriteLocal), Incr(KeyB, 61, WriteLocal), AddVD(KeyD, "e", WriteLocal), AddVD(KeyE, "c", WriteLocal), Delay(314),
    AddVD(KeyF, "j", WriteLocal), Decr(KeyA, 7, WriteLocal), Decr(KeyA, 7, WriteLocal), Decr(KeyC, 6, WriteTo(2, 5 seconds)),
    Incr(KeyA, 14, WriteLocal), Delay(197))

  val operations3 = Vector(Delay(407), Delay(225), Delay(239), Delay(437), AddVD(KeyD, "g", WriteLocal),
    AddVD(KeyE, "c", WriteLocal), Decr(KeyB, 7, WriteLocal), AddVD(KeyF, "j", WriteLocal), AddVD(KeyD, "b", WriteLocal),
    AddVD(KeyD, "c", WriteLocal), Decr(KeyA, 4, WriteLocal), Decr(KeyC, 3, WriteLocal), AddVD(KeyD, "d", WriteLocal),
    AddVD(KeyF, "e", WriteLocal), Incr(KeyC, 50, WriteLocal), AddVD(KeyE, "g", WriteLocal), Decr(KeyA, 5, WriteLocal),
    Decr(KeyA, 5, WriteLocal), Incr(KeyC, 89, WriteLocal), AddVD(KeyD, "d", WriteLocal), AddVD(KeyE, "a", WriteLocal),
    Delay(488), Decr(KeyC, 1, WriteLocal), Decr(KeyB, 2, WriteLocal), AddVD(KeyF, "i", WriteLocal), Delay(31),
    Incr(KeyA, 18, WriteLocal), Decr(KeyA, 4, WriteLocal), Delay(41), Decr(KeyC, 5, WriteLocal), Incr(KeyB, 18, WriteLocal),
    AddVD(KeyE, "g", WriteLocal), Decr(KeyA, 6, WriteLocal))

  val operations4 = Vector(Incr(KeyB, 18, WriteLocal), Incr(KeyB, 61, WriteLocal), Delay(140), Delay(235), Delay(497),
    AddVD(KeyD, "i", WriteLocal), Delay(226), Incr(KeyA, 79, WriteLocal), Decr(KeyC, 9, WriteLocal),
    AddVD(KeyF, "b", WriteLocal), Delay(142), AddVD(KeyF, "d", WriteTo(2, 5 seconds)), Delay(155), Incr(KeyA, 78, WriteLocal),
    Delay(326), Decr(KeyC, 8, WriteLocal), Delay(333), Incr(KeyA, 64, WriteLocal), AddVD(KeyF, "g", WriteLocal),
    Delay(238), AddVD(KeyE, "b", WriteLocal), Decr(KeyA, 0, WriteLocal), Decr(KeyA, 6, WriteLocal), Decr(KeyB, 5, WriteLocal),
    Incr(KeyC, 39, WriteLocal), Decr(KeyB, 7, WriteLocal), Incr(KeyA, 40, WriteLocal), Delay(462), AddVD(KeyE, "b", WriteLocal),
    Incr(KeyC, 75, WriteLocal), Incr(KeyB, 29, WriteLocal), Incr(KeyA, 26, WriteTo(2, 5 seconds)), Decr(KeyC, 1, WriteLocal),
    AddVD(KeyF, "b", WriteLocal), Incr(KeyA, 31, WriteLocal))

  val genOps = List(first → operations1, second → operations2, third → operations3, fourth → operations4).toMap
```

**Comment by gosubpl** [comment]
Interestingly, for this input the test fails very often, but not always :)

**Comment by gosubpl** [comment]
The trace is here (for `NoVD` case), but no luck replicating in unit test:
```
[JVM-3] ORMap mergeDelta this ORMap(h -> ORSet(a, f, c, g), g -> ORSet(a, i, b, g, c, d)) thatDelta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(i)),(i,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(i)),ORMultiMapTag))) result ORMap(h -> ORSet(a, f, c, g), g -> ORSet(a, i, b, g, c, d), i -> ORSet())
[JVM-3] mergeDelta DEBUG: Map(h -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 60), g -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 22)) vvector VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 60, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 51, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64324,1837082777) -> 25)
[JVM-2] ORMap mergeDelta this ORMap(h -> ORSet(a, f, c, g), g -> ORSet(a, i, b, g, c, d)) thatDelta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(i)),(i,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(i)),ORMultiMapTag))) result ORMap(h -> ORSet(a, f, c, g), g -> ORSet(a, i, b, g, c, d))
[JVM-3]  result Map(h -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 60), g -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 22), i -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68)) vvector VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 60, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64324,1837082777) -> 25)
[JVM-3]  delta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(i)),(i,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(i)),ORMultiMapTag)))
[JVM-3]  deltaGroup Some(Vector(add elements: Map(i -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68)) vvector: VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68), del  elements: Map(i -> VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68)) vvector: VersionVector(UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64322,1837082777) -> 24, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64323,1837082777) -> 68, UniqueAddress(akka.trttl.gremlin.tcp://ReplicatorMapDeltaSpec@localhost:64324,1837082777) -> 25)))
```

**Comment by gosubpl** [comment]
And managed to replicate:
```
    "not have anomalies for remove+updated scenario and deltas 12" in {
      val m2a = ORMultiMap.empty[String, String].addBinding(node1, "q", "Q").removeBinding(node1, "q", "Q")
      val m1 = ORMultiMap.empty[String, String].addBinding(node1, "z", "Z").addBinding(node2, "x", "X")
        .removeBinding(node1, "z", "Z")

      val m2 = m2a.resetDelta.removeBinding(node2, "a", "A")

      val merged1 = m1 merge m2

      merged1.contains("a") should be(false)

      val merged2 = m1 mergeDelta m2.delta.get

      println("Delta " + m2.delta.get)

      merged2.entries("a") should be(Set())
    }
```

```
ORMap mergeDelta this ORMap(x -> ORSet(X)) thatDelta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(a)),(a,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(a)),ORMultiMapTag))) result ORMap(x -> ORSet(X), a -> ORSet())


mergeDelta DEBUG: Map(x -> VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 106)) vvector VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2551,1) -> 108, UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 106)
 result Map(x -> VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 106), a -> VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109)) vvector VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2551,1) -> 108, UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109)
 delta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(a)),(a,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(a)),ORMultiMapTag)))
 deltaGroup Some(Vector( add elements: Map(a -> VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109)) vvector: VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109),  del elements: Map(a -> VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109)) vvector: VersionVector(UniqueAddress(akka.tcp://Sys@localhost:2551,1) -> 103, UniqueAddress(akka.tcp://Sys@localhost:2552,2) -> 109)))
Delta DeltaGroup(Vector(PutDeltaOp(AddDeltaOp(ORSet(a)),(a,ORSet()),ORMultiMapTag), RemoveDeltaOp(RemoveDeltaOp(ORSet(a)),ORMultiMapTag)))
```

**Comment by gosubpl** [comment]
@patriknw good news, there is unit test replicating this. Will look into that later.

**Comment by gosubpl** [comment]
Reproducible with `ORSet` too:
```
    "not have anomalies for remove+updated scenario and deltas ugh" in {
      val m2a = ORSet.empty[String].add(node1, "q").remove(node1, "q")
      val m1 = ORSet.empty[String].add(node1, "z").add(node2, "x")
        .remove(node1, "z")

      val m2 = m2a.resetDelta.add(node2, "a").remove(node2, "a")

      val merged1 = m1 merge m2

      merged1.contains("a") should be(false)

      val merged2 = m1 mergeDelta m2.delta.get

      println("Delta " + m2.delta.get)

      val ORSet(mg2) = merged2
      mg2 should be(Set("x", "a")) // !!!
    }
```

**Comment by 2m** [comment]
One more datapoint of a nightly failure: https://jenkins.akka.io:8498/job/akka-nightly/4271/consoleFull

**Comment by patriknw** [comment]
I'm not sure if that scenario is possible in reality. I find it difficult to follow when writing multiple operations from different nodes on the same line. `add(node1, "z").add(node2, "x")`

"z" can't be added like that, it must have been added to m2a or the opposite. Operations from one node is always performed in sequence.

**Comment by gosubpl** [comment]
More realistic scenario:
```
    "not have anomalies for ORSet in complex but realistic scenario" in {
      val node1_1 = ORSet.empty[String].add(node1, "q").remove(node1, "q")
      val delta1_1 = node1_1.delta.get
      val node1_2 = node1_1.resetDelta.resetDelta.add(node1, "z").remove(node1, "z")
      val delta1_2 = node1_2.delta.get
      // we finished doing stuff on node1 - there are two separate deltas that will be propagated
      // node2 is created, then gets first delta from node1 and then adds an element "x"
      val node2_1 = ORSet.empty[String].mergeDelta(delta1_1).resetDelta.add(node2, "x")
      val delta2_1 = node2_1.delta.get
      // node2 continues its existence adding and later removing the element
      // it still didn't get the second update from node1 (that is fully legit :) )
      val node2_2 = node2_1.resetDelta.add(node2, "a").remove(node2, "a")
      val delta2_2 = node2_2.delta.get

      // in the meantime there is some node3
      // there is not much activity on it, it just gets the first delta from node1 then it gets
      // first delta from node2
      // then it gets the second delta from node1 (that node2 still didn't get, but, hey!, this is fine)
      val node3_1 = ORSet.empty[String].mergeDelta(delta1_1).mergeDelta(delta2_1).mergeDelta(delta1_2)

      // and node3_1 receives full update from node2 via gossip
      val merged1 = node3_1 merge node2_2

      merged1.contains("a") should be(false)

      // and node3_1 receives delta update from node2 (it just needs to get the second delta,
      // as it already got the first delta just a femtosecond ago :) )

      val merged2 = node3_1 mergeDelta delta2_2

      // KABOOM!

      val ORSet(mg2) = merged2
      mg2 should be(Set("x", "a")) // !!!
    }
```

**Comment by gosubpl** [comment]
@patriknw hopefully fixed by https://github.com/akka/akka/issues/22654
@2m many thanks for gathering additional failed cases, I will check them in the spec setting when I have few more minutes, to be double sure that everything works.
