### ISSUE TITLE
Failed: DDataClusterShardingLeaving

### ISSUE THREAD

**Issue by 2m** [akka/akka#22632]
https://jenkins.akka.io:8498/job/akka-nightly/4261/consoleFull

```
[JVM-1] - must recover after leaving coordinator node *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: expected class akka.cluster.sharding.ClusterShardingLeavingSpec$Locations, found class akka.remote.RemoteActorRef (Actor[akka.tcp://ClusterShardingLeavingSpec@localhost:60990/system/sharding/Entity/1/1#876114527])
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:488)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:460)
[JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:829)
```

**Comment by patriknw** [comment]
This should not be related to deltas. The error is:
```
[first] [ERROR] [03/25/2017 22:45:14.215] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-18] [akka.tcp://ClusterShardingLeavingSpec@first/system/sharding/EntityCoordinator/singleton/coordinator] The ShardCoordinator was unable to get an initial state within 'waiting-for-state-timeout' (was retrying): 5000 millis
[first] - must initialize shards *** FAILED ***
[first]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
[first]   at scala.Predef$.assert(Predef.scala:170)
[first]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:487)
[first]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:460)
[first]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:829)
[first]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7$$anonfun$4.apply(ClusterShardingLeavingSpec.scala:183)
[first]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$mcV$sp$7$$anonfun$4.apply(ClusterShardingLeavingSpec.scala:180)
```

Not sure why it couldn't retrieve the initial state. Could be just slowness.

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4284/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.4/232/consoleFull

Can't see an actual failure, just barriers failing. Lots of messages going to dead letter though.

```
[JVM-1] - must recover after leaving coordinator node *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-4
...
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2207/consoleFull
