### ISSUE TITLE
ORMultiMap delta issue for remove

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22648]
Reproducer in ORMultiMapSpec:

```scala
"be able to have its entries correctly merged with another ORMultiMap with overlapping entries 2" in {
      val m1 = ORMultiMap()
        .addBinding(node1, "b", "B1")
      val m2 = ORMultiMap()
        .addBinding(node2, "b", "B2")
        .remove(node2, "b")

      // merge both ways

      val expectedMerged = Map(
        "b" → Set("B1"))

      val merged1 = m1 merge m2
      merged1.entries should be(expectedMerged)

      val merged2 = m2 merge m1
      merged2.entries should be(expectedMerged)

      val merged3 = m1 mergeDelta m2.delta.get
      merged3.entries should be(expectedMerged)

      val merged4 = m2 mergeDelta m1.delta.get
      merged4.entries should be(expectedMerged)
    }
```

The results of the delta merge is not the same as the full state merge:
```
[info] - must be able to have its entries correctly merged with another ORMultiMap with overlapping entries 3 *** FAILED *** (11 milliseconds)
[info]   Map("b" -> Set("B1", "B2")) was not equal to Map("b" -> Set("B1")) (ORMultiMapSpec.scala:107)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.cluster.ddata.ORMultiMapSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ORMultiMapSpec.scala:107)
[info]   at akka.cluster.ddata.ORMultiMapSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(ORMultiMapSpec.scala:88)
```

**Comment by gosubpl** [comment]
Looking at this

**Comment by gosubpl** [comment]
Fix for this also fixes https://github.com/akka/akka/issues/22631
