### ISSUE TITLE
Failed: PersistentClusterShardingLeaving

### ISSUE THREAD

**Issue by 2m** [akka/akka#22709]
https://jenkins.akka.io:8498/job/akka-multi-node/2033/consoleFull

```
[JVM-1] [WARN] [04/11/2017 12:24:58.379] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-28] [akka://ClusterShardingLeavingSpec/system/sharding/Entity] received dead letter from Actor[akka.tcp://ClusterShardingLeavingSpec@a5.moxie:47601/system/testProbe-14#-665987041]: Ping(9)
[JVM-1] [WARN] [04/11/2017 12:24:59.492] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-28] [akka://ClusterShardingLeavingSpec/system/sharding/Entity] received dead letter from Actor[akka.tcp://ClusterShardingLeavingSpec@a5.moxie:47601/system/testProbe-15#-411990037]: Ping(9)
[JVM-2] - must recover after leaving coordinator node *** FAILED ***
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:486)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:468)
[JVM-2]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:828)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13$$anonfun$apply$mcV$sp$15.apply(ClusterShardingLeavingSpec.scala:213)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13$$anonfun$apply$mcV$sp$15.apply(ClusterShardingLeavingSpec.scala:209)
[JVM-2]   at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
[JVM-2]   at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply$mcV$sp(ClusterShardingLeavingSpec.scala:209)
[JVM-2]   at akka.cluster.sharding.ClusterShardingLeavingSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply(ClusterShardingLeavingSpec.scala:207)
[JVM-2]   ...
[JVM-1] [ERROR] [04/11/2017 12:25:00.532] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeavingSpec/user/controller/barriers] unannounced disconnect of RoleName(second) (akka.remote.testconductor.BarrierCoordinator$ClientLost)
[JVM-2] [INFO] [04/11/2017 12:25:00.538] [ClusterShardingLeavingSpec-akka.remote.default-remote-dispatcher-5] [akka.tcp://ClusterShardingLeavingSpec@a5.moxie:47601/system/remoting-terminator] Shutting down remote daemon.
[JVM-2] [INFO] [04/11/2017 12:25:00.541] [ClusterShardingLeavingSpec-akka.remote.default-remote-dispatcher-5] [akka.tcp://ClusterShardingLeavingSpec@a5.moxie:47601/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[JVM-1] - must recover after leaving coordinator node *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-4
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
[JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:157)
[JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-1]   ...
[JVM-3] - must recover after leaving coordinator node *** FAILED ***
[JVM-3]   java.lang.RuntimeException: barrier failed: after-4
[JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-3]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-3]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-3]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
[JVM-3]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-3]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:157)
[JVM-3]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-3]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-3]   at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-3]   ...
[JVM-1] [WARN] [04/11/2017 12:25:00.551] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-28] [akka://ClusterShardingLeavingSpec/user/controller/barriers] cannot remove RoleName(first): no client to remove
[JVM-4] - must recover after leaving coordinator node *** FAILED ***
[JVM-4]   java.lang.RuntimeException: barrier failed: after-4
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:663)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:157)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-4]   ...
[JVM-3] [INFO] [04/11/2017 12:25:00.569] [ClusterShardingLeavingSpec-akka.remote.default-remote-dispatcher-21] [akka.tcp://ClusterShardingLeavingSpec@a6.moxie:55350/system/remoting-terminator] Shutting down remote daemon.
[JVM-3] [INFO] [04/11/2017 12:25:00.572] [ClusterShardingLeavingSpec-akka.remote.default-remote-dispatcher-21] [akka.tcp://ClusterShardingLeavingSpec@a6.moxie:55350/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[JVM-3] [WARN] [04/11/2017 12:25:00.578] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-23] [akka://ClusterShardingLeavingSpec/deadLetters] received dead letter from Actor[akka://ClusterShardingLeavingSpec/system/cluster/core/daemon/heartbeatSender#860780196]: Heartbeat(akka.tcp://ClusterShardingLeavingSpec@a6.moxie:55350)
[JVM-3] [INFO] [04/11/2017 12:25:00.578] [ClusterShardingLeavingSpec-akka.actor.default-dispatcher-16] [akka://ClusterShardingLeavingSpec/deadLetters] Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://ClusterShardingLeavingSpec/system/cluster/core/daemon/heartbeatSender#860780196] to Actor[akka://ClusterShardingLeavingSpec/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by patriknw** [comment]
After the Aeron 1.2.4 update processes for multi-node tests were still alive on a5, running at full cpu throttle.
So closing because it was probably a symptom of that.
