### ISSUE TITLE
Failed: ArteryRemoteReDeploymentSlow

### ISSUE THREAD

**Issue by 2m** [akka/akka#22708]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/176/consoleFull

```
[JVM-1] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (13 seconds, 717 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message PostStop
[JVM-1]   at scala.Predef$.assert(Predef.scala:219)
[JVM-1]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:630)
[JVM-1]   at akka.testkit.TestKitBase.expectNoMsg(TestKit.scala:626)
[JVM-1]   at akka.testkit.TestKitBase.expectNoMsg$(TestKit.scala:626)
[JVM-1]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:828)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec.$anonfun$new$2(RemoteReDeploymentSpec.scala:177)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$Lambda$492/1161322357.apply$mcV$sp(Unknown Source)
[JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[JVM-1]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[JVM-1]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[JVM-1]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[JVM-1]   at akka.remote.RemotingMultiNodeSpec.withFixture(RemotingMultiNodeSpec.scala:37)
[JVM-1]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
```

**Comment by patriknw** [comment]
After the Aeron 1.2.4 update processes for multi-node tests were still alive on a5, running at full cpu throttle.
So closing because it was probably a symptom of that.
