### ISSUE TITLE
 Failed to persist event 

### ISSUE THREAD

**Issue by leruy** [akka/akka#22727]
build.sbt:

```
scalaVersion := "2.11.8"
 "com.typesafe.akka" %% "akka-actor" % "2.4.17",
  "com.typesafe.akka" %% "akka-remote" % "2.4.17",
  "com.typesafe.akka" %% "akka-persistence" % "2.4.17",
  "com.typesafe.akka" %% "akka-cluster" % "2.4.17",
  "com.typesafe.akka" %% "akka-cluster-tools" % "2.4.17",
  "com.typesafe.akka" %% "akka-slf4j" % "2.4.17"
  "mysql" % "mysql-connector-java" % "6.0.5",
  "org.mybatis" % "mybatis" % "3.4.1",
```

we used 'jdbc-journal' for "akka.persistence.journal.plugin".
configuration as follows:

```
jdbc-journal {
  slick = ${slick}
  slick.db.numThreads = 20
  slick.db.maxConnections = 40
  slick.db.minConnections = 1
  recovery-event-timeout = 60m
}
...jdbc-snapshot-store omitted.

The program run after a period of time, then threw exception :
2017-04-14 20:19:27,363 ERROR c.x.c.backend.users.UserProcessor - Failed to persist event type [com.xinguodu.coincola.data.users.UserMessage$DoResetPassword] with sequence number [224] for persistenceId [user_processor].
java.sql.BatchUpdateException: Duplicate entry 'user_processor-224' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.core.util.Util.handleNewInstance(Util.java:185)
	at com.mysql.cj.core.util.Util.getInstance(Util.java:168)
	at com.mysql.cj.core.util.Util.getInstance(Util.java:175)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:636)
	at com.mysql.cj.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1544)
	at com.mysql.cj.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1209)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:1009)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.LoggingStatement$$anonfun$executeBatch$1.apply(LoggingStatement.scala:41)
	at slick.jdbc.LoggingStatement$$anonfun$executeBatch$1.apply(LoggingStatement.scala:41)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:16)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:41)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$anonfun$run$9.apply(JdbcActionComponent.scala:529)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$anonfun$run$9.apply(JdbcActionComponent.scala:523)
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:347)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:407)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:498)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:523)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'user_processor-224' for key 'PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:533)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2034)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:1970)
	at com.mysql.cj.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:4984)
	at com.mysql.cj.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1505)
	... 21 common frames omitted
```

We call 'persist' as follows:
```
 persist(doResetPassword, resetPassword -> {
                    updateState(resetPassword);
                });
```

**Comment by patriknw** [comment]
Do you have two active user_processor at the same time. Duplicate primary key.

Anyway, I don't think this is an akka/akka issue. Questions are better asked at akka-user google group.

**Comment by leruy** [comment]
Thanks. I am checked repeatedly.
Maybe we have two active user_processor at the same time as you said.

**Comment by ktoso** [comment]
That's illegal and should fail indeed - Akka Persistence explicitly requires / rides upon the "single writer principle".

Please read about cluster sharding http://doc.akka.io/docs/akka/current/scala/cluster-sharding.html and the split brain resolver http://doc.akka.io/docs/akka/akka-commercial-addons-1.0/scala/split-brain-resolver.html 
to see how akka provides tools to help avoid this situation.
