### ISSUE TITLE
failed: TypedSpecSpec not terminating

### ISSUE THREAD

**Issue by patriknw** [akka/akka#22763]
The test is not failing, but it looks like something is wrong in the shutdown.

```
[info] TypedSpecSetup:
[info] TypedSpecSpec:
[info] A TypedSpec
[info]   when using the adapted implementation
[ERROR] [04/21/2017 09:04:02.429] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-7] [akka://TypedSpec_AdaptedSystem_class/user/failure] expected
akka.actor.ActorInitializationException: akka://TypedSpec_AdaptedSystem_class/user/failure: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
	at akka.actor.ActorCell.create(ActorCell.scala:600)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:454)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:476)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.scalatest.exceptions.TestFailedException: expected
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.refspec.RefSpec.newAssertionFailedException(RefSpec.scala:1331)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1089)
	at org.scalatest.refspec.RefSpec.fail(RefSpec.scala:1331)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:211)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:211)
	at akka.typed.StepWise$.akka$typed$StepWise$$run(StepWise.scala:134)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:113)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:112)
	at akka.typed.scaladsl.Actor$Deferred.apply(Actor.scala:212)
	at akka.typed.Behavior$.undefer(Behavior.scala:159)
	at akka.typed.internal.adapter.ActorAdapter.preStart(ActorAdapter.scala:61)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:521)
	at akka.typed.internal.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:14)
	at akka.actor.ActorCell.create(ActorCell.scala:583)
	... 9 more

-> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 3 children
   |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
   |   ⌊-> eventStreamUnsubscriber-14 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
   |   ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
   ⌊-> user LocalActorRef class akka.typed.internal.adapter.ActorAdapter status=0 no children
-> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 3 children
   |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
   |   ⌊-> eventStreamUnsubscriber-14 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
   |   ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
   ⌊-> user LocalActorRef class akka.typed.internal.adapter.ActorAdapter status=0 no children
[info]   - must report failures (28 milliseconds)
[info]   when using the native implementation
[ERROR] [04/21/2017 09:04:02.437] [TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1-akka.actor.default-dispatcher-2] [typed://TypedSpecSpec_A_u0020TypedSpec_CommonTests__anonfun_must_u0020report_u0020failures_1/user/failure] expected
org.scalatest.exceptions.TestFailedException: expected
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.refspec.RefSpec.newAssertionFailedException(RefSpec.scala:1331)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1089)
	at org.scalatest.refspec.RefSpec.fail(RefSpec.scala:1331)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:211)
	at akka.typed.TypedSpecSpec$A$u0020TypedSpec$CommonTests$$anonfun$must$u0020report$u0020failures$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2.apply(TypedSpec.scala:211)
	at akka.typed.StepWise$.akka$typed$StepWise$$run(StepWise.scala:134)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:113)
	at akka.typed.StepWise$$anonfun$apply$1.apply(StepWise.scala:112)
	at akka.typed.scaladsl.Actor$Deferred.apply(Actor.scala:212)
	at akka.typed.Behavior$.undefer(Behavior.scala:159)
	at akka.typed.internal.SupervisionMechanics$class.create(SupervisionMechanics.scala:71)
	at akka.typed.internal.SupervisionMechanics$class.processSignal(SupervisionMechanics.scala:52)
	at akka.typed.internal.ActorCell.processSignal(ActorCell.scala:68)
	at akka.typed.internal.ActorCell.liftedTree1$1(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.processAllSystemMessages(ActorCell.scala:384)
	at akka.typed.internal.ActorCell.run(ActorCell.scala:281)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

-> system LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 1-receptionist LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 2-eventStreamUnsubscriber LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 3-log1-DefaultLogger LocalActorRef class akka.typed.Behavior$EmptyBehavior$ status=0 nextMsg=null
       ⌊-> logger LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
-> user LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
-> system LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 1-receptionist LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 2-eventStreamUnsubscriber LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
   ⌊-> 3-log1-DefaultLogger LocalActorRef class akka.typed.Behavior$EmptyBehavior$ status=0 nextMsg=null
       ⌊-> logger LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
-> user LocalActorRef class akka.typed.scaladsl.Actor$Immutable status=0 nextMsg=null
```

and also
```
[WARN] [04/21/2017 09:04:22.755] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-4] [akka://TypedSpec_AdaptedSystem_class/deadLetters] received dead letter from Actor[akka://TypedSpec_AdaptedSystem_class/deadLetters]: Timedout
[WARN] [04/21/2017 09:04:23.214] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-4] [akka://TypedSpec_AdaptedSystem_class/deadLetters] received dead letter from Actor[akka://TypedSpec_AdaptedSystem_class/deadLetters]: Timedout
[WARN] [04/21/2017 09:04:23.333] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-4] [akka://TypedSpec_AdaptedSystem_class/deadLetters] received dead letter from Actor[akka://TypedSpec_AdaptedSystem_class/deadLetters]: Timedout
[WARN] [04/21/2017 09:04:23.834] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-4] [akka://TypedSpec_AdaptedSystem_class/deadLetters] received dead letter from Actor[akka://TypedSpec_AdaptedSystem_class/deadLetters]: Timedout
[WARN] [04/21/2017 09:04:23.923] [TypedSpec_AdaptedSystem_class-akka.actor.default-dispatcher-4] [akka://TypedSpec_AdaptedSystem_class/deadLetters] received dead letter from Actor[akka://TypedSpec_AdaptedSystem_class/deadLetters]: Timedout
...
```

**Comment by raboof** [comment]
@patriknw I don't see the `Timedout` warnings.

The other stacktraces are 'expected': they're printed when the test `must report failures` indeed fails and reports its (expected) failure (https://github.com/akka/akka/blob/wip-akka-typed-dev/akka-typed-tests/src/test/scala/akka/typed/TypedSpec.scala#L105).

Should we try and use something else instead of `println` there and somehow suppress that output in this test?

**Comment by 2m** [comment]
I also noticed these timeout warnings. I ran all tests with `akka-typed-tests/test` and then after all tests finish and after some time (a minute or two) these warnings where printed out. So something was not stopped after the tests ran.

**Comment by raboof** [comment]
Ah maybe I didn't wait long enough - let me check :)

**Comment by raboof** [comment]
Can we close this or should we look into suppressing the logging?

**Comment by patriknw** [comment]
Leave it open until I have checked again, I think I saw something that was not looking good also in latest.

**Comment by patriknw** [comment]
It was nothing wrong, but the printTree is scary because that it is normally an indication of that ActorSystem couldn't be shutdown. Fixed in https://github.com/akka/akka/pull/22832
