### ISSUE TITLE
FAILED: jdocs.future.FutureDocTest thenApplyAsyncExecutor

### ISSUE THREAD

**Issue by ktoso** [akka/akka#22888]
https://jenkins.akka.io:8498/job/akka-nightly/4395/testReport/junit/jdocs.future/FutureDocTest/thenApplyAsyncExecutor/

```
Error Message

java.util.concurrent.TimeoutException
Stacktrace

      java.util.concurrent.TimeoutException
      at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1763)
      at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907)
      at jdocs.future.FutureDocTest.thenApplyAsyncExecutor(FutureDocTest.java:649)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

**Comment by 2m** [comment]
Increased MetaSize of akka-nightly job to 768. Closing this one and https://github.com/akka/akka/issues/22839 and see if that happens more.
