### ISSUE TITLE
Akka typed scala.MatchError: null

### ISSUE THREAD

**Issue by greenhost87** [akka/akka#22946]
I write simple code to test brand new Akka Typed performance, as a playground I use https://github.com/patriknw/akka-typed-blog and try run that code

```scala
object Messages {
  sealed trait Message

  case object Increment extends Message

  case object Ok extends Message

  case object Result extends Message
}

class TypedActor(ctx: ActorContext[Messages.Message], start: Long) extends akka.typed.scaladsl.Actor.MutableBehavior[Messages.Message] {
  var i: Long = 0

  import Messages._

  override def onMessage(msg: Message): Behavior[Message] = {
    msg match {
      case Increment =>
        i += 1
      case Result =>
        println(s"Current i is [$i]")
        println(s"Took [${(System.nanoTime() - start) / 1000000000.00}] seconds")
        ctx.system.terminate()
    }

    this
  }
}

object TypedPerformanceTest extends App {

  import Messages._

  val root = akka.typed.scaladsl.Actor.deferred[Nothing] { ctx =>
    val actor: ActorRef[Messages.Message] = ctx.spawn(akka.typed.scaladsl.Actor.mutable[Message](ctx => new TypedActor(ctx, System.nanoTime())), "counter")

    implicit val ex = ctx.system.executionContext

    Future.sequence {
      1 to 2 map { _ =>
        Future {
          1 to 10000000 foreach { _ =>
            actor ! Messages.Increment
          }
        }
      }
    }.foreach { _ =>
      actor ! Messages.Result
    }

    akka.typed.scaladsl.Actor.empty
  }

  val system = akka.typed.ActorSystem[Nothing]("HelloWorld", root)
}
```

As result application crash with error:

```
scala.MatchError: null
	at TypedActor.onMessage(PerfomanceTest.scala:41)
	at TypedActor.onMessage(PerfomanceTest.scala:35)
	at akka.typed.scaladsl.Actor$MutableBehavior.receiveMessage(Actor.scala:84)
	at akka.typed.Behavior$.interpret(Behavior.scala:275)
	at akka.typed.Behavior$.interpretMessage(Behavior.scala:257)
	at akka.typed.internal.ActorCell.processMessage(ActorCell.scala:374)
	at akka.typed.internal.ActorCell.run(ActorCell.scala:286)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

If change number of concurrent runing futures from 2 to 1 application complete work without error

**Comment by patriknw** [comment]
Thanks for trying Akka Typed. I have tried and can confirm that it's a bug. `null` is actually passed in as the message. Could be a concurrency bug or invalid catch of OutOfMemoryError.

By the way, that is useless a performance test but great that you found the issue.

**Comment by greenhost87** [comment]
I continue play with typed actors and try immutable approach with JMH. Below my simple code with JMH that have some `null` problem, maybe it can be helpful:

```scala
package com.github.greenhost87.akka.typed

import akka.typed.scaladsl.Actor
import akka.typed.scaladsl.Actor.MutableBehavior
import akka.typed.{ActorSystem, Behavior}
import org.openjdk.jmh.annotations._

object Messages {

  sealed trait Message

  case object Increment extends Message

  case object Result extends Message

}

import Messages._

@State(Scope.Benchmark)
class MutableTypedActor {

  var actor: ActorSystem[Message] = _

  @Setup
  def setup(): Unit = {
    actor = ActorSystem[Message]("JMH", behavior)
  }

  @TearDown
  def tearDown(): Unit = {
    actor.terminate()
  }

  private def behavior: Behavior[Message] = new MutableBehavior[Message] {
    var i: Long = 0

    override def onMessage(msg: Message): Behavior[Message] = {
      msg match {
        case Increment =>
          i += 1
        case Result =>
          println(s"Current i is [$i]")
      }

      this
    }
  }
}

@State(Scope.Benchmark)
class ImmutableTypedActor {

  var actor: ActorSystem[Message] = _

  @Setup
  def setup(): Unit = {
    actor = ActorSystem[Message]("JMH", behavior(0))
  }

  @TearDown
  def tearDown(): Unit = {
    actor.terminate()
  }

  private def behavior(i: Long = 0): Behavior[Message] = Actor.immutable[Message] { (ctx, msg) =>
    msg match {
      case Increment =>
        behavior(i + 1)
      case Result =>
        println(s"Current i is [$i]")
        Actor.same
    }
  }
}

class AkkaTypedJmh {
  @Benchmark
  def mutableActorTest(mta: MutableTypedActor): Unit = {
    mta.actor ! Messages.Increment
  }

  @Benchmark
  def immutableActorTest(ita: ImmutableTypedActor): Unit = {
    ita.actor ! Messages.Increment
  }
}
```

**Comment by patriknw** [comment]
You could try to convert this: https://github.com/akka/akka/blob/master/akka-bench-jmh/src/main/scala/akka/actor/ForkJoinActorBenchmark.scala

**Comment by greenhost87** [comment]
I try https://gist.github.com/greenhost87/5f5beb39b7202e7b75553c9ff8463119 but I can't figure out how to change that code https://gist.github.com/greenhost87/5f5beb39b7202e7b75553c9ff8463119#file-forkjointypedactorbenchmark-scala-L104-L108 and look like something wrong with system termination, because after end of each test I get:

```
[info] <JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 4 seconds more...>
[info] 
[info] Non-finished threads:
[info] 
[info] Thread[ForkJoinActorBenchmark-akka.actor.default-dispatcher-6,5,main]
[info]   at sun.misc.Unsafe.park(Native Method)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] 
[info] Thread[ForkJoinActorBenchmark-akka.actor.default-dispatcher-3,5,main]
[info]   at sun.misc.Unsafe.park(Native Method)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
