### ISSUE TITLE
FAILED: LeaderElectionWithFailureDetectorPuppet (artery)

### ISSUE THREAD

**Issue by raboof** [akka/akka#22982]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/617/consoleFull
```
[JVM-2] LeaderElectionWithFailureDetectorPuppetMultiJvmNode2:
[JVM-5] A cluster of four nodes
[JVM-3] A cluster of four nodes
[JVM-4] A cluster of four nodes
[JVM-2] A cluster of four nodes
[JVM-2] [INFO] [05/13/2017 10:15:44.671] [LeaderElectionSpec-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Node [akka://LeaderElectionSpec@a5.moxie:47657] is JOINING, roles []
[JVM-2] [INFO] [05/13/2017 10:15:44.687] [LeaderElectionSpec-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Leader is moving node [akka://LeaderElectionSpec@a5.moxie:47657] to [Up]
[JVM-2] [INFO] [05/13/2017 10:15:45.456] [LeaderElectionSpec-akka.actor.default-dispatcher-9] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Node [akka://LeaderElectionSpec@a5.moxie:36228] is JOINING, roles []
[JVM-2] [INFO] [05/13/2017 10:15:45.465] [LeaderElectionSpec-akka.actor.default-dispatcher-9] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Node [akka://LeaderElectionSpec@a6.moxie:35178] is JOINING, roles []
[JVM-4] [INFO] [05/13/2017 10:15:45.569] [LeaderElectionSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:36228] - Welcome from [akka://LeaderElectionSpec@a5.moxie:47657]
[JVM-3] [INFO] [05/13/2017 10:15:45.572] [LeaderElectionSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a6.moxie:35178] - Welcome from [akka://LeaderElectionSpec@a5.moxie:47657]
[JVM-2] [INFO] [05/13/2017 10:15:45.579] [LeaderElectionSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Leader is moving node [akka://LeaderElectionSpec@a5.moxie:36228] to [Up]
[JVM-2] [INFO] [05/13/2017 10:15:45.579] [LeaderElectionSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://LeaderElectionSpec)] Cluster Node [akka://LeaderElectionSpec@a5.moxie:47657] - Leader is moving node [akka://LeaderElectionSpec@a6.moxie:35178] to [Up]
[JVM-5] [ERROR] [05/13/2017 10:15:46.818] [LeaderElectionSpec-akka.actor.default-dispatcher-11] [TaskInvocation] Unsupported field: OffsetSeconds
[JVM-5] java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
[JVM-5] 	at java.time.LocalDate.get0(LocalDate.java:680)
[JVM-5] 	at java.time.LocalDate.getLong(LocalDate.java:659)
[JVM-5] 	at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
[JVM-5] 	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
[JVM-5] 	at java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3338)
[JVM-5] 	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2182)
[JVM-5] 	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1744)
[JVM-5] 	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1718)
[JVM-5] 	at akka.remote.artery.AeronErrorLog.lambda$logErrors$0(AeronErrorLog.java:77)
[JVM-5] 	at akka.remote.artery.AeronErrorLog$$Lambda$26/1178986264.accept(Unknown Source)
[JVM-5] 	at org.agrona.concurrent.errors.ErrorLogReader.read(ErrorLogReader.java:69)
[JVM-5] 	at akka.remote.artery.AeronErrorLog.logErrors(AeronErrorLog.java:71)
[JVM-5] 	at akka.remote.artery.ArteryTransport$$anonfun$startAeronErrorLog$1.apply$mcV$sp(ArteryTransport.scala:617)
[JVM-5] 	at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:83)
[JVM-5] 	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(LightArrayRevolverScheduler.scala:101)
[JVM-5] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
[JVM-5] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
[JVM-5] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-5] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-5] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-5] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[JVM-5] 
[JVM-5] [ERROR] [05/13/2017 10:16:04.996] [LeaderElectionSpec-akka.remote.default-remote-dispatcher-14] [akka.remote.artery.Association(akka://LeaderElectionSpec)] Outbound control stream to [akka://LeaderElectionSpec@a5.moxie:47657] failed. Restarting it. Handshake with [akka://LeaderElectionSpec@a5.moxie:47657] did not complete within 20000 ms (akka.remote.artery.OutboundHandshake$HandshakeTimeoutException)
[JVM-5] [ERROR] [05/13/2017 10:16:05.035] [LeaderElectionSpec-akka.remote.default-remote-dispatcher-8] [akka.remote.artery.Association(akka://LeaderElectionSpec)] Outbound message stream to [akka://LeaderElectionSpec@a5.moxie:47657] failed. Restarting it. Handshake with [akka://LeaderElectionSpec@a5.moxie:47657] did not complete within 20000 ms (akka.remote.artery.OutboundHandshake$HandshakeTimeoutException)
[JVM-2] 27.799: [GC (Allocation Failure) [PSYoungGen: 76282K->10732K(76288K)] 79829K->20170K(251392K), 0.0359463 secs] [Times: user=0.15 sys=0.06, real=0.03 secs] 
[JVM-2] - must be able to 'elect' a single leader *** FAILED *** (25 seconds, 114 milliseconds)
[JVM-2]   3 did not equal 4 (MultiNodeClusterSpec.scala:305)
[JVM-2]   org.scalatest.exceptions.TestFailedException:
[JVM-2]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[JVM-2]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:305)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$mcV$sp$3.apply(MultiNodeClusterSpec.scala:305)
[JVM-2]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:302)
[JVM-2]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:313)
[JVM-2]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:828)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply$mcV$sp(MultiNodeClusterSpec.scala:305)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:302)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:302)
[JVM-2]   at akka.testkit.TestKitBase$class.within(TestKit.scala:344)
[JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:828)
[JVM-2]   at akka.testkit.TestKitBase$class.within(TestKit.scala:358)
[JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:828)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$class.awaitMembersUp(MultiNodeClusterSpec.scala:302)
[JVM-2]   at akka.cluster.LeaderElectionSpec.awaitMembersUp(LeaderElectionSpec.scala:37)
[JVM-2]   at akka.cluster.MultiNodeClusterSpec$class.awaitClusterUp(MultiNodeClusterSpec.scala:224)
[JVM-2]   at akka.cluster.LeaderElectionSpec.awaitClusterUp(LeaderElectionSpec.scala:37)
```

**Comment by patriknw** [comment]
strange, I thought we fixed all those. I'll take a look.

**Comment by patriknw** [comment]
It's indeed an issue:
```
import java.time.format._
import java.time.format._

val timeZone = ZoneId.systemDefault()
val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSSZ")
formatter.format(LocalDateTime.ofInstant(Instant.ofEpochMilli(System.currentTimeMillis()), timeZone))

java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
  at java.time.LocalDate.get0(LocalDate.java:680)
  at java.time.LocalDate.getLong(LocalDate.java:659)
  at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
  at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
  at java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3335)
  at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
  at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
  at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
```
