### ISSUE TITLE
FAILED: DDataClusterShardingRememberEntities

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#22994]
https://jenkins.akka.io:8498/job/akka-multi-node/2094/consoleFull

```
[JVM-1] - must start remembered entities in new cluster *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: timeout (29595957220 nanoseconds) during expectMsgClass waiting for class akka.cluster.sharding.ClusterShardingRememberEntitiesSpec$Started
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:486)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:459)
[JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:828)
[JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec$$anonfun$1$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13$$anonfun$apply$mcV$sp$15.apply$mcV$sp(ClusterShardingRememberEntitiesSpec.scala:215)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:355)
[JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec$$anonfun$1$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply$mcV$sp(ClusterShardingRememberEntitiesSpec.scala:213)
[JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec$$anonfun$1$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply(ClusterShardingRememberEntitiesSpec.scala:205)
[JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec$$anonfun$1$$anonfun$apply$mcV$sp$12$$anonfun$apply$mcV$sp$13.apply(ClusterShardingRememberEntitiesSpec.scala:205)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:344)
[JVM-1]   ...
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/721/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/630/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/631/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2095/consoleFull

**Comment by jrudolph** [comment]
(Stopping here, there are more)

**Comment by patriknw** [comment]
These are all multi-node and the problem is that the test is assuming that it could use the same directory (lmdb data) for node first and second node, but that will of course not work when it's multi-node.
