### ISSUE TITLE
akka.remote.ResendUnfulfillableException: Unable to fulfill resend request since negatively acknowledged payload is no longer in buffer. The resend states between two systems are compromised and cannot be recovered.

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23010]
We have seen a few (but infrequent) reports of quarantining happening with this error message.

The error messages usually look like this:

```
Association to [...] with UID [...] irrecoverably failed. Quarantining address. 
java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [7 {1, 2, 3, 4, 5, 6, 7}] ack: ACK[7, {0}] 
at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:301) 
at akka.actor.Actor$class.aroundReceive(Actor.scala:484) 
at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:200) 
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) 
at akka.actor.ActorCell.invoke(ActorCell.scala:495) 
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) 
at akka.dispatch.Mailbox.run(Mailbox.scala:224) 
at akka.dispatch.Mailbox.exec(Mailbox.scala:234) 
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) 
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) 
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) 
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
Caused by: akka.remote.ResendUnfulfillableException: Unable to fulfill resend request since negatively acknowledged payload is no longer in buffer. The resend states between two systems are compromised and cannot be recovered. 
at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:107) 
at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:297) 
... 11 common frames omitted 
```

The particular acknowledgement setup can be different.

We have seen reports for this occurring on Akka 2.4.7, 2.4.11, and 2.4.17.

It seems to happen under different kind of circumstances:
 * node is restarted
 * temporary unreachability of a node due to GC
 * underlying connection breakdown due to external causes

So far, we haven't been able to reproduce the issue or having been able to get hold of a complete set of logs that would allow us to reproduce the issue.

Maybe related: https://github.com/akka/akka/issues/16623 and https://github.com/akka/akka/issues/19780

**Comment by jrudolph** [comment]
The error message means that the sending side of a system message first receives acknowledgement for a message and then later receives a negative acknowledgement for that same message.

How could that happen? IIUC these buffers and management data structures are kept even if the physical connection had to be reestablished.

E.g. in the case above

```
 acknowledgement buffer: [7 {1, 2, 3, 4, 5, 6, 7}] ack: ACK[7, {0}] 
```

Message 0 was likely confirmed earlier. The receiver then seems to "have forgotten" about that message and when it receives other messages later on it sends a negative acknowledgement for that message. The question is why this information gets lost at some point.

**Comment by 412b** [comment]
hi hAkkers
we've just recently hit that particular bug in production, so can this be pushed a bit and released faster? :)
I see it being a hidden timebomb in our cluster and fix for it is critical :)

**Comment by patriknw** [comment]
We will release on Monday

**Comment by 412b** [comment]
@patriknw thank you, I see release for 2.4. is there a chance to see 2.5 with this fix soon?

**Comment by patriknw** [comment]
yes, we will release 2.5.3 in a few days
