### ISSUE TITLE
FAILED: ActorDocSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23013]
https://jenkins.akka.io:8498/job/akka-multi-node/2101/console

```
[info] - run basic Ping Pong *** FAILED *** (558 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected: Terminated Actor[akka://pingpong/user/pinger#302387757] but got unexpected message Terminated(Actor[akka://pingpong/user/ponger#-1330229420])
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:405)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:828)
[info]   at akka.testkit.TestKitBase$class.expectTerminated(TestKit.scala:416)
[info]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:828)
[info]   at docs.actor.ActorDocSpec$$anonfun$14.apply(ActorDocSpec.scala:380)
[info]   at docs.actor.ActorDocSpec$$anonfun$14.apply(ActorDocSpec.scala:360)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4937/testReport/junit/docs.actor/ActorDocSpec/run_basic_Ping_Pong/

**Comment by patriknw** [comment]
that's a very simple race, I'll fix right away
