### ISSUE TITLE
ArteryRemoteDeliveryMultiJvm

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23115]
https://jenkins.akka.io:8498/job/akka-nightly/4472/consoleFull

```
[JVM-1] - must not drop messages under normal circumstances *** FAILED *** (192 milliseconds)
[JVM-1]   java.util.NoSuchElementException: None.get
[JVM-1]   at scala.None$.get(Option.scala:347)
[JVM-1]   at scala.None$.get(Option.scala:345)
[JVM-1]   at akka.remote.RemoteDeliverySpec$$anonfun$identify$1.apply(RemoteDeliverySpec.scala:59)
[JVM-1]   at akka.remote.RemoteDeliverySpec$$anonfun$identify$1.apply(RemoteDeliverySpec.scala:57)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:344)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:828)
[JVM-1]   at akka.testkit.TestKitBase$class.within(TestKit.scala:358)
[JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:828)
```

**Comment by patriknw** [comment]
That's strange. Test looks valid, with barrier and such.

**Comment by raboof** [comment]
(closing as outdated rare failure)
