### ISSUE TITLE
LoggingReceiveSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23140]
An Actor must log LifeCycle events if requested

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4980/testReport/junit/akka.event/LoggingReceiveSpec/An_Actor_must_log_LifeCycle_events_if_requested/
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4981/

```
 org.scalatest.exceptions.TestFailedException: Set(0, 1) did not equal Set(0, 1, 2)
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
      at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
      at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
      at akka.event.LoggingReceiveSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$10.akka$event$LoggingReceiveSpec$$anonfun$$anonfun$$anon$$expectMsgAllPF(LoggingReceiveSpec.scala:267)
      at akka.event.LoggingReceiveSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$10$$anonfun$21.apply(LoggingReceiveSpec.scala:232)
      at akka.event.LoggingReceiveSpec$$anonfun$2$$anonfun$apply$mcV$sp$9$$anon$10$$anonfun$21.apply(LoggingReceiveSpec.scala:227)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4488/testReport/junit/akka.event/LoggingReceiveSpec/An_Actor_must_log_LifeCycle_events_if_requested/
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/4989/
