### ISSUE TITLE
failed: FlowSplitWhenSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23199]
https://jenkins.akka.io:8498/job/akka-release-2.4/246

Note: 2.4

```
[info] - must fail substream if materialized twice *** FAILED *** (2 seconds, 44 milliseconds)
[info]   Expected exception java.lang.IllegalStateException to be thrown, but no exception was thrown (FlowSplitWhenSpec.scala:260)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.words.ResultOfAnTypeInvocation.mustBe(ResultOfAnTypeInvocation.scala:155)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$14$$anonfun$apply$18.apply(FlowSplitWhenSpec.scala:260)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$14$$anonfun$apply$18.apply(FlowSplitWhenSpec.scala:260)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$14.apply(FlowSplitWhenSpec.scala:259)
[info]   at akka.stream.scaladsl.FlowSplitWhenSpec$$anonfun$2$$anonfun$apply$mcV$sp$14.apply(FlowSplitWhenSpec.scala:259)
```

**Comment by agolubev** [comment]
Per my understanding,  there is a race condition between Sink.ignore in the test and functionality that fails stream once the second materialization captured. 
I'm now trying to rewrite it in a proper way.

**Comment by johanandren** [comment]
Merged but we missed to close it seems.
