### ISSUE TITLE
avoid match error for null message in DistributedPubSubMediator

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23215]
Sending null message can't work, but we should not throw match error.
```
[info] [ERROR] [06/14/2017 21:55:18.433] [ClusterSystem-akka.actor.default-dispatcher-3] [akka://ClusterSystem/system/distributedPubSubMediator] null
[info] scala.MatchError: null
[info]  at akka.cluster.pubsub.DistributedPubSubMediator$Internal$$anonfun$wrapIfNeeded$1.apply(DistributedPubSubMediator.scala:400)
[info]  at akka.cluster.pubsub.DistributedPubSubMediator$$anonfun$receive$1.applyOrElse(DistributedPubSubMediator.scala:550)
[info]  at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
[info]  at akka.cluster.pubsub.DistributedPubSubMediator.aroundReceive(DistributedPubSubMediator.scala:479)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:495)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info]  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info]  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ktoso** [comment]
I can fix that one, unless you started hacking on it already @patriknw?
Just adding a check and throwing explicitly is what we want here I assume?

**Comment by patriknw** [comment]
I have not started. Use `InvalidMessageException`, we use that in Envelope
