### ISSUE TITLE
TestKitBase.expectNoMsg can sometimes fail after timeout passed

### ISSUE THREAD

**Issue by manonthegithub** [akka/akka#23224]
I've continued investigation on [#90 in stream contrib](https://github.com/akka/akka-stream-contrib/pull/90) and got some new results.
I've decided to switch to akka project to alter expectNoMsg in order to get more info. Here's altered version of expectNoMsg_internal which is called inside expectNoMsg:
```scala
private def expectNoMsg_internal(max: FiniteDuration) {
    val start = System.nanoTime()
    val o = receiveOne(max)
    val diff = System.nanoTime() - start
   //just measure start and finish and print it before check
    println(s"Diff was: $diff elem $o")
    assert(o eq null, s"received unexpected message $o")
    lastWasNoMsg = true
  }
```
then I run this simplified test:
```scala
"ttt" taggedAs TimingTest in {

      class Delay extends SimpleLinearGraphStage[Int] {

        override def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new TimerGraphStageLogic(shape) with InHandler with OutHandler {

          case object Key

          var elem: Int = _

          override def onPull(): Unit = {
            pull(in)
          }

          override def onPush(): Unit = {
            elem = grab(in)
            scheduleOnce(Key, 1 second)
          }

          override def onTimer(timerKey: Any): Unit = {
            push(out, elem)
            if (isClosed(in)) {
              completeStage()
            }
          }

          override def onUpstreamFinish(): Unit = {
            if (!isTimerActive(Key)) {
              completeStage()
            }
          }

          setHandler(out, this)
          setHandler(in, this)

        }
      }

      for (_ ← 1 to 10000) {
        val li = List(1, 2)
        val c = TestSubscriber.manualProbe[Int]()
        Source(li).via(new Delay).to(Sink.fromSubscriber(c)).run()
        val sub = c.expectSubscription()

        li.foreach(e ⇒ {
          sub.request(1)
          c.expectNoMsg(1000.millis)
          e should be(c.expectNext())
        })

        c.expectComplete()

      }

    }
```

After running it for couple of hours the result is following:
```
...
Diff was: 1003330867 elem null
Diff was: 1006857829 elem null
Diff was: 1003038750 elem null
Diff was: 1009631928 elem OnNext(1)
--- Stream actors debug dump ---
Stream actors alive: List(Actor[akka://TickSourceSpec/user/StreamSupervisor-0/flow-1859-0-unnamed#-401457290])
activeShells (actor: Actor[akka://TickSourceSpec/user/StreamSupervisor-0/flow-1859-0-unnamed#-401457290]):
  GraphInterpreterShell(
    logics: [
      akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1@7779ca8e attrs: [InputBuffer(4,16), SupervisionStrategy(<function1>)],
      ActorOutputBoundary(port=TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1.out(913065088), demand=0, finished=false) attrs: [],
      StatefulMapConcat attrs: [Name(statefulMapConcat), Name(iterableSource), InputBuffer(4,16), SupervisionStrategy(<function1>)],
      SingleSource attrs: [Name(singleSource), Name(iterableSource), InputBuffer(4,16), SupervisionStrategy(<function1>)]
    ],
    connections: [
      Connection(0, 1, Empty, akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1$$anon$1@1a42a8fb, akka.stream.impl.fusing.StatefulMapConcat$$anon$28@74dca55c),
      Connection(1, 49, Empty, akka.stream.impl.fusing.StatefulMapConcat$$anon$28@74dca55c, akka.stream.impl.fusing.GraphStages$SingleSource$$anon$7@369ebe29),
      Connection(2, 1, Empty, ActorOutputBoundary(port=TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1.out(913065088), demand=0, finished=false), akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1$$anon$1@1a42a8fb)
    ]
  )

dot format graph for deadlock analysis:
================================================================
digraph waits {
  N0 [label="akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1@7779ca8e"];
  N1 [label="ActorOutputBoundary(port=TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$Delay$1.out(913065088), demand=0, finished=false)"];
  N2 [label="StatefulMapConcat"];
  N3 [label="SingleSource"];
  N0 -> N2 [label=shouldPull, color=blue];
  N2 -> N3 
  N1 -> N0 [label=shouldPull, color=blue];
}
================================================================
// (4, 7, 7)() (running=3, shutdown=2,1,1,0)
newShells:


assertion failed: received unexpected message OnNext(1)
java.lang.AssertionError: assertion failed: received unexpected message OnNext(1)
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:633)
	at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:626)
	at akka.testkit.TestKit.expectNoMsg(TestKit.scala:831)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMsg(StreamTestKit.scala:549)
	at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$3.apply(TickSourceSpec.scala:78)
	at akka.stream.scaladsl.TickSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$3.apply(TickSourceSpec.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
```

We can see that it failed after 1000 milliseconds passed `Diff was: 1009631928 elem OnNext(1)`.
I think it is due to some acceptable inaccuracy in timing of `LinkedBlockingDeque.pollFirst()`.

I suggest measure the diff and let the test pass if diff is higher than is specified.
```scala
private def expectNoMsg_internal(max: FiniteDuration) {
    val start = System.nanoTime()
    val o = receiveOne(max)
    val diff = System.nanoTime() - start
    if(diff <= max.toNanos) {
      assert(o eq null, s"received unexpected message $o")
    }
    lastWasNoMsg = true
  }
```

What do you think guys?

**Comment by manonthegithub** [comment]
I can create PR if you don't mind

**Comment by johanandren** [comment]
Thanks for the thorough investigation! 

I think we should rather not use `receiveOne` but make a custom implementation for `expectNoMsg_internal` since `receiveOne` is for a different use case (receive message within rather than should not have received message before).

**Comment by manonthegithub** [comment]
> I think we should rather not use receiveOne
Yes, I think it's much better, than I previously suggested, because receiveOne removes message from queue, which can lead to missing message for following code in test.

**Comment by raboof** [comment]
I agree it'd be much nicer if `expectNoMsg` didn't use `receiveOne` internally - additionally it'd be nice to be able to configure the default timeouts separately. Also related to #20255.

**Comment by manonthegithub** [comment]
I am thinking about simple solution for internal implementationwith using Thread.sleep with interval parameter to have better responsiveness.

something like `watchForMessage(max: FiniteDuration, checkInterval: FiniteDutration = 100 millis )`

If you think it is ok, I can try to implement this, if more scalable multithreaded solution is not needed.

**Comment by johanandren** [comment]
I don't think we need to be able to tweak a polling interval in the API even if the solution is peek+sleep. Make sure to read the ticket Arnout mentioned also before taking a stab at it.
