### ISSUE TITLE
Failed: DurableDataSpec: expected UpdateSuccess(durable-A,None), found UpdateTimeout(durable-A,None)

### ISSUE THREAD

**Issue by raboof** [akka/akka#23284]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/762/consoleFull

```
[JVM-2] - work in multi node cluster *** FAILED *** (5 seconds, 700 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: expected UpdateSuccess(durable-A,None), found UpdateTimeout(durable-A,None)
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:387)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:363)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:831)
[JVM-2]   at akka.cluster.ddata.DurableDataSpec$$anonfun$2.apply$mcV$sp(DurableDataSpec.scala:167)
```

**Comment by patriknw** [comment]
ah, I increased the test timeouts, but not the `Update` timeout
