### ISSUE TITLE
Ending up with too many vector clocks

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23318]
Some pruning not happening as it should perhaps? Appeared in the nightlies over the weekend, after merging all the things friday.

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13932/consoleFull

```
[JVM-1] java.lang.IllegalStateException: Too many vector clock entries in gossip state Gossip(members = [Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:53681, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a2.moxie:60170, dataCenter = dc2, status = Up), Member(address = akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828, dataCenter = dc1, status = Up)], overview = GossipOverview(reachability = [], seen = [UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a4.moxie:60828,545928382)]), version = VectorClock(4ff491baf31afdcfffb3caa205a8ecf3 -> 1, 602c2526b740ec11feae8fa507e6f350 -> 8, 869516b02d35eb7c34d222fdcc98de38 -> 5, d633377ef2e0f995779c730c5f27bbae -> 3), tombstones = Map(UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:34905,1926157669) -> 1499450297287, UniqueAddress(akka.trttl.gremlin.tcp://MultiDcSpec@a5.moxie:43278,-1097777188) -> 1499450301143))
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.assertLatestGossip(ClusterDaemon.scala:1242)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.updateLatestGossip(ClusterDaemon.scala:1237)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActionsOnConvergence(ClusterDaemon.scala:1103)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.leaderActions(ClusterDaemon.scala:968)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon$$anonfun$initialized$1.applyOrElse(ClusterDaemon.scala:459)
[JVM-1] 	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
[JVM-1] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
[JVM-1] 	at akka.cluster.ClusterCoreDaemon.aroundReceive(ClusterDaemon.scala:288)
[JVM-1] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[JVM-1] 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
[JVM-1] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[JVM-1] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[JVM-1] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[JVM-1] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13942/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13943/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13949/consoleFull

**Comment by johanandren** [comment]
Dang: https://jenkins.akka.io:8498/job/akka-multi-node-repeat/13992/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14003/consoleFull
