### ISSUE TITLE
FAILED: Ticket1978SHA1PRNGSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23337]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/262/consoleFull

```
[info] akka.remote.Ticket1978SHA1PRNGSpec *** ABORTED *** (0 milliseconds)
[info]   org.jboss.netty.channel.ChannelException was thrown inside "-" must, construction cannot continue: "Failed to bind to: localhost/127.0.0.1:59118" (Ticket1978CommunicationSpec.scala:114)
[info]   org.scalatest.exceptions.NotAllowedException:
[info]   at org.scalatest.WordSpecLike.org$scalatest$WordSpecLike$$registerBranch(WordSpecLike.scala:197)
[info]   at org.scalatest.WordSpecLike$$anon$2.apply(WordSpecLike.scala:996)
[info]   at org.scalatest.words.MustVerb$StringMustWrapperForVerb.must(MustVerb.scala:191)
[info]   at org.scalatest.words.MustVerb$StringMustWrapperForVerb.must$(MustVerb.scala:190)
[info]   at org.scalatest.words.MustVerb$$anon$1.must(MustVerb.scala:229)
[info]   at akka.remote.Ticket1978CommunicationSpec.<init>(Ticket1978CommunicationSpec.scala:114)
[info]   at akka.remote.Ticket1978SHA1PRNGSpec.<init>(Ticket1978CommunicationSpec.scala:86)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   Cause: org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:59118
[info]   at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
[info]   at akka.remote.transport.netty.NettyTransport.$anonfun$listen$1(NettyTransport.scala:417)
[info]   at akka.remote.transport.netty.NettyTransport$$Lambda$11515/492087895.apply(Unknown Source)
[info]   at scala.util.Success.$anonfun$map$1(Try.scala:251)
[info]   at scala.util.Success.map(Try.scala:209)
[info]   at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
[info]   at scala.concurrent.Future$$Lambda$4189/460343332.apply(Unknown Source)
[info]   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[info]   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[info]   at scala.concurrent.impl.Promise$$Lambda$3782/583357458.apply(Unknown Source)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$11435/752384277.apply$mcV$sp(Unknown Source)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
[info]   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info]   Cause: java.net.BindException: Address already in use
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:437)
[info]   at sun.nio.ch.Net.bind(Net.java:429)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info]   at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
[info]   at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
[info]   at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
[info]   at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
[info]   at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by raboof** [comment]
happened again in https://jenkins.akka.io:8498/job/akka-nightly-2.13/161/testReport/junit/akka.remote/Ticket1978SHA1PRNGSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/
