### ISSUE TITLE
FAILED: GraphMergePrioritizedSpec.merge prioritized must stream data with priority

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23336]
https://jenkins.akka.io:8498/job/akka-nightly/4575/testReport/junit/akka.stream.scaladsl/GraphMergePrioritizedSpec/merge_prioritized_must_stream_data_with_priority/

```
Error Message

5 did not equal 6

Stacktrace

      org.scalatest.exceptions.TestFailedException: 5 did not equal 6
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6742)
      at akka.stream.scaladsl.GraphMergePrioritizedSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GraphMergePrioritizedSpec.scala:72)
      at akka.stream.scaladsl.GraphMergePrioritizedSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GraphMergePrioritizedSpec.scala:47)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
      at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
      at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:392)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
      at scala.collection.immutable.List.foreach(List.scala:392)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
      at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
      at org.scalatest.Suite$class.run(Suite.scala:1147)
      at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
      at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
      at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
      at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
      at sbt.TestRunner.runTest$1(TestFramework.scala:76)
      at sbt.TestRunner.run(TestFramework.scala:85)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
      at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
      at sbt.TestFunction.apply(TestFramework.scala:207)
      at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
      at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
      at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
      at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
      at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
      at sbt.std.Transform$$anon$4.work(System.scala:63)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
      at sbt.Execute.work(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
```

**Comment by johanandren** [comment]
Can't find anything wrong with the stage, but, MergePrioritized only prioritizes when downstream is slower, so I think the test is wrong in assuming that throttling will always be applied when it in fact depends on the fairness of the graph interpreter.
