### ISSUE TITLE
Failed: NodeChurn

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23369]
On the multi-dc repeat job:

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14105/consoleFull

```
[JVM-3] - must join and remove transient nodes without growing gossip payload (on node 'third', class akka.cluster.NodeChurnMultiJvmNode3) *** FAILED *** (41 seconds, 179 milliseconds)
[JVM-3]   java.lang.AssertionError: assertion failed: received unexpected message New maximum payload size for [akka.cluster.GossipEnvelope] is [1321] bytes
[JVM-3]   at scala.Predef$.assert(Predef.scala:170)
[JVM-3]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:633)
[JVM-3]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:629)
[JVM-3]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:831)
[JVM-3]   at akka.cluster.NodeChurnSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$mcV$sp$6.apply$mcVI$sp(NodeChurnSpec.scala:144)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14111/console

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14201/console

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14317/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14459/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14587/console

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14640/consoleFull

**Comment by patriknw** [comment]
The reason is that we introduced tombstones instead of removing immediately.
