### ISSUE TITLE
Failed: MultiDcHeartbeatTakingOverSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23371]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14117/consoleFull

```
[JVM-5] - must be healthy (on node 'fifth', class akka.cluster.MultiDcHeartbeatTakingOverSpecMultiJvmNode5) *** FAILED *** (13 milliseconds)
[JVM-5]   java.lang.AssertionError: assertion failed: expected class akka.cluster.CrossDcHeartbeatSender$MonitoringActive, found class akka.cluster.CrossDcHeartbeatSender$MonitoringDormant (MonitoringDormant())
[JVM-5]   at scala.Predef$.assert(Predef.scala:170)
[JVM-5]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:490)
[JVM-5]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:471)
[JVM-5]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:831)
[JVM-5]   at akka.cluster.MultiDcHeartbeatTakingOverSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp(MultiDcHeartbeatTakingOverSpec.scala:120)
```

**Comment by johanandren** [comment]
Happened again :( So probably not what I thought it was then.

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14236/consoleFull
