### ISSUE TITLE
Failed: UnfoldResourceAsyncSourceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23382]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/270/testReport/junit/akka.stream.scaladsl/UnfoldResourceAsyncSourceSpec/Unfold_Resource_Async_Source_must_close_resource_when_stream_is_abruptly_terminated/

```
 java.util.concurrent.TimeoutException: Timeout of 3 seconds with time factor of 1.0
      at akka.testkit.TestLatch.ready(TestLatch.scala:42)
      at akka.testkit.TestLatch.ready(TestLatch.scala:26)
      at scala.concurrent.Await$.$anonfun$ready$1(package.scala:169)
      at scala.concurrent.Await$$$Lambda$3978/861515813.apply(Unknown Source)
      at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
      at scala.concurrent.Await$.ready(package.scala:123)
      at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec.$anonfun$new$34(UnfoldResourceAsyncSourceSpec.scala:268)
      at akka.stream.scaladsl.UnfoldResourceAsyncSourceSpec$$Lambda$16874/1295434925.apply(Unknown Source)
```

**Comment by 2m** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5120/consoleFull
