### ISSUE TITLE
FAILED: LruBoundedCacheSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23386]
akka.remote.artery.LruBoundedCacheSpec.LruBoundedCache must maintain a good average probe distance

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/9806/testReport/junit/akka.remote.artery/LruBoundedCacheSpec/LruBoundedCache_must_maintain_a_good_average_probe_distance/

```
Error Message

2.5475409836065572 was not less than 2.5
Stacktrace

      org.scalatest.exceptions.TestFailedException: 2.5475409836065572 was not less than 2.5
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
      at akka.remote.artery.LruBoundedCacheSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$10.apply(LruBoundedCacheSpec.scala:216)
      at akka.remote.artery.LruBoundedCacheSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anonfun$apply$mcV$sp$10.apply(LruBoundedCacheSpec.scala:203)
      at scala.collection.immutable.Range.foreach(Range.scala:160)
      at akka.remote.artery.LruBoundedCacheSpec$$anonfun$1$$anonfun$apply$mcV$sp$8.apply$mcV$sp(LruBoundedCacheSpec.scala:203)
      at akka.remote.artery.LruBoundedCacheSpec$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(LruBoundedCacheSpec.scala:203)
      at akka.remote.artery.LruBoundedCacheSpec$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(LruBoundedCacheSpec.scala:203)
      at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
      at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
```

**Comment by ktoso** [comment]
The picked number is a bit arbitrary, and the problem has not happened again since 3 months or so... Closing
