### ISSUE TITLE
Failed: RemoteDeploymentDocSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23391]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/779/testReport/junit/docs.remoting/RemoteDeploymentDocSpec/demonstrate_programmatic_deployment/

4 second GC pause what likely the reason. But why was there a 4 second GC pause?

```
 java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
      at scala.Predef$.assert(Predef.scala:170)
      at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:489)
      at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:462)
      at akka.testkit.TestKit.expectMsgType(TestKit.scala:831)
      at docs.remoting.RemoteDeploymentDocSpec$$anonfun$2.apply(RemoteDeploymentDocSpec.scala:42)
      at docs.remoting.RemoteDeploymentDocSpec$$anonfun$2.apply(RemoteDeploymentDocSpec.scala:35)
```

**Comment by patriknw** [comment]
We already have an issue for the GC: #22979
