### ISSUE TITLE
JDK9: Failed TcpTest, touches "sun.nio.ch"

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23400]
Obtained by running https://github.com/ktoso/akka/tree/wip-jdk9 on JDK9 (Java(TM) SE Runtime Environment (build 9-ea+174))

```
[info] TcpTest:
[info] - mustReportServerBindFailure *** FAILED ***
[info]   java.lang.reflect.InaccessibleObjectException: Unable to make public void sun.nio.ch.ServerSocketAdaptor.bind(java.net.SocketAddress) throws java.io.IOException accessible: module java.base does not "exports sun.nio.ch" to unnamed module @6782c3ca
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
[info]   at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
[info]   at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
[info]   at scala.reflect.package$.ensureAccessible(package.scala:53)
[info]   at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:140)
[info]   at akka.testkit.SocketUtil$.reflMethod$Method1(SocketUtil.scala:37)
[info]   at akka.testkit.SocketUtil$.$anonfun$temporaryServerAddresses$1(SocketUtil.scala:37)
[info]   at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:90)
[info]   at akka.testkit.SocketUtil$.temporaryServerAddresses(SocketUtil.scala:32)
[info]   at akka.testkit.SocketUtil$.temporaryServerAddress(SocketUtil.scala:29)
[info]   at akka.testkit.SocketUtil.temporaryServerAddress(SocketUtil.scala)
[info]   at akka.stream.javadsl.TcpTest.mustReportServerBindFailure(TcpTest.java:86)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
```

**Comment by ktoso** [comment]
Another similar one in TcpSpec, also touching sun.net:

```
Caused by: java.lang.IllegalAccessError: class akka.io.InetAddressDnsResolver (in unnamed module @0x7d7a4b5a) cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @0x7d7a4b5a

```

**Comment by ktoso** [comment]
Use this sbt to be able to run JDK9: https://github.com/sbt/sbt-launcher-package/pull/143

**Comment by chbatey** [comment]
Confirmed that TcpTest is fixed by https://github.com/akka/akka/pull/23721

**Comment by chbatey** [comment]
TcpSpec is covered in https://github.com/akka/akka/issues/23108 I believe
