### ISSUE TITLE
JDK9: Mockito breaks in akka.pattern.CircuitBreakerSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#23402]
Easiest to rewrite test to not need mockito I propose 

```
[info]   Cause: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5459139a
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
[info]   at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
[info]   at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
[info]   at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:57)
[info]   at java.base/java.security.AccessController.doPrivileged(Native Method)
[info]   at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:47)
[info]   at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
[info]   at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[info]   at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
[info]   at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
[info]   at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
[info]   at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
[info]   at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
[info]   at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
[info]   at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:95)
[info]   at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
[info]   at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
[info]   at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
[info]   at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
[info]   at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
[info]   at org.mockito.Mockito.mock(Mockito.java:1285)
[info]   at org.mockito.Mockito.mock(Mockito.java:1163)
[info]   at org.scalatest.mockito.MockitoSugar.mock(MockitoSugar.scala:73)
[info]   at org.scalatest.mockito.MockitoSugar.mock$(MockitoSugar.scala:72)
[info]   at akka.pattern.CircuitBreakerSpec$Breaker.mock(CircuitBreakerSpec.scala:22)
[info]   at akka.pattern.CircuitBreakerSpec$Breaker.<init>(CircuitBreakerSpec.scala:31)
[info]   at akka.pattern.CircuitBreakerSpec$.longResetTimeoutCb(CircuitBreakerSpec.scala:68)
[info]   at akka.pattern.CircuitBreakerSpec.$anonfun$new$9(CircuitBreakerSpec.scala:99)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
```

**Comment by xuwei-k** [comment]
https://github.com/akka/akka/blob/1b0c27dc756f5aa7da5fbd30f98df3da6c4587ea/project/Dependencies.scala#L89

`"mockito-all" % "1.10.19"` does not support Java9 but latest version of mockito support Java9

related(?) https://github.com/scalatest/scalatest/issues/1114

I was updated mockito dependency in some scala projects.
- https://github.com/gitbucket/gitbucket/pull/1492
- https://github.com/scalikejdbc/scalikejdbc/pull/650

**Comment by ktoso** [comment]
Thanks for the info! We can give that a try as well then :)
