### ISSUE TITLE
Invalid stack trace because reused exception code is defined as val

### ISSUE THREAD

**Issue by francisdb** [akka/akka#23416]
Both `OutputStreamSourceStage` (and `InputStreamSinkStage`) build an IOException and store it as val. This causes the stack trace to be populated at val instantiation time instead of the place where it is thrown. This in turn yields strange stack traces originating at the wrong location.

My guess is that this is not on purpose and should have been defined as a `def` instead of a `val`
(you might want to search the code for more of these)

https://github.com/akka/akka/blob/87b28d0dc53d236168b00dab0f443886f0f11853/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L164

```scala
 val publisherClosedException = new IOException("Reactive stream is terminated, no writes are possible")

  @scala.throws(classOf[IOException])
  private[this] def send(sendAction: () ⇒ Unit): Unit = {
    if (isActive) {
      if (isPublisherAlive) sendAction()
      else throw publisherClosedException
    } else throw new IOException("OutputStream is closed")
  }
```

the same is done here: https://github.com/akka/akka/blob/87b28d0dc53d236168b00dab0f443886f0f11853/akka-stream/src/main/scala/akka/stream/impl/io/InputStreamSinkStage.scala#L117

**Comment by jrudolph** [comment]
The stack trace will always look the same so I guess it was intentional. We could add `NoStackTrace` instead to remove the stack trace completely, though we should also improve the error message to be more descriptive of what has happened.

**Comment by francisdb** [comment]
I'm having this being thrown and am trying to debug what is going on, since the cause might be in the implementation of the reading/writing done by a different lib the stack trace would be more than welcome. Currently the trace points to the location where .run() is called which is very confusing.

```
java.io.IOException: Reactive stream is terminated, no writes are possible
	at akka.stream.impl.io.OutputStreamAdapter.<init>(OutputStreamSourceStage.scala:164)
	at akka.stream.impl.io.OutputStreamSourceStage.createLogicAndMaterializedValue(OutputStreamSourceStage.scala:151)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:627)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:439)
	at my.project.ImportExport$.readZip(ImportExport.scala:66)
...
```

where the line in my code is this

```scala
val is = source.toMat(StreamConverters.asInputStream(5.seconds))(Keep.right).run()
// the reading of the InputStream is handled further down in the code using a Future
```

The error is probably caused by the library I am using that writes to the stream and closes/flushes multiple times.

Also this is the only place in Akka streams where I see this pattern of pre-creating the exception. Sure this is not an accidental mistake?

**Comment by francisdb** [comment]
@jrudolph There are 3 places where this is thrown so the stack trace would not be the same after the fix. As I see it, it would point to the code writing to the stream which is exactly how this would need to be debugged.

**Comment by jrudolph** [comment]
> There are 3 places where this is thrown so the stack trace would not be the same after the fix.

I see, that might be a good reason to keep the stack trace. Another possibility would be to create three different exceptions. Note, though, that in no case, the stack trace would point to user code. It now points to `materialize`, with `def` it will later only contain infrastructure code, starting from the thread pool, through streams infrastructure to the GraphStage.

**Comment by francisdb** [comment]
@jrudolph let me prove the usefulness of the real trace

created an example main class __akka.stream.Main__
```scala
package akka.stream

import akka.actor.ActorSystem
import akka.stream.javadsl.StreamConverters
import akka.stream.scaladsl.{ Keep, Source }
import akka.util.ByteString

import scala.concurrent.Future
import scala.concurrent.duration._
import scala.util._
import scala.concurrent.ExecutionContext.Implicits.global

object Main extends App {

  implicit val system = ActorSystem()
  implicit val mat = ActorMaterializer()

  val source = Source.repeat(ByteString("foobar"))

  val is = source.toMat(StreamConverters.asInputStream(5.seconds))(Keep.right).run()

  Future {
    is.close()
    is.read() // bug outside of akka streams
  }.onComplete {
    case Success(_) ⇒
      println("ok")
      mat.shutdown()
      system.terminate()
    case Failure(e) ⇒
      e.printStackTrace()
      mat.shutdown()
      system.terminate()
  }

}
```

running this before my patch:
```
java.io.IOException: Reactive stream is terminated, no reads are possible
	at akka.stream.impl.io.InputStreamAdapter.<init>(InputStreamSinkStage.scala:117)
	at akka.stream.impl.io.InputStreamSinkStage.createLogicAndMaterializedValue(InputStreamSinkStage.scala:100)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:627)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:458)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496)
	at akka.stream.Main$.delayedEndpoint$akka$stream$Main$1(Main.scala:20)
	at akka.stream.Main$delayedInit$body.apply(Main.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at akka.stream.Main$.main(Main.scala:13) <-- ???
	at akka.stream.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```

and with my patch applied

```
java.io.IOException: Reactive stream is terminated, no reads are possible
	at akka.stream.impl.io.InputStreamAdapter.subscriberClosedException(InputStreamSinkStage.scala:117)
	at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:125)
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:144)
	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:130)
	at akka.stream.Main$$anonfun$1.apply$mcI$sp(Main.scala:24) <-- \o/
	at akka.stream.Main$$anonfun$1.apply(Main.scala:22)
	at akka.stream.Main$$anonfun$1.apply(Main.scala:22)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

you can clearly see the second trace pointing to line `24` which is the invalid `is.read()` causing the exception where before the trace pointed to line `13` which calls the `.run()`

**Comment by francisdb** [comment]
Thanks!
