### ISSUE TITLE
Failed: ClusterSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23449]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/14323/

```
[info] - must leave via CoordinatedShutdown.run *** FAILED *** (1 second, 73 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$MemberExited, found class akka.cluster.ClusterEvent$MemberRemoved (MemberRemoved(Member(address = akka.tcp://ClusterSpec2@127.0.1.1:39938, status = Removed),Leaving))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:490)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:462)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:831)
[info]   at akka.cluster.ClusterSpec$$anonfun$1$$anonfun$apply$mcV$sp$15.apply(ClusterSpec.scala:163)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by patriknw** [comment]
This shouldn't be related to multi-dc changes. The `MemberExited` event is not published, and we can see deadLetters for `PublishChanges`:

```
[INFO] [07/27/2017 14:50:29.763] [ClusterSpec2-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://ClusterSpec2)] Cluster Node [akka.tcp://ClusterSpec2@127.0.1.1:39938] - Successfully shut down
[INFO] [07/27/2017 14:50:29.769] [ClusterSpec2-akka.actor.default-dispatcher-25] [akka://ClusterSpec2/system/cluster/core/publisher] Message [akka.cluster.InternalClusterAction$PublishChanges] from Actor[akka://ClusterSpec2/system/cluster/core/daemon#-2010170107] to Actor[akka://ClusterSpec2/system/cluster/core/publisher#696729932] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [07/27/2017 14:50:29.769] [ClusterSpec2-akka.actor.default-dispatcher-25] [akka://ClusterSpec2/system/cluster/core/publisher] Message [akka.cluster.InternalClusterAction$PublishChanges] from Actor[akka://ClusterSpec2/system/cluster/core/daemon#-2010170107] to Actor[akka://ClusterSpec2/system/cluster/core/publisher#696729932] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

The reason is a race between receiving that `PublishChanges` in `ClusterDomainEventPublisher` and stopping it. Note that the final `MemberRemoved` is published via `postStop` in `ClusterDomainEventPublisher`.

Let's see if it is recurring.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10684

Not sure if this one is the same reason as before. Might also be related to coordinated shutdown (settings)?
```
[info] - must leave via CoordinatedShutdown.run *** FAILED *** (1 second, 91 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$MemberExited, found class akka.cluster.ClusterEvent$MemberRemoved (MemberRemoved(Member(address = akka.tcp://ClusterSpec2@127.0.1.1:33040, status = Removed),Leaving))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:481)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
[info]   at akka.cluster.ClusterSpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(ClusterSpec.scala:163)
```

**Comment by ktoso** [comment]
Again here:
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10886/consoleFull

```
[INFO] [12/05/2017 05:30:48.218] [ClusterSpec2-akka.actor.default-dispatcher-20] [akka.remote.Remoting] Remoting shut down
[INFO] [12/05/2017 05:30:48.218] [ClusterSpec2-akka.remote.default-remote-dispatcher-8] [akka.tcp://ClusterSpec2@127.0.1.1:51879/system/remoting-terminator] Remoting shut down.
[info] - must leave via CoordinatedShutdown.run *** FAILED *** (1 second, 84 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$MemberExited, found class akka.cluster.ClusterEvent$MemberRemoved (MemberRemoved(Member(address = akka.tcp://ClusterSpec2@127.0.1.1:51879, status = Removed),Leaving))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[info]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:481)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
[info]   at akka.cluster.ClusterSpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(ClusterSpec.scala:163)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
```
