### ISSUE TITLE
NPE when typo in application.conf

### ISSUE THREAD

**Issue by fmalothomas** [akka/akka#23442]
Hi, I am new to submitting issues and english is not my native language therefore I apologize in advance for it may be bad.

I am using `play framework 2.6.0`, `scala 2.12.2`, `akka-stream_2.12-2.5.3`, `play-akka-http-server_2.12-2.6.0`.
I got a NPE with a double dot instead of simple dot in my `application.conf` file:
For example:  
`play..modules.enabled += "module.Module"` is throwing the NPE
`play.modules.enabled += "module.Module"` works fine.

Here is the stack trace:
```[ERROR] [07/26/2017 16:48:38.438] [play-dev-mode-akka.actor.default-dispatcher-16] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
java.lang.NullPointerException
        at com.typesafe.config.ConfigException.<init>(ConfigException.java:23)
        at com.typesafe.config.ConfigException$BadPath.<init>(ConfigException.java:198)
        at com.typesafe.config.ConfigException$BadPath.<init>(ConfigException.java:204)
        at com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:170)
        at com.typesafe.config.impl.PathParser.parsePathNodeExpression(PathParser.java:85)
        at com.typesafe.config.impl.PathParser.parsePathNodeExpression(PathParser.java:79)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseKey(ConfigDocumentParser.java:282)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:448)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646)
        at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:307)
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:747)
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
        at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
        at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
        at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:978)
        at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
        at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
        at play.api.Configuration$.$anonfun$load$5(Configuration.scala:73)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.Configuration$.load(Configuration.scala:69)
        at play.api.Configuration$.load(Configuration.scala:109)
        at play.api.Configuration$.load(Configuration.scala:115)
        at play.api.http.DefaultHttpErrorHandler$.setEditor$lzycompute(HttpErrorHandler.scala:277)
        at play.api.http.DefaultHttpErrorHandler$.setEditor(HttpErrorHandler.scala:276)
        at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:285)
        at play.core.server.Server.logExceptionAndGetResult$1(Server.scala:53)
        at play.core.server.Server.getHandlerFor(Server.scala:83)
        at play.core.server.Server.getHandlerFor$(Server.scala:49)
        at play.core.server.AkkaHttpServer.getHandlerFor(AkkaHttpServer.scala:42)
        at play.core.server.AkkaHttpServer.getHandler(AkkaHttpServer.scala:193)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:173)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:95)
        at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
        at akka.actor.Actor.aroundReceive(Actor.scala:513)
        at akka.actor.Actor.aroundReceive$(Actor.scala:511)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by johanandren** [comment]
Hi @fmalothomas, thanks for reporting, this is an issue in the "Typesafe Config Library" and not in Akka itself, you can find the repository of that library here: https://github.com/typesafehub/config/issues

I think this may be what already is reported in issue typesafehub/config#367 so please look at that and comment over there or open a new ticket if you disagree.

I'll close this ticket now, since it is not strictly a problem with the Akka project.
