### ISSUE TITLE
Uninitialized field for Scala 2.12.3

### ISSUE THREAD

**Issue by TimothyKlim** [akka/akka#23453]
I've just upgraded my app to new scala and I got this when log some data:
```
scala.UninitializedFieldError: Uninitialized field: com/xxx/ProtoGraphStage.scala: 67
	at com.xxx.ProtoGraphStage$$anon$1.akka$stream$stage$StageLogging$$_log(ProtoGraphStage.scala:67) ~[classes/:?]
	at akka.stream.stage.StageLogging.log(StageLogging.scala:29) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.stream.stage.StageLogging.log$(StageLogging.scala:27) ~[akka-stream_2.12-2.5.3.jar:?]
	at com.xxx.ProtoGraphStage$$anon$1.log(ProtoGraphStage.scala:67) ~[classes/:?]
	at com.xxx.ProtoGraphStage$$anon$1.preStart(ProtoGraphStage.scala:92) ~[classes/:?]
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:290) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.actor.Actor.aroundPreStart(Actor.scala:521) ~[akka-actor_2.12-2.5.3.jar:?]
	at akka.actor.Actor.aroundPreStart$(Actor.scala:521) ~[akka-actor_2.12-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.3.jar:?]
	at akka.actor.ActorCell.create(ActorCell.scala:591) ~[akka-actor_2.12-2.5.3.jar:?]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462) [akka-actor_2.12-2.5.3.jar:?]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.3.jar:?]
```

**Comment by ktoso** [comment]
What is `scala.UninitializedFieldError: Uninitialized field: com/xxx/ProtoGraphStage.scala: 67`?

**Comment by TimothyKlim** [comment]
`log.info("test")`

**Comment by ktoso** [comment]
And what's log, where is it coming from? Please more context so we actually can have a chance of figuring out where the issue may lie :-)

**Comment by ktoso** [comment]
In other words, would you be able to provide a minimised reproducer?

**Comment by TimothyKlim** [comment]
Hah, it's [scalac issue](https://github.com/scala/bug/issues/10437) (`scalacOptions += "-Xcheckinit"`), sorry for disturb you 😉

**Comment by ktoso** [comment]
Thanks for finding the issue on scalac :)
