### ISSUE TITLE
Error in Docker container: Default journal plugin is not configured

### ISSUE THREAD

**Issue by jansoren** [akka/akka#23465]
Hi,

I am working on getting my akka-persistence app to run in Docker. When I run the application from Intellij it works as intended, but when i deploy the same files(jar & config) to Docker and try to run it from the container i get this error: 
```
[ERROR] [08/02/2017 11:04:10.226] [actor-system-akka.actor.default-dispatcher-2] [akka://actor-system/user/PersistenceActor] requirement failed: default journal plugin is not configured, see 'reference.conf'
akka.actor.ActorInitializationException: akka://actor-system/user/PersistenceActor: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
        at akka.actor.ActorCell.create(ActorCell.scala:608)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at akka.util.Reflect$.instantiate(Reflect.scala:65)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:563)
        at akka.actor.ActorCell.create(ActorCell.scala:589)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: requirement failed: default journal plugin is not configured, see 'reference.conf'
        at scala.Predef$.require(Predef.scala:224)
        at akka.persistence.Persistence.defaultJournalPluginId$lzycompute(Persistence.scala:163)
        at akka.persistence.Persistence.defaultJournalPluginId(Persistence.scala:161)
        at akka.persistence.Persistence.journalConfigFor(Persistence.scala:239)
        at akka.persistence.Eventsourced$class.$init$(Eventsourced.scala:61)
        at akka.persistence.AbstractPersistentActor.<init>(PersistentActor.scala:409)
        at no.jansoren.akka.persistence.eventsourcing.EventSourcedPersistenceActor.<init>(EventSourcedPersistenceActor.java:14)
        at no.jansoren.eventsourcing.PersistenceActor.<init>(PersistenceActor.java:21)
        ... 18 more
```

My `reference.conf` file looks like this:

```
akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "DEBUG"
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"

  persistence {
    journal {
      plugin = "akka.persistence.journal.leveldb"
      leveldb.dir = "target/journal"
    }
    snapshot-store {
      plugin = "akka.persistence.snapshot-store.local"
      local.dir = "target/snapshots"
    }
  }
  actor {
    warn-about-java-serializer-usage = false
  }
}
```

Any suggestions on how to attack this issue?

**Comment by johanandren** [comment]
Hi @jansoren, please use the issue tracker only for bug reports and enhancements. For usage question like this instead use the mailing list: https://groups.google.com/forum/#!forum/akka-user or the gitter chat channel: https://gitter.im/akka/akka, thanks!

**Comment by jansoren** [comment]
I hope you could reconsider using github as a place for questions aswell, since the markup is much nicer, feedback-loop is faster and its a good way to keep track on old issues/questions aswell. All in one place 🙂
