### ISSUE TITLE
Failed: akka.typed.ActorContextSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23482]
https://jenkins.akka.io:8498/job/akka-nightly/4626/testReport/junit/akka.typed/ActorContextSpec/An_ActorContext_with_deferred_Behavior__native__11_must_watch_a_child_actor_after_its_termination/

```
akka.typed.StepWise$$anon$2: timeout of 3 seconds expired while waiting for a message
      at akka.typed.ActorContextSpec$Tests$$anonfun$11$u0020must$u0020watch$u0020a$u0020child$u0020actor$u0020after$u0020its$u0020termination$1.apply(ActorContextSpec.scala:505)
      at akka.typed.ActorContextSpec$Tests$$anonfun$11$u0020must$u0020watch$u0020a$u0020child$u0020actor$u0020after$u0020its$u0020termination$1.apply(ActorContextSpec.scala:494)
      at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:298)
      at akka.typed.ActorContextSpec$Tests$$anonfun$setup$1.apply(ActorContextSpec.scala:293)
```

**Comment by chbatey** [comment]
Closing as it was for the native system #24176
