### ISSUE TITLE
Failed: LeveldbEndToEndEventAdapterSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23483]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5129/testReport/junit/akka.persistence/LeveldbEndToEndEventAdapterSpec/EventAdapters_in_end_to_end_scenarios_must_use_the_same_adapter_when_reading_as_was_used_when_writing_to_the_journal/

```
akka.actor.InvalidActorNameException: actor name [p1] is not unique!
      at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
      at akka.actor.dungeon.Children$class.reserveChild(Children.scala:134)
      at akka.actor.ActorCell.reserveChild(ActorCell.scala:370)
      at akka.actor.dungeon.Children$class.makeChild(Children.scala:272)
      at akka.actor.dungeon.Children$class.attachChild(Children.scala:48)
      at akka.actor.ActorCell.attachChild(ActorCell.scala:370)
      at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:717)
      at akka.persistence.EndToEndEventAdapterSpec.persister(EndToEndEventAdapterSpec.scala:154)
      at akka.persistence.EndToEndEventAdapterSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(EndToEndEventAdapterSpec.scala:180)
      at akka.persistence.EndToEndEventAdapterSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(EndToEndEventAdapterSpec.scala:164)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2245/

**Comment by patriknw** [comment]
This has been fixed and merged
