### ISSUE TITLE
Failed: akka.stream.scaladsl.RestartSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23484]
https://jenkins.akka.io:8498/job/akka-nightly/4657/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_restart_on_cancellation/

```
java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:290)
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:281)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(RestartSpec.scala:362)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$14.apply(RestartSpec.scala:351)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4660/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_restart_on_completion/

```
 java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:290)
      at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:281)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$15.apply(RestartSpec.scala:386)
      at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$15.apply(RestartSpec.scala:373)
```

**Comment by johanandren** [comment]
@jroper any chance you could take a look at these failures? Can't see that it would be any GC around the failures triggering a timeout, so maybe there is something to these failures.

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/4670/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_restart_on_completion/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/295/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_restart_on_completion/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/296/consoleFull

**Comment by patriknw** [comment]
@raboof don't forget to set milestone when closing tickets, thanks

**Comment by chbatey** [comment]
Looks to happen again: https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5388/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_backoff_before_restart/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2364/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_backoff_before_restart/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2394/consoleFull

**Comment by 2m** [comment]
It would be better to leave the ticket that is assigned to the already released milestone closed and open a new one, even if the failing test is the same one. Keeps the books more ir check. :)

Created a PR for the new failure: #23972
