### ISSUE TITLE
Exception when Running Akka Actors in Spark using databricks

### ISSUE THREAD

**Issue by arcalderon** [akka/akka#23538]
[ERROR] [08/16/2017 19:58:04.091] [system-akka.actor.default-dispatcher-7] [akka://system/user/StreamSupervisor-15/flow-0-0-ignoreSink] Error in stage [StatefulMapConcat]: Element must not be null, rule 2.13
java.lang.NullPointerException: Element must not be null, rule 2.13
	at akka.stream.impl.ReactiveStreamsCompliance$.elementMustNotBeNullException(ReactiveStreamsCompliance.scala:46)
	at akka.stream.impl.ReactiveStreamsCompliance$.requireNonNullElement(ReactiveStreamsCompliance.scala:72)
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:510)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$28.pushPull(Ops.scala:1844)
	at akka.stream.impl.fusing.StatefulMapConcat$$anon$28.onPull(Ops.scala:1868)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:506)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:412)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by patriknw** [comment]
@arcalderon Null elements are not allowed. Could it be that the statefulMapConcat in your system emits an null element?

**Comment by johanandren** [comment]
Closing this as there hasn't been any response in a month and it most likely is a user error, emitting null from a stage.

**Comment by arcalderon** [comment]
@patriknw you were absolutely right. One of the entries I had was null. Thanks.
