### ISSUE TITLE
Illegal response status code: 518

### ISSUE THREAD

**Issue by Venkatachalapatee** [akka/akka#23541]
I am getting the following, Any idea about what is 518 error code. 

akka.http.scaladsl.model.IllegalResponseException: Illegal response status code: 518
	at akka.http.impl.engine.client.OutgoingConnectionBlueprint$PrepareResponse$$anon$1.onPush(OutgoingConnectionBlueprint.scala:191)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

Source.single(req -> requestId)
      .via(flow)
      .runWith(Sink.head)
      .flatMap(response => response._1 match {
        case Success(resp@HttpResponse(statusCode, _, _, _)) => statusCode match {
          case StatusCodes.PermanentRedirect | StatusCodes.TemporaryRedirect | StatusCodes.Found =>
       
            // Discard the Entity, preventing the Akka from apply back pressure.
            resp.discardEntityBytes()
           
            //Redirect Request
            Http().singleRequest(req.withUri(resp.header[Location].get.uri))
          case _ =>

            Future(resp)
        }
      }).flatMap(resp =>
      {

        resp.status match {
          case StatusCodes.NotImplemented =>
            resp.discardEntityBytes()
            HttpResponse(500) //Send errror
          case _ => Future(resp)
      }
    }).flatMap(HttpUtils.toStrict)

```

**Comment by Venkatachalapatee** [comment]
518 was custom error code. Closing this issue.

**Comment by ozmad** [comment]
This is how one can register custom codes:
https://doc.akka.io/docs/akka-http/current/common/http-model.html#registering-custom-status-codes
