### ISSUE TITLE
value of _interpreter variable may not visible when an AsyncCallback is invoked

### ISSUE THREAD

**Issue by swachter** [akka/akka#23556]
I have a custom GraphStageWithMaterializedValue that uses an AsyncCallback to invoke a method via the materialized value of the stage. I got the following IllegalStateException (sporadically)

```
java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
  at akka.stream.stage.GraphStageLogic.interpreter(GraphStage.scala:295)
  at akka.stream.stage.GraphStageLogic$$anon$1.invoke(GraphStage.scala:960)
```

that seems to be caused by the fact that access to the `_interpreter` variable of the GraphStage logic by an invoke of an AsyncCallback is not synchronized and the `_interpreter` is not marked `volatile`.

```
  /**
   * INTERNAL API
   */
  private[this] var _interpreter: GraphInterpreter = _

  ...

  /**
   * INTERNAL API
   */
  private[akka] def interpreter: GraphInterpreter =
    if (_interpreter == null)
      throw new IllegalStateException("not yet initialized: only setHandler is allowed in GraphStageLogic constructor")
    else _interpreter

  ...

  final def getAsyncCallback[T](handler: T ⇒ Unit): AsyncCallback[T] = {
    new AsyncCallback[T] {
      override def invoke(event: T): Unit =
        interpreter.onAsyncInput(GraphStageLogic.this, event, handler.asInstanceOf[Any ⇒ Unit])
    }
  }
```

**Comment by patriknw** [comment]
This is a duplicate of https://github.com/akka/akka/issues/20503 and it is in progress (see PR https://github.com/akka/akka/pull/23185)
