### ISSUE TITLE
Akka StreamConvertes timeout error in versions 2.5.x

### ISSUE THREAD

**Issue by wookie41** [akka/akka#23570]
One of the apps that I'm working on is using akka (mainly actor and stream modules), currently vesion `2.4.17`, with Scala's version `2.11`, meaning it's the following [artifact][1].

We wanted to update to the latest version of akka, which is `2.5.4`, but during the upgrade we've encountered a problem. 

The following code works well under `2.4.17`, but fails under `2.5.4`.

Example code:

    Source
        .single(ByteString.fromString("A"))
        .to(StreamConverters.asInputStream().mapMaterializedValue(inputStream -> { System.out.println(inputStream.read());  return "ok";}))
        .run(ActorMaterializer.create(ActorSystem.create()));

Under `2.4.17` it prints, `A`, under `2.5.4` fail with:

    Exception in thread "main" java.io.IOException: Timeout after 5 seconds waiting for Initialized message from stage
    	at akka.stream.impl.io.InputStreamAdapter.waitIfNotInitialized(InputStreamSinkStage.scala:214)
    	at akka.stream.impl.io.InputStreamAdapter.executeIfNotClosed(InputStreamSinkStage.scala:123)
    	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:144)
    	at akka.stream.impl.io.InputStreamAdapter.read(InputStreamSinkStage.scala:130)
    	at test.lambda$main$570cdad2$1(test.java:12)
    	at akka.stream.javadsl.Sink$$anonfun$mapMaterializedValue$1.apply(Sink.scala:322)
    	at akka.stream.impl.Transform.apply(TraversalBuilder.scala:155)
    	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:482)
    	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:420)
    	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:415)
    	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:496)
    	at akka.stream.javadsl.RunnableGraph$RunnableGraphAdapter.run(Flow.scala:2260)
    	at test.main(test.java:13)

Any ideas? 

  [1]: https://mvnrepository.com/artifact/com.typesafe.akka/akka-actor_2.11/2.4.17

**Comment by wookie41** [comment]
Maybe it's got something to do with [this](http://doc.akka.io/docs/akka/2.5.3/scala/project/migration-guide-2.4.x-2.5.x.html#removal-of-source-transform-replaced-by-via)

**Comment by johanandren** [comment]
It has to do with this #21504

As you are calling a blocking method inside the mapMaterialized value which depends on the stream running, you may end up deadlocking. Don't block the materialization.

**Comment by johanandren** [comment]
Also, see warning in the docs here: http://doc.akka.io/docs/akka/current/scala/stream/stages-overview.html#additional-sink-and-source-converters
