### ISSUE TITLE
failed: SurviveNetworkInstabilitySpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23592]
https://jenkins.akka.io:8498/job/akka-multi-node/2279

**Comment by raboof** [comment]
Possibly related to #18767, #21247

**Comment by raboof** [comment]
The logging shows the nodes from `side2` (`fifth`, `sixth`, `seventh`) are still visible on `first` and `third` (fails on line 345, `clusterView.members.map(_.address) should ===(expected)`).

Interestingly, `fourth` seems to have already moved on to the `side2-removed` barrier, so the `awaitAssert` may be looping on `first` and `third` but that doesn't have any effect on `fourth`, and thus the `cluster.down(` is not triggered again on `fourth`.

Not sure how to make that more reliable though, ideas?

**Comment by jrudolph** [comment]
Seemed to have happened again (https://jenkins.akka.io:8498/job/akka-multi-node/3781/consoleFull):

```
[info] [JVM-7] - must heal after unreachable when ring is changed (on node 'seventh', class akka.cluster.SurviveNetworkInstabilityMultiJvmNode7) *** FAILED *** (59 seconds, 936 milliseconds)
[info] [JVM-7]   Set(akka://SurviveNetworkInstabilitySpec@a5.moxie:43457, akka://SurviveNetworkInstabilitySpec@a5.moxie:46211, akka://SurviveNetworkInstabilitySpec@a4.moxie:36737, akka://SurviveNetworkInstabilitySpec@a6.moxie:44383, akka://SurviveNetworkInstabilitySpec@a6.moxie:37447) did not equal Set(akka://SurviveNetworkInstabilitySpec@a5.moxie:43457, akka://SurviveNetworkInstabilitySpec@a6.moxie:44383, akka://SurviveNetworkInstabilitySpec@a5.moxie:46211, akka://SurviveNetworkInstabilitySpec@a6.moxie:37447) (SurviveNetworkInstabilitySpec.scala:121)
[info] [JVM-7]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-7]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info] [JVM-7]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
[info] [JVM-7]   at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$assertUnreachable$2(SurviveNetworkInstabilitySpec.scala:121)
[info] [JVM-7]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:327)
[info] [JVM-7]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:344)
[info] [JVM-7]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:316)
[info] [JVM-7]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:928)
[info] [JVM-7]   at akka.cluster.SurviveNetworkInstabilitySpec.assertUnreachable(SurviveNetworkInstabilitySpec.scala:121)
[info] [JVM-7]   at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$new$36(SurviveNetworkInstabilitySpec.scala:262)
[info] [JVM-7]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:384)
[info] [JVM-7]   at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$new$29(SurviveNetworkInstabilitySpec.scala:262)
[info] [JVM-7]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-7]   at akka.testkit.TestKitBase.within(TestKit.scala:375)
[info] [JVM-7]   at akka.testkit.TestKitBase.within$(TestKit.scala:363)
[info] [JVM-7]   at akka.testkit.TestKit.within(TestKit.scala:928)
[info] [JVM-7]   at akka.testkit.TestKitBase.within(TestKit.scala:390)
[info] [JVM-7]   at akka.testkit.TestKitBase.within$(TestKit.scala:390)
[info] [JVM-7]   at akka.testkit.TestKit.within(TestKit.scala:928)
[info] [JVM-7]   at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$new$28(SurviveNetworkInstabilitySpec.scala:238)
```

**Comment by patriknw** [comment]
Closing as old
