### ISSUE TITLE
failed: RestartSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#23593]
https://jenkins.akka.io:8498/job/akka-nightly/4740

```
[ERROR] [09/03/2017 03:55:41.080] [RestartSpec-akka.actor.default-dispatcher-3] [akka.dispatch.Dispatcher] assertion failed: timeout (3 seconds) during expectMsg: 
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg: 
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:404)
	at akka.testkit.TestKit.expectMsgPF(TestKit.scala:831)
	at akka.stream.testkit.StreamTestKit$PublisherProbeSubscription.expectRequest(StreamTestKit.scala:761)
	at akka.stream.testkit.TestPublisher$Probe.sendNext(StreamTestKit.scala:195)
	at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$16$$anonfun$apply$26$$anonfun$apply$27.apply(RestartSpec.scala:317)
	at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$16$$anonfun$apply$26$$anonfun$apply$27.apply(RestartSpec.scala:316)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

--- Stream actors debug dump ---
Stream actors alive: List(Actor[akka://RestartSpec/user/StreamSupervisor-209/flow-44-0-unnamed#-60190210], Actor[akka://RestartSpec/user/StreamSupervisor-209/flow-45-0-unnamed#1981245514], Actor[akka://RestartSpec/user/StreamSupervisor-209/flow-49-0-unnamed#51056665], Actor[akka://RestartSpec/user/StreamSupervisor-209/flow-50-0-unnamed#-1391320023])
[info] - should restart on completion *** FAILED *** (5 seconds, 90 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:313)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:304)
[info]   at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$15.apply(RestartSpec.scala:386)
[info]   at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$15.apply(RestartSpec.scala:373)
```

We fixed something in #23484 but this failed afterwards. Perhaps something else?

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2283/consoleFull

**Comment by ktoso** [comment]
Looking into it again

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2301/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5295/console

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/844/consoleFull

**Comment by patriknw** [comment]
I looked some at the RestartSpec, and it's way too timing sensitive. I'll see if I can improve that.

**Comment by patriknw** [comment]
No guarantees that I fixed the exact issue that was reported here, but since the test was so sensitive I didn't fully trust it. Let's open new issue if it fails again.
