### ISSUE TITLE
akka-persistence: actor crash when using stash() from persist callback

### ISSUE THREAD

**Issue by fredfp** [akka/akka#23639]
I think that this is about a crash related to stashing messages from within the `persist` callback.

I'm not sure whether this is a bug in akka-persistence, or if some documentation should be added to explain that messages cannot be stashed from the `persist` callback.

How to reproduce with a minimal scala example:

```scala
import akka.actor.{ ActorSystem, Props }
import akka.persistence._
import akka.testkit.{ ImplicitSender, TestActors, TestKit }
import org.scalatest.{ BeforeAndAfterAll, Matchers, WordSpecLike }

class StashTest() extends TestKit(ActorSystem("StashTest")) with ImplicitSender
    with WordSpecLike with Matchers with BeforeAndAfterAll {

  override def afterAll {
    TestKit.shutdownActorSystem(system)
  }

  "A stashing persistent actor" must {
    "not crash" in {
      val actor = system.actorOf(Props[StashActor])
      actor ! "push1"
      expectMsg("push1")
      actor ! "push2"
      expectMsg("push2")
      actor ! "pop"
      expectMsg("pop-push2")
      actor ! "pop"
      expectMsg("pop-push1")
      actor ! "pop"
      expectNoMsg()
      actor ! "push3"
      expectMsg("push3")
      expectMsg("pop-push3")
    }
  }
}

class StashActor extends PersistentActor {
  override def persistenceId = "sample-id-1"
  override def journalPluginId = "akka.persistence.journal.inmem"  
  override def snapshotPluginId = "akka.persistence.no-snapshot-store"
  
  var state: List[String] = Nil

  val receiveRecover: Receive = {
    case "pop" if state.isEmpty => stash()
    case "pop" =>
      sender ! ("pop-" + state.head)
      state = state.tail
    case push: String if push.startsWith("push") =>
      state = push :: state
      sender() ! push
      unstashAll()
    case RecoveryCompleted =>
    case other => println("Unhandled message: " + other)
  }

  val receiveCommand: Receive = {
    case msg =>
      persist(msg) { m =>
        receiveRecover(m)
      }
  }
}
```

The following `build.sbt` is enough:
```
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-persistence" % "2.5.4",
  "com.typesafe.akka" %% "akka-testkit" % "2.5.4" % "test",
  "org.scalatest" %% "scalatest" % "3.0.1" % "test"
)
```

The actor crashes with the following stacktrace:

> java.util.NoSuchElementException
>         at java.util.LinkedList.removeFirst(LinkedList.java:270)
>         at java.util.LinkedList.pop(LinkedList.java:801)
>         at akka.persistence.Eventsourced$$anon$1.onWriteMessageComplete(Eventsourced.scala:675)
>         at akka.persistence.Eventsourced$ProcessingState$$anonfun$2.applyOrElse(Eventsourced.scala:611)
>         at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
>         at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:661)
>         at akka.persistence.Eventsourced.aroundReceive(Eventsourced.scala:183)
>         at akka.persistence.Eventsourced.aroundReceive$(Eventsourced.scala:182)
>         at StashActor.aroundReceive(StashTest.scala:33)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:496)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
>         at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

And then during the replay, the actor receives the following message (evidenced by the `case other =>` in `receiveRecover`:
> ReplayedMessage(PersistentImpl(pop,5,sample-id-1,,false,null,4e070155-13c4-4c36-8c9d-ba3489a073b8))

**Comment by johanandren** [comment]
Neither stashing nor responding to `sender()` while recovering makes sense, recover must apply all events or else you will reach an invalid state compared to the persisted state.

Additionally, in the persist callback you have already accepted and persisted the fact that you accepted the message so stashing it is something really strange to do there. In a persistent actor you would accept a command, and either decide to stash it or make an event for it and persist that, not both.

Could you describe a use case where you think it make sense to do this?

**Comment by fredfp** [comment]
Thank you, I agree with what you said and have no good use case.

To make it short, I think that what is missing is a short statement in the persistence docs, warning against stashing from the persistence callback. An additional step (but probably of little value, if at all possible) could be to either detect `stash()` calls in the persist callbacks and/or give a hint in the thrown exception.

Only a short sentence in the docs would have spared me some time looking for the source of the problems mentioned in my initial description.

**Comment by raboof** [comment]
In fact we have a PR open to throw an exception when someone calls `stash()` from a `persist` callback, but it appears that got stuck while trying to determine whether the change was introducing a binary incompatibility, see #22615
