### ISSUE TITLE
FutureFlattenSourceSpec: handle downstream cancelling before the underlying Future completes

### ISSUE THREAD

**Issue by raboof** [akka/akka#23656]
```
[ERROR] [09/19/2017 04:31:10.939] [FutureFlattenSourceSpec-akka.test.stream-dispatcher-9] [akka://FutureFlattenSourceSpec/user/StreamSupervisor-279/flow-8-0-terminationWatcher] null
java.lang.NullPointerException
	at akka.event.LogSource$$anon$6.genString(Logging.scala:283)
	at akka.event.LogSource$$anon$6.genString(Logging.scala:282)
	at akka.event.LogSource$.apply(Logging.scala:306)
	at akka.event.Logging$.apply(Logging.scala:557)
	at akka.stream.impl.fusing.GraphInterpreterShell.log$lzycompute(ActorGraphInterpreter.scala:448)
	at akka.stream.impl.fusing.GraphInterpreterShell.log(ActorGraphInterpreter.scala:448)
	at akka.stream.impl.fusing.GraphInterpreterShell.interpreter$lzycompute(ActorGraphInterpreter.scala:483)
	at akka.stream.impl.fusing.GraphInterpreterShell.interpreter(ActorGraphInterpreter.scala:483)
	at akka.stream.impl.fusing.GraphInterpreterShell.toString(ActorGraphInterpreter.scala:626)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(ActorGraphInterpreter.scala:763)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(ActorGraphInterpreter.scala:761)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:761)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must handle downstream cancelling before the underlying Future completes *** FAILED *** (7 seconds, 50 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected no StreamSupervisor children, but got [Actor[akka://FutureFlattenSourceSpec/user/StreamSupervisor-279/flow-8-0-terminationWatcher#1909747338]]
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Utils.scala:31)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1$$anonfun$apply$mcV$sp$1.apply(Utils.scala:28)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:302)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:313)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:835)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply$mcV$sp(Utils.scala:28)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.stream.testkit.Utils$$anonfun$assertAllStagesStopped$1.apply(Utils.scala:26)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:344)
[info]   at akka.testkit.TestKit.within(TestKit.scala:835)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:358)
[info]   at akka.testkit.TestKit.within(TestKit.scala:835)
[info]   at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:26)
[info]   at akka.stream.scaladsl.FutureFlattenSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(FutureFlattenSourceSpec.scala:81)
[info]   at akka.stream.scaladsl.FutureFlattenSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(FutureFlattenSourceSpec.scala:81)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:59)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:59)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:59)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by raboof** [comment]
Again: https://jenkins.akka.io:8498/job/akka-multi-node/2300/consoleFull

**Comment by raboof** [comment]
Suspiciously, almost 3 times in a row. Saw it locally once, but not anymore :/

https://jenkins.akka.io:8498/job/akka-multi-node/2302/consoleFull

**Comment by raboof** [comment]
Another instance at https://jenkins.akka.io:8498/job/akka-multi-node/2304/consoleFull, but that was before #23661 was merged so might be OK

**Comment by raboof** [comment]
Unfortunately it looks like the NPE fixed in #23661 was only a symptom and the underlying issue is still there, https://jenkins.akka.io:8498/job/akka-multi-node/2311/consoleFull

**Comment by jrudolph** [comment]
More instances:

https://jenkins.akka.io:8498/job/akka-multi-node/2312/consoleFull
https://jenkins.akka.io:8498/job/akka-multi-node/2315/testReport/junit/akka.stream.scaladsl/FutureFlattenSourceSpec/Future_source_must_handle_downstream_cancelling_before_the_underlying_Future_completes/
https://jenkins.akka.io:8498/job/akka-multi-node/2316/testReport/junit/akka.stream.scaladsl/FutureFlattenSourceSpec/Future_source_must_handle_downstream_cancelling_before_the_underlying_Future_completes/

**Comment by 2m** [comment]
There was one more, might be the last one, who knows. I'll keep posting those, as they come.

https://jenkins.akka.io:8498/job/akka-multi-node/2332/consoleFull
