### ISSUE TITLE
Akka system down, no log to method the root cause even turn on akka debug log

### ISSUE THREAD

**Issue by ChanglinZhou** [akka/akka#23684]
After hours of debugging, The root cause is found: using assert in the actor code, and assertion failed. It will be very nice to log the root cause in log.

**Comment by johanandren** [comment]
The reason is that assertion throws an `Error` and not an `Exception` and usually errors are unrecoverable problems with the JVM, for example out of memory, meaning that executing some logging logic would be dangerous or impossible. But maybe we could special case `java.lang.AssertionError`.

Would you be up for looking into it and sending in a PR?

**Comment by ChanglinZhou** [comment]
Please check the PR https://github.com/akka/akka/pull/23706.

Thank you

**Comment by johanandren** [comment]
Actually, I cannot repeat this, with this code: 
```
 val system = ActorSystem("name")

  val ref = system.actorOf(Props(new Actor {
    override def receive: Receive = {
      case whatever => assert(false)
    }
  }))

  ref ! "test"
```

I get a clear error message:
```
[ERROR] [09/22/2017 18:27:51.597] [name-akka.actor.default-dispatcher-3] [akka.actor.LocalActorRefProvider(akka://name)] guardian failed, shutting down system
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at basics.BasicPlayground$$anonfun$1$$anon$1$$anonfun$receive$1.applyOrElse(BasicPlayground.scala:14)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at basics.BasicPlayground$$anonfun$1$$anon$1.aroundReceive(BasicPlayground.scala:12)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
...
```

Is there some more circumstances that makes it disappear in your case perhaps?

**Comment by ChanglinZhou** [comment]
Ok, "guardian failed, shutting down system" is the message which indicates system is shutting down.

**Comment by ChanglinZhou** [comment]
guardian-supervisor-strategy = "your-strategy"

And the strategy related code:

case class MyOneForOneStrategy(
                              maxNrOfRetries:              Int      = -1,
                              withinTimeRange:             Duration = Duration.Inf,
                              override val loggingEnabled: Boolean  = true)(val decider: SupervisorStrategy.Decider)
  extends SupervisorStrategy {

  /**
    * Java API
    */
  def this(maxNrOfRetries: Int, withinTimeRange: Duration, decider: SupervisorStrategy.JDecider, loggingEnabled: Boolean) =
    this(maxNrOfRetries, withinTimeRange, loggingEnabled)(SupervisorStrategy.makeDecider(decider))

  /**
    * Java API
    */
  def this(maxNrOfRetries: Int, withinTimeRange: Duration, decider: SupervisorStrategy.JDecider) =
    this(maxNrOfRetries, withinTimeRange)(SupervisorStrategy.makeDecider(decider))

  /**
    * Java API
    */

  /**
    * Java API: compatible with lambda expressions
    */
  def this(maxNrOfRetries: Int, withinTimeRange: Duration, decider: SupervisorStrategy.Decider) =
    this(maxNrOfRetries = maxNrOfRetries, withinTimeRange = withinTimeRange)(decider)

  def this(loggingEnabled: Boolean, decider: SupervisorStrategy.Decider) =
    this(loggingEnabled = loggingEnabled)(decider)

  /**
    * Java API: compatible with lambda expressions
    */
  def this(decider: SupervisorStrategy.Decider) =
    this()(decider)

  /*
   *  this is a performance optimization to avoid re-allocating the pairs upon
   *  every call to requestRestartPermission, assuming that strategies are shared
   *  across actors and thus this field does not take up much space
   */
  private val retriesWindow = (
    SupervisorStrategy.maxNrOfRetriesOption(maxNrOfRetries),
    SupervisorStrategy.withinTimeRangeOption(withinTimeRange).map(_.toMillis.toInt))

  def handleChildTerminated(context: ActorContext, child: ActorRef, children: Iterable[ActorRef]): Unit = ()

  def processFailure(context: ActorContext, restart: Boolean, child: ActorRef, cause: Throwable, stats: ChildRestartStats, children: Iterable[ChildRestartStats]): Unit = {
    if (restart && stats.requestRestartPermission(retriesWindow))
      restartChild(child, cause, suspendFirst = false)
    else
      context.stop(child) //TODO optimization to drop child here already?
  }

  override  def logFailure(context: ActorContext, child: ActorRef, cause: Throwable, decision: Directive): Unit =
    if (loggingEnabled) {
      val logMessage = cause match {
        case e: ActorInitializationException if e.getCause ne null ⇒ e.getCause match {
          case ex: InvocationTargetException if ex.getCause ne null ⇒ ex.getCause.getMessage
          case ex ⇒ ex.getMessage
        }
        case e ⇒ e.getMessage
      }
      decision match {
        case Resume   ⇒ publish(context, Warning(child.path.toString, getClass, logMessage))
        case Escalate ⇒ publish(context, Error(cause, child.path.toString, getClass, logMessage))
        case _        ⇒ publish(context, Error(cause, child.path.toString, getClass, logMessage))
      }
    }

  private def publish(context: ActorContext, logEvent: LogEvent): Unit =
    try context.system.eventStream.publish(logEvent) catch { case NonFatal(_) ⇒ }
}

final class SuperVisorStrategyConfig extends SupervisorStrategyConfigurator {
  final val defaultDecider: Decider = {
    case _: ActorInitializationException ⇒ Stop
    case _: ActorKilledException         ⇒ Stop
    case _: DeathPactException           ⇒ Stop
    case _: Exception                    ⇒ Restart
  }

  /**
    * When supervisorStrategy is not specified for an actor this
    * is used by default. OneForOneStrategy with decider defined in
    * [[#defaultDecider]].
    */
  final val defaultStrategy: SupervisorStrategy = {
    MyOneForOneStrategy()(defaultDecider)
  }

  override def create(): SupervisorStrategy = defaultStrategy
}
