### ISSUE TITLE
Akka Remote issue with Artery and Java 9

### ISSUE THREAD

**Issue by guidomedina** [akka/akka#23702]
Got the following exception at startup:
```
ERROR 14:01:06,265 Encoder - Failed to serialize message [akka.remote.artery.OutboundHandshake$HandshakeReq].
java.lang.ClassCastException: [B cannot be cast to [C
    at akka.remote.artery.EnvelopeBuffer.writeLiteral(BufferPool.scala:502) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.artery.EnvelopeBuffer.writeHeader(BufferPool.scala:414) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:84) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.remote.artery.Encoder$$anon$2.onPush(Codecs.scala:125) ~[akka-remote_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.actor.Actor.aroundReceive(Actor.scala:514) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.actor.Actor.aroundReceive$(Actor.scala:512) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.4.jar:?]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.12-2.5.4.jar:?]
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.12-2.5.4.jar:?]
```

**Comment by guidomedina** [comment]
@patriknw the issue might be easier to fix, this is the relevant block of code causing the issue
```
      val chars = Unsafe.instance.getObject(literal, StringValueFieldOffset).asInstanceOf[Array[Char]]
      var i = 0
      while (i < length) {
        // UsAscii
        bytes(i) = chars(i).asInstanceOf[Byte]
        i += 1
      }
```
maybe get it as `Array[Byte]`, and then just go through the bytes, no further casting will be needed, it might even slightly improve performance because the loop casts back to byte.

**Comment by guidomedina** [comment]
I wonder what happens if you try directly with bytes in Java 8.

**Comment by guidomedina** [comment]
Closing to re-open as PR only.
