### ISSUE TITLE
FAILED: RemoteReDeploymentFast

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23717]
https://jenkins.akka.io:8498/job/akka-release-2.4/331/consoleFull

Maybe related `RemoteReDeploymentSlow` failure:  #20180 

```
[JVM-1] - must terminate the child when its parent system is replaced by a new one *** FAILED *** (5 seconds, 571 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message PostStop
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg_internal(TestKit.scala:616)
[JVM-1]   at akka.testkit.TestKitBase$class.expectNoMsg(TestKit.scala:612)
[JVM-1]   at akka.testkit.TestKit.expectNoMsg(TestKit.scala:814)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RemoteReDeploymentSpec.scala:177)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:121)
[JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RemoteReDeploymentSpec.scala:121)
[JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[JVM-1]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[JVM-1]   at akka.remote.RemotingMultiNodeSpec.withFixture(RemotingMultiNodeSpec.scala:37)
[JVM-1]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[JVM-1]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[JVM-1]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[JVM-1]   at akka.remote.RemotingMultiNodeSpec.runTest(RemotingMultiNodeSpec.scala:27)
[JVM-1]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
```

**Comment by patriknw** [comment]
Looks like we have several issues for RemoteReDeploymentSpec, which probably/hopefully are all the same. Closing in favor of https://github.com/akka/akka/issues/23838
