### ISSUE TITLE
FAILED: MultiDcClusterSharding

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23741]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/880/consoleFull

```
[JVM-4] - must join cluster (on node 'fourth', class akka.cluster.sharding.MultiDcClusterShardingMultiJvmNode4) *** FAILED ***
[JVM-4]   false was not true (MultiDcClusterShardingSpec.scala:94)
[JVM-1] [DEBUG] [09/27/2017 12:38:54.716] [New I/O worker #2] [akka.remote.testconductor.ConductorHandler(akka://MultiDcClusterShardingSpec)] message from /10.0.1.235:42889: EnterBarrier(after-2,Some(29999979321 nanoseconds))
[JVM-4] [DEBUG] [09/27/2017 12:38:54.725] [New I/O worker #1] [akka.remote.testconductor.PlayerHandler(akka://MultiDcClusterShardingSpec)] message from a4.moxie/10.0.1.234:4711: BarrierResult(after-2,false)
[JVM-1] [DEBUG] [09/27/2017 12:38:54.726] [New I/O worker #4] [akka.remote.testconductor.PlayerHandler(akka://MultiDcClusterShardingSpec)] message from /10.0.1.234:4711: BarrierResult(fourth-joined,false)
[JVM-3] [DEBUG] [09/27/2017 12:38:54.727] [New I/O worker #1] [akka.remote.testconductor.PlayerHandler(akka://MultiDcClusterShardingSpec)] message from a4.moxie/10.0.1.234:4711: BarrierResult(fourth-joined,false)
[JVM-2] [DEBUG] [09/27/2017 12:38:54.727] [New I/O worker #1] [akka.remote.testconductor.PlayerHandler(akka://MultiDcClusterShardingSpec)] message from a4.moxie/10.0.1.234:4711: BarrierResult(fourth-joined,false)
[JVM-1] [ERROR] [09/27/2017 12:38:54.726] [MultiDcClusterShardingSpec-akka.actor.default-dispatcher-9] [akka://MultiDcClusterShardingSpec/user/controller/barriers] RoleName(fourth) tried to enter 'after-2' while we were waiting for 'fourth-joined' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier: RoleName(fourth) tried to enter 'after-2' while we were waiting for 'fourth-joined')
[JVM-4] - must initialize shards (on node 'fourth', class akka.cluster.sharding.MultiDcClusterShardingMultiJvmNode4) *** FAILED ***
[JVM-4]   java.lang.RuntimeException: barrier failed: after-2
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-4]   at akka.actor.FSM$class.processEvent(FSM.scala:665)
[JVM-4]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
[JVM-4]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:801)
[JVM-4]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:157)
[JVM-4]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:659)
[JVM-4]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
[JVM-4]   at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
```

Previous case, #23582, was closed 2 days ago, so maybe it wasn't yet fixed?

**Comment by ktoso** [comment]
Again https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/905/consoleFull

**Comment by chbatey** [comment]
Added https://github.com/akka/akka/pull/23868 will check back when it fails again

**Comment by jrudolph** [comment]
New failure here: https://jenkins.akka.io:8498/job/akka-multi-node/2411/consoleFull

**Comment by chbatey** [comment]
This look consistently broken now, taking a look

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5497/consoleFull

**Comment by chbatey** [comment]
Last one was the typed test ^

Raised https://github.com/akka/akka/issues/25190
