### ISSUE TITLE
Javadoc generation fails under jdk11

### ISSUE THREAD

**Issue by raboof** [akka/akka#23756]
When building with jdk9, the javadoc is not successfully generated.

The in-process javadoc tool is invoked on the java code generated by [genjavadoc](https://github.com/typesafehub/genjavadoc). Because genjavadoc's code generation is not perfect, this produces a number of errors.

Finally, genjavadoc fails with a `NullPointerException`:
```
com.sun.tools.doclets.internal.toolkit.util.DocletAbortException: java.lang.NullPointerException
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:154)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractMemberBuilder.build(AbstractMemberBuilder.java:79)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.buildChildren(AbstractBuilder.java:173)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.MethodBuilder.buildMethodDoc(MethodBuilder.java:168)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.invokeMethod(AbstractBuilder.java:192)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:140)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractMemberBuilder.build(AbstractMemberBuilder.java:79)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.buildChildren(AbstractBuilder.java:173)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.buildMethodDetails(ClassBuilder.java:414)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.invokeMethod(AbstractBuilder.java:192)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:140)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.buildChildren(AbstractBuilder.java:173)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.buildMemberDetails(ClassBuilder.java:354)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.invokeMethod(AbstractBuilder.java:192)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:140)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.buildChildren(AbstractBuilder.java:173)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.buildClassDoc(ClassBuilder.java:147)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.invokeMethod(AbstractBuilder.java:192)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.AbstractBuilder.build(AbstractBuilder.java:140)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.builders.ClassBuilder.build(ClassBuilder.java:119)
        at jdk.javadoc/com.sun.tools.doclets.formats.html.HtmlDoclet.generateClassFiles(HtmlDoclet.java:236)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:206)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.AbstractDoclet.generateClassFiles(AbstractDoclet.java:191)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:146)
        at jdk.javadoc/com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startDoclet(AbstractDoclet.java:89)
        at jdk.javadoc/com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:80)
        at jdk.javadoc/com.sun.tools.doclets.standard.Standard.start(Standard.java:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.invoke(DocletInvoker.java:332)
        at jdk.javadoc/com.sun.tools.javadoc.main.DocletInvoker.start(DocletInvoker.java:211)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.parseAndExecute(Start.java:453)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:238)
        at jdk.javadoc/com.sun.tools.javadoc.main.Start.begin(Start.java:224)
        at jdk.javadoc/com.sun.tools.javadoc.Main.execute(Main.java:173)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at sbt.internal.inc.javac.LocalJava$.unsafeJavadoc(LocalJava.scala:76)
        at sbt.internal.inc.javac.LocalJavadoc.run(LocalJava.scala:100)
        at sbt.inc.Doc$$anon$1.run(Doc.scala:64)
        at sbt.inc.Doc$$anon$2.run(Doc.scala:83)
        at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:106)
        at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:102)
        at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
        at sbt.inc.Doc$$anon$3.run(Doc.scala:110)
        at sbtunidoc.Unidoc$.apply(Unidoc.scala:40)
        at sbtunidoc.BaseUnidocPlugin$.$anonfun$baseUnidocSettings$1(BaseUnidocPlugin.scala:25)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:266)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
```

It looks like this `NullPointerException` prevents the javadocs from being generated: `target/javaunidoc` contains some files but nowhere near the complete set:

```
✗ find target/javaunidoc
target/javaunidoc
target/javaunidoc/akka
target/javaunidoc/akka/remote
target/javaunidoc/akka/remote/AckedSendBuffer.html
target/javaunidoc/akka/remote/ArteryControlFormats.html
target/javaunidoc/akka/remote/AddressUrlEncoder$.html
target/javaunidoc/akka/remote/Ack.html
target/javaunidoc/akka/remote/AckedReceiveBuffer$.html
target/javaunidoc/akka/remote/AckedSendBuffer$.html
target/javaunidoc/akka/remote/AckedReceiveBuffer.html
target/javaunidoc/akka/remote/AddressUidExtension$.html
target/javaunidoc/akka/remote/AddressUrlEncoder.html
target/javaunidoc/akka/remote/Ack$.html
target/javaunidoc/akka/remote/AddressUidExtension.html
```

It's not obvious whether the `NullPointerException` is a result of the javadoc errors.

**Comment by ktoso** [comment]
Hmm weird, this very much seems like a gen java doc thing :( seems perhaps there’s some edge cases in type of class that would cause this?

**Comment by raboof** [comment]
It turned out the  `NullPointerException` was somehow triggered by `-Ywarn-unused:explicits` (see also #26441).

However, `sbt -Dakka.genjavadoc.enabled=true unidoc` still fails for me when run under jdk11.

**Comment by raboof** [comment]
Figured it out: this failure was triggered by the addition of `-Yrangepos` to the scalac flags. This is not wrong, but triggered a bug in genjavadoc that is apparently so serious that cannot be ignored though `--ignore-source-errors`.

https://github.com/lightbend/genjavadoc/pull/165 fixes the genjavadoc problem, and makes javadoc generation succeed again.
