### ISSUE TITLE
java.lang.invoke.WrongMethodTypeException with "affinity-pool-executor"

### ISSUE THREAD

**Issue by yanns** [akka/akka#23792]
Hello,

I'm trying to use the "affinity-pool-executor":
```
akka {
  actor {
    default-dispatcher {
      executor: "affinity-pool-executor"
    }
  }
}
```

I got the following runtime error:
```
root java.lang.invoke.WrongMethodTypeException: expected ()void but found ()Object
root 	at java.base/java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:468)
root 	at java.base/java.lang.invoke.Invokers.checkExactType(Invokers.java:477)
root 	at akka.dispatch.affinity.AffinityPool$IdleStrategy.idle(AffinityPool.scala:90)
root 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.executeNext$1(AffinityPool.scala:268)
root 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.runLoop$1(AffinityPool.scala:283)
root 	at akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.run(AffinityPool.scala:294)
root 	at java.base/java.lang.Thread.run(Thread.java:844)
```

I'm running on java 9.

**Comment by zaharidichev** [comment]
I assume u do not get the same problem on Java8 ? 

Zahari
