### ISSUE TITLE
Akka.Status.Failure.ToString() throws when Cause is null

### ISSUE THREAD

**Issue by HenryTonnison** [akka/akka#23820]
**Akka.Actor.Futures.Ask(this ICanTell self, object message, TimeSpan? timeout = null)**
will cancel the Task if the Timeout is reached.

The cancelled task is then handled by PipeTo
**Akka.Actor.PipeToSupport.PipeTo<T>(this Task<T> taskToPipe, ICanTell recipient, IActorRef sender = null, Func<T, object> success = null, Func<Exception, object> failure = null)**

_if (tresult.IsCanceled || tresult.IsFaulted)
{
          recipient.Tell(failure != null ? failure((Exception) tresult.Exception) : **(object) new Status.Failure((Exception) tresult.Exception)**, sender);
 }_

When the new Status.Failure() is created when task is cancelled the Exception is null.
**Akka.Actor.Failure.ToString()**
{
       return "Failure: " + this.Cause.ToString();
}

Then blows up, in akka's own logging.

System.NullReferenceException: Object reference not set to an instance of an object.
   at **Akka.Actor.Status.Failure.ToString()**
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.ToDebug(UnhandledMessage message)
   at Akka.Event.LoggingBus.UnhandledMessageForwarder.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

--------------------------------------
My opinion....

1. Failure.ToString() handles null.
2. In PipeTo, if the task is cancelled, fail with a TaskCanceledException
3. The Ask doesn't cancel a task on timeout but raises a TimeoutException

**Comment by ktoso** [comment]
Uhm, seems you mean to report this on the .net port of Akka?
Please report this here: https://github.com/akkadotnet/akka.net

The .net port is independent from Akka "jvm"

**Comment by HenryTonnison** [comment]
Yep sorry.
