### ISSUE TITLE
Failed: RemoteReDeploymentSlowMultiJvm

### ISSUE THREAD

**Issue by chbatey** [akka/akka#23838]
See https://jenkins.akka.io:8498/job/akka-multi-node/2358/consoleFull

```
[JVM-2] - must terminate the child when its parent system is replaced by a new one (on node 'second', class akka.remote.RemoteReDeploymentSlowMultiJvmNode2) *** FAILED *** (25 seconds, 593 milliseconds)
[JVM-2]   java.lang.AssertionError: assertion failed: timeout (15 seconds) during expectMsg while waiting for HelloParent
[JVM-2]   at scala.Predef$.assert(Predef.scala:170)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:401)
[JVM-2]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:387)
[JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:882)
[JVM-2]   at akka.remote.RemoteReDeploymentMultiJvmSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(RemoteReDeploymentSpec.scala:174)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:355)
```

**Comment by chbatey** [comment]
Again: 

https://jenkins.akka.io:8498/job/akka-nightly/4898/consoleFull

**Comment by chbatey** [comment]
This hasn't happened sixe https://github.com/akka/akka/pull/23867 was merged.

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5015/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5101/consoleFull

**Comment by chbatey** [comment]
This looks to have uncovered a bug:

```
[JVM-1] java.lang.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [0 {0}] ack: ACK[1, {}]                                                                                                     
[JVM-1]         at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:304)                                                                                                                                   
[JVM-1]         at akka.actor.Actor$class.aroundReceive(Actor.scala:517)                                                                                                                                                                       
[JVM-1]         at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:203)                                                                                                                                                    
[JVM-1]         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)                                                                                                                                                                    
[JVM-1]         at akka.actor.ActorCell.invoke(ActorCell.scala:496)                                                                                                                                                                            
[JVM-1]         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)                                                                                                                                                                     
[JVM-1]         at akka.dispatch.Mailbox.run(Mailbox.scala:224)                                                                                                                                                                                
[JVM-1]         at akka.dispatch.Mailbox.exec(Mailbox.scala:234)                                                                                                                                                                               
[JVM-1]         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                                                                                                                                           
[JVM-1]         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                                                                                                                                               
[JVM-1]         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                                                                                                                                       
[JVM-1]         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)                                                                                                                                              
[JVM-1] Caused by: java.lang.IllegalArgumentException: Highest SEQ so far was 0 but cumulative ACK is 1                                                                                                                                        
[JVM-1]         at akka.remote.AckedSendBuffer.acknowledge(AckedDelivery.scala:103)                                                                                                                                                            
[JVM-1]         at akka.remote.ReliableDeliverySupervisor$$anonfun$receive$1.applyOrElse(Endpoint.scala:300)                                                                                                                                   
[JVM-1]         ... 11 more                                                                                                                                                                                                                    
[JVM-1]      
```

**Comment by johanandren** [comment]
Failed on the 2.4 release branch:
https://jenkins.akka.io:8498/job/akka-release-2.4/564/consoleFull

**Comment by patriknw** [comment]
I looked at the log from https://jenkins.akka.io:8498/job/akka-nightly/5101/consoleFull
* The test consist of two nodes first and second.
* Actor `parent` is started on second, and that creates a remote child on `first`, i.e. some system messages exchanged.
* blackhole and shutdown second (parent) node
* FD on first => quarantine as expected on first
* start second again with same port
* DeathWatchNotification is sent from first to second, and it is received on second
* something weird with the communication, not all messages get through, and things I don't understand
* "IllegalArgumentException: Highest SEQ so far was 0 but cumulative ACK is 1" on first, which could be the Ack from the DeathWatchNotification
* but the DeathWatchNotification was never intended for the new incarnation of second, so that seqnr is probably not in the AckedSendBuffer when the Ack arrives

Unfortunately I think this is just another symptom of the many race conditions in classic remoting. I don't see what we can do without major rewrite, which is already done in Artery.

**Comment by patriknw** [comment]
obsolete, classic remoting
