### ISSUE TITLE
NoClassDefFoundError: XmlRootElement

### ISSUE THREAD

**Issue by raboof** [akka/akka#23904]
Somewhere deep inside camel there is a reference to the `XmlRootElement` annotation, which is no longer loaded by default. It's probably in the `java.xml.bind` module (haven't checked).

We should probably just load the `java.xml.bind` jre module when testing the `akka-camel` akka module.
```
Uncaught error from thread [NonSharedCamelSystem-akka.actor.default-dispatcher-2]: javax/xml/bind/annotation/XmlRootElement, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[NonSharedCamelSystem]
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
	at org.apache.camel.model.OptionalIdentifiedDefinition.getShortName(OptionalIdentifiedDefinition.java:79)
	at org.apache.camel.impl.DefaultNodeIdFactory.createId(DefaultNodeIdFactory.java:36)
	at org.apache.camel.model.OptionalIdentifiedDefinition.idOrCreate(OptionalIdentifiedDefinition.java:158)
	at org.apache.camel.model.ProcessorDefinition.createOutputsProcessorImpl(ProcessorDefinition.java:455)
	at org.apache.camel.model.ProcessorDefinition.createOutputsProcessor(ProcessorDefinition.java:418)
	at org.apache.camel.model.ProcessorDefinition.createOutputsProcessor(ProcessorDefinition.java:165)
	at org.apache.camel.model.OnExceptionDefinition.addRoutes(OnExceptionDefinition.java:198)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1069)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:196)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:974)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:3301)
	at org.apache.camel.impl.DefaultCamelContext.addRouteDefinitions(DefaultCamelContext.java:908)
	at org.apache.camel.builder.RouteBuilder.populateRoutes(RouteBuilder.java:418)
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:331)
	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:835)
	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:832)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:2873)
	at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:832)
	at akka.camel.internal.ConsumerRegistrar$$anonfun$receive$4.applyOrElse(CamelSupervisor.scala:200)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)

```

**Comment by raboof** [comment]
Indeed loading that module just for that test run seems to work out.

**Comment by leeoandradee** [comment]
Did you get to solve it? I am with the same problem!

**Comment by ktoso** [comment]
It's a JDK9 issue, not really anything about Akka itself.
See solution: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

Without getting all modularised the workaround is to pass `--add-modules java.xml.bind`
