### ISSUE TITLE
VirtualPublisher throws IllegalStateException

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#23933]
Happened in akka-http test code on Akka 2.4.19

```
[ERROR] [11/06/2017 18:08:19.064] [HostConnectionPoolSpec-akka.actor.default-dispatcher-10] [akka://HostConnectionPoolSpec/user/StreamSupervisor-0/flow-122-0-unknown-operation] Error in stage [akka.http.impl.engine.client.PoolSlot$SlotProcessor@7ce4e7bf]: internal error
java.lang.IllegalStateException: internal error
	at akka.stream.impl.VirtualPublisher.registerPublisher(StreamLayout.scala:832)
	at akka.stream.impl.MaterializerSession.akka$stream$impl$MaterializerSession$$doSubscribe(StreamLayout.scala:1034)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3$$anonfun$apply$3.apply(StreamLayout.scala:925)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3$$anonfun$apply$3.apply(StreamLayout.scala:924)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3.apply(StreamLayout.scala:924)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3.apply(StreamLayout.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:924)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:256)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:152)
	at akka.stream.impl.SubFusingActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:272)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1.establishConnectionFlow$1(PoolSlot.scala:188)
	at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1.onPush(PoolSlot.scala:204)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraph
```

**Comment by ktoso** [comment]
Will look into it

**Comment by ktoso** [comment]
Hmm this was on 2.4.19 I guess, I propose to add some more debugging info there I guess but don't see how it could have happened hmmm

**Comment by ktoso** [comment]
Hm wait...

**Comment by ktoso** [comment]
The code path seems to be during failing materialization:

```
case NonFatal(cause) ⇒
        // PANIC!!! THE END OF THE MATERIALIZATION IS NEAR!
        // Cancels all intermediate Publishers and fails all intermediate Subscribers.
        // (This is an attempt to clean up after an exception during materialization)
        val errorPublisher = new ErrorPublisher(new MaterializationPanic(cause), "")
        for (subMap ← subscribersStack; sub ← subMap.asScala.valuesIterator) <<<
```

And the issue is when something was materialized I guess, but then the failure happened so this tried to set a publisher (with the error publisher) again, which is illegal. Since this is during failing to materialize I'd say "bets are off" and this exception is "fine" since things are going super bad already.

I'll improve the logging of that but propose not investigating more, since it's the old materializer infrastructure and this codepath does not exist in the new infra. WDYT?

**Comment by hepin1989** [comment]
@johanandren This one could be closed now.

**Comment by johanandren** [comment]
Hmm, I think the PR just changed to a better error, it didn't fix the potential bug.

**Comment by hepin1989** [comment]
@johanandren Hum...

**Comment by johanandren** [comment]
No new case for a long while, let's close this and re-open if it is seen again.
