### ISSUE TITLE
AbstractPersistentFSMTest: testSuccessfulRecoveryWithCorrectStateData

### ISSUE THREAD

**Issue by raboof** [akka/akka#23955]
https://jenkins.akka.io:8498/job/akka-multi-node/2393/consoleFull:
```
[info] - testSuccessfulRecoveryWithCorrectStateData *** FAILED ***
[info]   java.lang.AssertionError:
[info]   at org.junit.Assert.fail(Assert.java:86)
[info]   at org.junit.Assert.assertTrue(Assert.java:41)
[info]   at org.junit.Assert.assertTrue(Assert.java:52)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$3.<init>(AbstractPersistentFSMTest.java:162)
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest.testSuccessfulRecoveryWithCorrectStateData(AbstractPersistentFSMTest.java:141)
```

**Comment by chbatey** [comment]
I didn't even know we had a persistent FSM :) This is odd as it is not even in the recovery, it is the shopping cart from the initial state that should be empty. Not a very helpful failure message.
