### ISSUE TITLE
FAILED: FsmTimingSpec

### ISSUE THREAD

**Issue by raboof** [akka/akka#23961]
Timed out waiting for a timeout... this spec failed before but a long time ago (#15972, #18071) so probably unrelated

https://jenkins.akka.io:8498/job/akka-nightly/4942/consoleFull
```
[info] - must receive StateTimeout *** FAILED *** (1 second, 4 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (800872656 nanoseconds) during expectMsg while waiting for Transition(Actor[akka://FSMTimingSpec/user/$a#-2090606703],TestStateTimeout,Initial)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:401)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:378)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:882)
[info]   at akka.actor.FSMTimingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$11.apply(FSMTimingSpec.scala:30)
[info]   at akka.actor.FSMTimingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$11.apply(FSMTimingSpec.scala:28)
```

**Comment by ktoso** [comment]
Looking
