### ISSUE TITLE
Failed: Typed ClusterShardingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#23993]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10713/testReport/junit/akka.typed.cluster.sharding/ClusterShardingSpec/Typed_cluster_sharding_03_must_send_messsages_via_cluster_sharding__without_envelopes/

```
[WARN] [SECURITY][11/14/2017 15:57:56.008] [ClusterShardingSpec-akka.remote.default-remote-dispatcher-12] [akka.serialization.Serialization(akka://ClusterShardingSpec)] Multiple serializers found for class akka.typed.cluster.sharding.ClusterShardingSpec$IdReplyPlz, choosing first: Vector((interface java.io.Serializable,DisabledJavaSerializer(akka://ClusterShardingSpec)), (interface akka.typed.cluster.sharding.ClusterShardingSpec$IdTestProtocol,akka.typed.cluster.sharding.ClusterShardingSpec$Serializer@10e9076d))
[WARN] [SECURITY][11/14/2017 15:57:56.008] [ClusterShardingSpec-akka.remote.default-remote-dispatcher-12] [DisabledJavaSerializer(akka://ClusterShardingSpec)] Outgoing message attempted to use Java Serialization even though `akka.actor.allow-java-serialization = off` was set! Message type was: [class akka.typed.cluster.sharding.ClusterShardingSpec$IdReplyPlz]
[ERROR] [11/14/2017 15:57:56.009] [ClusterShardingSpec-akka.remote.default-remote-dispatcher-12] [Encoder(akka://ClusterShardingSpec)] Failed to serialize message [akka.typed.cluster.sharding.ClusterShardingSpec$IdReplyPlz]. (akka.serialization.DisabledJavaSerializer$JavaSerializationException: Attempted to serialize message using Java serialization while `akka.actor.allow-java-serialization` was disabled. Check WARNING logs for more details.)
[info] - 03 must send messsages via cluster sharding, without envelopes *** FAILED *** (3 seconds, 15 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for Hello!
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.typed.testkit.scaladsl.TestProbe.expectMsg_internal(TestProbe.scala:177)
[info]   at akka.typed.testkit.scaladsl.TestProbe.expectMsg(TestProbe.scala:163)
[info]   at akka.typed.cluster.sharding.ClusterShardingSpec$Typed$u0020cluster$u0020sharding$.03$u0020must$u0020send$u0020messsages$u0020via$u0020cluster$u0020sharding$u002C$u0020without$u0020envelopes(ClusterShardingSpec.scala:224)
```

**Comment by patriknw** [comment]
That must be after the merge of https://github.com/akka/akka/pull/23776
Strange because that PR was validated before merging.

**Comment by jrudolph** [comment]
Another one here: https://jenkins.akka.io:8498/job/akka-multi-node/2412
