### ISSUE TITLE
Failed: RestartSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24075]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/914/consoleFull

```
[info] - should restart on completion *** FAILED *** (12 seconds, 31 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 10 seconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:325)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
[info]   at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$17.apply(RestartSpec.scala:444)
[info]   at akka.stream.scaladsl.RestartSpec$$anonfun$3$$anonfun$apply$mcV$sp$17.apply(RestartSpec.scala:431)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5019/
