### ISSUE TITLE
DistributedPubSubRestart

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24100]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/409/consoleFull

```
[JVM-3] - must handle restart of nodes with same address (on node 'third', class akka.cluster.pubsub.DistributedPubSubRestartMultiJvmNode3) *** FAILED ***
[JVM-3]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[JVM-3]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:183)
[JVM-3]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:169)
[JVM-3]   at scala.concurrent.Await$$$Lambda$870/1880078449.apply(Unknown Source)
[JVM-3]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[JVM-3]   at scala.concurrent.Await$.ready(package.scala:123)
[JVM-3]   at akka.cluster.pubsub.DistributedPubSubRestartSpec.$anonfun$new$11(DistributedPubSubRestartSpec.scala:166)
[JVM-3]   at akka.cluster.pubsub.DistributedPubSubRestartSpec$$Lambda$759/2038522556.apply$mcV$sp(Unknown Source)
[JVM-3]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:369)
[JVM-3]   at akka.cluster.pubsub.DistributedPubSubRestartSpec.$anonfun$new$5(DistributedPubSubRestartSpec.scala:139)
[JVM-3]   ...
[J
```

**Comment by patriknw** [comment]
I noticed a slightly different failure in this test:
```
[JVM-1] - must handle restart of nodes with same address (on node 'first', class akka.cluster.pubsub.DistributedPubSubRestartMultiJvmNode1) *** FAILED ***
[JVM-1]   java.lang.AssertionError: assertion failed: expected long, found class akka.actor.ActorIdentity (ActorIdentity(None,Some(Actor[akka://DistributedPubSubRestartSpec@localhost:42433/user/shutdown#1174471491])))
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:481)
[JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:890)
[JVM-1]   at akka.cluster.pubsub.DistributedPubSubRestartSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4$$anonfun$apply$mcV$sp$7.apply$mcV$sp(DistributedPubSubRestartSpec.scala:135)
```
