### ISSUE TITLE
failed: CoordinatedShutdownShardingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24113]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10922

```
[info] - must run coordinated shutdown when leaving *** FAILED *** (11 seconds, 816 milliseconds)
[info]   3 did not equal 2 (CoordinatedShutdownShardingSpec.scala:118)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$7$$anonfun$apply$8.apply(CoordinatedShutdownShardingSpec.scala:118)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$7$$anonfun$apply$8.apply(CoordinatedShutdownShardingSpec.scala:117)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:311)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:328)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:882)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$7.apply(CoordinatedShutdownShardingSpec.scala:117)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$7.apply(CoordinatedShutdownShardingSpec.scala:117)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:359)
[info]   at akka.testkit.TestKit.within(TestKit.scala:882)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:373)
[info]   at akka.testkit.TestKit.within(TestKit.scala:882)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(CoordinatedShutdownShardingSpec.scala:116)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(CoordinatedShutdownShardingSpec.scala:112)
[info]   at akka.cluster.sharding.CoordinatedShutdownShardingSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(CoordinatedShutdownShardingSpec.scala:112)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2457/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5030/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_leaving/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5537/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_leaving/
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/928/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5540/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/10991/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11001/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11002/testReport/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1033/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_downing/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11005/

**Comment by patriknw** [comment]
Temporary fix of the test in https://github.com/akka/akka/pull/24163

The real issue that should be fixed is that there seems to be a race between the CS and the ClusterSingleton observing OldestChanged and terminating coordinator singleton before the graceful sharding stop is done

```
[INFO] [12/14/2017 17:44:35.254] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://CoordinatedShutdownShardingSpec)] Cluster Node [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:44715] - Marked address [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629] as [Leaving]
[INFO] [12/14/2017 17:44:37.093] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://CoordinatedShutdownShardingSpec)] Cluster Node [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545] - Leader is moving node [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629] to [Exiting]
[INFO] [12/14/2017 17:44:37.102] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://CoordinatedShutdownShardingSpec)] Cluster Node [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629] - Exiting, starting coordinated shutdown
[INFO] [12/14/2017 17:44:37.108] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-4] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545/system/sharding/type1Coordinator] Younger observed OldestChanged: [Some(akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629) -> myself]
[INFO] [12/14/2017 17:44:37.110] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-4] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545/system/sharding/type1Coordinator] ClusterSingletonManager state change [Younger -> BecomingOldest]
[INFO] [12/14/2017 17:44:37.194] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-22] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629/system/sharding/type1Coordinator] ClusterSingletonManager state change [Oldest -> HandingOver]
[INFO] [12/14/2017 17:44:37.210] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-6] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545/system/sharding/type1Coordinator] Hand-over in progress at [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629]
[INFO] [12/14/2017 17:44:37.249] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-2] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629/system/sharding/type1Coordinator] Singleton terminated, hand-over done [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629 -> Some(akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545)]
[INFO] [12/14/2017 17:44:37.251] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-2] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:45629/system/sharding/type1Coordinator] ClusterSingletonManager state change [HandingOver -> End]
[INFO] [12/14/2017 17:44:37.265] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-6] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545/system/sharding/type1Coordinator] Singleton manager starting singleton actor [akka://CoordinatedShutdownShardingSpec/system/sharding/type1Coordinator/singleton]
[INFO] [12/14/2017 17:44:37.266] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-6] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:35545/system/sharding/type1Coordinator] ClusterSingletonManager state change [BecomingOldest -> Oldest]
[WARN] [12/14/2017 17:44:37.268] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-2] [akka://CoordinatedShutdownShardingSpec/system/sharding/type1Coordinator/singleton/coordinator] received dead letter from Actor[akka://CoordinatedShutdownShardingSpec/system/sharding/type1#-913564370]: GracefulShutdownReq(Actor[akka://CoordinatedShutdownShardingSpec/system/sharding/type1#-913564370])
```

**Comment by ktoso** [comment]
Workaround fixed in https://github.com/akka/akka/pull/24163
Still need to resolve real issue

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5556/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1042/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11049/console

**Comment by patriknw** [comment]
seems to be failing all the time, could someone mark it as ignored?

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/429/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5077/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5086/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5088/

**Comment by chbatey** [comment]
The latest failure (5088) seems different. It is in the first test (second one fails as well) where the node leaving does not contain the shard coordinator.

The coordinator deallocates the shard on that node and sees that ShardRegion as terminated:

```
[DEBUG] [12/28/2017 04:41:06.408] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-3] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1Coordinator/singleton/coordinator] Rebalance shard [2]     done [true]   
[DEBUG] [12/28/2017 04:41:06.432] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-15] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1Coordinator/singleton/coordinator] Shard [2] deallocated    
[DEBUG] [12/28/2017 04:41:06.439] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-15] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1Coordinator/singleton/coordinator] ShardRegion termin    ated: [Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:46025/system/sharding/type1#158783699]]  
```

We do get a dead letter in distributed data:

```
[WARN] [12/28/2017 04:41:06.474] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-19] [akka://CoordinatedShutdownShardingSpec/system/sharding/replicator] received dead letter from Actor[akka.tcp://CoordinatedShutdownShard    ingSpec@127.0.1.1:39561/system/sharding/replicator/$h#325585805]: Write(type1CoordinatorState,DataEnvelope(LWWRegister(State(Map(1 -> Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1#-1108675086],     3 -> Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/type1#-1956609611]),Map(Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1#-1108675086] -> Vector(1), Actor[akka.    tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/type1#-1956609611] -> Vector(3)),Set(),Set(),false)),Map(),VersionVector()))
```

Then when we try to ping all the entities after the node is removed we don't get a response for shard 2 home (was on the removed node)

```
[DEBUG] [12/28/2017 04:41:08.351] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-3] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/type1] Request shard [2] home                                  
[DEBUG] [12/28/2017 04:41:09.267] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-14] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/replicator] Received gossip status from [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901], chunk [1] of [1] containing [type1CoordinatorState]                                                                                                                                                    
[DEBUG] [12/28/2017 04:41:09.272] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-3] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/replicator] Received gossip status from [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561], chunk [1] of [1] containing [type1CoordinatorState]                                                                                                                                                     
[DEBUG] [12/28/2017 04:41:09.275] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-2] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/type1] Retry request for shard [2] homes from coordinator at [Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1Coordinator/singleton/coordinator#-2142613461]]. [1] buffered messages.                                                                                   
[DEBUG] [12/28/2017 04:41:11.266] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-17] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/replicator] Received gossip status from [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901], chunk [1] of [1] containing [type1CoordinatorState]                                                                                                                                                    
[DEBUG] [12/28/2017 04:41:11.271] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-20] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/replicator] Received gossip status from [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561], chunk [1] of [1] containing [type1CoordinatorState]                                                                                                                                                    
[DEBUG] [12/28/2017 04:41:11.274] [CoordinatedShutdownShardingSpec-akka.actor.default-dispatcher-20] [akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:42901/system/sharding/type1] Retry request for shard [2] homes from coordinator at [Actor[akka.tcp://CoordinatedShutdownShardingSpec@127.0.1.1:39561/system/sharding/type1Coordinator/singleton/coordinator#-2142613461]]. [1] buffered messages.                                                                                  
[info] - must run coordinated shutdown when leaving *** FAILED *** (5 seconds, 939 milliseconds)                                                                                                                                               
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for                                                                                                                                   
[info]   at scala.Predef$.assert(Predef.scala:170)                                                                                                                                                                                             

```


Probably worth someone who knows the internals of cluster/sharding to take another look before ignoring this test as it now has debug logging on

**Comment by jrudolph** [comment]
More failures:

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/949/
https://jenkins.akka.io:8498/job/akka-nightly/5104/
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5601/
https://jenkins.akka.io:8498/job/akka-nightly/5106/

**Comment by chbatey** [comment]
There is a bug here (I think) and it depends on where the shards land. Will take this over for today

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/440/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_leaving/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11208/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_downing/

**Comment by patriknw** [comment]
Nope, this is not fixed yet. We have fixed some related things, but not https://github.com/akka/akka/issues/24113#issuecomment-351956970

**Comment by ktoso** [comment]
I see, 2.5.10 then 👍

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11244/testReport/junit/akka.cluster.sharding/CoordinatedShutdownShardingSpec/Sharding_and_CoordinatedShutdown_must_run_coordinated_shutdown_when_leaving/

**Comment by hepin1989** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14411/
