### ISSUE TITLE
Akka Typed Cluster Singleton fails for Akka Typed PersistentActors

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24112]
Trying to run a persistent actor as a cluster singleton fails with an exception.

This is how I create the actors:

``` scala
def spawnSingleton(system: ActorSystem[Nothing]): ActorRef[Command] =
  ClusterSingleton(system)
    .spawn(
      UserRepository(),
      UserRepository.Name,
      Props.empty,
      ClusterSingletonSettings(system),
      UserRepository.Stop
    )

def apply(): Behavior[Command] =
  PersistentActor.persistentEntity(_ => Name, State(), commandHandler, eventHandler)
  //PersistentActor.immutable(Name, State(), commandHandler, eventHandler)
```

This is the exception which is thrown when the first message is sent to the singleton:

```
whirlwind-tour-akka-typed 16:47:28 ERROR OneForOneStrategy [akka://wtat/system/singletonManageruser-repository/user-repository] - cannot wrap behavior [akka.typed.persistence.scaladsl.PersistentBehavior@5d3c189f] in Actor.deferred, Actor.supervise or similar
whirlwind-tour-akka-typed java.lang.IllegalArgumentException: cannot wrap behavior [akka.typed.persistence.scaladsl.PersistentBehavior@5d3c189f] in Actor.deferred, Actor.supervise or similar
whirlwind-tour-akka-typed 	at akka.typed.Behavior$.interpret(Behavior.scala:285) ~[akka-typed_2.12-2.5.7.jar:2.5.7]
whirlwind-tour-akka-typed 	at akka.typed.Behavior$.interpretMessage(Behavior.scala:270) ~[akka-typed_2.12-2.5.7.jar:2.5.7]
whirlwind-tour-akka-typed 	at akka.typed.internal.adapter.ActorAdapter$$anonfun$receive$1.applyOrElse(ActorAdapter.scala:39) ~[akka-typed_2.12-2.5.7.jar:2.5.7]
whirlwind-tour-akka-typed 	at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:15) ~[akka-typed_2.12-2.5.7.jar:2.5.7]
whirlwind-tour-akka-typed 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.12-2.5.7.jar:?]
whirlwind-tour-akka-typed 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.12-2.5.7.jar:?]
```

**Comment by chbatey** [comment]
@hseeberger which version are you running this with? 2.5.7?

**Comment by patriknw** [comment]
It's because of the special impl of PersistentBehavior. Missing special case in AdaptedClusterSingletonImpl. Should be similar to https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/cluster/sharding/ClusterSharding.scala#L232-L235

**Comment by hseeberger** [comment]
Sounds not too hard. Hoping you can fix this soon, because I need this working for my Scala Exchange workshop  😬

**Comment by patriknw** [comment]
I'd recommend using sharding.

Fastest way to get things done is to contribute, as you know ;-)

**Comment by hseeberger** [comment]
> I'd recommend using sharding.

That would be a nice workaround, but I would like to teach "the right things".

> Fastest way to get things done is to contribute, as you know ;-)

Somehow I know you would be saying something like this ... ;-)

**Comment by patriknw** [comment]
Sharding is the right thing with persistence. Not often one want a single or a handful of persistent actors. Anyway, I guess you want to teach it step-by-step.

Should be a simple fix.

**Comment by hseeberger** [comment]
Are you saying that there is no use case for a persistent cluster singleton?

I would argue that many singletons need to be persistent. E.g. the ShardCoordinator (before DD).

**Comment by patriknw** [comment]
Ok, that kind could be a good example

**Comment by patriknw** [comment]
@hseeberger I have fixed this, so that can be included in today's release. See https://github.com/akka/akka/pull/24114

**Comment by hseeberger** [comment]
@patriknw awesome! Thanks!
