### ISSUE TITLE
Failed: OptionalSnapshotStoreSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24144]
https://jenkins.akka.io:8498/job/akka-nightly/5040/testReport/junit/akka.persistence/OptionalSnapshotStoreSpec/Persistence_extension_must_initialize_properly_even_in_absence_of_configured_snapshot_store/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.event.Logging$Warning
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:508)
	at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:481)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
	at akka.persistence.OptionalSnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(OptionalSnapshotStoreSpec.scala:52)
	at akka.persistence.OptionalSnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(OptionalSnapshotStoreSpec.scala:49)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5057/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5079/testReport/junit/akka.persistence/OptionalSnapshotStoreSpec/Persistence_extension_must_initialize_properly_even_in_absence_of_configured_snapshot_store/

**Comment by ktoso** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5619/testReport/junit/akka.persistence/OptionalSnapshotStoreSpec/Persistence_extension_must_initialize_properly_even_in_absence_of_configured_snapshot_store/
