### ISSUE TITLE
Failed: LargeMessagesStreamSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24143]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/415/testReport/junit/akka.remote.artery/LargeMessagesStreamSpec/The_large_message_support_should_not_affect_regular_communication/

```
sbt.ForkMain$ForkError: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://LargeMessagesStreamSpec-remote-0@localhost:57180/), Path(/user/regular)]
	at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:70)
	at akka.actor.ActorSelection$$Lambda$1680/362979419.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:78)
	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:120)
	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:114)

```

**Comment by johanandren** [comment]
Note the weirdness that Patrik pointed out in the full logs after the stack trace pasted here, also some details in that closed PR

**Comment by johanandren** [comment]
Possibly related: https://github.com/scalatest/scalatest/issues/770

**Comment by jrudolph** [comment]
Didn't fail for a long time. Closing...

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/574/testReport/akka.remote.artery/LargeMessagesStreamSpec/The_large_message_support_should_allow_for_normal_communication_while_simultaneously_sending_large_messages/

```
Error Message
akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://LargeMessagesStreamSpec-remote-2@localhost:55694/), Path(/user/large)]
Stacktrace
sbt.ForkMain$ForkError: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://LargeMessagesStreamSpec-remote-2@localhost:55694/), Path(/user/large)]
	at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:74)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:74)
	at akka.dispatch.internal.SameThreadExecutionContext$$anon$1.unbatchedExecute(SameThreadExecutionContext.scala:21)
	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:123)
	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:117)
	at akka.dispatch.internal.SameThreadExecutionContext$$anon$1.execute(SameThreadExecutionContext.scala:20)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:72)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:89)
	at akka.remote.artery.LargeMessagesStreamSpec.awaitResolve(LargeMessagesStreamSpec.scala:128)
	at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$new$6(LargeMessagesStreamSpec.scala:101)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.remote.artery.ArteryMultiNodeSpec.withFixture(ArteryMultiNodeSpec.scala:48)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by johanandren** [comment]
Still no clue what is going on here. I think the Scalatest serialization is a red herring though, an actor ref caught in a exception stacktrace being serialized or something like that.

Since it happens so seldom, could it be UDP package loss (unlikely on loopback but perhaps possible?)

**Comment by patriknw** [comment]
> Since it happens so seldom, could it be UDP package loss (unlikely on loopback but perhaps possible?)

Aeron doesn't have package loss.

**Comment by johanandren** [comment]
Good! That turns one flimsy idea of what is going on to zero though :D

**Comment by raboof** [comment]
Saw it again in https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/802/testReport/junit/akka.remote.artery/LargeMessagesStreamSpec/The_large_message_support_should_pass_small_regular_messages_over_the_large_message_stream/

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/4293643023?check_suite_focus=true
