### ISSUE TITLE
AKKA HTTP giving Exceptio  --- Caused by: java.net.SocketException: Connection reset 

### ISSUE THREAD

**Issue by Bishnup1995** [akka/akka#24154]
After sending 8k request i am getting this error:

` (Thread-6157) java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
        at sun.reflect.GeneratedConstructorAccessor4.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:359)
        at scalaj.http.HttpRequest.exec(Http.scala:335)
        at scalaj.http.HttpRequest.asString(Http.scala:455)
        at Test.RequestSender1$$anonfun$main$1$$anonfun$apply$mcVI$sp$1$$anon$1.run(RequestSender.scala:23)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
        at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:357)
        at scalaj.http.HttpRequest.exec(Http.scala:335)
        at scalaj.http.HttpRequest.asString(Http.scala:455)
        at Test.RequestSender1$$anonfun$main$1$$anonfun$apply$mcVI$sp$1$$anon$1.run(RequestSender.scala:23)`

Anyone Help me out with this .
 My Serevr code is 👍 

`object Collection {
  case class calculate(values:Double)
 }
 object EngineController{
 import Collection._
def main(args: Array[String]): Unit = {
try {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  implicit val executionContext = system.dispatcher
val requestHandler = system.actorOf(RoundRobinPool(3).props(RequestHandler.props), "round-robin-pool")
  val route: Route = {
    implicit val timeout = Timeout(100.seconds)
    path("aggregate") {
      log.info("REQUEST RECEIVED")
      post {
        entity(as[String]) { values =>
          onSuccess(requestHandler ? calculate(values)) {
            case result: Double =>
              log.info("Response Sent -" + result)
              complete(s"${result}")
          }
        }
      }
    } 
  }
  val routeBinding :Future[ServerBinding] = Http().bindAndHandle(route, "localhost", 8080)
  log.info("Connection Established! Waiting for Request")
  routeBinding.failed.foreach { ex =>
    log.error(ex, "Failed to bind to {}:{}!", host, port)
  }
  StdIn.readLine()
  routeBinding.flatMap(_.unbind())
  system.terminate()
}
catch {
  case ex: Exception =>
    log.error(ex, ex)
}
}
}`
> Request Handler Code 👍 
`object RequestHandler extends App {
def props: Props = {
Props(classOf[RequestHandler])
  }
class RequestHandler extends Actor {
var doubleArray: Array[Double] = Array.empty
val system1 = ActorSystem("system2")
var routees: List[ActorRef] = _
override def preStart() = {
routees = List.fill(5)(
context.actorOf(AggregateCalculator.props)
)
}
val aggregateActor = system1.actorOf(AggregateCalculator.props.withRouter(RandomPool(100)), "ag")
 //CONVERT STRING TO ARRAY
 def stringToArray(values: String): Array[Double] = {
 return values.split(",").map(x => x.toDouble)
 }
 override def receive: Receive = {
 case calculate(values) =>
 doubleArray = stringToArray(values)
 sender() ! doubleArray.max
   }
  }
 }`

> Client Code 👍
 `import scalaj.http.{Http, HttpResponse}
 import org.apache.log4j.Logger
 //libraryDependencies += "org.scalaj" % "scalaj-http_2.11" % "2.3.0"
 object RequestSender1 {
val log = Logger.getLogger(getClass.getName)
def main(args: Array[String]): Unit = {
try {
  val str = "22.78, -1.23, 50, 60, 3, 32, 11, 54, 72, 78, 99, 70, 19, 47, 90, 81, 50, 69, 69, 72, 83, 14.7, 8, 41, 65, 73, 48, 63, 47, 17, 55, 39, 50, 87, 76, 8, 67, 51, 55, 94, 75, 14, 91, 35, 87, 36, 42, 74, 70, 81, 18, 14, 50, 22, 16, 55, 71, 17, 39, 44, 58, 61, 16, 4, 74, 61, 37, 31, 62, 36, 53, 30, 82, 72, 89, 96, 28, 36, 77, 89, 30, 2, 31, 79, 50, 34, 81, 39, 91, 85, 94, 25, 68, 98, 46, 42,14,14"
  var result: HttpResponse[String] = null
  var counter = 0
  for (i <- 1 to 300) {
    for (i <- 1 to 13000) {
      val thread = new Thread {
        override def run {
          while (counter < 1000024) {
            try {
              counter += 1
              result = scalaj.http.Http("http://localhost:8080/aggregate").postData(str).timeout(1200000, 120000000) //192.168.0.157:8089
                .header("Content-Type", "text/plain").asString
              println("Thread Count----" + java.lang.Thread.activeCount())
              j += 1
              println(result.body + "   " + j)
            } catch {
              case ex:Exception =>
                log.error(ex)
            }
          }
        }
      }
      thread.start
      // slow the loop down a bit
    }
    println("Sent request with --" + i)
    Thread.sleep(1)
    // slow the loop down a bit
 }
}
catch {
  case ex:Exception =>
    println("Exception"+">>>>>>>>>>")
}`

**Comment by jrudolph** [comment]
This is the wrong project. You seem to be using scalaj/scalaj-http not Akka Http. Please report errors over there.

**Comment by Bishnup1995** [comment]
@jrudolph  i am using scalaj client. I am getting in my akka http server side. If i am sending request to my akka http server by akka client or any other client like an okHttpClient, i  am getting the same error. Don't care about the client program. Focus on my server Program.

**Comment by jrudolph** [comment]
Ah, sorry, didn't see that (in github you can use triple backquotes ``` to syntax highlight longer code blocks btw which helps with readability). The exception just says that the connection breaks. That could have all kind of causes. If this is reproducible, please provide a self-contained example project which shows the broken behavior and open another case at https://github.com/akka/akka-http.

**Comment by Bishnup1995** [comment]
@jrudolph  ok i will again create a new issue with the code and project .

**Comment by Bishnup1995** [comment]
@jrudolph I have raised a new issue. Check it here [https://github.com/akka/akka/issues/24161](url)

**Comment by jrudolph** [comment]
Wrong project ;) It should be in the *akka-http* project.
