### ISSUE TITLE
MultiDcSplitBrainSpec

### ISSUE THREAD

**Issue by raboof** [akka/akka#24175]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5553/consoleFull
```
must be able to have data center member leave while there is inter data center split (on node 'third', class akka.cluster.MultiDcSplitBrainMultiJvmNode3) *** FAILED *** (497 milliseconds)
[JVM-3]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$UnreachableDataCenter, found class akka.cluster.ClusterEvent$ReachableDataCenter (ReachableDataCenter(dc1))
[JVM-3]   at scala.Predef$.assert(Predef.scala:170)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[JVM-3]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:490)
[JVM-3]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:882)
[JVM-3]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$splitDataCenters$3.apply$mcV$sp(MultiDcSplitBrainSpec.scala:93)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/2487/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/441/consoleFull

**Comment by chbatey** [comment]
Running this with some extra logging on repeat

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/457/consoleFull

**Comment by patriknw** [comment]
```
[JVM-1] - must be able to have data center member leave while there is inter data center split (on node 'first', class akka.cluster.MultiDcSplitBrainMultiJvmNode1) *** FAILED *** (470 milliseconds)
[JVM-1]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$UnreachableDataCenter, found class akka.cluster.ClusterEvent$ReachableDataCenter (ReachableDataCenter(dc2))
[JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:490)
[JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:890)
[JVM-1]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$splitDataCenters$3.apply$mcV$sp(MultiDcSplitBrainSpec.scala:93)
[JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:369)
[JVM-1]   at akka.cluster.MultiDcSplitBrainSpec.splitDataCenters(MultiDcSplitBrainSpec.scala:92)
[JVM-1]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply$mcV$sp(MultiDcSplitBrainSpec.scala:179)
[JVM-1]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(MultiDcSplitBrainSpec.scala:178)
[JVM-1]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(MultiDcSplitBrainSpec.scala:178)
```

https://jenkins.akka.io:8498/job/akka-multi-node-repeat/18181
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/18167

**Comment by chbatey** [comment]
This test has failed once before for another reason but we can open a new issue if that happens again
