### ISSUE TITLE
FAILED: akka.remote.ArteryRemoteDeploymentDeathWatchFast / RemoteDeploymentDeathWatchSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#24224]
```
[JVM-2] - must be able to shutdown when remote node crash (on node 'second', class akka.remote.ArteryRemoteDeploymentDeathWatchFastMultiJvmNode2) *** FAILED *** (14 seconds, 986 milliseconds)
[JVM-2]   java.util.concurrent.TimeoutException: Client timed out while waiting for barrier third-crashed
[JVM-2]   at akka.remote.testconductor.Player$$anonfun$enter$1.apply(Player.scala:111)
[JVM-2]   at akka.remote.testconductor.Player$$anonfun$enter$1.apply(Player.scala:98)
[JVM-2]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[JVM-2]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[JVM-2]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[JVM-2]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[JVM-2]   at akka.remote.testconductor.Player$class.enter(Player.scala:98)
[JVM-2]   at akka.remote.testconductor.TestConductorExt.enter(Extension.scala:52)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.enterBarrier(MultiNodeSpec.scala:383)
[JVM-2]   at akka.remote.RemoteDeploymentDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(RemoteDeploymentDeathWatchSpec.scala:91)
[JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:369)
[JVM-2]   at akka.remote.RemoteDeploymentDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(RemoteDeploymentDeathWatchSpec.scala:85)
[JVM-2]   at akka.remote.RemoteDeploymentDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(RemoteDeploymentDeathWatchSpec.scala:84)
[JVM-2]   at akka.remote.RemoteDeploymentDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(RemoteDeploymentDeathWatchSpec.scala:84)
```

**Comment by jrudolph** [comment]
Didn't happen for a long time, closing...
