### ISSUE TITLE
Exception thrown in akka.stream.scaladsl.Partition is not bubbled up to Supervision.Decider

### ISSUE THREAD

**Issue by KCBEAR2017** [akka/akka#24220]
found that the stream is shutdown/doesn’t continue if there is exception thrown in Partition.   

Suppose sending 1 to 10 and throws exception in 5, afterwards, there is nothing.

2018-01-02 11:40:35.662 INFO  [c.FlowExceptionHandlingSpec] [FlowExceptionHandlingSpec-akka.actor.default-dispatcher-4] - passing 1
2018-01-02 11:40:35.662 INFO  [c.FlowExceptionHandlingSpec] [FlowExceptionHandlingSpec-akka.actor.default-dispatcher-4] - passing 2
2018-01-02 11:40:35.662 INFO  [c.FlowExceptionHandlingSpec] [FlowExceptionHandlingSpec-akka.actor.default-dispatcher-4] - passing 3
2018-01-02 11:40:35.662 INFO  [c.FlowExceptionHandlingSpec] [FlowExceptionHandlingSpec-akka.actor.default-dispatcher-4] - passing 4
[ERROR] [01/02/2018 11:40:35.662] [FlowExceptionHandlingSpec-akka.actor.default-dispatcher-4] [akka://FlowExceptionHandlingSpec/user/StreamSupervisor-0/flow-0-0-unnamed] Error in stage [Partition(2)]: Mock IllegalStateException 5
java.lang.IllegalStateException: Mock IllegalStateException 5
              at com.FlowExceptionHandlingSpec.incomingMessageSplitter$1(FlowExceptionHandlingSpec.scala:43)
              at com.FlowExceptionHandlingSpec.$anonfun$new$4(FlowExceptionHandlingSpec.scala:52)
              at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:12)
….

Even tried with, val incomingSplit = builder.add(Partition[Int](2, incomingMessageSplitter).withAttributes(ActorAttributes.supervisionStrategy(decider)))
The issue is still there.

akka-stream 2.12, version 2.5.6
[study_uncaught_expcetion_in_Splitter2.zip](https://github.com/akka/akka/files/1596611/study_uncaught_expcetion_in_Splitter2.zip)

in the test cases, I tried with different implementation while my objectives is using Source.queue to offer message due to clustering consistent hashing concern. Anyways, you can reference the test case of a Graph DSL with/without using splitter. The main objective is all uncaught exception should go to Decider and flow should be resumed even there is exception thrown

**Comment by johanandren** [comment]
Sounds like it could make sense (note that a lot of stages does not honor the supervision strategy, #23066 )

**Comment by ktoso** [comment]
Worked on tokyo hackathon :)
