### ISSUE TITLE
Cannot instantiate a MessageDispatcherConfigurator with typed actors

### ISSUE THREAD

**Issue by yanns** [akka/akka#24245]
I'm using a custom MessageDispatcherConfigurator like the one described here: https://yanns.github.io/blog/2014/05/04/slf4j-mapped-diagnostic-context-mdc-with-play-framework/:
```
/**
 * Configurator for a MDC propagating dispatcher.
 *
 * To use it, configure play like this:
 * {{{
 * akka {
 *   actor {
 *     default-dispatcher = {
 *       type = "de.commercetools.sphere.util.concurrent.MDCPropagatingDispatcherConfigurator"
 *     }
 *   }
 * }
 * }}}
 *
 * Credits to James Roper for the [[https://github.com/jroper/thread-local-context-propagation/ initial implementation]]
 */
class MDCPropagatingDispatcherConfigurator(config: Config, prerequisites: DispatcherPrerequisites)
  extends MessageDispatcherConfigurator(config, prerequisites) {

  private val instance = new Dispatcher(
    this,
    config.getString("id"),
    config.getInt("throughput"),
    FiniteDuration(config.getDuration("throughput-deadline-time", TimeUnit.NANOSECONDS), TimeUnit.NANOSECONDS),
    configureExecutor(),
    FiniteDuration(config.getDuration("shutdown-timeout", TimeUnit.MILLISECONDS), TimeUnit.MILLISECONDS))
    with MDCPropagatorExecutionContext

  override def dispatcher(): MessageDispatcher = instance
}
```

I can use this dispatcher with the un-typed actor system.
But the typed actor system cannot instantiate it.

The error:
```
[info]   akka.ConfigurationException: Cannot instantiate DispatcherConfigurator type [de.commercetools.sphere.util.concurrent.MDCPropagatingDispatcherConfigurator], defined in [akka.actor.default-dispatcher], make sure it has constructor with [com.typesafe.config.Config] and [akka.dispatch.DispatcherPrerequisites] parameters
[info]   at akka.typed.internal.DispatchersImpl$$anonfun$configuratorFrom$1.applyOrElse(DispatchersImpl.scala:139)
[info]   at akka.typed.internal.DispatchersImpl$$anonfun$configuratorFrom$1.applyOrElse(DispatchersImpl.scala:133)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[info]   at scala.util.Failure.recover(Try.scala:230)
[info]   at akka.typed.internal.DispatchersImpl.configuratorFrom(DispatchersImpl.scala:133)
[info]   at akka.typed.internal.DispatchersImpl.lookupConfigurator(DispatchersImpl.scala:86)
[info]   at akka.typed.internal.DispatchersImpl.lookup(DispatchersImpl.scala:64)
[info]   at akka.typed.internal.DispatchersImpl.defaultGlobalDispatcher(DispatchersImpl.scala:46)
[info]   at akka.typed.internal.DispatchersImpl.lookup(DispatchersImpl.scala:22)
[info]   at akka.typed.internal.ActorSystemImpl.<init>(ActorSystemImpl.scala:189)
[info]   ...
[info]   Cause: java.lang.ClassCastException: class akka.typed.internal.DispatcherConfigurator is not assignable from class de.commercetools.sphere.util.concurrent.MDCPropagatingDispatcherConfigurator
[info]   at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:23)
[info]   at scala.util.Try$.apply(Try.scala:209)
[info]   at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:20)
[info]   at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:38)
[info]   at akka.typed.internal.DispatchersImpl.configuratorFrom(DispatchersImpl.scala:133)
[info]   at akka.typed.internal.DispatchersImpl.lookupConfigurator(DispatchersImpl.scala:86)
[info]   at akka.typed.internal.DispatchersImpl.lookup(DispatchersImpl.scala:64)
[info]   at akka.typed.internal.DispatchersImpl.defaultGlobalDispatcher(DispatchersImpl.scala:46)
[info]   at akka.typed.internal.DispatchersImpl.lookup(DispatchersImpl.scala:22)
[info]   at akka.typed.internal.ActorSystemImpl.<init>(ActorSystemImpl.scala:189)
[info]   ...
```

The code for instantiating in the un-typed world:
```
        val args = List(classOf[Config] → cfg, classOf[DispatcherPrerequisites] → prerequisites)
        prerequisites.dynamicAccess.createInstanceFor[MessageDispatcherConfigurator](fqn, args).recover({
          case exception ⇒
            throw new ConfigurationException(
              ("Cannot instantiate MessageDispatcherConfigurator type [%s], defined in [%s], " +
                "make sure it has constructor with [com.typesafe.config.Config] and " +
                "[akka.dispatch.DispatcherPrerequisites] parameters")
                .format(fqn, cfg.getString("id")), exception)
        }).get
```

This code instantiates a `MessageDispatcherConfigurator` with 2 parameters: `Config` and `DispatcherPrerequisites`.

Compared to the code in the typed world:
```
        val args = List(classOf[Config] → cfg)
        prerequisites.dynamicAccess.createInstanceFor[DispatcherConfigurator](fqn, args).recover({
          case exception ⇒
            throw new ConfigurationException(
              ("Cannot instantiate DispatcherConfigurator type [%s], defined in [%s], " +
                "make sure it has constructor with [com.typesafe.config.Config] and " +
                "[akka.dispatch.DispatcherPrerequisites] parameters")
                .format(fqn, cfg.getString("id")), exception)
        }).get
```

This code instantiates a `MessageDispatcherConfigurator` with only 1 parameter: `Config`.
(although the error message says otherwise)

For consistency, I'd suggest that we add the `DispatcherPrerequisites` parameter in the typed world also. WDYT?

**Comment by yanns** [comment]
The typed implementation was removed in https://github.com/akka/akka/pull/24176
(as discussed in https://github.com/akka/akka/issues/24149).
So I guess this error will not happen anymore.

**Comment by johanandren** [comment]
Thanks for digging into it and letting us know, closing this then!
