### ISSUE TITLE
FAILED: LargeMessageStreamSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24266]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11190/testReport/junit/akka.remote.artery/LargeMessagesStreamSpec/The_large_message_support_should_allow_for_normal_communication_while_simultaneously_sending_large_messages/

```
sbt.ForkMain$ForkError: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://LargeMessagesStreamSpec-remote-2@localhost:33979/), Path(/user/large)]
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:70)
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:68)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:78)
	at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:120)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:77)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:274)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:68)
	at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:85)
	at akka.remote.artery.LargeMessagesStreamSpec.awaitResolve(LargeMessagesStreamSpec.scala:122)
	at akka.remote.artery.LargeMessagesStreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(LargeMessagesStreamSpec.scala:102)
	at akka.remote.artery.LargeMessagesStreamSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(LargeMessagesStreamSpec.scala:84)
```

**Comment by johanandren** [comment]
Ach. Duplicate of #24143
