### ISSUE TITLE
Artery shutdown hook: IllegalStateException: Shutdown in progress

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24282]
Noticed this when ctrl-c in sample app

```
16:49:30.481 ERROR [akka.actor.OneForOneStrategy] [ClusterSystem-akka.actor.default-dispatcher-25] - Shutdown in progress
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at akka.remote.artery.ArteryTransport.shutdown(ArteryTransport.scala:883)
	at akka.remote.RemoteActorRefProvider$RemotingTerminator$$anonfun$3.applyOrElse(RemoteActorRefProvider.scala:64)
	at akka.remote.RemoteActorRefProvider$RemotingTerminator$$anonfun$3.applyOrElse(RemoteActorRefProvider.scala:61)
```

It's probably ok, but we shouldn't log that.

**Comment by patriknw** [comment]
This was fixed in https://github.com/akka/akka/commit/905e61664b7958e812463e1551d9fb40c7a01f19#diff-eb9e5a1a0b6ac3919352e9dd7689511bR884
