### ISSUE TITLE
Failed: MetricsBasedResizerSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24397]
```
Error Message
org.scalatest.exceptions.TestFailedException: 50 was not 70 plus or minus 14
Stacktrace
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: 50 was not 70 plus or minus 14
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
	at akka.routing.MetricsBasedResizerSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply$mcV$sp(MetricsBasedResizerSpec.scala:254)
	at akka.routing.MetricsBasedResizerSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(MetricsBasedResizerSpec.scala:232)
	at akka.routing.MetricsBasedResizerSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(MetricsBasedResizerSpec.scala:232)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scala
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5667/testReport/junit/akka.routing/MetricsBasedResizerSpec/MetricsBasedResizer_reportMessageCount_must_record_the_performance_log_with_the_correct_process_speed/

**Comment by johanandren** [comment]
50 millis plus minus 10 percent, seems like an awful tight timing given that we just before it saw a [Times: user=0.57 sys=0.08, real=0.07 secs]  GC pause. Maybe scale these timings up a bit
