### ISSUE TITLE
Failed: StreamRefsSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24413]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5670/testReport/junit/akka.stream.scaladsl/StreamRefsSpec/A_SinkRef_must_receive_hundreds_of_elements_via_remoting/

FYI @ktoso 

```
Error Message
java.lang.AssertionError: assertion failed: expected payload-98, found Failure(java.lang.IllegalArgumentException: Cannot push port (SourceRefStageImpl.out(1274846228)) twice, or before it being pulled)
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: expected payload-98, found Failure(java.lang.IllegalArgumentException: Cannot push port (SourceRefStageImpl.out(1274846228)) twice, or before it being pulled)
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
	at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:378)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:890)
	at akka.stream.scaladsl.StreamRefsSpec$$anonfun$2$$anonfun$apply$mcV$sp$8$$anonfun$apply$2.apply(StreamRefsSpec.scala:319)
	at akka.stream.scaladsl.StreamRefsSpec$$anonfun$2$$anonfun$apply$mcV$sp$8$$anonfun$apply$2.apply(StreamRefsSpec.scala:319)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at akka.stream.scaladsl.StreamRefsSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(StreamRefsSpec.scala:319)
	at akka.stream.scaladsl.StreamRefsSpec$$anonfun$2$$anonfun$apply$mcV$sp$8.apply(StreamRefsSpec.scala:310)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by ktoso** [comment]
Ouch that's likely a bug! Will assign to myself and look into it on monday

**Comment by ktoso** [comment]
On it
