### ISSUE TITLE
Failed: akka.stream.io.TcpSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24437]
akka.stream.io.TcpSpec.Outgoing TCP stream must fail the materialized future when the connection fails

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11550/testReport/junit/akka.stream.io/TcpSpec/Outgoing_TCP_stream_must_fail_the_materialized_future_when_the_connection_fails/

```
sbt.ForkMain$ForkError: org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100 milliseconds between each query.
	at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
	at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:676)
	at akka.testkit.AkkaSpec.whenReady(AkkaSpec.scala:59)
	at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$4.apply(TcpSpec.scala:96)
	at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$26$$anonfun$apply$4.apply(TcpSpec.scala:89)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:25)
	at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$26.apply(TcpSpec.scala:89)
	at akka.stream.io.TcpSpec$$anonfun$1$$anonfun$apply$mcV$sp$26.apply(TcpSpec.scala:89)
```

**Comment by chbatey** [comment]
Looks like there a few states where we don't handle the ReceiveTimeout. Will add
