### ISSUE TITLE
Failed: MultiDcSplitBrain

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24467]
https://jenkins.akka.io:8498/job/akka-multi-node/2562/consoleFull

```
[JVM-4] - must be able to have data center member leave while there is inter data center split (on node 'fourth', class akka.cluster.MultiDcSplitBrainMultiJvmNode4) *** FAILED *** (139 milliseconds)
[JVM-4]   java.lang.AssertionError: assertion failed: expected class akka.cluster.ClusterEvent$UnreachableDataCenter, found class akka.cluster.ClusterEvent$ReachableDataCenter (ReachableDataCenter(dc1))
[JVM-4]   at scala.Predef$.assert(Predef.scala:170)
[JVM-4]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[JVM-4]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:490)
[JVM-4]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:890)
[JVM-4]   at akka.cluster.MultiDcSplitBrainSpec$$anonfun$splitDataCenters$3.apply$mcV$sp(MultiDcSplitBrainSpec.scala:93)
[JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:369)
[JVM-4]   at akka.cluster.MultiDcSplitBrainSpec.splitDataCenters(MultiDcSplitBrainSpec.scala:92)
```

**Comment by chbatey** [comment]
I think this is fixed by https://github.com/akka/akka/pull/24443
