### ISSUE TITLE
Failed: ClusterSingletonManagerMultiJvm

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24483]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1134/consoleFull

```
[JVM-1] - must startup 6 node cluster (on node 'controller', class akka.cluster.singleton.ClusterSingletonManagerMultiJvmNode1) *** FAILED ***
[JVM-1]   java.lang.RuntimeException: barrier failed: after-11-verified
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:222)
[JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:197)
[JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:665)
[JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:157)
```

**Comment by johanandren** [comment]
Was actually the permission denied failure #20001
