### ISSUE TITLE
FAILED: akka.persistence.journal.leveldb.JournalNoCompactionSpec.A LevelDB-based persistent actor must NOT compact the journal if compaction is not activated by configuration

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#24502]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/472/testReport/akka.persistence.journal.leveldb/JournalNoCompactionSpec/A_LevelDB_based_persistent_actor_must_NOT_compact_the_journal_if_compaction_is_not_activated_by_configuration/

```
Error Message

java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for Generated(952)

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for Generated(952)
	at scala.Predef$.assert(Predef.scala:219)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:401)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:895)
	at akka.persistence.journal.leveldb.JournalNoCompactionSpec.$anonfun$new$3(JournalCompactionSpec.scala:31)
	at akka.persistence.journal.leveldb.JournalNoCompactionSpec.$anonfun$new$3$adapted(JournalCompactionSpec.scala:29)
	at akka.persistence.journal.leveldb.JournalNoCompactionSpec$$Lambda$745/1821730671.apply(Unknown Source)
	at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:71)
	at akka.persistence.journal.leveldb.JournalNoCompactionSpec.$anonfun$new$2(JournalCompactionSpec.scala:29)
	at akka.persistence.journal.leveldb.JournalNoCompactionSpec$$Lambda$744/1169747085.apply$mcV$sp(Unknown Source)
```

**Comment by patriknw** [comment]
obsolete
