### ISSUE TITLE
RestartWithBackoffFlow: Cannot pull closed port

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24529]
Noticed this, which might indicate a bug?

```
[info] java.lang.IllegalArgumentException: Cannot pull closed port (RestartWithBackoffFlow.in(427816349))
[info] 	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:465)
[info] 	at akka.stream.scaladsl.RestartWithBackoffLogic$$anon$10.onPull(Restart.scala:470)
[info] 	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$7.apply(GraphStage.scala:1345)
[info] 	at akka.stream.stage.GraphStageLogic$SubSourceOutlet$$anonfun$7.apply(GraphStage.scala:1341)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:454)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:465)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
```

I think it was when the inner flow was immediately completed with failure because it had a KillSwitch that had already been aborted.

**Comment by johanandren** [comment]
Tried to reproduce this for a while now but can't figure out how `in` could be closed/failed while the inner flow still would do a pull, it is either running with a sub flow and then cancel/error from upstream is delegated to the `SubSourceOutlet` or it is restarting, and then the default cancel/error handling is used and should fail the entire `RestartWithBackoffFlow` stage. O.o

**Comment by johanandren** [comment]
One idea just struck me, cancel/complete on the `SubSourceOutlet` is through an async callback, so maybe a race between that and the pull from downstream.

**Comment by johanandren** [comment]
More digging: the async callback race is not possible - `SubSourceoutlet` has a local flag it toggles on close/failure and subsequent async callbacks are ignored.

**Comment by johanandren** [comment]
Dropping this until we know more. I could push a fix but I'm worried that the fix hides the issue rather than fixes it as I didn't manage to reproduce.

**Comment by chbatey** [comment]
Taking a look at this
