### ISSUE TITLE
RateTransformationDocSpec

### ISSUE THREAD

**Issue by raboof** [akka/akka#24559]
I don't see a gc, but 100ms is a bit tight anyway perhaps?

https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/994/consoleFull

```
[info] RateTransformationDocSpec:
Coroner Thread Count starts at 21 in docs.stream.RateTransformationDocSpec
[info] - conflate should summarize *** FAILED *** (148 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.result(package.scala:190)
[info]   at docs.stream.RateTransformationDocSpec$$anonfun$4.apply(RateTransformationDocSpec.scala:41)
[info]   at docs.stream.RateTransformationDocSpec$$anonfun$4.apply(RateTransformationDocSpec.scala:24)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5235/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5742/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/995/console
