### ISSUE TITLE
FAILED: GraphMergePrioritizedSpec merge prioritized must stream data with priority

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24580]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11828/testReport/junit/akka.stream.scaladsl/GraphMergePrioritizedSpec/merge_prioritized_must_stream_data_with_priority/

```
org.scalatest.exceptions.TestFailedException: 7 did not equal 6

Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: 7 did not equal 6
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6742)
	at akka.stream.scaladsl.GraphMergePrioritizedSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GraphMergePrioritizedSpec.scala:74)
	at akka.stream.scaladsl.GraphMergePrioritizedSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GraphMergePrioritizedSpec.scala:49)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:59)
```

**Comment by 2m** [comment]
Previous issue https://github.com/akka/akka/issues/23336 and a fix https://github.com/akka/akka/pull/24020

**Comment by 2m** [comment]
The test-case is still at mercy of the scheduler.

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node/runs/2993/log/?start=0

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6622/testReport/junit/akka.stream.scaladsl/GraphMergePrioritizedSpec/merge_prioritized_must_stream_data_with_priority/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/17581/consoleFull

**Comment by jrudolph** [comment]
Still happening in Akka 2.5 so maybe it needs a backport:

https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/79/testReport/junit/akka.stream.scaladsl/GraphMergePrioritizedSpec/merge_prioritized_must_stream_data_with_priority/
