### ISSUE TITLE
failed: FlowIteratorSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24607]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11874/consoleText

```
[info]   java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class java.lang.IllegalStateException,None,Left(not two),true)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
[info]   at akka.stream.scaladsl.FlowIterableSpec$$anonfun$5.apply(FlowIteratorSpec.scala:40)
[info]   at akka.stream.scaladsl.FlowIterableSpec$$anonfun$5.apply(FlowIteratorSpec.scala:28)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:26)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
```

**Comment by patriknw** [comment]
ah, I thought this was another PR, but it was in https://github.com/akka/akka/pull/24605
perhaps it's just something that is not finished yet

**Comment by ktoso** [comment]
Yes, it's WIP, sorry should have marked
