### ISSUE TITLE
Artery TCP cannot be used with Akka Typed

### ISSUE THREAD

**Issue by hseeberger** [akka/akka#24620]
```
sbt:whirlwind-tour-akka> whirlwind-tour-akka[ERROR] Exception in thread "main" java.lang.IllegalStateException: The calling code expected that the ActorSystem was initialized but it wasn't yet. This is probably a bug in the ActorSystem initialization sequence often related to initialization of extensions. Please report at https://github.com/akka/akka/issues.
```

I just added this section to my config:

```
  remote {
    artery {
      enabled   = on
      transport = tcp
    }
  }
```

**Comment by hseeberger** [comment]
Using these additional props:

```
       |-Dwta.use-cluster-bootstrap=off
       |-Dcassandra-journal.contact-points.0=127.0.0.1:9042
       |-Dcassandra-snapshot-store.contact-points.0=127.0.0.1:9042
       |-Dakka.remote.artery.canonical.hostname=127.0.0.1
       |-Dakka.cluster.seed-nodes.0=akka://wta@127.0.0.1:25520""".stripMargin
```

**Comment by patriknw** [comment]
Ah, I don’t think we tried Typed with Artery.

**Comment by hseeberger** [comment]
Ouch ;-)

**Comment by johanandren** [comment]
Hmm programmatic join at least seems to work fine.

**Comment by johanandren** [comment]
You think you could share the entire stack trace so we can see what extension is triggering it @hseeberger ?

**Comment by hseeberger** [comment]
```
sbt:whirlwind-tour-akka> whirlwind-tour-akka[ERROR] Exception in thread "main" java.lang.IllegalStateException: The calling code expected that the ActorSystem was initialized but it wasn't yet. This is probably a bug in the ActorSystem initialization sequence often related to initialization of extensions. Please report at https://github.com/akka/akka/issues.
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.assertInitialized(ActorSystem.scala:820)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter.<init>(ActorSystemAdapter.scala:32)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension.<init>(ActorSystemAdapter.scala:92)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.createExtension(ActorSystemAdapter.scala:99)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.createExtension(ActorSystemAdapter.scala:95)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter$AdapterExtension$.apply(ActorSystemAdapter.scala:95)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.internal.adapter.ActorSystemAdapter$.apply(ActorSystemAdapter.scala:88)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.scaladsl.adapter.AdapterExtension.<init>(AdapterExtension.scala:16)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.scaladsl.adapter.AdapterExtension$.createExtension(AdapterExtension.scala:22)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.scaladsl.adapter.AdapterExtension$.createExtension(AdapterExtension.scala:21)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.scaladsl.adapter.AdapterExtension$.apply(AdapterExtension.scala:21)
whirlwind-tour-akka[ERROR] 	at akka.actor.typed.scaladsl.adapter.package$UntypedActorSystemOps$.toTyped$extension(package.scala:57)
whirlwind-tour-akka[ERROR] 	at rocks.heikoseeberger.wta.UserRepositorySerializer.<init>(UserRepositorySerializer.scala:51)
whirlwind-tour-akka[ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
whirlwind-tour-akka[ERROR] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
whirlwind-tour-akka[ERROR] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
whirlwind-tour-akka[ERROR] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
whirlwind-tour-akka[ERROR] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:32)
whirlwind-tour-akka[ERROR] 	at scala.util.Try$.apply(Try.scala:209)
whirlwind-tour-akka[ERROR] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
whirlwind-tour-akka[ERROR] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$4(ReflectiveDynamicAccess.scala:38)
whirlwind-tour-akka[ERROR] 	at scala.util.Success.flatMap(Try.scala:247)
whirlwind-tour-akka[ERROR] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:38)
whirlwind-tour-akka[ERROR] 	at akka.serialization.Serialization.serializerOf(Serialization.scala:301)
whirlwind-tour-akka[ERROR] 	at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:327)
whirlwind-tour-akka[ERROR] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:739)
whirlwind-tour-akka[ERROR] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
whirlwind-tour-akka[ERROR] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
whirlwind-tour-akka[ERROR] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:738)
whirlwind-tour-akka[ERROR] 	at akka.serialization.Serialization.<init>(Serialization.scala:327)
whirlwind-tour-akka[ERROR] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:15)
whirlwind-tour-akka[ERROR] 	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:12)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
whirlwind-tour-akka[ERROR] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
whirlwind-tour-akka[ERROR] 	at akka.serialization.SerializationExtension$.apply(SerializationExtension.scala:12)
whirlwind-tour-akka[ERROR] 	at akka.remote.artery.Deserializer$$anon$3.<init>(Codecs.scala:583)
whirlwind-tour-akka[ERROR] 	at akka.remote.artery.Deserializer.createLogic(Codecs.scala:581)
whirlwind-tour-akka[ERROR] 	at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:93)
whirlwind-tour-akka[ERROR] 	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:632)
whirlwind-tour-akka[ERROR] 	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:452)
whirlwind-tour-akka[ERROR] 	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:417)
whirlwind-tour-akka[ERROR] 	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:408)
whirlwind-tour-akka[ERROR] 	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:556)
whirlwind-tour-akka[ERROR] 	at akka.remote.artery.tcp.ArteryTcpTransport.runInboundControlStream(ArteryTcpTransport.scala:334)
whirlwind-tour-akka[ERROR] 	at akka.remote.artery.tcp.ArteryTcpTransport.runInboundStreams(ArteryTcpTransport.scala:211)
whirlwind-tour-akka[ERROR] 	at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:454)
whirlwind-tour-akka[ERROR] 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:225)
whirlwind-tour-akka[ERROR] 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:31)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:826)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:823)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:823)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:842)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
whirlwind-tour-akka[ERROR] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:234)
whirlwind-tour-akka[ERROR] 	at rocks.heikoseeberger.wta.Main$.main(Main.scala:50)
whirlwind-tour-akka[ERROR] 	at rocks.heikoseeberger.wta.Main.main(Main.scala)
whirlwind-tour-akka ... finished with exit code 1
```

**Comment by hseeberger** [comment]
It's this project. The changes made against master are:

```
diff --git a/build.sbt b/build.sbt
index 15748f0..93e5212 100644
--- a/build.sbt
+++ b/build.sbt
@@ -155,9 +155,8 @@ lazy val commandAliases =
        |-Dwta.use-cluster-bootstrap=off
        |-Dcassandra-journal.contact-points.0=127.0.0.1:9042
        |-Dcassandra-snapshot-store.contact-points.0=127.0.0.1:9042
-       |-Dakka.remote.netty.tcp.hostname=127.0.0.1
-       |-Dakka.remote.netty.tcp.port=2550
-       |-Dakka.cluster.seed-nodes.0=akka.tcp://wta@127.0.0.1:2550""".stripMargin
+       |-Dakka.remote.artery.canonical.hostname=127.0.0.1
+       |-Dakka.cluster.seed-nodes.0=akka://wta@127.0.0.1:25520""".stripMargin
   ) ++
     addCommandAlias(
       "r1",
@@ -167,7 +166,7 @@ lazy val commandAliases =
          |-Dwta.api.port=8001
          |-Dcassandra-journal.contact-points.0=127.0.0.1:9042
          |-Dcassandra-snapshot-store.contact-points.0=127.0.0.1:9042
-         |-Dakka.remote.netty.tcp.hostname=127.0.0.1
-         |-Dakka.remote.netty.tcp.port=2551
-         |-Dakka.cluster.seed-nodes.0=akka.tcp://wta@127.0.0.1:2550""".stripMargin
+         |-Dakka.remote.artery.canonical.hostname=127.0.0.1
+         |-Dakka.remote.artery.canonical.port=25521
+         |-Dakka.cluster.seed-nodes.0=akka://wta@127.0.0.1:25520""".stripMargin
     )
diff --git a/src/main/resources/application.conf b/src/main/resources/application.conf
index 8e8e879..a4ac61b 100644
--- a/src/main/resources/application.conf
+++ b/src/main/resources/application.conf
@@ -50,6 +50,13 @@ akka {
       plugin                     = cassandra-snapshot-store
     }
   }
+
+  remote {
+    artery {
+      enabled   = on
+      transport = tcp
+    }
+  }
 }
 
 wta {
```

**Comment by johanandren** [comment]
I wonder if it isn't that the `UserRepositorySerializer` eagerly tries to use the typed adapter, are you doing a toTyped in its constructor? Try making that lazy?

**Comment by hseeberger** [comment]
Yes, that solves the issue. Yet I try to avoid `lazy` in my codebase. Eagerly creating the `ActorRefResolver` works for the old transport. Hence I assume that there is something you could change in Artery to not force `lazy`ness on us ;-)

**Comment by johanandren** [comment]
I checked seed nodes by config joining as well and no problem there either, this may be worth fixing (not sure, we have a few places where we avoid such boot-deadlocks in extensions inside of Akka as well) but I'll drop it for now.

**Comment by jrudolph** [comment]
I looked into this a while ago when we noticed a similar problem in typed ActorSystem initialization. The problem is that 1) untyped ActorSystem initialization is somewhat messy and 2) there's no dependency system for Akka extensions so you can always run into similar issues when you have a circular dependency between extensions. Wrt 1) the situation could probably be somewhat improved by clearly delineating phases in the startup of an ActorSystem where certain features are already available (and fail  otherwise). However, it would be quite involved to actually fix this. We concluded that even if it is surprising that initialization works at all like this (ActorSystem creates the remote transport, the remote transport (in Artery) already tries to use Akka Streams during initialization which already needs features from the half-baken ActorSystem), it currently isn't easy enough to fix.

The error message you are seeing is one that I added back then. I added it specifically to avoid running into the extension initialization deadlock otherwise.

**Comment by patriknw** [comment]
In this case the serializers are loaded eagerly by Codecs.scala:583 and we can make that more lazy.
