### ISSUE TITLE
Failed: SupervisorHierarchySpec.A Supervisor Hierarchy must survive being stressed

### ISSUE THREAD

**Issue by 2m** [akka/akka#24630]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/5778/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5653/testReport/junit/akka.actor/SupervisorHierarchySpec/A_Supervisor_Hierarchy_must_survive_being_stressed/

**Comment by helena** [comment]
I am seeing this as well, locally and in CI here and a few other build runs
https://jenkins.akka.io:8498/view/Nightly%20Jobs/job/akka-nightly-scoverage/10/console. 
It should have had a full case match `case otherRef =>` but real issue is that it's `akka.actor.DeadLetterActorRef` and stopped is odd, versus the expected `stressTestSuccessful` and *then* `stressTestStopped`.
```
[ERROR] [02/27/2019 00:31:08.807] [SupervisorHierarchySpec-akka.actor.default-dispatcher-15] [akka://SupervisorHierarchySpec/user/stressTest] Actor[akka://SupervisorHierarchySpec/deadLetters] (of class akka.actor.DeadLetterActorRef)
scala.MatchError: Actor[akka://SupervisorHierarchySpec/deadLetters] (of class akka.actor.DeadLetterActorRef)
	at akka.actor.SupervisorHierarchySpec$StressTest.getErrorsUp(SupervisorHierarchySpec.scala:667)
```

**Comment by seglo** [comment]
I'm not sure if it's appropriate to repoen this issue since context from old builds are long gone.

https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/112/consoleFull

```
[info] - must survive being stressed *** FAILED *** (11 seconds, 656 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected stressTestSuccessful, found stressTestFailed
[info]   at scala.Predef$.assert(Predef.scala:282)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:419)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info]   at akka.actor.SupervisorHierarchySpec.$anonfun$new$20(SupervisorHierarchySpec.scala:925)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:61)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:61)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]   at scala.collection.immutable.List.foreach(List.scala:312)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]   at scala.collection.immutable.List.foreach(List.scala:312)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:61)
[info]   at org.scalatest.Suite.run(Suite.scala:1124)
[info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info]   at akka.testkit.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:61)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:61)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:61)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by patriknw** [comment]
Closing as old
