### ISSUE TITLE
Failed: LeveldbJournalNativeSpec (jdk9)

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24708]
https://jenkins.akka.io:8498/job/akka-nightly-jdk9/102/console

```
[info] LeveldbJournalNativeSpec:
[info] A journal
[info] akka.persistence.journal.leveldb.LeveldbJournalNativeSpec *** ABORTED *** (10 seconds, 203 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for WriteMessagesSuccessful
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:401)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:895)
[info]   at akka.persistence.journal.JournalSpec.writeMessages(JournalSpec.scala:96)
[info]   at akka.persistence.journal.JournalSpec.beforeEach(JournalSpec.scala:50)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:220)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
[info]   at akka.persistence.PluginSpec.runTest(PluginSpec.scala:14)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
```

**Comment by patriknw** [comment]
obsolete
