### ISSUE TITLE
Failed: akka.persistence.ThrowExceptionStrategyPersistentActorBoundedStashingSpec

### ISSUE THREAD

**Issue by 2m** [akka/akka#24724]
Failed on Scala 2.12 community build.

```
[akka-more] [info] - should throws stash overflow exception *** FAILED *** (132 milliseconds)
[akka-more] [info]   java.lang.AssertionError: assertion failed: expected DeadLetter(Cmd(1),Actor[akka://PersistenceSpec/system/testActor-79#-1727550055],Actor[akka://PersistenceSpec/user/$a#1541285985]), found DeadLetter(Cmd(a),Actor[akka://PersistenceSpec/system/testActor-79#-1727550055],Actor[akka://PersistenceSpec/user/$a#1541285985])
[akka-more] [info]   at scala.Predef$.assert(Predef.scala:219)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:402)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:378)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:378)
[akka-more] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:895)
[akka-more] [info]   at akka.persistence.ThrowExceptionStrategyPersistentActorBoundedStashingSpec.$anonfun$new$5(PersistentActorBoundedStashingSpec.scala:99)
[akka-more] [info]   at akka.persistence.ThrowExceptionStrategyPersistentActorBoundedStashingSpec.$anonfun$new$5$adapted(PersistentActorBoundedStashingSpec.scala:99)
[akka-more] [info]   at scala.collection.immutable.Range.foreach(Range.scala:156)
[akka-more] [info]   at akka.persistence.ThrowExceptionStrategyPersistentActorBoundedStashingSpec.$anonfun$new$2(PersistentActorBoundedStashingSpec.scala:99)
[akka-more] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[akka-more] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[akka-more] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[akka-more] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[akka-more] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[akka-more] [info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[akka-more] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[akka-more] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[akka-more] [info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:59)
[akka-more] [info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[akka-more] [info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[akka-more] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[akka-more] [info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
```

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2662/consoleFull

**Comment by patriknw** [comment]
obsolete
