### ISSUE TITLE
failed: akka.cluster.typed.ClusterApiSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#24728]
https://jenkins.akka.io:8498/job/akka-nightly/5316/testReport/junit/akka.cluster.typed/ClusterApiSpec/A_typed_Cluster_must_join_a_cluster_and_observe_events_from_both_sides/

```
Error Message
org.scalatest.exceptions.TestFailedException: Exiting did not equal Removed
Stacktrace
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: Exiting did not equal Removed
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$3.apply(ClusterApiSpec.scala:96)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$3.apply(ClusterApiSpec.scala:96)
	at akka.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:224)
	at akka.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:238)
	at akka.cluster.typed.ClusterApiSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ClusterApiSpec.scala:95)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

**Comment by johanandren** [comment]
I think it's simply a too short timeout for awaitAssert.

**Comment by johanandren** [comment]
Ach, I was wrong.

https://jenkins.akka.io:8498/job/akka-nightly/5440/testReport/junit/akka.cluster.typed/ClusterApiSpec/A_typed_Cluster_must_join_a_cluster_and_observe_events_from_both_sides/
