### ISSUE TITLE
Unexpected behaviour of RestartFlow.onFailuresWithBackoff

### ISSUE THREAD

**Issue by julianhowarth** [akka/akka#24726]
I was expecting the behaviour of `RestartFlow.onFailuresWithBackoff` to be the same as `RestartFlow.withBackoff` when a failure occurs in the stream. Instead I am seeing different behaviours. The below using `withBackoff` works as expected:

```
  implicit val sys = ActorSystem()
  implicit val executor = sys.dispatcher
  implicit val mat = {
    // Supervisor so we can see what's going on, but use default Stop behaviour 
    val decider: Supervision.Decider = {
      case NonFatal(e) ⇒
        println(s"Supervisor got exception: ${e.getMessage}")
        Supervision.Stop
    }
    ActorMaterializer(ActorMaterializerSettings(sys).withSupervisionStrategy(decider))
  }

  val failing =
    Flow[Int].map(i ⇒
      if (i % 3 == 0) {
        println("About to fail")
        throw new RuntimeException("FAIL!")
      }
      else i)

  val safe =
    RestartFlow.withBackoff(1.second, 2.seconds, 0.2, 2)(() ⇒ {
      println("Creating flow")
      failing
    })

  Source(1 to 7)
    .via(safe)
    .runWith(Sink.foreach(println))
    .onComplete {
      case Success(_) ⇒
        println("Completed successfully")
      case Failure(ex) ⇒
        println(s"Failed - ${ex.getMessage}")
    }
```
Prints out:
```
Creating flow
1
2
About to fail
Supervisor got exception: FAIL!
Creating flow
4
5
About to fail
Supervisor got exception: FAIL!
Creating flow
7
Completed successfully
```
However, if I change the `safe` val to be:
```
  val safe =
    RestartFlow.onFailuresWithBackoff(1.second, 2.seconds, 0.2, 2)(() ⇒ {
      println("Creating flow")
      failing
    })
```
I get:
```
Creating flow
1
2
About to fail
Supervisor got exception: FAIL!
[ERROR] [03/14/2018 08:22:42.753] [default-akka.actor.default-dispatcher-5] [RestartWithBackoffFlow(akka://default)] Restarting graph due to failure
java.lang.RuntimeException: FAIL!
	at jhowarth.RestartFlowTest$.$anonfun$failing$1(AkkaBug.scala:31)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:12)
	at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:732)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:758)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Creating flow
Failed - Cannot pull closed port (RestartWithBackoffFlow.in(1245019744))
```
However, I would have expected identical behaviour to the `withBackoff` version.

akka-streams: 2.5.11
scala: 2.12.4

**Comment by patriknw** [comment]
"Cannot pull closed port" indicates that this is a bug.

btw, do you see the same if removing the supervision decider?

**Comment by julianhowarth** [comment]
Thanks, I thought the "cannot pull" was unlikely to be the intended behaviour. 

Switching to use: `implicit val mat = ActorMaterializer()` and behaviour is the same (minus the logging):
```
Creating flow
1
2
About to fail
[ERROR] [03/14/2018 09:43:07.791] [default-akka.actor.default-dispatcher-2] [RestartWithBackoffFlow(akka://default)] Restarting graph due to failure
java.lang.RuntimeException: FAIL!
	at jhowarth.RestartFlowTest$.$anonfun$failing$1(AkkaBug.scala:32)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:12)
	at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:53)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:732)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:726)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:667)
	at akka.actor.ActorCell.create(ActorCell.scala:654)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Creating flow
Failed - Cannot pull closed port (RestartWithBackoffFlow.in(549026988))
```

**Comment by julianhowarth** [comment]
After a little bit of investigation there are a couple of things to note:
- The message "Restarting graph due to failure" is generated from the `RestartWithBackoffLogic` class when **_upstream_** fails. However, it is downstream that we are interested in as it has thrown the exception.
- Looking further down there is the `onDownstreamFinish` method in the `subSourceOutlet`, which is the route by which I'd expect to get notification and graph restart (this is the route followed for the `RestartFlow.withBackoff` method).
- However, the if condition is:
```
        if (finishing || maxRestartsReached() || onlyOnFailures) {
          cancel(in)
        } else {
          log.debug("Graph in finished")
          scheduleRestartTimer()
        }
```
so whereas for the `withBackoff` method we get a restart, in the case for `onFailuresWithBackoff` we do not restart as `onlyOnFailures` is set to `true`. Given that either completion or an error will both lead to downstream cancelling, I can't see how the `onlyOnFailures` condition in the code above can work without more context as to what caused the cancellation.
