### ISSUE TITLE
Failed: akka.persistence.fsm.AbstractPersistentFSMTest

### ISSUE THREAD

**Issue by 2m** [akka/akka#24723]
Failed on Scala 2.12 community build.

```
[akka-more] [info] - testSuccessfulRecoveryWithCorrectStateData *** FAILED ***
[akka-more] [info]   java.lang.AssertionError: Expected: <[]>
[akka-more] [info]      but: was <[Item{id=1, name=38.99, price=Shirt}, Item{id=2, name=39.99, price=Shoes}]>
[akka-more] [info]   at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
[akka-more] [info]   at org.junit.Assert.assertThat(Assert.java:956)
[akka-more] [info]   at org.junit.Assert.assertThat(Assert.java:923)
[akka-more] [info]   at akka.persistence.fsm.AbstractPersistentFSMTest$3.<init>(AbstractPersistentFSMTest.java:163)
[akka-more] [info]   at akka.persistence.fsm.AbstractPersistentFSMTest.testSuccessfulRecoveryWithCorrectStateData(AbstractPersistentFSMTest.java:142)
[akka-more] [info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[akka-more] [info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[akka-more] [info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[akka-more] [info]   at java.lang.reflect.Method.invoke(Method.java:498)
[akka-more] [info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[akka-more] [info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[akka-more] [info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[akka-more] [info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[akka-more] [info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[akka-more] [info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[akka-more] [info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[akka-more] [info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[akka-more] [info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[akka-more] [info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[akka-more] [info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[akka-more] [info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[akka-more] [info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
```

https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2662/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk10/310/testReport/junit/akka.persistence.fsm/AbstractPersistentFSMTest/testSuccessfulRecoveryWithCorrectStateData/

**Comment by patriknw** [comment]
obsolete
