### ISSUE TITLE
HandshakeRestartReceiverSpec: Artery Handshake must detect restarted receiver and initiate new handshake

### ISSUE THREAD

**Issue by raboof** [akka/akka#24789]
https://jenkins.akka.io:8498/job/akka-nightly/5350/consoleFull
```
[info] * akka.remote.artery.HandshakeRestartReceiverSpec
[info] [JVM-2] [INFO] [03/25/2018 22:11:25.710] [ScalaTest-main] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://HandshakeRestartReceiverSpec)] Started embedded media driver in directory [/dev/shm/aeron-jenkinsakka-HandshakeRestartReceiverSpec-dc360ddb-86a3-4350-9724-b0f3f123c981]
[info] [JVM-1] [INFO] [03/25/2018 22:11:25.779] [ScalaTest-main] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://HandshakeRestartReceiverSpec)] Started embedded media driver in directory [/dev/shm/aeron-jenkinsakka-HandshakeRestartReceiverSpec-42b35018-783d-42cf-8337-23a469a03c2f]
[info] [JVM-2] [INFO] [03/25/2018 22:11:25.929] [ScalaTest-main] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://HandshakeRestartReceiverSpec)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://HandshakeRestartReceiverSpec@localhost:35650] with UID [2003068454782805500]
[info] [JVM-1] [INFO] [03/25/2018 22:11:26.004] [ScalaTest-main] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://HandshakeRestartReceiverSpec)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://HandshakeRestartReceiverSpec@localhost:55543] with UID [-1915231115652925742]
[info] [JVM-1] [INFO] [03/25/2018 22:11:27.101] [ScalaTest-main] [HandshakeRestartReceiverSpecMultiJvmNode1(akka://HandshakeRestartReceiverSpec)] Role [first] started with address [akka://HandshakeRestartReceiverSpec@localhost:55543]
[info] [JVM-2] [INFO] [03/25/2018 22:11:27.171] [ScalaTest-main] [HandshakeRestartReceiverSpecMultiJvmNode2(akka://HandshakeRestartReceiverSpec)] Role [second] started with address [akka://HandshakeRestartReceiverSpec@localhost:35650]
[info] [JVM-1] HandshakeRestartReceiverSpecMultiJvmNode1:
[info] [JVM-1] Artery Handshake
[info] [JVM-2] HandshakeRestartReceiverSpecMultiJvmNode2:
[info] [JVM-2] Artery Handshake
[info] [JVM-2] [INFO] [03/25/2018 22:11:28.005] [HandshakeRestartReceiverSpec-akka.remote.default-remote-dispatcher-8] [akka://HandshakeRestartReceiverSpec@localhost:35650/system/remoting-terminator] Shutting down remote daemon.
[info] [JVM-2] [INFO] [03/25/2018 22:11:28.009] [HandshakeRestartReceiverSpec-akka.remote.default-remote-dispatcher-8] [akka://HandshakeRestartReceiverSpec@localhost:35650/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[info] [JVM-2] - must detect restarted receiver and initiate new handshake (on node 'second', class akka.remote.artery.HandshakeRestartReceiverSpecMultiJvmNode2) *** FAILED *** (10 seconds, 544 milliseconds)
[info] [JVM-2]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info] [JVM-2]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info] [JVM-2]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[info] [JVM-2]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info] [JVM-2]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info] [JVM-2]   at scala.concurrent.Await$.result(package.scala:190)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$4.apply$mcV$sp(HandshakeRestartReceiverSpec.scala:105)
[info] [JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:370)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HandshakeRestartReceiverSpec.scala:101)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HandshakeRestartReceiverSpec.scala:67)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HandshakeRestartReceiverSpec.scala:67)
[info] [JVM-2]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-2]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [JVM-2]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info] [JVM-2]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.withFixture(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info] [JVM-2]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info] [JVM-2]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.runTest(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info] [JVM-2]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info] [JVM-2]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info] [JVM-2]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-2]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info] [JVM-2]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info] [JVM-2]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info] [JVM-2]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info] [JVM-2]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-2]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info] [JVM-2]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info] [JVM-2]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info] [JVM-2]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.runTests(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.org$scalatest$WordSpecLike$$super$run(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info] [JVM-2]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info] [JVM-2]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info] [JVM-2]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.org$scalatest$BeforeAndAfterAll$$super$run(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info] [JVM-2]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info] [JVM-2]   at akka.remote.artery.HandshakeRestartReceiverSpec.run(HandshakeRestartReceiverSpec.scala:46)
[info] [JVM-2]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
[info] [JVM-2]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
[info] [JVM-2]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
[info] [JVM-2]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-2]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
[info] [JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
[info] [JVM-2]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
[info] [JVM-2]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
[info] [JVM-2]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
[info] [JVM-2]   at org.scalatest.tools.Runner$.main(Runner.scala:827)
[info] [JVM-2]   at org.scalatest.tools.Runner.main(Runner.scala)
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[error] [JVM-2] Timeout waiting for agent '[sender,receiver]' to close, Retrying...
[info] [JVM-2] Failed to stop [HandshakeRestartReceiverSpec] within [15 seconds] 
[info] [JVM-2] -> / LocalActorRefProvider$$anon$1 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
[info] [JVM-2]    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 9 children
[info] [JVM-2]        ⌊-> StreamSupervisor-0 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info] [JVM-2]        ⌊-> StreamSupervisor-1 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info] [JVM-2]        ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
[info] [JVM-2]        ⌊-> eventStreamUnsubscriber-1 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[info] [JVM-2]        ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
[info] [JVM-2]        ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
[info] [JVM-2]        ⌊-> remote-watcher RepointableActorRef class akka.remote.RemoteWatcher status=0 no children
[info] [JVM-2]        ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[info] [JVM-2]        ⌊-> testActor-1 RepointableActorRef class akka.testkit.TestActor status=0 no children
```

**Comment by chbatey** [comment]
Looks to have been Aeron failing to shut down causing the Akka system to not shut down.

We get this logged to stderr multiple times:

```
https://github.com/real-logic/agrona/blame/master/agrona/src/main/java/org/agrona/concurrent/AgentRunner.java#L214
```

Which looks be be that Aeron couldn't shut down one of its threads. No more info on why.

**Comment by chbatey** [comment]
We haven't seen Aeron unable to shut down its thread again and we've upgraded 2 Aeron versions so closing this unless it happens again.
