### ISSUE TITLE
Typed PersistentBehavior building stack (new impl)

### ISSUE THREAD

**Issue by patriknw** [akka/akka#24787]
Noticed some weird stack traces. Looks like it grows the stack for each persisted event. Marking as bug since we must fix this before releasing next.

After one persisted event:
```
	at akka.persistence.typed.scaladsl.PerformanceSpec$$anonfun$eventSourcedTestPersistenceBehavior$1$$anonfun$apply$2.apply$mcV$sp(PerformanceSpec.scala:89)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffect(EventsourcedRunning.scala:305)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffects(EventsourcedRunning.scala:292)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onWriteResponse$1(EventsourcedRunning.scala:209)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onJournalResponse(EventsourcedRunning.scala:216)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:183)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:171)
	at akka.actor.typed.scaladsl.MutableBehavior.receive(MutableBehavior.scala:23)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:173)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Widened.receive(BehaviorImpl.scala:52)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.Supervisor.receive(Restarter.scala:96)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:64)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:60)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:19)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

After 5 events:
```
	at akka.persistence.typed.scaladsl.PerformanceSpec$$anonfun$eventSourcedTestPersistenceBehavior$1$$anonfun$apply$2.apply$mcV$sp(PerformanceSpec.scala:89)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffect(EventsourcedRunning.scala:305)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffects(EventsourcedRunning.scala:292)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onWriteResponse$1(EventsourcedRunning.scala:209)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onJournalResponse(EventsourcedRunning.scala:216)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:183)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:171)
	at akka.actor.typed.scaladsl.MutableBehavior.receive(MutableBehavior.scala:23)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:173)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Widened.receive(BehaviorImpl.scala:52)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.Supervisor.receive(Restarter.scala:96)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:64)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:60)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:19)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

After 10 events:
```
akka.testkit.typed.TE: boom
	at akka.persistence.typed.scaladsl.PerformanceSpec$$anonfun$eventSourcedTestPersistenceBehavior$1$$anonfun$apply$2.apply$mcV$sp(PerformanceSpec.scala:89)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.scaladsl.Effect$$anonfun$andThen$1.apply(Effect.scala:73)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffect(EventsourcedRunning.scala:305)
	at akka.persistence.typed.internal.EventsourcedRunning.applySideEffects(EventsourcedRunning.scala:292)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onWriteResponse$1(EventsourcedRunning.scala:209)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onJournalResponse(EventsourcedRunning.scala:216)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:183)
	at akka.persistence.typed.internal.EventsourcedRunning$PersistingEvents.onMessage(EventsourcedRunning.scala:171)
	at akka.actor.typed.scaladsl.MutableBehavior.receive(MutableBehavior.scala:23)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:173)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Widened.receive(BehaviorImpl.scala:52)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.Supervisor.receive(Restarter.scala:96)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:64)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:60)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:19)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
The problem is that we use `withMdc` for each behavior change, also when switching between handlingCommands-persistingEvents. Each such adds to the wrapped behaviors.

The initial withMdc wraps are also kept.

I'll rework the `withMdc` stuff in persistence.

**Comment by johanandren** [comment]
Isn't this already solved in #24729 which removes previous withMdc when you wrap with a new one?

**Comment by patriknw** [comment]
ok, I'll verify that

**Comment by patriknw** [comment]
it's fixed by https://github.com/akka/akka/pull/24729
I'll work on the improvements for persistence anyway
