### ISSUE TITLE
FAILED: ArteryMessageLoggingSpec

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24865]
https://jenkins.akka.io:8498/job/akka-artery-tcp-remote-tests/42/testReport/akka.remote/ArteryMessageLoggingSpec/Message_logging_must_not_be_on_if_debug_logging_not_enabled/

Error Message

java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity

```
Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
	at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:482)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
	at akka.remote.MessageLoggingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(MessageLoggingSpec.scala:62)
	at akka.remote.MessageLoggingSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(MessageLoggingSpec.scala:58)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:60)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:60)
```

**Comment by ktoso** [comment]
Was likely already fixed, the email about this failure was old.

https://github.com/akka/akka/pull/24837
