### ISSUE TITLE
Cannot wrap PersistentBehavior in Behaviors.tap

### ISSUE THREAD

**Issue by pawelkaczor** [akka/akka#24915]
Tested with Akka 2.5.12:

```
java.lang.ClassCastException: akka.persistence.RecoveryPermitter$RecoveryPermitGranted$ cannot be cast to mypackage.JobScheduleCommand
	at akka.actor.typed.javadsl.Behaviors$.$anonfun$tap$1(Behaviors.scala:179)
	at akka.actor.typed.javadsl.Behaviors$.$anonfun$tap$1$adapted(Behaviors.scala:179)
	at akka.actor.typed.internal.BehaviorImpl$.$anonfun$tap$1(BehaviorImpl.scala:94)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:163)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:341)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:64)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:60)```

**Comment by patriknw** [comment]
Thanks, will look into it. Inthe meantime the workaround is to not combine tap and PersistentBehavior
