### ISSUE TITLE
Failed: ClusterClientHandoverSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24959]
https://jenkins.akka.io:8498/job/akka-nightly/5409/consoleFull

```
[info] [JVM-3] - should remove first node from the cluster (on node 'second', class akka.cluster.client.ClusterClientHandoverMultiJvmNode3) *** FAILED ***
[info] [JVM-3]   2 did not equal 1 (ClusterClientHandoverSpec.scala:58)
[info] [JVM-1] [ERROR] [04/14/2018 04:51:02.931] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-4] [akka://ClusterClientHandoverSpec/user/controller/barriers] RoleName(second) tried to enter 'handover-successful' while we were waiting for 'handover-done' (akka.remote.testconductor.BarrierCoordinator$WrongBarrier: RoleName(second) tried to enter 'handover-successful' while we were waiting for 'handover-done')
[info] [JVM-3] - should re-establish on receptionist shutdown (on node 'second', class akka.cluster.client.ClusterClientHandoverMultiJvmNode3) *** FAILED ***
[info] [JVM-3]   java.lang.RuntimeException: barrier failed: handover-successful
[info] [JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:221)
[info] [JVM-3]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:196)
[info] [JVM-3]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[info] [JVM-3]   at akka.actor.FSM$class.processEvent(FSM.scala:670)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5415/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/552/consoleFull
