### ISSUE TITLE
Failed: StreamTestKitSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#24956]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/545/testReport/junit/akka.stream.testkit/StreamTestKitSpec/A_TestSink_Probe_must__expectNextWithTimeoutPF_should_fail_after_timeout_when_element_delayed/

```
Expected exception java.lang.AssertionError to be thrown, but no exception was thrown
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
	at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:60)
	at org.scalatest.Assertions.intercept(Assertions.scala:822)
	at org.scalatest.Assertions.intercept$(Assertions.scala:802)
	at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:60)
	at akka.stream.testkit.StreamTestKitSpec.$anonfun$new$23(StreamTestKitSpec.scala:146)
	at akka.stream.testkit.StreamTestKitSpec$$Lambda$377/919291663.apply(Unknown Source)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/623/testReport/junit/akka.stream.testkit/StreamTestKitSpec/A_TestSink_Probe_must__expectNextChainingPF_should_fail_after_timeout_when_element_delayed/

**Comment by chbatey** [comment]
This was a different test failure, my mistake
