### ISSUE TITLE
Flaky wireTap test

### ISSUE THREAD

**Issue by ktoso** [akka/akka#24979]
Seems this spec is a bit flaky, https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/12416/testReport/junit/akka.stream.scaladsl/FlowWireTapSpec/A_wireTap_must_call_the_procedure_for_each_element/

A bit weird why... 

```
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 3

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 3
	at scala.Predef$.assert(Predef.scala:170)
	at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
	at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
	at akka.stream.scaladsl.FlowWireTapSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(FlowWireTapSpec.scala:25)
	at akka.stream.scaladsl.FlowWireTapSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcI$sp$1.apply(FlowWireTapSpec.scala:21)
	at akka.stream.scaladsl.FlowWireTapSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcI$sp$1.apply(FlowWireTapSpec.scala:21)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:29)
	at akka.stream.scaladsl.FlowWireTapSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcI$sp(FlowWireTapSpec.scala:21)
	at akka.stream.scaladsl.FlowWireTapSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(FlowWireTapSpec.scala:21)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.12/553/testReport/junit/akka.stream.scaladsl/FlowWireTapSpec/A_wireTap_must_call_the_procedure_for_each_element/

**Comment by ktoso** [comment]
See fix PR please so we can avoid the failure popping up in PRs
