### ISSUE TITLE
Failed: TestFSMRefSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25049]
https://jenkins.akka.io:8498/job/akka-nightly/5467/consoleFull

```
[info] A TestFSMRef
[info] - must allow access to state data *** FAILED *** (1 second, 415 milliseconds)
Coroner Thread Count started at 12, ended at 11, peaked at 14 in akka.testkit.TestFSMRefSpec
[info]   java.lang.AssertionError: assertion failed: block took 960.088 milliseconds, exceeding 500.000 milliseconds
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.within(TestKit.scala:365)
[info]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info]   at akka.testkit.TestFSMRefSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TestFSMRefSpec.scala:39)
[info]   at akka.testkit.TestFSMRefSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestFSMRefSpec.scala:16)
[info]   at akka.testkit.TestFSMRefSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestFSMRefSp
```

**Comment by patriknw** [comment]
obsolete
