### ISSUE TITLE
Log error message printed to stdout despite mute filter

### ISSUE THREAD

**Issue by dotta** [akka/akka#25057]
Using Akka version 2.5.11.

Have `akka.loggers = ["akka.testkit.TestEventListener"]` set in the `application.conf` and, before executing a test, do `system.eventStream.publish(TestEvent.Mute(EventFilter.error()))`.

With this setup, I expect all calls to `log.error` to be muted. However, what I'm actually seeing is that calls to `log.error(msg)` are correctly muted, while calls to `log.error(cause, msg)` are not (!).

Below is the stacktrace for the `log.error(cause, msg)` call

```
at akka.event.Logging$StdOutLogger.print(Logging.scala:890)
	  at akka.event.Logging$StdOutLogger.print$(Logging.scala:889)
	  at akka.event.Logging$DefaultLogger.print(Logging.scala:1021)
	  at akka.testkit.TestEventListener$$anonfun$receive$1.applyOrElse(TestEventListener.scala:506)
	  at akka.actor.Actor.aroundReceive(Actor.scala:517)
	  at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	  at akka.event.Logging$DefaultLogger.aroundReceive(Logging.scala:1021)
	  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	  at akka.actor.ActorCell.invoke(ActorCell.scala:559)
	  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	  at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

and this codepath is not hit when calling `log.error(msg)`.

Let me know if you can't pinpoint the issue and I should have some time next week to create a full reproducible

**Comment by raboof** [comment]
`EventFilter.error()` indeed only matches errors without a cause (https://doc.akka.io/api/akka/current/akka/testkit/EventFilter$.html#error(message:String,source:String,start:String,pattern:String,occurrences:Int):akka.testkit.EventFilter). For filtering errors with causes, use `EventFilter[CauseType]()`.

I can see how this can be surprising/confusing though. How could we make this more obvious?

**Comment by dotta** [comment]
Hey @raboof, thanks a lot, I'll use `EventFilter[CauseType]()` then!

> I can see how this can be surprising/confusing though. How could we make this more obvious?

From a user perspective, I feel it would be better to have a way to express "I **really** want to mute all logging, no matter what". Otherwise, every time I add code that may be logging with a `cause` I have to remember to update the testing code (and I bet I'll easily forget to do it :)).

**Comment by patriknw** [comment]
I agree that it would be better if that case muted all errors. Would you be able to create a pull request @dotta ?

**Comment by dotta** [comment]
@patriknw Here you go >> https://github.com/akka/akka/pull/25125
