### ISSUE TITLE
Multi-node ClusterDeathWatchSpec

### ISSUE THREAD

**Issue by raboof** [akka/akka#25065]
https://jenkins.akka.io:8498/job/akka-nightly/5472/consoleFull

Perhaps related to #19383, #24043 (but not identical)

```
[info] [JVM-3] [INFO] [05/05/2018 04:32:49.444] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:37043] - Shutting down myself
[info] [JVM-3] [INFO] [05/05/2018 04:32:49.445] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:37043] - Shutting down...
[info] [JVM-3] [INFO] [05/05/2018 04:32:49.446] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:37043] - Successfully shut down
[info] [JVM-4] [INFO] [05/05/2018 04:32:49.585] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-21] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:44661] - Trying to join [akka.tcp://ClusterDeathWatchSpec@localhost:39335] when already part of a cluster, ignoring
[info] [JVM-3] [WARN] [05/05/2018 04:32:49.606] [ClusterDeathWatchSpec-akka.remote.default-remote-dispatcher-23] [akka.tcp://ClusterDeathWatchSpec@localhost:37043/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FClusterDeathWatchSpec%40localhost%3A44661-3] Association with remote system [akka.tcp://ClusterDeathWatchSpec@localhost:44661] has failed, address is now gated for [5000] ms. Reason: [Disassociated] 
[info] [JVM-1] [INFO] [05/05/2018 04:32:49.621] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:39335] - Node [akka.tcp://ClusterDeathWatchSpec@localhost:35595] is JOINING, roles [dc-default]
[info] [JVM-5] [INFO] [05/05/2018 04:32:49.655] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:35595] - Welcome from [akka.tcp://ClusterDeathWatchSpec@localhost:39335]
[info] [JVM-1] [INFO] [05/05/2018 04:32:49.780] [ClusterDeathWatchSpec-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://ClusterDeathWatchSpec)] Cluster Node [akka.tcp://ClusterDeathWatchSpec@localhost:39335] - Leader is moving node [akka.tcp://ClusterDeathWatchSpec@localhost:35595] to [Up]
[info] [JVM-4] - must be able to watch actor before node joins cluster, ClusterRemoteWatcher takes over from RemoteWatcher (on node 'fourth', class akka.cluster.ClusterDeathWatchMultiJvmNode4) *** FAILED *** (19 seconds, 947 milliseconds)
[info] [JVM-4]   Some(akka.tcp://ClusterDeathWatchSpec@localhost:35595) did not equal Some(akka.tcp://ClusterDeathWatchSpec@localhost:37043) (MultiNodeClusterSpec.scala:314)
[info] [JVM-4]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-4]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info] [JVM-4]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$7.apply(MultiNodeClusterSpec.scala:314)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1$$anonfun$apply$7.apply(MultiNodeClusterSpec.scala:314)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:312)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:329)
[info] [JVM-4]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:314)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$$anonfun$awaitMembersUp$1.apply(MultiNodeClusterSpec.scala:305)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:360)
[info] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:374)
[info] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.awaitMembersUp(MultiNodeClusterSpec.scala:305)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.awaitMembersUp(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.awaitClusterUp(MultiNodeClusterSpec.scala:227)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.awaitClusterUp(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply$mcV$sp(ClusterDeathWatchSpec.scala:172)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(ClusterDeathWatchSpec.scala:150)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9$$anonfun$apply$mcV$sp$10.apply(ClusterDeathWatchSpec.scala:150)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:360)
[info] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-4]   at akka.testkit.TestKitBase$class.within(TestKit.scala:374)
[info] [JVM-4]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply$mcV$sp(ClusterDeathWatchSpec.scala:150)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(ClusterDeathWatchSpec.scala:150)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec$$anonfun$1$$anonfun$apply$mcV$sp$9.apply(ClusterDeathWatchSpec.scala:150)
[info] [JVM-4]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-4]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [JVM-4]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [JVM-4]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info] [JVM-4]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.akka$cluster$MultiNodeClusterSpec$$super$withFixture(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at akka.cluster.MultiNodeClusterSpec$class.withFixture(MultiNodeClusterSpec.scala:187)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.withFixture(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info] [JVM-4]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info] [JVM-4]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.runTest(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-4]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info] [JVM-4]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info] [JVM-4]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-4]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info] [JVM-4]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info] [JVM-4]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info] [JVM-4]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.runTests(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.org$scalatest$WordSpecLike$$super$run(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info] [JVM-4]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info] [JVM-4]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info] [JVM-4]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.org$scalatest$BeforeAndAfterAll$$super$run(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info] [JVM-4]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info] [JVM-4]   at akka.cluster.ClusterDeathWatchSpec.run(ClusterDeathWatchSpec.scala:43)
[info] [JVM-4]   at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
[info] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
[info] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
[info] [JVM-4]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-4]   at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
[info] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
[info] [JVM-4]   at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
[info] [JVM-4]   at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
[info] [JVM-4]   at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
[info] [JVM-4]   at org.scalatest.tools.Runner$.main(Runner.scala:827)
[info] [JVM-4]   at org.scalatest.tools.Runner.main(Runner.scala)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5494/consoleFull
