### ISSUE TITLE
StreamRef Serialization error: java.lang.NoClassDefFoundError: akka/serialization/Serializers$

### ISSUE THREAD

**Issue by erkinun** [akka/akka#25116]
I have been trying to use StreamRef in our Akka Cluster + Akka Http application. 
Akka version 2.5.9
Akka Stream version 2.5.12 

I create a `Source` from an File Iterator then convert it to a `SourceRef` using `source.runWith(StreamRefs.sourceRef())` and send the reply back to the sender. When I execute the application in a cluster, I got the following exception when a message is sent between the specified actors:

```
[error] java.lang.NoClassDefFoundError: akka/serialization/Serializers$
[error] 	at akka.stream.serialization.StreamRefSerializer.serializeSequencedOnNext(StreamRefSerializer.scala:108)
[error] 	at akka.stream.serialization.StreamRefSerializer.toBinary(StreamRefSerializer.scala:47)
[error] 	at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:47)
[error] 	at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:898)
[error] 	at akka.remote.EndpointWriter$$anonfun$serializeMessage$1.apply(Endpoint.scala:898)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:897)
[error] 	at akka.remote.EndpointWriter.writeSend(Endpoint.scala:788)
[error] 	at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:763)
[error] 	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
[error] 	at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:454)
[error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
[error] 	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:496)
[error] 	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
[error] 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
[error] 	at akka.kamon.instrumentation.ActorMonitors$TrackedActor$$anonfun$processMessage$2.apply(ActorMonitor.scala:88)
[error] 	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
[error] 	at akka.kamon.instrumentation.ActorMonitors$TrackedActor.processMessage(ActorMonitor.scala:87)
[error] 	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
[error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:489)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: java.lang.ClassNotFoundException: akka.serialization.Serializers$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Also during the startup of the application, these error lines are printed as well: 

```
[error] [AppClassLoader@18b4aac2] error can't determine superclass of missing type akka.serialization.Serializers$
[error] when weaving type akka.stream.serialization.StreamRefSerializer
[error] when weaving classes
[error] when weaving
[error]  [Xlint:cantFindType]
[error] [AppClassLoader@18b4aac2] error can't determine superclass of missing type akka.serialization.Serializers$
[error] when weaving type akka.stream.serialization.StreamRefSerializer
[error] when weaving classes
[error] when weaving
[error]  [Xlint:cantFindType]
[error] [AppClassLoader@18b4aac2] error can't determine whether missing type akka.serialization.Serializers$ is an instance of akka.pattern.AskableActorRef$
[error] when weaving type akka.stream.serialization.StreamRefSerializer
[error] when weaving classes
[error] when weaving
[error]  [Xlint:cantFindType]
```

We are using kryo and protobuf as serializers: 

```
serializers {
      kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
      protobuf = "akka.remote.serialization.ProtobufSerializer"
    }
```

Can you please let me know If I'm doing something wrong?

**Comment by ktoso** [comment]
What is doing the weaving? Does it work without whatever does the weaving?

**Comment by patriknw** [comment]
First, you must use the same version of the Akka modules. 2.5.12 for both akka-stream and other modules such as akka-cluster.

**Comment by erkinun** [comment]
Both errors are gone after I bumped the version of akka modules to 2.5.12. Thank you guys for your input. Maybe this should be discussed in the documentation somehow? https://doc.akka.io/docs/akka/current/stream/stream-refs.html

**Comment by patriknw** [comment]
Perhaps it's not the first page you would look at, but it's mentioned here: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
