### ISSUE TITLE
RemoveInternalClusterShardingData fails when persistence data is corrupted

### ISSUE THREAD

**Issue by e-kolpakov** [akka/akka#25124]
Looks like `RemoveInternalClusterShardingData` fails when persistence data is corrupted in one particular way - when it expects more messages than persisted in Cassandra (I have no idea how I achieved it, but last thing I did before corrupting it is to restart three entire cluster at the same time)

Invocation (redacted to omit gory details): `java -cp conf/application.conf  lib/* akka.cluster.sharding.RemoveInternalClusterShardingData Shift`

```
18-05-22T04:34:47.322 ERROR spatcher-5 a.c.s.RemoveInternalClusterShardingData$RemoveOnePersistenceId - Persistence failure when replaying events for persistenceId [/sharding/ShiftCoordinator]. Last known sequence number [60600]
java.lang.IllegalStateException: Sequence number [60401] still missing after [10.00 s], saw unexpected seqNr [60501] for persistenceId [/sharding/ShiftCoordinator].
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.lookForMissingSeqNr(EventsByPersistenceIdStage.scala:329)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.onTimer(EventsByPersistenceIdStage.scala:309)
	at akka.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1474)
	at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1463)
	at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1463)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:454)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18-05-22T04:34:47.325 ERROR spatcher-6 a.c.s.RemoveInternalClusterShardingData - Failed to remove data for persistenceId [/sharding/ShiftCoordinator], unexpected termination
[ERROR] [05/22/2018 04:34:47.325] [RemoveInternalClusterShardingData-akka.actor.default-dispatcher-5] [akka.tcp://RemoveInternalClusterShardingData@1.transport-capacity-service.service.redmart:2551/user/removeInternalClusterShardingData] Failed to remove data for persistenceId [/sharding/ShiftCoordinator], unexpected termination
```

**Comment by patriknw** [comment]
Can you try to set this config property when running RemoveInternalClusterShardingData:

```
cassandra-query-journal.gap-free-sequence-numbers = off
```

https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/resources/reference.conf#L576

Remove it again after the RemoveInternalClusterShardingData job.

If that works then we could set that property in the RemoveInternalClusterShardingData by default.

What happens is that there are some missing events and therefore the actor that is supposed to remove all events and snapshots can't recover.

**Comment by johanandren** [comment]
Good to hear! Let's close this then if it was resolved.
