### ISSUE TITLE
NullPointerException thrown in akka.stream.impl.io.OutputStreamSourceStage

### ISSUE THREAD

**Issue by longshorej** [akka/akka#25159]
Observed this "in the wild" - I think that there's a race with `blockingThread` here: https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/OutputStreamSourceStage.scala#L106-L143

L126 can execute between L139 and L140, throwing `NullPointerException`. I think a fix could be simply ignoring the exception, i.e.

```scala
if (blockingThread != null)
  try {
    blockingThread.interrupt()
    } catch {
      case _: NullPointerException ⇒ // ignore - there's a small chance of race between checking for null and calling interrupt

    }
```

If that sounds good, I'll be happy to provide a PR.

```
Error during postStop in [akka.stream.impl.io.OutputStreamSourceStage@21a712d9]: null
java.lang.NullPointerException: null
	at akka.stream.impl.io.OutputStreamSourceStage$OutputStreamSourceLogic$1.postStop(OutputStreamSourceStage.scala:140)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:467)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by johanandren** [comment]
I think it should be replaced by an atomic ref instead and do CAS and be "correct" rather than workaround NPEs, the current version is not safe since the field isn't volatile and is accessed from multiple threads.

**Comment by longshorej** [comment]
Thanks @johanandren - I created https://github.com/akka/akka/pull/25166 based on your suggestion.

**Comment by ktoso** [comment]
Please mark with tags @johanandren when triagign
