### ISSUE TITLE
failed: JoinConfigCompatCheckerSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25157]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1355

```
[info] - must NOT be allowed to re-join a cluster when one of the cluster required properties are not available on the joining side *** FAILED *** (4 seconds, 255 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 3 seconds expired: awaiting node [akka://JoinConfigCompatCheckerSpec@127.0.1.1:56162] to be 'Removed'
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.poll$1(TestKit.scala:280)
[info]   at akka.testkit.TestKitBase$class.awaitCond(TestKit.scala:286)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:896)
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.quitAndRestart(ClusterTestKit.scala:116)
[info]   at akka.cluster.JoinConfigCompatCheckerSpec$$anonfun$2$$anonfun$apply$mcV$sp$22.apply(JoinConfigCompatCheckerSpec.scala:429)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1243/testReport/junit/akka.cluster/JoinConfigCompatCheckerSpec/A_Joining_Node_must_be_allowed_to_join_a_cluster_when_its_configuration_is_compatible/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3051/testReport/junit/akka.cluster/JoinConfigCompatCheckerSpec/A_Joining_Node_must_be_allowed_to_join_a_cluster_when_its_configuration_is_compatible/

**Comment by patriknw** [comment]
obsolete
