### ISSUE TITLE
Cluster sharding must log useful error message if sharding not started

### ISSUE THREAD

**Issue by raboof** [akka/akka#25196]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1364/consoleFull

```
[info] [JVM-1] - must log useful error message if sharding not started (on node 'first', class akka.cluster.sharding.ClusterShardingIncorrectSetupMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: helpful error message logged
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:221)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:196)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[info] [JVM-1]   at akka.actor.FSM$class.processEvent(FSM.scala:670)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:156)
[info] [JVM-1]   at akka.actor.LoggingFSM$class.processEvent(FSM.scala:806)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:156)
[info] [JVM-1]   at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:664)
[info] [JVM-1]   at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
[info] [JVM-1]   at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
[info] [JVM-1]   ...
```

**Comment by chbatey** [comment]
Sorry i fixed this on friday without raising an issue: https://github.com/akka/akka/pull/25187
