### ISSUE TITLE
A cluster with multiple dc's must be able to have a data center member join while there is inter data center split

### ISSUE THREAD

**Issue by raboof** [akka/akka#25198]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6062/consoleFull

```
[info] [JVM-5] - must be able to have a data center member join while there is inter data center split (on node 'fifth', class akka.cluster.MultiDcSplitBrainMultiJvmNode5) *** FAILED *** (20 seconds, 50 milliseconds)
[info] [JVM-5]   java.lang.RuntimeException: barrier failed: after-unsplit-verified-1
[info] [JVM-5]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:221)
[info] [JVM-5]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:196)
[info] [JVM-5]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[info] [JVM-5]   at akka.actor.FSM$class.processEvent(FSM.scala:670)
[info] [JVM-5]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:156)
```

**Comment by chbatey** [comment]
This this is a duplicate of https://github.com/akka/akka/issues/24955

**Comment by raboof** [comment]
oh weird that my search didn't hit it, thx
