### ISSUE TITLE
Failed: FanInThroughputSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25257]
https://jenkins.akka.io:8498/job/akka-nightly/5605/consoleFull

```
[info] [JVM-3] - must be great for warmup, burstSize = 1000, payloadSize = 100 (on node 'node-3', class akka.remote.artery.FanInThroughputSpecMultiJvmNode3) *** FAILED *** (10 seconds, 354 milliseconds)
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:170)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:491)
[info] [JVM-3]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info] [JVM-3]   at akka.remote.artery.FanInThroughputSpec.identifyReceiver(FanInThrougputSpec.scala:97)
[info] [JVM-3]   at akka.remote.artery.FanInThroughputSpec$$anonfun$test$2$$anonfun$4.apply(FanInThrougputSpec.scala:157)
[info] [JVM-3]   at akka.remote.artery.FanInThroughputSpec$$anonfun$test$2$$anonfun$4.apply(FanInThrougputSpec.scala:156)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3294/consoleFull

Similar but not quite the same. Might just be a timeout issue.

```
[info] [JVM-1] [ERROR] [04/18/2019 10:31:12.599] [FanInThroughputSpec-akka.actor.default-dispatcher-4] [akka://FanInThroughputSpec/user/controller/barriers] timeout while waiting for barrier 'size-10k-done' (akka.remote.testconductor.BarrierCoordinator$BarrierTimeout: timeout while waiting for barrier 'size-10k-done')
[info] [JVM-1] - must be great for size-10k, burstSize = 1000, payloadSize = 10000 (on node 'node-1', class akka.remote.artery.FanInThroughputSpecMultiJvmNode1) *** FAILED *** (5 minutes, 0 seconds)
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: size-10k-done
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:241)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:215)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-1]   at akka.actor.FSM.processEvent(FSM.scala:707)
[info] [JVM-1]   at akka.actor.FSM.processEvent$(FSM.scala:704)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:168)
```
