### ISSUE TITLE
Typed persistence: ClassCastException for TimerMsg during recovery

### ISSUE THREAD

**Issue by svroonland** [akka/akka#25268]
Version 2.5.13

Shouldn't the timer have been cancelled already when entering the running state of a persistent actor?

```
akka.actor.typed.Behavior - Exception during recovery.  Last known sequence number [mmsi356068000] WARNING arguments left: 1
java.lang.ClassCastException: akka.actor.typed.internal.TimerSchedulerImpl$TimerMsg cannot be cast to vessel.VesselActor$Command
at akka.persistence.typed.internal.EventsourcedRunning.onCommand$1(EventsourcedRunning.scala:79)
at akka.persistence.typed.internal.EventsourcedRunning.$anonfun$handlingCommands$3(EventsourcedRunning.scala:161)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:80)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.Behavior$.interpretOne$1(Behavior.scala:357)
	at akka.actor.typed.Behavior$.interpretMessages(Behavior.scala:363)
	at akka.actor.typed.internal.StashBufferImpl.unstash(StashBufferImpl.scala:104)
	at akka.persistence.typed.internal.EventsourcedStashManagement.tryUnstash(EventsourcedStashManagement.scala:51)
	at akka.persistence.typed.internal.EventsourcedStashManagement.tryUnstash$(EventsourcedStashManagement.scala:46)
	at akka.persistence.typed.internal.EventsourcedReplayingEvents.tryUnstash(EventsourcedReplayingEvents.scala:53)
	at akka.persistence.typed.internal.EventsourcedReplayingEvents.onRecoveryCompleted(EventsourcedReplayingEvents.scala:167)
	at akka.persistence.typed.internal.EventsourcedReplayingEvents.onJournalResponse(EventsourcedReplayingEvents.scala:97)
	at akka.persistence.typed.internal.EventsourcedReplayingEvents.$anonfun$stay$1(EventsourcedReplayingEvents.scala:69)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:80)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:170)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receive(BehaviorImpl.scala:173)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.BehaviorImpl$Widened.receive(BehaviorImpl.scala:51)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.Supervisor.receive(Restarter.scala:95)
	at akka.actor.typed.internal.BackoffRestarter.receive(Restarter.scala:291)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:338)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:318)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:67)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:63)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:22)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by patriknw** [comment]
Thanks for reporting.

It's `cancelRecoveryTimer`, but this comes from the unstashing when switching to running.

**Comment by ktoso** [comment]
Will look into this then! (After a few more reviews I have to do today...)

**Comment by ktoso** [comment]
Hah, that is weird stacktrace formatting... Missed that it continues onwards quite a few lines.

**Comment by ktoso** [comment]
I did not find a nice way to solve it yet... Putting it back to the queue.
The main mystery to me is how that timer message ends up in the stash anwyay; only code paths to do so seem to me to be part of a well typed path so it should not end up there hm... Otherwise I would have expected the wrapped withTimers to always handle this issue, even if it came from the unstash. I was not able to reproduce the exact issue though, so I may be missing something silly..

**Comment by patriknw** [comment]
I have fixed this in https://github.com/akka/akka/pull/25319
