### ISSUE TITLE
Broken ivy cache on travis?

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25270]
Seen this a couple of times

```
[error] java.io.IOException: Error accessing /home/travis/.ivy2/cache/com.typesafe.akka/akka-stream_2.12/jars/akka-stream_2.12-2.5.6.jar
[error] 	at scala.reflect.io.FileZipArchive.scala$reflect$io$FileZipArchive$$openZipFile(ZipArchive.scala:140)
[error] 	at scala.reflect.io.FileZipArchive.x$2$lzycompute(ZipArchive.scala:177)
[error] 	at scala.reflect.io.FileZipArchive.x$2(ZipArchive.scala:174)
[error] 	at scala.reflect.io.FileZipArchive.allDirs$lzycompute(ZipArchive.scala:174)
[error] 	at scala.reflect.io.FileZipArchive.allDirs(ZipArchive.scala:174)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.findDirEntry(ZipArchiveFileLookup.scala:72)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.packages(ZipArchiveFileLookup.scala:33)
[error] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.packages$(ZipArchiveFileLookup.scala:30)
[error] 	at scala.tools.nsc.classpath.ZipAndJarClassPathFactory$ZipArchiveClassPath.packages(ZipAndJarFileLookupFactory.scala:42)
```

**Comment by johanandren** [comment]
Saw it in the PR validation of https://github.com/akka/akka/pull/25269

Have deleted the caches with travis-cli now and waiting to see if it helped.

**Comment by johanandren** [comment]
Seems like that did the trick!
