### ISSUE TITLE
`FileIO.fromPath` does not work on named pipes (FIFOs)

### ISSUE THREAD

**Issue by nathankleyn** [akka/akka#25328]
Hello!

Firstly, many thanks for all of the hard work you all do to create such an incredible project for the community to use!

I've hit a funny little edge case when using `FileIO.fromPath` - basically, it has a check called "isRegularFile" that prevents it from being used on a named pipe/FIFOs:

```scala
import akka.stream._
import akka.stream.scaladsl._

import akka.{ NotUsed, Done }
import akka.actor.ActorSystem
import akka.util.ByteString
import scala.concurrent._
import scala.concurrent.duration._
import java.nio.file.Paths

object AkkaFileIONamedPipe extends App {
  private implicit val system = ActorSystem("AkkaFileIONamedPipe")
  private implicit val materializer = ActorMaterializer()
  private implicit val ec = system.dispatcher

  FileIO.fromPath(Paths.get("/tmp/some-fifo")) // Create this file with `mkfifo /tmp/some-fifo`.
    .to(Sink.ignore)
    .run()
    .onComplete(_ ⇒ system.terminate())
}
```

Produces the following error:

```
java.lang.IllegalArgumentException: requirement failed: Path '/tmp/some-fifo' is not a regular file
	at scala.Predef$.require(Predef.scala:277)
	at akka.stream.impl.io.FileSource$$anon$1.preStart(IOSources.scala:76)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.create(ActorCell.scala:652)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I've published this example on GitHub at https://github.com/nathankleyn/akka-fileio-named-pipe, and you can see the failure on the TravisCI build at https://travis-ci.org/nathankleyn/akka-fileio-named-pipe/jobs/401798278#L634.

[The exception thrown comes from this `require` call in `FileIO#preStart`](https://github.com/akka/akka/blob/563c7fbcf0fcb374d414403900d620c8fac54d52/akka-stream/src/main/scala/akka/stream/impl/io/IOSources.scala#L76). I found some discussion of this on #24512 which appears to not have been resolved before the issue was closed.

I was wondering if it would ever be possible to allow this restriction to be lifted? I've currently resorted to using Scala's `io.Source` and Akka's `fromIterator` right now - but it feels a bit strange as named pipes/FIFOs ought to be able to be treated like files and I couldn't find any documented reason for the restriction. Anything I can do to help make it so? I'm at your disposal!

**Comment by giftig** [comment]
Looks like it was introduced in #21801; it's not specifically discussed either there or in the commit message. My guess would be `isRegularFile` was used there to assert that it's not a directory, and the behaviour you describe is an unintended side effect. It does also protect against inadvertently using other non-regular files such as devices, but that doesn't really seem necessary to me.

Maybe make a PR and ask for feedback? Should be a one-liner.

**Comment by raboof** [comment]
Looks unintended to me as well!

**Comment by nathankleyn** [comment]
Thanks @giftig and @raboof for the speedy replies! To that end, I've raised a PR at https://github.com/akka/akka/pull/25333, swapping the `isRegularFile` for `!isDirectory` and adding the appropriate tests.  👍

**Comment by syspulse** [comment]
It seems to be not working for me (tried with mulitple versions):

`Error during preStart in [FileSource(/tmp/adsb, 8192)]: Illegal seek
java.io.IOException: Illegal seek
        at java.base/sun.nio.ch.FileDispatcherImpl.seek0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.seek(FileDispatcherImpl.java:78)
        at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:361)
        at akka.stream.impl.io.FileSource$$anon$1.preStart(IOSources.scala:80)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`
