### ISSUE TITLE
failed: ReplicatorDeltaSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25342]
Possible regression introduced by https://github.com/akka/akka/pull/25315 ?

https://jenkins.akka.io:8498/job/akka-multi-node/2865

```
[info] [JVM-3] - must preserve causal consistency for None delta *** FAILED *** (5 seconds, 835 milliseconds)
[info] [JVM-3]   118 did not equal 122 (ReplicatorDeltaSpec.scala:343)
[info] [JVM-3]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-3]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info] [JVM-3]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$39$$anonfun$apply$11.apply(ReplicatorDeltaSpec.scala:343)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$39$$anonfun$apply$11.apply(ReplicatorDeltaSpec.scala:340)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:312)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:329)
[info] [JVM-3]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$39.apply(ReplicatorDeltaSpec.scala:340)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$39.apply(ReplicatorDeltaSpec.scala:340)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:360)
[info] [JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-3]   at akka.testkit.TestKitBase$class.within(TestKit.scala:374)
[info] [JVM-3]   at akka.testkit.TestKit.within(TestKit.scala:896)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply$mcV$sp(ReplicatorDeltaSpec.scala:339)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(ReplicatorDeltaSpec.scala:275)
[info] [JVM-3]   at akka.cluster.ddata.ReplicatorDeltaSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(ReplicatorDeltaSpec.scala:275)
```

**Comment by patriknw** [comment]
Ok, I see what's going on here. The test is relying on that deltas are not propagated when "missing delta", but the change was to immediately send the full state when receiving `DeltaNack` and then that assumption in the test doesn't hold. The problem is in the test, I'll see what to do about it.
