### ISSUE TITLE
Failed: ClusterShardingLeavingSpec (2.4 branch)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25355]
I wonder if something that has been fixed in the 2.5 branch.

https://jenkins.akka.io:8498/job/akka-release-2.4/590/consoleFull

```
[JVM-4] - must recover after leaving coordinator node *** FAILED ***
[JVM-4]   java.lang.RuntimeException: barrier failed: after-4
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:210)
[JVM-4]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:185)
[JVM-4]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
```

**Comment by johanandren** [comment]
Given that 2.4 is EOL, let's close this.
