### ISSUE TITLE
Failed: SurviveNetworkInstabilitySpec (artery)

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25425]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1474/consoleFull

```
[info] [JVM-6] - must heal after unreachable when ring is changed (on node 'sixth', class akka.cluster.SurviveNetworkInstabilityMultiJvmNode6) *** FAILED *** (59 seconds, 990 milliseconds)
[info] [JVM-6]   Set(akka://SurviveNetworkInstabilitySpec@a5.moxie:57703, akka://SurviveNetworkInstabilitySpec@a4.moxie:38227, akka://SurviveNetworkInstabilitySpec@a6.moxie:54593, akka://SurviveNetworkInstabilitySpec@a5.moxie:35650, akka://SurviveNetworkInstabilitySpec@a6.moxie:37815) did not equal Set(akka://SurviveNetworkInstabilitySpec@a5.moxie:57703, akka://SurviveNetworkInstabilitySpec@a6.moxie:54593, akka://SurviveNetworkInstabilitySpec@a5.moxie:35650, akka://SurviveNetworkInstabilitySpec@a6.moxie:37815) (SurviveNetworkInstabilitySpec.scala:97)
[info] [JVM-6]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-6]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info] [JVM-6]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6798)
[info] [JVM-6]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$assertUnreachable$1.apply(SurviveNetworkInstabilitySpec.scala:97)
[info] [JVM-6]   at akka.cluster.SurviveNetworkInstabilitySpec$$anonfun$assertUnreachable$1.apply(SurviveNetworkInstabilitySpec.scala:97)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6064/consoleFull

```
akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:45923 Up seen=false]
[info] [JVM-4] - must heal after unreachable when ring is changed (on node 'fourth', class akka.cluster.SurviveNetworkInstabilityMultiJvmNode4) *** FAILED *** (59 seconds, 939 milliseconds)
[info] [JVM-4]   Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:38061, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:43353, akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:45923) did not equal Set(akka.trttl.gremlin.tcp://SurviveNetworkInstabilitySpec@localhost:45923) (SurviveNetworkInstabilitySpec.scala:97)
[info] [JVM-4]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-4]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info] [JVM-4]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6804)
[info] [JVM-4]   at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$assertUnreachable$2(SurviveNetworkInstabilitySpec.scala:97)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/72/consoleFull
