### ISSUE TITLE
Behaviors.withTimers leaks and causes java.lang.StackOverflowError

### ISSUE THREAD

**Issue by nktpro** [akka/akka#25504]
This bug exists as of the latest `v2.5.14` release.

Switching behavior which involves `Behaviors.withTimers` will throw `java.lang.StackOverflowError` with a similar stack trace to this:

```
java.lang.StackOverflowError
........
         at akka.actor.typed.internal.BehaviorImpl$Intercept.receiveSignal(BehaviorImpl.scala:164)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:346)
	at akka.actor.typed.Behavior$.interpretSignal(Behavior.scala:327)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receiveSignal(BehaviorImpl.scala:164)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:346)
	at akka.actor.typed.Behavior$.interpretSignal(Behavior.scala:327)
	at akka.actor.typed.internal.BehaviorImpl$Intercept.receiveSignal(BehaviorImpl.scala:164)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:346)
	at akka.actor.typed.Behavior$.interpretSignal(Behavior.scala:327)
........
```

Here is a simplified and complete reproducer:

```
import akka.actor.typed.{Behavior, SupervisorStrategy}
import akka.actor.typed.scaladsl.Behaviors
import akka.actor.typed.scaladsl.adapter._
import akka.{actor => untyped}

import scala.concurrent.duration._

object AkkaTypedTimersStackOverflowReproducer {
  def stackOverflowReproducer(dieAt: Int, frequency: FiniteDuration): Behavior[Int] = Behaviors.setup[Int] { ctx =>
    def scheduling(i: Int): Behavior[Int] = Behaviors.withTimers[Int] { t =>
      t.startSingleTimer("foo", i, frequency)
      printing
    }

    def printing: Behavior[Int] =
      Behaviors
        .receiveMessage[Int] { i =>
          if (i == dieAt) throw new IllegalStateException("Just die here")
          else {
            ctx.log.debug(s"Got: $i")
            scheduling(i + 1)
          }
        }

    scheduling(1)
  }

  def main(args: Array[String]): Unit = {
    implicit val system: untyped.ActorSystem = untyped.ActorSystem()

    val reproducer = stackOverflowReproducer(dieAt = 2000, frequency = Duration.Zero)
    val supervised = Behaviors.supervise(reproducer).onFailure[IllegalStateException](SupervisorStrategy.restart)
    system.spawn(supervised, "bug")
  }
}
```

**Expected:** The same actor is restarted infinitely by the supervisor
**Actual:** Upon the first restart cycle, `java.lang.StackOverflowError` is thrown and the JVM exits 

As a reference, this version using `ctx.schedule(...)` instead of `Behavior.withTimers` works as expected.

```
def workingVersion(dieAt: Int, frequency: FiniteDuration): Behavior[Int] = Behaviors.setup[Int] { ctx =>
    def scheduling(i: Int): Behavior[Int] = {
      val cancellable = ctx.schedule(frequency, ctx.self, i)
      printing(cancellable)
    }

    def printing(cancellable: Cancellable): Behavior[Int] =
      Behaviors
        .receiveMessage[Int] { i =>
          if (i == dieAt) throw new IllegalStateException("Just die here")
          else {
            ctx.log.debug(s"Got: $i")
            scheduling(i + 1)
          }
        }
        .receiveSignal {
          case (_, s @ (PreRestart | PostStop)) =>
            ctx.log.info(s"Got signal: $s")
            cancellable.cancel()
            Behaviors.same
        }

    scheduling(1)
  }
```

**Comment by patriknw** [comment]
Thanks for reporting and for the reproducer. We had a similar thing for supervision in https://github.com/akka/akka/issues/25128

You should only grab the `TimerScheduler` via `Behaviors.withTimers` once at the top level, and not for each returned Behavior (for each message).

We'll see if we can do something to avoid this anyway.

**Comment by nktpro** [comment]
@patriknw thank you for the tips, using `Behaviors.withTimers` once at the top level fixed this use case.

However it's not always possible to do so if the actor's behavior is functionally composed from others that use `Behaviors.withTimers` from other parts of the code-base that we may not have control over. They're just some methods returning some `Behavior[T]` after-all. 

A proper fix to un-nest the calls similarly to the one for `Behaviors.supervise` would definitely still be needed.

**Comment by patriknw** [comment]
Here is a reproducer test to be added in TimerSpec:
```scala
"not grow stack when nesting withTimers" in {
      def next(n: Int, probe: ActorRef[Int]): Behavior[String] = Behaviors.withTimers { timers ⇒
        timers.startSingleTimer("key", "tick", 1.millis)
        Behaviors.receiveMessage { msg ⇒
          if (n == 20) {
            val e = new RuntimeException().fillInStackTrace()
            val frames = e.getStackTrace.length
            probe ! frames
            Behaviors.stopped
          } else {
            next(n + 1, probe)
          }
        }
      }

      val probe = TestProbe[Int]()
      spawn(next(0, probe.ref))
      probe.expectMessageType[Int] should be <= 10
    }
```

@johanandren another of your favorite topics :)
Wonder if we can do anything about this? Perhaps we have to rethink how timers or intercepting are implemented?

**Comment by johanandren** [comment]
Stealing this from you then @patriknw, main idea I have after thinking about it for a while is that we need to keep one decorator as it does the scheduled message filtering, but after the lambda has been called for a nested `withTimers` that instance should be possible to discard.
