### ISSUE TITLE
ClusterHandoverSpec: must re-establish on receptionist shutdown

### ISSUE THREAD

**Issue by raboof** [akka/akka#25582]
Perhaps related to #24959 

https://jenkins.akka.io:8498/job/akka-nightly/5842/consoleFull

```
[info] [JVM-2] [WARN] [09/06/2018 22:55:37.524] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-17] [akka://ClusterClientHandoverSpec/system/distributedPubSubMediator] received dead letter from Actor[akka://ClusterClientHandoverSpec/system/receptionist/akka.tcp%3A%2F%2FClusterClientHandoverSpec%40localhost%3A45309%2Fsystem%2FtestActor-1%231798125793#106207485]: Send(/user/testService,hello,true)
[info] [JVM-2] [WARN] [09/06/2018 22:55:37.534] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-19] [akka://ClusterClientHandoverSpec/system/receptionist] received dead letter from Actor[akka.tcp://ClusterClientHandoverSpec@localhost:45309/user/client1#-897218492]: GetContacts
[info] [JVM-1] [INFO] [09/06/2018 22:55:37.530] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-17] [akka.tcp://ClusterClientHandoverSpec@localhost:45309/user/client1] Receptionist [Actor[akka.tcp://ClusterClientHandoverSpec@localhost:37059/system/receptionist#-778287976]] is shutting down, reestablishing connection
[info] [JVM-1] [INFO] [09/06/2018 22:55:37.560] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-17] [akka.tcp://ClusterClientHandoverSpec@localhost:45309/user/client1] Connected to [akka.tcp://ClusterClientHandoverSpec@localhost:33925/system/receptionist]
[info] [JVM-2] [WARN] [09/06/2018 22:55:38.243] [ClusterClientHandoverSpec-akka.actor.default-dispatcher-19] [akka://ClusterClientHandoverSpec/system/cluster/core/daemon/heartbeatSender] received dead letter from Actor[akka://ClusterClientHandoverSpec/system/cluster/core/daemon/heartbeatSender#5670185]: ExpectedFirstHeartbeat(UniqueAddress(akka.tcp://ClusterClientHandoverSpec@localhost:33925,606783337))
[info] [JVM-1] - must re-establish on receptionist shutdown (on node 'client', class akka.cluster.client.ClusterClientHandoverSpecMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class java.lang.String
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:170)
[info] [JVM-1]   at akka.testkit.TestKitBase$class.expectMsgClass_internal(TestKit.scala:509)
[info] [JVM-1]   at akka.testkit.TestKitBase$class.expectMsgType(TestKit.scala:491)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info] [JVM-1]   at akka.cluster.client.ClusterClientHandoverSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$12.apply$mcV$sp(ClusterClientHandoverSpec.scala:105)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:370)
[info] [JVM-1]   at akka.cluster.client.ClusterClientHandoverSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply$mcV$sp(ClusterClientHandoverSpec.scala:103)
[info] [JVM-1]   at akka.cluster.client.ClusterClientHandoverSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(ClusterClientHandoverSpec.scala:102)
[info] [JVM-1]   at akka.cluster.client.ClusterClientHandoverSpec$$anonfun$1$$anonfun$apply$mcV$sp$11.apply(ClusterClientHandoverSpec.scala:102)
[info] [JVM-1]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-1]   ...
```

**Comment by patriknw** [comment]
obsolete, cluster client
