### ISSUE TITLE
Artery might load `CoordinatedShutdown` in the shutdown hook

### ISSUE THREAD

**Issue by raboof** [akka/akka#25592]
When `akka.jvm-shutdown-hooks` is enabled, Artery registers [a shutdown hook](https://github.com/akka/akka/blob/master/akka-remote/src/main/scala/akka/remote/artery/ArteryTransport.scala#L499) that hooks into Coordinated Shutdown. However, if Coordinated Shutdown hadn't been loaded before, this means it is started while the actor system is already terminated:

```
Exception in thread “Thread-15” java.util.concurrent.RejectedExecutionException: ActorSystem already terminated.
    at akka.actor.ActorSystemImpl$TerminationCallbacks.addRec$1(ActorSystem.scala:1021)
    at akka.actor.ActorSystemImpl$TerminationCallbacks.add(ActorSystem.scala:1025)
    at akka.actor.ActorSystemImpl.registerOnTermination(ActorSystem.scala:844)
    at akka.actor.ActorSystemImpl.registerOnTermination(ActorSystem.scala:843)
    at akka.actor.CoordinatedShutdown$.createExtension(CoordinatedShutdown.scala:165)
    at akka.actor.CoordinatedShutdown$.createExtension(CoordinatedShutdown.scala:36)
    at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
    at akka.actor.ExtensionId.apply(Extension.scala:79)
    at akka.actor.ExtensionId.apply$(Extension.scala:78)
    at akka.actor.CoordinatedShutdown$.apply(CoordinatedShutdown.scala:36)
    at akka.remote.artery.ArteryTransport$$anon$1.run(ArteryTransport.scala:499)
```

**Comment by raboof** [comment]
This stack trace was taken on Akka v2.5.14

**Comment by patriknw** [comment]
Do you know how to reproduce and could do that with my PR?

**Comment by raboof** [comment]
It seems `RemoteActorRefProvider` is initialized even before the 'eager', and starts the `ArteryTransport`. From the stacktrace it looks like the `ArteryTransport` then calls its `shutdownHook` even before `CoordinatedShutdown` is 'eagerly' loaded, but also the `terminationFuture` was already triggered. I haven't quite traced back how/when that happens, though.

**Comment by patriknw** [comment]
Yes, that was my conclusion as well. provider and transport is initialized before that eager init. Kill in that window. I think my catch solves that scenario.
