### ISSUE TITLE
cleanup test log output in Typed tests

### ISSUE THREAD

**Issue by patriknw** [akka/akka#25597]
Let's try to cleanup and keep the test output green and without noise in Typed tests. Use `EventFilter.intercept`.

Related to https://github.com/akka/akka/issues/24348 but we can use untyped `EventFilter` until then, or implement it in typed testkit.

For example avoid stack traces like
```
[ERROR] [09/12/2018 08:23:48.125] [ActorContextSpec-akka.actor.default-dispatcher-3] [akka://ActorContextSpec/user/$o] death pact with Actor[akka://ActorContextSpec/user/$o/A#1170267854] was triggered
akka.actor.typed.DeathPactException: death pact with Actor[akka://ActorContextSpec/user/$o/A#1170267854] was triggered
	at akka.actor.typed.Behavior$.interpretSignal(Behavior.scala:376)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:47)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.dungeon.DeathWatch.receivedTerminated(DeathWatch.scala:67)
	at akka.actor.dungeon.DeathWatch.receivedTerminated$(DeathWatch.scala:64)
	at akka.actor.ActorCell.receivedTerminated(ActorCell.scala:431)
	at akka.actor.ActorCell.autoReceiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:556)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
This has annoyed me for a while, so I'll pick it up.
