### ISSUE TITLE
Failed: ArteryUpdSendConsistencyWithThreeLanesSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#25609]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6365/consoleFull

```
[info] Artery
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 96 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:509)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:491)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:491)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:896)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.$anonfun$new$2(RemoteSendConsistencySpec.scala:71)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
```

**Comment by patriknw** [comment]
This fails on the very first identify message. No logging before that. Let's close if it doesn't recur in a month or so.

**Comment by patriknw** [comment]
obsolete
