### ISSUE TITLE
FAILED: StreamRefsSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25637]
https://jenkins.akka.io:8498/job/akka-nightly/5868/testReport/junit/akka.stream.scaladsl/StreamRefsSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

```
sbt.ForkMain$ForkError: akka.remote.RemoteTransportException: Inbound Aeron channel is in errored state. See Aeron logs for details.
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.retry$1(ArteryAeronUdpTransport.scala:236)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.blockUntilChannelActive(ArteryAeronUdpTransport.scala:227)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.runInboundStreams(ArteryAeronUdpTransport.scala:306)
	at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:456)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:840)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:837)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:837)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:856)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
	at akka.stream.scaladsl.StreamRefsSpec.<init>(StreamRefsSpec.scala:193)
	at akka.stream.scaladsl.StreamRefsSpec.<init>(StreamRefsSpec.scala:190)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at sbt.ForkMain$Run$$Lambda$276/905847077.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5881/consoleFull

**Comment by johanandren** [comment]
This was a port conflict I think:

https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6444/log/?start=0

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6461/testReport/junit/akka.stream.scaladsl/StreamRefsSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6565/testReport/junit/akka.stream.scaladsl/StreamRefsSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6565/consoleFull
