### ISSUE TITLE
akka.util.Unsafe fails with exception on JDK 11

### ISSUE THREAD

**Issue by gyoetam** [akka/akka#25640]
On JDK 11, akka.util.Unsafe fails with exception even before reaching the point where it would check for Java9+. The reason is that accessing sun.misc.Unsafe is no longer allowed.

Looking at the code in master this would happen with the latest version as well.

> Exception in thread "main" java.lang.ExceptionInInitializerError
	at akka.dispatch.AbstractNodeQueue.<clinit>(AbstractNodeQueue.java:181)
	at akka.actor.LightArrayRevolverScheduler.<init>(LightArrayRevolverScheduler.scala:157)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:33)
	at scala.util.Try$.apply(Try.scala:209)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$4(ReflectiveDynamicAccess.scala:39)
	at scala.util.Success.flatMap(Try.scala:247)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
	at akka.actor.ActorSystemImpl.createScheduler(ActorSystem.scala:876)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:767)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:234)
	at akka.actor.ActorSystem$.create(ActorSystem.scala:169)
	at akka.actor.ActorSystem.create(ActorSystem.scala)
        at ...
Caused by: java.lang.ExceptionInInitializerError
	at akka.util.Unsafe.<clinit>(Unsafe.java:42)
	at akka.dispatch.AbstractNodeQueue.<clinit>(AbstractNodeQueue.java:179)
	... 20 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at akka.util.Unsafe.<clinit>(Unsafe.java:22)
	... 21 more
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by retronym** [comment]
Here's what we're doing in Scala 2.13.x: https://github.com/scala/scala/blob/2.13.x/src/library/scala/runtime/Statics.java#L127-L168

**Comment by johanandren** [comment]
@gyoetam did you start the JVM with any flags to make the module system stricter, we're not seeing these problems when testing out on vanilla JDK 11

**Comment by johanandren** [comment]
Aha, it's only when you run with modulepath and not classpath (which running a main from both sbt and IntelliJ does)

**Comment by gyoetam** [comment]
It happened with an OpenJDK version created with jlink by removing some modules. The command format was: java -classpath <path_to_libs>/* <main_class_name>
--add-modules=jdk.unsupported was required to make the Unsafe class accessible and avoid the error.

**Comment by johanandren** [comment]
Thanks for that extra info.

Note from testing: even with the module system enabled (not using jlink though) it seems to be working out of the box, tried with this dummy project: https://github.com/johanandren/akka-java-modules-app

**Comment by johanandren** [comment]
Update, I was wrong about the maven exec plugin switching to modules when giving it the release config, to use modules on Java 11 you have to explicitly configure a `exec:exec` rather. I have updated the dummy project with that.

Running it currently fails on some module related stuff in java8-compat before reaching the ActorSystem as is.

**Comment by gyoetam** [comment]
I can't seem to reproduce the issue with a JDK that includes the jdk.unsupported module. I'm not sure what changed since I posted the issue, could have been a preview version of the JDK (before GA)...

However, the code could still handle the case when the module is not available. I built the custom JRE with this jlink command:
jlink --module-path /opt/java/jdk-11/jmods/ --add-modules jdk.jcmd,$(java --list-modules | grep -v -e jdk. -e java.desktop | sed "s/@11//" | tr "\n" "," ) --compress 2 --no-header-files --no-man-pages --output /tmp/jre
Where /opt/java/jdk11 is a vanilla JDK. Running your test program with /tmp/jre/bin/java then produces the exception above.

**Comment by gyoetam** [comment]
> We'll see how we choose to deal with it, since we will still need to support Java 8 for quite a while more, I'm not sure we want separate code impls to maintain when Unsafe is still there, we could ending up choosing just requiring the "sun.unsupported" for now (I'm certainly leaning in that direction).

Is using Unsafe actually critical for performance or some other reason? The unified (Java 8-11) solution could simply be to not use internal classes, or use a toggle for it, as does Netty.
Choosing to require jdk.unsupported could also be a reasonable direction, but in that case this should clearly be mentioned in the documentation.

**Comment by johanandren** [comment]
I think it is critical for performance, that would need more research and benchmarking though, which would first require an implementation. I don't think we have any way to unify since I think we'd need VarHandles for the alternative impl. and those weren't introduced until Java 9

**Comment by adriaanm** [comment]
Some of the relevant implementation (deciding between unsafe/varhandle using invokedynamic) is in the link retronym posted above.

**Comment by viktorklang** [comment]
@adriaanm I'm not sure that is going to help, as we're going to need to access instance methods on VarHandle (not statics).

**Comment by magicghostVu** [comment]
requires jdk.unsupported;
i tried this and Unsafe is available

**Comment by Sciss** [comment]
Running into the same issue, using sbt-native-packager with `JlinkPlugin`. Does anyone know how I can configure it to `--add-modules=jdk.unsupported`. Is there a reason, Akka needs to access legacy sun API?

**Comment by Sciss** [comment]
Ok, so in sbt-native-packager:

```
  jlinkModules := {
    jlinkModules.value :+ "jdk.unsupported"
  },
```
