### ISSUE TITLE
PersistentActorJavaDslTest: tapPersistentActor expected akka.persistence.typed.javadsl.PersistentActorJavaDslTest$Increment@4c84057d, found RecoveryPermitGranted

### ISSUE THREAD

**Issue by raboof** [akka/akka#25727]
multi-node: https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node/runs/2980/log/?start=0
```
[info] PersistentActorJavaDslTest:
[info] - chainableSideEffectsWithEvents
[info] - transformEvent
[info] - tapPersistentActor *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected akka.persistence.typed.javadsl.PersistentActorJavaDslTest$Increment@4c84057d, found RecoveryPermitGranted
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:137)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:120)
[info]   at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.tapPersistentActor(PersistentActorJavaDslTest.java:454)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:497)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[info]   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
[info]   at org.scalatest.junit.JUnitSuiteLike.run(JUnitSuiteLike.scala:242)
[info]   at org.scalatest.junit.JUnitSuiteLike.run$(JUnitSuiteLike.scala:230)
[info]   at org.scalatest.junit.JUnitSuite.run(JUnitSuite.scala:71)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at sbt.ForkMain$Run$$Lambda$435/1822630059.call(Unknown Source)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by johanandren** [comment]
Another failure in the same test:
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6438/log/?start=0

```
[info] - stopThenLog *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectStop waiting for actor [akka://PersistentActorJavaDslTest/user/$n] to stop
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:228)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:233)
[info]   at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.stopThenLog(PersistentActorJavaDslTest.java:432)
```
