### ISSUE TITLE
FAILED akka.pattern.BackoffSupervisorSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25753]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6440/log/?start=0

```
[info] - must stop restarting the child after reaching maxNrOfRetries limit (Backoff.onFailure) *** FAILED *** (416 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected: Terminated Actor[akka://BackoffSupervisorSpec/user/$l/c1#-1281037035] but got unexpected message Terminated(Actor[akka://BackoffSupervisorSpec/user/$l#-296692734])
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:421)
[info]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:417)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:896)
[info]   at akka.testkit.TestKitBase.expectTerminated(TestKit.scala:435)
[info]   at akka.testkit.TestKitBase.expectTerminated$(TestKit.scala:434)
[info]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:896)
[info]   at akka.pattern.BackoffSupervisorSpec.$anonfun$new$28(BackoffSupervisorSpec.scala:333)
[info]   at akka.pattern.BackoffSupervisorSpec$$Lambda$3739/1381166281.apply$mcV$sp(Unknown Source)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/5950/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1242/testReport/junit/akka.pattern/BackoffSupervisorSpec/onFailure_/
