### ISSUE TITLE
FAILED: MultiDcClusterSharding

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25752]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-artery-cluster-tests/runs/1599/log/?start=0

```
[info] [JVM-1] - must start sharding (on node 'first', class akka.cluster.sharding.typed.MultiDcClusterShardingMultiJvmNode1) *** FAILED *** (3 seconds, 110 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMessage while waiting for Pong(dc1)
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:219)
[info] [JVM-1]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:136)
[info] [JVM-1]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:120)
[info] [JVM-1]   at akka.cluster.sharding.typed.MultiDcClusterShardingSpec.$anonfun$new$3(MultiDcClusterShardingSpec.scala:78)
[info] [JVM-1]   at akka.cluster.sharding.typed.MultiDcClusterShardingSpec$$Lambda$731/538667887.apply$mcV$sp(Unknown Source)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info] [JVM-1]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-1]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info] [JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [JVM-1]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info] [JVM-1]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info] [JVM-1]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info] [JVM-1]   at akka.cluster.sharding.typed.MultiDcClusterShardingSpec.withFixture(MultiDcClusterShardingSpec.scala:55)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-artery-cluster-tests/runs/1601/log/?start=0

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1615/consoleFull

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1617/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-artery-cluster-tests/detail/akka-artery-cluster-tests/1644/pipeline

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-artery-cluster-tests/runs/1653/log/?start=0
