### ISSUE TITLE
Failed: DDataClusterShardingWithEntityRecoveryMultiJvm

### ISSUE THREAD

**Issue by johanandren** [akka/akka#25763]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-artery-cluster-tests/runs/1604/log/?start=0

```
[info] [JVM-6] - easy to use with extensions (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6) *** FAILED ***
[info] [JVM-6]   java.lang.AssertionError: assertion failed: timeout (49950309634 nanoseconds) during expectMsg while waiting for 0
[info] [JVM-6]   at scala.Predef$.assert(Predef.scala:219)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:402)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info] [JVM-6]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info] [JVM-6]   at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$55(ClusterShardingSpec.scala:661)
[info] [JVM-6]   at akka.cluster.sharding.ClusterShardingSpec$$Lambda$1154/1200048933.apply$mcV$sp(Unknown Source)
[info] [JVM-6]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:370)
[info] [JVM-6]   at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$53(ClusterShardingSpec.scala:657)
[info] [JVM-6]   at akka.cluster.sharding.ClusterShardingSpec$$Lambda$1141/789982400.apply$mcV$sp(Unknown Source)
```

**Comment by helena** [comment]
This seems resolved now 
* no failures since November 2019 on https://jenkins.akka.io:8498/job/akka-artery-cluster-tests
* https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-artery-cluster-tests doesn't exist anymore
