### ISSUE TITLE
Reactive Streams spec violation, possible bug in Reactive Streams TCK

### ISSUE THREAD

**Issue by jroper** [akka/akka#25927]
I haven't had time to try to reproduce or create a minimizer, but I wanted to record this here because it's very surprising and I'm not sure if I'll see it again. I've never seen it before, and looking at it, it appears that Akka is claiming that the TCK is calling onNext without demand. I guess this could either be a bug in Akka Streams, or in the TCK, I'm raising here because this is probably the best place to start investigating.

Seen in Akka Streams 2.5.14.

I have a Reactive Streams TCK Identity Processor verification that is testing what is essentially:

```java
Flow.create().mapConcat(Arrays::asList).toProcessor().run();
```

Testing against that, I get the following error:

```
required_spec308_requestMustRegisterGivenNumberElementsToBeProduced(org.eclipse.microprofile.reactive.streams.tck.spi.FlatMapIterableStageVerification$ProcessorVerification)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.IllegalStateException: spec violation: onNext was signaled from upstream without demand
	at akka.stream.impl.VirtualProcessor.rec$5(StreamLayout.scala:336)
	at akka.stream.impl.VirtualProcessor.onNext(StreamLayout.scala:341)
	at akka.stream.scaladsl.Flow$$anon$1.onNext(Flow.scala:306)
	at org.reactivestreams.tck.TestEnvironment$ManualPublisher.sendNext(TestEnvironment.java:730)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification$WhiteboxTestStage.signalNext(SubscriberWhiteboxVerification.java:571)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification$WhiteboxTestStage.signalNext(SubscriberWhiteboxVerification.java:567)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification$14.run(SubscriberWhiteboxVerification.java:440)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification.subscriberTest(SubscriberWhiteboxVerification.java:498)
	at org.reactivestreams.tck.SubscriberWhiteboxVerification.required_spec308_requestMustRegisterGivenNumberElementsToBeProduced(SubscriberWhiteboxVerification.java:436)
	at org.reactivestreams.tck.IdentityProcessorVerification.required_spec308_requestMustRegisterGivenNumberElementsToBeProduced(IdentityProcessorVerification.java:670)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

As I said, I've never seen a failure like this before, and I haven't upgraded either Akka Streams or the TCK recently in this project, yet this particular test has been run over and over again without failing, so I doubt I'll see it any time soon again, it's likely a race condition that very rarely gets triggered.

**Comment by jroper** [comment]
Ok, this is a bug in the TCK, and as it turns out, I already reported it over 3 years ago:

https://github.com/reactive-streams/reactive-streams-jvm/issues/277.

**Comment by jroper** [comment]
PR: https://github.com/reactive-streams/reactive-streams-jvm/pull/441

**Comment by viktorklang** [comment]
@jroper Thanks James!
