### ISSUE TITLE
FAILED: DurablePruningSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25954]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/1685/consoleFull

```
[info] [JVM-1] - must move data from removed node *** FAILED *** (21 seconds, 101 milliseconds)
[info] [JVM-1]   4 was not equal to 3 (DurablePruningSpec.scala:170)
[info] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-1]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info] [JVM-1]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info] [JVM-1]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info] [JVM-1]   at akka.cluster.ddata.DurablePruningSpec.$anonfun$new$22(DurablePruningSpec.scala:170)
```

**Comment by patriknw** [comment]
obsolete
