### ISSUE TITLE
Failed: WatchSpec akka.actor.typed.WatchSpec.Actor monitoring must allow watch message redefinition using unwatch

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25955]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6566/testReport/junit/akka.actor.typed/WatchSpec/Actor_monitoring_must_allow_watch_message_redefinition_using_unwatch/

```
Error Message

org.scalatest.exceptions.TestFailedException: CustomTerminationMessage did not equal CustomTerminationMessage2
Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: CustomTerminationMessage did not equal CustomTerminationMessage2
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6742)
	at akka.actor.typed.WatchSpec.$anonfun$new$21(WatchSpec.scala:250)
	at akka.actor.typed.WatchSpec$$Lambda$1148/932486804.apply(Unknown Source)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3121/testReport/junit/akka.actor.typed/WatchSpec/Actor_monitoring_must_allow_watch_message_redefinition_using_unwatch/
