### ISSUE TITLE
Failed: PrimitiveStateSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#25958]
https://jenkins.akka.io:8498/job/akka-nightly/6069/testReport/junit/akka.persistence.typed.scaladsl/PrimitiveStateSpec/A_typed_persistent_actor_with_primitive_state_must_persist_events_and_update_state/

```
Error Message

java.lang.AssertionError: assertion failed: expected eventHandler:1:2, found onRecoveryCompleted:1

Stacktrace

sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: expected eventHandler:1:2, found onRecoveryCompleted:1
	at scala.Predef$.assert(Predef.scala:219)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:138)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:121)
	at akka.persistence.typed.scaladsl.PrimitiveStateSpec.$anonfun$new$2(PrimitiveStateSpec.scala:60)
	at akka.persistence.typed.scaladsl.PrimitiveStateSpec$$Lambda$967/1239911049.apply(Unknown Source)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14616/testReport/junit/akka.persistence.typed.scaladsl/PrimitiveStateSpec/A_typed_persistent_actor_with_primitive_state_must_persist_events_and_update_state/
