### ISSUE TITLE
NPE in ActorGraphInterpreter

### ISSUE THREAD

**Issue by Saheb** [akka/akka#25995]
We were seeing this NPE in our error log, but we're not able to figure out why it is happening. It is not causing any functional problem, but just annoying to have this in the logs. Any ideas?

We're using akka-http version `10.1.3`

It's not easy to reproduce this, but, we would appreciate if someone familiar with the codebase can dig and find out why this is being exposed to the end user. If that doesn't work, let us know, and we would invest time in documenting ways to reproduce it.

```
2018-11-23 16:09:15,042 ERROR akka.actor.RepointableActorRef - Error in stage [BatchingActorInputBoundary(forPort=CheckContentLength(sent=0), fill=0/16, completed=true, canceled=true)]: null
java.lang.NullPointerException: null
    at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary.clear(ActorGraphInterpreter.scala:80)
    at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary.cancel(ActorGraphInterpreter.scala:166)
    at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary.onDownstreamFinish(ActorGraphInterpreter.scala:236)
    at akka.stream.impl.fusing.FinishSignals.downstreamFinish(FinishSignals.java:31)
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:494)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:735)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:761)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
    at akka.actor.ActorCell.invoke$$original(ActorCell.scala:557)
    at akka.actor.ActorCell.invoke(ActorCell.scala:61)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run$$original(Mailbox.scala:225)
    at akka.dispatch.Mailbox.run(Mailbox.scala:32)
    at cinnamon.akka.DispatcherInstruments$RecordingRunnable.run(DispatcherInstruments.scala:143)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by hepin1989** [comment]
@Saheb how about you upgrade the Akka to the latest version and see if the problem is still there?

**Comment by johanandren** [comment]
Thanks for trying latest Akka @Saheb! I think this is a bug in the interpreter, but as we haven't seen it reported before it would be great if you had some form of minimal reproducer to help us pinpoint what causes it.

**Comment by hepin1989** [comment]
```
    private def clear(): Unit = {
      java.util.Arrays.fill(inputBuffer, 0, inputBuffer.length, null)
      inputBufferElements = 0
    }
```

**Comment by johanandren** [comment]
Hi again @Saheb any chance you could share a minimal reproducer or some more details? I looked into the code and there is no obvious cause of a NPE in that method.

**Comment by Saheb** [comment]
Hi @johanandren, 

I did try to create a standalone snippet to reproduce the bug but haven't been able to do so. We're doing something like this, which emits the above stack trace. Not sure if it will help, but it might give you some context. We continue to see the annoying NPE in our error log.

```scala
import scala.concurrent.{ExecutionContext, Future}

import akka.actor.{Actor, ActorLogging, ActorSystem, Props}
import akka.http.scaladsl.Http
import akka.http.scaladsl.marshalling.Marshal
import akka.http.scaladsl.model._
import akka.stream.{ActorMaterializer, Materializer}
import HttpClient.AkkaHttpClient
import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport

abstract class KafkaBatchConsumerActor extends Actor with ActorLogging {

  implicit val ec: ExecutionContext = context.dispatcher

  def processMessages(messages: Seq[Int]): Future[Unit]

  override def receive: Receive = {
    case messages: Seq[Int] =>
      processMessages(messages)
  }
}

abstract class KafkaConsumerActor extends KafkaBatchConsumerActor {

  def processMessage(message: Int): Future[Unit]

  override def processMessages(messages: Seq[Int]): Future[Unit] =
    Future.traverse(messages)(processMessage).map(_ => ())
}

class PersistedKafkaConsumerActor(publishers: Seq[Publisher]) extends KafkaConsumerActor {
  override def processMessage(message: Int): Future[Unit] = {
    Future.traverse(publishers) {
      publisher => publisher.publish(message).recover {
        case error: Throwable =>
          val publisherName = publisher.getClass.getName
          log.error(error, s"Error publishing result {} with publisher {}", message, publisherName)
      }
    }.map(_ => ())
  }
}

trait Publisher {
  def publish(msg: Int): Future[Unit]
}

class SlackPublisher(webHooks: Seq[Uri], slackClient: SlackClient)(implicit system: ActorSystem) extends Publisher {

  import system.dispatcher

  override def publish(msg: Int): Future[Unit] = {
    Future.traverse(webHooks) {
      webHook  =>
        Future {
          println(webHook)
          println(msg)
          slackClient.publishSlackMessage(SlackMessage(msg.toString), webHook)
        }
    }.map(_ => ())
  }
}

object Test extends App {
  implicit val system: ActorSystem = ActorSystem("Test")
  implicit val ec: ExecutionContext = system.dispatcher
  implicit val materializer: Materializer = ActorMaterializer()

  val webHooks = Seq(Uri("..."))
  val slackClient = new SlackClient(new AkkaHttpClient)
  val actorRef = system.actorOf(Props(new PersistedKafkaConsumerActor(Seq(new SlackPublisher(webHooks, slackClient)))))
  actorRef ! Seq(1,2,3)
}

class SlackClient(httpClient: HttpClient)(implicit system: ActorSystem, mat: Materializer) {

  import SprayJsonSupport._
  import system.dispatcher

  def publishSlackMessage(message: SlackMessage, webHook: Uri): Future[Unit] = {
    for {
      request <- Marshal(message).to[RequestEntity]
      response <- httpClient.httpRequest(
        HttpRequest(
          method = HttpMethods.POST,
          uri = webHook,
          entity = request
        )
      )
      _ <- response.status match {
        case StatusCodes.OK =>
          response.discardEntityBytes().future
        case code: StatusCode =>
          Future.failed(new Exception(s"Slack API request failed with status: $code"))
      }
    } yield ()
  }
}

trait HttpClient {
  def httpRequest(httpRequest: HttpRequest): Future[HttpResponse]
}

object HttpClient {

  class AkkaHttpClient(implicit system: ActorSystem) extends HttpClient {
    override def httpRequest(httpRequest: HttpRequest): Future[HttpResponse] =
      Http().singleRequest(httpRequest)
  }
}

object SlackMessage {
  import spray.json._
  import DefaultJsonProtocol._

  implicit val slackMessageFormat: RootJsonFormat[SlackMessage] =
    jsonFormat1(SlackMessage.apply)
}

final case class SlackMessage(text: String)
```

**Comment by johanandren** [comment]
Better than nothing, thanks @Saheb, I'll see if that gives any hints.

**Comment by jrudolph** [comment]
@Saheb there's something strange with the line numbers. I couldn't find a version where the line numbers would be matching our code. It seems `clear` never was at line 80:

```
    at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary.clear(ActorGraphInterpreter.scala:80)
```

Also what is this:

```
    at akka.stream.impl.fusing.FinishSignals.downstreamFinish(FinishSignals.java:31)
```

I couldn't find this file as well?

**Comment by Saheb** [comment]
That is strange, I've been trying to figure out why that would be the case. Found this till now:
`
2019-01-09 12:40:33,066 [mas-notification-akka.actor.default-dispatcher-4] WARN akka.util.ManifestInfo - Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use [2.5.18] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries.Possibly conflicting versions [2.5.18, 2.5.3, 2.5.12] in libraries [akka-protobuf:2.5.18, akka-actor:2.5.18, akka-slf4j:2.5.3, akka-stream:2.5.18, akka-stream-testkit:2.5.12]
`

**Comment by jrudolph** [comment]
Can you run with `-verbose:class` and check where `akka.stream.impl.fusing.FinishSignals` is loaded from?

**Comment by Saheb** [comment]
```
[Loaded akka.stream.impl.fusing.FinishSignals from file:/opt/docker/lib/com.typesafe.akka.akka-stream_2.12-2.5.18.jar]
```
![screen shot 2019-01-15 at 12 46 21 pm](https://user-images.githubusercontent.com/1163256/51181661-a9ebc100-18c3-11e9-8e31-2cb8c41ae4bb.png)

**Comment by jrudolph** [comment]
Do you know where that jar file comes from? Can you attach it here (or somewhere else)?

**Comment by Saheb** [comment]
[akka-stream_2.12-2.5.18.zip](https://github.com/akka/akka/files/2760246/akka-stream_2.12-2.5.18.zip)
I still don't see `FinishSignals` file in the jar.

**Comment by Saheb** [comment]
I suspect the same, working my way around various possibilities and understanding the abstraction layers in place. And yes, the above jar was downloaded before the docker image of the service was published to our internal artifactory.

**Comment by Saheb** [comment]
Thanks, @jrudolph, that solves the issue. I'm at fault as well I guess, I should've mentioned we're using cinnamon.

**Comment by raboof** [comment]
Glad to hear that solved it!
