### ISSUE TITLE
failed: Inbound Aeron channel is in errored state.

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26009]
```
Error Message
akka.remote.RemoteTransportException: Inbound Aeron channel is in errored state. See Aeron logs for details.
Stacktrace
sbt.ForkMain$ForkError: akka.remote.RemoteTransportException: Inbound Aeron channel is in errored state. See Aeron logs for details.
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.retry$1(ArteryAeronUdpTransport.scala:236)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.blockUntilChannelActive(ArteryAeronUdpTransport.scala:227)
	at akka.remote.artery.aeron.ArteryAeronUdpTransport.runInboundStreams(ArteryAeronUdpTransport.scala:306)
	at akka.remote.artery.ArteryTransport.start(ArteryTransport.scala:456)
	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:222)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:873)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:869)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:869)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:890)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:246)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:289)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:264)
	at akka.testkit.AkkaSpec.<init>(AkkaSpec.scala:67)
	at akka.stream.scaladsl.StreamRefsSpec.<init>(StreamRefsSpec.scala:186)
	at akka.stream.scaladsl.StreamRefsSpec.<init>(StreamRefsSpec.scala:190)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at sbt.ForkMain$Run$$Lambda$280/1334405552.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14020/testReport/junit/akka.stream.scaladsl/StreamRefsSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

**Comment by chbatey** [comment]
Fixed in https://github.com/akka/akka/pull/25991
