### ISSUE TITLE
Failed: PersistentActorJavaDslTest

### ISSUE THREAD

**Issue by chbatey** [akka/akka#26030]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6606/testReport/junit/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/stopThenLog/

```
Error Message
java.lang.AssertionError: assertion failed: timeout (1 second) during expectStop waiting for actor [akka://PersistentActorJavaDslTest/user/$o] to stop
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (1 second) during expectStop waiting for actor [akka://PersistentActorJavaDslTest/user/$o] to stop
	at scala.Predef$.assert(Predef.scala:219)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:251)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:256)
	at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.stopThenLog(PersistentActorJavaDslTest.java:461)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/141/testReport/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/failOnIncorrectExpectedStateForThenRun/

**Comment by patriknw** [comment]
Note that the jdk11 failure has an interesting error message:
```
[ERROR] [02/12/2019 11:33:30.938] [PersistentActorJavaDslTest-akka.actor.default-dispatcher-9] [akka://PersistentActorJavaDslTest/user] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at akka.persistence.typed.javadsl.Effect.$anonfun$thenRun$1(Effect.scala:131)
	at akka.persistence.typed.javadsl.Effect.$anonfun$thenRun$1$adapted(Effect.scala:131)
	at akka.persistence.typed.internal.Running.applySideEffect(Running.scala:339)
	at akka.persistence.typed.internal.Running.applySideEffects(Running.scala:317)
	at akka.persistence.typed.internal.Running.applyEffects$1(Running.scala:147)
	at akka.persistence.typed.internal.Running.onCommand$1(Running.scala:89)
	at akka.persistence.typed.internal.Running.$anonfun$handlingCommands$3(Running.scala:173)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:49)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:421)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:394)
	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:50)
	at akka.actor.typed.internal.WidenedInterceptor.aroundReceive(InterceptorImpl.scala:198)
	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:74)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:421)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:394)
	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:50)
	at akka.persistence.typed.internal.EventSourcedBehaviorImpl$$anon$1.aroundReceive(EventSourcedBehaviorImpl.scala:122)
	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:74)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:421)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:394)
	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:50)
	at akka.actor.typed.internal.SimpleSupervisor.aroundReceive(Supervision.scala:96)
	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:74)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:421)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:394)
	at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:82)
	at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:78)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:39)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[info] - failOnIncorrectExpectedStateForThenRun *** FAILED ***
[info]   java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on ErrorFilter(class akka.event.Logging$Error$NoCause$,None,Left(java.lang.Integer cannot be cast to java.lang.String),true)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:115)
[info]   at akka.testkit.javadsl.EventFilter.intercept(EventFilter.scala:51)
[info]   at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.failOnIncorrectExpectedStateForThenRun(PersistentActorJavaDslTest.java:631)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[info]   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk10/465/testReport/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/failOnIncorrectExpectedStateForThenRun/

Looking at the ErrorFilter, it seems the `ClassCastException` is expected?

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/142/testReport/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/failOnIncorrectExpectedStateForThenRun/

**Comment by jrudolph** [comment]
The JDK 11 failure is distinct from the original one.
