### ISSUE TITLE
Failed: NullEmptyStateSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#26047]
https://jenkins.akka.io:8498/job/akka-nightly/6111/testReport/junit/akka.persistence.typed.scaladsl/NullEmptyStateSpec/A_typed_persistent_actor_with_primitive_state_must_persist_events_and_update_state/

```
Error Message
java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for eventHandler:null:one
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for eventHandler:null:one
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:291)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:139)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:120)
	at akka.persistence.typed.scaladsl.NullEmptyStateSpec.$anonfun$new$2(NullEmptyStateSpec.scala:59)
	at akka.persistence.typed.scaladsl.NullEmptyStateSpec$$Lambda$725/47504848.apply(Unknown Source)
```

**Comment by johanandren** [comment]
This code path has been changed so much that the original 
```
java.util.NoSuchElementException: OptionVal.None.get
	at akka.util.OptionVal$.get$extension(OptionVal.scala:70)
	at akka.persistence.typed.internal.EventsourcedStashReferenceManagement.stashBuffer(EventsourcedStashReferenceManagement.scala:27)
	at akka.persistence.typed.internal.EventsourcedStashReferenceManagement.stashBuffer$(EventsourcedStashReferenceManagement.scala:21)
```

Isn't there anymore, I have chased an `OptionVal.get` in the stash logic but can't find anything there anymore after the rewrite of stashing. I think we can close this one.
