### ISSUE TITLE
NullPointerException in Slf4jLogger

### ISSUE THREAD

**Issue by KarelCemus** [akka/akka#26042]
I use Akka `2.5.18` with `akka-slf4j` and `logback`.

This logging statement results in `NullPointerException`:

```scala
  log.warning(new IllegalArgumentException(), "Some message")
```

error stack:

```
java.lang.NullPointerException: null
	at akka.event.slf4j.Slf4jLogger.akka$event$slf4j$Slf4jLogger$$markerIfPresent(Slf4jLogger.scala:117)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.$anonfun$applyOrElse$2(Slf4jLogger.scala:76)
	at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:103)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:75)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:54)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I traced the issue into [Slf4jLogger:117](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala#L117) and the following assumption is invalid:

```scala
    event match {
      case m: LogEventWithMarker ⇒
        m.marker match {
          case slf4jMarker: Slf4jLogMarker ⇒ slf4jMarker.marker
          case marker                      ⇒ MarkerFactory.getMarker(marker.name)
        }
      case _ ⇒ null
    }
```

This code assumes existence of a marker when a class is instance of `LogEventWithMarker`, which is unfortunatelly invalid.

Invocation of `log.warn` results in calling [`Warning(cause.get, logSource, logClass, message, mdc, marker.orNull.asInstanceOf[UntypedLM])
 `](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala#L392), which creates instance of:

``` scala
class Warning4(logSource: String, logClass: Class[_], message: Any, override val mdc: MDC, override val marker: LogMarker, override val cause: Throwable)
    extends Warning2(logSource, logClass, message, mdc) with LogEventWithMarker with LogEventWithCause
```

but with the marker set to `null`.

**Comment by raboof** [comment]
Very strange that we did not catch this before, since this seems to be a common usage pattern.

**Comment by raboof** [comment]
Ah wait `log.warn` with a `cause` is new in Akka Typed.

I guess we can go 2 ways here: we can dictate a `LogEventWithMarker` should always have a marker (so creating one with a `null` marker is the bug) or decide the marker may be `null` (so assuming it is present is the bug).

**Comment by KarelCemus** [comment]
The bug is quite simple. See how a difference between [error](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala#L377) and [warning](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-actor-typed/src/main/scala/akka/actor/typed/internal/adapter/LoggerAdapterImpl.scala#L392). While there is proper pattern matching over a marker within an error, there is no such pattern matching within a warning when a cause is defined.

**Comment by patriknw** [comment]
Sounds good, would you be able to create a PR @KarelCemus?

**Comment by KarelCemus** [comment]
Sure, I'll take care of it.
