### ISSUE TITLE
Failed: TlsSpec in JDK11

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#26064]
It seems that these tests consistently need twice the time to run with JDK11 than in the regular nightly build. That's enough to fail a hard-coded timeout. We should investigate if that slow down can be reproduced locally and track down where it comes from.

[History of this test in JDK11 nightly](https://jenkins.akka.io:8498/job/akka-nightly-jdk11/83/testReport/junit/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiates_while_sending_LargeMessages/history/)
[History of this test in regular nightly](https://jenkins.akka.io:8498/job/akka-nightly/6114/testReport/junit/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiates_while_sending_LargeMessages/history/)

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/83/testReport/junit/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiates_while_sending_LargeMessages/

+ others

```
Error Message

java.util.concurrent.TimeoutException: Futures timed out after [8 seconds]
Stacktrace

sbt.ForkMain$ForkError: java.util.concurrent.TimeoutException: Futures timed out after [8 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:142)
	at akka.stream.io.TlsSpec.$anonfun$new$8(TlsSpec.scala:384)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:28)
	at akka.stream.io.TlsSpec.$anonfun$new$7(TlsSpec.scala:359)
```

**Comment by patriknw** [comment]
Looks like the test duration for this is around 6 seconds for both jdk 8 and 11 now.

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/lastCompletedBuild/testReport/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiates_while_sending_LargeMessages/history/

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/501/testReport/akka.stream.io/TlsSpec/SslTls_must_work_in_mode_ClientInitiates_while_sending_LargeMessages/history/
