### ISSUE TITLE
CoordinatedShutdownShardingSpec: run coordinated shutdown when leaving timeout (1 second) during expectMsg while waiting for 1

### ISSUE THREAD

**Issue by raboof** [akka/akka#26214]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-multi-node-nightly2/detail/akka-multi-node-nightly2/1308/artifacts
```
[0m[[0m[0minfo[0m] [0m[0m[31m- must run coordinated shutdown when leaving *** FAILED *** (33 seconds, 845 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsg while waiting for 1[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.Predef$.assert(Predef.scala:223)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:402)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:388)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:388)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:896)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.CoordinatedShutdownShardingSpec.$anonfun$pingEntities$1(CoordinatedShutdownShardingSpec.scala:79)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:312)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:329)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:301)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.CoordinatedShutdownShardingSpec.pingEntities(CoordinatedShutdownShardingSpec.scala:76)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.CoordinatedShutdownShardingSpec.$anonfun$new$16(CoordinatedShutdownShardingSpec.scala:136)[0m[0m
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-artery-tcp-cluster-tests/detail/akka-artery-tcp-cluster-tests/584/artifacts

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-nightly-2.13/detail/akka-nightly-2.13/31/artifacts

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/rest/organizations/jenkins/pipelines/akka-multi-node-nightly/runs/6685/log/?start=0

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-multi-node-nightly2/detail/akka-multi-node-nightly2/1309/changes/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-nightly-jdk11/detail/akka-nightly-jdk11/107/artifacts

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/blue/organizations/jenkins/akka-artery-tcp-cluster-tests/detail/akka-artery-tcp-cluster-tests/587/pipeline

**Comment by raboof** [comment]
This is certainly happening a *lot* now...

**Comment by hepin1989** [comment]
refs:https://github.com/akka/akka/pull/26220
