### ISSUE TITLE
Failed: RateTransformationDocSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26262]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14552/testReport/junit/docs.stream/RateTransformationDocSpec/extrapolate_should_send_seed_first/

```
java.util.concurrent.TimeoutException: Futures timed out after [100 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at docs.stream.RateTransformationDocSpec.$anonfun$new$17(RateTransformationDocSpec.scala:91)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/14688/testReport/junit/docs.stream/RateTransformationDocSpec/extrapolate_should_send_seed_first/
