### ISSUE TITLE
Unsafe.copyUSAsciiStrToBytes fails on OpenJ9/OpenJDK 11

### ISSUE THREAD

**Issue by dguggemos** [akka/akka#26286]
I'm using Akka 2.5.19 together with OpenJ9/OpenJDK11 and encounter the same problem as described in #25161. The solution was replacing `chars.length` with `str.length()`. But this was only [done for the Java 8 case](https://github.com/fjeremic/akka/commit/33b8fb298c4b253f5b7d116d6bc82f27a74d6c2f). Is there any reason why the [Java 9+ case](https://github.com/akka/akka/blob/v2.5.19/akka-actor/src/main/scala/akka/util/Unsafe.java#L49) was not changed accordingly?

Exception for Akka 2.5.19 and OpenJ9/OpenJDK11:
```
2019-01-25 08:47:34,633 ERROR [] a.r.artery.Encoder Encoder(akka://ditto-cluster) - Failed to serialize > message [ActorSelectionMessage(akka.cluster.InternalClusterAction$InitJoin)].
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 94
	at java.base/java.lang.System.arraycopy(Native Method)
	at akka.util.Unsafe.copyUSAsciiStrToBytes(Unsafe.java:49)
	at akka.remote.artery.EnvelopeBuffer.writeLiteral(EnvelopeBufferPool.scala:537)
	at akka.remote.artery.EnvelopeBuffer.writeHeader(EnvelopeBufferPool.scala:433)
	at akka.remote.MessageSerializer$.serializeForArtery(MessageSerializer.scala:76)
```

**Comment by johanandren** [comment]
Not sure and can't find anything explaining that, would you be up for doing a PR to see if that fixes the issue on J9/11?

**Comment by thjaeckle** [comment]
The explanation is that Akka's `Unsafe.copyUSAsciiStrToBytes` relies on Hotspot internal behavior of how `String` allocates its characaters (see also #25161) in a quite "unsafe" way ;)
Using `str.length()` instead of the length of the String internal `chars.length` did make the implementation of `Unsafe.copyUSAsciiStrToBytes` more robost to JVM internals.

Unfortunately the Java9+ case was missed in PR #25165

**Comment by johanandren** [comment]
Yeah, it was why the Java 9+ I referred to not being able to figure out if there was an explanation for, not why the change in #25161 was made.

Any idea why we need the manual loop for 8 but array copy is fine for 9+?
