### ISSUE TITLE
IllegalStateException in cluster receptionist

### ISSUE THREAD

**Issue by senia-psm** [akka/akka#26283]
In some configurations (~20 cluster nodes, ~30-50 typed actors on each node registered using actor receptionist) I'm getting this issue:

```
java.lang.IllegalStateException: missing value for ServiceKey[mt.package.MyClass](myActorName)
at akka.cluster.ddata.ORMap.$anonfun$dryMerge$1(ORMap.scala:353)
at akka.cluster.ddata.ORMap.$anonfun$dryMerge$1$adapted(ORMap.scala:334)
at scala.collection.Iterator.foreach(Iterator.scala:944)
at scala.collection.Iterator.foreach$(Iterator.scala:944)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
at akka.cluster.ddata.ORMap.dryMerge(ORMap.scala:334)
at akka.cluster.ddata.ORMap.merge(ORMap.scala:361)
at akka.cluster.ddata.ORMultiMap.merge(ORMultiMap.scala:81)
at akka.cluster.ddata.ORMultiMap.merge(ORMultiMap.scala:65)
at akka.cluster.ddata.Replicator$Internal$DataEnvelope.merge(Replicator.scala:786)
at akka.cluster.ddata.Replicator$Internal$DataEnvelope.merge(Replicator.scala:774)
at akka.cluster.ddata.Replicator.write(Replicator.scala:1425)
at akka.cluster.ddata.Replicator.writeAndStore(Replicator.scala:1405)
at akka.cluster.ddata.Replicator.$anonfun$receiveGossip$1(Replicator.scala:1713)
at akka.cluster.ddata.Replicator.$anonfun$receiveGossip$1$adapted(Replicator.scala:1710)
at scala.collection.immutable.Map$Map1.foreach(Map.scala:125)
at akka.cluster.ddata.Replicator.receiveGossip(Replicator.scala:1710)
at akka.cluster.ddata.Replicator$$anonfun$4.applyOrElse(Replicator.scala:1271)
at akka.actor.Actor.aroundReceive(Actor.scala:517)
at akka.actor.Actor.aroundReceive$(Actor.scala:515)
at akka.cluster.ddata.Replicator.aroundReceive(Replicator.scala:1164)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
at akka.actor.ActorCell.invoke(ActorCell.scala:557)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
at akka.dispatch.Mailbox.run(Mailbox.scala:225)
at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
```

After this issue there is no way to publish any ServiceKey: each actor checks receptionist for it's service key and tries to republish self addresses once per minute, but after error above such check never succeeds. There are no additional errors in logs.

The error is stable - I'm getting it on every startup of my application.

Unfortunately I can't provide minimal example yet since I'm getting this issue only on production environment (aws) on application with a huge code base.

**Comment by senia-psm** [comment]
Additional information:
There are 2 nodes: `A` and `B`. `ServiceKey[mt.package.MyClass](myActorName)` is registered by `A`, but `B` fails to start.
`B` fails every time it tries to connect to cluster with `A`.
To connect `B` to cluster we have to stop `A`, wait for it to go out of cluster, connect `B` to cluster and start `A`.

**Comment by johanandren** [comment]
Could you see if you can cook it down to a minimal reproducer that you can share?

**Comment by senia-psm** [comment]
@johanandren I'll try to create a reproducer this weekend. I suspect it might be triggered by 2 `ServiceKey`s with the same name, but different classes. At least last time this issue was resolver after duplicate `ServiceKey` names fix, though  it might be a coincidence.

**Comment by patriknw** [comment]
I think this is caused by the same thing as https://github.com/akka/akka/issues/26284

**Comment by patriknw** [comment]
Assuming this was also caused by #26284, but please re-open if it happens again.
