### ISSUE TITLE
Failed: FlowThrottleSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#26325]
```
Error Message
java.lang.RuntimeException: Too high rate, got 352.0, expected max 350, after 3514 ms at element 771
Stacktrace
sbt.ForkMain$ForkError: java.lang.RuntimeException: Too high rate, got 352.0, expected max 350, after 3514 ms at element 771
	at akka.stream.scaladsl.FlowThrottleSpec.$anonfun$new$72(FlowThrottleSpec.scala:337)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:23)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:52)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:41)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.ap
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6763/testReport/junit/akka.stream.scaladsl/FlowThrottleSpec/Throttle_for_various_cost_elements_must_work_for_real_scenario_with_automatic_burst_size/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6277/testReport/junit/akka.stream.scaladsl/FlowThrottleSpec/Throttle_for_various_cost_elements_must_work_for_real_scenario_with_automatic_burst_size/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6304/testReport/junit/akka.stream.scaladsl/FlowThrottleSpec/Throttle_for_various_cost_elements_must_work_for_real_scenario_with_automatic_burst_size/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/6890/testReport/junit/akka.stream.scaladsl/FlowThrottleSpec/Throttle_for_various_cost_elements_must_work_for_real_scenario_with_automatic_burst_size/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7987/

**Comment by raboof** [comment]
> Hopefully fixed "must send elements downstream as soon as time comes" in #30781 but leaving issue open since there are probably rather many timing sensitive things in that test.

Hmm, it indeed looks like it, though in practice it seems to have been rather stable for the past months - perhaps let's close until it shows up again.
