### ISSUE TITLE
RepointableActorRef - Error in stage (NullPointerException)

### ISSUE THREAD

**Issue by jdanwmal** [akka/akka#26459]
We have the error below happening randomly on an akka stream application (akka version 2.5.18). When the error happens, reprocessing the same data again has no issues, and the stack does not point to any particular line of code on the application side.

```
2019-03-04 14:18:04,270 ERROR a.a.RepointableActorRef - Error in stage [Map(com.x.y.z.XXX$$$Lambda$767/704958629@1a33ccf6)]: null
java.lang.NullPointerException: null
	at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:41)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
2019-03-04 14:18:04,270 ERROR a.s.Materializer - [XXX] Upstream failed.
java.lang.NullPointerException: null
	at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:54)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:45)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:41)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:78)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)

```

Any idea what's going on or how to investigate this?

**Comment by johanandren** [comment]
Looks like line 54 in ops is invoking the supervision strategy "decider", have you configured `SupervisionStrategy` for your stream somehow?

**Comment by jdanwmal** [comment]
Exactly, I checked that but ince in this case the strategy of the decider is quite simple I am not sure how that is interfering. Here is the decider code in any case (only the log message was redacted):

`  val decider: Supervision.Decider = { t: Throwable =>
    logger.error("Blahblahblah", t)
    Supervision.Resume
  }`

**Comment by johanandren** [comment]
And you are not accessing that before it is declared when creating the stream somehow (trait initialization order for example)?

**Comment by jdanwmal** [comment]
Since it is working for hours or even a day before failing I would think that couldn't be the case but after refactoring some initialization code it has not happened again so you are probably right. Thanks @johanandren!

**Comment by johanandren** [comment]
Thanks for letting us know, I'll close this for now then.
