### ISSUE TITLE
DispatcherDocSpec: defining control aware dispatcher

### ISSUE THREAD

**Issue by raboof** [akka/akka#26467]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1364/

```
java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg:
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:420)
[info]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:417)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:896)
[info]   at docs.dispatcher.DispatcherDocSpec$$anon$2.<init>(DispatcherDocSpec.scala:425)
[info]   at docs.dispatcher.DispatcherDocSpec.$anonfun$new$12(DispatcherDocSpec.scala:397)
```

**Comment by patriknw** [comment]
obsolete, not important
