### ISSUE TITLE
PersistentActorJavaDslTest: stopThenLog

### ISSUE THREAD

**Issue by raboof** [akka/akka#26466]
https://jenkins.akka.io:8498/job/akka-nightly/6340/testReport/junit/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/stopThenLog/

```
java.lang.AssertionError: assertion failed: timeout (1 second) during expectStop waiting for actor [akka://PersistentActorJavaDslTest/user/$q] to stop
	at scala.Predef$.assert(Predef.scala:223)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated_internal(TestProbeImpl.scala:318)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:306)
	at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.stopThenLog(PersistentActorJavaDslTest.java:458)
```

**Comment by jrudolph** [comment]
Wrong repo, moved to akka/akka. May be a reoccurrence https://github.com/akka/akka/issues/26030 which might not have been fixed (as mentioned in https://github.com/akka/akka/issues/26030#issuecomment-463567945) by the fix for JDK 11.
