### ISSUE TITLE
Akka occur concurrentmodificationexception when used akka-sharding-cluster ,why

### ISSUE THREAD

**Issue by plutogeek** [akka/akka#26498]
````
2019-03-11 19:17:45,364 CST ERROR srmbqdm02 CODE [QDBS-akka.actor.default-dispatcher-54] Failed to serialize remote message [class akka.actor.ActorSelectionMessage] using serializer [class akka.remote.serialization.MessageContainerSerializer]. Transient association error (association remains live)||akka.remote.EndpointWriter
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class akka.actor.ActorSelectionMessage] using serializer [class akka.remote.serialization.MessageContainerSerializer].
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:63) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.remote.EndpointWriter.$anonfun$serializeMessage$1(Endpoint.scala:906) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.8.jar:?]
        at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:906) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.remote.EndpointWriter.writeSend(Endpoint.scala:793) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:768) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.actor.Actor.aroundReceive(Actor.scala:517) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.actor.Actor.aroundReceive$(Actor.scala:515) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:458) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.actor.ActorCell.invoke(ActorCell.scala:561) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.Mailbox.run(Mailbox.scala:225) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList.writeObject(ArrayList.java:766) ~[?:1.8.0_131]
        at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_131]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_131]
        at akka.serialization.JavaSerializer.$anonfun$toBinary$1(Serializer.scala:324) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.8.jar:?]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.8.jar:?]
        at akka.serialization.JavaSerializer.toBinary(Serializer.scala:324) ~[akka-actor_2.12-2.5.20.jar:2.5.20]
        at akka.remote.serialization.MessageContainerSerializer.serializeSelection(MessageContainerSerializer.scala:37) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.remote.serialization.MessageContainerSerializer.toBinary(MessageContainerSerializer.scala:26) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:53) ~[akka-remote_2.12-2.5.20.jar:2.5.20]
        ... 17 more
2019-03-11 19:17:45,536 CST DEBUG srmbqdm02 CODE [QDBS-akka.actor.default-dispatcher-2] Received gossip status from [akka.tcp://QDBS@x.x.x.x:16669], chunk [1] of [1] containing [InstnCenterActorCoordinatorState]||akka.cluster.ddata.Replicator
2019-03-11 19:17:46,596 CST DEBUG srmbqdm02 CODE [QDBS-akka.actor.default-dispatcher-62] Received gossip status from [akka.tcp://QDBS@x.x.x.x:16669], chunk [1] of [1] containing [InstnCenterActorCoordinatorState]||akka.cluster.ddata.Replicator



````

**Comment by johanandren** [comment]
Hi @plutogeek, we try to use the issue tracker only for issues and feature-tracking, but this is very likely a configuration issue in you project. Please use the [forums](https://discuss.akka.io) or the [gitter channel](https://gitter.im/akka/akka) to get help with questions like this, thanks!
