### ISSUE TITLE
Akka Stream - StreamTestKit.printDebugDump - MatchError 50

### ISSUE THREAD

**Issue by Sciss** [akka/akka#26493]
I am using `StreamTestKit.printDebugDump(materializer.supervisor)` to check the topology of my stream graph. This gives me

```
scala.MatchError: 50 (of class java.lang.Integer)
	at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$4(GraphInterpreter.scala:662)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at akka.stream.impl.fusing.GraphInterpreter.toSnapshot(GraphInterpreter.scala:654)
	at akka.stream.impl.fusing.GraphInterpreterShell.toSnapshot(ActorGraphInterpreter.scala:648)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.$anonfun$applyOrElse$1(ActorGraphInterpreter.scala:755)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:51)
	at scala.collection.SetLike.map(SetLike.scala:104)
	at scala.collection.SetLike.map$(SetLike.scala:104)
	at scala.collection.AbstractSet.map(Set.scala:51)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:755)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
`50 == InClosed | OutClosed | Pulling` which is not covered by the matching function. Akka Stream is `"2.5.21"`, Scala 2.12 JVM.

**Comment by johanandren** [comment]
Thanks for reporting, seems to be something we missed when doing #26364

**Comment by raboof** [comment]
@Sciss good catch! Would you like to contribute a fix?

**Comment by Sciss** [comment]
I don't know this code. Perhaps it should be

```scala
case x if (x | InClosed | OutClosed) != 0 => ConnectionSnapshot.Closed
```
?

**Comment by johanandren** [comment]
The original case had a fallthrough for I-don't-know-what state of the connection, that was missed when I changed this, hovewer, Enno pointed out that they had seen weird stuff with test probes in Alpakka and that there may be something more hiding here, see:
https://github.com/akka/alpakka/pull/1561
