### ISSUE TITLE
QueueSource should limit the current offering on the fly

### ISSUE THREAD

**Issue by hepin1989** [akka/akka#26508]
I got the error below:
```
Caused by: java.lang.IllegalStateException: You have to wait for previous offer to be resolved to send another request
```
With code:
```java
public class WorkQueueTest3 {
    private static final ExecutorService asyncThreadPool;
    private static final ActorSystem actorSystem;
    private static final Materializer materializer;
    private static final SourceQueueWithComplete<Integer> workQueue;

    static {
        //chould be changed to Executors.newFixed...
        asyncThreadPool  = new ThreadPoolExecutor(2   , 32, 60 * 1000,
                                                  TimeUnit.MILLISECONDS,
                                                  new LinkedBlockingDeque<>(100),
                                                  new NamedPoolThreadFactory(
                                                      "integerInsertWorker", true),
                                                  new SaneRejectedExecutionHandler());

        actorSystem = ActorSystem.create(
            "backend");

        materializer = ActorMaterializer.create(actorSystem);

        workQueue = Source.<Integer>queue(100, OverflowStrategy.backpressure())
            .groupedWithin(100, Duration.ofMillis(1))
            .mapAsyncUnordered(4, new Function<List<Integer>, CompletionStage<Integer>>() {
                @Override
                public CompletionStage<Integer> apply(final List<Integer> param) throws Exception {
                    return CompletableFuture.supplyAsync(() -> {
                        System.out.println("onNext on "+Thread.currentThread() + " size :" + param.size());
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        return param.size();
                    },asyncThreadPool);
                }
            })
            .toMat(Sink.foreach(new Procedure<Integer>() {
                @Override
                public void apply(final Integer param) throws Exception {
                    System.out.println("size :"+param);
                }
            }), Keep.left())
        .run(materializer);
    }

    public static void process(int value) throws InterruptedException {
        //System.out.println("process value "+value);
        //Should blocking here
        workQueue.offer(value).toCompletableFuture().join();
    }

    public static void main(String[] args) throws IOException {

        for (int i = 0; i < 100; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int j = 0; j < 1000000; j++) {
                        try {
                            process(j);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            })
            .start();
        }
        System.out.println("read....");
        System.in.read();
    }


}
```
stacktrace:
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: You have to wait for previous offer to be resolved to send another request
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at com.alibaba.wireless.process.message.single.impl.WorkQueueTest3.process(WorkQueueTest3.java:71)
	at com.alibaba.wireless.process.message.single.impl.WorkQueueTest3$3.run(WorkQueueTest3.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: You have to wait for previous offer to be resolved to send another request
	at akka.stream.impl.QueueSource$$anon$1.bufferElem(QueueSource.scala:92)
	at akka.stream.impl.QueueSource$$anon$1.$anonfun$callback$1(QueueSource.scala:105)
	at akka.stream.impl.QueueSource$$anon$1.$anonfun$callback$1$adapted(QueueSource.scala:99)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:450)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:470)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

![image](https://user-images.githubusercontent.com/501740/54227051-08d35c80-453a-11e9-85e5-cf0eccfdd4b8.png)

The real user case is batch db inserting.
I tried with RxJava / Reactor both failed, Akka-stream works, but the first errors with `You have to wait for previous offer to be resolved to send another request` is not funning.

I think the cause is that, when we are doing the offering,  there is no checking about the concurrent offering on the fly.

A better I dear maybe let the offering blocking until there are some space in the buffer. BTW, even we set the buffer of SourceQueue to 0, this happens too.

**Comment by hepin1989** [comment]
What I would like to achieve is the behavior below:

```java
package com.alibaba.wireless.process.message.single.impl;

import akka.actor.ActorSystem;
import akka.japi.function.Creator;
import akka.japi.function.Function;
import akka.japi.function.Procedure;
import akka.stream.ActorMaterializer;
import akka.stream.Materializer;
import akka.stream.javadsl.Keep;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import com.alibaba.wireless.utils.NamedPoolThreadFactory;
import com.taobao.wireless.ripple2.core.util.SaneRejectedExecutionHandler;

import java.io.IOException;
import java.time.Duration;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.*;

/**
 * @author kerr
 **/
public class WorkQueueTest4 {
    private static final ExecutorService asyncThreadPool;
    private static final ActorSystem actorSystem;
    private static final Materializer materializer;
    private static final SynchronousQueue<Integer> workQueue = new SynchronousQueue<Integer>(false);

    static {
        asyncThreadPool  = new ThreadPoolExecutor(2   , 32, 60 * 1000,
                                                  //保活时间是毫秒时间！
                                                  TimeUnit.MILLISECONDS,
                                                  new LinkedBlockingDeque<>(100),
                                                  new NamedPoolThreadFactory(
                                                      "integerInsertWorker", true),
                                                  new SaneRejectedExecutionHandler());

        actorSystem = ActorSystem.create(
            "backend");

        materializer = ActorMaterializer.create(actorSystem);

        Source.<Integer>fromIterator(new Creator<Iterator<Integer>>() {
                @Override
                public Iterator<Integer> create() throws Exception {
                    return new Iterator<Integer>() {
                        @Override
                        public boolean hasNext() {
                            return true;
                        }

                        @Override
                        public Integer next() {
                            try {
                                return workQueue.take();
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            return null;
                        }
                    };
                }
            })
            .groupedWithin(100, Duration.ofMillis(1))
            .mapAsyncUnordered(4, new Function<List<Integer>, CompletionStage<Integer>>() {
                @Override
                public CompletionStage<Integer> apply(final List<Integer> param) throws Exception {
                    return CompletableFuture.supplyAsync(() -> {
                        System.out.println("onNext on "+Thread.currentThread() + " size :" + param.size());
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        return param.size();
                    },asyncThreadPool);
                }
            })
            .toMat(Sink.foreach(new Procedure<Integer>() {
                @Override
                public void apply(final Integer param) throws Exception {
                    System.out.println("size :"+param);
                }
            }), Keep.left())
        .run(materializer);
    }

    public static void process(int value) throws InterruptedException {
        //System.out.println("process value "+value);
        //Should blocking here
        workQueue.put(value);
    }

    public static void main(String[] args) throws IOException {

        for (int i = 0; i < 100; i++) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    for (int j = 0; j < 1000000; j++) {
                        try {
                            process(j);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            })
            .start();
        }
        System.out.println("read....");
        System.in.read();
    }


}

```

**Comment by johanandren** [comment]
Related or possibly duplicate: #25798

**Comment by johanandren** [comment]
I'm not quite sure what you are requesting here @hepin1989, but we won't change `Source.queue` to be blocking, if you want to imperatively push data you will have to do the blocking yourself in your application for the previous `Future/CS` to complete, and also actually look at that value before pushing a new element.

Note that in general it is better to do such logic with pull style, `Source.unfold` for example, where there won't be a next element created until there is demand.

**Comment by hepin1989** [comment]
@johanandren I am not asking for `Source.queue` to be blocking but the returned `CS` should not be completed with error in the first messages.

I want the next type of error never occur.

Caused by: java.lang.IllegalStateException: You have to wait for previous offer to be resolved to send another request

**Comment by hepin1989** [comment]
I think an easy way to complete this is put an `AsyncQueue` in the implementation before sending messages to the sage.
https://github.com/monix/monix/blob/master/monix-execution/shared/src/main/scala/monix/execution/AsyncQueue.scala
