### ISSUE TITLE
Failed: ClusterSingletonPoisonPillSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26572]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/15142/testReport/junit/akka.cluster.typed/ClusterSingletonPoisonPillSpec/A_typed_cluster_singleton_must_support_using_PoisonPill_to_stop/

```
java.lang.AssertionError: assertion failed: timeout (1 second) during expectStop waiting for actor [akka://ClusterSingletonPoisonPillSpec/system/singletonManagersneaky/sneaky] to stop
	at scala.Predef$.assert(Predef.scala:223)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated_internal(TestProbeImpl.scala:328)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectTerminated(TestProbeImpl.scala:310)
	at akka.cluster.typed.ClusterSingletonPoisonPillSpec.$anonfun$new$2(ClusterSingletonPoisonPillSpec.scala:45)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withFixture(ScalaTestWithActorTestKit.scala:23)
	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
	at akka.cluster.typed.ClusterSingletonPoisonPillSpec.runTest(ClusterSingletonPoisonPillSpec.scala:28)
```

**Comment by johanandren** [comment]
Actual cause is: 
```
[ERROR] [03/19/2019 15:58:16.455] [ClusterSingletonPoisonPillSpec-akka.actor.default-dispatcher-22] [akka://ClusterSingletonPoisonPillSpec/system/singletonManagersneaky/sneaky] akka.actor.typed.internal.PoisonPill$ cannot be cast to akka.cluster.typed.ClusterSingletonPoisonPillSpec$GetSelf
java.lang.ClassCastException: akka.actor.typed.internal.PoisonPill$ cannot be cast to akka.cluster.typed.ClusterSingletonPoisonPillSpec$GetSelf
	at akka.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:37)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:465)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:421)
	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:53)
	at akka.actor.typed.internal.PoisonPillInterceptor.aroundReceive(PoisonPill.scala:41)
	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:80)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:465)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:421)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:112)
	at akka.actor.typed.internal.adapter.ActorAdapter.receiveMessage(ActorAdapter.scala:107)
	at akka.actor.typed.internal.adapter.OptimizedActorAdapter.aroundReceive(ActorAdapter.scala:60)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
```

Note that this was in the "optimized actor adapter" from the optimization branch I have, I don't think that could cause it though.

**Comment by johanandren** [comment]
Oh, wait, I take that back, the signal ended up in receive, that's gotta be because of something missed in the optimization.

**Comment by johanandren** [comment]
Closing as it was introduced in the optimization PR (fixed there as well) and not a bug in master
