### ISSUE TITLE
Sort of failed: context accessed before typed actor started

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26586]
It doesn't fail any tests but it must be a consequence of some recent change (poststop?) that causes a few tests in the typed test suite to log this:
```
java.lang.IllegalStateException: Context was accessed before typed actor was started.
	at akka.actor.typed.internal.adapter.ActorAdapter.ctx(ActorAdapter.scala:80)
	at akka.actor.typed.internal.adapter.ActorAdapter.postStop(ActorAdapter.scala:253)
	at akka.actor.Actor.aroundPostStop(Actor.scala:558)
	at akka.actor.Actor.aroundPostStop$(Actor.scala:558)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundPostStop(ActorAdapter.scala:69)
	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:214)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:172)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:142)
	at akka.actor.ActorCell.terminate(ActorCell.scala:445)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:551)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:567)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
I think this was fixed in https://github.com/akka/akka/pull/26590
