### ISSUE TITLE
failed: akka.cluster.typed.ActorSystemSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26614]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/15256

```
[03-26 08:10:33.041] [info] - must terminate the guardian actor *** FAILED *** (97 milliseconds)
[03-26 08:10:33.041] [info]   List() did not equal List("done") (ActorSystemSpec.scala:83)
[03-26 08:10:33.041] [info]   org.scalatest.exceptions.TestFailedException:
[03-26 08:10:33.041] [info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[03-26 08:10:33.042] [info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
[03-26 08:10:33.042] [info]   at akka.cluster.typed.ActorSystemSpec.$anonfun$new$8(ActorSystemSpec.scala:83)
[03-26 08:10:33.042] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[03-26 08:10:33.042] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[03-26 08:10:33.042] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[03-26 08:10:33.042] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[03-26 08:10:33.042] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[03-26 08:10:33.042] [info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[03-26 08:10:33.043] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[03-26 08:10:33.043] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[03-26 08:10:33.043] [info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[03-26 08:10:33.043] [info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[03-26 08:10:33.043] [info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[03-26 08:10:33.043] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[03-26 08:10:33.043] [info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[03-26 08:10:33.043] [info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[03-26 08:10:33.044] [info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[03-26 08:10:33.044] [info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[03-26 08:10:33.044] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[03-26 08:10:33.044] [info]   at scala.collection.immutable.List.foreach(List.scala:392)
[03-26 08:10:33.044] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[03-26 08:10:33.044] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[03-26 08:10:33.044] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[03-26 08:10:33.044] [info]   at scala.collection.immutable.List.foreach(List.scala:392)
[03-26 08:10:33.045] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[03-26 08:10:33.045] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[03-26 08:10:33.045] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[03-26 08:10:33.045] [info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[03-26 08:10:33.045] [info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[03-26 08:10:33.045] [info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[03-26 08:10:33.045] [info]   at org.scalatest.Suite.run(Suite.scala:1124)
[03-26 08:10:33.045] [info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[03-26 08:10:33.045] [info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[03-26 08:10:33.046] [info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[03-26 08:10:33.046] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[03-26 08:10:33.046] [info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[03-26 08:10:33.046] [info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[03-26 08:10:33.046] [info]   at akka.cluster.typed.ActorSystemSpec.org$scalatest$BeforeAndAfterAll$$super$run(ActorSystemSpec.scala:19)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/15261
Probably the same even different spec: akka.actor.typed.internal.ActorSystemSpec

**Comment by patriknw** [comment]
Suspect is https://github.com/akka/akka/pull/26590, since it was recently merged

**Comment by patriknw** [comment]
This fails frequently, I'll look into it
