### ISSUE TITLE
Failed: LeaseProviderSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26636]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/113/testReport/junit/akka.coordination.lease.scaladsl/LeaseProviderSpec/LeaseProvider_must_throw_if_unknown_lease_class_config/

```
Expected exception java.lang.ClassNotFoundException to be thrown, but java.lang.ClassCastException was thrown
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
	at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:61)
	at org.scalatest.Assertions.intercept(Assertions.scala:814)
	at org.scalatest.Assertions.intercept$(Assertions.scala:804)
	at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:61)
	at akka.coordination.lease.scaladsl.LeaseProviderSpec.$anonfun$new$9(LeaseProviderSpec.scala:119)
```

**Comment by raboof** [comment]
This was caused by https://github.com/scala/bug/issues/11242 - adding workaround for now
