### ISSUE TITLE
failed: SupervisorHierarchySpec - restart manager and workers in AllForOne

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26734]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/204/consoleText

```
[info] A Supervisor Hierarchy
[info] - must restart manager and workers in AllForOne *** FAILED *** (2 seconds, 35 milliseconds)
[info]   countDown.await(2L, SECONDS) was false (SupervisorHierarchySpec.scala:773)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
[info]   at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:61)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:503)
[info]   at akka.actor.SupervisorHierarchySpec.$anonfun$new$6(SupervisorHierarchySpec.scala:773)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
[info]   at akka.testkit.package$.filterException(package.scala:41)
[info]   at akka.actor.SupervisorHierarchySpec.$anonfun$new$2(SupervisorHierarchySpec.scala:767)
```

**Comment by patriknw** [comment]
one more, that can't be a coincidence, something must have changed?
https://jenkins.akka.io:8498/job/akka-multi-node/3281/consoleText
