### ISSUE TITLE
Harden loading of ClusterReceptionist

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26750]
Just by introducing a dependency to akka-actor-typed v. 2.5.20 and configuring `provider=cluster` without adding dependency akka-cluster-typed result in the following exception and stack trace:

```
Caused by: java.lang.RuntimeException: ClusterReceptionist could not be loaded dynamically. Make sure you have 'akka-cluster-typed' in the classpath.
	at akka.actor.typed.receptionist.ReceptionistImpl$$anonfun$1.applyOrElse(Receptionist.scala:46)
	at akka.actor.typed.receptionist.ReceptionistImpl$$anonfun$1.applyOrElse(Receptionist.scala:43)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at scala.util.Failure.recover(Try.scala:234)
	at akka.actor.typed.receptionist.ReceptionistImpl.<init>(Receptionist.scala:43)
	at akka.actor.typed.receptionist.Receptionist$.createExtension(Receptionist.scala:113)
	at akka.actor.typed.receptionist.Receptionist$.createExtension(Receptionist.scala:112)
	at akka.actor.typed.internal.ExtensionsImpl.$anonfun$createExtensionInstance$1(ExtensionsImpl.scala:89)
	at scala.Option.getOrElse(Option.scala:138)
	at akka.actor.typed.internal.ExtensionsImpl.createExtensionInstance(ExtensionsImpl.scala:89)
	at akka.actor.typed.internal.ExtensionsImpl.registerExtension(ExtensionsImpl.scala:78)
	at akka.actor.typed.internal.ExtensionsImpl.registerExtension$(ExtensionsImpl.scala:76)
	at akka.actor.typed.internal.adapter.ActorSystemAdapter.registerExtension(ActorSystemAdapter.scala:32)
	at akka.actor.typed.internal.ExtensionsImpl.$anonfun$loadExtensions$1(ExtensionsImpl.scala:45)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at akka.actor.typed.internal.ExtensionsImpl.loadExtensions$1(ExtensionsImpl.scala:39)
	at akka.actor.typed.internal.ExtensionsImpl.loadExtensions(ExtensionsImpl.scala:65)
	at akka.actor.typed.internal.ExtensionsImpl.loadExtensions$(ExtensionsImpl.scala:32)
```

**Comment by patriknw** [comment]
At least we can have an error message saying that the akka-cluster-typed dependency must be added. Might be bad to just ignore and use local receptionist since some functionality will not be enabled as expected.

**Comment by johanandren** [comment]
Isn't that exactly what the error message is saying: `Make sure you have 'akka-cluster-typed' in the classpath.`

**Comment by patriknw** [comment]
LOL
