### ISSUE TITLE
failed: CoordinatedShutdownSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26858]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly2/1423

```
[info] - must terminate ActorSystem *** FAILED *** (10 seconds, 5 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.result(package.scala:146)
[info]   at akka.actor.CoordinatedShutdownSpec.$anonfun$new$44(CoordinatedShutdownSpec.scala
```

Note that this happend before https://github.com/akka/akka/pull/26830 was merged

**Comment by johanandren** [comment]
Tried to reproduce this for a while, thinking it had something to do with the internal dispatcher changes, but no success.

**Comment by helena** [comment]
This may have been related to change https://github.com/akka/akka/commit/a77db34f8f644504c7facf464a92b11d6f5833ce

**Comment by patriknw** [comment]
Closing as old
