### ISSUE TITLE
Failed: LatencySpecMultiJvm 

### ISSUE THREAD

**Issue by johanandren** [akka/akka#26871]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7030/consoleFull

```
must be low for rate-20000-size-100, at 20000 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.LatencySpecMultiJvmNode1) *** FAILED *** (22 seconds, 30 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (22 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$e#1998529531]
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:436)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:433)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:923)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectTerminated(TestKit.scala:451)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectTerminated$(TestKit.scala:450)
[info] [JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:923)
[info] [JVM-1]   at akka.remote.artery.LatencySpec.$anonfun$test$2(LatencySpec.scala:324)
```

**Comment by patriknw** [comment]
Interestingly, this job was running at the same time as https://jenkins.akka.io:8498/job/akka-artery-perf/2164/, which also failed.

Those multi-node jobs are sharing the same multi-node worker nodes.

The performance jobs should not be scheduled at the same time as other multi-node jobs, so I changed the schedule. Also found that `akka-artery-perf` and `akka-artery-tcp-perf` had the same schedule, which I have also changed now.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3455/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3659/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7341/consoleText

**Comment by patriknw** [comment]
LatencySpec: https://jenkins.akka.io:8498/job/akka-artery-tcp-perf/1381

**Comment by patriknw** [comment]
It just halts with 0 msg/s. Failed again, 2 days in a row.
https://jenkins.akka.io:8498/job/akka-artery-tcp-perf/1526
```
[info] [JVM-1] warmup: 6,842 msgs/sec, 684,191 bytes/sec, totals 400,000 messages 38 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 400,000 messages 38 MB
[info] [JVM-1] warmup: 1,651 msgs/sec, 165,133 bytes/sec, totals 401,652 messages 38 MB
[info] [JVM-1] warmup: 9,583 msgs/sec, 958,341 bytes/sec, totals 411,240 messages 39 MB
[info] [JVM-1] warmup: 9,370 msgs/sec, 937,039 bytes/sec, totals 420,615 messages 40 MB
[info] [JVM-1] warmup: 6,229 msgs/sec, 622,873 bytes/sec, totals 426,847 messages 40 MB
[info] [JVM-1] warmup: 2,526 msgs/sec, 252,567 bytes/sec, totals 429,374 messages 40 MB
[info] [JVM-1] warmup: 646 msgs/sec, 64,566 bytes/sec, totals 430,020 messages 41 MB
[info] [JVM-1] warmup: 7,549 msgs/sec, 754,882 bytes/sec, totals 437,573 messages 41 MB
[info] [JVM-1] warmup: 9,579 msgs/sec, 957,859 bytes/sec, totals 447,157 messages 42 MB
[info] [JVM-1] warmup: 9,455 msgs/sec, 945,498 bytes/sec, totals 456,617 messages 43 MB
[info] [JVM-1] warmup: 7,177 msgs/sec, 717,749 bytes/sec, totals 463,798 messages 44 MB
[info] [JVM-2] 70.072: [GC (Allocation Failure) [PSYoungGen: 270993K->9649K(319488K)] 271057K->9721K(1018880K), 0.0180658 secs] [Times: user=0.09 sys=0.02, real=0.01 secs] 
[info] [JVM-1] warmup: 36 msgs/sec, 3,598 bytes/sec, totals 463,834 messages 44 MB
[info] [JVM-1] warmup: 175 msgs/sec, 17,493 bytes/sec, totals 464,009 messages 44 MB
[info] [JVM-1] 72.319: [GC (Allocation Failure) [PSYoungGen: 272499K->10643K(317440K)] 272563K->10715K(1016832K), 0.0178039 secs] [Times: user=0.09 sys=0.03, real=0.02 secs] 
[info] [JVM-1] warmup: 4,399 msgs/sec, 439,887 bytes/sec, totals 468,410 messages 44 MB
[info] [JVM-1] warmup: 54 msgs/sec, 5,397 bytes/sec, totals 468,464 messages 44 MB
[info] [JVM-1] warmup: 7,671 msgs/sec, 767,066 bytes/sec, totals 476,138 messages 45 MB
[info] [JVM-1] warmup: 12,783 msgs/sec, 1,278,324 bytes/sec, totals 488,929 messages 46 MB
[info] [JVM-1] warmup: 9,618 msgs/sec, 961,803 bytes/sec, totals 498,552 messages 47 MB
[info] [JVM-1] warmup: 9,575 msgs/sec, 957,549 bytes/sec, totals 508,132 messages 48 MB
[info] [JVM-1] warmup: 9,489 msgs/sec, 948,915 bytes/sec, totals 517,626 messages 49 MB
[info] [JVM-1] warmup: 9,509 msgs/sec, 950,907 bytes/sec, totals 527,140 messages 50 MB
[info] [JVM-1] warmup: 9,549 msgs/sec, 954,945 bytes/sec, totals 536,694 messages 51 MB
[info] [JVM-1] warmup: 9,541 msgs/sec, 954,085 bytes/sec, totals 546,240 messages 52 MB
[info] [JVM-1] Measured send rate 9211 msg/s (new adjustment factor: 1.9835562463969092)
[info] [JVM-1] warmup: 5,048 msgs/sec, 504,837 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] warmup: 0 msgs/sec, 0 bytes/sec, totals 551,291 messages 52 MB
[info] [JVM-1] - must be low for warmup, at 10000 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.LatencySpecMultiJvmNode1) *** FAILED *** (1 minute, 34 seconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (40 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$c#1476504453]
```

I suspected that it was some conflict with another multi-node job running at the same time, but there were no other.

**Comment by patriknw** [comment]
Closing as old
