### ISSUE TITLE
assertAllStagesStopped triggers ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ennru** [akka/akka#26902]
The stage didn't stop in one of my tests and `assertAllStagesStopped` fails with this for some reason.

This error seems to be triggered by some un-clean termination in Alpakka MQTT Streaming. (See details below)

```
java.lang.ArrayIndexOutOfBoundsException: 67108865
    at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5(GraphInterpreter.scala:688)
    at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5$adapted(GraphInterpreter.scala:688)
    at scala.collection.immutable.List.map(List.scala:282)
    at akka.stream.impl.fusing.GraphInterpreter.toSnapshot(GraphInterpreter.scala:688)
    at akka.stream.impl.fusing.GraphInterpreterShell.toSnapshot(ActorGraphInterpreter.scala:657)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.$anonfun$applyOrElse$1(ActorGraphInterpreter.scala:767)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:319)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:975)
    at scala.collection.TraversableLike.map(TraversableLike.scala:233)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike.map(SetLike.scala:100)
    at scala.collection.SetLike.map$(SetLike.scala:100)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:767)
    at akka.actor.Actor.aroundReceive(Actor.scala:539)
    at akka.actor.Actor.aroundReceive$(Actor.scala:537)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
    at akka.actor.ActorCell.invoke(ActorCell.scala:579)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
    at akka.dispatch.Mailbox.run(Mailbox.scala:229)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

On https://github.com/akka/alpakka/pull/1565/commits/4c0989107856ed0dc206faea96339696bd82c62b this error shows *sometimes* during `testOnly *.MqttSourceSpec -- -z unacked`.

The full log shows 
```
   1   │ 2019-05-10 14:47:15,856 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-3] [akka.event.slf4j.Slf4jLogger]  Slf4jLogger started
   2   │ 2019-05-10 14:47:16,331 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-3] [docs.scaladsl.MqttSourceSpec]  sleeping 2 seconds to make sure we don't get more than expected
   3   │ 2019-05-10 14:47:16,503 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: one-14:47:16.103
   4   │ 2019-05-10 14:47:16,505 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  acked one-14:47:16.103
   5   │ 2019-05-10 14:47:16,509 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: two-14:47:16.103
   6   │ 2019-05-10 14:47:16,510 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  acked two-14:47:16.103
   7   │ 2019-05-10 14:47:16,511 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-14] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Element: three-14:47:16.103
   8   │ 2019-05-10 14:47:18,335 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 1 received] Downstream finished.
   9   │ 2019-05-10 14:47:18,347 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-2] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.ClientConnector$ConnectionLost] without sender to Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321] was not delivered. [1] dead letters encountered. If this is
       │ not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  10   │ 2019-05-10 14:47:18,347 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-2] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.ClientConnector$ConnectionLost] without sender to Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321] was not delivered. [2] dead letters encountered. If this is
       │ not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-connector-1#-1279107321]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  11   │ 2019-05-10 14:47:18,350 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  sleeping 2 seconds to make sure we don't get more than expected
  12   │ 2019-05-10 14:47:18,367 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: three-14:47:16.103
  13   │ 2019-05-10 14:47:18,368 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-2] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: four-14:47:16.103
  14   │ 2019-05-10 14:47:18,368 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-3] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Element: five-14:47:16.103
  15   │ 2019-05-10 14:47:20,351 DEBUG [MqttSourceSpec-akka.actor.default-dispatcher-16] [docs.scaladsl.MqttSourceSpec]  [client 2 received] Downstream finished.
  16   │ 2019-05-10 14:47:20,861 INFO  [MqttSourceSpec-akka.actor.default-dispatcher-15] [akka.actor.RepointableActorRef]  Message [akka.stream.alpakka.mqtt.streaming.impl.RemotePacketRouter$Unregister] without sender to Actor[akka://MqttSourceSpec/user/client-consumer-packet-id-allocator-0#906428085] was not delivered. [3] dead letters encount
       │ ered. If this is not an expected behavior, then [Actor[akka://MqttSourceSpec/user/client-consumer-packet-id-allocator-0#906428085]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
  17   │ 2019-05-10 14:47:25,859 ERROR [MqttSourceSpec-akka.actor.default-dispatcher-15] [akka.actor.OneForOneStrategy]  67108865
  18   │ java.lang.ArrayIndexOutOfBoundsException: 67108865
  19   │     at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5(GraphInterpreter.scala:688)
  20   │     at akka.stream.impl.fusing.GraphInterpreter.$anonfun$toSnapshot$5$adapted(GraphInterpreter.scala:688)
  21   │     at scala.collection.immutable.List.map(List.scala:282)
  22   │     at akka.stream.impl.fusing.GraphInterpreter.toSnapshot(GraphInterpreter.scala:688)
  23   │     at akka.stream.impl.fusing.GraphInterpreterShell.toSnapshot(ActorGraphInterpreter.scala:657)
  24   │     at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.$anonfun$applyOrElse$1(ActorGraphInterpreter.scala:767)
  25   │     at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
  26   │     at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:319)
  27   │     at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:975)
  28   │     at scala.collection.TraversableLike.map(TraversableLike.scala:233)
  29   │     at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
  30   │     at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
  31   │     at scala.collection.SetLike.map(SetLike.scala:100)
  32   │     at scala.collection.SetLike.map$(SetLike.scala:100)
  33   │     at scala.collection.AbstractSet.map(Set.scala:47)
  34   │     at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:767)
  35   │     at akka.actor.Actor.aroundReceive(Actor.scala:539)
  36   │     at akka.actor.Actor.aroundReceive$(Actor.scala:537)
  37   │     at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
  38   │     at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
  39   │     at akka.actor.ActorCell.invoke(ActorCell.scala:579)
  40   │     at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
  41   │     at akka.dispatch.Mailbox.run(Mailbox.scala:229)
  42   │     at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
  43   │     at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  44   │     at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  45   │     at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  46   │     at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
Note that it is a race condition, so not necessarily repeatable.

**Comment by patriknw** [comment]
(maybe start using `Refs` instead of `Fixes`)

**Comment by johanandren** [comment]
Noted
