### ISSUE TITLE
Cannot use Behaviors.withMdc(static, mdcForMessage) together with EventSourcedEntity

### ISSUE THREAD

**Issue by pgabara** [akka/akka#26953]
Tested with Akka 2.5.21

I am getting an error trying to use both `Behaviors.withMdc(static, mdcForMessage)` and `EventSourcedEntity`

```
akka.persistence.RecoveryPermitter$RecoveryPermitGranted$ cannot be cast to mypackage.Command
java.lang.ClassCastException: akka.persistence.RecoveryPermitter$RecoveryPermitGranted$ cannot be cast to mypackage.Command
        at akka.actor.typed.internal.WithMdcBehaviorInterceptor.aroundReceive(WithMdcBehaviorInterceptor.scala:76)
        at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:73)
        at akka.actor.typed.Behavior$.interpret(Behavior.scala:421)
        at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:394)
        at akka.actor.typed.internal.adapter.ActorAdapter.akka$actor$typed$internal$adapter$ActorAdapter$$handleMessage(ActorAdapter.scala:82)
        at akka.actor.typed.internal.adapter.ActorAdapter$$anonfun$running$1.applyOrElse(ActorAdapter.scala:78)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:39)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Use below code snippet to reproduce the issue:
```
Behaviors.setup { ctx =>
      Behaviors.withMdc(Map("test" -> "test"), (_: Command) => Map("test" -> "test"))(
        EventSourcedEntity[Command, Event, State](
          entityTypeKey,
          entityId,
          Init,
          commandHandler,
          eventHandler
        )
      )
    }
```

**Comment by johanandren** [comment]
Another case related to #26867 

I think we should replace the narrow-widen trixery in EventSourcedBehavior with an adapter which would never cause any problems rather than duct-tape this until it works.

**Comment by jchapuis** [comment]
Is there a workaround for the moment? In my case I would need to perform some logic upon definitive persistence failure for an entity and log all commands going through generically. I'm having the same issues when defining my own implementation of BehaviorInterceptor, can't figure out a way to type it right to avoid the runtime issues. Thanks!

**Comment by patriknw** [comment]
@jchapuis I think you should be able to work around it by overriding the `interceptMessageType` method in your `BehaviorInterceptor`. This will change, but as a workaround until then.

**Comment by jchapuis** [comment]
Thanks @patriknw. I've tried a bit but I haven't managed to coerce it into what I need.

Just in case, I'm trying to intercept all messages and signals of an event-sourced behavior. After your comment, the closest I landed was something like below, but still I cannot find a way to propagate those "shadow" messages which escape the actual type:

```scala
Behaviors.intercept(EntityInterceptor(entityContext.entityId))(persistentEntity.eventSourcedEntity(entityContext.entityId)).narrow[Command]
```
and an interceptor like this:

```scala
 private case class EntityInterceptor(entityID: String) extends BehaviorInterceptor[Any, Command] {
    import BehaviorInterceptor._
    override def aroundReceive(ctx: TypedActorContext[Any],
                               msg: Any,
                               target: ReceiveTarget[Command]): Behavior[Command] = {
      logger.debug(s"Entity $entityID receives message $msg")
      msg match {
        case command: Command => target(ctx, command)
        case other => // can't figure out how to propagate the magic message here
      }
    }

    override def aroundSignal(ctx: TypedActorContext[Any],
                              signal: Signal,
                              target: SignalTarget[Command]): Behavior[Command] = {
    // ...
  }
```

Anyhow I guess I'd better pause this until your next iteration on it. Thanks again.

**Comment by jchapuis** [comment]
Btw on a slightly separate note, is there a plan to surface those entity messages into the type somehow, e.g. via some envelope?

**Comment by patriknw** [comment]
@jchapuis My suggestion was more like this:
```scala
  private case class EntityInterceptor(entityID: String) extends BehaviorInterceptor[Command, Command] {
    import BehaviorInterceptor._
    override def aroundReceive(ctx: TypedActorContext[Command],
      msg: Command,
      target: ReceiveTarget[Command]): Behavior[Command] = {
      logger.debug(s"Entity $entityID receives message $msg")
      target(msg)
    }

    override def aroundSignal(ctx: TypedActorContext[Command],
      signal: Signal,
      target: SignalTarget[Command]): Behavior[Command] = {
      target(ctx, signal)
    }

    override def interceptMessageType: Class[_ <: Command] = classOf[Command]
  }
```

It's important that `Command` is a real trait or class, not just a type parameter.

**Comment by patriknw** [comment]
Fixed by https://github.com/akka/akka/pull/27148
