### ISSUE TITLE
failed: CircuitBreakerSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26955]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/8/

```
[info] - must pass through next call and invoke onCallSuccess on success *** FAILED *** (197 milliseconds)
[info]   false did not equal true (CircuitBreakerSpec.scala:568)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6853)
[info]   at akka.pattern.CircuitBreakerSpec$$anonfun$13$$anonfun$apply$mcV$sp$100.apply(CircuitBreakerSpec.scala:568)
[info]   at akka.pattern.CircuitBreakerSpec$$anonfun$13$$anonfun$apply$mcV$sp$100.apply(CircuitBreakerSpec.scala:556)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:61)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1072)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1085)
[info]   at akka.pattern.CircuitBreakerSpec.org$scalatest$BeforeAndAfter$$super$runTest(CircuitBreakerSpec.scala:82)
```

**Comment by johanandren** [comment]
Output improved so hopefully if it fails again we get better info about what happened.

**Comment by SethTisue** [comment]
I recently saw this fail three runs in a row in the Scala community build:

**akka** fail Jun 18
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3528/artifact/logs/akka-build.log
  akka.pattern.CircuitBreakerSpec
**akka** fail Jun 18
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3527/artifact/logs/akka-build.log
  akka.pattern.CircuitBreakerSpec
**akka** fail Jun 18
  https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3526/artifact/logs/akka-build.log
  akka.pattern.CircuitBreakerSpec

there were also failures in April, March, February...

**Comment by ignasi35** [comment]
```
[info] - must reset failure count after success *** FAILED *** (2 seconds, 5 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 2 seconds expired:
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
[info]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
[info]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
[info]   at akka.pattern.CircuitBreakerSpec.f$proxy100$11(CircuitBreakerSpec.scala:645)
[info]   at akka.pattern.CircuitBreakerSpec.$init$$$anonfun$58$$anonfun$5(CircuitBreakerSpec.scala:641)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
```

This started happening on some PR's running the new GHAction to compile and test on scala 3 (probably flaky because it runs on GH actions VMs and unrelated to the fact that's scala 3, though).

**Comment by andreaTP** [comment]
https://github.com/akka/akka/pull/30570/checks?check_run_id=3419518072#step:5:2216

**Comment by andreaTP** [comment]
Can't reproduce in isolation:
https://github.com/andreaTP/akka/actions/runs/1167247905

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3726704646?check_suite_focus=true#step:5:2454

**Comment by johanandren** [comment]
Hmm, the only possible explanation I can see is that it was slow and got reset (500ms reset timeout on the cb under test). Sounds like a long hickup but otoh it doesn't happen often.
