### ISSUE TITLE
failed: ByteStringSpec (Scala 2.13)

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26956]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/12/

Note that it started failing after adding `ByteString.emptyByteString`

```
[info]   must serialize correctly
[info]   - when parsing regular ByteString1C as compat *** FAILED *** (20 milliseconds)
[info]     "...42797465537472696e67[fa3cde45d33a7b45]0200007870757200025b..." was not equal to "...42797465537472696e67[e54813305c6d95cc]0200007870757200025b..." (ByteStringSpec.scala:908)
[info]     org.scalatest.exceptions.TestFailedException:
[info]     at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]     at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
[info]     at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
[info]     at akka.util.ByteStringSpec.$anonfun$new$216(ByteStringSpec.scala:908)
```

**Comment by patriknw** [comment]
same in master: https://jenkins.akka.io:8498/job/akka-nightly-2.13/166/
