### ISSUE TITLE
failed: ReplicatorPruningSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#26975]
https://jenkins.akka.io:8498/job/akka-nightly/6568

```
[info] [JVM-2] [INFO] [05/18/2019 02:50:15.526] [ReplicatorPruningSpec-akka.actor.internal-dispatcher-18] [akka.cluster.Cluster(akka://ReplicatorPruningSpec)] Cluster Node [akka://ReplicatorPruningSpec@localhost:37185] - is the new leader among reachable nodes (more leaders may exist)
[info] [JVM-1] - must move data from removed node *** FAILED *** (4 seconds, 35 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for UpdateSuccess(A,None)
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:395)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:395)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:923)
[info] [JVM-1]   at akka.cluster.ddata.ReplicatorPruningSpec.$anonfun$new$2(ReplicatorPruningSpec.scala:94)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-1]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-1]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info] [JVM-1]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] [JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] [JVM-1]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] [JVM-1]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info] [JVM-1]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info] [JVM-1]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info] [JVM-1]   at akka.cluster.ddata.ReplicatorPruningSpec.withFixture(ReplicatorPruningSpec.scala:35)
[info] [JVM-1]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info] [JVM-1]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info] [JVM-1]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info] [JVM-1]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info] [JVM-1]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info] [JVM-1]   at akka.cluster.ddata.ReplicatorPruningSpec.runTest(ReplicatorPruningSpec.scala:35)
[info] [JVM-1]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info] [JVM-1]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info] [JVM-1]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-1]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info] [JVM-1]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info] [JVM-1]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info] [JVM-1]   at scala.collection.immutable.List.foreach(List.scala:392)
[info] [JVM-1]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info] [JVM-1]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info] [JVM-1]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info] [JVM-1]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info] [JVM-1]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info] [JVM-1]   at akka.cluster.ddata.ReplicatorPruningSpec.runTests(ReplicatorPruningSpec.scala:35)
[info] [JVM-1]   at org.scalatest.Suite.run(Suite.scala:1124)
[info] [JVM-1]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info] [JVM-1]   at akka.cluster.ddata.ReplicatorPruningSpec.org$scalatest$WordSpecLike$$super$run(ReplicatorPruningSpec.scala:35)

```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/212/consoleFull

**Comment by patriknw** [comment]
The change in https://github.com/akka/akka/pull/27829 didn't fix the problem if it's anything else than a spurious timeout, but since this hasn't occurred for a rather long time I'll close the issue and we can revisit if it happens again.
