### ISSUE TITLE
Failed: TcpSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27031]
https://jenkins.akka.io:8498/job/akka-nightly/6595/consoleText

```
--> [[34mOutgoing TCP stream must provide full exceptions when connection attempt fails because name cannot be resolved[0m] Start of log messages of test that [Failed(org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100 milliseconds between each query.)]
| [DEBUG] [05/27/2019 02:07:13.757] [pool-1-thread-1-ScalaTest-running-TcpSpec] [WithLogCapturing(akka://TcpSpec)] Logging started for test [Outgoing TCP stream must provide full exceptions when connection attempt fails because name cannot be resolved]
| [DEBUG] [05/27/2019 02:07:13.758] [TcpSpec-akka.actor.internal-dispatcher-26] [akka://TcpSpec/system/IO-TCP/selectors/$a] Executing [WorkerForCommand(Connect(abcdefghijklmnopkuh:12345,None,List(),None,true),Actor[akka://TcpSpec/system/StreamSupervisor-520/$$u#-233754729],akka.io.TcpManager$$anonfun$receive$1$$Lambda$930/131925385@48649795)]
| [DEBUG] [05/27/2019 02:07:13.759] [TcpSpec-akka.actor.internal-dispatcher-2] [akka://TcpSpec/system/IO-TCP/selectors/$a] Scheduling Registering channel java.nio.channels.SocketChannel[unconnected] with initialOps 0
| [DEBUG] [05/27/2019 02:07:13.759] [TcpSpec-akka.io.pinned-dispatcher-10] [akka://TcpSpec/system/IO-TCP/selectors/$a] Registering channel java.nio.channels.SocketChannel[unconnected] with initialOps 0
| [DEBUG] [05/27/2019 02:07:13.759] [TcpSpec-akka.actor.internal-dispatcher-2] [akka://TcpSpec/system/IO-TCP/selectors/$a/45] Resolving abcdefghijklmnopkuh before connecting
| [DEBUG] [05/27/2019 02:07:13.759] [TcpSpec-akka.actor.internal-dispatcher-26] [akka://TcpSpec/system/IO-DNS] Resolution request for abcdefghijklmnopkuh from Actor[akka://TcpSpec/system/IO-TCP/selectors/$a/45#-1946874741]
| [DEBUG] [05/27/2019 02:07:18.765] [pool-1-thread-1-ScalaTest-running-TcpSpec] [WithLogCapturing(akka://TcpSpec)] Logging finished for test [Outgoing TCP stream must provide full exceptions when connection attempt fails because name cannot be resolved]

- must provide full exceptions when connection attempt fails because name cannot be resolved *** FAILED *** (5 seconds, 12 milliseconds)
[info] A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100 milliseconds between each query. (TcpSpec.scala:518)
[info] org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info] at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
[info] at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info] at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info] at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info] at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info] at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info] at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info] at akka.stream.io.TcpSpec.$anonfun$new$47(TcpSpec.scala:518)
[info] at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info] at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info] at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info] at org.scalatest.Transformer.apply(Transformer.scala:22)
[info] at org.scalatest.Transformer.apply(Transformer.scala:20)
[info] at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info] at akka.testkit.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:35)
[info] at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
[info] at akka.testkit.WithLogCapturing.withFixture(WithLogCapturing.scala:33)
[info] at akka.testkit.WithLogCapturing.withFixture$(WithLogCapturing.scala:20)
[info] at akka.stream.io.TcpSpec.withFixture(TcpSpec.scala:32)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6610/testReport/junit/akka.stream.io/TcpSpec/Outgoing_TCP_stream_must_provide_full_exceptions_when_connection_attempt_fails_because_name_cannot_be_resolved/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6619/consoleFull

**Comment by chbatey** [comment]
My guess for this, based on the logs, is that it is timing out as the resolution is failing in the InetResolver. The test timeout for the `futureValue` is 5s but linux will try each name server twice with a timeout of 5s before failing.

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6689/testReport/junit/akka.stream.io/TcpSpec/Outgoing_TCP_stream_must_provide_full_exceptions_when_connection_attempt_fails_because_name_cannot_be_resolved/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/6719/consoleText
