### ISSUE TITLE
Testing persistent actors with BehaviorTestKit

### ISSUE THREAD

**Issue by michal-szturo** [akka/akka#27078]
Hi,

Sorry if I do not submit this issue correctly as this is my first time reporting.
I was testing typed persistent actors and trying to check the logging with BehaviorTestKit and encountered an exception with adapting typed/untyped system. It worked on normal typed actors and since the persistence was also typed I was expecting all the system conversions to work in similar fashion.

Here's the stack trace:
```
only adapted untyped ActorSystem permissible (Actor[akka://StubbedActorContext/user#0] of class akka.actor.testkit.typed.internal.ActorSystemStub)
java.lang.UnsupportedOperationException: only adapted untyped ActorSystem permissible (Actor[akka://StubbedActorContext/user#0] of class akka.actor.testkit.typed.internal.ActorSystemStub)
	at akka.actor.typed.internal.adapter.ActorSystemAdapter$.toUntyped(ActorSystemAdapter.scala:147)
	at akka.actor.typed.scaladsl.adapter.package$TypedActorSystemOps$.toUntyped$extension(package.scala:77)
	at akka.persistence.typed.internal.BehaviorSetup.<init>(BehaviorSetup.scala:59)
	at akka.persistence.typed.internal.EventSourcedBehaviorImpl.$anonfun$apply$3(EventSourcedBehaviorImpl.scala:126)
	at akka.actor.typed.Behavior$DeferredBehavior$$anon$1.apply(Behavior.scala:264)
	at akka.actor.typed.Behavior$.start(Behavior.scala:331)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:45)
	at akka.actor.typed.internal.AbstractSupervisor.aroundStart(Supervision.scala:72)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:68)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:25)
	at akka.actor.typed.Behavior$DeferredBehavior$$anon$1.apply(Behavior.scala:264)
	at akka.actor.typed.Behavior$.start(Behavior.scala:331)
	at akka.actor.testkit.typed.internal.BehaviorTestKitImpl.<init>(BehaviorTestKitImpl.scala:36)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKit$.apply(BehaviorTestKit.scala:22)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKit$.apply(BehaviorTestKit.scala:25)
	(...)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withFixture(ScalaTestWithActorTestKit.scala:23)
	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
	(...)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
	(...)
	at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
	(...)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:23)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	(...)
	at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
	(...)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```
Is it something I miss here, or is it a bug?

**Comment by patriknw** [comment]
That's currently not supported. Eventually we would like to a synchronous testkit for EventSourcedBehavior and the ticket for that is https://github.com/akka/akka/issues/23712
