### ISSUE TITLE
No configured serialization-bindings for class TimerSchedulerImpl$TimerMsg

### ISSUE THREAD

**Issue by xeppaka** [akka/akka#27153]
When `serialize-messages = on` is set in config for tests, an error appears in the log:

`Caused by: java.io.NotSerializableException: No configured serialization-bindings for class [akka.actor.typed.internal.TimerSchedulerImpl$TimerMsg]`

A class TimerSchedulerImpl$TimerMsg should extend NoSerializationVerification probably if it's local only message.
akka-typed-cluster version: 2.5.23

the whole exception:
`
2019-06-17T10:29:35,340 [:] [] [ERROR] akka.actor.typed.internal.adapter.ActorAdapter swallowing exception during message send
akka.actor.dungeon.SerializationCheckFailedException: Failed to serialize and deserialize message of type akka.actor.typed.internal.TimerSchedulerImpl$TimerMsg for testing. To avoid this error, either disable 'akka.actor.serialize-messages', mark the message with 'akka.actor.NoSerializationVerificationNeeded', or configure serialization to support this message
        at akka.actor.dungeon.SerializationCheckFailedException$.apply(Dispatch.scala:26)
        at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:175)
        at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:155)
        at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:152)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
        at akka.actor.Cell.sendMessage(ActorCell.scala:363)
        at akka.actor.Cell.sendMessage$(ActorCell.scala:362)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
        at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:177)
        at akka.actor.typed.internal.adapter.ActorRefAdapter.tell(ActorRefAdapter.scala:27)
        at akka.actor.typed.ActorRef$ActorRefOps$.$bang$extension(ActorRef.scala:67)
        at akka.actor.typed.internal.TimerSchedulerImpl.$anonfun$startTimer$1(TimerSchedulerImpl.scala:80)
        at akka.actor.Scheduler$$anon$2.run(Scheduler.scala:105)
        at akka.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:104)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:85)
        at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:125)
        at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:84)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:334)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:285)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:289)
        at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:241)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.NotSerializableException: No configured serialization-bindings for class [akka.actor.typed.internal.TimerSchedulerImpl$TimerMsg]
        at akka.serialization.Serialization.serializerFor(Serialization.scala:332)
        at akka.serialization.Serialization.findSerializerFor(Serialization.scala:307)
        at akka.actor.dungeon.Dispatch.serializeAndDeserializePayload(Dispatch.scala:186)
        at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:173)
        ... 21 common frames omitted
`

**Comment by patriknw** [comment]
Ok, it should be marked with `NoSerializationVerificationNeeded`. Would you be able to contribute with a pull request fixing that, @xeppaka ?

**Comment by xeppaka** [comment]
> Ok, it should be marked with `NoSerializationVerificationNeeded`. Would you be able to contribute with a pull request fixing that, @xeppaka ?

Sure

**Comment by patriknw** [comment]
While we could fix this for 2.5.x branch I'm afraid that there will be many more such messages in `-typed` modules. I'm  afraid we have to say that the `serialize-messages` testing features is not supported for Akka Typed in 2.5.x. It  will work in Akka 2.6 and we have published milestones if you want to switch now rather than waiting for upcoming 2.6.0.
