### ISSUE TITLE
Error in stage [Partition(3)]: Cannot pull closed port

### ISSUE THREAD

**Issue by klappvisor** [akka/akka#27189]
I have seen multiple errors happening in our Akka deployment.

We are using Akka 2.5.14 and Akka Remote with Artery via TCP.

```
ERROR akka.actor.RepointableActorRef [akka://Agent/system/StreamSupervisor-0/remote-53356-0-map] Error in stage [Partition(3)]: Cannot pull closed port (Partition.in(854632
497))
java.lang.IllegalArgumentException: Cannot pull closed port (Partition.in(854632497))
        at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:465)
        at akka.stream.scaladsl.Partition$$anon$6$$anon$23.onDownstreamFinish(Graph.scala:815)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:494)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by raboof** [comment]
Interesting! It would be good to check whether this problem is still present in 2.5.23. I can't remember any fixes in this particular area, but Akka 2.5.14 was released in July last year, so there might have been changes.

It would be very useful if you could provide a minimal reproducer showing the problems, so we can run it with 2.5.23 and continue to diagnose from there.

**Comment by klappvisor** [comment]
I am afraid I don't have an easy way to reproduce this. We are not using Akka Streams directly, but these are libraries that are used.

akka-actor: 2.5.14
akka-remote: 2.5.14
akka-http-core: 10.1.3

**Comment by patriknw** [comment]
By looking at the stacktrace and the code for Partition I think I see what is wrong. I'll give it a try.
