### ISSUE TITLE
Failed: TypedActorRemoteDeploySpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27340]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/224/testReport/junit/akka.remote/TypedActorRemoteDeploySpec/Typed_actors_must_be_possible_to_deploy_remotely_and_communicate_with/

```
Future timed out after [3 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:200)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.result(package.scala:124)
	at akka.remote.TypedActorRemoteDeploySpec.verify(TypedActorRemoteDeploySpec.scala:51)
	at akka.remote.TypedActorRemoteDeploySpec.$anonfun$new$2(TypedActorRemoteDeploySpec.scala:61)
```

**Comment by chbatey** [comment]
For some reason, this test only ran on 213/211 so was missed that it uses java serialization (typed actors appear to internally). Will allow java serialization as i don't think we should spend time making typed actors work without it
