### ISSUE TITLE
[2.5.23] ActorSystem in  TestKit cannot be shut down

### ISSUE THREAD

**Issue by marekzebrowski** [akka/akka#27358]
I have a test using ActorSystem. When test finishes, it is expected to shutdown ActorSystem  using scalaTest `afterAll` function
```
TestKit.shutdownActorSystem(actorSystem, duration = 25.seconds, verifySystemShutdown = false)
```

The same testcase shuts down actor system succesfully in akka 2.5.22, but fails to shutdown in 2.5.23 - no mater what time it is given

Logs from 2.5.23:
```
14:20:43.275 DEBUG a.a.LocalActorRef: unhandled message from Actor[akka://sgActors/deadLetters]: Down(akka://sgActors@127.0.0.1:40669)
14:20:43.282 DEBUG a.a.LocalActorRefProvider$Guardian: stopping
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.285 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.287 DEBUG a.r.ResizablePoolActor: stopping
14:20:43.288 DEBUG a.r.ResizablePoolActor: stopped
14:20:43.288 DEBUG a.a.LocalActorRefProvider$Guardian: stopped
14:20:43.293 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
14:20:43.298 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
14:20:43.298 DEBUG a.r.a.a.ArteryAeronUdpTransport(akka://sgActors): Shutting down [akka://sgActors@127.0.0.1:40669#9086416273363290353]
14:20:43.312 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.317 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.318 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.357 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
14:20:43.358 DEBUG a.e.EventStream: shutting down: StandardOutLogger
```

state that is reported by failed actor system termination

```
Failed to stop [sgActors] within [25 seconds] 
-> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=2 Terminating(UserRequest)
       |    toDie: Actor[akka://sgActors/system/IO-TCP#-1393770779]
       |           Actor[akka://sgActors/system/StreamSupervisor-0#2106731697]
       |           Actor[akka://sgActors/system/StreamSupervisor-1#-1937061650]
       |           Actor[akka://sgActors/system/StreamSupervisor-10#-1490812215]
       |           Actor[akka://sgActors/system/StreamSupervisor-11#-254200562]
       |           Actor[akka://sgActors/system/StreamSupervisor-12#-1551423715]
       |           Actor[akka://sgActors/system/StreamSupervisor-13#1737096192]
       |           Actor[akka://sgActors/system/StreamSupervisor-14#-1072304513]
       |           Actor[akka://sgActors/system/StreamSupervisor-15#-1468175561]
       |           Actor[akka://sgActors/system/StreamSupervisor-16#-389603246]
       |           Actor[akka://sgActors/system/StreamSupervisor-17#-107339488]
       |           Actor[akka://sgActors/system/StreamSupervisor-2#1742195351]
       ⌊-> IO-TCP RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-0 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-1 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-10 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-11 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-12 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-13 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-14 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-15 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-16 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-17 RepointableActorRef null status=1 terminated
       ⌊-> StreamSupervisor-2 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 Terminating(UserRequest)
       |   |    toDie: Actor[akka://sgActors/system/StreamSupervisor-2/flow-7-0-ignoreSink#1646286883]
       |   ⌊-> flow-7-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
       ⌊-> StreamSupervisor-3 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-4 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-5 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-6 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-7 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-8 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> StreamSupervisor-9 RepointableActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> UnhandledMessageForwarder RepointableActorRef class akka.event.LoggingBus$$anon$1 status=0 no children
       ⌊-> cluster RepointableActorRef class akka.cluster.ClusterDaemon status=0 12 children
       |   ⌊-> $a LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $b LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $c LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $d LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $e LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $f LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $g LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $h LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $i LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> $j LocalActorRef class akka.cluster.OnMemberStatusChangedListener status=0 no children
       |   ⌊-> core LocalActorRef class akka.cluster.ClusterCoreSupervisor status=0 2 children
       |   |   ⌊-> daemon LocalActorRef class akka.cluster.ClusterCoreDaemon status=0 no children
       |   |   ⌊-> publisher LocalActorRef class akka.cluster.ClusterDomainEventPublisher status=0 no children
       |   ⌊-> heartbeatReceiver LocalActorRef class akka.cluster.ClusterHeartbeatReceiver status=0 no children
       ⌊-> clusterEventBusListener RepointableActorRef class akka.cluster.ClusterReadView$$anon$1 status=0 no children
       ⌊-> ddataReplicator RepointableActorRef class akka.cluster.ddata.Replicator status=0 no children
       ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
       ⌊-> distributedPubSubMediator RepointableActorRef class akka.cluster.pubsub.DistributedPubSubMediator status=0 no children
       ⌊-> eventStreamUnsubscriber-1 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
       ⌊-> log1-Slf4jLogger RepointableActorRef null status=1 terminated
       ⌊-> pool-master RepointableActorRef class akka.http.impl.engine.client.PoolMasterActor status=0 no children
       ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
       ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children
       ⌊-> remoting-terminator RepointableActorRef null status=1 terminated
       ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 13 children
       |   ⌊-> Shard1Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard1ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       |   ⌊-> Shard2Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard2ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       |   ⌊-> Shard3Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard3ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       |   ⌊-> Shard4Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard4ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       |   ⌊-> Shard5Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard5ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       |   ⌊-> shardsReplicator LocalActorRef class akka.cluster.ddata.Replicator status=0 1 children
       |   |   ⌊-> durableStore LocalActorRef class akka.cluster.ddata.LmdbDurableStore status=0 no children
       |   ⌊-> Shard6Actor LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
       |   ⌊-> Shard6ActorCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 no children
       ⌊-> testProbe-1 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-2 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-3 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-4 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-5 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-6 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-7 RepointableActorRef class akka.testkit.TestActor status=0 no children
       ⌊-> testProbe-8 RepointableActorRef class akka.testkit.TestActor status=0 no children
```

Logs from 2.5.22:

```
14:20:43.275 DEBUG a.a.LocalActorRef: unhandled message from Actor[akka://sgActors/deadLetters]: Down(akka://sgActors@127.0.0.1:40669)
14:20:43.282 DEBUG a.a.LocalActorRefProvider$Guardian: stopping
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.283 DEBUG a.c.s.ClusterSingletonProxy: stopped
14:20:43.285 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.286 DEBUG a.c.s.ClusterSingletonManager: stopped
14:20:43.287 DEBUG a.r.ResizablePoolActor: stopping
14:20:43.288 DEBUG a.r.ResizablePoolActor: stopped
14:20:43.288 DEBUG a.a.LocalActorRefProvider$Guardian: stopped
14:20:43.293 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
14:20:43.298 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
14:20:43.298 DEBUG a.r.a.a.ArteryAeronUdpTransport(akka://sgActors): Shutting down [akka://sgActors@127.0.0.1:40669#9086416273363290353]
14:20:43.312 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.317 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.318 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.322 DEBUG a.s.i.f.ActorGraphInterpreter: stopped
14:20:43.357 INFO  a.r.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
14:20:43.358 DEBUG a.e.EventStream: shutting down: StandardOutLogger
```

I didn't manage to minimize the testcase yet. but I'd be very happy  debug the problem. Is there a way to go into the actor system state waiting for termination?  "Failed to stop" logs suggests that IO, and StreamSupoervisors are waiting to die unsuccesfully.

**Comment by johanandren** [comment]
Does a thread dump when stuck shutting down shed any light on it? (stream operators blocking perhaps?)

**Comment by marekzebrowski** [comment]
Thanks for hint - @johanandren . it turned out that CallingThreadDispatcher was used as `stream.materializer.dispatcher`.  I guess it is not supported. I'm closing the ticket

**Comment by marekzebrowski** [comment]
Just for reference: thread dump disclosed deadlock:
```
Found one Java-level deadlock:
=============================
"sgActors-akka.actor.default-dispatcher-2":
  waiting for ownable synchronizer 0x000000061e558818, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "sgActors-akka.actor.default-dispatcher-29"
"sgActors-akka.actor.default-dispatcher-29":
  waiting for ownable synchronizer 0x000000061e54e9d8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "sgActors-akka.actor.default-dispatcher-2"

Java stack information for the threads listed above:
===================================================
"sgActors-akka.actor.default-dispatcher-2":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x000000061e558818> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.3/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:980)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:1288)
	at java.util.concurrent.locks.ReentrantLock.tryLock(java.base@11.0.3/ReentrantLock.java:424)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:304)
	at akka.testkit.CallingThreadDispatcher.systemDispatch(CallingThreadDispatcher.scala:218)
	at akka.actor.dungeon.Dispatch.stop(Dispatch.scala:149)
	at akka.actor.dungeon.Dispatch.stop$(Dispatch.scala:148)
	at akka.actor.ActorCell.stop(ActorCell.scala:447)
	at akka.actor.RepointableActorRef.stop(RepointableActorRef.scala:131)
	at akka.actor.dungeon.Children.stop(Children.scala:127)
	at akka.actor.dungeon.Children.stop$(Children.scala:115)
	at akka.actor.ActorCell.stop(ActorCell.scala:447)
	at akka.actor.dungeon.FaultHandling.$anonfun$terminate$1(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling.$anonfun$terminate$1$adapted(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling$$Lambda$9720/0x0000000841ec1040.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at akka.util.Collections$PartialImmutableValuesIterable$$anon$1.foreach(Collections.scala:27)
	at akka.util.Collections$PartialImmutableValuesIterable.foreach(Collections.scala:52)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:143)
	at akka.actor.ActorCell.terminate(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:553)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.testkit.CallingThreadDispatcher.process$1(CallingThreadDispatcher.scala:273)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:313)
	at akka.testkit.CallingThreadDispatcher.systemDispatch(CallingThreadDispatcher.scala:218)
	at akka.actor.dungeon.Dispatch.stop(Dispatch.scala:149)
	at akka.actor.dungeon.Dispatch.stop$(Dispatch.scala:148)
	at akka.actor.ActorCell.stop(ActorCell.scala:447)
	at akka.actor.RepointableActorRef.stop(RepointableActorRef.scala:131)
	at akka.actor.dungeon.Children.stop(Children.scala:127)
	at akka.actor.dungeon.Children.stop$(Children.scala:115)
	at akka.actor.ActorCell.stop(ActorCell.scala:447)
	at akka.actor.dungeon.FaultHandling.$anonfun$terminate$1(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling.$anonfun$terminate$1$adapted(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling$$Lambda$9720/0x0000000841ec1040.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at akka.util.Collections$PartialImmutableValuesIterable$$anon$1.foreach(Collections.scala:27)
	at akka.util.Collections$PartialImmutableValuesIterable.foreach(Collections.scala:52)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:151)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:143)
	at akka.actor.ActorCell.terminate(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:553)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:271)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
"sgActors-akka.actor.default-dispatcher-29":
	at jdk.internal.misc.Unsafe.park(java.base@11.0.3/Native Method)
	- parking to wait for  <0x000000061e54e9d8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.3/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:980)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(java.base@11.0.3/AbstractQueuedSynchronizer.java:1288)
	at java.util.concurrent.locks.ReentrantLock.tryLock(java.base@11.0.3/ReentrantLock.java:424)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:304)
	at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:234)
	at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:158)
	at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:152)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
	at akka.actor.Cell.sendMessage(ActorCell.scala:363)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:362)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
	at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:177)
	at akka.stream.stage.GraphStageLogic$StageActor.stop(GraphStage.scala:283)
	at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1277)
	at akka.stream.stage.TimerGraphStageLogic.afterPostStop(GraphStage.scala:1559)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:580)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:560)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:465)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.testkit.CallingThreadDispatcher.process$1(CallingThreadDispatcher.scala:280)
	at akka.testkit.CallingThreadDispatcher.runQueue(CallingThreadDispatcher.scala:313)
	at akka.testkit.CallingThreadDispatcher.dispatch(CallingThreadDispatcher.scala:234)
	at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:158)
	at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:152)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
	at akka.actor.Cell.sendMessage(ActorCell.scala:363)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:362)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:447)
	at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:177)
	at akka.stream.impl.fusing.GraphInterpreterShell.$anonfun$interpreter$1(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.$anonfun$interpreter$1$adapted(ActorGraphInterpreter.scala:517)
	at akka.stream.impl.fusing.GraphInterpreterShell$$Lambda$922/0x0000000840e1a440.apply(Unknown Source)
	at akka.stream.stage.GraphStageLogic$ConcurrentAsyncCallback.onAsyncInput(GraphStage.scala:1186)
	at akka.stream.stage.GraphStageLogic$ConcurrentAsyncCallback.invokeWithPromise(GraphStage.scala:1177)
	at akka.stream.stage.GraphStageLogic$ConcurrentAsyncCallback.invoke(GraphStage.scala:1170)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$functionRef$1(GraphStage.scala:231)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$functionRef$1$adapted(GraphStage.scala:222)
	at akka.stream.stage.GraphStageLogic$StageActor$$Lambda$1514/0x00000008410c8840.apply(Unknown Source)
	at akka.actor.FunctionRef.$bang(ActorRef.scala:737)
	at akka.actor.FunctionRef.sendSystemMessage(ActorRef.scala:746)
	at akka.actor.dungeon.DeathWatch.sendTerminated$1(DeathWatch.scala:141)
	at akka.actor.dungeon.DeathWatch.$anonfun$tellWatchersWeDied$2(DeathWatch.scala:157)
	at akka.actor.dungeon.DeathWatch.$anonfun$tellWatchersWeDied$2$adapted(DeathWatch.scala:157)
	at akka.actor.dungeon.DeathWatch$$Lambda$9735/0x0000000841ecc040.apply(Unknown Source)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at akka.actor.dungeon.DeathWatch.tellWatchersWeDied(DeathWatch.scala:157)
	at akka.actor.dungeon.DeathWatch.tellWatchersWeDied$(DeathWatch.scala:133)
	at akka.actor.ActorCell.tellWatchersWeDied(ActorCell.scala:447)
	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:222)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:173)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:143)
	at akka.actor.ActorCell.terminate(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:553)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Found 1 deadlock.
```

**Comment by johanandren** [comment]
Good that you figured it out and thanks for sharing!

**Comment by dr-jerry** [comment]
I'm facing same behaviour when using scala 2.13,
scalaVersion := "2.12.6" works fine.
scalaVersion := "2.13.3" does not finish test and display results.
val akkaVersion = "2.6.9"
val scalaTest = "3.2.0"
