### ISSUE TITLE
2.6.0-M4 No configuration setting found for key 'akka.remote.use-dispatcher'

### ISSUE THREAD

**Issue by michael-read** [akka/akka#27369]
Testing Akka Typed w/ Mulit-JVM test: seeing the following error on each JVM as they start:
```
[JVM-1] [ERROR] [07/17/2019 16:03:23.159] [ArtifactStatesSpec-akka.actor.default-dispatcher-15] [TaskInvocation] merge of hardcoded value,reference.conf @ jar:file:/home/michael/Downloads/Projects/akka-typed-blog-distributed-state/target/multi-run-copied-libraries/akka-remote_2.12-2.6.0-M4.jar!/reference.conf: 178-747: No configuration setting found for key 'akka.remote.use-dispatcher'
[JVM-1] com.typesafe.config.ConfigException$Missing: merge of hardcoded value,reference.conf @ jar:file:/home/michael/Downloads/Projects/akka-typed-blog-distributed-state/target/multi-run-copied-libraries/akka-remote_2.12-2.6.0-M4.jar!/reference.conf: 178-747: No configuration setting found for key 'akka.remote.use-dispatcher'
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
[JVM-1] 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker.$anonfun$checkRemoteDispatcher$1(ConfigChecker.scala:634)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker.ifEnabled(ConfigChecker.scala:243)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker.checkRemoteDispatcher(ConfigChecker.scala:632)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker.checkRemote(ConfigChecker.scala:619)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker.check(ConfigChecker.scala:232)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker$.runChecks$1(ConfigChecker.scala:79)
[JVM-1] 	at com.lightbend.akka.diagnostics.ConfigChecker$.$anonfun$reportIssues$3(ConfigChecker.scala:97)
[JVM-1] 	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:470)
[JVM-1] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
[JVM-1] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
[JVM-1] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[JVM-1] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[JVM-1] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[JVM-1] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
I've disabled Cinnamon to make sure there wasn't a conflict. The project can be tested on internal Lightbend repo project https://github.com/lightbend/akka-typed-distributed-state-blog, on branch `akka-2.6`.
```docker-compose -f docker-compose-cassandra.yml up```
Before
```sbt multi-jvm:test```

**Comment by michael-read** [comment]
This isn't just about multi-jvm, I just tried running both node types locally as described in the README.md for the project, and both produce the same error on start. 

On branch akka-2.6:
```
docker-compose -f docker-compose-cassandra.yml up
```
To start the entity cluster:
```
sbt '; set javaOptions += "-Dconfig.resource=cluster-application.conf" ; run'
```
To start the HTTP server:
```
sbt '; set javaOptions += "-Dconfig.resource=endpoint-application.conf" ; run'
```

**Comment by raboof** [comment]
> com.lightbend.akka.diagnostics.ConfigChecker

Aaah looks like it's the enhancements that haven't been updated for 2.6

**Comment by chbatey** [comment]
Let's close this and track it in enhancements, thanks for reporting @michael-read
