### ISSUE TITLE
Annotate akka.actor.typed.SpawnProtocol$Spawn with NoSerializationVerificationNeeded 

### ISSUE THREAD

**Issue by schernichkin** [akka/akka#27425]
Version:
```Scala
val akkaVersion = "2.6.0-M4"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.typesafe.akka" %% "akka-actor-typed" % akkaVersion)
```

`serialize-messages = on` configuration property can be used to verify message serialization. However `akka.actor.typed.SpawnProtocol$Spawn` message not annotated with `NoSerializationVerificationNeeded`. In general `Spawn` will not be serializable, because it contain `Behavior[T]` field and build-in behavior classes are not serializable. And it does not meant to be serializable because Spawn message should be send to local actor system to spawn local actors. Lack of `NoSerializationVerificationNeeded` annotation prevents from using `serialize-messages = on` property to verify message serialization.

Steps to reproduce: 
1. Add following configuration property:
```
akka {
  actor {
    serialize-messages = on
  }
}
```
2. Create actor system with Spawn protocol:
```Scala
val system = ActorSystem(SpawnProtocol.behavior, "localsystem")
```
3. Spawn typed actor:
```Scala
var actorRef = system ? SpawnProtocol.Spawn(behavior = Behaviors.stopped[Unit], "")
```

Expected result:
Actor should be spawned normally.

Actual result: 
```
[ERROR] [07/26/2019 17:33:45.225] [main] [akka://hujpizda/user] swallowing exception during message send
akka.actor.dungeon.SerializationCheckFailedException: Failed to serialize and deserialize message of type akka.actor.typed.SpawnProtocol$Spawn for testing. To avoid this error, either disable 'akka.actor.serialize-messages', mark the message with 'akka.actor.NoSerializationVerificationNeeded', or configure serialization to support this message
	at akka.actor.dungeon.SerializationCheckFailedException$.apply(Dispatch.scala:26)
	at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:175)
	at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:155)
	at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:152)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:408)
	at akka.actor.Cell.sendMessage(ActorCell.scala:324)
	at akka.actor.Cell.sendMessage$(ActorCell.scala:323)
	at akka.actor.ActorCell.sendMessage(ActorCell.scala:408)
	at akka.actor.LocalActorRef.$bang(ActorRef.scala:412)
	at akka.actor.typed.internal.adapter.ActorSystemAdapter.tell(ActorSystemAdapter.scala:61)
	at akka.actor.typed.RecipientRef$RecipientRefOps$.$bang$extension(ActorRef.scala:134)
	at akka.actor.typed.scaladsl.AskPattern$.akka$actor$typed$scaladsl$AskPattern$$askUntyped(AskPattern.scala:146)
	at akka.actor.typed.scaladsl.AskPattern$Askable$.ask$extension(AskPattern.scala:104)
	at akka.actor.typed.scaladsl.AskPattern$Askable$.$qmark$extension(AskPattern.scala:68)
	at beams.Main$.main(Main.scala:39)
	at beams.Main.main(Main.scala)
Caused by: java.io.NotSerializableException: akka.actor.typed.internal.BehaviorImpl$StoppedBehavior$
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at akka.serialization.JavaSerializer.$anonfun$toBinary$1(Serializer.scala:333)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at akka.serialization.JavaSerializer.toBinary(Serializer.scala:333)
	at akka.actor.dungeon.Dispatch.serializeAndDeserializePayload(Dispatch.scala:194)
	at akka.actor.dungeon.Dispatch.serializeAndDeserialize(Dispatch.scala:173)
	... 14 more
```

**Comment by chbatey** [comment]
There's maybe a usecase for having this be serializeable? If so we should add a protobuf serializer for it

**Comment by jchapuis** [comment]
Same issue here, I would really like to use `serialize-messages = on` in my tests to detect any missing serializers, but I can't make it work because of this.

**Comment by schernichkin** [comment]
@jchapuis I use "fake" serializer as temporary workaround.

1. Create "fake" serializer, which does not serialize message, but store it temporary in hash table and return message key in binary format. For example:
```scala
class FakeSerializer(val system: ExtendedActorSystem) extends BaseSerializer {
  private val BYTES = java.lang.Integer.BYTES
  private val objects: mutable.HashMap[Int, AnyRef] = new mutable.HashMap[Int, AnyRef]()

  override def toBinary(o: AnyRef): Array[Byte] = synchronized {
    var key = objects.size
    objects(key) = o
    val bytes = new Array[Byte](BYTES)
    for (i <- BYTES - 1 to 0 by -1) {
      bytes(i) = (key & 0xFF).toByte
      key = key >>> 8
    }
    bytes
  }

  override def includeManifest: Boolean = false

  override def fromBinary(bytes: Array[Byte], manifest: Option[Class[_]]): AnyRef = synchronized {
    var key = 0
    for (i <- 0 until BYTES) {
      key = key << 8
      key = key | (bytes(i) & 0xFF)
    }
    val obj = objects(key)
    objects.remove(key)
    obj
  }
}
```
2. Add following configuration:
```
akka {
    actor {
        serialize-messages = on

        serializers {
            fake = FakeSerializer
        }

        serialization-bindings {
            "akka.actor.typed.SpawnProtocol$Command" = fake
        }
    }
}
```
Akka serialization checker will call once `toBinary` on Spawn message and then `fromBinary` immediately after that. "Fake" serializer will remove object from table so memory will not leak.

**Comment by jchapuis** [comment]
^^
Good trick! thanks

**Comment by patriknw** [comment]
Related to #24273

**Comment by patriknw** [comment]
Closing this since it will be solved via https://github.com/akka/akka/pull/27517
