### ISSUE TITLE
Failed: DurableDataSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#27430]
https://jenkins.akka.io:8498/job/akka-multi-node-repeat/20762/consoleFull

```
[info] [JVM-2] Durable CRDT
[info] [JVM-2] - must work in single node cluster (762 milliseconds)
[info] [JVM-1] - must work in single node cluster (848 milliseconds)
[info] [JVM-2] - work in multi node cluster *** FAILED *** (15 seconds, 374 milliseconds)
[info] [JVM-2]   java.lang.AssertionError: assertion failed: expected UpdateSuccess(durable-A,None), found UpdateTimeout(durable-A,None)
[info] [JVM-2]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-2]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:419)
[info] [JVM-2]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:395)
[info] [JVM-2]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:395)
[info] [JVM-2]   at akka.testkit.TestKit.expectMsg(TestKit.scala:928)
[info] [JVM-2]   at akka.cluster.ddata.DurableDataSpec.$anonfun$new$10(DurableDataSpec.scala:171)

```

**Comment by chbatey** [comment]
this is on the protobuf3 branch
