### ISSUE TITLE
FAILED: AsyncDnsResolverIntegrationSpec / DnsDiscoverySpec 

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27489]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/46/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/
https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/46/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/
https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/50/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/
https://jenkins.akka.io:8498/job/akka-release-2.5-2.13/50/testReport/junit/akka.discovery.dns/DnsDiscoverySpec/_It_is_not_a_test_it_is_a_sbt_testing_SuiteSelector_/

```
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: [] was not null
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
	at akka.io.dns.DockerBindDnsService$class.atStartup(DockerBindDnsService.scala:73)
	at akka.discovery.dns.DnsDiscoverySpec.atStartup(DnsDiscoverySpec.scala:43)
	at akka.testkit.AkkaSpec.beforeAll(AkkaSpec.scala:87)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:61)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:483)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Likely cause is that an docker upgrade changed the json response from `null` to `[]`.

**Comment by jrudolph** [comment]
All nightlies failed since yesterday, didn't log all of them here, since #27490 is pending merge.

**Comment by burbaki** [comment]
`creation.warnings() should be(null).or(have(size(0)))` is failed with `nullPointerException` 
 when creation.warnings() is null.
