### ISSUE TITLE
FAILED: akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.EventSourcedBehavior with retention must be possible to snapshot every event withDeleteEventsOnSnapshot

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27507]
https://jenkins.akka.io:8498/job/akka-multi-node/3529/testReport/akka.persistence.typed.scaladsl/EventSourcedBehaviorRetentionSpec/EventSourcedBehavior_with_retention_must_be_possible_to_snapshot_every_event_withDeleteEventsOnSnapshot/

```
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: DeleteEventsCompleted(6) did not equal DeleteSnapshotsCompleted(Criteria(SnapshotSelectionCriteria(4,9223372036854775807,1,0)))
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.expectDeleteSnapshotCompleted$1(EventSourcedBehaviorRetentionSpec.scala:295)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.$anonfun$new$42(EventSourcedBehaviorRetentionSpec.scala:539)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withFixture(ScalaTestWithActorTestKit.scala:28)
	at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
	at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
	at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.runTest(EventSourcedBehaviorRetentionSpec.scala:148)
	at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
	at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.runTests(EventSourcedBehaviorRetentionSpec.scala:148)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:28)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.org$scalatest$WordSpecLike$$super$run(EventSourcedBehaviorRetentionSpec.scala:148)
	at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
	at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.run(EventSourcedBehaviorRetentionSpec.scala:148)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by johanandren** [comment]
Cause is using the same probe for journal and snapshot events so ordering can be off.
