### ISSUE TITLE
failed: ClusterShardingRememberEntitiesSpec: Cluster sharding with remember entities (persistence) must setup shared journal

### ISSUE THREAD

**Issue by raboof** [akka/akka#27548]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2084/consoleFull
```
[info] [JVM-1] - must setup shared journal (on node 'first', class akka.cluster.sharding.PersistentClusterShardingRememberEntitiesMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:528)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:510)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:509)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:928)
[info] [JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec.$anonfun$new$4(ClusterShardingRememberEntitiesSpec.scala:163)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:384)
[info] [JVM-1]   at akka.cluster.sharding.ClusterShardingRememberEntitiesSpec.$anonfun$new$2(ClusterShardingRememberEntitiesSpec.scala:161)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-1]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3545/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3549/consoleText

**Comment by helena** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3577/consoleFull

**Comment by patriknw** [comment]
I removed that target directory this morning.

**Comment by helena** [comment]
https://github.com/akka/akka/issues/27548#issuecomment-528456420 is a separate and new issue, being resolved by https://github.com/akka/akka/issues/27661.

The original failure noted in the description will be addressed here.
