### ISSUE TITLE
SupervisionSpec: Supervision for a sharded actor must allow passivation

### ISSUE THREAD

**Issue by raboof** [akka/akka#27549]
https://jenkins.akka.io:8498/job/akka-nightly/6857/testReport/junit/akka.cluster.sharding/SupervisionSpec/Supervision_for_a_sharded_actor_must_allow_passivation/
```
[info] - must allow passivation *** FAILED *** (20 seconds, 9 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsgClass waiting for class akka.cluster.sharding.SupervisionSpec$Response
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:528)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:510)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:509)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:928)
[info]   at akka.cluster.sharding.SupervisionSpec.$anonfun$new$6(SupervisionSpec.scala:133)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2114

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18830/testReport/junit/akka.cluster.sharding/SupervisionSpec/Supervision_for_a_sharded_actor_must_allow_passivation/
