### ISSUE TITLE
Use ActorSystem's ThreadFactory for Aeron threads

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27603]
We had `akka-artery-aeron-udp-remote-tests` Jenkins job configured incorrectly. It was using `tcp`. When I changed to `aeron-udp` this started failing.

https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/120/consoleText

```
[info] Remoting configured with daemonic = on
[WARN] [08/30/2019 09:48:21.976] [pool-1-thread-1-ScalaTest-running-DaemonicSpec] [akka.remote.RemoteActorRefProvider] Using the 'remote' ActorRefProvider directly, which is a low-level layer. For most use cases, the 'cluster' abstraction on top of remoting is more suitable instead.
[WARN] [08/30/2019 09:48:21.977] [pool-1-thread-1-ScalaTest-running-DaemonicSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
[INFO] [08/30/2019 09:48:21.988] [pool-1-thread-1-ScalaTest-running-DaemonicSpec] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://daemonic)] Started embedded media driver in directory [/dev/shm/aeron-jenkinsakka-daemonic-eec15162-d553-441d-868b-db02a40e5935]
[INFO] [08/30/2019 09:48:22.000] [pool-1-thread-1-ScalaTest-running-DaemonicSpec] [akka.remote.artery.aeron.ArteryAeronUdpTransport(akka://daemonic)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://daemonic@127.0.1.1:34036] with UID [6163690640094425712]
[INFO] [08/30/2019 09:48:22.039] [daemonic-akka.actor.default-dispatcher-6] [akka://daemonic/user/SomeActor] Message [java.lang.String] to Actor[akka://daemonic/user/SomeActor] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://daemonic/user/SomeActor] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [08/30/2019 09:48:26.025] [daemonic-akka.remote.default-remote-dispatcher-9] [akka://daemonic@127.0.1.1:34036/system/remoting-terminator] Shutting down remote daemon.
[INFO] [08/30/2019 09:48:26.025] [daemonic-akka.remote.default-remote-dispatcher-9] [akka://daemonic@127.0.1.1:34036/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [08/30/2019 09:48:26.046] [daemonic-akka.remote.default-remote-dispatcher-16] [akka://daemonic@127.0.1.1:34036/system/remoting-terminator] Remoting shut down.
[info] - must shut down correctly after getting connection refused *** FAILED *** (4 seconds, 101 milliseconds)
[info]   Set(Thread[driver-conductor,5,main], Thread[[sender,receiver],5,main], Thread[aeron-client-conductor,5,main]) did not equal Set() (DaemonicSpec.scala:50)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6859)
[info]   at akka.remote.DaemonicSpec.$anonfun$new$3(DaemonicSpec.scala:50)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:327)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:344)
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:316)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:928)
[info]   at akka.remote.DaemonicSpec.$anonfun$new$2(DaemonicSpec.scala:47)
```

**Comment by johanandren** [comment]
Failing every night since.

**Comment by patriknw** [comment]
I'll look into this now
