### ISSUE TITLE
failed: Typed multi-node tests 

### ISSUE THREAD

**Issue by patriknw** [akka/akka#27652]
https://jenkins.akka.io:8498/job/akka-multi-node/3581/

Something wrong with assembly because of the new logback-test.xml files,

```
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:141)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:84)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] 	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:141)
[error] 	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
[error] 	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
[error] 	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
[error] 	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
[error] 	at sbtassembly.Assembly$.apply(Assembly.scala:84)
[error] 	at sbtassembly.Assembly$.$anonfun$assemblyTask$1(Assembly.scala:249)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (akka-cluster-sharding-typed / Multi-jvm / assembly) deduplicate: different file contents found in the following:
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] logback-test.xml
[error] (akka-cluster-typed / Multi-jvm / assembly) deduplicate: different file contents found in the following:
``

**Comment by helena** [comment]
We are still seeing this, e.g. https://jenkins.akka.io:8498/job/akka-multi-node/3581/consoleFull 
Sep 9, 2019 2:35:02 PM

**Comment by patriknw** [comment]
but build 3581 was before my fix.
Fixed in https://jenkins.akka.io:8498/job/akka-multi-node/3582/

**Comment by helena** [comment]
Corrected. The deduplicate is something new  https://github.com/akka/akka/issues/27667
