### ISSUE TITLE
No configuration setting found for key 'default'

### ISSUE THREAD

**Issue by garfi-wu** [akka/akka#27795]
/*
 This is a question about Akka http demo when I run the packed jar.
 But it works well in Intellij Idea.  I had stuck for serveral days.
*/

// Gradle Dependencies
dependencies {
    compile group: 'org.scala-lang', name: 'scala-library', version: '2.12.6'
    compile group: 'com.typesafe.akka', name: 'akka-http_2.12', version: '10.1.9'
    compile group: 'com.typesafe.akka', name: 'akka-stream_2.12', version: '2.5.22'
}

// A test scala file named Rest.scala
package io.qross
import akka.actor.ActorSystem
import akka.http.scaladsl.server
import akka.stream.ActorMaterializer
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.Directives._

import scala.concurrent.ExecutionContextExecutor
import scala.io.StdIn

object Rest {
    def main(args: Array[String]): Unit = {

        implicit val system: ActorSystem = ActorSystem("api-server")
        implicit val materializer: ActorMaterializer = ActorMaterializer()
        implicit val executionContext: ExecutionContextExecutor = system.dispatcher

        val path: server.Route =
            pathSingleSlash {
                get {
                    complete("HELLO WORLD")
                }
            }

        val bindingFuture = Http().bindAndHandle(path,"0.0.0.0",8250)
        println("Server is running...")
        StdIn.readLine()
        bindingFuture.flatMap(_.unbind()).onComplete(_=>system.terminate())
        println("Server has shut down.")

    }
}

// Full exception info when I run it.
// java -cp myjar.jar io.qross.Rest
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'default'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.typesafe.sslconfig.util.ConfigLoader$.$anonfun$booleanLoader$2(Configuration.scala:186)
        at com.typesafe.sslconfig.util.ConfigLoader$.$anonfun$booleanLoader$2$adapted(Configuration.scala:186)
        at com.typesafe.sslconfig.util.ConfigLoader$$anon$2.load(Configuration.scala:173)
        at com.typesafe.sslconfig.util.EnrichedConfig.get(Configuration.scala:22)
        at com.typesafe.sslconfig.ssl.SSLConfigParser.parse(Config.scala:498)
        at com.typesafe.sslconfig.ssl.SSLConfigFactory$.parse(Config.scala:486)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.defaultSSLConfigSettings(AkkaSSLConfig.scala:34)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:29)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:19)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
        at akka.actor.ExtensionId.apply(Extension.scala:79)
        at akka.actor.ExtensionId.apply$(Extension.scala:78)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:24)
        at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:19)
        at akka.http.scaladsl.HttpExt.<init>(Http.scala:79)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:1124)
        at akka.http.scaladsl.Http$.createExtension(Http.scala:893)
        at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
        at akka.actor.ExtensionId.apply(Extension.scala:79)
        at akka.actor.ExtensionId.apply$(Extension.scala:78)
        at akka.http.scaladsl.Http$.apply(Http.scala:1119)
        at io.qross.Rest$.main(Rest.scala:26)
        at io.qross.Rest.main(Rest.scala)

**Comment by johanandren** [comment]
Probably because of making a combined jar but not handling reference.conf the right way, see docs here: https://doc.akka.io/docs/akka/current/general/configuration.html#when-using-jarjar-onejar-assembly-or-any-jar-bundler

**Comment by keysunHong** [comment]
Missing 'ssl-config' configuration ，reference document：https://github.com/lightbend/ssl-config/blob/master/ssl-config-core/src/main/resources/reference.conf

**Comment by patriknw** [comment]
I assume this has been sorted out
