### ISSUE TITLE
Failed: akka.io.dns.AsyncDnsResolverIntegrationSpec.Resolver must handle nonexistent domains

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27839]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/371/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/Resolver_must_handle_nonexistent_domains/

```
sbt.ForkMain$ForkError: org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 51 times, sleeping 100 milliseconds between each query.
	at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.io.dns.AsyncDnsResolverIntegrationSpec.$anonfun$new$17(AsyncDnsResolverIntegrationSpec.scala:135)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5-2.11/61/testReport/junit/akka.io.dns/AsyncDnsResolverIntegrationSpec/Resolver_must_handle_nonexistent_domains/

**Comment by raboof** [comment]
Again on 2.5:

https://jenkins.akka.io:8498/job/akka-release-2.5/220/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4027
(master)

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-scala3/44/consoleFull

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3750584122?check_suite_focus=true#step:5:3969

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3726704551?check_suite_focus=true#step:5:4289

**Comment by johanandren** [comment]
Looking at the logs, what is going on is that since there are two search domains, there is actually three dns lookups happening, one without the domains, and then one each with the domains since the first one did not result in any found ips, those three lookups simply sometimes takes more than 5 seconds which is the timeout.

**Comment by johanandren** [comment]
Looks like this should be fixed in #30710

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3801647766?check_suite_focus=true#step:5:3073

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3821627979?check_suite_focus=true#step:5:3841
