### ISSUE TITLE
Failed: akka.cluster.JoinConfigCompatCheckerSpec.downing-provider-class

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27840]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/155/testReport/junit/akka.cluster/JoinConfigCompatCheckerSpec/downing_provider_class/

```
sbt.ForkMain$ForkError: java.lang.IllegalStateException: cannot create children while terminating or terminated
	at akka.actor.dungeon.Children.makeChild(Children.scala:289)
	at akka.actor.dungeon.Children.attachChild(Children.scala:51)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:50)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:408)
	at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:891)
	at akka.stream.SystemMaterializer.<init>(SystemMaterializer.scala:57)
	at akka.stream.SystemMaterializer$.createExtension(SystemMaterializer.scala:35)
	at akka.stream.SystemMaterializer$.createExtension(SystemMaterializer.scala:29)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1141)
	at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1179)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1175)
	at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1191)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1039)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1027)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1027)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1049)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:281)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:325)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:299)
	at akka.cluster.ClusterTestKit$ClusterTestUtil.newActorSystem(ClusterTestKit.scala:54)
	at akka.cluster.JoinConfigCompatCheckerSpec.$anonfun$new$17(JoinConfigCompatCheckerSpec.scala:273)
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/154/testReport/junit/akka.cluster/JoinConfigCompatCheckerSpec/downing_provider_class/

**Comment by jrudolph** [comment]
Since the error message is the same and scope similar, these might be the same:

akka.cluster.DowningProviderSpec.The downing provider mechanism should stop the cluster if the downing provider throws exception in props method

https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/155/testReport/junit/akka.cluster/DowningProviderSpec/The_downing_provider_mechanism_should_stop_the_cluster_if_the_downing_provider_throws_exception_in_props_method/

**Comment by jrudolph** [comment]
Seems to fail pretty consistently right now for akka-classic-cluster-test.

https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/156/#showFailuresLink

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/157/#showFailuresLink

**Comment by patriknw** [comment]
I fixed the JoinConfigCompatCheckerSpec in https://github.com/akka/akka/pull/27859

More difficult is the other one in DowningProviderSpec.
I think the test is terminating the ActorSystem while the akka.stream.SystemMaterializer is still not fully initialized ("cannot create children while terminating").
Not sure we need some error handling for this scenario in SystemMaterializer?

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/158/testReport/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/159/testReport/

**Comment by patriknw** [comment]
Remaining here is to debug DowningProviderSpec again with ` -Dakka.remote.artery.enabled=off` and see if we need to do something about the race between `akka.stream.SystemMaterializer` starting and the ActorSystem terminating prematurely.
