### ISSUE TITLE
Failed: akka-publish-nightly fails with "Scala signature package has wrong version"

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#27854]
https://jenkins.akka.io:8498/job/akka-publish-nightly/1234/consoleFull

Are we mixing scala versions here?

```
[info] Compiling 189 Scala sources and 27 Java sources to /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-actor/target/classes ...
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class
	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:124)
	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:66)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.unpickleOrParseInnerClasses(ClassfileParser.scala:1174)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:465)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:161)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:146)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:129)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:329)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:355)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:410)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:299)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.internal.Types$TypeRef.decls(Types.scala:2281)
	at scala.tools.nsc.typechecker.Namers$Namer.enterPackage(Namers.scala:751)
	at scala.tools.nsc.typechecker.Namers$Namer.dispatch$1(Namers.scala:281)
	at scala.tools.nsc.typechecker.Namers$Namer.standardEnterSym(Namers.scala:294)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym(AnalyzerPlugins.scala:479)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym$(AnalyzerPlugins.scala:478)
	at scala.tools.nsc.Global$$anon$4.pluginsEnterSym(Global.scala:482)
	at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:272)
	at scala.tools.nsc.typechecker.Analyzer$namerFactory$$anon$1.apply(Analyzer.scala:50)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:399)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1503)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1487)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1480)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1606)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1757)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1730)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
	at sbt.Execute.work(Execute.scala:289)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[error] error while loading package, class file '/localhome/jenkinsakka/workspace/akka-publish-nightly/akka-actor/target/classes/akka/util/ccompat/package.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of package.class: Scala signature package has wrong version
[error]  expected: 5.0
[error]  found: 5.2 in package.class)
[error] one error found
```

**Comment by jrudolph** [comment]
cinnamon-akka-nightly also fails for the same reason:

https://ci.lightbend.com/blue/organizations/jenkins/cinnamon-akka-nightly/detail/cinnamon-akka-nightly/1377/pipeline

**Comment by pvlugter** [comment]
In the cinnamon nightly, this was cross-compiling with `+publishLocal` but cross paths/targets are disabled. I've updated to separate compiles using the build scala version system property.

**Comment by patriknw** [comment]
@pvlugter what does that mean? That we can't use `+publish` anymore or that we can if we enable something?

**Comment by pvlugter** [comment]
`crossPaths` is disabled, so the cross compiles share the same target directory.

It looks like it was something that I actually added [many years ago](https://github.com/akka/akka/commit/29106c0df0bdb8437e9a9d06c98978ebdfb098c0), and couldn't say why it was disabled way back then, but it seems to have been carried forward into the current build.

Removing `crossPaths := false` sounds good. And then checking any usage of both `target`  and `crossTarget` settings. Some `target` directory uses may need to be `crossTarget` when scala-specific, and there may be `crossTarget` use that needs to go to the shared `target` directory instead.
