### ISSUE TITLE
Improve documentation around completion and stream cycles

### ISSUE THREAD

**Issue by rolandjohann** [akka/akka#27908]
Creating a feedback loop/cycle with async flows at the feedback part of the graph, events will be dropped when the merge junction is setup with `eagerComplete = true` to be able to complete the stream when upstream finishes.

Below you find a test with corresponding output:

code:
```scala
import akka.actor.ActorSystem
import akka.event.{Logging, LoggingAdapter}
import akka.stream._
import akka.stream.scaladsl.{Flow, GraphDSL, Merge, Partition, RunnableGraph, Sink, Source}
import org.scalatest.{AsyncFlatSpec, BeforeAndAfterAll}
import org.slf4j.LoggerFactory

import scala.concurrent.{ExecutionContext, Future}

class AsyncFeedbackLoopTest extends AsyncFlatSpec with BeforeAndAfterAll {

  private val logger = LoggerFactory.getLogger(this.getClass)

  implicit private val system: ActorSystem = ActorSystem()
  implicit private val log: LoggingAdapter = Logging(system.eventStream, this.getClass)
  implicit private val ec: ExecutionContext = system.dispatcher

  private val materializerSettings = ActorMaterializerSettings(system).withSupervisionStrategy { t =>
    logger.error("Unhandled exception at stream", t)
    Supervision.Stop
  }
  implicit private val materializer: ActorMaterializer = ActorMaterializer(materializerSettings)

  override def afterAll(): Unit = {
    logger.info("shutdown")
    materializer.shutdown()
    system.terminate()
  }

  it should "test async feedback loop doesn't drop events when terminated" in {
    logger.info("""test "test async feedback loop doesn't drop events when terminated"""")
    val sink = Sink.seq[(Int, Int)]

    RunnableGraph
      .fromGraph(GraphDSL.create(sink) { implicit b =>
        sink =>
          import GraphDSL.Implicits._

          val source = Source((0 until 5).toList).map(x => x -> x).named("source").log("source")

          val merge = b.add(Merge[(Int, Int)](2, eagerComplete = true))

          val partition = b.add(Partition[(Int, Int)](2, x => if (x._2 % 2 == 0) 0 else 1))

          val add = b.add {
            Flow[(Int, Int)]
              .map(x => (x._1, x._2 + 1))
              .log("async-add.before")
              .mapAsync(1) { x =>
                Future {
                  Thread.sleep((math.random * 1000).toLong)
                  x
                }
              }
              .log("async-add.after")
          }

          // @formatter:off
          source ~> merge ~>        partition
                                    partition.out(0).log("sink") ~> sink
                    merge <~ add <~ partition.out(1)
          // @formatter:on

          ClosedShape
      })
      .run()
      .map { result =>
        logger.info("got result: {}", result)
        assert(result.size == 5)
      } recover {
        case t =>
          fail(t)
    }
  }

  it should "test feedback loop doesn't drop events when terminated" in {
    logger.info("""test "test feedback loop doesn't drop events when terminated"""")

    val sink = Sink.seq[(Int, Int)]

    RunnableGraph
      .fromGraph(GraphDSL.create(sink) { implicit b =>
        sink =>
          import GraphDSL.Implicits._

          val source = Source((0 until 5).toList).map(x => x -> x).named("source").log("source")

          val merge = b.add(Merge[(Int, Int)](2, eagerComplete = true))

          val partition = b.add(Partition[(Int, Int)](2, x => if (x._2 % 2 == 0) 0 else 1))

          val add = b.add {
            Flow[(Int, Int)]
              .map(x => (x._1, x._2 + 1))
              .log("add")
          }

          // @formatter:off
          source ~> merge ~>        partition
                                    partition.out(0).log("sink") ~> sink
                    merge <~ add <~ partition.out(1)
          // @formatter:on

          ClosedShape
      })
      .run()
      .map { result =>
        logger.info("got result: {}", result)
        assert(result.size == 5)
      } recover {
      case t =>
        fail(t)
    }
  }
}
```

output:
```
[...]
INFO i.r.s.f.AsyncFeedbackLoopTest - test "test async feedback loop doesn't drop events when terminated"
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (0,0)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (0,0)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (1,1)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [async-add.before] Element: (1,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (2,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (2,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (3,3)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (4,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Upstream finished.
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [async-add.after] Downstream finished.
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [async-add.before] Downstream finished.
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (4,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Upstream finished.
INFO i.r.s.f.AsyncFeedbackLoopTest - got result: Vector((0,0), (2,2), (4,4))

org.scalatest.exceptions.TestFailedException was thrown.
ScalaTestFailureLocation: [...].AsyncFeedbackLoopTest$$anonfun$2$$anonfun$apply$1 at (AsyncFeedbackLoopTest.scala:73)
org.scalatest.exceptions.TestFailedException
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.AsyncFlatSpec.newAssertionFailedException(AsyncFlatSpec.scala:2219)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1121)
	at org.scalatest.AsyncFlatSpec.fail(AsyncFlatSpec.scala:2219)
	at [...].AsyncFeedbackLoopTest$$anonfun$2$$anonfun$apply$1.applyOrElse(AsyncFeedbackLoopTest.scala:73)
	at [...].AsyncFeedbackLoopTest$$anonfun$2$$anonfun$apply$1.applyOrElse(AsyncFeedbackLoopTest.scala:71)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:92)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.scalatest.exceptions.TestFailedException: Vector((0,0), (2,2), (4,4)) had size 3 instead of expected size 5
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
	at org.scalatest.AsyncFlatSpec.newAssertionFailedException(AsyncFlatSpec.scala:2219)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
	at [...].AsyncFeedbackLoopTest$$anonfun$2$$anonfun$apply$6.apply(AsyncFeedbackLoopTest.scala:70)
	at [...].AsyncFeedbackLoopTest$$anonfun$2$$anonfun$apply$6.apply(AsyncFeedbackLoopTest.scala:68)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	... 13 more

INFO i.r.s.f.AsyncFeedbackLoopTest - test "test feedback loop doesn't drop events when terminated"
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (0,0)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (0,0)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (1,1)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [add] Element: (1,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (1,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (2,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (3,3)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [add] Element: (3,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (2,2)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Element: (4,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (3,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Element: (4,4)
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [source] Upstream finished.
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [add] Downstream finished.
DEBUG i.r.s.f.AsyncFeedbackLoopTest - [sink] Upstream finished.
INFO i.r.s.f.AsyncFeedbackLoopTest - got result: Vector((0,0), (1,2), (2,2), (3,4), (4,4))
INFO i.r.s.f.AsyncFeedbackLoopTest - shutdown
DEBUG a.e.EventStream - shutting down: StandardOutLogger

Process finished with exit code 0
```

**Comment by johanandren** [comment]
That is an expected risk with the eager complete on the merge, it will complete as soon as either upstream completes, potentially dropping elements that were in flight in the other upstream.

**Comment by rolandjohann** [comment]
Loops are one of Akka Streams features that other stream processing libs not offer. How can we safely construct them? If it's not possible, we should at least provide a hint at the docs that using feedback loops has implications.

**Comment by johanandren** [comment]
We have some docs around implications of loops: https://doc.akka.io/docs/akka/current/stream/stream-graphs.html#graph-cycles-liveness-and-deadlocks nothing about stream completion though, so maybe that would fit there?

**Comment by rolandjohann** [comment]
@johanandren yes, this is the part of the docs that should mention this behavior.

Besides that: how can we safely construct feedback loops?

As far as I can see we can solve this issue by sending the complete signals not per stage, but per stage and output so we can resolve the deadlock situation when using merge junctions with eagerComplete disabled. Currently we are able to define the state of a stage per stage only, the API for completing `inlet`s and `outlet`s is not accessable from `GraphStage` implementations:

https://github.com/akka/akka/blob/bb622e639b0c4b75f0b4e1a9768d57fbae38ddc0/akka-stream/src/main/scala/akka/stream/stage/GraphStage.scala#L636-L640

**Comment by johanandren** [comment]
That is accessible from a `GraphStageLogic` implementation which is what will be inside a materiaized/running graph (`GraphStage` itself is just the blueprint). It is used all over in the operator implementations (for example `Unfold`, `JavaStreamSource` and `SetupStage`)

Why can your specific loop just not use eager complete for `Merge`, sounds like non-eager is exactly what you are after?

**Comment by rolandjohann** [comment]
doh.. was late last evening - it's `protected`, not private. So we can use this. Great!

Using `Merge` with `eagerComplete = false` the stream never completes because of this:
https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala#L156-L157

The upstream finished event won't be propagated to outputs until all inputs have been completed. We can introduce a `MergeCycled` flow that specifies output ports used for connecting the actual cycle. When we receive `upstreamFinished` event we can complete that cycle port to propagate the event to the remaining input port(s) eventually.

**Comment by johanandren** [comment]
I don't have a good solution for that, other than custom a fanout like you described, from the top of my head, I'd recommend that you open up a discussion around that in the forums (https://discuss.akka.io) and see if someone else in the community has some good ideas.

**Comment by an-tex** [comment]
I've just tripped over the same issue. Pretty tricky. My workaround was to introduce a idleTimeout, not pretty but might be sufficient in some cases
