### ISSUE TITLE
akka.stream.CompletionStrategy not Serializable

### ISSUE THREAD

**Issue by SkyTrix** [akka/akka#27932]
I have a stream which involves `Source.actorRef` that crosses ActorSystems using Akka Remoting. According to the [documentation](https://doc.akka.io/docs/akka/current/stream/stream-integrations.html#source-actorref) we should send `akka.actor.Status.Success` with an `akka.stream.CompletionStrategy` instead of a `PoisonPill` to the actor to complete the stream. However, this fails because `CompletionStrategy` is not Serializable. If it at all matters, note that we have [disabled the Java Serializer](https://doc.akka.io/docs/akka/current/serialization.html#disabling-the-java-serializer).

Is this an oversight on Akka's part or are we using it wrong?

```
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class akka.actor.Status$Success] using serializer [class akka.remote.serialization.MiscMessageSerializer].
	at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:67)
	at akka.remote.EndpointWriter.$anonfun$serializeMessage$1(Endpoint.scala:1021)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:1021)
	at akka.remote.EndpointWriter.writeSend(Endpoint.scala:887)
	at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:859)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:536)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
	at akka.actor.ActorCell.invoke(ActorCell.scala:581)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.NotSerializableException: No configured serialization-bindings for class [akka.stream.CompletionStrategy$Immediately$]
	at akka.serialization.Serialization.serializerFor(Serialization.scala:332)
	at akka.serialization.Serialization.findSerializerFor(Serialization.scala:307)
	at akka.remote.serialization.WrappedPayloadSupport.payloadBuilder(WrappedPayloadSupport.scala:22)
	at akka.remote.serialization.MiscMessageSerializer.serializeStatusSuccess(MiscMessageSerializer.scala:117)
	at akka.remote.serialization.MiscMessageSerializer.toBinary(MiscMessageSerializer.scala:42)
	at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:55)
	... 17 common frames omitted
````

**Comment by johanandren** [comment]
It's a missing serializer. Note however that it is somewhat dangerous to interact with the source actorref from another node since that increases the risk of messages getting lost, causing for example a resource leak if that `Immediate` message would have a serializer but got lost.

Could be worth looking into the StreamRef API instead perhaps. https://doc.akka.io/docs/akka/current/stream/stream-refs.html#streamrefs-reactive-streams-over-the-network

**Comment by SkyTrix** [comment]
I'll look into that, thanks for your suggestion.

**Comment by patriknw** [comment]
If I'm not misunderstanding there is nothing we should do here.
