### ISSUE TITLE
LoggerInitializationException in cluster tests

### ISSUE THREAD

**Issue by johanandren** [akka/akka#27955]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2133/consoleText

```
[error] [JVM-1] akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log2-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
[error] [JVM-1] 	at akka.event.LoggingBus$$anonfun$$nestedInanonfun$startDefaultLoggers$3$1.applyOrElse(Logging.scala:134)
[error] [JVM-1] 	at akka.event.LoggingBus$$anonfun$$nestedInanonfun$startDefaultLoggers$3$1.applyOrElse(Logging.scala:129)
[error] [JVM-1] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error] [JVM-1] 	at scala.util.Failure.recover(Try.scala:234)
[error] [JVM-1] 	at akka.event.LoggingBus.$anonfun$startDefaultLoggers$3(Logging.scala:129)
[error] [JVM-1] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:827)
[error] [JVM-1] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] [JVM-1] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] [JVM-1] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] [JVM-1] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] [JVM-1] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] [JVM-1] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] [JVM-1] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:826)
[error] [JVM-1] 	at akka.event.LoggingBus.startDefaultLoggers(Logging.scala:121)
[error] [JVM-1] 	at akka.event.LoggingBus.startDefaultLoggers$(Logging.scala:106)
[error] [JVM-1] 	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:25)
[error] [JVM-1] 	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:572)
[error] [JVM-1] 	at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:218)
[error] [JVM-1] 	at akka.cluster.ClusterActorRefProvider.init(ClusterActorRefProvider.scala:48)
[error] [JVM-1] 	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1031)
[error] [JVM-1] 	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1027)
[error] [JVM-1] 	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1027)
[error] [JVM-1] 	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1049)
[error] [JVM-1] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:281)
[error] [JVM-1] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:325)
[error] [JVM-1] 	at akka.actor.ActorSystem$.apply(ActorSystem.scala:299)
[error] [JVM-1] 	at akka.remote.testkit.MultiNodeSpec$$anonfun$$lessinit$greater$2.apply(MultiNodeSpec.scala:290)
[error] [JVM-1] 	at akka.remote.testkit.MultiNodeSpec$$anonfun$$lessinit$greater$2.apply(MultiNodeSpec.scala:288)
[error] [JVM-1] 	at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:283)
[error] [JVM-1] 	at akka.remote.testkit.MultiNodeSpec.<init>(MultiNodeSpec.scala:288)
[error] [JVM-1] 	at akka.cluster.metrics.ClusterMetricsDisabledSpec.<init>(ClusterMetricsExtensionSpec.scala:137)
[error] [JVM-1] 	at akka.cluster.metrics.ClusterMetricsDisabledMultiJvmNode1.<init>(ClusterMetricsExtensionSpec.scala:130)
[error] [JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] [JVM-1] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] [JVM-1] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] [JVM-1] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] [JVM-1] 	at java.lang.Class.newInstance(Class.java:442)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1431)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1239)
[error] [JVM-1] 	at scala.collection.immutable.List.map(List.scala:286)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1238)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
[error] [JVM-1] 	at org.scalatest.tools.Runner$.main(Runner.scala:827)
[error] [JVM-1] 	at org.scalatest.tools.Runner.main(Runner.scala)
[error] [JVM-1] Caused by: akka.event.Logging$LoggerInitializationException: Logger log2-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
[error] [JVM-1] 	at akka.event.LoggingBus.addLogger(Logging.scala:215)
[error] [JVM-1] 	at akka.event.LoggingBus.$anonfun$startDefaultLoggers$4(Logging.scala:127)
[error] [JVM-1] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] [JVM-1] 	at scala.util.Success.map(Try.scala:213)
[error] [JVM-1] 	at akka.event.LoggingBus.$anonfun$startDefaultLoggers$3(Logging.scala:126)
[error] [JVM-1] 	... 42 more
```

**Comment by johanandren** [comment]
So something is causing logback take more than 5s to start on one out of 5 nodes.

Internet points towards DNS resolution of `localhost` but in that case it wouldn't be an transient failure but should always fail on that node (a4).

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2226/consoleFull

```
akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log2-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
```
