### ISSUE TITLE
Akka cluster is very noisy if shut down immediately

### ISSUE THREAD

**Issue by jroper** [akka/akka#27970]
I'm not sure that this issue occurred in Akka 2.5, but in Akka 2.6, if I shut down the actor system immediately after starting it, with the cluster actor ref provider, a tonne of exceptions get logged from the replicator:

```
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.cluster.Cluster(akka://management-api) - Cluster Node [akka://management-api@192.168.1.105:25520] - Exiting completed
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.cluster.Cluster(akka://management-api) - Cluster Node [akka://management-api@192.168.1.105:25520] - Shutting down...
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.cluster.Cluster(akka://management-api) - Cluster Node [akka://management-api@192.168.1.105:25520] - Successfully shut down
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.remote.RemoteActorRefProvider$RemotingTerminator - Shutting down remote daemon.
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.remote.RemoteActorRefProvider$RemotingTerminator - Remote daemon shut down; proceeding with flushing remote transports.
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.typed.internal.adapter.ActorAdapter - requirement failed: Cluster node must not be terminated
[error] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[error] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[error] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[error] 	at akka.actor.Props.newActor(Props.scala:212)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[error] 	... 9 more
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorCell - changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.typed.internal.adapter.ActorAdapter - requirement failed: Cluster node must not be terminated
[error] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[error] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[error] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[error] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[error] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[error] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[error] 	at akka.actor.Props.newActor(Props.scala:212)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[error] 	... 16 more
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorCell - changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.typed.internal.adapter.ActorAdapter - requirement failed: Cluster node must not be terminated
[error] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[error] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[error] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[error] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] [ERROR] [10/11/2019 15:01:46.670] [management-api-akka.actor.internal-dispatcher-14] [akka://management-api@192.168.1.105:25520/system/clusterReceptionist] requirement failed: Cluster node must not be terminated
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[info] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[info] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[info] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[info] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[error] 	at scala.Predef$.require(Predef.scala:281)
[info] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[error] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[info] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[error] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[info] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[error] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[error] 	at akka.actor.Props.newActor(Props.scala:212)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[info] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[info] 	at scala.Predef$.require(Predef.scala:281)
[info] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[info] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[info] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[error] 	... 16 more
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorCell - changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] [management-api-akka.actor.default-dispatcher-4] INFO akka.remote.RemoteActorRefProvider$RemotingTerminator - Remoting shut down.
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.typed.internal.adapter.ActorAdapter - requirement failed: Cluster node must not be terminated
[error] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[info] 	at akka.actor.Props.newActor(Props.scala:212)
[info] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[error] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[info] 	... 16 more
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[error] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[info] [ERROR] [10/11/2019 15:01:46.676] [management-api-akka.actor.internal-dispatcher-7] [akka://management-api/system/clusterReceptionist/replicator] changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[info] [ERROR] [10/11/2019 15:01:46.670] [management-api-akka.actor.internal-dispatcher-14] [akka://management-api@192.168.1.105:25520/system/clusterReceptionist] requirement failed: Cluster node must not be terminated
[info] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[info] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[error] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[info] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[info] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[info] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[info] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[info] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[info] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[error] 	at scala.Predef$.require(Predef.scala:281)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[info] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[info] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[info] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at akka.actor.Props.newActor(Props.scala:212)
[info] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[info] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[info] 	at scala.Predef$.require(Predef.scala:281)
[error] 	... 16 more
[info] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorCell - changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[info] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[info] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[info] 	at akka.actor.Props.newActor(Props.scala:212)
[info] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[info] 	... 16 more
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.typed.internal.adapter.ActorAdapter - requirement failed: Cluster node must not be terminated
[error] akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
[error] 	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:657)
[error] 	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:137)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:131)
[error] 	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:121)
[error] 	at akka.actor.ActorCell.faultCreate(ActorCell.scala:408)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:60)
[error] 	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:56)
[error] 	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:408)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:512)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: Cluster node must not be terminated
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at akka.cluster.ddata.Replicator.<init>(Replicator.scala:1249)
[error] 	at akka.cluster.ddata.Replicator$.$anonfun$props$2(Replicator.scala:379)
[error] 	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
[error] 	at akka.actor.Props.newActor(Props.scala:212)
[error] 	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
[error] 	at akka.actor.ActorCell.create(ActorCell.scala:635)
[error] 	... 16 more
[error] [management-api-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorCell - changing Recreate into Create after akka.actor.ActorInitializationException: akka://management-api/system/clusterReceptionist/replicator: exception during creation
```

Why would I shut down an actor system immediately after starting it? Because I started the actor system, and then tried to extract my own settings from its settings, and failed, and cleaned up. I think the replicator ends up in an infinite restart loop, so you can end up with screens upon screens of errors, and trying to find that one original error logged that caused the actor system to be immediately shut down might be quite difficult (I had to start a new terminal session so I could just scroll up to the top of the screen to find it).

**Comment by patriknw** [comment]
Thanks for reporting, we'll look into it.
