### ISSUE TITLE
BehaviorTestKit fails when testing for child actor

### ISSUE THREAD

**Issue by maxbalan** [akka/akka#27996]
Akka-Java: 2.5.25
Test: Groovy + Spock

The issue happens only when the behavior is wrapped in a static method, like the `child` in the example below. It passes with no exception if the `child` behavior is converted into a static variable like the `main` one.

Test used to reproduce:
```
class SpawnSpec extends Specification {
    
   def "child should be spawn"() {
        when:
        def test = BehaviorTestKit.create(Test.main)

        then:
        test.expectEffect(Effects.spawned(Test.child(), "child", Props.empty()))
    }

    class Test {
        public final static Behavior<String> main =
            Behaviors.setup({ctx ->
                def child = ctx.spawn(Test.child(), "child");

                return Behaviors.<String>receive(String.class)
                                .onMessage(String.class, {msg -> child.tell(msg)})
                                .build()
            })


        public static final Behavior<String> child() {
            return Behaviors.setup({ctx ->

                return Behaviors.<String> receive(String.class)
                                .onMessage(String.class, {msg -> println msg})
                                .build()

            })
        }
    }
}
```

Test results:
```
Condition failed with Exception:

test.expectEffect(Effects.spawned(Test.child(), "child", Props.empty()))
|    |                    |            |                       |
|    |                    |            |                       EmptyProps
|    |                    |            Deferred(Behaviors.scala:43)
|    |                    Spawned(Deferred(Behaviors.scala:43), child, EmptyProps)
|    java.lang.AssertionError: assertion failed: expected: Spawned(Deferred(Behaviors.scala:43), child, EmptyProps) but found Spawned(Deferred(Behaviors.scala:43), child, EmptyProps)
<akka.actor.testkit.typed.internal.BehaviorTestKitImpl@42383cb0 context=Inbox(Actor[akka.actor.typed.inbox://anonymous/testkit#-1597189271]) currentUncanonical=Deferred(Behaviors.scala:43) akka$actor$testkit$typed$internal$BehaviorTestKitImpl$$current=akka.actor.typed.javadsl.BuiltBehavior@267cde2e>


	at com.beautymoft.jerryservice.akka.account.visibility.change.manager.AccountPublicVisibilityChangeManagerSpec.when guardian start it should start public visibility child actor(AccountPublicVisibilityChangeManagerSpec.groovy:44)
Caused by: java.lang.AssertionError: assertion failed: expected: Spawned(Deferred(Behaviors.scala:43), child, EmptyProps) but found Spawned(Deferred(Behaviors.scala:43), child, EmptyProps)
	at scala.Predef$.assert(Predef.scala:282)
	at akka.actor.testkit.typed.internal.BehaviorTestKitImpl.expectEffect(BehaviorTestKitImpl.scala:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 1 more

```

**Comment by johanandren** [comment]
For cases where you don't have access to a specific instance to compare to you will have to use `expectEffectClass(Spawned.class)` instead and then assert individual fields on the returned `Spawned` object in other ways.

**Comment by maxbalan** [comment]
I see, would nice to have this solution in the docs as well. 

Though what would be the correct way to test the Behavior for an expected type?

**Comment by johanandren** [comment]
If the behavior is `setup(ctx -> new ActualBehavior)` it won't be possible to inspect the actual runtime behavior using the `BehaviorTestKit`, so for that kind of testing it may be better to just cover that a child was spawned with behavior testkit and then do "regular" async testkit testing where you test the expected child behavior when interacting rather than what exact child is created.

**Comment by maxbalan** [comment]
I though so, was thinking since the behavior is a generic and we can get the ref of the child there would be a way to get the class passed to the behavior as well.

Thank you for the help.
