### ISSUE TITLE
java.util.NoSuchElementException: head of empty stream

### ISSUE THREAD

**Issue by dcullender-cb** [akka/akka#28024]
Hi Akka Team,

Thanks for all the great work you do.

We are using akka 2.5.25 and once in a while we see the below exception message. It does not seem to cause any issues but thought I would raise it in any case.

We are using akka grpc with a streaming server API which may be causing this.

Thanks
Daniel

```
java.util.NoSuchElementException: head of empty stream
        at akka.stream.scaladsl.Sink$.$anonfun$head$3(Sink.scala:180)
        at scala.Option.getOrElse(Option.scala:138)
        at akka.stream.scaladsl.Sink$.$anonfun$head$2(Sink.scala:180)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:85)
        at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:122)
        at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
        at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:84)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
        at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
        at scala.concurrent.Promise.trySuccess(Promise.scala:94)
        at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
        at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
        at akka.stream.impl.HeadOptionStage$$anon$2.onUpstreamFinish(Sinks.scala:273)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:576)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:682)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:731)
        at akka.actor.Actor.aroundPreStart(Actor.scala:550)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:550)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:671)
        at akka.actor.ActorCell.create(ActorCell.scala:676)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
It means a stream was run with `Sink.head` but the stream completed without any elements coming through, the trace doesn't say if that is constructed in Akka gRPC or in your own code.

If it is in your code `Sink.headOption` will provide a way to deal with a stream that may not see any elements.

**Comment by Captain1653** [comment]
This issue is quite old. There are no comments for 4 years.

Should this issue be closed?

**Comment by johanandren** [comment]
Lets' close, please re-open if it resurfaces and anyone can share more details or a reproducer.
