### ISSUE TITLE
FAILED: ClusterSingletonLeaseSpec

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28072]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/182/consoleFull

```
[info] akka.cluster.singleton.ClusterSingletonLeaseSpec *** ABORTED *** (16 seconds, 81 milliseconds)
[info]   java.lang.NullPointerException:
[info]   at akka.actor.ActorSystemImpl.printNode$1(ActorSystem.scala:1210)
[info]   at akka.actor.ActorSystemImpl.$anonfun$printTree$1(ActorSystem.scala:1229)
[info]   at scala.collection.immutable.Stream.map(Stream.scala:418)
[info]   at akka.actor.ActorSystemImpl.printNode$1(ActorSystem.scala:1229)
[info]   at akka.actor.ActorSystemImpl.$anonfun$printTree$2(ActorSystem.scala:1230)
[info]   at scala.Option.map(Option.scala:230)
[info]   at akka.actor.ActorSystemImpl.printNode$1(ActorSystem.scala:1230)
[info]   at akka.actor.ActorSystemImpl.$anonfun$printTree$1(ActorSystem.scala:1229)
[info]   at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
[info]   at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
[info]   at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
[info]   at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
[info]   at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
[info]   at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
[info]   at scala.collection.immutable.Stream.force(Stream.scala:269)
[info]   at scala.collection.immutable.Stream.mkString(Stream.scala:759)
[info]   at scala.collection.immutable.Stream.mkString(Stream.scala:756)
[info]   at akka.actor.ActorSystemImpl.printNode$1(ActorSystem.scala:1231)
[info]   at akka.actor.ActorSystemImpl.$anonfun$printTree$1(ActorSystem.scala:1229)
[info]   at scala.collection.immutable.Stream.map(Stream.scala:418)
[info]   at akka.actor.ActorSystemImpl.printNode$1(ActorSystem.scala:1229)
[info]   at akka.actor.ActorSystemImpl.printTree(ActorSystem.scala:1236)
[info]   at akka.testkit.TestKit$.shutdownActorSystem(TestKit.scala:979)
[info]   at akka.testkit.TestKitBase.shutdown(TestKit.scala:838)
[info]   at akka.testkit.TestKitBase.shutdown$(TestKit.scala:834)
[info]   at akka.testkit.TestKit.shutdown(TestKit.scala:928)
[info]   at akka.testkit.AkkaSpec.afterAll(AkkaSpec.scala:92)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:379)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:375)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
[info]   at org.scalatest.Status.withAfterEffect(Status.scala:375)
[info]   at org.scalatest.Status.withAfterEffect$(Status.scala:373)
[info]   at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:782)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:224)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:61)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by patriknw** [comment]
fixed in linked PR
