### ISSUE TITLE
Failed: LatencySpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#28119]
It was too slow for HDRHistogram

```
[info] [JVM-1] rate-10000-size-100: 0 msgs/sec, 0 bytes/sec, totals 19,999 messages 1 MB
[info] [JVM-1] rate-10000-size-100: 0 msgs/sec, 0 bytes/sec, totals 19,999 messages 1 MB
[error] [JVM-1] java.lang.ArrayIndexOutOfBoundsException: value 17265097022 outside of histogram covered range. Caused by: java.lang.ArrayIndexOutOfBoundsException: 25605
[error] [JVM-1] 	at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:537)
[error] [JVM-1] 	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:527)
[error] [JVM-1] 	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:429)
[error] [JVM-1] 	at akka.remote.artery.LatencySpec$Receiver.receiveMessage(LatencySpec.scala:128)
[error] [JVM-1] 	at akka.remote.artery.LatencySpec$Receiver$$anonfun$receive$2.applyOrElse(LatencySpec.scala:115)
[error] [JVM-1] 	at akka.actor.Actor.aroundReceive(Actor.scala:532)
[error] [JVM-1] 	at akka.actor.Actor.aroundReceive$(Actor.scala:530)
[error] [JVM-1] 	at akka.remote.artery.LatencySpec$Receiver.aroundReceive(LatencySpec.scala:96)
[error] [JVM-1] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
[error] [JVM-1] 	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
[error] [JVM-1] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
[error] [JVM-1] 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
[error] [JVM-1] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
[error] [JVM-1] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] [JVM-1] === LatencySpec rate-10000-size-100: RTT 50%ile: 478 µs, 90%ile: 578 µs, 99%ile: 5300 µs, rate: 1,000 msg/s
[error] [JVM-1] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error] [JVM-1] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error] [JVM-1] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

https://jenkins.akka.io:8498/job/akka-nightly/7084/consoleFull

**Comment by patriknw** [comment]
Just something with the HdrHistogram latency reporting. Closing since it doesn't seem to happen often and is not an issue in Akka itself.
