### ISSUE TITLE
UdpConnectedIntegrationSpec: The UDP connection oriented implementation must report error if can not resolve

### ISSUE THREAD

**Issue by raboof** [akka/akka#28133]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/18036/consoleFull
```
java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for CommandFailed(Connect(Actor[akka://UdpConnectedIntegrationSpec/system/testProbe-558#-1504839518],doesnotexist.local:1234,None,List()))
[11-05 23:40:48.987] [info]   at scala.Predef$.assert(Predef.scala:223)
[11-05 23:40:48.987] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[11-05 23:40:48.987] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[11-05 23:40:48.987] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[11-05 23:40:48.987] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:928)
[11-05 23:40:48.987] [info]   at akka.io.UdpConnectedIntegrationSpec.$anonfun$new$2(UdpConnectedIntegrationSpec.scala:48)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly/7100/consoleFull

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/3803/testReport/junit/akka.io/UdpConnectedIntegrationSpec/The_UDP_connection_oriented_implementation_must_report_error_if_can_not_resolve/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7217/testReport/junit/akka.io/UdpConnectedIntegrationSpec/The_UDP_connection_oriented_implementation_must_report_error_if_can_not_resolve/

**Comment by raboof** [comment]
(#28444 added a new log line in this area, let's look at this failure when it happens again)

**Comment by jrudolph** [comment]
It did now:

https://jenkins.akka.io:8498/job/akka-multi-node/3863/testReport/junit/akka.io/UdpConnectedIntegrationSpec/The_UDP_connection_oriented_implementation_must_report_error_if_can_not_resolve/

```
--> [The UDP connection oriented implementation must report error if can not resolve] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for CommandFailed(Connect(Actor[akka://UdpConnectedIntegrationSpec/system/testProbe-573#-154027824],doesnotexist.local:1234,None,List())))]
| [DEBUG] [01/22/2020 09:05:58.553] [pool-1-thread-1-ScalaTest-running-UdpConnectedIntegrationSpec] [WithLogCapturing(akka://UdpConnectedIntegrationSpec)] Logging started for test [The UDP connection oriented implementation must report error if can not resolve]
| [DEBUG] [01/22/2020 09:05:58.585] [UdpConnectedIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://UdpConnectedIntegrationSpec/system/IO-DNS] Resolution request for doesnotexist.local from Actor[akka://UdpConnectedIntegrationSpec/system/IO-UDP-CONN/selectors/$a/0#-297427799]
| [DEBUG] [01/22/2020 09:05:58.586] [UdpConnectedIntegrationSpec-akka.actor.default-blocking-io-dispatcher-19] [akka://UdpConnectedIntegrationSpec/system/IO-DNS/inet-address/$d] Request for [doesnotexist.local] was not yet cached
| [DEBUG] [01/22/2020 09:06:04.579] [pool-1-thread-1-ScalaTest-running-UdpConnectedIntegrationSpec] [WithLogCapturing(akka://UdpConnectedIntegrationSpec)] Logging finished for test [The UDP connection oriented implementation must report error if can not resolve]
<-- [The UDP connection oriented implementation must report error if can not resolve] End of log messages of test that [Failed(java.lang.AssertionError: assertion 
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7329/testReport/junit/akka.io/UdpConnectedIntegrationSpec/The_UDP_connection_oriented_implementation_must_report_error_if_can_not_resolve/

**Comment by johanandren** [comment]
I thought perhaps this is something node-related, but it has failed on both a3 and a4, and doing a dig of `doesnotexist.local` fails to resolve in 1-2ms when I try with nslookup, however I managed to get curl to take a long time (5s ish) to resolve once (before cached). Could that perhaps be something about IPv4 vs IPv6 DNS (https://unix.stackexchange.com/questions/290987/resolving-hostname-takes-5-seconds)?

Anyways I think 5s timeout of DNS resolution verified with a 6s timeout in the test seems like it is a bit tight and could perhaps trigger falsely on a bad day. I'll increase that with some more time.

**Comment by johanandren** [comment]
This is the culprit on the Java side, `java.net.InetAddress.getAllByName` seemingly hanging:

```
"UdpConnectedIntegrationSpec-akka.actor.default-blocking-io-dispatcher-12" Id=36 RUNNABLE (in native)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at akka.io.InetAddressDnsResolver$$anonfun$receive$1.applyOrElse(InetAddressDnsResolver.scala:127)
```

**Comment by johanandren** [comment]
Could possibly be https://bugs.openjdk.java.net/browse/JDK-8158038
