### ISSUE TITLE
Failed: TimerSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28261]
https://jenkins.akka.io:8498/job/akka-multi-node/3763/testReport/junit/akka.actor.typed/TimerSpec/A_timer_must_replace_timer/
https://jenkins.akka.io:8498/job/akka-multi-node/3762/#showFailuresLink
https://jenkins.akka.io:8498/job/akka-multi-node/3758/
https://jenkins.akka.io:8498/job/akka-multi-node/3760/#showFailuresLink
https://jenkins.akka.io:8498/job/akka-multi-node/3759/testReport/
https://jenkins.akka.io:8498/job/akka-multi-node/3758/testReport/junit/akka.actor.typed/TimerSpec/A_timer_must_replace_timer/

Probably related to #27875 getting merged?

```
expected Tock(2), found Tock(1)
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:164)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:143)
	at akka.actor.typed.TimerSpec.$anonfun$new$7(TimerSpec.scala:135)
```

**Comment by raboof** [comment]
hum another case of #27937?
