### ISSUE TITLE
Failed: ArteryRemoteNodeDeathWatchSlow

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28440]
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/226/consoleFull

```
[info] [JVM-1] - must cleanup when watching node crash (on node 'first', class akka.remote.ArteryRemoteNodeDeathWatchSlowMultiJvmNode1) *** FAILED *** (3 seconds, 13 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for hello7
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:928)
[info] [JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec.$anonfun$new$26(RemoteNodeDeathWatchSpec.scala:442)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:384)
[info] [JVM-1]   at akka.remote.RemoteNodeDeathWatchSpec.$anonfun$new$24(RemoteNodeDeathWatchSpec.scala:438)
```

**Comment by patriknw** [comment]
Looked a bit at this, but can't see a reason. It's some ordinary message exchange that fails within the 3 seconds. Transport is aeron-udp.

**Comment by patriknw** [comment]
Closing as old
