### ISSUE TITLE
Failed: ReplicatorPruningSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28491]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2231/consoleText

```
10 was not equal to 11 (ReplicatorPruningSpec.scala:229)
```

**Comment by raboof** [comment]
again at https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2255/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2337

**Comment by octonato** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2516/consoleText

```scala
[info] [JVM-2] - must move data from removed node *** FAILED *** (11 seconds, 257 milliseconds)
[info] [JVM-2]   10 was not equal to 11 (ReplicatorPruningSpec.scala:230)
[info] [JVM-2]   org.scalatest.exceptions.TestFailedException:
```

**Comment by raboof** [comment]
Again at https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2565/consoleFull

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2591/consoleText

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2653/console

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2705/consoleText

```
0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [INFO] [05/02/2021 09:48:06.157] [ReplicatorPruningSpec-akka.remote.default-remote-dispatcher-17] [akka://ReplicatorPruningSpec@a5.moxie:49168/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m- must move data from removed node *** FAILED *** (11 seconds, 229 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  10 was not equal to 11 (ReplicatorPruningSpec.scala:230)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.ddata.ReplicatorPruningSpec$$anonfun$updateAfterPruning$1$1.applyOrElse(ReplicatorPruningSpec.scala:230)[0m[0m
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4450956907?check_suite_focus=true#step:5:21280

**Comment by pvlugter** [comment]
This one has popped up again:

https://github.com/akka/akka/runs/6824101495?check_suite_focus=true#step:9:36095

```
[info] [JVM-2] - must move data from removed node *** FAILED *** (14 seconds, 424 milliseconds)
[info] [JVM-2]   10 was not equal to 11 (ReplicatorPruningSpec.scala:230)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7035011964?check_suite_focus=true

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/7313568840?check_suite_focus=true

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/2815036186

```
[akka://ReplicatorPruningSpec@test-node2:6000] - Ignoring received gossip from unknown [UniqueAddress(akka://ReplicatorPruningSpec@test-node3:6000,-6786409748423954691)]
2022-08-08T03:48:51.5404968Z [info] [JVM-3] - must move data from removed node *** FAILED *** (7 seconds, 816 milliseconds)
2022-08-08T03:48:51.5406230Z [info] [JVM-3]   java.lang.AssertionError: assertion failed: expected UpdateSuccess(A,None), found UpdateTimeout(A,None)
2022-08-08T03:48:51.5407191Z [info] [JVM-3]   at scala.Predef$.assert(Predef.scala:279)
2022-08-08T03:48:51.5408087Z [info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
2022-08-08T03:48:51.5408930Z [info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
2022-08-08T03:48:51.5409743Z [info] [JVM-3]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
2022-08-08T03:48:51.5410543Z [info] [JVM-3]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
2022-08-08T03:48:51.5412019Z [info] [JVM-3]   at akka.cluster.ddata.ReplicatorPruningSpec.$anonfun$new$2(ReplicatorPruningSpec.scala:98)
2022-08-08T03:48:51.5413239Z [info] [JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2022-08-08T03:48:51.5414193Z [info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
2022-08-08T03:48:51.5415023Z [info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
2022-08-08T03:48:51.5415747Z [info] [JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
2022-08-08T03:48:51.5416478Z [info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
2022-08-08T03:48:51.5417293Z [info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
2022-08-08T03:48:51.5418089Z [info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
2022-08-08T03:48:51.5418888Z [info] [JVM-3]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
2022-08-08T03:48:51.5419640Z [info] [JVM-3]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
2022-08-08T03:48:51.5420490Z [info] [JVM-3]   at akka.cluster.ddata.ReplicatorPruningSpec.withFixture(ReplicatorPruningSpec.scala:39)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4380726282/jobs/7668091352

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4695664510/jobs/8325031421

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5086502919/jobs/9141012227
