### ISSUE TITLE
Streams testkit - InvalidActorNameException when creating test probes

### ISSUE THREAD

**Issue by Charlyzzz** [akka/akka#28509]
Hi!
I've managed to create a simple snippet that reproduces a bug

```
class FailingTest extends ScalaTestWithActorTestKit with AnyFreeSpecLike {

  "fails" in {
    implicit val untypedSystem: ActorSystem = testKit.system.toClassic
    implicit val materializer: Materializer = ActorMaterializer()

    val (pub, sub) = TestSource.probe[Int]
      .map(_ + 1)
      .toMat(TestSink.probe[Int])(Keep.both)
      .run()
    testKit.createTestProbe()
  }
}
```
The exception I'm getting is 
```
actor name [testProbe-1] is not unique!
akka.actor.InvalidActorNameException: actor name [testProbe-1] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:134)
	at akka.actor.dungeon.Children.reserveChild(Children.scala:139)
	at akka.actor.dungeon.Children.reserveChild$(Children.scala:137)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:447)
	at akka.actor.dungeon.Children.makeChild(Children.scala:289)
	at akka.actor.dungeon.Children.attachChild(Children.scala:51)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:50)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:447)
	at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:774)
	at akka.testkit.TestKitBase.$init$(TestKit.scala:181)
	at akka.testkit.TestKit.<init>(TestKit.scala:923)
	at akka.testkit.TestProbe.<init>(TestKit.scala:984)
	at akka.testkit.TestProbe.<init>(TestKit.scala:986)
	at akka.testkit.TestProbe$.apply(TestKit.scala:1020)
	at akka.stream.testkit.TestSubscriber$ManualProbe.<init>(StreamTestKit.scala:298)
	at akka.stream.testkit.TestSubscriber$Probe.<init>(StreamTestKit.scala:758)
	at akka.stream.testkit.TestSubscriber$.probe(StreamTestKit.scala:286)
	at akka.stream.testkit.StreamTestKit$ProbeSink.create(StreamTestKit.scala:860)
	at akka.stream.impl.SinkModulePhase.materializeAtomic(PhasedFusingActorMaterializer.scala:870)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:492)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:451)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:444)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:629)
	at typeracer.flow.FailingTest.$anonfun$new$1(Test.scala:21)
```
Creating the probe first throws the same exception.

Is this an expected behavior? What I'm missing?

Thanks!

PS: `akka-actor-typed`, `akka-actor-testkit-typed` and `akka-stream-testkit` are at version 2.5.26

**Comment by Charlyzzz** [comment]
Naming the probe makes the test pass.

**Comment by johanandren** [comment]
Thanks for letting us know, I'd expect it is the same in 2.6 but did you verify that?

**Comment by Charlyzzz** [comment]
Yes, it's still failing

**Comment by johanandren** [comment]
Thanks for confirming that it is still an issue in 2.6.
