### ISSUE TITLE
ScalatestRouteTest and Artery BindException

### ISSUE THREAD

**Issue by politrons** [akka/akka#28548]
Hi all, 

Using Akka version **2.6.3** and **ScalatestRouteTest** with the configuration of provider as cluster, we're facing the issue that the artery default port (**25520**) is getting stuck, so in our next **ScalatestRouteTest** test defined in our scalaTest framework is failing because BindAddressException.

I also experiment the very same issue using **TestKit**, even terminating the actorSystem in my afterAll

```
  override def afterAll {
    TestKit.shutdownActorSystem(system)
  }
```

The error as I mention is a BindAddressException

```
  Cause: akka.remote.RemoteTransportException: Failed to bind TCP to [10.0.75.1:25520] due to: Bind failed because of java.net.BindException: [/10.0.75.1:25520] Address already in use: bind
  at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:269)
  at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:263)
  at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
  at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
  at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:85)
  at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:122)
  at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
```

Any solution or workaround of this problem?.

Put provider as local, fix the problem, but we need to test some cluster scenarios, so is not a possible workaround.

Regards.

**Comment by patriknw** [comment]
Hi, we use github issues just for bugs and feature requests. Your question doesn't seem to fall in that range. Can you please ask it on https://discuss.akka.io ?

That will help us a lot to keep this place clean for actual work items (and you will probably find a bigger audience there to help you with that question).

You have probably started several ActorSystems, and only one can bind to the port. Using port 0 to dynamically assign free port is often best in tests.
