### ISSUE TITLE
Failed: LeveldbJournalNativePerfSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#28556]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7351/consoleFull

```
[info] - must measure: persist()-ing 100 events *** FAILED *** (10 seconds, 8 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsg while waiting for 100
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:418)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:404)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:404)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:928)
[info]   at akka.persistence.journal.JournalPerfSpec.feedAndExpectLast(JournalPerfSpec.scala:136)
[info]   at akka.persistence.journal.JournalPerfSpec.$anonfun$new$7(J
```

**Comment by renatocaval** [comment]
There is nothing else in the logs that could explain a 10 seconds timeout. 

Last similar occurrence was almost one year ago (https://github.com/akka/akka/issues/24708)

Closing for now...
