### ISSUE TITLE
Latency of Artery must be low for warmup, at 10000 msg/s, payloadSize = 100

### ISSUE THREAD

**Issue by raboof** [akka/akka#28609]
https://jenkins.akka.io:8498/job/akka-multi-node/3900/consoleFull

```
[info] [JVM-1] - must be low for warmup, at 10000 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.LatencySpecMultiJvmNode1) *** FAILED *** (22 seconds, 937 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (22 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$a#-1854517188]
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:437)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:434)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:929)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectTerminated(TestKit.scala:452)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectTerminated$(TestKit.scala:451)
[info] [JVM-1]   at akka.testkit.TestKit.expectTerminated(TestKit.scala:929)
[info] [JVM-1]   at akka.remote.artery.LatencySpec.$anonfun$test$2(LatencySpec.scala:321)
[info] [JVM-1]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[info] [JVM-1]   at akka.remote.artery.LatencySpec.$anonfun$test$1(LatencySpec.scala:272)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:384)
[info] [JVM-1]   at akka.remote.artery.LatencySpec.test(LatencySpec.scala:252)
```

**Comment by patriknw** [comment]
Here is another hiccup, but with tcp https://jenkins.akka.io:8498/job/akka-artery-tcp-perf/1444

```
[info] [JVM-1] rate-20000-size-100: 20,878 msgs/sec, 2,087,800 bytes/sec, totals 653,066 messages 62 MB
[info] [JVM-1] rate-20000-size-100: 20,767 msgs/sec, 2,076,668 bytes/sec, totals 673,840 messages 64 MB
[info] [JVM-1] rate-20000-size-100: 20,855 msgs/sec, 2,085,489 bytes/sec, totals 694,704 messages 66 MB
[info] [JVM-1] Measured send rate 19634 msg/s (new adjustment factor: 2.3108515357257158)
[info] [JVM-1] rate-20000-size-100: 14,885 msgs/sec, 1,488,468 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] rate-20000-size-100: 0 msgs/sec, 0 bytes/sec, totals 709,594 messages 67 MB
[info] [JVM-1] - must be low for rate-20000-size-100, at 20000 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.LatencySpecMultiJvmNode1) *** FAILED *** (1 minute, 16 seconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (40 seconds) during expectMsg: Terminated Actor[akka://LatencySpec/user/$n#-1942707029]
```

**Comment by patriknw** [comment]
another, in ordinary multi-node job
https://jenkins.akka.io:8498/job/akka-multi-node/3982

**Comment by patriknw** [comment]
and https://jenkins.akka.io:8498/job/akka-artery-tcp-perf/1448

**Comment by johanandren** [comment]
Long time no see, ordinary multi-node-job, tcp:

https://jenkins.akka.io:8498/job/akka-multi-node/4383

**Comment by patriknw** [comment]
closing as old
