### ISSUE TITLE
ActorSystemSpec intermittently fails

### ISSUE THREAD

**Issue by SethTisue** [akka/akka#28648]
I've now seen this a number of times in the Scala community build

for example, from https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3234/artifact/logs/akka-build.log

```
[akka] [info] An ActorSystem
[akka] [info] - must use scala.concurrent InternalCallbackExecutor/parasitic (7 milliseconds)
[akka] [info] - must reject invalid names (2 milliseconds)
[akka] [info] - must allow valid names (144 milliseconds)
[akka] [info] - must log dead letters (307 milliseconds)
[akka] [WARN] [02/26/2020 01:54:59.495] [LogDeadLetters-akka.actor.default-dispatcher-7] [akka://LogDeadLetters/user/$a] received dead letter: boom
[akka] [info] - must log dead letters sent without sender reference *** FAILED *** (323 milliseconds)
[akka] [info]   java.lang.AssertionError: received 1 excess messages on InfoFilter(None,Right(.*not delivered),false)
[akka] [info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:124)
[akka] [info]   at akka.actor.ActorSystemSpec.$anonfun$new$10(ActorSystemSpec.scala:193)
```

see also:

* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/728/artifact/logs/akka-build.log
* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/706/artifact/logs/akka-build.log
* https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3112/artifact/logs/akka-build.log
* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1107/artifact/logs/akka-build.log
* https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1064/artifact/logs/akka-build.log

I didn't look closely at whether all the failures are identical

**Comment by SethTisue** [comment]
for, I've excluded ActorSystemTest.scala from the community build

**Comment by SethTisue** [comment]
https://github.com/scala/community-build/pull/1100
