### ISSUE TITLE
Failed: Error downloading com.lightbend.paradox:sbt-paradox;sbtVersion=1.0;scalaVersion=2.12:0.6.9 from proxy-ch.typesafe.com artifactory

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28649]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/306/console
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/523/console
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2273/console

```
[akka-nightly-jdk11] $ /usr/lib/jvm/jdk-11.0.1+13/bin/java -Dsbt.log.noformat=false -Dsbt.ivy.home=/localhome/jenkinsakka/.ivy2 -Dakka.build.M2Dir=/localhome/jenkinsakka/.m2/repository -Dakka.test.timefactor=1 -Dsbt.override.build.repos=true -Dakka.genjavadoc.enabled=true -Dakka.test.multi-in-test=false -Xmx3072M -Xms1024M -jar /usr/share/sbt/bin/sbt-launch.jar clean test checkTestsHaveRun
[info] Loading settings for project akka-nightly-jdk11-build from plugins.sbt ...
[info] Loading project definition from /localhome/jenkinsakka/workspace/akka-nightly-jdk11/project
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.lightbend.paradox:sbt-paradox:0.6.9 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.lightbend.paradox:sbt-paradox;sbtVersion=1.0;scalaVersion=2.12:0.6.9
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinsakka/.ivy2/local/com.lightbend.paradox/sbt-paradox/scala_2.12/sbt_1.0/0.6.9/ivys/ivy.xml
[error]   not found: https://proxy-ch.typesafe.com:8082/artifactory/repo/com.lightbend.paradox/sbt-paradox/scala_2.12/sbt_1.0/0.6.9/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 409 for URL: https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom (Server returned HTTP response code: 409 for URL: https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom) while downloading https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:246)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:215)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:215)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.lightbend.paradox:sbt-paradox;sbtVersion=1.0;scalaVersion=2.12:0.6.9
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinsakka/.ivy2/local/com.lightbend.paradox/sbt-paradox/scala_2.12/sbt_1.0/0.6.9/ivys/ivy.xml
[error]   not found: https://proxy-ch.typesafe.com:8082/artifactory/repo/com.lightbend.paradox/sbt-paradox/scala_2.12/sbt_1.0/0.6.9/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 409 for URL: https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom (Server returned HTTP response code: 409 for URL: https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom) while downloading https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom
```

That `409 Conflict` error message is this:

```
λ curl -vvv https://proxy-ch.typesafe.com:8082/artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom
*   Trying 128.179.67.43:8082...
* TCP_NODELAY set
* Connected to proxy-ch.typesafe.com (128.179.67.43) port 8082 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=proxy-ch.typesafe.com
*  start date: Sep  3 00:00:00 2018 GMT
*  expire date: Dec  1 23:59:59 2020 GMT
*  subjectAltName: host "proxy-ch.typesafe.com" matched cert's "proxy-ch.typesafe.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET /artifactory/repo/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom HTTP/1.1
> Host: proxy-ch.typesafe.com:8082
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 409 Conflict
< Server: Artifactory/4.7.1
< X-Artifactory-Id: 908fc7e3a9a685b7:-51017054:1705488daf7:-8000
< Content-Type: application/json;charset=ISO-8859-1
< Transfer-Encoding: chunked
< Date: Wed, 26 Feb 2020 12:51:25 GMT
< 
{
  "errors" : [ {
    "status" : 409,
    "message" : "The target deployment path 'com/lightbend/paradox/sbt-paradox_2.12_1.0/0.6.9/sbt-paradox-0.6.9.pom' does not match the POM's expected path prefix 'com/lightbend/paradox/sbt-paradox/0.6.9'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."
  } ]
* Connection #0 to host proxy-ch.typesafe.com left intact
}%       
```

The question is where that proxy-ch resolver comes from and what changed in recent builds (or can it be a race condition?).

**Comment by jrudolph** [comment]
I checked the artifactory logs and it happens when artifactory tries to store the pom from maven central into the local cache. There's no significant difference between sbt-paradox 0.6.8 and 0.6.9 so it seems the stricter POM checking wasn't enabled before? I tried to see if artifactory might have been updated in the meantime but due to log rotation there are no logs of the second last artifactory restart.

It seems previously we tried to remove artifactory from the loop at least for some jobs, see #22980, so that could be one solution if we cannot make it work otherwise.

**Comment by jrudolph** [comment]
https://stackoverflow.com/questions/43740489/sbt-and-maven-using-local-artifactory-server might be a solution if we find someone who can enable it.

**Comment by jrudolph** [comment]
The problem was probably that the proxy still used http access to download artifacts. It had both sonatype releases and maven central defined but only for maven central it disabled pom consistency checks. Then when http access to maven central stopped working, it tried to download from sonatype central and failed because of the pom issue. I found a way to reconfigure artifactory (without admin credentials), so that it now uses https to every upstream repo and also disabled the pom consistency check for sonatype central which fixes this issue.
