### ISSUE TITLE
akka-more AskSpec failure in 2.13 community build

### ISSUE THREAD

**Issue by szeiger** [akka/akka#28650]
The failed job is https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/3235/

It's testing https://github.com/scala/scala/pull/8534 on top of other 2.13.2 changes. The failure may be timeout-related and everything else passed in this build which makes the new `Vector` an unlikely cause.

I started a rebuild: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/3237/

Possibly related to https://github.com/akka/akka/issues/19341.

According to @SethTisue in https://typesafe.slack.com/archives/C02A6LVUZ/p1582727428113700?thread_ts=1582726604.111000&cid=C02A6LVUZ:

> I have seen the AskSpec failure before. for no particular reason, I just hadn't reported it to akka/akka yet. so I'm confident it's not related to your changes.

**Comment by SethTisue** [comment]
e.g. from Jan 15 https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3052/artifact/logs/akka-more-build.log

**Comment by johanandren** [comment]
```
[akka-more] [info] - must fail the future if the actor doesn't exist *** FAILED *** (3 seconds, 9 milliseconds)
[akka-more] [info]   java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.
[akka-more] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
[akka-more] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:176)
[akka-more] [info]   at scala.Option.getOrElse(Option.scala:201)
[akka-more] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:176)
[akka-more] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:169)
[akka-more] [info]   at akka.actor.typed.AskSpec.$anonfun$new$10(AskSpec.scala:106)
```

and logs:

```
[akka-more] --> [[34makka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't exist[0m] Start of log messages of test that [Failed(java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.)]
[akka-more] 2020-01-16 00:18:01,295 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started {}
[akka-more] 2020-01-16 00:18:01,304 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor is already terminated] {}
[akka-more] 2020-01-16 00:18:01,407 INFO  akka.actor.LocalActorRef akkaDeadLetter - Message [akka.actor.typed.AskSpec$Foo] to Actor[akka://AskSpec/user/$a#1538206448] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://AskSpec/user/$a#1538206448] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. {akkaAddress=akka://AskSpec, sourceThread=AskSpec-akka.actor.default-dispatcher-3, akkaSource=akka://AskSpec/user/$a, sourceActorSystem=AskSpec, akkaMessageClass=akka.actor.typed.AskSpec$Foo, akkaTimestamp=00:18:01.407UTC}
[akka-more] 2020-01-16 00:18:01,407 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor is already terminated] that [Succeeded] {}
[akka-more] 2020-01-16 00:18:01,408 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.AskSpec: Ask pattern must succeed when the actor is alive] {}
[akka-more] 2020-01-16 00:18:01,509 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.AskSpec: Ask pattern must succeed when the actor is alive] that [Succeeded] {}
[akka-more] 2020-01-16 00:18:01,510 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.AskSpec: Ask pattern must provide a symbolic alias that works the same] {}
[akka-more] 2020-01-16 00:18:01,611 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.AskSpec: Ask pattern must provide a symbolic alias that works the same] that [Succeeded] {}
[akka-more] 2020-01-16 00:18:01,612 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't reply in time] {}
[akka-more] 2020-01-16 00:18:01,715 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't reply in time] that [Succeeded] {}
[akka-more] 2020-01-16 00:18:01,716 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't exist] {}
[akka-more] 2020-01-16 00:18:01,730 INFO  akka.actor.DeadLetterActorRef akkaDeadLetter - Message [akka.actor.typed.AskSpec$Foo] to Actor[akka://AskSpec/deadLetters] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://AskSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. {akkaAddress=akka://AskSpec, sourceThread=AskSpec-akka.actor.default-dispatcher-3, akkaSource=akka://AskSpec/deadLetters, sourceActorSystem=AskSpec, akkaMessageClass=akka.actor.typed.AskSpec$Foo, akkaTimestamp=00:18:01.718UTC}
[akka-more] 2020-01-16 00:18:04,719 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't exist] that [Failed(java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.)] {}
[akka-more] <-- [[34makka.actor.typed.AskSpec: Ask pattern must fail the future if the actor doesn't exist[0m] End of log messages of test that [Failed(java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.)]
```
