### ISSUE TITLE
Leases implemented in Java don't work

### ISSUE THREAD

**Issue by dogenkigen** [akka/akka#28685]
If there is Lease created in Java by implementing `akka.coordination.lease.javadsl.Lease` there will be exception thrown:

```
09:23:08.369 [test-lease-akka.actor.default-dispatcher-11] ERROR a.c.lease.scaladsl.LeaseProvider - Invalid lease configuration for leaseName [test], configPath [test-lease] lease-class [com.test.MyLease]. The class must implement Lease and have constructor with LeaseSettings parameter and optionally ActorSystem parameter.
java.lang.ClassCastException: class akka.coordination.lease.scaladsl.Lease is not assignable from class com.test.MyLease
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:31)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:66)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:57)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.coordination.lease.scaladsl.LeaseProvider.getLease(LeaseProvider.scala:52)
	at akka.coordination.lease.javadsl.LeaseProvider.getLease(LeaseProvider.scala:37)
	at com.test.TestLeaseMain.main(TestLeaseMain.java:21)
09:23:09.370 [main] ERROR com.test.TestLeaseMain - Error
java.lang.ClassCastException: class akka.coordination.lease.scaladsl.Lease is not assignable from class com.test.MyLease
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:31)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:66)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:57)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:52)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.coordination.lease.scaladsl.LeaseProvider.getLease(LeaseProvider.scala:52)
	at akka.coordination.lease.javadsl.LeaseProvider.getLease(LeaseProvider.scala:37)
	at com.test.TestLeaseMain.main(TestLeaseMain.java:21)
```

Seems like the Akka internals are trying to cast it to `akka.coordination.lease.scaladsl.Lease`. My configuration is the following:

```
akka.actor.provider = cluster
test-lease {
  lease-class = "com.test.MyLease"
  heartbeat-timeout = 5s
  heartbeat-interval = 1s
  lease-operation-timeout = 5s
}
```

And the Lease implementation looks like this:

```java
package com.test;

import akka.coordination.lease.LeaseSettings;
import akka.coordination.lease.javadsl.Lease;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import java.util.function.Consumer;

public class MyLease extends Lease {

    private final LeaseSettings settings;

    public MyLease(LeaseSettings settings) {
        this.settings = settings;
    }

    @Override
    public LeaseSettings getSettings() {
        return settings;
    }

    @Override
    public CompletionStage<Boolean> acquire() {
        return null;
    }

    @Override
    public CompletionStage<Boolean> acquire(Consumer<Optional<Throwable>> leaseLostCallback) {
        return null;
    }

    @Override
    public CompletionStage<Boolean> release() {
        return null;
    }

    @Override
    public boolean checkLease() {
        return false;
    }
}
```

**Comment by patriknw** [comment]
Thanks for reporting. That seems to be an oversight that should be fixed immediately.

**Comment by chbatey** [comment]
Ah doh the test for java loads the scala one

**Comment by dogenkigen** [comment]
> 
> 
> Ah doh the test for java loads the scala one

Yep ;)

**Comment by chbatey** [comment]
We should also add tests for scala loading java leases and java loading scala leases
