### ISSUE TITLE
Failure: "Could not apply tag" in release build

### ISSUE THREAD

**Issue by seglo** [akka/akka#28684]
https://jenkins.akka.io:8498/job/akka-release-2.5/196/console

```
 > git tag -a -f -m Jenkins Build #196 jenkins-akka-release-2.5-196 # timeout=10
FATAL: Could not apply tag jenkins-akka-release-2.5-196
hudson.plugins.git.GitException: Command "git tag -a -f -m Jenkins Build #196 jenkins-akka-release-2.5-196" returned status code 128:
stdout: 
stderr: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect name (got 'Unknown')

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2429)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2359)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2355)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1915)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1927)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.tag(CliGitAPIImpl.java:1794)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to a7
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
		at com.sun.proxy.$Proxy102.tag(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.tag(RemoteGitImpl.java:502)
		at hudson.plugins.git.extensions.impl.PerBuildTag.onCheckoutCompleted(PerBuildTag.java:30)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1237)
		at hudson.scm.SCM.checkout(SCM.java:505)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1205)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1853)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:427)
Caused: hudson.plugins.git.GitException: Could not apply tag jenkins-akka-release-2.5-196
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.tag(CliGitAPIImpl.java:1796)
	at hudson.plugins.git.GitAPI.tag(GitAPI.java:282)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, /localhome/jenkinsakka/workspace/akka-release-2.5/akka-actor-testkit-typed/target/test-reports/TEST-akka.actor.testkit.typed.javadsl.ActorTestKitTest.xml is 3 days 2 hr old
```

May have been a transient issue related to the LDAP failure on a7, but as of creating this issue there have been no green builds yet.

**Comment by chbatey** [comment]
Why do we tag the build and not push it? I removed it from the job for now.

**Comment by thisismanikandan** [comment]
To solve this, please configure the username and useremail in Jenkins GIT Plugin. The steps are listed below:

1. Login Jenkins and Click "Manage Jenkins".
2. Click "System" option.
3. Search for Git Plugin
4. Enter the Name and Email for Git user.name and user.email
