### ISSUE TITLE
failed: LargeMessagesStreamSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28700]
Failed in PR validation for 2.5 branch.
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19099

```
[03-06 14:21:29.577] [info] The large message support
[03-06 14:21:30.116] [info] - should not affect regular communication (538 milliseconds)
[03-06 14:21:35.201] [info] - should pass small regular messages over the large-message stream *** FAILED *** (5 seconds, 74 milliseconds)
[03-06 14:21:35.201] [info]   akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://LargeMessagesStreamSpec-remote-1@localhost:55791/), Path(/user/large)]
[03-06 14:21:35.217] [info]   at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:75)
[03-06 14:21:35.217] [info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[03-06 14:21:35.217] [info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[03-06 14:21:35.217] [info]   at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
[03-06 14:21:35.217] [info]   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:85)
[03-06 14:21:35.217] [info]   at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:122)
[03-06 14:21:35.217] [info]   at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
[03-06 14:21:35.217] [info]   at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:84)
[03-06 14:21:35.217] [info]   at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
[03-06 14:21:35.217] [info]   at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:316)
[03-06 14:21:35.217] [info]   at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:307)
[03-06 14:21:35.218] [info]   at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:73)
[03-06 14:21:35.218] [info]   at akka.actor.ActorSelection.resolveOne(ActorSelection.scala:90)
[03-06 14:21:35.218] [info]   at akka.remote.artery.LargeMessagesStreamSpec.awaitResolve(LargeMessagesStreamSpec.scala:128)
[03-06 14:21:35.218] [info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$new$4(LargeMessagesStreamSpec.scala:74)
```

**Comment by johanandren** [comment]
The test verified that the actor has started using a ping-pong on node A before it tries to look it up over remoting from node B. The lookup explicitly failed with an `Actor not found` though, I wonder if that would happen if remoting is not completely set up yet when calling `resolveOne`.

**Comment by johanandren** [comment]
Verified that is what happens, so a slow remoting setup likely.

**Comment by johanandren** [comment]
Closing, re-open and fix if it ever happens again
