### ISSUE TITLE
Failed: ManualTimerExampleTest

### ISSUE THREAD

**Issue by chbatey** [akka/akka#28702]
```
Error Message
java.lang.AssertionError: Timeout (3 seconds) during expectMessageClass waiting for class jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest$Tock
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: Timeout (3 seconds) during expectMessageClass waiting for class jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest$Tock
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:233)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass(TestProbeImpl.scala:218)
	at jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest.testScheduleNonRepeatedTicks(ManualTimerExampleTest.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAc
```

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/532/testReport/junit/jdocs.akka.actor.testkit.typed.javadsl/ManualTimerExampleTest/testScheduleNonRepeatedTicks/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/758/

```
--> [[34mjdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest: testScheduleNonRepeatedTicks[0m] Start of log messages of test that failed with Timeout (3 seconds) during expectMessageClass waiting for class jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest$Tock
2020-10-16 11:00:52,801 ERROR akka.actor.SupervisorStrategy  - cannot use Same as initial behavior MDC: {akkaAddress=akka://ActorTestKitTest, akkaSource=akka://ActorTestKitTest/user, sourceActorSystem=ActorTestKitTest}
akka.actor.ActorInitializationException: akka://ActorTestKitTest/user/$a: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:661)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalArgumentException: cannot use Same as initial behavior
	at akka.actor.typed.Behavior$.validateAsInitial(Behavior.scala:207)
	at akka.actor.typed.internal.adapter.ActorAdapter.preStart(ActorAdapter.scala:281)
	at akka.actor.Actor.aroundPreStart(Actor.scala:548)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:256)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	... 10 common frames omitted
2020-10-16 11:00:52,924 INFO  akka.actor.testkit.typed.javadsl.LogCapturing  - Logging started for test [jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest: testScheduleNonRepeatedTicks] MDC: {}
<-- [[34mjdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest: testScheduleNonRepeatedTicks[0m] End of log messages of test that failed with Timeout (3 seconds) during expectMessageClass waiting for class jdocs.akka.actor.testkit.typed.javadsl.ManualTimerExampleTest$Tock
```

**Comment by patriknw** [comment]
This is weird, possibly a bug. "cannot use Same as initial behavior" and it's when starting the actor. Where does that `same` come from?

**Comment by patriknw** [comment]
Closing as old
