### ISSUE TITLE
DNS CACHING: Does not attempt to re-resolve DNS, causing infinite retries after the failed host comes up

### ISSUE THREAD

**Issue by alexmnyc** [akka/akka#28744]
Using alpakka SQS sink, akka stream DNS resolver seems to have cached a non-existing host DNS and never tries to re-resolve it
```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: null
[service] 	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
[service] 	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
[service] 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:125)
[service] 	... 23 common frames omitted
[service] Caused by: akka.stream.StreamTcpException: Tcp command [Connect(localstack:4576,None,List(),Some(10 seconds),true)] failed because of java.net.UnknownHostException: localstack
[service] Caused by: java.net.UnknownHostException: localstack
[service] 	at akka.io.dns.DnsProtocol$Resolved.address(DnsProtocol.scala:103)
[service] 	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:82)
[service] 	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:51)
[service] 	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:82)
[service] 	at akka.actor.Actor.aroundReceive(Actor.scala:533)
[service] 	at akka.actor.Actor.aroundReceive$(Actor.scala:531)
[service] 	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:32)
[service] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
[service] 	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
[service] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
[service] 	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
[service] 	at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:653)
[service] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
[service] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[service] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[service] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[service] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by johanandren** [comment]
What Akka version? Also, are you using the `async-dns` or the `inet-address` one (configured through `akka.io.dns.resolver`?

**Comment by alexmnyc** [comment]
akka 2.6.4
i was using alpakka sqs sink that was a restartable, upon restart, it keeps on using cached DNS i.e. "Unknown host". I would imagine the dns resolver should not be caching exceptions

**Comment by alexmnyc** [comment]
The easiest way to replicate is to add a docker network and a few hosts to it. take a host down before starting a service needing to talk to it. bring the service up. bring the upstream "localstack" in this case up. and see the exception continued being thrown

**Comment by johanandren** [comment]
One workaround could be to use the new DNS client, setting `akka.io.dns.resolver = async-dns` in your config.

**Comment by alexmnyc** [comment]
sounds good. let me try that. but i still think the default implementation of DNS resolver shouldn't be caching exception

**Comment by johanandren** [comment]
I agree that is something that we should look into.

**Comment by johanandren** [comment]
Looks like the default negative cache is 10 seconds (see for example https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html ), so behavior is according to spec. It is possible to change the default either by overriding the JVM property or by configuring Akka to ignore the JVM setting in your `application.conf` with `akka.io.dns.inet-address.negative-ttl = never`
