### ISSUE TITLE
Failed: command execution failed: Channel "hudson.remoting.Channel

### ISSUE THREAD

**Issue by renatocaval** [akka/akka#28768]
This seems to be a Jenkins issue.
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/326/

I upgraded the build nodes on the 17th March, that's probably related to it. I'm reporting it here just for the record. If we see it happening again we can investigate it. 

```scala 
FATAL: command execution failed: Channel "hudson.remoting.Channel@58ca34b1:a4": Remote call on a4 failed. The channel is closing down or has closed down
hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@58ca34b1:a4": Remote call on a4 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:948)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
	at com.sun.proxy.$Proxy106.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1150)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1142)
	at hudson.Launcher$ProcStarter.join(Launcher.java:470)
	at org.jvnet.hudson.plugins.SbtPluginBuilder.perform(SbtPluginBuilder.java:127)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1853)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
```

**Comment by renatocaval** [comment]
I'm closing this right away. The goal was just to register it in case it occurs again.

**Comment by raboof** [comment]
probably while upgrading/rebooting a4?
