### ISSUE TITLE
Failed: ManualTimerExampleSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28802]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7508/testReport/junit/docs.akka.actor.testkit.typed.scaladsl/ManualTimerExampleSpec/A_timer_must_schedule_repeated_ticks/

```
java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Tock
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:165)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:143)
	at docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec.$anonfun$new$8(ManualTimerExampleSpec.scala:67)
	at docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec.$anonfun$new$8$adapted(ManualTimerExampleSpec.scala:63)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec.$anonfun$new$5(ManualTimerExampleSpec.scala:63)
```

**Comment by johanandren** [comment]
Duplicate #28801
