### ISSUE TITLE
Failed: ManualTimerExampleSpec: A timer must schedule repeated ticks

### ISSUE THREAD

**Issue by ennru** [akka/akka#28801]
In "akka-nightly-jdk8" build on Jenkins.

`docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec` A timer must schedule repeated ticks

```
sbt.ForkMain$ForkError: java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Tock
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:165)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:143)
	at docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec.$anonfun$new$8(ManualTimerExampleSpec.scala:67)
	at docs.akka.actor.testkit.typed.scaladsl.ManualTimerExampleSpec.$anonfun$new$8$adapted(ManualTimerExampleSpec.scala:63)
```

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7508/testReport/junit/docs.akka.actor.testkit.typed.scaladsl/ManualTimerExampleSpec/A_timer_must_schedule_repeated_ticks/

**Comment by ennru** [comment]
Same error in "akka-nightly-jdk11"

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/620/testReport/junit/docs.akka.actor.testkit.typed.scaladsl/ManualTimerExampleSpec/A_timer_must_schedule_repeated_ticks/

**Comment by patriknw** [comment]
Closing as old
