### ISSUE TITLE
Failed: InputStreamSinkSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#28829]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19380/testReport/junit/akka.stream.io/InputStreamSinkSpec/InputStreamSink_must_propagate_error_to_InputStream/

```
Expected exception java.io.IOException to be thrown, but no exception was thrown
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at akka.testkit.AkkaSpec.newAssertionFailedException(AkkaSpec.scala:96)
	at org.scalatest.Assertions.intercept(Assertions.scala:766)
	at org.scalatest.Assertions.intercept$(Assertions.scala:746)
	at akka.testkit.AkkaSpec.intercept(AkkaSpec.scala:96)
	at akka.stream.io.InputStreamSinkSpec.$anonfun$new$57(InputStreamSinkSpec.scala:273)
```

**Comment by renatocaval** [comment]
Fixed in #28990
