### ISSUE TITLE
Failed: compiler crash with 2.12.11 for akka-publish-nightly job

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28848]
https://jenkins.akka.io:8498/job/akka-publish-nightly/1351/consoleFull

```
[info] Compiling 19 Scala sources and 1 Java source to /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-cluster-sharding-typed/target/scala-2.12/classes ...
[info] /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java: /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java uses or overrides a deprecated API.
[info] /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-cluster-sharding-typed/src/main/java/akka/cluster/sharding/typed/internal/protobuf/ShardingMessages.java: Recompile with -Xlint:deprecation for details.
[info] Done compiling.
[error] java.lang.AssertionError: assertion failed: 
[error]   type AnyRef in java.lang
[error]      while compiling: /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-persistence/src/main/scala/akka/persistence/snapshot/local/LocalSnapshotStore.scala
[error]         during phase: globalPhase=terminal, enteringPhase=silencer
[error]      library version: version 2.12.11
[error]     compiler version: version 2.12.11
```

Will try to reproduce before reporting to compiler team.

**Comment by jrudolph** [comment]
Seems to be a problem with scaladoc that's probably why it wasn't detected earlier.

**Comment by jrudolph** [comment]
Only fails with JDK 11. Simplest reproducer is `sbt akka-actor/doc` with JDK 11:

```
λ sbt11 akka-actor/doc
[info] Loading settings for project global-plugins from plugins.sbt,idea.sbt ...
[info] Loading global plugins from /home/johannes/git/self/config/etc/.sbt/1.0/plugins
[info] Loading settings for project akka-build from plugins.sbt ...
[info] Loading project definition from /tmp/akka-doc-test/akka/project
[info] Loading settings for project akka from build.sbt ...
[info] Resolving key references (49297 settings) ...
[info] Set current project to akka (in build file:/tmp/akka-doc-test/akka/)
[info] Main Scala API documentation to /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/api...
[error] java.lang.AssertionError: assertion failed: 
[error]   type AnyRef in java.lang
[error]      while compiling: /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/src_managed/main/akka/japi/tuple/Tuples.scala
[error]         during phase: globalPhase=terminal, enteringPhase=silencer
[error]      library version: version 2.12.11
[error]     compiler version: version 2.12.11
[error]   reconstructed args: -bootclasspath /home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar -javabootclasspath /home/johannes/.jabba/jdk/adopt@1.8.0-222/jre/lib/rt.jar -feature -unchecked -classpath /home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.11/1.6.0/silencer-lib_2.12.11-1.6.0.jar:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar -d /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/api -language:higherKinds -release 8 -Xlog-reflective-calls -Xplugin:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-plugin_2.12.11/1.6.0/silencer-plugin_2.12.11-1.6.0.jar -doc-external-doc:/modules/java.base#https://docs.oracle.com/en/java/javase/11/docs/api/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.11/1.6.0/silencer-lib_2.12.11-1.6.0.jar#https://javadoc.io/page/com.github.ghik/silencer-lib_2.12.11/1.6.0/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar#https://javadoc.io/page/org.scala-lang.modules/scala-java8-compat_2.12/0.8.0/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar#https://www.scala-lang.org/api/2.12.11/ -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar#https://javadoc.io/page/com.typesafe/config/1.4.0/index.html
[error] 
[error]   last tree to typer: Ident(Tuple22$1)
[error]        tree position: line 304 of /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/src_managed/main/akka/japi/tuple/Tuples.scala
[error]             tree tpe: Tuple22$1.type
[error]               symbol: value Tuple22$1
[error]    symbol definition: val Tuple22$1: akka.japi.tuple.Tuple22[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22] (a TermSymbol)
[error]       symbol package: akka.japi.tuple
[error]        symbol owners: value Tuple22$1 -> method equals -> class Tuple22
[error]            call site: method equals in class Tuple22 in package tuple
[error] 
[error] == Source file context for tree position ==
[error] 
[error]    301  * Java API Tuple container.
[error]    302  */
[error]    303 @SerialVersionUID(1L)
[error]    304 final case class Tuple22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21, t22: T22) {
[error]    305    val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22)
[error]    306 }
[error]    307 
[error]         at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:702)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$8.<init>(ModelFactory.scala:689)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:689)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$8.<init>(ModelFactory.scala:689)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:689)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
[error]         at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
[error]         at scala.tools.nsc.doc.model.ModelFactory$RootPackageImpl.<init>(ModelFactory.scala:487)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$7.<init>(ModelFactory.scala:671)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:671)
[error]         at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createRootPackage(ModelFactory.scala:619)
[error]         at scala.tools.nsc.doc.model.ModelFactory$$anon$1.<init>(ModelFactory.scala:55)
[error]         at scala.tools.nsc.doc.model.ModelFactory.makeModel(ModelFactory.scala:52)
[error]         at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:88)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:131)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1632)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (akka-actor / Compile / doc) java.lang.AssertionError: assertion failed: 
[error]   type AnyRef in java.lang
[error]      while compiling: /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/src_managed/main/akka/japi/tuple/Tuples.scala
[error]         during phase: globalPhase=terminal, enteringPhase=silencer
[error]      library version: version 2.12.11
[error]     compiler version: version 2.12.11
[error]   reconstructed args: -bootclasspath /home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar -javabootclasspath /home/johannes/.jabba/jdk/adopt@1.8.0-222/jre/lib/rt.jar -feature -unchecked -classpath /home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.11/1.6.0/silencer-lib_2.12.11-1.6.0.jar:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar -d /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/api -language:higherKinds -release 8 -Xlog-reflective-calls -Xplugin:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-plugin_2.12.11/1.6.0/silencer-plugin_2.12.11-1.6.0.jar -doc-external-doc:/modules/java.base#https://docs.oracle.com/en/java/javase/11/docs/api/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.11/1.6.0/silencer-lib_2.12.11-1.6.0.jar#https://javadoc.io/page/com.github.ghik/silencer-lib_2.12.11/1.6.0/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar#https://javadoc.io/page/org.scala-lang.modules/scala-java8-compat_2.12/0.8.0/index.html -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar#https://www.scala-lang.org/api/2.12.11/ -doc-external-doc:/home/johannes/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar#https://javadoc.io/page/com.typesafe/config/1.4.0/index.html
[error] 
[error]   last tree to typer: Ident(Tuple22$1)
[error]        tree position: line 304 of /tmp/akka-doc-test/akka/akka-actor/target/scala-2.12/src_managed/main/akka/japi/tuple/Tuples.scala
[error]             tree tpe: Tuple22$1.type
[error]               symbol: value Tuple22$1
[error]    symbol definition: val Tuple22$1: akka.japi.tuple.Tuple22[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22] (a TermSymbol)
[error]       symbol package: akka.japi.tuple
[error]        symbol owners: value Tuple22$1 -> method equals -> class Tuple22
[error]            call site: method equals in class Tuple22 in package tuple
[error] 
[error] == Source file context for tree position ==
[error] 
[error]    301  * Java API Tuple container.
[error]    302  */
[error]    303 @SerialVersionUID(1L)
[error]    304 final case class Tuple22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6, t7: T7, t8: T8, t9: T9, t10: T10, t11: T11, t12: T12, t13: T13, t14: T14, t15: T15, t16: T16, t17: T17, t18: T18, t19: T19, t20: T20, t21: T21, t22: T22) {
[error]    305    val toScala: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22) = (t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20, t21, t22)
[error]    306 }
[error]    307 
[error] Total time: 22 s, completed Mar 31, 2020, 11:07:57 AM
```

**Comment by raboof** [comment]
I'm also seeing it with other scala versions :/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-publish-nightly/1353/console

**Comment by jrudolph** [comment]
Can we close this now or should we wait for another run to succeed?

**Comment by raboof** [comment]
Let's close and reopen when it happens again (though I don't suspect it will, it worked for me locally)
