### ISSUE TITLE
Failed: akka.actor.typed.NormalActorContextSpec.An ActorContext must canonicalize behaviors

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28849]
https://jenkins.akka.io:8498/job/akka-publish-nightly/1351/consoleFull

```
sbt.ForkMain$ForkError: java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:386)
	at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:176)
	at scala.Option.getOrElse(Option.scala:189)
	at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:176)
	at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:169)
	at akka.actor.typed.ActorContextSpec.$anonfun$new$4(ActorContextSpec.scala:117)
```

**Comment by johanandren** [comment]
I think this is the race I fixed with #28886 (subscription not complete when the event asserting for happens)
