### ISSUE TITLE
Akka StreamRefs - IllegalStateException (Saw RemoteStreamCompleted while in state UpstreamTerminated)

### ISSUE THREAD

**Issue by Theseus93** [akka/akka#28852]
I'm trying to send stream of audio from service A to service B with the usage of akka stream refs (akka-streams library version: 2.6.3). Everything is working rather good, except for the fact that once in a month an exception (With daily usage of this service being around 50k calls per day or so) is thrown in the akka stream ref, and I can't find the cause of the problem.

The stacktrace for error is following:
```
        Caused by: java.lang.IllegalStateException: [SourceRef-46] Saw RemoteStreamCompleted(37) while in state UpstreamTerminated(Actor[akka://system-name@serviceA:34363/system/Materializers/StreamSupervisor-3/$$S4-SinkRef-3405#-939568637]), should never happen
        	at akka.stream.impl.streamref.SourceRefStageImpl$$anon$1.$anonfun$receiveRemoteMessage$1(SourceRefImpl.scala:285)
        	at akka.stream.impl.streamref.SourceRefStageImpl$$anon$1.$anonfun$receiveRemoteMessage$1$adapted(SourceRefImpl.scala:196)
        	at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:243)
        	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1(GraphStage.scala:202)
        	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1$adapted(GraphStage.scala:202)
        	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
        	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:497)
        	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
        	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
        	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
        	at akka.actor.Actor.aroundReceive(Actor.scala:534)
        	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
        	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
        	... 11 common frames omitted
```

The code responsible for pushing audio through SourceRef in service A:
```
Materializer materializer = Materializer.createMaterializer(actorSystem);
AudioExtractor extractor = new AudioExtractorImpl("/path/to/audio/file"); // gets all audio bytes from audio file and puts them into chunks (byte arrays of certain length)
List<AudioChunk> audioChunkList = extractor.getChunkedBytesIntoList();
SourceRef<AudioChunk> sourceRef = Source.from(audioChunkList)
      .runWith(StreamRefs.sourceRef(), materializer);
// wrap the sourceRef into msg
serviceBActor.tell(wrappedAudioSourceRefInMsg, getSelf());
```

Whereas code responsible for accepting audio in service B:
```
private final List<AudioChunk> audioChunksBuffer = new ArrayList<>();
private final Materializer materializer;

public Receive createReceive() {
      return receiveBuilder.match(WrappedAudioSourceRefInMsg.class, response -> {
            response.getSourceRef()
                  .getSource()
                  .runWith(Sink.forEach(chunk -> audioChunksBuffer.add(chunk)), materializer); 
      }).build();
} 
```

What I've confirmed is that this error always happens after all audio has been sent from service A, and the stream completed. I've tried to reproduce the issue in a test with 500k iteration loop, but had no success with it.

**Comment by johanandren** [comment]
Looks like a rare race condition when the stream on both nodes are terminating/stopping/ending at the same time. If you can come up with anything that repeats it or circumstances that makes it more likely to happen that would be useful.

**Comment by Theseus93** [comment]
I'm afraid I can't be of much more help here. The example code I've given is as close to the one we are using as I can give. As I said this situation is happening really, really seldom, so we resolved to catching the exception on consumer side and ignoring it if it's this one. Not clean, not perfect, but the only thing we were able to do. The good thing is that no data is lost as it happens only when stream is completed or is about to do so.

**Comment by thjaeckle** [comment]
We are facing the same issue in [eclipse/ditto](https://github.com/eclipse/ditto) while working on upgrading from Akka 2.5.29 to Akka 2.6.7:
When using a `SourceRef` and streaming results (150 entries are streamed), for the last element we get: 
```
2020-07-23 10:34:58,178 ERROR [] c.b.i.t.s.g.e.a.ThingsHttpRequestActor akka://ditto-cluster/user/$2e - Got <Status.Failure> when a command response was expected: <java.lang.IllegalStateException: [SourceRef-151] Saw RemoteStreamCompleted(150) while in state UpstreamTerminated(Actor[akka://ditto-cluster@127.0.0.1:2555/user/conciergeRoot/dispatcherActor/aggregator/StreamSupervisor-5/$$Ue-SinkRef-151#-378913480]), should never happen>!
...
2020-07-23 10:34:58,176 ERROR [459743fd-4091-456a-91fa-8ff6166275d0] o.e.d.s.u.a.ThingsAggregatorProxyActor akka://ditto-cluster/user/gatewayRoot/proxy/aggregatorProxy - [retrieve-thing-response] Upstream failed.
java.lang.IllegalStateException: [SourceRef-151] Saw RemoteStreamCompleted(150) while in state UpstreamTerminated(Actor[akka://ditto-cluster@127.0.0.1:2555/user/conciergeRoot/dispatcherActor/aggregator/StreamSupervisor-5/$$Ue-SinkRef-151#-378913480]), should never happen
	at akka.stream.impl.streamref.SourceRefStageImpl$$anon$1.$anonfun$receiveRemoteMessage$1(SourceRefImpl.scala:286)
	at akka.stream.impl.streamref.SourceRefStageImpl$$anon$1.$anonfun$receiveRemoteMessage$1$adapted(SourceRefImpl.scala:197)
	at akka.stream.impl.streamref.SourceRefStageImpl$$anon$1$$Lambda$2033/0000000000000000.apply(Unknown Source)
	at akka.stream.stage.GraphStageLogic$StageActor.internalReceive(GraphStage.scala:244)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1(GraphStage.scala:203)
	at akka.stream.stage.GraphStageLogic$StageActor.$anonfun$callback$1$adapted(GraphStage.scala:203)
	at akka.stream.stage.GraphStageLogic$StageActor$$Lambda$427/0000000000000000.apply(Unknown Source)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Our development branch is still on Akka 2.5.29 where this error did not occur:
https://github.com/eclipse/ditto/blob/8141313a5d057788ee71599d447e53a8f2dd52b3/services/concierge/starter/src/main/java/org/eclipse/ditto/services/concierge/starter/actors/ThingsAggregatorActor.java#L162

There the `SourceRef` was still wrapped in a `CompletionStage` and piped to the actor which shall consume the `SourceRef`.
The consuming actor handles it the same way as with Akka 2.5.29:
https://github.com/eclipse/ditto/blob/8141313a5d057788ee71599d447e53a8f2dd52b3/services/utils/aggregator/src/main/java/org/eclipse/ditto/services/utils/aggregator/ThingsAggregatorProxyActor.java#L194

Only difference is that we replaced the `ActorMaterializer` with a `Materializer` created with `Materializer.createMaterializer(this::getContext)`.

How can we find out what's the problem here our how could we help in fixing the `"should never happen"` error?

**Comment by johanandren** [comment]
The problem is likely related to two terminations happening roughly at the same time, one on the remote node and one upstream and in which order they arrive at the `SourceRefStageImpl`.

If you want to see if you can contribute a fix I think a good starting point would be to read on the state machine implemented in the internal actors that drive the streamref, and then see if you can make a test reproducing the crash (best case consistently, but since it likely is a race condition that will probably rather be a test that fails some percentage of the time).

The existing test coverage is in these two files

lower level unit test: 
https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-stream-tests/src/test/scala/akka/stream/scaladsl/StreamRefsSpec.scala

integration/end-to-end/multi-jvm: https://github.com/akka/akka/blob/0e4d41ad33dbeb00b598cb75b4d29899371bdc8c/akka-cluster/src/multi-jvm/scala/akka/cluster/StreamRefSpec.scala

I think the lower level test is probably the easiest place to reproduce as you can do a pretend remote side and have more control over ordering of things than having to "end up" with the inconsistency with the multi-jvm test.

**Comment by thjaeckle** [comment]
Here our DEBUG output from the `SourceRefStageImpl` right before the IllegalStateException:
```
14:55:13,785 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Starting up with, self ref: Actor[akka://ditto-cluster/user/gatewayRoot/proxy/aggregatorProxy/StreamSupervisor-4/$$xc-SourceRef-151#1310747818], state: AwaitingSubscription(Actor[akka://ditto-cluster@127.0.0.1:2555/user/conciergeRoot/dispatcherActor/aggregator/StreamSupervisor-5/$$Ue-SinkRef-151#-2145564190]), subscription timeout: 30.00 s
14:55:13,785 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding, before subscription seen, until [0] (+32)
14:55:13,809 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Received on subscribe handshake OnSubscribeHandshake(Actor[akka://ditto-cluster@127.0.0.1:2555/user/conciergeRoot/dispatcherActor/aggregator/StreamSupervisor-5/$$Ue-SinkRef-151#-2145564190]) while awaiting subscription from Actor[akka://ditto-cluster@127.0.0.1:2555/user/conciergeRoot/dispatcherActor/aggregator/StreamSupervisor-5/$$Ue-SinkRef-151#-2145564190]
14:55:14,193 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [32] (+17)
14:55:14,416 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [49] (+17)
14:55:14,513 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [66] (+17)
14:55:14,831 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [83] (+17)
14:55:15,132 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [100] (+17)
14:55:15,361 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [117] (+17)
14:55:15,493 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [134] (+17)
14:55:15,723 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Demanding until [151] (+17)
14:55:15,824 DEBUG a.s.i.s.SourceRefStageImpl - [SourceRef-151] Partner terminated, starting delayed shutdown, deadline: [2000 milliseconds]
14:55:15,830 DEBUG a.s.i.s.SourceRefStageImpl - [{}] Received element after partner terminated
```

And this is from the `SinkRefStageImpl`:
```
14:55:15,709 DEBUG a.s.i.s.SinkRefStageImpl - [SinkRef-151] Sending sequenced: SequencedOnNext(147,RetrieveThingResponse [...]) to Actor[akka://ditto-cluster@127.0.0.1:2562/user/gatewayRoot/proxy/aggregatorProxy/StreamSupervisor-4/$$xc-SourceRef-151#1310747818]
14:55:15,710 DEBUG o.e.d.s.c.s.a.ThingsAggregatorActor - [command-response] Element: RetrieveThingResponse [...]
14:55:15,710 DEBUG a.s.i.s.SinkRefStageImpl - [SinkRef-151] Sending sequenced: SequencedOnNext(148,RetrieveThingResponse [...]) to Actor[akka://ditto-cluster@127.0.0.1:2562/user/gatewayRoot/proxy/aggregatorProxy/StreamSupervisor-4/$$xc-SourceRef-151#1310747818]
14:55:15,718 DEBUG o.e.d.s.c.s.a.ThingsAggregatorActor - [command-response] Element: RetrieveThingResponse [...]
14:55:15,718 DEBUG a.s.i.s.SinkRefStageImpl - [SinkRef-151] Sending sequenced: SequencedOnNext(149,RetrieveThingResponse [...]) to Actor[akka://ditto-cluster@127.0.0.1:2562/user/gatewayRoot/proxy/aggregatorProxy/StreamSupervisor-4/$$xc-SourceRef-151#1310747818]
14:55:15,718 DEBUG o.e.d.s.c.s.a.ThingsAggregatorActor - [command-response] Upstream finished.
14:55:15,718 DEBUG a.s.i.s.SinkRefStageImpl - [SinkRef-151] Upstream finish, partnerRef [Some(Actor[akka://ditto-cluster@127.0.0.1:2562/user/gatewayRoot/proxy/aggregatorProxy/StreamSupervisor-4/$$xc-SourceRef-151#1310747818])]
14:55:15,729 DEBUG a.s.i.s.SinkRefStageImpl - [SinkRef-151] Received cumulative demand [CumulativeDemand(168)], consumable demand: [18]
```

But I guess that won't help ..

**Comment by johanandren** [comment]
It might, thanks. 

Nobody is actively looking into this right now, just to set the expectations.
