### ISSUE TITLE
akka-stream-perf-master job and akka-bench-jmh project broken

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#28889]
https://jenkins.akka.io:8498/job/akka-stream-perf-master/

`jmh:run` fails with

```
Annotation generator had thrown the exception.
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at java.lang.Class.getCanonicalName(Class.java:1399)
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getQualifiedName(RFClassInfo.java:67)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.buildAnnotatedSet(BenchmarkGenerator.java:206)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:75)
	at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
	at pl.project13.scala.sbt.JmhPlugin$.internalGenerateBenchmarkSourcesAndResources(JmhPlugin.scala:125)
	at pl.project13.scala.sbt.JmhPlugin$.$anonfun$generateBenchmarkSourcesAndResources$2(JmhPlugin.scala:108)
	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:146)
	at sbt.util.Difference.apply(Tracked.scala:323)
	at sbt.util.Difference.apply(Tracked.scala:303)
	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:142)
	at sbt.util.Difference.apply(Tracked.scala:323)
	at sbt.util.Difference.apply(Tracked.scala:298)
	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:141)
	at pl.project13.scala.sbt.JmhPlugin$.generateBenchmarkSourcesAndResources(JmhPlugin.scala:110)
	at pl.project13.scala.sbt.JmhPlugin$.$anonfun$projectSettings$13(JmhPlugin.scala:66)
```

**Comment by jrudolph** [comment]
Probably broken in b1346ad.

**Comment by patriknw** [comment]
@jrudolph I'll see if I can understand what is wrong. I have have run akka-bench-jmh with flight recorder, but maybe only with jdk11. That job is with 8.

**Comment by patriknw** [comment]
It works with jdk11. Can we change that job to jdk11?
I can try to find out what change that broke it for jdk8, but the quick fix should be to use 11.

**Comment by patriknw** [comment]
Problem was that nested objects doesn't work with getSimpleName in JDK 8. Well known Scala problem.

**Comment by jrudolph** [comment]
Great, thanks! Good to be able to benchmark on JDK 8 :)

**Comment by seglo** [comment]
This occurred again, but from a commit before #28892 was merged.  I've forced a build to see if it runs all the way through.

https://jenkins.akka.io:8498/job/akka-stream-perf-master/2221/console

**Comment by seglo** [comment]
Build 2222 has passed :tada: 

https://jenkins.akka.io:8498/job/akka-stream-perf-master/2222/
