### ISSUE TITLE
Failed - Rolling upgrade to 2.6.4

### ISSUE THREAD

**Issue by seglo** [akka/akka#28904]
https://travis-ci.com/github/akka/akka-upgrade-testing/builds/159082132#L1813

```
[info] - should upgrade to version 2.6.4 *** FAILED ***
[info]   akka-upgrade-testing-blue-5ff7d94866-k6j7m    0/1     ContainerCreating   0          0s
[info]   akka-upgrade-testing-blue-74545ddff5-grv7h    0/1     Terminating         0          86s
[info]   akka-upgrade-testing-green-74545ddff5-bs4g5   1/1     Running             0          33s
[info]   akka-upgrade-testing-green-74545ddff5-gtcnf   1/1     Running             0          103s
[info]   akka-upgrade-testing-green-74545ddff5-hmt9b   1/1     Running             0          86s Warnings and errors found on node akka-upgrade-testing-green-74545ddff5-gtcnf. All lines: 
[info]    [INFO] [04/07/2020 15:48:40.684] [main] [akka.remote.artery.tcp.ArteryTcpTransport(akka://default)] Remoting started with transport [Artery tcp]; listening on address [akka://default@172.17.0.6:2552] with UID [5838286581454214378]
[info]   [INFO] [04/07/2020 15:48:40.723] [main] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Starting up, Akka version [2.5-20200401-102402] ...
[info]   [INFO] [04/07/2020 15:48:40.916] [main] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Registered cluster JMX MBean [akka:type=Cluster]
[info]   [INFO] [04/07/2020 15:48:40.916] [main] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Started up successfully
[info]   [INFO] [04/07/2020 15:48:41.085] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/cluster-usage.html#joining-to-seed-nodes
[info]   [INFO] [04/07/2020 15:48:41.492] [main] [ClusterBootstrap(akka://default)] Bootstrap using `akka.discovery` method: kubernetes-api
[info]   [INFO] [04/07/2020 15:48:42.595] [main] [HealthChecksImpl(akka://default)] Loading readiness checks List(NamedHealthCheck(cluster-membership,akka.management.cluster.scaladsl.ClusterMembershipCheck))
[info]   [INFO] [04/07/2020 15:48:42.595] [main] [HealthChecksImpl(akka://default)] Loading liveness checks List()
[info]   [INFO] [04/07/2020 15:48:42.641] [main] [AkkaManagement(akka://default)] Binding Akka Management (HTTP) endpoint to: 172.17.0.6:8558
[info]   [INFO] [04/07/2020 15:48:42.730] [main] [AkkaManagement(akka://default)] Including HTTP management routes for ClusterHttpManagementRouteProvider
[info]   [INFO] [04/07/2020 15:48:42.850] [main] [AkkaManagement(akka://default)] Including HTTP management routes for ClusterBootstrap
[info]   [INFO] [04/07/2020 15:48:42.856] [main] [ClusterBootstrap(akka://default)] Using self contact point address: http://172.17.0.6:8558
[info]   [INFO] [04/07/2020 15:48:42.880] [main] [AkkaManagement(akka://default)] Including HTTP management routes for HealthCheckRoutes
[info]   [INFO] [04/07/2020 15:48:43.192] [default-akka.actor.default-dispatcher-3] [AkkaManagement(akka://default)] Bound Akka Management (HTTP) endpoint to: 172.17.0.6:8558
[info]   [INFO] [04/07/2020 15:48:43.193] [main] [ClusterBootstrap(akka://default)] Initiating bootstrap procedure using kubernetes-api method...
[info]   [INFO] [04/07/2020 15:48:43.232] [default-akka.actor.default-dispatcher-2] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Locating service members. Using discovery [akka.discovery.kubernetes.KubernetesApiServiceDiscovery], join decider [akka.management.cluster.bootstrap.LowestAddressJoinDecider]
[info]   [INFO] [04/07/2020 15:48:43.235] [default-akka.actor.default-dispatcher-2] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Looking up [Lookup(akka-upgrade-testing,None,Some(tcp))]
[info]   [INFO] [04/07/2020 15:48:43.236] [default-akka.actor.default-dispatcher-2] [KubernetesApiServiceDiscovery(akka://default)] Querying for pods with label selector: [app=akka-upgrade-testing]. Namespace: [default]. Port: [None]
[info]   [INFO] [04/07/2020 15:48:43.939] [default-akka.actor.default-dispatcher-3] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Located service members based on: [Lookup(akka-upgrade-testing,None,Some(tcp))]: [ResolvedTarget(172-17-0-10.default.pod.cluster.local,None,Some(/172.17.0.10)), ResolvedTarget(172-17-0-8.default.pod.cluster.local,None,Some(/172.17.0.8)), ResolvedTarget(172-17-0-5.default.pod.cluster.local,None,Some(/172.17.0.5)), ResolvedTarget(172-17-0-6.default.pod.cluster.local,None,Some(/172.17.0.6))], filtered to [ResolvedTarget(172-17-0-5.default.pod.cluster.local,None,Some(/172.17.0.5)), ResolvedTarget(172-17-0-6.default.pod.cluster.local,None,Some(/172.17.0.6)), ResolvedTarget(172-17-0-10.default.pod.cluster.local,None,Some(/172.17.0.10)), ResolvedTarget(172-17-0-8.default.pod.cluster.local,None,Some(/172.17.0.8))]
[info]   [INFO] [04/07/2020 15:48:44.147] [default-akka.actor.default-dispatcher-9] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Contact point [akka://default@172.17.0.10:2552] returned [3] seed-nodes [akka://default@172.17.0.10:2552, akka://default@172.17.0.5:2552, akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:48:44.171] [default-akka.actor.default-dispatcher-9] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Contact point [akka://default@172.17.0.5:2552] returned [3] seed-nodes [akka://default@172.17.0.10:2552, akka://default@172.17.0.5:2552, akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:48:44.171] [default-akka.actor.default-dispatcher-9] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Contact point [akka://default@172.17.0.8:2552] returned [3] seed-nodes [akka://default@172.17.0.10:2552, akka://default@172.17.0.5:2552, akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:48:44.173] [default-akka.actor.default-dispatcher-9] [akka://default@172.17.0.6:2552/system/bootstrapCoordinator] Joining [akka://default@172.17.0.6:2552] to existing cluster [akka://default@172.17.0.10:2552, akka://default@172.17.0.5:2552, akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:48:44.179] [default-akka.actor.default-dispatcher-20] [akka://default/deadLetters] Message [akka.management.cluster.bootstrap.internal.BootstrapCoordinator$Protocol$BootstrappingCompleted$] from Actor[akka://default/system/bootstrapCoordinator#-911161263] to Actor[akka://default/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info]   [INFO] [04/07/2020 15:48:44.421] [default-akka.actor.default-dispatcher-10] [HttpClusterBootstrapRoutes(akka://default)] Bootstrap request from 172.17.0.6:48604: Contact Point returning 0 seed-nodes ([TreeSet()])
[info]   [INFO] [04/07/2020 15:48:44.702] [default-akka.actor.default-dispatcher-10] [akka://default/system/bootstrapCoordinator/contactPointProbe-172-17-0-6.default.pod.cluster.local-8558] Message [akka.actor.Status$Failure] from Actor[akka://default/system/bootstrapCoordinator/contactPointProbe-172-17-0-6.default.pod.cluster.local-8558#-753819722] to Actor[akka://default/system/bootstrapCoordinator/contactPointProbe-172-17-0-6.default.pod.cluster.local-8558#-753819722] was not delivered. [2] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/system/bootstrapCoordinator/contactPointProbe-172-17-0-6.default.pod.cluster.local-8558#-753819722]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info]   [INFO] [04/07/2020 15:48:45.098] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Received InitJoinAck message from [Actor[akka://default@172.17.0.8:2552/system/cluster/core/daemon#1362047888]] to [akka://default@172.17.0.6:2552]
[info]   [INFO] [04/07/2020 15:48:45.159] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Welcome from [akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:48:56.361] [default-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Exiting confirmed [akka://default@172.17.0.5:2552]
[info]   [INFO] [04/07/2020 15:48:57.469] [default-akka.remote.default-remote-dispatcher-6] [akka.remote.artery.Association(akka://default)] Association to [akka://default@172.17.0.5:2552] having UID [1693346669616295778] has been stopped. All messages to this UID will be delivered to dead letters. Reason: ActorSystem terminated
[info]   [WARN] [04/07/2020 15:49:00.539] [default-akka.remote.default-remote-dispatcher-8] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.5:2552], control stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [WARN] [04/07/2020 15:49:00.557] [default-akka.remote.default-remote-dispatcher-6] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.5:2552], message stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [INFO] [04/07/2020 15:49:05.816] [default-akka.actor.default-dispatcher-9] [HttpClusterBootstrapRoutes(akka://default)] Bootstrap request from 172.17.0.7:37210: Contact Point returning 3 seed-nodes ([TreeSet(ClusterMember(akka://default@172.17.0.10:2552,-7671132210440356556,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.6:2552,5838286581454214378,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.8:2552,3900555790206885553,Up,Set(dc-default)))])
[info]   [INFO] [04/07/2020 15:49:06.539] [default-akka.actor.default-dispatcher-20] [HttpClusterBootstrapRoutes(akka://default)] Bootstrap request from 172.17.0.9:38122: Contact Point returning 3 seed-nodes ([TreeSet(ClusterMember(akka://default@172.17.0.10:2552,-7671132210440356556,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.6:2552,5838286581454214378,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.8:2552,3900555790206885553,Up,Set(dc-default)))])
[info]   [INFO] [04/07/2020 15:49:06.563] [default-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Received InitJoin message from [Actor[akka://default@172.17.0.7:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-731311419]] to [akka://default@172.17.0.6:2552]
[info]   [INFO] [04/07/2020 15:49:06.563] [default-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Sending InitJoinAck message from node [akka://default@172.17.0.6:2552] to [Actor[akka://default@172.17.0.7:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-731311419]] (version [2.5-20200401-102402])
[info]   [INFO] [04/07/2020 15:49:07.149] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Node [akka://default@172.17.0.7:2552] is JOINING, roles [dc-default]
[info]   [INFO] [04/07/2020 15:49:07.773] [default-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Received InitJoin message from [Actor[akka://default@172.17.0.9:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#1192606746]] to [akka://default@172.17.0.6:2552]
[info]   [INFO] [04/07/2020 15:49:07.773] [default-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Sending InitJoinAck message from node [akka://default@172.17.0.6:2552] to [Actor[akka://default@172.17.0.9:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#1192606746]] (version [2.5-20200401-102402])
[info]   [INFO] [04/07/2020 15:49:13.848] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->https://10.96.0.1:443)] Pool shutting down because akka.http.host-connection-pool.idle-timeout triggered after 30 seconds.
[info]   [INFO] [04/07/2020 15:49:13.849] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->https://10.96.0.1:443)] Pool is now shutting down as requested.
[info]   [ERROR] [04/07/2020 15:49:13.857] [default-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anon$2: Pool slot was shut down)
[info]   [INFO] [04/07/2020 15:49:14.149] [default-akka.actor.default-dispatcher-3] [default/Pool(shared->http://172-17-0-5.default.pod.cluster.local:8558)] Pool shutting down because akka.http.host-connection-pool.idle-timeout triggered after 30 seconds.
[info]   [INFO] [04/07/2020 15:49:14.156] [default-akka.actor.default-dispatcher-3] [default/Pool(shared->http://172-17-0-5.default.pod.cluster.local:8558)] Pool is now shutting down as requested.
[info]   [INFO] [04/07/2020 15:49:14.158] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->http://172-17-0-10.default.pod.cluster.local:8558)] Pool shutting down because akka.http.host-connection-pool.idle-timeout triggered after 30 seconds.
[info]   [INFO] [04/07/2020 15:49:14.159] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->http://172-17-0-10.default.pod.cluster.local:8558)] Pool is now shutting down as requested.
[info]   [ERROR] [04/07/2020 15:49:14.160] [default-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anon$2: Pool slot was shut down)
[info]   [INFO] [04/07/2020 15:49:14.180] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->http://172-17-0-8.default.pod.cluster.local:8558)] Pool shutting down because akka.http.host-connection-pool.idle-timeout triggered after 30 seconds.
[info]   [INFO] [04/07/2020 15:49:14.180] [default-akka.actor.default-dispatcher-9] [default/Pool(shared->http://172-17-0-8.default.pod.cluster.local:8558)] Pool is now shutting down as requested.
[info]   [ERROR] [04/07/2020 15:49:14.183] [default-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anon$2: Pool slot was shut down)
[info]   [INFO] [04/07/2020 15:49:14.713] [default-akka.actor.default-dispatcher-4] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Exiting confirmed [akka://default@172.17.0.10:2552]
[info]   [INFO] [04/07/2020 15:49:14.720] [default-akka.actor.default-dispatcher-4] [default/Pool(shared->http://172-17-0-6.default.pod.cluster.local:8558)] Pool shutting down because akka.http.host-connection-pool.idle-timeout triggered after 30 seconds.
[info]   [INFO] [04/07/2020 15:49:14.720] [default-akka.actor.default-dispatcher-4] [default/Pool(shared->http://172-17-0-6.default.pod.cluster.local:8558)] Pool is now shutting down as requested.
[info]   [ERROR] [04/07/2020 15:49:14.720] [default-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anon$2: Pool slot was shut down)
[info]   [INFO] [04/07/2020 15:49:15.080] [default-akka.actor.default-dispatcher-9] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - is the new leader among reachable nodes (more leaders may exist)
[info]   [INFO] [04/07/2020 15:49:15.807] [default-akka.remote.default-remote-dispatcher-8] [akka.remote.artery.Association(akka://default)] Association to [akka://default@172.17.0.10:2552] having UID [-7671132210440356556] has been stopped. All messages to this UID will be delivered to dead letters. Reason: ActorSystem terminated
[info]   [INFO] [04/07/2020 15:49:16.136] [default-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Leader is removing confirmed Exiting node [akka://default@172.17.0.10:2552]
[info]   [WARN] [04/07/2020 15:49:18.828] [default-akka.remote.default-remote-dispatcher-8] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.10:2552], control stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [WARN] [04/07/2020 15:49:18.829] [default-akka.remote.default-remote-dispatcher-8] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.10:2552], message stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [INFO] [04/07/2020 15:49:20.330] [default-akka.actor.default-dispatcher-9] [HttpClusterBootstrapRoutes(akka://default)] Bootstrap request from 172.17.0.5:33970: Contact Point returning 4 seed-nodes ([TreeSet(ClusterMember(akka://default@172.17.0.6:2552,5838286581454214378,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.7:2552,-8536693591177213541,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.8:2552,3900555790206885553,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.9:2552,5103752981692354101,Up,Set(dc-default)))])
[info]   [INFO] [04/07/2020 15:49:20.971] [default-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Received InitJoin message from [Actor[akka://default@172.17.0.5:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#24052524]] to [akka://default@172.17.0.6:2552]
[info]   [INFO] [04/07/2020 15:49:20.972] [default-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Sending InitJoinAck message from node [akka://default@172.17.0.6:2552] to [Actor[akka://default@172.17.0.5:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#24052524]] (version [2.5-20200401-102402])
[info]   [INFO] [04/07/2020 15:49:21.450] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Node [akka://default@172.17.0.5:2552] is JOINING, roles [dc-default]
[info]   [INFO] [04/07/2020 15:49:23.090] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Leader is moving node [akka://default@172.17.0.5:2552] to [Up]
[info]   [INFO] [04/07/2020 15:49:24.088] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - is no longer leader
[info]   [INFO] [04/07/2020 15:49:33.576] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Exiting confirmed [akka://default@172.17.0.8:2552]
[info]   [INFO] [04/07/2020 15:49:34.627] [default-akka.remote.default-remote-dispatcher-6] [akka.remote.artery.Association(akka://default)] Association to [akka://default@172.17.0.8:2552] having UID [3900555790206885553] has been stopped. All messages to this UID will be delivered to dead letters. Reason: ActorSystem terminated
[info]   [INFO] [04/07/2020 15:49:39.278] [default-akka.actor.default-dispatcher-4] [akka://default/deadLetters] Message [akka.cluster.ClusterHeartbeatSender$Heartbeat] from Actor[akka://default/system/cluster/core/daemon/heartbeatSender#886470426] to Actor[akka://default/deadLetters] was not delivered. [3] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info]   [WARN] [04/07/2020 15:49:39.280] [default-akka.remote.default-remote-dispatcher-8] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.8:2552], control stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [INFO] [04/07/2020 15:49:39.280] [default-akka.actor.default-dispatcher-4] [akka://default/deadLetters] Message [akka.cluster.GossipStatus] from Actor[akka://default/system/cluster/core/daemon#-1596245303] to Actor[akka://default/deadLetters] was not delivered. [4] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/deadLetters]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info]   [WARN] [04/07/2020 15:49:39.280] [default-akka.remote.default-remote-dispatcher-6] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.8:2552], message stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   15:49:41.351 [default-akka.actor.default-dispatcher-19] INFO CollectVersions - Collecting versions for members: TreeSet(Member(address = akka://default@172.17.0.5:2552, status = Up), Member(address = akka://default@172.17.0.6:2552, status = Up), Member(address = akka://default@172.17.0.7:2552, status = Up), Member(address = akka://default@172.17.0.9:2552, status = Up))
[info]   [INFO] [04/07/2020 15:49:48.603] [default-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Exiting confirmed [akka://default@172.17.0.5:2552]
[info]   [INFO] [04/07/2020 15:49:49.084] [default-akka.actor.default-dispatcher-10] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - is the new leader among reachable nodes (more leaders may exist)
[info]   [INFO] [04/07/2020 15:49:49.679] [default-akka.remote.default-remote-dispatcher-6] [akka.remote.artery.Association(akka://default)] Association to [akka://default@172.17.0.5:2552] having UID [5714349980311980395] has been stopped. All messages to this UID will be delivered to dead letters. Reason: ActorSystem terminated
[info]   [INFO] [04/07/2020 15:49:50.089] [default-akka.actor.default-dispatcher-9] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Leader is removing confirmed Exiting node [akka://default@172.17.0.5:2552]
[info]   [WARN] [04/07/2020 15:49:52.698] [default-akka.remote.default-remote-dispatcher-6] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.5:2552], control stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [WARN] [04/07/2020 15:49:52.703] [default-akka.remote.default-remote-dispatcher-6] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [outbound connection to [akka://default@172.17.0.5:2552], message stream] Upstream failed, cause: Association$OutboundStreamStopQuarantinedSignal$: 
[info]   [INFO] [04/07/2020 15:49:54.061] [default-akka.actor.default-dispatcher-19] [HttpClusterBootstrapRoutes(akka://default)] Bootstrap request from 172.17.0.8:51984: Contact Point returning 3 seed-nodes ([TreeSet(ClusterMember(akka://default@172.17.0.6:2552,5838286581454214378,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.7:2552,-8536693591177213541,Up,Set(dc-default)), ClusterMember(akka://default@172.17.0.9:2552,5103752981692354101,Up,Set(dc-default)))])
[info]   [INFO] [04/07/2020 15:49:54.603] [default-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Received InitJoin message from [Actor[akka://default@172.17.0.8:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-1447097928]] to [akka://default@172.17.0.6:2552]
[info]   [INFO] [04/07/2020 15:49:54.603] [default-akka.actor.default-dispatcher-5] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Sending InitJoinAck message from node [akka://default@172.17.0.6:2552] to [Actor[akka://default@172.17.0.8:2552/system/cluster/core/daemon/joinSeedNodeProcess-1#-1447097928]] (version [2.5-20200401-102402])
[info]   [INFO] [04/07/2020 15:49:56.079] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Leader is moving node [akka://default@172.17.0.8:2552] to [Up]
[info]   15:50:08.204 [default-akka.actor.default-dispatcher-4] INFO CollectVersions - Collecting versions for members: TreeSet(Member(address = akka://default@172.17.0.6:2552, status = Up), Member(address = akka://default@172.17.0.7:2552, status = Up), Member(address = akka://default@172.17.0.8:2552, status = Up), Member(address = akka://default@172.17.0.9:2552, status = Up))
[info]   [INFO] [04/07/2020 15:50:14.091] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Leader is moving node [akka://default@172.17.0.7:2552] to [Exiting]
[info]   [INFO] [04/07/2020 15:50:14.167] [default-akka.actor.default-dispatcher-20] [akka.cluster.Cluster(akka://default)] Cluster Node [akka://default@172.17.0.6:2552] - Exiting confirmed [akka://default@172.17.0.7:2552]
[info]   15:50:14.221 [default-akka.actor.default-dispatcher-9] INFO CollectVersions - Collecting versions for members: TreeSet(Member(address = akka://default@172.17.0.6:2552, status = Up), Member(address = akka://default@172.17.0.7:2552, status = Exiting), Member(address = akka://default@172.17.0.8:2552, status = Up), Member(address = akka://default@172.17.0.9:2552, status = Up))
[info]   [ERROR] [04/07/2020 15:50:14.237] [default-akka.actor.default-dispatcher-9] [akka.actor.ActorSystemImpl(default)] Error during processing of request: 'Actor not found for: ActorSelection[Anchor(akka://default@172.17.0.7:2552/), Path(/user/version)]'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
[info]   akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka://default@172.17.0.7:2552/), Path(/user/version)]
[info]   	at akka.actor.ActorSelection.$anonfun$resolveOne$1(ActorSelection.scala:75)
[info]   	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
[info]   	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[info]   	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:73)
[info]   	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:100)
[info]   	at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:122)
[info]   	at akka.dispatch.BatchingExecutor.execute$(BatchingExecutor.scala:116)
[info]   	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:99)
[info]   	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
[info]   	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:299)
[info]   	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
[info]   	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
[info]   	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:581)
[info]   	at akka.remote.artery.MessageDispatcher.dispatch(MessageDispatcher.scala:83)
[info]   	at akka.remote.artery.ArteryTransport.$anonfun$messageDispatcherSink$1(ArteryTransport.scala:912)
[info]   	at akka.remote.artery.ArteryTransport.$anonfun$messageDispatcherSink$1$adapted(ArteryTransport.scala:911)
[info]   	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:54)
[info]   	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
[info]   	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
[info]   	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
[info]   	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
[info]   	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
[info]   	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
[info]   	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
[info]   	at akka.actor.Actor.aroundReceive(Actor.scala:539)
[info]   	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
[info]   	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
[info]   	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
[info]   	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
[info]   	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
[info]   	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
[info]   	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
[info]   	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment]
Hmmm, 172.17.0.7:2552 is Exiting one the line before the failure to look up an actor on it

**Comment by chbatey** [comment]
This used to use ActorSelection on all nodes and picked up one that was existing from a previous rolling deploy, it now uses the receptionist so closing
