### ISSUE TITLE
RejectedExecutionException in multi-jvm tests

### ISSUE THREAD

**Issue by patriknw** [akka/akka#28906]
Not critical, but annoying. We tried to fix it in https://github.com/akka/akka/pull/28692 and https://github.com/akka/akka/pull/28896, but those attempts don't work.

```
[error] [JVM-3] java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
[error] [JVM-2] 	at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
[error] [JVM-3] 	at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
[error] [JVM-2] 	at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
[error] [JVM-3] 	at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
[error] [JVM-2] 	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
[error] [JVM-3] 	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
[error] [JVM-2] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-3] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[error] [JVM-2] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-3] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
[error] [JVM-2] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-3] 	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
[error] [JVM-2] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
[error] [JVM-3] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
[error] [JVM-2] 	at org.jboss.netty.channel.Channels.close(Channels.java:812)
[error] [JVM-2] 	at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:205)
[error] [JVM-3] 	at org.jboss.netty.channel.Channels.close(Channels.java:812)
[error] [JVM-2] 	at akka.remote.testconductor.ClientFSM$$anonfun$5.applyOrElse(Player.scala:309)
```

I don't think that exception is throw out from the Player. Maybe it's logged by the Executor?

**Comment by patriknw** [comment]
I'll see if we can reduce the risk by guard with `if (channel.isOpen)`

**Comment by patriknw** [comment]
> I'll see if we can reduce the risk by guard with if (channel.isOpen)

nope, doesn't help
