### ISSUE TITLE
Failed: akka-nightly-jdk8 Jenkins build occasionally times out after 150 min

### ISSUE THREAD

**Issue by seglo** [akka/akka#28910]
The build status appears as "Aborted".

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7540//consoleFull

```
Build timed out (after 150 minutes). Marking the build as failed.
FATAL: command execution failed: null
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.Channel.call(Channel.java:997)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
	at com.sun.proxy.$Proxy96.join(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1133)
	at hudson.Launcher$ProcStarter.join(Launcher.java:469)
	at org.jvnet.hudson.plugins.SbtPluginBuilder.perform(SbtPluginBuilder.java:127)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1856)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Build using sbt' changed build result to ABORTED
Build step 'Build using sbt' marked build as failure
[Current build status] check if current [ABORTED] is worse or equals then [FAILURE] and better or equals then [FAILURE]
Recording test results
Email was triggered for: Aborted
Sending email for trigger: Aborted
Sending email to: akka.official@gmail.com
Finished: ABORTED
```

**Comment by johanandren** [comment]
There's a jenkins build timeout (now 180 minutes so I guess someone touched it), those logs are not available anymore though, so let's close this and re-open if it happens again
