### ISSUE TITLE
ClusterMetricsDisabled: must not collect metrics, not publish metrics events, and not gossip metrics

### ISSUE THREAD

**Issue by raboof** [akka/akka#28968]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/512/consoleFull
```
[info] [JVM-1] - must not collect metrics, not publish metrics events, and not gossip metrics (on node 'node-1', class akka.cluster.metrics.ClusterMetricsDisabledMultiJvmNode1) *** FAILED *** (25 seconds, 163 milliseconds)
[info] [JVM-1]   4 did not equal 5 (MultiNodeClusterSpec.scala:309)
[info] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-1]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info] [JVM-1]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$5(MultiNodeClusterSpec.scala:309)
[info] [JVM-1]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:328)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:345)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:317)
[info] [JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:967)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$1(MultiNodeClusterSpec.scala:309)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:414)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:402)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:967)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:429)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:429)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:967)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.awaitMembersUp(MultiNodeClusterSpec.scala:306)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.awaitMembersUp$(MultiNodeClusterSpec.scala:302)
[info] [JVM-1]   at akka.cluster.metrics.ClusterMetricsDisabledSpec.awaitMembersUp(ClusterMetricsExtensionSpec.scala:139)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.awaitClusterUp(MultiNodeClusterSpec.scala:224)
[info] [JVM-1]   at akka.cluster.MultiNodeClusterSpec.awaitClusterUp$(MultiNodeClusterSpec.scala:214)
[info] [JVM-1]   at akka.cluster.metrics.ClusterMetricsDisabledSpec.awaitClusterUp(ClusterMetricsExtensionSpec.scala:139)
[info] [JVM-1]   at akka.cluster.metrics.ClusterMetricsDisabledSpec.$anonfun$new$15(ClusterMetricsExtensionSpec.scala:148)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7596

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7597/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7598/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-sigar/1666/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7737/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7738/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2331/console
