### ISSUE TITLE
Failed: MessageAdapterSpec: log wrapped message of DeadLetter

### ISSUE THREAD

**Issue by seglo** [akka/akka#29044]
```
<-- [akka.actor.typed.scaladsl.MessageAdapterSpec: log wrapped message of DeadLetter] End of log messages of test that [Failed(java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),None,None,None,Some(Pong.*wrapped in.*AdaptMessage.*dead letters encountered),None,Map(),None).)]
[info] - log wrapped message of DeadLetter *** FAILED *** (3 seconds, 17 milliseconds)
[info]   java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),None,None,None,Some(Pong.*wrapped in.*AdaptMessage.*dead letters encountered),None,Map(),None).
[info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:101)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.$anonfun$new$34(MessageAdapterSpec.scala:293)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:54)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:52)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.withFixture(MessageAdapterSpec.scala:35)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.runTest(MessageAdapterSpec.scala:35)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.runTests(MessageAdapterSpec.scala:35)
[info]   at org.scalatest.Suite.run(Suite.scala:1112)
[info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:31)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(MessageAdapterSpec.scala:35)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[info]   at akka.actor.typed.scaladsl.MessageAdapterSpec.run(MessageAdapterSpec.scala:35)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

https://jenkins.akka.io:8498/job/akka-multi-node/4045/consoleFull

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4045/consoleFull

**Comment by patriknw** [comment]
The reason for why this started failing is probably the change of the `FunctionRef` in #29026 
I'll take a look at the test.
