### ISSUE TITLE
Failed: PersistentClusterShardingFailure

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29062]
On the remembered entities feature branch

https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19822/consoleFull

```
[05-11 14:53:37.613] [info] - must recover on graceful entity stop when storing a stop event fails NoResponse *** FAILED *** (6 seconds, 410 milliseconds)
[05-11 14:53:37.614] [info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for hello-2
[05-11 14:53:37.651] [info]   at scala.Predef$.assert(Predef.scala:223)
[05-11 14:53:37.651] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:457)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:434)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:434)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:967)
[05-11 14:53:37.652] [info]   at akka.cluster.sharding.RememberEntitiesFailureSpec.$anonfun$new$10(RememberEntitiesFailureSpec.scala:338)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:328)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:345)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:317)
[05-11 14:53:37.652] [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:967)
[05-11 14:53:37.652] [info]   at akka.cluster.sharding.RememberEntitiesFailureSpec.$anonfun$new$9(RememberEntitiesFailureSpec.scala:336)
[05-11 14:53:37.652] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[05-11 14:53:37.652] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[05-11 14:53:37.652] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly-remember-entities/3/consoleFull

**Comment by johanandren** [comment]
I think that this was fixed. Closing for now.
