### ISSUE TITLE
Failed: akka.io.TcpListenerSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29115]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19918/testReport/junit/akka.io/TcpListenerSpec/A_TcpListener_must_continue_to_accept_connections_after_a_previous_accept/

```
assertion failed: timeout (3 seconds) during expectMsg: 
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:477)
	at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:474)
	at akka.testkit.TestKit.expectMsgPF(TestKit.scala:969)
	at akka.io.TcpListenerSpec$TestSetup.expectWorkerForCommand(TcpListenerSpec.scala:170)
	at akka.io.TcpListenerSpec$$anon$4.<init>(TcpListenerSpec.scala:70)
	at akka.io.TcpListenerSpec.$anonfun$new$5(TcpListenerSpec.scala:59)
```

**Comment by patriknw** [comment]
Closing as old
