### ISSUE TITLE
Failed: akka.cluster.sharding.DDataClusterShardingFailure

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29120]
On the feature-remember-entities-rework branch.

https://jenkins.akka.io:8498/job/akka-multi-node-nightly-remember-entities/29/consoleText

```
 must recover after journal/network failure (on node 'first', class akka.cluster.sharding.DDataClusterShardingFailureMultiJvmNode2) *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  java.lang.AssertionError: assertion failed: timeout (18737247611 nanoseconds) during expectMsg while waiting for Value(30,3)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at scala.Predef$.assert(Predef.scala:223)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:457)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:434)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:434)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:967)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.ClusterShardingFailureSpec.$anonfun$new$10(ClusterShardingFailureSpec.scala:203)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:384)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.ClusterShardingFailureSpec.$anonfun$new$6(ClusterShardingFailureSpec.scala:171)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.testkit.TestKitBase.within(TestKit.scala:414)[0m[0m
```

**Comment by seglo** [comment]
Getting the same timeout with this test.

```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m- must recover after leaving coordinator node (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode5) *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at scala.Predef$.assert(Predef.scala:282)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:166)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at scala.collection.immutable.HashMap.foreach(HashMap.scala:1076)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$21(ClusterShardingLeavingSpec.scala:162)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-5[0m] [31m  ...[0m[0m
```

https://jenkins.akka.io:8498/job/akka-nightly-2.13/657/consoleText

**Comment by patriknw** [comment]
Closing as old
