### ISSUE TITLE
Failed: akka.pattern.BackoffSupervisorSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29132]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/19937/testReport/junit/akka.pattern/BackoffSupervisorSpec/BackoffSupervisor_must_supervisor_must_not_stop_when_final_stop_message_has_not_been_received/

```
timeout (3 seconds) waiting for 1 messages on WarningFilter(None,Right(.*(ping|stop).*),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
	at akka.pattern.BackoffSupervisorSpec.$anonfun$new$40(BackoffSupervisorSpec.scala:384)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
```

**Comment by chbatey** [comment]
I think this is just on the remember entities branch

**Comment by johanandren** [comment]
I see, there is a log difference with master, debug vs warning so perhaps this goes away after the merge of master.

**Comment by johanandren** [comment]
Didn't happen after merge from master, so let's close
