### ISSUE TITLE
Sharding should not allocate to terminated regions (failed RandomizedSplitBrainResolverIntegrationSpec)

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29131]
https://jenkins.akka.io:8498/job/akka-multi-node/4073

Failure in RandomizedSplitBrainResolverIntegrationSpec with random seed: 1590493980980

```
[info] [JVM-1] - must Scenario(lease-majority, 5) (on node 'node1', class akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpecMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 6
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:445)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:445)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$2(RandomizedBrainResolverIntegrationSpec.scala:247)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$2$adapted(RandomizedBrainResolverIntegrationSpec.scala:244)
[info] [JVM-1]   at scala.collection.immutable.Range.foreach(Range.scala:158)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$1(RandomizedBrainResolverIntegrationSpec.scala:244)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
```

**Comment by patriknw** [comment]
I could reproduce it locally with same random seed, with debug log level.
[issue-29131.log.zip](https://github.com/akka/akka/files/4682997/issue-29131.log.zip)

but my brain is fried for today

**Comment by patriknw** [comment]
I have found the reason. SBR is doing the right thing. It's a bug in sharding. It's also because of that we disable watch outside the cluster, which is fixed in https://github.com/akka/akka/pull/29092

It may be triggered by having a non-zero removal margin, which we have when SBR is enabled.

I'll open a PR improving one more thing than the watch outside cluster. We shouldn't allocate to regions that are in the `regionTerminationInProgress`.

In the end of the test there is only one node 55948 remaining, but shard 9 is allocated to the removed 55949. Extract from the logs:

```
>>> member removed
[info] [JVM-1] [INFO] [05/26/2020 16:31:56.086] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-11] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator] Member removed [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949]

>>> region 55949 terminated
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:56.087] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-12] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2] Entity-2: Region [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]] with shards [1, 6] terminated

>>>
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:56.087] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-12] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/remote-watcher] Watchee terminated: [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2]

>>> shard 9 allocated to 55949
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.057] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-14] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator/singleton/coordinator] The coordinator state was successfully updated with ShardHomeAllocated(9,Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183])

>>> GetShardHome requests ignored while regionTerminationInProgress
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:07.865] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-13] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator/singleton/coordinator] GetShardHome [9] request ignored, due to region [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]] termination in progress.
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:07.865] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-35] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/replicator/$z] WriteMajorityPlus [Entity-2CoordinatorState] [1] of [1].

>>>
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.058] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-14] [Association(akka://RandomizedSplitBrainResolverIntegrationSpec-2)] Dropping message [akka.cluster.sharding.ShardCoordinator$Internal$HostShard] from [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2Coordinator/singleton/coordinator#-557855592]] to [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]] due to quarantined system [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949]

>>>
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.058] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-29] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2] Entity-2: Shard [9] located at [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]]

[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.058] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-14] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator/singleton/coordinator] New coordinator state after [ShardHomeAllocated(9,Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183])]: [State(Map(8 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55955/system/sharding/Entity-2#-779669514], 4 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 9 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183], 5 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 6 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183], 1 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183], 0 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 2 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55951/system/sharding/Entity-2#-669270734], 7 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55951/system/sharding/Entity-2#-669270734], 3 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55955/system/sharding/Entity-2#-779669514]))]


>>>
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.058] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-5] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/remote-watcher] Watching: [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969] -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]]

>>> watch outside cluster disabled, watch is from the region actor
[info] [JVM-1] [DEBUG] [05/26/2020 16:31:59.058] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-5] [akka.cluster.ClusterActorRefProvider] Dropped remote Watch: disabled for [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183] -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969]]

>>> ShardRegionTerminated 55949, after the DelayedShardRegionTerminated, so it's removed from the coordinator state
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:07.866] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-13] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator/singleton/coordinator] The coordinator state was successfully updated with ShardRegionTerminated(Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183])
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:07.866] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.default-dispatcher-13] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2Coordinator/singleton/coordinator] New coordinator state after [ShardRegionTerminated(Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183])]: [State(Map(8 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55955/system/sharding/Entity-2#-779669514], 4 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 5 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 0 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/sharding/Entity-2#-958202969], 2 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55951/system/sharding/Entity-2#-669270734], 7 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55951/system/sharding/Entity-2#-669270734], 3 -> Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55955/system/sharding/Entity-2#-779669514]))]


>>> but the region doesn't know, because the watch was disabled outside cluster. Continues forwarding for shard 9 to 55949
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:09.167] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-30] [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55948/system/sharding/Entity-2] Entity-2: Forwarding message for shard [9] to [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]]
[info] [JVM-1] [DEBUG] [05/26/2020 16:32:09.167] [RandomizedSplitBrainResolverIntegrationSpec-2-akka.actor.internal-dispatcher-30] [Association(akka://RandomizedSplitBrainResolverIntegrationSpec-2)] Dropping message [java.lang.Integer] from [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2/system/testProbe-10#84709150]] to [Actor[akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949/system/sharding/Entity-2#-203630183]] due to quarantined system [akka://RandomizedSplitBrainResolverIntegrationSpec-2@localhost:55949]
```
