### ISSUE TITLE
Failed: ClusterShardingLeaseSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29167]
During PR validation on Remember Entities feature branch
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/20018/consoleText

```
--> [[34mCluster sharding with lease should not start until lease is acquired[0m] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1)]
| [DEBUG] [06/02/2020 17:05:16.610] [pool-1-thread-1-ScalaTest-running-DDataClusterShardingLeaseSpec] [WithLogCapturing(akka://ClusterShardingLeaseSpec)] Logging started for test [Cluster sharding with lease should not start until lease is acquired]
| [DEBUG] [06/02/2020 17:05:16.610] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Request shard [1] home. Coordinator [None]
| [INFO] [akkaClusterSingletonStarted][06/02/2020 17:05:16.610] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator] Singleton manager starting singleton actor [akka://ClusterShardingLeaseSpec/system/sharding/echoCoordinator/singleton]
| [INFO] [06/02/2020 17:05:16.611] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator] ClusterSingletonManager state change [Start -> Oldest]
| [DEBUG] [06/02/2020 17:05:16.611] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Starting remember entities store from provider akka.cluster.sharding.internal.DDataRememberEntitiesProvider@16d80314
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-all].
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [echoCoordinatorState].
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Received [0] remembered shard ids (when waitingForInitialState)
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [TimerScheduler(akka://ClusterShardingLeaseSpec)] Cancel timer [RememberEntityTimeout] with generation [1]
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator/$a] ReadMajorityPlus [echoCoordinatorState] [1] of [1].
| [DEBUG] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-7] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Initial coordinator unknown using empty state
| [INFO] [06/02/2020 17:05:16.612] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-7] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] ShardCoordinator was moved to the active state State(Map())
| [DEBUG] [06/02/2020 17:05:16.871] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] ShardRegion registered: [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]]
| [DEBUG] [06/02/2020 17:05:16.871] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Storing new coordinator state [State(Map())]
| [DEBUG] [06/02/2020 17:05:16.872] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Update for key [echoCoordinatorState].
| [DEBUG] [06/02/2020 17:05:16.872] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator/$b] WriteMajorityPlus [echoCoordinatorState] [1] of [1].
| [DEBUG] [06/02/2020 17:05:16.872] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] The coordinator state was successfully updated with ShardRegionRegistered(Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689])
| [DEBUG] [06/02/2020 17:05:16.872] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] New coordinator state after [ShardRegionRegistered(Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689])]: [State(Map())]
| [DEBUG] [06/02/2020 17:05:16.872] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [TimerScheduler(akka://ClusterShardingLeaseSpec)] Cancel timer [RegisterRetry] with generation [4]
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Retry request for shard [1] homes from coordinator at [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echoCoordinator/singleton/coordinator#-87399318]]. [1] buffered messages.
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Storing new coordinator state [State(Map())]
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Remembering shard allocation [1]
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Update for key [echoCoordinatorState].
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator/$c] WriteMajorityPlus [echoCoordinatorState] [1] of [1].
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Update for key [shard-echo-all].
| [DEBUG] [06/02/2020 17:05:16.873] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] The coordinator state was successfully updated with ShardHomeAllocated(1,Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]), waiting for remember shard update
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator/RememberEntitiesStore] The coordinator shards state was successfully updated with 1
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] The ShardCoordinator saw remember shard start successfully written ShardHomeAllocated(1,Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689])
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [TimerScheduler(akka://ClusterShardingLeaseSpec)] Cancel timer [RememberEntityTimeout] with generation [2]
| [DEBUG] [akkaShardAllocated][06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] Shard [1] allocated at [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]]
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Host Shard [1] 
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echoCoordinator/singleton/coordinator] New coordinator state after [ShardHomeAllocated(1,Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689])]: [State(Map(1 -> Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]))]
| [DEBUG] [akkaShardStarted][06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Starting shard [1] in region
| [DEBUG] [06/02/2020 17:05:16.874] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Shard [1] located at [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]]
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-17] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1/RememberEntitiesStore] Starting up DDataRememberEntitiesStore, write timeout: [2.000 s], read timeout: [5.000 s], majority min cap: [5]
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-1-0].
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-1-1].
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-1-2].
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-1-3].
| [DEBUG] [06/02/2020 17:05:16.876] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-5] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/replicator] Received Get for key [shard-echo-1-4].
| [INFO] [06/02/2020 17:05:16.886] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [TestLease(akka://ClusterShardingLeaseSpec)] Creating lease LeaseSettings(ClusterShardingLeaseSpec-shard-echo-1, ClusterShardingLeaseSpec@127.0.1.1:39905, TimeoutSettings(12 seconds, 2 minutes, 5 seconds))
| [INFO] [06/02/2020 17:05:16.886] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1] Acquiring lease LeaseSettings(ClusterShardingLeaseSpec-shard-echo-1, ClusterShardingLeaseSpec@127.0.1.1:39905, TimeoutSettings(12 seconds, 2 minutes, 5 seconds))
| [INFO] [06/02/2020 17:05:16.886] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [TestLease(akka://ClusterShardingLeaseSpec)] acquire, current response Future(<not completed>)
| [DEBUG] [06/02/2020 17:05:16.911] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1] Lease acquired
| [DEBUG] [06/02/2020 17:05:16.911] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-18] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1] Waiting for load of entity ids using [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo/1/RememberEntitiesStore#23391494]] to complete
| [DEBUG] [06/02/2020 17:05:16.911] [ClusterShardingLeaseSpec-akka.actor.default-dispatcher-19] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1/RememberEntitiesStore] Another get entities request after responding to one, not expected/supported
| [DEBUG] [06/02/2020 17:05:18.622] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-3] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Retry request for shard [1] homes from coordinator at [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echoCoordinator/singleton/coordinator#-87399318]]. [1] buffered messages.
| [DEBUG] [06/02/2020 17:05:18.622] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-3] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Shard [1] located at [Actor[akka://ClusterShardingLeaseSpec/system/sharding/echo#455684689]]
| [ERROR] [06/02/2020 17:05:18.922] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-3] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1] Failed to load initial entity ids from remember entities store within [2.000 s], stopping shard for backoff and restart
| [DEBUG] [06/02/2020 17:05:18.922] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-3] [TimerScheduler(akka://ClusterShardingLeaseSpec)] Cancel all timers
| [DEBUG] [06/02/2020 17:05:18.922] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-3] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo/1] Shard [1] shutting down
| [DEBUG] [06/02/2020 17:05:18.923] [ClusterShardingLeaseSpec-akka.actor.internal-dispatcher-22] [akka://ClusterShardingLeaseSpec@127.0.1.1:39905/system/sharding/echo] echo: Shard [1]  terminated while not being handed off
| [DEBUG] [06/02/2020 17:05:19.913] [pool-1-thread-1-ScalaTest-running-DDataClusterShardingLeaseSpec] [WithLogCapturing(akka://ClusterShardingLeaseSpec)] Logging finished for test [Cluster sharding with lease should not start until lease is acquired]
<-- [[34mCluster sharding with lease should not start until lease is acquired[0m] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1)]
[06-02 15:05:19.941] [0m[[0m[0minfo[0m] [0m[0m[31m- should not start until lease is acquired *** FAILED *** (3 seconds, 319 milliseconds)[0m[0m
[06-02 15:05:19.941] [0m[[0m[0minfo[0m] [0m[0m[31m  java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.Predef$.assert(Predef.scala:223)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:969)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.ClusterShardingLeaseSpec.$anonfun$new$2(ClusterShardingLeaseSpec.scala:104)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)[0m[0m
[06-02 15:05:19.942] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:36)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)[0m[0m
[06-02 15:05:19.943] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.WithLogCapturing.withFixture(WithLogCapturing.scala:34)[0m[0m
[06-02 15:05:19.944] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.WithLogCapturing.withFixture$(WithLogCapturing.scala:21)[0m[0m
[06-02 15:05:19.944] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.ClusterShardingLeaseSpec.withFixture(ClusterShardingLeaseSpec.scala:61)[0m[0m
```

**Comment by johanandren** [comment]
Note that this was before build 47 (merging all the outstanding work) so could not be relevant. But it kind of looks like a timing issue.

**Comment by johanandren** [comment]
Let's close this since it was before a lot of changes in the Remember Entities rework
