### ISSUE TITLE
Failed: DDataClusterShardingLeavingSpec (remember entities branch)

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29179]
```
[info] [JVM-4] - must recover after leaving coordinator node (on node 'fourth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode4) *** FAILED ***
[info] [JVM-4]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-4]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-4]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info]
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly-remember-entities/47/consoleFull

**Comment by johanandren** [comment]
Not sure it is the same but just saw a fail in the same test class in master #29212

**Comment by patriknw** [comment]
closing as old, and I think we fixed something here
