### ISSUE TITLE
Failed: SurviveNetworkInstability

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29198]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2376/consoleText

```
must heal after unreachable when ring is changed (on node 'seventh', class akka.cluster.SurviveNetworkInstabilityMultiJvmNode7) *** FAILED *** (59 seconds, 962 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  Set(akka://SurviveNetworkInstability@a6.moxie:54699, akka://SurviveNetworkInstability@a5.moxie:49828, akka://SurviveNetworkInstability@a4.moxie:37807, akka://SurviveNetworkInstability@a6.moxie:40144, akka://SurviveNetworkInstability@a5.moxie:55101) did not equal Set(akka://SurviveNetworkInstability@a5.moxie:55101, akka://SurviveNetworkInstability@a6.moxie:54699, akka://SurviveNetworkInstability@a5.moxie:49828, akka://SurviveNetworkInstability@a6.moxie:40144) (SurviveNetworkInstabilitySpec.scala:122)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$assertUnreachable$2(SurviveNetworkInstabilitySpec.scala:122)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.cluster.SurviveNetworkInstabilitySpec.assertUnreachable(SurviveNetworkInstabilitySpec.scala:122)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.cluster.SurviveNetworkInstabilitySpec.$anonfun$new$36(SurviveNetworkInstabilitySpec.scala:263)[0m[0m
```

**Comment by chbatey** [comment]
I was unable to see what happened here. Node 7, having joined the cluster by joining 1 while partitioned from 2, 3, 4 and 5 also sees node 1 as unreachable but there are no logs to see why:

```
[INFO] [06/08/2020 09:44:53.059] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - Welcome from [akka://SurviveNetworkInstability@a4.moxie:37807]
[info] [JVM-7] [INFO] [06/08/2020 09:44:53.098] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - is the new leader among reachable nodes (more leaders may exist)
[info] [JVM-7] [INFO] [06/08/2020 09:44:53.317] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - is no longer leader
[info] [JVM-7] [WARN] [akkaUnreachable][06/08/2020 09:44:59.698] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - Marking node as UNREACHABLE [Member(address = akka://SurviveNetworkInstability@a5.moxie:49828, status = Up)].
[info] [JVM-7] [WARN] [akkaUnreachable][06/08/2020 09:44:59.699] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - Marking node as UNREACHABLE [Member(address = akka://SurviveNetworkInstability@a5.moxie:55101, status = Up)].
[info] [JVM-7] [WARN] [akkaUnreachable][06/08/2020 09:44:59.699] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - Marking node as UNREACHABLE [Member(address = akka://SurviveNetworkInstability@a6.moxie:40144, status = Up)].
[info] [JVM-7] [WARN] [akkaUnreachable][06/08/2020 09:44:59.699] [SurviveNetworkInstability-akka.actor.internal-dispatcher-19] [Cluster(akka://SurviveNetworkInstability)] Cluster Node [akka://SurviveNetworkInstability@a6.moxie:40421] - Marking node as UNREACHABLE [Member(address = akka://SurviveNetworkInstability@a6.moxie:54699, status = Up)].
``` 

Then

```
Set(
    akka://SurviveNetworkInstability@a6.moxie:54699,
    akka://SurviveNetworkInstability@a5.moxie:49828,
    akka://SurviveNetworkInstability@a4.moxie:37807, an extra one, which is node 1
    akka://SurviveNetworkInstability@a6.moxie:40144,
    akka://SurviveNetworkInstability@a5.moxie:55101

    ) did not equal


Set(
    akka://SurviveNetworkInstability@a6.moxie:54699,
    akka://SurviveNetworkInstability@a5.moxie:49828,
    akka://SurviveNetworkInstability@a6.moxie:40144
    akka://SurviveNetworkInstability@a5.moxie:55101,
 ) (SurviveNetworkInstabilitySpec.scala:122)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7991/consoleText

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/815/console

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/6316605765?check_suite_focus=true

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/7758696312?check_suite_focus=true

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3442066387/jobs/5742264289
