### ISSUE TITLE
Failed: DDataClusterShardingLeavingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29212]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/411/console

```
[info] [JVM-4] - must recover after leaving coordinator node (on node 'fourth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode4) *** FAILED ***
[info] [JVM-4]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-5] - must recover after leaving coordinator node (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode5) *** FAILED ***
[info] [JVM-3] - must recover after leaving coordinator node (on node 'third', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode3) *** FAILED ***
[info] [JVM-4]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-5]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-5]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-4]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-5]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info] [JVM-4]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:164)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-5]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:164)
```

**Comment by ignasi35** [comment]
Again in https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2381/console


```
[info] [JVM-5] [WARN] [06/13/2020 10:23:38.343] [DDataClusterShardingLeavingSpec-akka.actor.internal-dispatcher-28] [akka://DDataClusterShardingLeavingSpec@a6.moxie:38586/system/sharding/Entity] Entity: Retry request for shards [8] homes from coordinator. [13] total buffered messages.
[info] [JVM-3] [WARN] [06/13/2020 10:23:38.378] [DDataClusterShardingLeavingSpec-akka.actor.internal-dispatcher-26] [akka://DDataClusterShardingLeavingSpec@a6.moxie:35993/system/sharding/Entity] Entity: Retry request for shards [8] homes from coordinator. [13] total buffered messages.
[info] [JVM-4] - must recover after leaving coordinator node (on node 'fourth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode4) *** FAILED ***
[info] [JVM-4]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-4]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-4]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info] [JVM-4]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:164)
[info] [JVM-4]   at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
[info] [JVM-4]   at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[info] [JVM-4]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$21(ClusterShardingLeavingSpec.scala:160)
[info] [JVM-4]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-4]   ...
[info] [JVM-5] - must recover after leaving coordinator node (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode5) *** FAILED ***
[info] [JVM-5]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-5]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-5]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info] [JVM-5]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info] [JVM-5]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:164)
[info] [JVM-5]   at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:370)
[info] [JVM-5]   at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:675)
[info] [JVM-5]   at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$21(ClusterShardingLeavingSpec.scala:160)
[info] [JVM-5]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-5]   ...
[info] [JVM-3] - must recover after leaving coordinator node (on node 'third', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode3) *** FAILED ***
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
[info] [JVM-2] [INFO] [06/13/2020 10:23:38.528] [DDataClusterShardingLeavingSpec-akka.actor.internal-dispatcher-25] [Association(akka://DDataClusterShardingLeavingSpec)] Association to [akka://DDataClusterShardingLeavingSpec@a5.moxie:39164] having UID [-1653191956959949722] has been stopped. All messages to this UID will be delivered to dead letters. Reason: Cluster member removed, previous status [Up]
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-2] [INFO] [06/13/2020 10:23:38.529] [DDataClusterShardingLeavingSpec-akka.actor.internal-dispatcher-25] [Association(akka://DDataClusterShardingLeavingSpec)] Association to [akka://DDataClusterShardingLeavingSpec@a6.moxie:38586] having UID [-7181221736749850360] has been stopped. All messages to this UID will be delivered to dead letters. Reason: Cluster member removed, previous status [Up]
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info] [JVM-2] [INFO] [06/13/2020 10:23:38.529] [DDataClusterShardingLeavingSpec-akka.actor.internal-dispatcher-25] [Association(akka://DDataClusterShardingLeavingSpec)] Association to [akka://DDataClusterShardingLeavingSpec@a6.moxie:35993] having UID [2373560743327391381] has been stopped. All messages to this UID will be delivered to dead letters. Reason: Cluster member removed, previous status [Up]
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info] [JVM-3]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
```

**Comment by chbatey** [comment]
I think this is related to our recent changes to ddata/sharding.

Node2 times out leaving gracefully (10s) meaning that the new coordinator can't do state updates. 

There's nothing at INFO level saying why JVM2 was unable to shutdown gracefully. I'll run this on repeat with debug logging in Jenkins.

**Comment by seglo** [comment]
Timeout on Jenkins `akka-classic-cluster-tests` build on master

https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/484/consoleText

```
java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef
```

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7998/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7909/consoleFull

**Comment by johanandren** [comment]
We haven't seen this for 1.5 years, closing for now.
