### ISSUE TITLE
Failed: akka.cluster.sharding.PersistentShardingMigrationSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29234]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/20114/testReport/junit/akka.cluster.sharding/PersistentShardingMigrationSpec/Migration_should_allow_migration_of_remembered_shards_and_now_allow_going_back/

(in the new remember entities branch)
```
 assertion failed: timeout (3 seconds) during expectMsg while waiting for ack
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:969)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3(PersistentShardingMigrationSpec.scala:109)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3$adapted(PersistentShardingMigrationSpec.scala:107)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.withSystem$1(PersistentShardingMigrationSpec.scala:163)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$2(PersistentShardingMigrationSpec.scala:107)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly-remember-entities/91/testReport/junit/akka.cluster.sharding/PersistentShardingMigrationSpec/Migration_should_allow_migration_of_remembered_shards_and_now_allow_going_back/

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8083/testReport/junit/akka.cluster.sharding/PersistentShardingMigrationSpec/Migration_should_allow_migration_of_remembered_shards_and_now_allow_going_back/
