### ISSUE TITLE
[failed] PersistentClusterShardingWithEntityRecoveryMultiJvm

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#29269]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/420/console
```
Failed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode1
Failed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode4
Failed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode5
Failed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode6
Failed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode7
```

**Comment by johanandren** [comment]
Failure in build 420: 

```
[info] [JVM-4]  must recover entities upon restart (on node 'third', class akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode4) *** FAILED ***
[info] [JVM-4] [31m  java.lang.AssertionError: assertion failed: timeout (49341041596 nanoseconds) during expectMsg while waiting for 0
[info] [JVM-4] [31m  at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-4] [31m  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
[info] [JVM-4] [31m  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)
[info] [JVM-4] [31m  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)
[info] [JVM-4] [31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:969)
[info] [JVM-4] [31m  at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$68(ClusterShardingSpec.scala:784)
[info] [JVM-4] [31m  at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-4] [31m  at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$66(ClusterShardingSpec.scala:762)
```

**Comment by octonato** [comment]
I couldn't find anything that could explain this failure except regular timeout. 

Verbose have been enabled for this test after the failure (see https://github.com/akka/akka/pull/29325/files#diff-d0d079ef85ad428ebfe62812f0871f818f09d94e2bab423608e82b185942e357R135). Since then it didn't happen again, so we may need more time to see if we get more insights.

**Comment by patriknw** [comment]
I assume this was also fixed by https://github.com/akka/akka/pull/29773
