### ISSUE TITLE
[failed] DurablePruningSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#29270]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2386/console

**Comment by chbatey** [comment]
@ignasi35 it is nice to include the stack so we can quickly check if it is the same failure when logging ones in the future

**Comment by ignasi35** [comment]
(better late than never)
This is the stacktrace missing in the description above:

```

[info] [JVM-2] [WARN] [akkaUnreachable][06/18/2020 12:26:17.451] [DurablePruningSpec-akka.actor.internal-dispatcher-27] [Cluster(akka://DurablePruningSpec)] Cluster Node [akka://DurablePruningSpec@a5.moxie:56102] - Marking node as UNREACHABLE [Member(address = akka://DurablePruningSpec@a4.moxie:36039, status = Up)].
[info] [JVM-2] [INFO] [06/18/2020 12:26:17.859] [DurablePruningSpec-akka.actor.internal-dispatcher-14] [Cluster(akka://DurablePruningSpec)] Cluster Node [akka://DurablePruningSpec@a5.moxie:36116] - is the new leader among reachable nodes (more leaders may exist)
[info] [JVM-1] - must move data from removed node *** FAILED *** (22 seconds, 424 milliseconds)
[info] [JVM-1]   4 was not equal to 3 (DurablePruningSpec.scala:180)
[info] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-1]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[info] [JVM-1]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
[info] [JVM-1]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
[info] [JVM-1]   at akka.cluster.ddata.DurablePruningSpec.$anonfun$new$22(DurablePruningSpec.scala:180)
[info] [JVM-1]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)
[info] [JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.ddata.DurablePruningSpec.$anonfun$new$21(DurablePruningSpec.scala:174)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:416)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:404)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:969)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:431)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:431)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.ddata.DurablePruningSpec.$anonfun$new$20(DurablePruningSpec.scala:172)
...
[info] [JVM-1] [ERROR] [06/18/2020 12:26:22.378] [DurablePruningSpec-akka.remote.default-remote-dispatcher-6] [akka://DurablePruningSpec/system/Materializers/StreamSupervisor-1/remote-2-0-ignoreSink] Error in stage [akka.remote.artery.InboundHandshake@6310b396]: outboundControlIngress for [akka://DurablePruningSpec@a4.moxie:60858] not initialized yet
[info] [JVM-1] java.lang.IllegalStateException: outboundControlIngress for [akka://DurablePruningSpec@a4.moxie:60858] not initialized yet
[info] [JVM-1] 	at akka.remote.artery.Association.outboundControlIngress(Association.scala:236)
[info] [JVM-1] 	at akka.remote.artery.Association.sendControl(Association.scala:323)
[info] [JVM-1] 	at akka.remote.artery.ArteryTransport.sendControl(ArteryTransport.scala:751)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.$anonfun$onHandshakeReq$1(Handshake.scala:272)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$after(Handshake.scala:296)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:271)
....

[info] [JVM-1] [ERROR] [06/18/2020 12:26:22.378] [DurablePruningSpec-akka.remote.default-remote-dispatcher-11] [akka://DurablePruningSpec/system/Materializers/StreamSupervisor-1/remote-3-0-ignoreSink] Error in stage [akka.remote.artery.InboundHandshake@6310b396]: outboundControlIngress for [akka://DurablePruningSpec@a4.moxie:60858] not initialized yet
[info] [JVM-1] java.lang.IllegalStateException: outboundControlIngress for [akka://DurablePruningSpec@a4.moxie:60858] not initialized yet
[info] [JVM-1] 	at akka.remote.artery.Association.outboundControlIngress(Association.scala:236)
[info] [JVM-1] 	at akka.remote.artery.Association.sendControl(Association.scala:323)
[info] [JVM-1] 	at akka.remote.artery.ArteryTransport.sendControl(ArteryTransport.scala:751)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.$anonfun$onHandshakeReq$1(Handshake.scala:272)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$after(Handshake.scala:296)
[info] [JVM-1] 	at akka.remote.artery.InboundHandshake$$anon$2.akka$remote$artery$InboundHandshake$$anon$$onHandshakeReq(Handshake.scala:271)
[info] [JVM-1] 	at 
...
```
