### ISSUE TITLE
failed: SplitBrainResolverIntegrationSpec - cross dc joining

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29280]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7766

```
[info] [JVM-1] [ERROR] [06/20/2020 06:34:17.393] [SplitBrainResolverIntegrationSpec-akka.actor.default-dispatcher-21] [akka://SplitBrainResolverIntegrationSpec@localhost:34541/user/shardingRegistry-13] trying to register akka://SplitBrainResolverIntegrationSpec-13@localhost:34577, but akka://SplitBrainResolverIntegrationSpec-13@localhost:35351 was already registered for /system/sharding/Entity-13/7/7-dcB
[info] [JVM-1] - must KeepAll when using keep-majority and side1=3 and side2=2with multi-DC (on node 'node1', class akka.cluster.sbr.SplitBrainResolverIntegrationSpecMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(DoubleRegister(/system/sharding/Entity-13/1/1-dcB,trying to register akka://SplitBrainResolverIntegrationSpec-13@localhost:35351, but akka://SplitBrainResolverIntegrationSpec-13@localhost:34577 was already registered for /system/sharding/Entity-13/1/1-dcB),Actor[akka://SplitBrainResolverIntegrationSpec/user/shardingRegistry-13#1632689785]) after 49 millis
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:767)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:731)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:730)
[info] [JVM-1]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.sbr.SplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$5(SplitBrainResolverIntegrationSpec.scala:258)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-1]   at akka.cluster.sbr.SplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$2(SplitBrainResolverIntegrationSpec.scala:254)
```

**Comment by patriknw** [comment]
The problem is what @johanandren identified in the logs:
```
[JVM-5] [INFO] [akkaMemberChanged][06/20/2020 06:34:16.271] [SplitBrainResolverIntegrationSpec-13-akka.actor.internal-dispatcher-31] [Cluster(akka://SplitBrainResolverIntegrationSpec-13)] Cluster Node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] dc [dcB] - Leader is moving node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] to [Up]
[JVM-5] [INFO] [akkaMemberChanged][06/20/2020 06:34:16.271] [SplitBrainResolverIntegrationSpec-13-akka.actor.internal-dispatcher-31] [Cluster(akka://SplitBrainResolverIntegrationSpec-13)] Cluster Node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-5] dc [dcB] - Leader is moving node [akka://SplitBrainResolverIntegrationSpec-13@localhost:NODE-4] to [Up]


// 5 is saying it is Up:ing itself, and then marking 4 as up, even though already is up since 06:34:15.284
// do we have a split brain from some bug with joining and multi-dc here?
```

NODE-4 joins via NODE-1 and moves itself to Up in dcB.

NODE-5 joins via NODE-1 and moves itself to Up in dcB. NODE-5 has lower address than NODE-4 and is therefore new leader. It hasn't seen NODE-1 as Up yet so it assigns the upNumber=1 to NODE-5, but that is what NODE-4 also did to itself. Two singletons.

We must find a more safe cross-dc joining mechanism.

In this case both joined via NODE-1 but it could be even worse if they concurrently joined via different nodes.

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7803/consoleFull

**Comment by ignasi35** [comment]
Again in https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7852/console
