### ISSUE TITLE
Failed: PersistentClusterSharding

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29290]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/571/consoleFull

```
[info] [JVM-4] - must recover entities upon restart (on node 'third', class akka.cluster.sharding.PersistentClusterShardingMultiJvmNode4) *** FAILED ***
[info] [JVM-4]   java.lang.AssertionError: assertion failed: timeout (49274064614 nanoseconds) during expectMsg while waiting for 0
[info] [JVM-4]   at scala.Predef$.assert(Predef.scala:282)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)
[info] [JVM-4]   at akka.testkit.TestKit.expectMsg(TestKit.scala:969)
[info] [JVM-4]   at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$68(ClusterShardingSpec.scala:784)
[info] [JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-4]   at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$66(ClusterShardingSpec.scala:762)
[info] [JVM-4]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-4]   at akka.testkit.TestKitBase.within(TestKit.scala:416)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/571

**Comment by chbatey** [comment]
This has with log capturing on now so waiting for it to fail again

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8124/consoleFull

**Comment by patriknw** [comment]
in multi-node with aeron-udp: https://github.com/akka/akka/runs/4576980010?check_suite_focus=true

**Comment by octonato** [comment]
also an old aeron-udp error, may not be relevant anymore

**Comment by patriknw** [comment]
yeah, lets close as old
