### ISSUE TITLE
Log warnings in active-active akka-persistence-typed-tests

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29327]
Much warning logging when running `akka-persistence-typed-tests> testOnly akka.persistence.typed.*`

```
[WARN] [06/29/2020 13:51:29.319] [ActiveActiveSpec-akka.actor.default-dispatcher-6] [RestartWithBackoffSource(akka://ActiveActiveSpec)] Restarting graph due to failure. stack_trace:
akka.stream.WatchedActorTerminatedException: Actor watched by [ask()] has terminated! Was: Actor[akka://ActiveActiveSpec/user/$h#-1066057306]
	at akka.stream.typed.scaladsl.ActorFlow$$anonfun$1.applyOrElse(ActorFlow.scala:124)
	at akka.stream.typed.scaladsl.ActorFlow$$anonfun$1.applyOrElse(ActorFlow.scala:116)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
  | => aat akka.stream.impl.fusing.MapError$$anon$8.onUpstreamFailure(Ops.scala:324)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by johanandren** [comment]
It's the replica-trailing stream failing when the actor stops, we should hide that (perhaps we'd need to go back to separate watch/mapAsync to do that?)

**Comment by chbatey** [comment]
This was fixed by recovering for this exception
