### ISSUE TITLE
HandshakeRetrySpec: Artery handshake must be retried during handshake-timeout (no message loss)

### ISSUE THREAD

**Issue by raboof** [akka/akka#29347]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/581/consoleFull

```
[WARN] [07/02/2020 20:51:57.594] [pool-1-thread-1-ScalaTest-running-HandshakeRetrySpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
[ERROR] [07/02/2020 20:51:57.848] [HandshakeRetrySpec-akka.remote.default-remote-dispatcher-10] [akka://HandshakeRetrySpec/system/Materializers/StreamSupervisor-3/remote-8-0-ignoreSink] Error in stage [TCP-to(localhost:41539)]: null
java.lang.NullPointerException
	at akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anon$6.onPush(TcpStages.scala:413)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:51:57.862] [HandshakeRetrySpec-akka.remote.default-remote-dispatcher-8] [akka://HandshakeRetrySpec/system/Materializers/StreamSupervisor-3/remote-7-0-ignoreSink] Error in stage [TCP-to(localhost:41539)]: null
java.lang.NullPointerException
	at akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anon$6.onPush(TcpStages.scala:413)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:51:57.869] [systemB-akka.remote.default-remote-dispatcher-7] [akka://systemB/system/Materializers/StreamSupervisor-6/remote-7-0-map] Error in stage [akka.remote.artery.tcp.TcpFraming@611c0cd2]: null
java.lang.NullPointerException
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParseInner(ByteStringParser.scala:52)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParse(ByteStringParser.scala:106)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.onPull(ByteStringParser.scala:112)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:551)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:434)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:595)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:702)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:751)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:51:57.869] [systemB-akka.remote.default-remote-dispatcher-10] [akka://systemB/system/Materializers/StreamSupervisor-6/remote-8-0-map] Error in stage [akka.remote.artery.tcp.TcpFraming@611c0cd2]: null
java.lang.NullPointerException
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParseInner(ByteStringParser.scala:52)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParse(ByteStringParser.scala:106)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.onPull(ByteStringParser.scala:112)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:551)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:434)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:595)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:702)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:751)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:52:00.051] [HandshakeRetrySpec-akka.remote.default-remote-dispatcher-18] [akka://HandshakeRetrySpec/system/Materializers/StreamSupervisor-3/remote-8-0-ignoreSink] Error in stage [TCP-to(localhost:41539)]: null
java.lang.NullPointerException
	at akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anon$6.onPush(TcpStages.scala:413)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:52:00.058] [systemB-akka.remote.default-remote-dispatcher-10] [akka://systemB/system/Materializers/StreamSupervisor-6/remote-9-0-map] Error in stage [akka.remote.artery.tcp.TcpFraming@611c0cd2]: null
java.lang.NullPointerException
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParseInner(ByteStringParser.scala:52)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParse(ByteStringParser.scala:106)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.onPull(ByteStringParser.scala:112)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:551)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:434)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:595)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:702)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:751)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:52:00.090] [HandshakeRetrySpec-akka.remote.default-remote-dispatcher-18] [akka://HandshakeRetrySpec/system/Materializers/StreamSupervisor-3/remote-7-0-ignoreSink] Error in stage [TCP-to(localhost:41539)]: null
java.lang.NullPointerException
	at akka.stream.impl.io.TcpConnectionStage$TcpStreamLogic$$anon$6.onPush(TcpStages.scala:413)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
	at akka.actor.Actor.aroundReceive(Actor.scala:535)
	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[ERROR] [07/02/2020 20:52:00.096] [systemB-akka.remote.default-remote-dispatcher-10] [akka://systemB/system/Materializers/StreamSupervisor-6/remote-10-0-map] Error in stage [akka.remote.artery.tcp.TcpFraming@611c0cd2]: null
java.lang.NullPointerException
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParseInner(ByteStringParser.scala:52)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.doParse(ByteStringParser.scala:106)
	at akka.stream.impl.io.ByteStringParser$ParsingLogic.onPull(ByteStringParser.scala:112)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:551)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:434)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:595)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:702)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:751)
	at akka.actor.Actor.aroundPreStart(Actor.scala:546)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Reeks of #29341...

**Comment by jrudolph** [comment]
Maybe it's just because your fix for the original issue never made it through so far?

https://github.com/akka/akka/pull/29244

**Comment by jrudolph** [comment]
I created an issue for the original problem at #29354.
