### ISSUE TITLE
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class akka.actor.ActorSelectionMessage] using serializer [class akka.remote.serialization.MessageContainerSerializer].

### ISSUE THREAD

**Issue by selimguvenc** [akka/akka#29420]
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class akka.actor.ActorSelectionMessage] using serializer [class akka.remote.serialization.MessageContainerSerializer].
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:67)
        at akka.remote.EndpointWriter.$anonfun$serializeMessage$1(Endpoint.scala:1033)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:1033)
        at akka.remote.EndpointWriter.writeSend(Endpoint.scala:893)
        at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:865)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:540)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by selimguvenc** [comment]
my configuration;

akka {
  actor {
    provider = "akka.cluster.ClusterActorRefProvider"

    serializers {
      jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-bindings {
      "com.common.message.db.EntityMessage" = jackson-json
      "com.common.message.db.EntityResultMessage" = jackson-json
    }

    deployment {
      /adminApiRouter {
        router = broadcast-group
        routees.paths = ["/user/adminApiMaster"]
        cluster {
          enabled = on
          allow-local-routees = on
          use-role = adminApi
        }
      
      }
    }
  }

  remote {
    log-remote-lifecycle-events = off
    artery.enabled = false
    classic {
      enabled-transports = ["akka.remote.classic.netty.tcp"]
      netty.tcp {
        hostname = "127.0.0.1"
        port = 2556
      }
    }
  }

  cluster {
    seed-nodes = [
      "akka.tcp://dispatch-actor-system@127.0.0.1:2551",
      "akka.tcp://dispatch-actor-system@127.0.0.1:2552",
      "akka.tcp://dispatch-actor-system@127.0.0.1:2553"]

    # auto downing is NOT safe for production deployments.
    # you may want to use it during development, read more about it in the docs.
    auto-down-unreachable-after = 10s

    failure-detector {
      heartbeat-interval = 10 s
      heartbeat-request {
        expected-response-after = 20 s
      }
      acceptable-heartbeat-pause = 10 m
      min-std-deviation = 1000 ms
      threshold = 20.0
    }
  }

  default-dispatcher {
    type = "Dispatcher"
    executor = "fork-join-executor"
    fork-join-executor {
      parallelism-min = 16
      parallelism-factor = 20
      parallelism-max = 100
    }
    shutdown-timeout = 1s
    throughput = 1
    throughput-deadline-time = 0ms
  }
}

**Comment by renatocaval** [comment]
Hello @selimguvenc,   

Our [forums](https://discuss.lightbend.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests, not for general discussion and getting help. Given that, I'm closing this.  

Best.

**Comment by selimguvenc** [comment]
ok thanks
