### ISSUE TITLE
ClusterSingletonManagerLease: should form a cluster

### ISSUE THREAD

**Issue by raboof** [akka/akka#29423]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7863/consoleFull

```
[info] [JVM-5] - should form a cluster (on node 'fourth', class akka.cluster.singleton.ClusterSingletonManagerLeaseMultiJvmNode5) *** FAILED ***
[info] [JVM-5]   java.lang.AssertionError: assertion failed: timeout 3 seconds expired:
[info] [JVM-5]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-5]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:298)
[info] [JVM-5]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:304)
[info] [JVM-5]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:287)
[info] [JVM-5]   at akka.testkit.TestKit.awaitCond(TestKit.scala:969)
[info] [JVM-5]   at akka.cluster.MultiNodeClusterSpec.joinWithin(MultiNodeClusterSpec.scala:241)
[info] [JVM-5]   at akka.cluster.MultiNodeClusterSpec.joinWithin$(MultiNodeClusterSpec.scala:234)
```

**Comment by octonato** [comment]
Happening again
https://github.com/akka/akka/actions/runs/6141065748/job/16660822120#step:10:29962
