### ISSUE TITLE
EntityTypeKey in ReplicatedShardingSettings

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29448]
Is this correct?

```
val typeKey = EntityTypeKey[M](replicaId.id)
```

The `name` of an EntityTypeKey is typically something like the entity class name, e.g. "ShoppingCart".

**Comment by chbatey** [comment]
It needs the replica id in it so we get a full copy of sharding per replica but we should likely also add a name so you can have more than one instance of a sharded replicated entity

**Comment by patriknw** [comment]
> It needs the replica id in it so we get a full copy of sharding per replica

ok, when using `.withDataCenter(replicaId.id))` that is probably handled already.

I wonder if that isn't the case also for `.withRole(replicaId.id))`? We need to look into this more.

> but we should likely also add a name so you can have more than one instance of a sharded replicated entity

Yes, that is needed. I tried this out with two different entity types.

```
Caused by: java.lang.IllegalArgumentException: [DC-A] already initialized for [akka.cluster.sharding.typed.ReplicatedShardingSpec$MyReplicatedStringSet$Command]
	at akka.cluster.sharding.typed.internal.ClusterShardingImpl.internalInit(ClusterShardingImpl.scala:234)
	at akka.cluster.sharding.typed.internal.ClusterShardingImpl.init(ClusterShardingImpl.scala:133)
	at akka.cluster.sharding.typed.internal.ReplicatedShardingExtensionImpl.$anonfun$init$1(ReplicatedShardingExtensionImpl.scala:45)
```
