### ISSUE TITLE
Failed: doc (publish) of akka-protobuf fails

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29466]
after Make warnings in Java code fatal https://github.com/akka/akka/pull/28402

This is failing the akka-publish-nightly

```
[error] Constructing Javadoc information...
[error] Standard Doclet version 11.0.1
[error] Building tree for all the packages and classes...
[error] /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-protobuf/src/main/java/akka/protobuf/LazyStringArrayList.java:51:1:  error: tag not supported in the generated HTML version: tt
[error]  * If multiple threads access an <tt>ArrayList</tt> instance concurrently,
[error]                                  ^Generating /localhome/jenkinsakka/workspace/akka-publish-nightly/akka-protobuf/target/scala-2.12/api/akka/protobuf
```

and

```
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (akka-protobuf / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
```

**Comment by chbatey** [comment]
Could also be related: https://github.com/akka/akka/commit/faada69ab4741164ce6ba892623578aa44d31657

**Comment by patriknw** [comment]
No, I tried

**Comment by patriknw** [comment]
The java warnings are also failing compile of akka-docs in https://jenkins.akka.io:8498/job/akka-nightly-jdk11/688
