### ISSUE TITLE
failed: ArteryUpdSendConsistencyWithThreeLanesSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#29465]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/687

```
[info] - must be able to identify a remote actor and ping it *** FAILED *** (5 seconds, 134 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[WARN] [08/06/2020 11:16:27.333] [systemB-akka.actor.default-dispatcher-7] [akka://systemB/user/otherEcho1] received dead letter from Actor[akka://ArteryUpdSendConsistencyWithThreeLanesSpec/system/testActor-1181#935545040]: 72
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.actorRefBySelection(RemoteSendConsistencySpec.scala:80)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.$anonfun$new$2(RemoteSendConsistencySpec.scala:97)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/628

**Comment by seglo** [comment]
https://jenkins.akka.io:8498/job/akka-release-2.5/282/consoleText

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-aeron-udp-remote-tests/557/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/21396/

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4471/

**Comment by pvlugter** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/9041/

**Comment by patriknw** [comment]
Closing as old (from Jenkins)

**Comment by pvlugter** [comment]
Reopening with failure from GitHub Actions.

https://github.com/akka/akka/runs/7663118350?check_suite_focus=true#step:5:2750

```
[info] - must be able to identify a remote actor and ping it *** FAILED *** (10 seconds, 602 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (10 seconds) during expectMsgClass waiting for class akka.actor.ActorIdentity
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:553)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:552)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.actorRefBySelection(RemoteSendConsistencySpec.scala:81)
[info]   at akka.remote.artery.AbstractRemoteSendConsistencySpec.$anonfun$new$2(RemoteSendConsistencySpec.scala:98)
```
