### ISSUE TITLE
The java JavaExtension.java should be run as part of the build

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29475]
```
[error] java.lang.IllegalArgumentException: requirement failed: The java JavaExtension.java should be run as part of the build
[error] 	at scala.Predef$.require(Predef.scala:281)
[error] 	at akka.TestExtras$Filter$.shouldExist$1(TestExtras.scala:55)
[error] 	at akka.TestExtras$Filter$.$anonfun$settings$11(TestExtras.scala:61)
[error] 	at akka.TestExtras$Filter$.$anonfun$settings$11$adapted(TestExtras.scala:61)
[error] 	at scala.Function2.$anonfun$tupled$1(Function2.scala:53)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at akka.TestExtras$Filter$.$anonfun$settings$9(TestExtras.scala:61)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execut
```

https://jenkins.akka.io:8498/job/akka-nightly-jdk11/691/consoleFull

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/692/console

Failing reliably since https://jenkins.akka.io:8498/job/akka-nightly-jdk11/686/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/693/console

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk11/694/console

**Comment by jrudolph** [comment]
The changes of the first build failing (https://jenkins.akka.io:8498/job/akka-nightly-jdk11/686/changes) would make 327e16980d the most likely culprit.
