### ISSUE TITLE
Failed: MultiDcJoin

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29486]
```
[info] [JVM-5] - must make sure oldest is selected correctly (on node 'fifth', class akka.cluster.MultiDcJoinMultiJvmNode5) *** FAILED *** (6 seconds, 5 milliseconds)
[info] [JVM-4] - must make sure oldest is selected correctly (on node 'fourth', class akka.cluster.MultiDcJoinMultiJvmNode4) *** FAILED *** (5 seconds, 994 milliseconds)
[info] [JVM-5]   1 did not equal 2 (MultiDcJoinSpec.scala:119)
[info] [JVM-4]   akka://MultiDcJoin@a5.moxie:46449 did not equal akka://MultiDcJoin@a6.moxie:43569 (MultiDcJoinSpec.scala:116)
[info] [JVM-5]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-4]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-5]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info] [JVM-4]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info] [JVM-5]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info] [JVM-4]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info] [JVM-5]   at akka.cluster.MultiDcJoinSpec.$anonfun$new$12(MultiDcJoinSpec.scala:119)
[info] [JVM-4]   at akka.cluster.MultiDcJoinSpec.$anonfun$new$12(MultiDcJoinSpec.scala:116)
[info] [JVM-5]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
```

https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7885/consoleFull

**Comment by patriknw** [comment]
Interesting. This was supposed to be solved in https://github.com/akka/akka/pull/29346

The log:

```
[info] [JVM-1] [INFO] [akkaMemberChanged][08/11/2020 22:49:10.268] [MultiDcJoin-akka.actor.interna l-dispatcher-4] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Node [akka://MultiDcJoin@third] is JOINING, roles [dc-alpha]
[info] [JVM-1] [INFO] [akkaMemberChanged][08/11/2020 22:49:10.271] [MultiDcJoin-akka.actor.internal-dispatcher-4] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Node [akka://MultiDcJoin@second] is JOINING, roles [dc-alpha]
[info] [JVM-3] [INFO] [08/11/2020 22:49:10.369] [MultiDcJoin-akka.actor.internal-dispatcher-3] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@third] dc [alpha] - Welcome from [akka://MultiDcJoin@first]
[info] [JVM-2] [INFO] [08/11/2020 22:49:10.372] [MultiDcJoin-akka.actor.internal-dispatcher-15] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@second] dc [alpha] - Welcome from [akka://MultiDcJoin@first]
[info] [JVM-1] [INFO] [akkaMemberChanged][08/11/2020 22:49:11.155] [MultiDcJoin-akka.actor.internal-dispatcher-31] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Leader is moving node [akka://MultiDcJoin@second] to [Up]
[info] [JVM-1] [INFO] [akkaMemberChanged][08/11/2020 22:49:11.155] [MultiDcJoin-akka.actor.internal-dispatcher-31] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Leader is moving node [akka://MultiDcJoin@third] to [Up]
[info] [JVM-1] [INFO] [akkaMemberChanged][08/11/2020 22:49:11.645] [MultiDcJoin-akka.actor.internal-dispatcher-2] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Node [akka://MultiDcJoin@fifth] is JOINING, roles [dc-beta]
[info] [JVM-5] [INFO] [08/11/2020 22:49:11.693] [MultiDcJoin-akka.actor.internal-dispatcher-3] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fifth] dc [beta] - Welcome from [akka://MultiDcJoin@first]
[info] [JVM-5] [INFO] [08/11/2020 22:49:12.373] [MultiDcJoin-akka.actor.internal-dispatcher-16] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fifth] dc [beta] - is the new leader among reachable nodes (more leaders may exist)
[info] [JVM-5] [INFO] [akkaMemberChanged][08/11/2020 22:49:13.411] [MultiDcJoin-akka.actor.internal-dispatcher-2] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fifth] dc [beta] - Leader is moving node [akka://MultiDcJoin@fifth] to [Up]
[info] [JVM-5] [INFO] [08/11/2020 22:49:13.423] [MultiDcJoin-akka.actor.internal-dispatcher-24] [akka://MultiDcJoin@fifth/system/cluster/core/daemon/crossDcHeartbeatSender] Cluster Node [akka://MultiDcJoin@fifth] dc [beta] - Cross DC heartbeat becoming ACTIVE on this node (for DC: beta), monitoring other DCs oldest nodes
[info] [JVM-2] [INFO] [akkaMemberChanged][08/11/2020 22:49:13.818] [MultiDcJoin-akka.actor.internal-dispatcher-3] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@second] dc [alpha] - Node [akka://MultiDcJoin@fourth] is JOINING, roles [dc-beta]
[info] [JVM-4] [INFO] [08/11/2020 22:49:13.877] [MultiDcJoin-akka.actor.internal-dispatcher-2] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fourth] dc [beta] - Welcome from [akka://MultiDcJoin@second]
[info] [JVM-4] [INFO] [08/11/2020 22:49:14.372] [MultiDcJoin-akka.actor.internal-dispatcher-3] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fourth] dc [beta] - is the new leader among reachable nodes (more leaders may exist)
[info] [JVM-1] [INFO] [08/11/2020 22:49:14.462] [MultiDcJoin-akka.actor.internal-dispatcher-32] [akka://MultiDcJoin@first/system/cluster/core/daemon/crossDcHeartbeatSender] Cluster Node [akka://MultiDcJoin@first] dc [alpha] - Cross DC heartbeat becoming ACTIVE on this node (for DC: alpha), monitoring other DCs oldest nodes
[info] [JVM-4] [INFO] [akkaMemberChanged][08/11/2020 22:49:15.398] [MultiDcJoin-akka.actor.internal-dispatcher-2] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fourth] dc [beta] - Leader is moving node [akka://MultiDcJoin@fourth] to [Up]
[info] [JVM-4] [INFO] [akkaMemberChanged][08/11/2020 22:49:15.398] [MultiDcJoin-akka.actor.internal-dispatcher-2] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fourth] dc [beta] - Leader is moving node [akka://MultiDcJoin@fifth] to [Up]
[info] [JVM-4] [INFO] [08/11/2020 22:49:15.411] [MultiDcJoin-akka.actor.internal-dispatcher-16] [akka://MultiDcJoin@fourth/system/cluster/core/daemon/crossDcHeartbeatSender] Cluster Node [akka://MultiDcJoin@fourth] dc [beta] - Cross DC heartbeat becoming ACTIVE on this node (for DC: beta), monitoring other DCs oldest nodes
[info] [JVM-5] [INFO] [08/11/2020 22:49:15.437] [MultiDcJoin-akka.actor.internal-dispatcher-25] [Cluster(akka://MultiDcJoin)] Cluster Node [akka://MultiDcJoin@fifth] dc [beta] - is no longer leader
[info] [JVM-5] - must make sure oldest is selected correctly (on node 'fifth', class akka.cluster.MultiDcJoinMultiJvmNode5) *** FAILED *** (6 seconds, 5 milliseconds)
[info] [JVM-4] - must make sure oldest is selected correctly (on node 'fourth', class akka.cluster.MultiDcJoinMultiJvmNode4) *** FAILED *** (5 seconds, 994 milliseconds)
[info] [JVM-5]   1 did not equal 2 (MultiDcJoinSpec.scala:119)
[info] [JVM-4]   akka://MultiDcJoin@fourth did not equal akka://MultiDcJoin@fifth (MultiDcJoinSpec.scala:116)
```

fourth is moved to Up twice, first by fifth and then by fourth.

It's supposed to wait for convergence, but it doesn't. I think I see what is wrong.
