### ISSUE TITLE
Cluster sharding (ddata) with down member, scenario 2 should recover after downing other node (not coordinator)

### ISSUE THREAD

**Issue by raboof** [akka/akka#29494]
https://jenkins.akka.io:8498/job/akka-multi-node/4173/consoleFull
```
[info] [JVM-2] - must recover after downing other node (not coordinator) (on node 'second', class akka.cluster.sharding.DDataClusterShardCoordinatorDowning2MultiJvmNode2) *** FAILED ***
[info] [JVM-2]   java.lang.AssertionError: assertion failed: block took 21.209 seconds, exceeding 20.000 seconds
[info] [JVM-2]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:422)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:404)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:969)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:431)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:431)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:969)
[info] [JVM-2]   at akka.cluster.sharding.ClusterShardCoordinatorDowning2Spec.$anonfun$new$12(ClusterShardCoordinatorDowning2Spec.scala:132)
[info] [JVM-2]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info] [JVM-2]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by chbatey** [comment]
Running on repeat here with DEBUG logging: https://jenkins.akka.io:8498/job/legacy-akka-multi-node-repeat4/

**Comment by pvlugter** [comment]
This is an old failure and doesn't seem to have been seen again. Worth keeping open or close?
