### ISSUE TITLE
Failed: MultiDcClusterShardingMultiJvm serveral timeouts

### ISSUE THREAD

**Issue by octonato** [akka/akka#29524]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/636/consoleText

Several future timeouts and barrier failures across all nodes in multi-jvm test:

```scala
be able to ask via entity ref (on node 'third', class akka.cluster.sharding.typed.MultiDcClusterShardingMultiJvmNode3) *** FAILED *** (165 milliseconds)
A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query. (MultiDcClusterShardingSpec.scala:91)
org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
at akka.cluster.sharding.typed.MultiDcClusterShardingSpec.$anonfun$new$6(MultiDcClusterShardingSpec.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

and 

```scala
java.lang.RuntimeException: barrier failed: cross-dc-1
at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
at akka.actor.FSM.processEvent(FSM.scala:804)
at akka.actor.FSM.processEvent$(FSM.scala:801)
at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:793)
at akka.actor.Actor.aroundReceive(Actor.scala:537)
at akka.actor.Actor.aroundReceive$(Actor.scala:535)
at akka.remote.testconductor.ClientFSM.aroundReceive(Player.scala:172)
```

**Comment by johanandren** [comment]
I think it is only one timeout, the barrier failures are consequences of it.
