### ISSUE TITLE
Failed: DDataClusterShardingWithEntityRecovery

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29538]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7985/consoleText

```
[info] [JVM-1] - must recover entities upon restart (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: after-shard-restart
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-4] <-- [Persistent Cluster Shards must recover entities upon restart (on node 'third', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode4)] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (49279513480 nanoseconds) during expectMsg while waiting for 0)]
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-1]   at akka.actor.FSM.processEvent(FSM.scala:804)
[info] [JVM-1]   at akka.actor.FSM.processEvent$(FSM.scala:801)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
[info] [JVM-1]   ...
[info] [JVM-1] - must permanently stop entities which passivate (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: cluster-started-12
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-1]   at akka.actor.FSM.processEvent(FSM.scala:804)
[info] [JVM-1]   at akka.actor.FSM.processEvent$(FSM.scala:801)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
[info] [JVM-1]   ...
[info] [JVM-1] --> [Persistent Cluster Shards must restart entities which stop without passivating (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1)] Start of log messages of test that [Failed(java.lang.RuntimeException: barrier failed: cluster-started-12)]
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.466] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode1] [WithLogCapturing(akka://DDataClusterShardingWithEntityRecoverySpec)] Logging started for test [Persistent Cluster Shards must restart entities which stop without passivating (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1)]
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.467] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode1] [akka.actor.ActorSystemImpl(DDataClusterShardingWithEntityRecoverySpec)] entering barriers (cluster-started-12)
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.468] [New I/O worker #4] [PlayerHandler(akka://DDataClusterShardingWithEntityRecoverySpec)] channel [id: 0x3721325a, /127.0.0.1:48606 => /127.0.0.1:4711] written 35
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.468] [New I/O worker #1] [ConductorHandler(akka://DDataClusterShardingWithEntityRecoverySpec)] message from /127.0.0.1:48606: EnterBarrier(cluster-started-12,Some(49999396460 nanoseconds))
[info] [JVM-6] - must recover entities upon restart (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6) *** FAILED ***
[info] [JVM-6]   java.lang.RuntimeException: barrier failed: after-shard-restart
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.469] [New I/O worker #4] [PlayerHandler(akka://DDataClusterShardingWithEntityRecoverySpec)] message from /127.0.0.1:4711: BarrierResult(cluster-started-12,false)
[info] [JVM-6]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-6]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-6]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-6]   at akka.actor.FSM.processEvent(FSM.scala:804)
[info] [JVM-6]   at akka.actor.FSM.processEvent$(FSM.scala:801)
[info] [JVM-6]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
[info] [JVM-6]   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
[info] [JVM-1] | [DEBUG] [09/01/2020 06:12:59.470] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode1] [WithLogCapturing(akka://DDataClusterShardingWithEntityRecoverySpec)] Logging finished for test [Persistent Cluster Shards must restart entities which stop without passivating (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1)]
[info] [JVM-6]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
[info] [JVM-6]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
[info] [JVM-1] <-- [Persistent Cluster Shards must restart entities which stop without passivating (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1)] End of log messages of test that [Failed(java.lang.RuntimeException: barrier failed: cluster-started-12)]
[info] [JVM-6]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
[info] [JVM-6]   ...
[info] [JVM-6] --> [Persistent Cluster Shards must permanently stop entities which passivate (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6)] Start of log messages of test that [Failed(java.lang.RuntimeException: barrier failed: cluster-started-12)]
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.464] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode6] [WithLogCapturing(akka://DDataClusterShardingWithEntityRecoverySpec)] Logging started for test [Persistent Cluster Shards must permanently stop entities which passivate (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6)]
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.469] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode6] [akka.actor.ActorSystemImpl(DDataClusterShardingWithEntityRecoverySpec)] entering barriers (cluster-started-12)
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.470] [DDataClusterShardingWithEntityRecoverySpec-akka.actor.default-dispatcher-18] [akka://DDataClusterShardingWithEntityRecoverySpec@localhost:34115/user/RememberCounterRegion] Idle entities will not be passivated because 'rememberEntities' is enabled.
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.470] [New I/O worker #4] [PlayerHandler(akka://DDataClusterShardingWithEntityRecoverySpec)] channel [id: 0x4f82a5b8, /127.0.0.1:48610 => localhost/127.0.0.1:4711] written 34
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.471] [DDataClusterShardingWithEntityRecoverySpec-akka.actor.default-dispatcher-18] [akka://DDataClusterShardingWithEntityRecoverySpec@localhost:34115/user/RememberCounterRegion] RememberCounter: Coordinator moved from [] to [akka://DDataClusterShardingWithEntityRecoverySpec@localhost:46211]
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.471] [DDataClusterShardingWithEntityRecoverySpec-akka.actor.default-dispatcher-18] [TimerScheduler(akka://DDataClusterShardingWithEntityRecoverySpec)] Cancel timer [RegisterRetry] with generation [2]
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.471] [New I/O worker #4] [PlayerHandler(akka://DDataClusterShardingWithEntityRecoverySpec)] message from localhost/127.0.0.1:4711: BarrierResult(cluster-started-12,false)
[info] [JVM-6] | [DEBUG] [09/01/2020 06:12:59.472] [ScalaTest-main-running-DDataClusterShardingWithEntityRecoveryMultiJvmNode6] [WithLogCapturing(akka://DDataClusterShardingWithEntityRecoverySpec)] Logging finished for test [Persistent Cluster Shards must permanently stop entities which passivate (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6)]
[info] [JVM-6] <-- [Persistent Cluster Shards must permanently stop entities which passivate (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6)] End of log messages of test that [Failed(java.lang.RuntimeException: barrier failed: cluster-started-12)]
[info] [JVM-1] - must restart entities which stop without passivating (on node 'controller', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: cluster-started-12
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-1]   at akka.actor.FSM.processEvent(FSM.scala:804)
[info] [JVM-1]   at akka.actor.FSM.processEvent$(FSM.scala:801)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent(FSM.scala:944)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
[info] [JVM-1]   ...
[info] [JVM-6] - must permanently stop entities which passivate (on node 'fifth', class akka.cluster.sharding.DDataClusterShardingWithEntityRecoveryMultiJvmNode6) *** FAILED ***
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8107

**Comment by octonato** [comment]
For the record:

I've found this strange logs:
(logs truncated to easy reading)

```
[DEBUG] [10/12/2020 03:40:40.126] [dispatcher-4] [akka://DDataClusterShardingWithEntityRecoverySpec@localhost:41263/user/RememberCounterEntitiesRegion/1] RememberCounterEntities: Shard [1] shutting down[0m
...
[WARN] [10/12/2020 03:40:40.127]  [dispatcher-4] [akka://DDataClusterShardingWithEntityRecoverySpec/user/RememberCounterEntitiesRegion/1] Get(13)[0m
```

at 40.126 we see logging from Shard's `postStop`. 

at 40.127, when the shard is supposed to be gone, we a WARN log with only message `Get(13)` using the what seems to be the shard logger. 

While investigating https://github.com/akka/akka/issues/29269, I suspected that the `Get(13)` message were being lost some how. 

This reinforces the suspicion.

**Comment by patriknw** [comment]
@octonato It's indeed strange that the warn logging is just the `Get(13)`. It must be some kind of dropped/dead message.

Anyway, looking at the test again I see that the problem is that it is assumed that `persistentEntitiesRegion` has the right information at this point:
```
persistentEntitiesRegion ! Get(13)
```

I don't think that's always the case, and there is soo much "fake" in this test.

I would try to place that in an awaitAssert
```
        persistentEntitiesRegion ! Get(13)
        expectMsg(0)
```
