### ISSUE TITLE
FlowFutureFlowSpec: must handle closed downstream when flow future is late completed

### ISSUE THREAD

**Issue by raboof** [akka/akka#29535]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7979/consoleFull

```
[info] a futureFlow with akka.stream.Attributes$NestedMaterializationCancellationPolicy@7b34e99f
...
[info] - must handle closed downstream when flow future is late completed *** FAILED *** (2 seconds, 31 milliseconds)
[info]   Some(Success(Vector())) was not empty (FlowFutureFlowSpec.scala:273)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6834)
[info]   at akka.stream.scaladsl.FlowFutureFlowSpec.$anonfun$new$28(FlowFutureFlowSpec.scala:273)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.FlowFutureFlowSpec.$anonfun$new$27(FlowFutureFlowSpec.scala:259)
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7986/
