### ISSUE TITLE
Failed: akka.persistence.LeveldbPersistentActorWithRuntimePluginConfigSpec.A persistent actor must reply to the original sender() of a command, even when using persistAsync

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29563]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8000/testReport/junit/akka.persistence/LeveldbPersistentActorWithRuntimePluginConfigSpec/A_persistent_actor_must_reply_to_the_original_sender___of_a_command__even_when_using_persistAsync/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: block took 3.199 seconds, exceeding 3.000 seconds
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.within(TestKit.scala:422)
	at akka.testkit.TestKitBase.within$(TestKit.scala:404)
	at akka.testkit.TestKit.within(TestKit.scala:969)
	at akka.testkit.TestKitBase.within(TestKit.scala:431)
	at akka.testkit.TestKitBase.within$(TestKit.scala:431)
	at akka.testkit.TestKit.within(TestKit.scala:969)
	at akka.persistence.PersistentActorSpec.$anonfun$new$33(PersistentActorSpec.scala:1446)
```

**Comment by johanandren** [comment]
Might be the same ci server slow disk problem as #29196

**Comment by patriknw** [comment]
Closing as old
