### ISSUE TITLE
Failed: jdocs.discovery.DnsDiscoveryDocTest.dnsDiscoveryShouldResolveAkkaIo

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29562]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/7997/testReport/junit/jdocs.discovery/DnsDiscoveryDocTest/dnsDiscoveryShouldResolveAkkaIo/

```
sbt.ForkMain$ForkError: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.package$.blocking(package.scala:146)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
	at jdocs.discovery.DnsDiscoveryDocTest.dnsDiscoveryShouldResolveAkkaIo(DnsDiscoveryDocTest.java:51)
```

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8039/testReport/junit/jdocs.discovery/DnsDiscoveryDocTest/dnsDiscoveryShouldResolveAkkaIo/

**Comment by jrudolph** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8116/

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/4755754480?check_suite_focus=true
