### ISSUE TITLE
Failed: ReplicatedShardingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#29674]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/668/console

```
 The code passed to eventually never returned normally. Attempted 19 times over 10.32073456 seconds. Last failure message: Set("from first to R1") did not equal Set("from first to R1", "from first to R2"). (ReplicatedShardingSpec.scala:160)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  org.scalatest.exceptions.TestFailedDueToTimeoutException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:185)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:192)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:402)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:401)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.typed.ReplicatedShardingSpec.eventually(ReplicatedShardingSpec.scala:114)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.typed.ReplicatedShardingSpec.$anonfun$new$9(ReplicatedShardingSpec.scala:160)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.typed.ReplicatedShardingSpec.$anonfun$new$4(ReplicatedShardingSpec.scala:160)[0m[0m
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4230/consoleText
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7930/consoleText
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7931/consoleText
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/7932/consoleText
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8058/consoleText
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8059/consoleText
etc
