### ISSUE TITLE
[failure] Rolling upgrade 2.6.9+56-90dac8dc

### ISSUE THREAD

**Issue by ennru** [akka/akka#29706]
```
RollingUpgradeSpec:

Rolling upgrade
- should upgrade to version 2.6.5+106-33d64f9d *** FAILED ***
  java.lang.RuntimeException: Nonzero exit value: 1
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:161)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:118)
  at RollingUpgradeSpec.$anonfun$printLogs$3(RollingUpgradeSpec.scala:155)
  at scala.collection.immutable.List.map(List.scala:223)
  at RollingUpgradeSpec.printLogs(RollingUpgradeSpec.scala:155)
  at RollingUpgradeSpec.$anonfun$new$5(RollingUpgradeSpec.scala:240)
```

https://travis-ci.com/github/akka/akka-upgrade-testing/builds/169444191#L1322

**Comment by octonato** [comment]
I guess this one can be closed already. It was an update from 2.6.5 to 2.6.5+106-33d64f9d
