### ISSUE TITLE
RandomizedSplitBrainResolverIntegrationSpec: Scenario(lease-majority, 3)

### ISSUE THREAD

**Issue by raboof** [akka/akka#29718]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8096/consoleFull
```
[info] [JVM-1] - must Scenario(lease-majority, 3) (on node 'node1', class akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpecMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(DoubleRegister(/system/sharding/Entity-1/1/1-default,trying to register akka://RandomizedSplitBrainResolverIntegrationSpec-1@localhost:42701, but akka://RandomizedSplitBrainResolverIntegrationSpec-1@localhost:37725 was already registered for /system/sharding/Entity-1/1/1-default),Actor[akka://RandomizedSplitBrainResolverIntegrationSpec/user/shardingRegistry-1#-1155572375]) after 0 millis
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:767)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:731)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:730)
[info] [JVM-1]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$25(RandomizedBrainResolverIntegrationSpec.scala:356)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-1]   at akka.cluster.sbr.RandomizedSplitBrainResolverIntegrationSpec$DisposableSys.$anonfun$verify$4(RandomizedBrainResolverIntegrationSpec.scala:353)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

**Comment by patriknw** [comment]
This is probably same as https://github.com/akka/akka/issues/29565, so I'm adding there and closing this.
