### ISSUE TITLE
Failed: RemoteReDeploymentMultiJvmSpec must terminate the child when its parent system is replaced by a new one (on node 'first', class akka.remote.ArteryRemoteReDeploymentSlowMultiJvmNode1)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka#29746]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8114/consoleFull

```
[info] [JVM-1] - must terminate the child when its parent system is replaced by a new one (on node 'first', class akka.remote.ArteryRemoteReDeploymentSlowMultiJvmNode1) *** FAILED *** (13 seconds, 779 milliseconds)
[info] [JVM-1]   java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
[info] [JVM-1]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info] [JVM-1]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
[info] [JVM-1]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:220)
[info] [JVM-1]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info] [JVM-1]   at scala.concurrent.Await$.result(package.scala:146)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec$AwaitHelper.await(MultiNodeSpec.scala:298)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.node(MultiNodeSpec.scala:411)
[info] [JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec.$anonfun$new$7(RemoteReDeploymentSpec.scala:157)
[info] [JVM-1]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)
[info] [JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)
[info] [JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec.$anonfun$new$5(RemoteReDeploymentSpec.scala:157)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-1]   at akka.remote.RemoteReDeploymentMultiJvmSpec.$anonfun$new$2(RemoteReDeploymentSpec.scala:148)
```

**Comment by patriknw** [comment]
Closing as old
