### ISSUE TITLE
Fail: LeaseMajority5NodeSpecMultiJvm - should keep the side that can acquire the lease

### ISSUE THREAD

**Issue by octonato** [akka/akka#29775]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8143/consoleText

```scala
[info] [JVM-5] - should keep the side that can acquire the lease (on node 'node5', class akka.cluster.sbr.LeaseMajority5NodeSpecMultiJvmNode5) *** FAILED *** (19 seconds, 963 milliseconds)
[info] [JVM-5]   false did not equal true (LeaseMajority5NodeSpec.scala:140)
[info] [JVM-5]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-5]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info] [JVM-5]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info] [JVM-5]   at akka.cluster.sbr.LeaseMajority5NodeSpec.$anonfun$new$20(LeaseMajority5NodeSpec.scala:140)
[info] [JVM-5]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)
[info] [JVM-5]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)
[info] [JVM-5]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)
[info] [JVM-5]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)
```

Other nodes failed on barried.
```scala
[info] [JVM-1] - should keep the side that can acquire the lease (on node 'node1', class akka.cluster.sbr.LeaseMajority5NodeSpecMultiJvmNode1) *** FAILED *** (26 seconds, 301 milliseconds)
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: downed-and-removed
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)

```

**Comment by chbatey** [comment]
The correct decision was made by both sides of the split, it jus ttimed out waiting for all the nodes on the minor side to shut down.

I'll tune the settings to get it to happen quicker rather than increase the timeout
