### ISSUE TITLE
Failed: LeaseMajoritySpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29786]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8163/console

```
should keep the side that can acquire the lease (on node 'node4', class akka.cluster.sbr.LeaseMajority5NodeSpecMultiJvmNode4) *** FAILED *** (20 seconds, 31 milliseconds)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  false did not equal true (LeaseMajority5NodeSpec.scala:140)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  org.scalatest.exceptions.TestFailedException:ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.cluster.sbr.LeaseMajority5NodeSpec.$anonfun$new$20(LeaseMajority5NodeSpec.scala:140)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:3
```

**Comment by chbatey** [comment]
Duplicate of https://github.com/akka/akka/issues/29775
