### ISSUE TITLE
Failed: PersistentClusterShardingWithEntityRecoverySpec, java.lang.RuntimeException: barrier failed: entities-started

### ISSUE THREAD

**Issue by seglo** [akka/akka#29782]
```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m- must ensure rebalance restarts shards (on node 'third', class akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode4) *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  java.lang.RuntimeException: barrier failed: entities-started[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.actor.FSM.processEvent(FSM.scala:804)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.actor.FSM.processEvent$(FSM.scala:801)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.actor.LoggingFSM.processEvent(FSM.scala:944)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.actor.LoggingFSM.processEvent$(FSM.scala:926)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-4[0m] [31m  ...[0m[0m
```

```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m*** 5 TESTS FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] Heap[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]  PSYoungGen      total 141824K, used 20386K [0x00000000f5580000, 0x0000000100000000, 0x0000000100000000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]   eden space 131072K, 7% used [0x00000000f5580000,0x00000000f5eef410,0x00000000fd580000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]   from space 10752K, 99% used [0x00000000fd580000,0x00000000fdff9440,0x00000000fe000000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]   to   space 10752K, 0% used [0x00000000ff580000,0x00000000ff580000,0x0000000100000000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]  ParOldGen       total 175104K, used 19366K [0x00000000e0000000, 0x00000000eab00000, 0x00000000f5580000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]   object space 175104K, 11% used [0x00000000e0000000,0x00000000e12e9bb8,0x00000000eab00000)[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]  Metaspace       used 51956K, capacity 57492K, committed 57728K, reserved 1099776K[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m]   class space    used 7091K, capacity 7492K, committed 7552K, reserved 1048576K[0m
[0m[[0m[31merror[0m] [0m[0mFailed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode1[0m
[0m[[0m[31merror[0m] [0m[0mFailed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode4[0m
[0m[[0m[31merror[0m] [0m[0mFailed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode5[0m
[0m[[0m[31merror[0m] [0m[0mFailed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode6[0m
[0m[[0m[31merror[0m] [0m[0mFailed: akka.cluster.sharding.PersistentClusterShardingWithEntityRecoveryMultiJvmNode7[0m
```

https://jenkins.akka.io:8498/job/akka-multi-node/4269/consoleText

**Comment by seglo** [comment]
This time on akka-nightly

https://jenkins.akka.io:8498/job/akka-nightly-2.13/699/consoleText

**Comment by octonato** [comment]
Should have been fixed in https://github.com/akka/akka/pull/29773

**Comment by octonato** [comment]
Hmm, re-opening it. 
Not exactly the same failure as in #29773, but the fix may be similar.
