### ISSUE TITLE
Failed: PersistentClusterShardingSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29785]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/703/

```
 must recover entities upon restart (on node 'third', class akka.cluster.sharding.PersistentClusterShardingMultiJvmNode4) *** FAILED ***ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  java.lang.AssertionError: assertion failed: timeout (49124790443 nanoseconds) during expectMsg while waiting for 0ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at scala.Predef$.assert(Predef.scala:282)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-5ESC[0m] | [DEBUG] [10/30/2020 22:23:17.167] [PersistentClusterShardingSpec-akka.actor.internal-dispatcher-29] [ArteryTcpTransport(akka://PersistentClusterShardingSpec)] Incoming ActorRef compression advertisement from [akka://PersistentClusterShardingSpec@localhost:45689#6867232988408635262], table: [CompressionTable(4030114885230593546,1,HashMap(Actor[akka://PersistentClusterShardingSpec@localhost:45689/system/cluster/core/daemon#1638976139] -> 1, Actor[akka://PersistentClusterShardingSpec@localhost:45689/system/testProbe-3#-2056159488] -> 3, Actor[akka://PersistentClusterShardingSpec/user/counterRegion/4/4#1066614925] -> 0, Actor[akka://PersistentClusterShardingSpec@localhost:45689/] -> 2, Actor[akka://PersistentClusterShardingSpec/system/cluster/core/daemon#216385449] -> 4))]ESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-1ESC[0m] | [DEBUG] [10/30/2020 22:23:17.063] [PersistentClusterShardingSpec-akka.actor.internal-dispatcher-18] [akka://PersistentClusterShardingSpec@localhost:33385/system/IO-TCP/selectors/$a/25] Resolving localhost before connectingESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKit.expectMsg(TestKit.scala:969)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$68(ClusterShardingSpec.scala:791)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.cluster.sharding.ClusterShardingSpec.$anonfun$new$66(ClusterShardingSpec.scala:769)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-5ESC[0m] | [DEBUG] [10/30/2020 22:23:17.270] [PersistentClusterShardingSpec-akka.actor.internal-dispatcher-16] [ArteryTcpTransport(akka://PersistentClusterShardingSpec)] Incoming Class Manifest compression advertisement from [akka://PersistentClusterShardingSpec@localhost:43429#-2874874742707754523], table: [CompressionTable(4030114885230593546,1,HashMap(BK -> 4, BI -> 3, GE -> 0, d -> 5, BG -> 2, BD -> 1))]ESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  at akka.testkit.TestKitBase.within(TestKit.scala:416)ESC[0mESC[0m
ESC[0m[ESC[0mESC[0minfoESC[0m] ESC[0mESC[0m[ESC[34mJVM-4ESC[0m] ESC[31m  ...ESC[0mESC[0m
```

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2523/consoleFull

**Comment by chbatey** [comment]
Duplicate of https://github.com/akka/akka/issues/29782 even tho it is a different spec they both extend the same base spec and is at the same line
