### ISSUE TITLE
Failed: EventSourcedBehaviorRetentionSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29787]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8167/testReport/junit/akka.persistence.typed.scaladsl/EventSourcedBehaviorRetentionSpec/EventSourcedBehavior_with_retention_must_snapshot_every_N_sequence_nrs/

```
Error Message
java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for State(1,Vector(0))
Stacktrace
sbt.ForkMain$ForkError: java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for State(1,Vector(0))
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:387)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:166)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:144)
	at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.$anonfun$new$2(EventSourcedBehaviorRetentionSpec.scala:150)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by johanandren** [comment]
I think this was leveldb recovery taking close to 3 seconds leading to the expectMesage timing out:

```
2020-11-01 03:51:04,063 [DEBUG] [akka.actor.typed.Behavior$] [] [akka://EventSourcedBehaviorRetentionSpec/user/$a] [replay-evt] [c1)] - Recovery for persistenceId [PersistenceId(c1))] took 2.843 s 
2020-11-01 03:51:04,064 [DEBUG] [akka.actor.typed.Behavior$] [] [akka://EventSourcedBehaviorRetentionSpec/user/$a] [running-cmd] [c1)] - Handled command [akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$Increment$], resulting effect: [Persist(Incremented(1))], side effects: [0] 
```

Looks like other `PerformanceSpec` test were also failing, and that uses the leveldb journal as well.

Perhaps related to #29196 ?
