### ISSUE TITLE
Issue with uppercase shard type names when using kubernetes lease 

### ISSUE THREAD

**Issue by nathanleyton** [akka/akka#29837]
Hi 

We are facing an error when using kubernetes lease for cluster sharding. Our shard type names have upper case chars and we get the following error:-

StackTrace
akka.coordination.lease.LeaseException: Unexpected response from API server when creating Lease StatusCode: 422 Unprocessable Entity. Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Lease.akka.io \"hubbub-shard-NumberUniquenessChecker--501\" is invalid: metadata.name: Invalid value: \"hubbub-shard-NumberUniquenessChecker--501\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"hubbub-shard-NumberUniquenessChecker--501","group":"akka.io","kind":"Lease","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"hubbub-shard-NumberUniquenessChecker--501\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}

	at akka.coordination.lease.kubernetes.internal.KubernetesApiImpl.$anonfun$createLeaseResource$6(KubernetesApiImpl.scala:291)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at akka.coordination.lease.kubernetes.internal.KubernetesApiImpl.$anonfun$createLeaseResource$3(KubernetesApiImpl.scala:288)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at akka.coordination.lease.kubernetes.internal.KubernetesApiImpl.$anonfun$createLeaseResource$2(KubernetesApiImpl.scala:272)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by nathanleyton** [comment]
Perhaps forcing to lowercase before creating / querying in the kubernetes api would do it?
