### ISSUE TITLE
Failed: BoundedSourceQueueSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka#29859]
```
Error Message
org.scalatest.exceptions.TestFailedException: 7756479321617 was not equal to 7754188971150
Stacktrace
sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: 7756479321617 was not equal to 7754188971150
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
	at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
	at akka.stream.scaladsl.BoundedSourceQueueSpec.$anonfun$new$21(BoundedSourceQueueSpec.scala:169)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
```

https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8266/testReport/junit/akka.stream.scaladsl/BoundedSourceQueueSpec/BoundedSourceQueue_should_without_cancellation_only_flag_elements_as_enqueued_that_will_also_be_passed_to_downstream/

**Comment by johanandren** [comment]
I wonder if there isn't a race condition in the BoundedSourceQueue causing this failure. Looking at the logs not a single element is marked as dropped. 

The scenario I'm thinking about:

```
1. thread1 calls offer, state is Running
2. thread2 calls complete, state becomes Done
3. stage picks up done, queue is empty, so completes
3. thread1 appends e1 to queue because it thinks it is running
4. thread1 sees state is not NeedsActivation and returns Enqueued

e1 is now lost
```

Isn't there a need for a completed/failed state that is only switched to once the stage stops/fails so that the enqueueing can notice?

**Comment by johanandren** [comment]
Given that, as documented on `offer`: `A result of `QueueOfferResult.Enqueued` does not guarantee that an element also has been or will be processed by the downstream.` the test is actually setting too high expectations that all elements that were Enqueued were emitted.

Gut feeling with a completion coming from the queue side is still that it could somehow notice that the stage stopped after enqueueing an element, especially since it already reads the state. Not quite sure how to achieve it yet though. Adding a stopped state just moves the race condition to be about enqueue + read instead of read + enqueue.

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/741/testReport/junit/akka.stream.scaladsl/BoundedSourceQueueSpec/BoundedSourceQueue_should_without_cancellation_only_flag_elements_as_enqueued_that_will_also_be_passed_to_downstream/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/754/testReport/junit/akka.stream.scaladsl/BoundedSourceQueueSpec/BoundedSourceQueue_should_without_cancellation_only_flag_elements_as_enqueued_that_will_also_be_passed_to_downstream/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/21312/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8401/testReport/junit/akka.stream.scaladsl/BoundedSourceQueueSpec/BoundedSourceQueue_should_without_cancellation_only_flag_elements_as_enqueued_that_will_also_be_passed_to_downstream/

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/785/

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/788/testReport/junit/akka.stream.scaladsl/BoundedSourceQueueSpec/BoundedSourceQueue_should_without_cancellation_only_flag_elements_as_enqueued_that_will_also_be_passed_to_downstream/

(following build, aka build number 789, passed)

**Comment by octonato** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-2.13/799/

```scala
 - should without cancellation only flag elements as enqueued that will also be passed to downstream *** FAILED *** (82 milliseconds)                           │
   2415654211160 was not equal to 2422371741074 (BoundedSourceQueueSpec.scala:169)                                                                              │
   org.scalatest.exceptions.TestFailedException:                                                                                                                │
   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)                                                                          │
   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)                                                         │
   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)                                                                       │
   at akka.stream.scaladsl.BoundedSourceQueueSpec.$anonfun$new$21(BoundedSourceQueueSpec.scala:169)                                                             │
   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```
