### ISSUE TITLE
DownAllUnstable5: down all when instability continues

### ISSUE THREAD

**Issue by raboof** [akka/akka#29895]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/597/consoleFull

```
[info] [JVM-1] - should down all when instability continues (on node 'node1', class akka.cluster.sbr.DownAllUnstable5NodeSpecMultiJvmNode1) *** FAILED *** (33 seconds, 72 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout 15 seconds expired:
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:223)
[info] [JVM-1]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:298)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:304)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:287)
[info] [JVM-1]   at akka.testkit.TestKit.awaitCond(TestKit.scala:969)
[info] [JVM-1]   at akka.cluster.sbr.DownAllUnstable5NodeSpec.$anonfun$new$2(DownAllUnstable5NodeSpec.scala:126)
```

**Comment by patriknw** [comment]
Closing as old

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5594472080/job/15153566774#step:10:24297

```scala
info] [JVM-3] - should down all when instability continues (on node 'node3', class akka.cluster.sbr.DownAllUnstable5NodeSpecMultiJvmNode3) *** FAILED *** (1 minute, 1 second)
[info] [JVM-3]   java.lang.AssertionError: assertion failed: timeout 30 seconds expired:
[info] [JVM-3]   at scala.Predef$.assert(Predef.scala:279)
[info] [JVM-3]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:299)
[info] [JVM-3]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:305)
[info] [JVM-3]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:288)
[info] [JVM-3]   at akka.testkit.TestKit.awaitCond(TestKit.scala:955)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9057019166/job/24880380958#step:10:20741
