### ISSUE TITLE
BehaviorTestKit's returned messageAdapter ref is unusable

### ISSUE THREAD

**Issue by eyalfa** [akka/akka#29891]
when testing a behaviour that exposes a message adapter, the adapter's ref fails when attempted to be used.

I've slightly modified the `BehaviorTestKitSpec`'s `Parent` protocol such that `CreateMessageAdapter` optionally returns the created adapter:
```
case class CreateMessageAdapter[U](messageClass: Class[U], f: U => Command, replyTo : Option[ActorRef[ActorRef[U]]] = None) extends Command
```

I've added the following test which fails when attempting to send a message to the tested behaviour via the message adapter:

```
"create message adapter and receive messages via the newly created adapter" in {
      val testkit = BehaviorTestKit[Parent.Command](Parent.init)
      val replyTo = TestInbox[ActorRef[Int]]("replyTo")
      testkit.run(CreateMessageAdapter(classOf[Int], SpawnChildren.apply, Some(replyTo.ref)))
      testkit.expectEffectType[MessageAdapter[String, Command]]
      val adaptorRef = replyTo.receiveMessage()
      adaptorRef ! 2
      testkit.selfInbox().hasMessages should be (true)
      testkit.runOne() //this line fails
      testkit.expectEffectPF{
        case Spawned(_, childName, _) => childName should equal ("child1")
      }
      testkit.expectEffectPF{
        case Spawned(_, childName, _) => childName should equal ("child2")
      }
    }
```

this code fails with a `ClassCastException`:

```
class akka.actor.typed.internal.AdaptWithRegisteredMessageAdapter cannot be cast to class akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec$Parent$Command (akka.actor.typed.internal.AdaptWithRegisteredMessageAdapter and akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec$Parent$Command are in unnamed module of loader 'app')
java.lang.ClassCastException: class akka.actor.typed.internal.AdaptWithRegisteredMessageAdapter cannot be cast to class akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec$Parent$Command (akka.actor.typed.internal.AdaptWithRegisteredMessageAdapter and akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec$Parent$Command are in unnamed module of loader 'app')
	at akka.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:136)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.testkit.typed.internal.BehaviorTestKitImpl.run(BehaviorTestKitImpl.scala:135)
	at akka.actor.testkit.typed.internal.BehaviorTestKitImpl.runOne(BehaviorTestKitImpl.scala:144)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec.$anonfun$new$25(BehaviorTestKitSpec.scala:285)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
	at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec.withFixture(BehaviorTestKitSpec.scala:139)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec.org$scalatest$BeforeAndAfterAll$$super$run(BehaviorTestKitSpec.scala:139)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.actor.testkit.typed.scaladsl.BehaviorTestKitSpec.run(BehaviorTestKitSpec.scala:139)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:41)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

it seems`akka.actor.testkit.typed.internal.StubbedActorContext#internalSpawnMessageAdapter` is not expecting the unsafe cast performed by `akka.actor.typed.internal.ActorContextImpl#internalMessageAdapter` which mascarades a `AdaptWithRegisteredMessageAdapter[Any]` as a `T`. 
a deeper look suggests that unlike the adapting context impl, the stubbed impl hands the `AdaptWithRegisteredMessageAdapter` message directly to the current behaviour  without the adapter's `aroundReceive` handling which intercepts these (and other) messages in the adapting implementation.

**Comment by johanandren** [comment]
Would you be up for taking a stab at fixing this @eyalfa ?

**Comment by eyalfa** [comment]
@johanandren , sure I'll try

**Comment by Gaurav-Deshkar** [comment]
@eyalfa  @johanandren I am sort of facing the same issue. I observed the fix you have put work fine  for `testkit.runOne()` but when I try to do `testKit.selfInbox().receiveMessage()` it still throws same exception. 

so the modified test case might look as follow
`    

      "create message adapter and receive messages via the newly created adapter" in {     
           val testkit = BehaviorTestKit[Parent.Command](Parent.init)
           val replyTo = TestInbox[ActorRef[Int]]("replyTo")
           testkit.run(CreateMessageAdapter(classOf[Int], SpawnChildren.apply, Some(replyTo.ref)))
           testkit.expectEffectType[MessageAdapter[String, Command]]
           val adaptorRef = replyTo.receiveMessage()
           adaptorRef ! 2
           testkit.selfInbox().hasMessages should be (true)
          val msg = testKit.selfInbox().receiveMessage() //this line fails
       
    }`
