### ISSUE TITLE
SplitBrainResolverIntegrationSpec suite aborted, timeout

### ISSUE THREAD

**Issue by seglo** [akka/akka#29936]
```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31mSUITE ABORTED - SplitBrainResolverIntegrationSpecMultiJvmNode7: Failed to stop [SplitBrainResolverIntegrationSpec-2] within [10 seconds] [0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m-> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 8 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-6 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-7 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 1 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   |   ⌊-> remote-20-0-unnamed RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-8 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> eventStreamUnsubscriber-3 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> testProbe-6 RepointableActorRef class akka.testkit.TestActor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  java.lang.RuntimeException: Failed to stop [SplitBrainResolverIntegrationSpec-2] within [10 seconds] [0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m-> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 8 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-6 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-7 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 1 children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   |   ⌊-> remote-20-0-unnamed RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       |   ⌊-> StreamSupervisor-8 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> eventStreamUnsubscriber-3 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m       ⌊-> testProbe-6 RepointableActorRef class akka.testkit.TestActor status=0 no children[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.testkit.TestKit$.shutdownActorSystem(TestKit.scala:1026)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.cluster.sbr.SplitBrainResolverIntegrationSpec$DisposableSys.shutdownSys(SplitBrainResolverIntegrationSpec.scala:157)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at akka.cluster.sbr.SplitBrainResolverIntegrationSpec.afterEach(SplitBrainResolverIntegrationSpec.scala:97)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.BeforeAndAfterEach.$anonfun$runTest$1(BeforeAndAfterEach.scala:247)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.SucceededStatus$.whenCompleted(Status.scala:462)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.Status.withAfterEffect(Status.scala:373)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.Status.withAfterEffect$(Status.scala:371)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  at org.scalatest.SucceededStatus$.withAfterEffect(Status.scala:434)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m  ...[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-9[0m] [36mRun completed in 8 minutes, 20 seconds.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-9[0m] [36mTotal number of tests run: 15[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-9[0m] [36mSuites: completed 1, aborted 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-9[0m] [36mTests: succeeded 15, failed 0, canceled 0, ignored 0, pending 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-9[0m] [32mAll tests passed.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [36mRun completed in 8 minutes, 20 seconds.[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [36mTotal number of tests run: 15[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [36mSuites: completed 0, aborted 1[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [36mTests: succeeded 15, failed 0, canceled 0, ignored 0, pending 0[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-7[0m] [31m*** 1 SUITE ABORTED ***[0m[0m
```
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2589/

**Comment by johanandren** [comment]
Actually several multinode tests failing with the same shutdown timeout of 15s:

`ClusterConsistentHashingRouter`, `ClusterRoundRobin`, `ClusterSingletonLeaseSpec`, `SplitBrainResolverIntegrationSpec`, `ClassicClusterRemoteFeatures`, `UseRoleIgnored` and `ArteryClusterRemoteFeatures`

So something making node shutdown really slow that one run. Perhaps not worth investigating more until/unless it happens again.

**Comment by pvlugter** [comment]
Seen again in https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2750/

**Comment by patriknw** [comment]
closing as old
