### ISSUE TITLE
[failed] SplitBrainQuarantine

### ISSUE THREAD

**Issue by octonato** [akka/akka#29998]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2613/

```scala
 - must split brain (on node 'second', class akka.cluster.SplitBrainQuarantineMultiJvmNode2) *** FAILED *** (14 seconds, 967 milliseconds)              
   TreeSet() did not equal Set(akka://SplitBrainQuarantine@a4.moxie:59238, akka://SplitBrainQuarantine@a5.moxie:60890) (SplitBrainQuarantineSpec.scala:8
   org.scalatest.exceptions.TestFailedException:                                                                                                        
   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)                                                                  
   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)                                                               
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$8(SplitBrainQuarantineSpec.scala:81)                                                           
   at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)                                                                                                
   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)                                                                                           
   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)                                                                                          
   at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)                                                                                               
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$7(SplitBrainQuarantineSpec.scala:80)                                                           
   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)                                                                                  
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$5(SplitBrainQuarantineSpec.scala:79)   
 - must split brain (on node 'first', class akka.cluster.SplitBrainQuarantineMultiJvmNode1) *** FAILED *** (15 seconds, 43 milliseconds)                
   TreeSet() did not equal Set(akka://SplitBrainQuarantine@a4.moxie:59238, akka://SplitBrainQuarantine@a5.moxie:60890) (SplitBrainQuarantineSpec.scala:8
   org.scalatest.exceptions.TestFailedException:                                                                                                        
   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)                                                                  
   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)                                                               
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$8(SplitBrainQuarantineSpec.scala:81)                                                           
   at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)                                                                                                
   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)                                                                                           
   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)                                                                                          
   at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)                                                                                               
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$7(SplitBrainQuarantineSpec.scala:80)                                                           
   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)                                                                                  
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$5(SplitBrainQuarantineSpec.scala:79)                                                           
   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)                                                                            
   at akka.testkit.TestKitBase.within(TestKit.scala:416)                                                                                                
   at akka.testkit.TestKitBase.within$(TestKit.scala:404)                                                                                               
   at akka.testkit.TestKit.within(TestKit.scala:969)                                                                                                    
   at akka.testkit.TestKitBase.within(TestKit.scala:431)                                                                                                
   at akka.testkit.TestKitBase.within$(TestKit.scala:431)                                                                                               
   at akka.testkit.TestKit.within(TestKit.scala:969)                                                                                                    
   at akka.cluster.SplitBrainQuarantineSpec.$anonfun$new$3(SplitBrainQuarantineSpec.scala:74)   
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8470

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2633/consoleText

**Comment by johanandren** [comment]
Note that we still have not fixed #29963 so this is likely that 

(this is present in the last failure at least):
```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [DEBUG] [02/19/2021 09:33:08.530] [SplitBrainQuarantine-akka.remote.default-remote-dispatcher-11] [InboundTestStage$$anon$2(akka://SplitBrainQuarantine)] inbound message [ActorSelectionMessage(akka.cluster.GossipEnvelope)] before handshake completed, cannot check if remote is blackholed, letting through[0m
```

**Comment by ignasi35** [comment]
Again https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8557/console

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/(legacy)%20akka-multi-node-repeat-johan/1320/consoleText
