### ISSUE TITLE
[failed] Unrecognized VM option 'PrintGCTimeStamps' (Scala3 build)

### ISSUE THREAD

**Issue by octonato** [akka/akka#30000]
https://jenkins.akka.io:8498/job/akka-nightly-scala3/1/console

```scala
Unrecognized VM option 'PrintGCTimeStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[error] Could not accept connection from test agent: class java.net.SocketException: Socket closed
[error] java.net.SocketException: Socket closed
[error] 	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
[error] 	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
[error] 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:551)
[error] 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:519)
[error] 	at sbt.ForkTests$Acceptor$1$.run(ForkTests.scala:84)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by johanandren** [comment]
Sorry, that is from me setting it up, I thought I deleted all mails to akka official but must have missed this fail.
