### ISSUE TITLE
failed: PersistentShardingMigrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30009]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8461/testReport/junit/akka.cluster.sharding/PersistentShardingMigrationSpec/Migration_should_allow_migration_of_remembered_shards_and_not_allow_going_back/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ack
	at scala.Predef$.assert(Predef.scala:223)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:971)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3(PersistentShardingMigrationSpec.scala:116)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3$adapted(PersistentShardingMigrationSpec.scala:113)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.withSystem$1(PersistentShardingMigrationSpec.scala:173)
	at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$2(PersistentShardingMigrationSpec.scala:113)
```

**Comment by johanandren** [comment]
Quite strange, it forms a one node cluster, waits for the region to be registered with the coordinator and sends three messages, waiting for an ack on each. But in this run, for some reason it looks as though it immediately triggered a graceful shutdown of the shard, after one region was observed, so that the requests are lost. Haven't been able to see any reason for that in the test logic, or think of some other explanation.

**Comment by patriknw** [comment]
Closing as old, and we haven't heard any migration problems
