### ISSUE TITLE
ScalaTestWithActorTestKit fails with AeronException "Address already in use"

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#30016]
I tried to override the port but it didn't help.
```scala
ScalaTestWithActorTestKit("""
    akka.persistence.testkit.events.serialize = off
    akka {
      remote {
          artery.enabled = on
          artery.transport = aeron-udp
          artery.canonical.port = 25551
          artery.canonical.hostname = "127.0.0.1"
      }
    }
    """)
```

With this config or not, I have the following error.

```
[2021-02-09 11:22:20,823] [ERROR] [akka.remote.artery.aeron.ArteryAeronUdpTransport] [] [my-app-akka.actor.default-dispatcher-4] - Aeron error: 1 observations from 02/09/2021 11:22:20.815 to 02/09/2021 11:22:20.815 for:
 io.aeron.exceptions.AeronException: ERROR - channel error - Address already in use (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=127.0.0.1:2552
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:167)
        at io.aeron.driver.media.ReceiveChannelEndpoint.openChannel(ReceiveChannelEndpoint.java:240)
        at io.aeron.driver.Receiver.onRegisterReceiveChannelEndpoint(Receiver.java:156)
        at io.aeron.driver.ReceiverProxy.lambda$registerReceiveChannelEndpoint$5(ReceiverProxy.java:126)
        at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:116)
        at io.aeron.driver.Receiver.doWork(Receiver.java:77)
        at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:814)
        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:785)
        at io.aeron.driver.media.UdpChannelTransport.openDatagramChannel(UdpChannelTransport.java:127)
        ... 9 more
 {akkaAddress=akka://my-app, sourceThread=pool-1-thread-1, akkaSource=ArteryAeronUdpTransport(akka://my-app), sourceActorSystem=my-app, akkaTimestamp=10:22:20.822UTC}
[2021-02-09 11:22:20,825] [ERROR] [akka.remote.artery.aeron.ArteryAeronUdpTransport] [] [my-app-akka.actor.default-dispatcher-4] - Aeron error, io.aeron.exceptions.ChannelEndpointException: ERROR - AeronException : ERROR - channel error - Address already in use (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=127.0.0.1:2552 {akkaAddress=akka://my-app, sourceThread=aeron-client-conductor, akkaSource=ArteryAeronUdpTransport(akka://my-app), sourceActorSystem=my-app, akkaTimestamp=10:22:20.823UTC}
io.aeron.exceptions.ChannelEndpointException: ERROR - AeronException : ERROR - channel error - Address already in use (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=127.0.0.1:2552
        at io.aeron.ClientConductor.onChannelEndpointError(ClientConductor.java:246)
        at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:109)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
        at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:68)
        at io.aeron.ClientConductor.service(ClientConductor.java:1071)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:192)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2021-02-09 11:22:20,826] [ERROR] [akka.remote.artery.aeron.ArteryAeronUdpTransport] [] [my-app-akka.actor.default-dispatcher-4] - Aeron error, io.aeron.exceptions.ChannelEndpointException: ERROR - AeronException : ERROR - channel error - Address already in use (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=127.0.0.1:2552 {akkaAddress=akka://my-app, sourceThread=aeron-client-conductor, akkaSource=ArteryAeronUdpTransport(akka://my-app), sourceActorSystem=my-app, akkaTimestamp=10:22:20.823UTC}
io.aeron.exceptions.ChannelEndpointException: ERROR - AeronException : ERROR - channel error - Address already in use (at java.base/sun.nio.ch.Net.bind0(Native Method)): aeron:udp?endpoint=127.0.0.1:2552
        at io.aeron.ClientConductor.onChannelEndpointError(ClientConductor.java:246)
        at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:109)
        at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
        at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:68)
        at io.aeron.ClientConductor.service(ClientConductor.java:1071)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:192)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by johanandren** [comment]
I'd guess that something else in your project setting the `akka.remote.artery.bind.port` to `2552`

**Comment by Zhen-hao** [comment]
I have it in `src/main/resources/application.conf`. will the test kit load that?

**Comment by johanandren** [comment]
It shouldn't, if you use it with no config it should pick upp `application-test.conf` and if you give it config it should use only that. You sure you are not starting some additional actorsystems in your tests picking up default config?

**Comment by Zhen-hao** [comment]
ah, now I know the cause. 

I added `implicit val system = ActorSystem("my-app")`  after a refactoring.
changing it to `implicit val system = testKit.internalSystem.toClassic` fixed it.

So `ActorSystem` always loads `src/main/resources/application.conf` even in tests?

**Comment by johanandren** [comment]
Yes, it can not "know" it runs in a test.
 
I'll close this issue. Please try to start in the forums for things that are more like questions in the future and we can create issues if it turns out there is an actual problem/bug/possible improvement in Akka.
