### ISSUE TITLE
ClusterSingleton does not work with KubernetesLease

### ISSUE THREAD

**Issue by danischroeter** [akka/akka#30024]
since ClusterSingletonManager uses his self.path in the lease name.

ClusterSingletonManager
```
  private val singletonLeaseName = s"${context.system.name}-singleton-${self.path}"

  override val log = Logging.withMarker(context.system, this)

  val lease: Option[Lease] = settings.leaseSettings.map(
    settings =>
      LeaseProvider(context.system)
        .getLease(singletonLeaseName, settings.leaseImplementation, cluster.selfAddress.hostPort))
```
I guess this should be `settings.singletonName`
I can create a pull request if my assumption is true...

```
akka.actor.InvalidActorNameException: Invalid actor path element [kubernetesLease5-im-singleton-akka://im/user/identityManager-singleton-im@10.52.105.235:9999], illegal character [/] at position: 35. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:100)
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:78)
	at akka.actor.dungeon.Children.checkName(Children.scala:250)
	at akka.actor.dungeon.Children.attachChild(Children.scala:52)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:51)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:410)
	at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:889)
	at akka.coordination.lease.kubernetes.KubernetesLease.<init>(KubernetesLease.scala:32)
	at akka.coordination.lease.kubernetes.KubernetesLease.<init>(KubernetesLease.scala:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
	at scala.util.Success.flatMap(Try.scala:258)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:102)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:69)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:59)
```

**Comment by danischroeter** [comment]
Shard seems fine in that regard:
```
  private val lease = settings.leaseSettings.map(
    ls =>
      LeaseProvider(context.system).getLease(
        s"${context.system.name}-shard-$typeName-$shardId",
        ls.leaseImplementation,
        Cluster(context.system).selfAddress.hostPort))
        ```

**Comment by johanandren** [comment]
Thanks for the report.

I guess we could either sanitize or just skip the `settings.leaseName` and possibly `settings.ownerName` in the actor path in `KubernetesLease`. Which by the way is a part of Akka Managemnet, I'll move the ticket over there.
