### ISSUE TITLE
Failed: ClusterShardingPreparingForShutdownSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30051]
New one in ClusterShardingPreparingForShutdownSpec:
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/664/consoleText

```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  self member: Member(akka.tcp://ClusterShardingPreparingForShutdownSpec@a6.moxie:35091, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$19(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue(Assertions.scala:1065)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue$(Assertions.scala:1052)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withClue(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$18(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
```

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8498/consoleText

**Comment by ignasi35** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/682/console

**Comment by chbatey** [comment]
https://mail.google.com/mail/u/2/#inbox/FMfcgxwLtGjJmFQspPFshSqNJlSjdFdB

**Comment by seglo** [comment]
```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m- must not rebalance but should still work preparing for shutdown (on node 'third', class akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownMultiJvmNode3) *** FAILED *** (23 seconds, 409 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  self member: Member(akka.tcp://ClusterShardingPreparingForShutdownSpec@a6.moxie:33335, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$19(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue(Assertions.scala:1065)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue$(Assertions.scala:1052)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withClue(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$18(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$3(ClusterShardingPreparingForShutdownSpec.scala:134)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withFixture(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.runTest(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.runTests(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Suite.run(Suite.scala:1112)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Suite.run$(Suite.scala:1094)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.org$scalatest$BeforeAndAfterAll$$super$run(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.run(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.collection.immutable.List.foreach(List.scala:333)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner$.main(Runner.scala:775)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.tools.Runner.main(Runner.scala)[0m[0m
```

https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/732/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2726

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2755/consoleText

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2755/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/821/consoleFull

**Comment by johanandren** [comment]
```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  self member: Member(akka://ClusterShardingPreparingForShutdownSpec@localhost:39157, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  org.scalatest.exceptions.TestFailedException:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$19(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue(Assertions.scala:1065)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at org.scalatest.Assertions.withClue$(Assertions.scala:1052)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withClue(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$18(ClusterShardingPreparingForShutdownSpec.scala:136)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$3(ClusterShardingPreparingForShutdownSpec.scala:134)[0m[0m
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4662924462?check_suite_focus=true#step:5:2276

**Comment by jrudolph** [comment]
This looks like a genuine bug in akka-cluster which seems to happen when in a two node cluster the node that currently is not the leader is issueing a `Leave(leader)` and then `Leave(itself)`. In that case, the issuing node doesn't seem to consider to move itself to `Exiting` after it has been become the new leader.

**Comment by jrudolph** [comment]
I replaced the leaving section in the test with

```
      runOn(first, third) {
        // run on node that is *not* the leader
        val isThisNodeLeader = cluster.state.leader.contains(cluster.selfMember.address)
        log.info(s"This node is the leader: $isThisNodeLeader")

        val thisAddress = cluster.selfMember.address
        val other =
          if (thisAddress == address(first)) address(third)
          else address(first)

        if (!isThisNodeLeader) {
          cluster.manager ! Leave(other)
          Thread.sleep(10)
          cluster.manager ! Leave(thisAddress)
        }
      }
```

to make the scenario more likely and it indeed failed once but not more than that yet...

**Comment by patriknw** [comment]
Isn't the test failure what I fixed in #31144 . Missing the final Removed status.

```
cluster.selfMember.status shouldEqual Removed
```

```
self member: Member(akka.tcp://ClusterShardingPreparingForShutdownSpec@localhost:41575, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)
```

**Comment by jrudolph** [comment]
Good point, but it seems there are also cases where shutdown is never run for the final node (I looked for "CoordinatedShutdown").

**Comment by pvlugter** [comment]
Just failed again: https://github.com/akka/akka/runs/5296714189?check_suite_focus=true#step:5:2250

```
[info] [JVM-3-ClusterShardingPreparingForShutdownMultiJvmNode3] - must not rebalance but should still work preparing for shutdown (on node 'third', class akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownMultiJvmNode3) *** FAILED *** (33 seconds, 725 milliseconds)
[info] [JVM-3-ClusterShardingPreparingForShutdownMultiJvmNode3]   self member: Member(akka.tcp://ClusterShardingPreparingForShutdownSpec@localhost:41587, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3247138784/jobs/5326726283

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3852058537/jobs/6563845246
