### ISSUE TITLE
Source.futureSource regression since 2.6.11: Error during postStop when downstream completes before Future

### ISSUE THREAD

**Issue by nktpro** [akka/akka#30071]
Since `2.6.11` release, there's a regression with `Source.futureSource` (or more specifically `FutureFlattenSource`) where an error will be thrown if downstream completes before the `Future[Source[T, M]]` completes. The error looks like this:

```
[ERROR] [...] [...] [akka://test/system/Materializers/StreamSupervisor-0/flow-0-0-ignoreSink] Error during postStop in [akka.stream.impl.fusing.GraphStages$FutureFlattenSource$$anon$7-futureFlattenSource]: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FutureFlattenSource.in) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
java.lang.IllegalStateException: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FutureFlattenSource.in) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
	at akka.stream.impl.fusing.SubSink.dispatchCommand(StreamOfStreams.scala:706)
	at akka.stream.impl.fusing.SubSink.cancelSubstream(StreamOfStreams.scala:689)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1476)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1472)
	at akka.stream.impl.fusing.GraphStages$FutureFlattenSource$$anon$7.postStop(GraphStages.scala:344)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:599)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:579)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:595)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:702)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:751)
	at akka.actor.Actor.aroundPreStart(Actor.scala:548)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.create(ActorCell.scala:641)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
```

Here's a minimum reproducer:

```scala
import akka.actor.ActorSystem
import akka.stream.scaladsl.Source

import scala.concurrent.Future
import scala.concurrent.duration._
import akka.pattern.after

object FutureSourceRegression {
  def main(args: Array[String]): Unit = {
    implicit val as: ActorSystem = ActorSystem("test")
    import as.dispatcher

    Source
      .futureSource(
        after(2.seconds)(Future.successful(Source(1 to 2)))
      )
      .merge(Source(3 to 4))
      .take(1)
      .runForeach(println)
      .onComplete(println)
  }
}
```

This is reproducible from `2.6.11` to latest `2.6.13`

**Comment by johanandren** [comment]
Thanks for reporting. 

Likely because of the substream auto cancel added in #29790 
I think could be as simple as removing the postStop since the subSink is automatically closed.

**Comment by nvollmar** [comment]
We've seen those showing up in the logs occasionally since about that release.

**Comment by rgugliel-da** [comment]
It seems that the issue is not solved by 2.6.15 (as mentioned by @francisdb  just above). Wondering this issue could be reopened ?

**Comment by raboof** [comment]
> It seems that the issue is not solved by 2.6.15 (as mentioned by @francisdb just above). Wondering this issue could be reopened ?

I just double-checked the reproducer above, and can confirm that it reproduced the problem with 2.6.14 and no longer shows the problem with 2.6.15.

I'd recommend opening a separate ticket for the problem you're seeing and linking it to this one, as it seems to be a separate-but-related problem. A reproducer would also be helpful ;)

**Comment by rgugliel-da** [comment]
Thanks for the reply! I'll see if I can extract a minimal example.

**Comment by aygalinc** [comment]
I observe the trace with 2.6.15 : https://github.com/akka/akka/issues/30322#issuecomment-891000983
