### ISSUE TITLE
[failed] AllPersistenceIdsSpec.Leveldb query AllPersistenceIds must find new persistenceIds

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30087]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8546/testReport/junit/akka.persistence.query.journal.leveldb/AllPersistenceIdsSpec/Leveldb_query_AllPersistenceIds_must_find_new_persistenceIds/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 9447738223 nanoseconds
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:387)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:378)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectOneOf$1(StreamTestKit.scala:464)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextUnorderedN(StreamTestKit.scala:469)
	at akka.persistence.query.journal.leveldb.AllPersistenceIdsSpec.$anonfun$new$6(AllPersistenceIdsSpec.scala:72)
	at akka.testkit.TestKitBase.within(TestKit.scala:418)
	at akka.testkit.TestKitBase.within$(TestKit.scala:406)
	at akka.testkit.TestKit.within(TestKit.scala:971)
	at akka.testkit.TestKitBase.within(TestKit.scala:433)
	at akka.testkit.TestKitBase.within$(TestKit.scala:433)
```

**Comment by johanandren** [comment]
Probably same LevelDB + CI server slow disk issue as #30088

**Comment by patriknw** [comment]
closing as old
