### ISSUE TITLE
[failed] PersistentActorJavaDslTest

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30086]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8545/testReport/junit/akka.persistence.typed.javadsl/PersistentActorJavaDslTest/transformEvent/

```
sbt.ForkMain$ForkError: java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for State{value=1, history=[0]}
	at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
	at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:148)
	at akka.persistence.typed.javadsl.PersistentActorJavaDslTest.transformEvent(PersistentActorJavaDslTest.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

**Comment by patriknw** [comment]
Closing as old
