### ISSUE TITLE
failed: ClusterSingletonManagerPreparingForShutdownSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30111]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8560

```
[info] [JVM-3] - must last nodes should shut down (on node 'third', class akka.cluster.singleton.ClusterSingletonManagerPreparingForShutdownMultiJvmNode3) *** FAILED ***
[info] [JVM-3]   self member: Member(akka://ClusterSingletonManagerPreparingForShutdownSpec@localhost:39289, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterSingletonManagerPreparingForShutdownSpec.scala:159)
[info] [JVM-1] [ERROR] [03/12/2021 03:29:51.614] [ClusterSingletonManagerPreparingForShutdownSpec-akka.actor.default-dispatcher-20] [akka://ClusterSingletonManagerPreparingForShutdownSpec/system/controller/barriers] unannounced disconnect of RoleName(third) (akka.remote.testconductor.BarrierCoordinator$ClientLost: unannounced disconnect of RoleName(third))
[info] [JVM-1] - must last nodes should shut down (on node 'first', class akka.cluster.singleton.ClusterSingletonManagerPreparingForShutdownMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.RuntimeException: barrier failed: done
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)
[info] [JVM-1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[info] [JVM-1]   at akka.actor.FSM.processEvent(FSM.scala:851)
[info] [JVM-1]   at akka.actor.FSM.processEvent$(FSM.scala:848)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent(FSM.scala:991)
[info] [JVM-1]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:973)
[info] [JVM-1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)
[info] [JVM-1]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:845)
```

Similar to https://github.com/akka/akka/issues/30051

**Comment by johanandren** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8569/consoleText

**Comment by patriknw** [comment]
looks like a duplicate of https://github.com/akka/akka/issues/30307, which we closed yesterday
