### ISSUE TITLE
isTimerActive is not implemented for BehaviorTestKit

### ISSUE THREAD

**Issue by chessman** [akka/akka#30140]
```
class IsTimerActiveSpec extends AnyWordSpec {
  "isTimerActive should not throw an exception" in {
    val behavior = Behaviors.withTimers[String] { timers =>
      timers.isTimerActive("timer")
      Behaviors.same
    }
    BehaviorTestKit(behavior)
  }
}
```

It throws an exception:
```
- isTimerActive should not throw an exception *** FAILED ***
  scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
  at akka.actor.testkit.typed.internal.EffectfulActorContext$$anon$1.isTimerActive(EffectfulActorContext.scala:103)
```

In `EffectfulActorContext` the implementation is missing:
```
    override def isTimerActive(key: Any): Boolean = ???
```

**Comment by johanandren** [comment]
Looks like a slight oversight, because the state is there, so just needs to look if key is present in `activeTimers`, if you'd be up for fixing it with a PR that'd be great!
