### ISSUE TITLE
Release 2.5, sigar, and akka-stream-perf build broken

### ISSUE THREAD

**Issue by chbatey** [akka/akka#30143]
This due to the bintray going away?

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.lightbend.akka:paradox-theme-akka:0.23
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinsakka/.ivy2/local/com.lightbend.akka/paradox-theme-akka/0.23/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lightbend/akka/paradox-theme-akka/0.23/paradox-theme-akka-0.23.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/lightbend/akka/paradox-theme-akka/0.23/paradox-theme-akka-0.23.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/lightbend/akka/paradox-theme-akka/0.23/paradox-theme-akka-0.23.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.akka/paradox-theme-akka/0.23/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.lightbend.akka/paradox-theme-akka/0.23/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
```

Builds currently broken:

* [x] akka-artery-aeron-udp-remote-tests
* [x] akka-sigar
* [x] release-2.5
* [x] akka-stream-perf

**Comment by raboof** [comment]
Looking at my ~/.ivy2/cache/com.lightbend.akka/paradox-theme-akka/ivydata-0.36.properties I previously got it from https://jcenter.bintray.com/com/lightbend/akka/paradox-theme-akka/0.36/paradox-theme-akka-0.36.pom , which is returning 403 forbidden right now...

**Comment by raboof** [comment]
though I'm not sure it's the sunset, the schedule https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ mentions the first read access going away in april

**Comment by chbatey** [comment]
Also other sbt plugins:
https://jenkins.akka.io:8498/job/akka-nightly-sigar/1998/console

```
[error] sbt.librarymanagement.ResolveException: Error downloading net.bzzt:sbt-reproducible-builds;sbtVersion=1.0;scalaVersion=2.12:0.25
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinsakka/.ivy2/local/net.bzzt/sbt-reproducible-builds/scala_2.12/sbt_1.0/0.25/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.25/sbt-reproducible-builds-0.25.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.25/sbt-reproducible-builds-0.25.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/net/bzzt/sbt-reproducible-builds_2.12_1.0/0.25/sbt-reproducible-builds-0.25.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/net.bzzt/sbt-reproducible-builds/0.25/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/net.bzzt/sbt-reproducible-builds/0.25/ivys/ivy.xml
[error] Error downloading de.heikoseeberger:sbt-header;sbtVersion=1.0;scalaVersion=2.12:5.6.0
[error]   Not found
[error]   Not found
[error]   not found: /localhome/jenkinsakka/.ivy2/local/de.heikoseeberger/sbt-header/scala_2.12/sbt_1.0/5.6.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/de/heikoseeberger/sbt-header_2.12_1.0/5.6.0/sbt-header-5.6.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/de/heikoseeberger/sbt-header_2.12_1.0/5.6.0/sbt-header-5.6.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/de/heikoseeberger/sbt-header_2.12_1.0/5.6.0/sbt-header-5.6.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/de.heikoseeberger/sbt-header/5.6.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/de.heikoseeberger/sbt-header/5.6.0/ivys/ivy.xml
```

**Comment by chbatey** [comment]
And: https://jenkins.akka.io:8498/job/akka-stream-perf-master/2918/console

**Comment by chbatey** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-sigar/1999/console

**Comment by chbatey** [comment]
Fixed now. These builds had override.build.servers set, so maybe something changed on the jenkins host which caused this, all fo them work without it

**Comment by johanandren** [comment]
It was probably my fault, I disabled the artifactory proxy on the jenkins cluster because of certificate issues last week, and thought I had gone through all ci jobs and fixed + verified, but it looks as if there was some builds I missed after all.
