### ISSUE TITLE
Failed: ClusterShardingPreparingForShutdownSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#30158]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2669/

```scala
[info] [JVM-3] - must not rebalance but should still work preparing for shutdown (on node 'third', class akka.cluster.sharding.typed.ClusterShardingPreparingForShutdo│
[info] [JVM-3]   java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Pong(1)                                                         │
[info] [JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:391)                                                               │
[info] [JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)                                                   │
[info] [JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:148)                                                            │
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$3(ClusterShardingPreparingForShutdownSpec.scala:88)              │
[info] [JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)                                                                            │
[info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)                                                                                             │
[info] [JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)                                                                                            │
[info] [JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)                                                                                           │
[info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)                                                                                             │
[info] [JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)                                                                                             │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)                                                                  │
[info] [JVM-3]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)                                                                                          │
[info] [JVM-3]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)                                                                                         │
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withFixture(ClusterShardingPreparingForShutdownSpec.scala:65)                 │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)                                                            │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)                                                             │
[info] [JVM-3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)                                                                                           │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)                                                                        │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)                                                                       │
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.runTest(ClusterShardingPreparingForShutdownSpec.scala:65)                     │
[info] [JVM-3]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)                                                            │
[info] [JVM-3]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)                                                                           │
[info] [JVM-3]   at scala.collection.immutable.List.foreach(List.scala:431)                                                                                           ┤
[info] [JVM-3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
```

**Comment by octonato** [comment]
and also here: https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/701/

**Comment by johanandren** [comment]
Duplicate of #30051 ?

**Comment by octonato** [comment]
yes, that's a duplicate. Strange that I didn't find it when searching for ClusterShardingPreparingForShutdownSpec. 

I will close this one.
