### ISSUE TITLE
Akka Streams NPE during postStop

### ISSUE THREAD

**Issue by pashashiz** [akka/akka#30201]
Hi, I am getting the following error when the computation graph which has inside either `mapAsync` or `flatMapConcat`and wrapped into `RestartSources.onFailuresWithBackoff` fails. This happens when multiple async operations fail at the same time. 

Unfortunately, I did not yet come up with a synthetic example to reproduce that. Few words about how we use it. In our project, we use akka streams to wrap Azure ServiceBus reactive library. The library itself is quite unstable so we had to restart it when we cannot acknowledge the messages (we just propagate the error upstream to the source). In case there are multiple errors during async parallel message acknowledgment the graph fails with NPE and the Azure ServiceBus source is not canceled because of that, it leads to resource leaks, and our services just hang after some period of time. In case we make `parallelism = 1` for `mapAsync` or `flatMapConcat` the issue disappears, but that leads to poor performance.

Akka version `2.6.14`

```
26-04-2021 09:53:51.725 [consumer-akka.actor.default-dispatcher-5] ERROR akka.actor.RepointableActorRef - Error during postStop in [akka.stream.impl.fusing.GraphStages$IgnoreSink$$anon$10-ignoreSink]: null
java.lang.NullPointerException: null
	at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1366)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:600)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:579)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:775)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:762)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:791)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by johanandren** [comment]
That is curious, that `asyncCallbacksInProgress` atomic is private and as far as I can see it should only be set to `null` from `afterPostStop()` so almost like someone/something is calling `afterPostStop()` multiple times.

**Comment by jrudolph** [comment]
Previous instance of that problem: #25537

**Comment by jrudolph** [comment]
> Previous instance of that problem: #25537

I tried the reproducer given in #25537 but wasn't able to reproduce the behavior. For reference, here's the full code I used:

```java
package akka.stream;

import akka.actor.ActorSystem;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.RetryFlow;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;

import java.time.Duration;
import java.time.Instant;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

public class Reproducer {
  public static void main(String[] args) throws ExecutionException, InterruptedException {
    ActorSystem system = ActorSystem.create();
    Source.single(1)
        .via(
            RetryFlow.withBackoff(
                Duration.ofSeconds(1),
                Duration.ofSeconds(10),
                0.2,
                500,
                Flow.of(Integer.class)
                    .mapAsync(
                        1,
                        input -> {
                          System.out.println("Flow trigger at " + Instant.now().toString());
                          if (input % 2 == 0) {
                            return CompletableFuture.completedFuture(1);
                          }
                          return CompletableFuture.completedFuture(-1);
                        }),
                (input, result) -> {
                  if (result == -1) {
                    System.out.println("Retry at " + Instant.now().toString());
                    return Optional.of(input);
                  }
                  System.out.println("Continue at " + Instant.now().toString());
                  return Optional.empty();
                }))
        .runWith(
            Sink.foreach(
                i ->
                    System.out.println(
                        "Reach sink with value " + i + " at " + Instant.now().toString())),
            system)
        .toCompletableFuture()
        .get();
  }
}
```

**Comment by johanandren** [comment]
@kamiKAZIK thanks for the reproducer, I could see the error (also with latest Akka 2.6.17)

I think there is a bug lurking here with the chasing optimization in the graph interpreter and stage completion, the immediate fix would be to add a null check in that if-expression but I think that would potentially just obscure additional problems.

This is from running with a patched version that prints a stack trace when afterPostStop is called:

```
java.lang.RuntimeException: afterPostStop akka.stream.impl.RetryFlowCoordinator$$anon$1
	at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1366)
	at akka.stream.stage.TimerGraphStageLogic.afterPostStop(GraphStage.scala:1681)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:601)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:580)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:427) // <--- chasing PUSH
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	...

2021-11-01 15:45:43.801 [AkkaApiClientSpec-f26d4835-fe18-4acf-a2b7-cbae0fa0920e-akka.actor.default-dispatcher-5] ERROR akka.actor.RepointableActorRef - Error during postStop in [akka.stream.impl.RetryFlowCoordinator$$anon$1]: Cannot invoke "scala.collection.immutable.List.nonEmpty()" because "inProgress" is null
java.lang.NullPointerException: Cannot invoke "scala.collection.immutable.List.nonEmpty()" because "inProgress" is null
	at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1367)
	at akka.stream.stage.TimerGraphStageLogic.afterPostStop(GraphStage.scala:1681)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:601)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:580)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:438) // <--- chasing PULL
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
    ...
```

I didn't quite figure this out yet, but to sum it up:

Two slightly different paths to `afterStageHasRun` for the same stage there, the first one in the PUSH chasing loop, and the second in the PULL chasing loop. It is strange that the PULL chasing loop ever processes the same stage that completed in the first loop though. In addition to calling `finalizeStage`, `isStageCompleted` also subtracts the count of running stages so that should also be incorrect because of this bug.

ping @jrudolph

**Comment by jrudolph** [comment]
It seems the push and pull chasing logic don't check whether the stage is still running in the same way that `processEvents` does so they still try to execute events even when the stage is already finished (which I guess can also lead to even more issues).

We probably don't track whether a stage has already run it's `postStop` logic, so that's one thing we could do. Or we remove the push/pull chase optimization altogether because it just adds complexity like this and has little benefit.

**Comment by patriknw** [comment]
This seems to be a real bug. Could you try one of your ideas of how to fix it @jrudolph ?
