### ISSUE TITLE
Failed: ClusterSingletonManagerSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30253]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2728

```
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ClusterSingletonManagerSpec/system/controller#-1096482806]] after [10000 ms]. Message of type [akka.remote.testconductor.Terminate]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.[0m[0m
  ...[0m[0m
- must take over when oldest crashes in 2 nodes cluster (on node 'sixth', class akka.cluster.singleton.ClusterSingletonManagerMultiJvmNode8) *** FAILED ***[0m[0m
  java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for 33[0m[0m
  at scala.Predef$.assert(Predef.scala:280)[0m[0m
  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)[0m[0m
  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:447)[0m[0m
  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:447)[0m[0m
  at akka.testkit.TestKit.expectMsg(TestKit.scala:973)[0m[0m
  at akka.cluster.singleton.ClusterSingletonManagerSpec.$anonfun$verifyMsg$2(ClusterSingletonManagerSpec.scala:308)
```

**Comment by patriknw** [comment]
multi-node with aeron-udp
https://github.com/akka/akka/runs/4057493010?check_suite_focus=true#step:9:30739

```
[info] [JVM-8] - must startup 6 node cluster (on node 'sixth', class akka.cluster.singleton.ClusterSingletonManagerMultiJvmNode8) *** FAILED ***
30740
[info] [JVM-8]   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsg while waiting for Pong
30741
[info] [JVM-8]   at scala.Predef$.assert(Predef.scala:279)
30742
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
30743
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:447)
30744
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:447)
30745
[info] [JVM-8]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
30746
[info] [JVM-8]   at akka.cluster.singleton.ClusterSingletonManagerSpec.$anonfun$verifyProxyMsg$3(ClusterSingletonManagerSpec.scala:264)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4074436532?check_suite_focus=true#step:9:29613

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4099647976?check_suite_focus=true#step:9:30207

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4086990370?check_suite_focus=true#step:9:30755

**Comment by johanandren** [comment]
Looks like they all have growing heartbeat intervals up to 5-6 seconds and then nodes marked as unreachable. All aeron-udp. 

It's an 8 node multi-jvm test, we don't have many using that many nodes, some form of resource constraint slowing things down?

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4123066105?check_suite_focus=true#step:9:30703

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4128238060?check_suite_focus=true#step:9:30885

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4133398130?check_suite_focus=true#step:9:30692

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4146239242?check_suite_focus=true#step:9:30701

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4159419758?check_suite_focus=true#step:9:31073

**Comment by patriknw** [comment]
It's indeed a starvation problem. This is just local scheduling:
```
Previous heartbeat was sent [4353] ms ago, expected interval is [1000] ms
```

**Comment by patriknw** [comment]
attempt in merged PR, pls reopen if it fails again
