### ISSUE TITLE
Failed: DDataClusterShardingLeaving

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30255]
https://jenkins.akka.io:8498/job/(legacy)%20akka-multi-node-repeat-johan/1304/consoleText

```
must recover after leaving coordinator node (on node 'third', class akka.cluster.sharding.DDataClusterShardingLeavingMultiJvmNode3) *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsgClass waiting for class akka.actor.ActorRef[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.Predef$.assert(Predef.scala:280)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:553)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:552)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$22(ClusterShardingLeavingSpec.scala:167)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at scala.collection.immutable.HashMap.foreach(HashMap.scala:1076)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-3[0m] [31m  at akka.cluster.sharding.ClusterShardingLeavingSpec.$anonfun$new$21(ClusterShardingLeavingSpec.scala:163)[0m[0m
```

**Comment by patriknw** [comment]
closing as old
