### ISSUE TITLE
Failed: ClusterShardingPreparingForShutdown: waiting for Pong(1)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30260]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2730/consoleText

```
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m- must not rebalance but should still work preparing for shutdown (on node 'first', class akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownMultiJvmNode1) *** FAILED *** (3 seconds, 90 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Pong(1)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:171)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$3(ClusterShardingPreparingForShutdownSpec.scala:88)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withFixture(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.runTest(ClusterShardingPreparingForShutdownSpec.scala:65)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[[34mJVM-1[0m] [31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)[0m[0m
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node/4441

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2740/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2768

**Comment by debasishg** [comment]
https://jenkins.akka.io:8498/job/akka-multi-node-nightly/8213/

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2777/consoleFull

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2791/consoleFull

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2805

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/835

Slightly different?

```
[info] [JVM-3]   self member: Member(akka.tcp://ClusterShardingPreparingForShutdownSpec@a6.moxie:32895, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:136)
[info] [JVM-3]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-3]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[info] [JVM-3]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$19(ClusterShardingPreparingForShutdownSpec.scala:136)
[info] [JVM-3]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info] [JVM-3]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withClue(ClusterShardingPreparingForShutdownSpec.scala:65)
[info] [JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$18(ClusterShardingPreparingForShutdownSpec.scala:136)
```

**Comment by raboof** [comment]
> https://jenkins.akka.io:8498/job/akka-classic-cluster-tests/835
>
> Slightly different

I think that's #30051

**Comment by patriknw** [comment]
> Slightly different

looks like #31144

**Comment by raboof** [comment]
`Pong(1)` is the test message *before* starting to test the shutdown, so this is unlikely to be a 'lurking problem' and more likely a test instability. Since we're not sure how recently we've seen it (previous comments might have been #30051/#31144 instead) I think we can close this one for now.
