### ISSUE TITLE
ClusterClientSpec: must re-establish connection to receptionist after server restart

### ISSUE THREAD

**Issue by raboof** [akka/akka#30292]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2742/consoleFull
```
[info] [JVM-1] - must re-establish connection to receptionist after server restart (on node 'client', class akka.cluster.client.ClusterClientMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   java.lang.AssertionError: timeout (10 seconds) waiting for 1 messages on InfoFilter(Some(akka://ClusterClientSpec@a4.moxie:33684/user/client4),Left(Connected to),false)
[info] [JVM-1]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
[info] [JVM-1]   at akka.cluster.client.ClusterClientSpec.$anonfun$new$50(ClusterClientSpec.scala:482)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:375)
[info] [JVM-1]   at akka.cluster.client.ClusterClientSpec.$anonfun$new$49(ClusterClientSpec.scala:467)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:418)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:973)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:433)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)
```

Possibly related to #21477 or #19320 .

Perhaps we should remove this test as ClusterClient is deprecated anyway, though.

**Comment by octonato** [comment]
Similar failure one the Dec 3rd 2021

https://github.com/akka/akka/runs/4402479871?check_suite_focus=true#step:9:28374

Note that first failure is different, but followed by the same as previously reported here. So probably both have same cause. 

```scala
[info] [JVM-1] - must re-establish connection to receptionist after partition (on node 'client', class akka.cluster.client.ClusterClientMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://ClusterClientSpec/system/controller#-1161785968]] after [10000 ms]. Message of type [akka.remote.testconductor.Terminate]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
[info] [JVM-1]   ...
[info] [JVM-1] - must re-establish connection to receptionist after server restart (on node 'client', class akka.cluster.client.ClusterClientMultiJvmNode1) *** FAILED ***
[info] [JVM-1]   3 did not equal 1 (ClusterClientSpec.scala:469)
```
