### ISSUE TITLE
PersistentShardingMigration: allow migration of remembered shards and not allow going back

### ISSUE THREAD

**Issue by raboof** [akka/akka#30308]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8818/consoleFull

```
[info]   Set() had size 0 instead of expected size 1 (PersistentShardingMigrationSpec.scala:183)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2720)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$12(PersistentShardingMigrationSpec.scala:183)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.assertRegionRegistrationComplete$1(PersistentShardingMigrationSpec.scala:181)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3(PersistentShardingMigrationSpec.scala:115)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3$adapted(PersistentShardingMigrationSpec.scala:114)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.withSystem$1(PersistentShardingMigrationSpec.scala:174)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$2(PersistentShardingMigrationSpec.scala:114)
```

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8903

```
[INFO] [07/04/2021 06:25:31.516] [pool-1-thread-1] [ArteryTcpTransport(akka://PersistentShardingMigrationSpec)] Remoting started with transport [Artery tcp]; listening on address [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] with UID [-2335503823815173901]
[INFO] [07/04/2021 06:25:31.518] [pool-1-thread-1] [Cluster(akka://PersistentShardingMigrationSpec)] Cluster Node [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] - Starting up, Akka version [2.6.15+10-9657f843-SNAPSHOT] ...
[INFO] [07/04/2021 06:25:31.526] [pool-1-thread-1] [Cluster(akka://PersistentShardingMigrationSpec)] Cluster Node [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [07/04/2021 06:25:31.526] [pool-1-thread-1] [Cluster(akka://PersistentShardingMigrationSpec)] Cluster Node [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] - Started up successfully
[INFO] [07/04/2021 06:25:31.531] [PersistentShardingMigrationSpec-akka.actor.internal-dispatcher-6] [Cluster(akka://PersistentShardingMigrationSpec)] Cluster Node [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] - No downing-provider-class configured, manual cluster downing required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#downing
[INFO] [07/04/2021 06:25:31.531] [PersistentShardingMigrationSpec-akka.actor.internal-dispatcher-6] [Cluster(akka://PersistentShardingMigrationSpec)] Cluster Node [akka://PersistentShardingMigrationSpec@127.0.1.1:39157] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
[info] PersistentShardingMigrationSpec:
Coroner Thread Count starts at 22 in akka.cluster.sharding.PersistentShardingMigrationSpec
[info] Migration
[INFO] [07/04/2021 06:25:31.649] [pool-1-thread-1-ScalaTest-running-PersistentShardingMigrationSpec] [ArteryTcpTransport(akka://OldMode)] Remoting started with transport [Artery tcp]; listening on address [akka://OldMode@127.0.1.1:37759] with UID [-1091456356755319877]
[INFO] [07/04/2021 06:25:31.650] [pool-1-thread-1-ScalaTest-running-PersistentShardingMigrationSpec] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Starting up, Akka version [2.6.15+10-9657f843-SNAPSHOT] ...
[WARN] [07/04/2021 06:25:31.659] [pool-1-thread-1-ScalaTest-running-PersistentShardingMigrationSpec] [Cluster(akka://OldMode)] Could not register Cluster JMX MBean with name=akka:type=Cluster as it is already registered. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
[INFO] [07/04/2021 06:25:31.659] [pool-1-thread-1-ScalaTest-running-PersistentShardingMigrationSpec] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Started up successfully
[INFO] [07/04/2021 06:25:31.664] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - No downing-provider-class configured, manual cluster downing required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#downing
[INFO] [07/04/2021 06:25:31.664] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
[INFO] [akkaMemberChanged][07/04/2021 06:25:31.742] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Node [akka://OldMode@127.0.1.1:37759] is JOINING itself (with roles [dc-default], version [0.0.0]) and forming new cluster
[INFO] [07/04/2021 06:25:31.743] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - is the new leader among reachable nodes (more leaders may exist)
[INFO] [akkaMemberChanged][07/04/2021 06:25:31.744] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Leader is moving node [akka://OldMode@127.0.1.1:37759] to [Up]
[WARN] [07/04/2021 06:25:31.900] [pool-1-thread-1-ScalaTest-running-PersistentShardingMigrationSpec] [ClusterSharding(akka://OldMode)] Cluster Sharding has been set to use the deprecated `persistence` state store mode.
[INFO] [akkaClusterSingletonStarted][07/04/2021 06:25:31.912] [OldMode-akka.actor.internal-dispatcher-11] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] Singleton manager starting singleton actor [akka://OldMode/system/sharding/MigrationCoordinator/singleton]
[INFO] [07/04/2021 06:25:31.913] [OldMode-akka.actor.internal-dispatcher-11] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] ClusterSingletonManager state change [Start -> Oldest]
[INFO] [akkaMemberChanged][07/04/2021 06:25:34.865] [OldMode-akka.actor.internal-dispatcher-6] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Marked address [akka://OldMode@127.0.1.1:37759] as [Leaving]
[INFO] [07/04/2021 06:25:34.868] [OldMode-akka.actor.internal-dispatcher-19] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] Exited [akka://OldMode@127.0.1.1:37759].
[INFO] [07/04/2021 06:25:34.868] [OldMode-akka.actor.internal-dispatcher-19] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] Oldest observed OldestChanged: [akka://OldMode@127.0.1.1:37759 -> None]
[INFO] [07/04/2021 06:25:34.868] [OldMode-akka.actor.internal-dispatcher-19] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] ClusterSingletonManager state change [Oldest -> WasOldest]
[INFO] [akkaDeadLetter][07/04/2021 06:25:35.265] [OldMode-akka.actor.default-dispatcher-14] [akka://OldMode/system/sharding/MigrationCoordinator/singleton/coordinator] Message [akka.cluster.sharding.ShardCoordinator$Internal$GracefulShutdownReq] from Actor[akka://OldMode/system/sharding/Migration#2097000550] to Actor[akka://OldMode/system/sharding/MigrationCoordinator/singleton/coordinator#1757073390] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[INFO] [akkaMemberChanged][07/04/2021 06:25:35.739] [OldMode-akka.actor.internal-dispatcher-2] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Leader is moving node [akka://OldMode@127.0.1.1:37759] to [Exiting]
[INFO] [07/04/2021 06:25:35.879] [OldMode-akka.actor.internal-dispatcher-20] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] Singleton manager stopping singleton actor [akka://OldMode/system/sharding/MigrationCoordinator/singleton]
[INFO] [07/04/2021 06:25:35.879] [OldMode-akka.actor.internal-dispatcher-20] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] ClusterSingletonManager state change [WasOldest -> Stopping]
[INFO] [akkaClusterSingletonTerminated][07/04/2021 06:25:35.882] [OldMode-akka.actor.internal-dispatcher-19] [akka://OldMode@127.0.1.1:37759/system/sharding/MigrationCoordinator] Singleton actor [akka://OldMode/system/sharding/MigrationCoordinator/singleton] was terminated
[INFO] [07/04/2021 06:25:35.884] [OldMode-akka.actor.internal-dispatcher-18] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Exiting completed
[INFO] [07/04/2021 06:25:35.885] [OldMode-akka.actor.internal-dispatcher-18] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Shutting down...
[INFO] [07/04/2021 06:25:35.885] [OldMode-akka.actor.internal-dispatcher-18] [Cluster(akka://OldMode)] Cluster Node [akka://OldMode@127.0.1.1:37759] - Successfully shut down
[INFO] [07/04/2021 06:25:35.892] [OldMode-akka.remote.default-remote-dispatcher-10] [akka://OldMode@127.0.1.1:37759/system/remoting-terminator] Shutting down remote daemon.
[INFO] [07/04/2021 06:25:35.892] [OldMode-akka.remote.default-remote-dispatcher-10] [akka://OldMode@127.0.1.1:37759/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[INFO] [07/04/2021 06:25:35.897] [OldMode-akka.remote.default-remote-dispatcher-24] [akka://OldMode@127.0.1.1:37759/system/remoting-terminator] Remoting shut down.
[info] - should allow migration of remembered shards and not allow going back *** FAILED *** (4 seconds, 321 milliseconds)
[info]   Set() had size 0 instead of expected size 1 (PersistentShardingMigrationSpec.scala:183)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2720)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$12(PersistentShardingMigrationSpec.scala:183)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.assertRegionRegistrationComplete$1(PersistentShardingMigrationSpec.scala:181)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3(PersistentShardingMigrationSpec.scala:115)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$3$adapted(PersistentShardingMigrationSpec.scala:114)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.withSystem$1(PersistentShardingMigrationSpec.scala:174)
[info]   at akka.cluster.sharding.PersistentShardingMigrationSpec.$anonfun$new$2(PersistentShardingMigrationSpec.scala:114)
```

**Comment by raboof** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8987/consoleFull
