### ISSUE TITLE
RotatingProviderWithChangingKeysSpec: Failed to stop [systemB-reread] within [10 seconds] 

### ISSUE THREAD

**Issue by raboof** [akka/akka#30309]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8819/consoleFull
```
[info] akka.remote.artery.tcp.ssl.RotatingProviderWithChangingKeysSpec *** ABORTED *** (16 seconds, 43 milliseconds)
[info]   java.lang.RuntimeException: Failed to stop [systemB-reread] within [10 seconds] 
[info] -> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
[info]    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 8 children
[info]        ⌊-> IO-DNS RepointableActorRef class akka.io.SimpleDnsManager status=0 1 children
[info]        |   ⌊-> inet-address RoutedActorRef class akka.routing.RouterPoolActor status=0 4 children
[info]        |       ⌊-> $a LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $b LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $c LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $d LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        ⌊-> IO-TCP RepointableActorRef class akka.io.TcpManager status=0 1 children
[info]        |   ⌊-> selectors RoutedActorRef class akka.routing.RouterPoolActor status=0 1 children
[info]        |       ⌊-> $a LocalActorRef class akka.io.SelectionHandler status=0 1 children
[info]        |           ⌊-> 0 LocalActorRef class akka.io.TcpListener status=0 no children
[info]        ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children
[info]        |   ⌊-> StreamSupervisor-439 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]        |   ⌊-> StreamSupervisor-440 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 2 children
[info]        |   |   ⌊-> remote-0-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]        |   |   ⌊-> remote-24-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]        |   ⌊-> StreamSupervisor-441 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]        ⌊-> eventStreamUnsubscriber-208 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[info]        ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
[info]        ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[info]        ⌊-> testProbe-1142 RepointableActorRef class akka.testkit.TestActor status=0 no children
[info]        ⌊-> testProbe-1144 RepointableActorRef class akka.testkit.TestActor status=0 no children
[info]   at akka.testkit.TestKit$.shutdownActorSystem(TestKit.scala:1032)
[info]   at akka.testkit.TestKitBase.shutdown(TestKit.scala:883)
[info]   at akka.testkit.TestKitBase.shutdown$(TestKit.scala:879)
[info]   at akka.testkit.TestKit.shutdown(TestKit.scala:973)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.$anonfun$beforeTermination$2(RotatingKeysSSLEngineProviderSpec.scala:274)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.$anonfun$beforeTermination$2$adapted(RotatingKeysSSLEngineProviderSpec.scala:274)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProviderSpec.beforeTermination(RotatingKeysSSLEngineProviderSpec.scala:274)
```

**Comment by johanandren** [comment]
Could it be related to this old goodie perhaps #29331 ?

**Comment by raboof** [comment]
(not excluded and not seen for ~half a year, closing)
