### ISSUE TITLE
Failed: FlowFlattenMergeSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30322]
Or not really failed, but saw this when running other tests and it looks like it would be worth investigating:

```
[ERROR] [06/14/2021 14:20:36.002] [FlowFlattenMergeSpec-akka.test.stream-dispatcher-10] [akka://FlowFlattenMergeSpec/system/Materializers/StreamSupervisor-10/flow-20-0-headSink] Error during postStop in [akka.stream.impl.fusing.FlattenMerge$$anon$1-flattenMerge]: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(java.lang.Exception: buh) is still pending
java.lang.IllegalStateException: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(java.lang.Exception: buh) is still pending
	at akka.stream.impl.fusing.SubSink.dispatchCommand(StreamOfStreams.scala:709)
	at akka.stream.impl.fusing.SubSink.cancelSubstream(StreamOfStreams.scala:692)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1480)
	at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1476)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1(StreamOfStreams.scala:131)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1$adapted(StreamOfStreams.scala:131)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:201)
	at akka.stream.impl.fusing.FlattenMerge$$anon$1.postStop(StreamOfStreams.scala:131)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:600)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:580)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:620)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:727)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:776)
	at akka.actor.Actor.aroundPreStart(Actor.scala:548)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.create(ActorCell.scala:644)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:514)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:536)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by francisdb** [comment]
looks like a similar issue as https://github.com/akka/akka/issues/30071

We also see these in production code

```
java.lang.IllegalStateException: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
    at akka.stream.impl.fusing.SubSink.dispatchCommand(StreamOfStreams.scala:709)
    at akka.stream.impl.fusing.SubSink.cancelSubstream(StreamOfStreams.scala:692)
    at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1480)
    at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1476)
    at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1(StreamOfStreams.scala:131)
    at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1$adapted(StreamOfStreams.scala:131)
    at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
    at akka.stream.impl.fusing.FlattenMerge$$anon$1.postStop(StreamOfStreams.scala:131)
    at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:599)
    at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:579)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:775)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:762)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:791)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
    at akka.actor.ActorCell.invoke(ActorCell.scala:547)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run(Mailbox.scala:231)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by aygalinc** [comment]
Also see with akka-stream 2.6.15 : 
```
: [ERROR] [08/02/2021 09:52:35.059] [offer-processing-actor-system-akka.actor.default-dispatcher-18] [akka://offer-processing-actor-system/system/Materializers/StreamSupervisor-1/flow-524577-4-map] Error during postStop in [akka.stream.impl.fusing.FlattenMerge$$anon$1-flattenMerge]: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]: java.lang.IllegalStateException: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.SubSink.dispatchCommand(StreamOfStreams.scala:709)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.SubSink.cancelSubstream(StreamOfStreams.scala:692)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1480)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1476)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1$adapted(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.postStop(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:600)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:580)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.Actor.aroundReceive(Actor.scala:537)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.Actor.aroundReceive$(Actor.scala:535)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.ActorCell.invoke(ActorCell.scala:548)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.run(Mailbox.scala:231)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]: [ERROR] [08/02/2021 09:52:35.059] [offer-processing-actor-system-akka.actor.default-dispatcher-18] [akka://offer-processing-actor-system/system/Materializers/StreamSupervisor-1/flow-524577-4-map] Error during postStop in [akka.stream.impl.fusing.FlattenMerge$$anon$1-flattenMerge]: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]: java.lang.IllegalStateException: Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) on subsink(FlattenMergeSink) is illegal when Cancel(akka.stream.SubscriptionWithCancelException$NoMoreElementsNeeded$) is still pending
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.SubSink.dispatchCommand(StreamOfStreams.scala:709)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.SubSink.cancelSubstream(StreamOfStreams.scala:692)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1480)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.stage.GraphStageLogic$SubSinkInlet.cancel(GraphStage.scala:1476)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.$anonfun$postStop$1$adapted(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.FlattenMerge$$anon$1.postStop(StreamOfStreams.scala:131)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:600)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:580)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:394)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.Actor.aroundReceive(Actor.scala:537)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.Actor.aroundReceive$(Actor.scala:535)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.actor.ActorCell.invoke(ActorCell.scala:548)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.run(Mailbox.scala:231)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Aug 02 09:52:35 dc1-bing-dev-exporter-01.dev.dc1.kelkoo.net bash[591629]:         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```
