### ISSUE TITLE
Failed: RestartSpec

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#30320]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8834/testReport/junit/akka.stream.scaladsl/RestartSpec/A_restart_with_backoff_flow_should_not_restart_on_completion_when_maxRestarts_is_reached/

```
java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 10 seconds
    at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:387)
    at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:378)
    at akka.stream.scaladsl.RestartSpec.$anonfun$new$113(RestartSpec.scala:824)
```

Similar to earlier closed issue for failure in #24075

**Comment by raboof** [comment]
very similar in https://github.com/akka/akka/runs/3533465227

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5276807239?check_suite_focus=true#step:5:15993

```
[02/21/2022 16:27:12.564] [RestartSpec-akka.actor.default-dispatcher-6] [akka.dispatch.Dispatcher] assertion failed: timeout (20 seconds) during expectMsg: expecting request() signal
```
