### ISSUE TITLE
AssertionError: assertion failed: Timer should have triggered only after deadline

### ISSUE THREAD

**Issue by francisdb** [akka/akka#30333]
`Akka 2.6.10`
`openjdk:11-jdk`

The last 3 days we have seen 4 of these on one of our services running in Kubernetes (Google cloud)

https://github.com/akka/akka/commit/01603ccc90befb5f7ce27f3c7e240f54f7ce675f seems to have introduced this assertion
(First released in `Akka 2.6.6`)

According to this blog post `System.nanoTime()` can be adjusted by NTP

> Monotonic clocks are also not completely safe. NTP servers can speed up or slow down the clocks (known as slewing) by around 0.05% but they cannot cause the clock to jump forward or backwards.” — @khare_khote https://codeburst.io/why-shouldnt-you-trust-system-clocks-72a82a41df93

But probably there could be other reasons for this assertion to trigger?

### Possible fixes

- Change the assertion to a WARN or ERROR log message
- Allow some drift in the assertion

### These are the diffs we encountered

```
now is 1518903501995345 and deadline was 1518903502183533 diff -188188.
now is 1518903502002808 and deadline was 1518903502197734 diff -194926.
now is 1518903502047087 and deadline was 1518903502157208 diff -110121.
now is 1892025571210405 and deadline was 1892025632127525 diff -60917120.
```

### Full stack trace

```
java.util.concurrent.ExecutionException: Boxed Exception
    at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
    at scala.concurrent.Promise.tryFailure(Promise.scala:117)
    at scala.concurrent.Promise.tryFailure$(Promise.scala:117)
    at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:104)
    at akka.http.impl.util.StreamUtils$$anon$4$$anon$5.onUpstreamFailure(StreamUtils.scala:83)
    at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:524)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
    at akka.actor.ActorCell.invoke(ActorCell.scala:547)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run(Mailbox.scala:231)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

java.lang.AssertionError: assertion failed: Timer should have triggered only after deadline but now is 1518903501995345 and deadline was 1518903502183533 diff -188188.
    at scala.Predef$.assert(Predef.scala:280)
    at akka.stream.impl.Timers$IdleInject$$anon$7.onTimer(Timers.scala:276)
    at akka.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1602)
    at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1591)
    at akka.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1591)
    at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:498)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
    at akka.actor.ActorCell.invoke(ActorCell.scala:547)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run(Mailbox.scala:231)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by johanandren** [comment]
I think it could just reschedule a new delay in that very uncommon case and skip the assert.

**Comment by patriknw** [comment]
As far as I know, `nanoTime` should never go backwards, so it's interesting to investigate how this can happen. 

Wonder if there could be some "thinko" in that `now - nextDeadline` logic. Note that scheduleOnce of a negative or zero duration will execute immediately.

**Comment by francisdb** [comment]
Likely the source of the timer is this keepalive:
```scala
val ndJson = jsonMessages
      .zipWith(newLines)((a, b) => a ++ b)
      .keepAlive(60.seconds, () => ByteString("{}\n"))
```

**Comment by aumann** [comment]
We are seeing the same issue on one of our deployments (Windows 10 Pro, JVM 8, akka `2.6.10`)

It is occurring sporadically (approximately every two weeks). Unfortunately, I do not (yet) have any further information as to 'why' this might happen.

**Comment by aumann** [comment]
May be related to this JRE bug: https://bugs.openjdk.java.net/browse/JDK-8184271  ?

We run on jre8u191 -- I must admit that I find it difficult to research whether the fix for this issue had already been backported to that release -- I can't wrap my head around all the backport versions of https://bugs.openjdk.java.net/browse/JDK-8184271 and what exactly this means for the build we use on that particular system

**Comment by johanandren** [comment]
Isn't the problem that this scheduled timer only ever triggered if the deadline has already passed?

https://github.com/akka/akka/blob/390e9f675b6d2f666be2dd15b87c84c870e8b625/akka-stream/src/main/scala/akka/stream/impl/Timers.scala#L270

**Comment by francisdb** [comment]
We run on `openjdk:11-jdk`

**Comment by craffit** [comment]
Ran into the same issue on jdk 11.

https://stackoverflow.com/questions/8853698/is-system-nanotime-system-nanotime-guaranteed-to-be-0/8854104#8854104 it is explained how the nano clock can run backwards on multicore environments. I think this code should be updtaed to either not rely on nanotime (millis?) or allow for the clock running backwards.

**Comment by johanandren** [comment]
I found both the concurrency list discussions (and that SO response) to be a bit speculative. 

Searching a bit all mentions of nanoTime going backwards are old or refer to bugs that has since been fixed, while this SO writeup is from 2019 and showing nanoTime by specification is monotonic since Java 7: https://stackoverflow.com/questions/510462/is-system-nanotime-completely-useless/54566928#54566928

The post also recommends treating negative time measured with nanoTime as zero to ignore any eventual JDK bugs, rather than fail though, so maybe that's a good idea for us. 

If we decide to do that I think we need to consider from case to case in Akka, where time passed is measured with nanoTime, if such a JDK bug can safely be ignored (but probably logged so that such issues are noticed and reported to the JDK bug tracker) or needs to cause a failure.

**Comment by patriknw** [comment]
Was this observed on Windows?

I trust this answer https://stackoverflow.com/a/8853738

**Comment by aumann** [comment]
> Was this observed on Windows?
> 
> I trust this answer https://stackoverflow.com/a/8853738

In our case, yes, definitely Windows. I don't believe it has been Windows XP, though, but will double check.

**Comment by SakulK** [comment]
We experience this issue on a websockets server using akka-http `handleWebSocketMessages` with `keepAlive(maxIdle = 15 seconds)` very regularly and in "batches" like this:
```
Jul 14, 2022 @ 12:44:37.643 akka.actor.ActorSystemImpl: Websocket handler failed with assertion failed: Timer should have triggered only after deadline but now is 4685817314890 and deadline was 4685824398802 diff -7083912.
Jul 14, 2022 @ 12:44:37.642 akka.actor.ActorSystemImpl: Websocket handler failed with assertion failed: Timer should have triggered only after deadline but now is 4685817489188 and deadline was 4685824451425 diff -6962237.
Jul 14, 2022 @ 12:44:37.641 akka.actor.ActorSystemImpl: Websocket handler failed with assertion failed: Timer should have triggered only after deadline but now is 4685817307865 and deadline was 4685824352735 diff -7044870.
Jul 14, 2022 @ 12:44:37.640 akka.actor.ActorSystemImpl: Websocket handler failed with assertion failed: Timer should have triggered only after deadline but now is 4685817301858 and deadline was 4685824290324 diff -6988466.
```
Maximum diff value I observed was around 110 millis. Application is running on k8s with JDK 11, Akka 2.6.19. Let me know if I can provide some more details to figure this out :)

**Comment by He-Pin** [comment]
akka 2.6.20
jdk: ajdk ajdk-8.16.20-20220507102823

**Comment by He-Pin** [comment]
I was caching a `Source.queue` with caffine cache, and emitting/offering elements from outside of the flow, this error will kill the flow forever, so for now, I will just drop the usage of the `keepAlive`, hope this get fixed soon.
I like @francisdb 's proposal for `Changing the assertion to a WARN or ERROR log message`.

**Comment by He-Pin** [comment]
@francisdb Hi I have submitted a pr, would you like to give some input?thanks
