### ISSUE TITLE
JDK 17 Could not initialize class org.lmdbjava.ByteBufferProxy

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30341]
From community build with JDK 17

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk17-integrate-community-build/15/artifact/logs/akka-more-build.log

```
[akka-more] <-- [[34mClusterSharding must initialize cluster and allocate sharded actors[0m] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for 1)]
[akka-more] [info] - must initialize cluster and allocate sharded actors *** FAILED *** (5 seconds, 341 milliseconds)
[akka-more] [info]   java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsg while waiting for 1
[akka-more] [info]   at scala.Predef$.assert(Predef.scala:279)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[akka-more] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[akka-more] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[akka-more] [info]   at akka.cluster.sharding.ShardRegionSpec.$anonfun$new$2(ShardRegionSpec.scala:128)
[akka-more] [info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
[akka-more] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[akka-more] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[akka-more] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[akka-more] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[akka-more] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[akka-more] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
[akka-more] [info]   at akka.testkit.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:36)
[akka-more:error] Uncaught error from thread [ShardRegionSpec-akka.cluster.distributed-data.durable.pinned-store-29]: Could not initialize class org.lmdbjava.ByteBufferProxy, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ShardRegionSpec]
[akka-more:error] java.lang.NoClassDefFoundError: Could not initialize class org.lmdbjava.ByteBufferProxy
[akka-more:error] 	at org.lmdbjava.Env.create(Env.java:87)
[akka-more:error] 	at akka.cluster.ddata.LmdbDurableStore.akka$cluster$ddata$LmdbDurableStore$$lmdb(DurableStore.scala:146)
[akka-more:error] 	at akka.cluster.ddata.LmdbDurableStore$$anonfun$active$1.applyOrElse(DurableStore.scala:242)
[akka-more:error] 	at akka.actor.Actor.aroundReceive(Actor.scala:537)
[akka-more:error] 	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[akka-more:error] 	at akka.cluster.ddata.LmdbDurableStore.aroundReceive(DurableStore.scala:114)
[akka-more:error] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
[akka-more:error] 	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[akka-more:error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[akka-more:error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[akka-more:error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[akka-more:error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[akka-more:error] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by johanandren** [comment]
Work around is opening up access with: `--add-opens=java.base/java.nio=ALL-UNNAMED`
