### ISSUE TITLE
PersistentStartEntitySpec: Persistent Shard must remember entities started with StartEntity

### ISSUE THREAD

**Issue by raboof** [akka/akka#30393]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2774/testReport/junit/akka.cluster.sharding/PersistentStartEntitySpec/Persistent_Shard_must_remember_entities_started_with_StartEntity/
```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
	at scala.Predef$.assert(Predef.scala:280)
	at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
	at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
	at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
	at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
	at akka.cluster.sharding.PersistentStartEntitySpec.$anonfun$new$2(PersistentStartEntitySpec.scala:95)
```

**Comment by octonato** [comment]
Also happening in GH Actions

https://github.com/akka/akka/runs/3452449786?check_suite_focus=true#step:5:27798

```scala
[info] - must remember entities started with StartEntity *** FAILED *** (6 seconds, 816 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsgClass waiting for class akka.actor.ActorRef
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
111

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/3848794563?check_suite_focus=true#step:5:27042

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4188784117?check_suite_focus=true#step:5:2327
