### ISSUE TITLE
[failed] RoutersTest.poolBroadcastTest 

### ISSUE THREAD

**Issue by octonato** [akka/akka#30424]
It happened in a PR build (https://github.com/akka/akka/pull/30283)

```scala
 - poolBroadcastTest *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<[not-]bc-message> but was:<[]bc-message>
[info]   at org.junit.Assert.assertEquals(Assert.java:117)
[info]   at org.junit.Assert.assertEquals(Assert.java:146)
[info]   at akka.actor.typed.javadsl.RoutersTest.poolBroadcastTest(RoutersTest.java:58)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
```

**Comment by octonato** [comment]
This happened a second time after a successful run in the PR mentioned above. 

Seems that Scala 3 compilation added some flakiness. 😱

**Comment by octonato** [comment]
I'm closing this since it happened in Travis and we usually don't run the tests in Travis
