### ISSUE TITLE
LocalPubSubSpec: A pub-sub topic running locally shouldn't publish after unsubscribe

### ISSUE THREAD

**Issue by raboof** [akka/akka#30432]
Only seen on scala3 so far

https://github.com/akka/akka/runs/3161613823?check_suite_focus=true

```
[info] - must doesn't publish after unsubscribe *** FAILED *** (119 milliseconds)
[info]   java.lang.AssertionError: Received 1 excess messages on LoggingTestKitImpl(1,Some(DEBUG),None,None,Some(Topic list updated),None,None,Map(),None).
[info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:103)
[info]   at akka.actor.typed.pubsub.LocalPubSubSpec.f$proxy4$3(LocalPubSubSpec.scala:131)
[info]   at akka.actor.typed.pubsub.LocalPubSubSpec.$init$$$anonfun$5$$anonfun$4(LocalPubSubSpec.scala:127)
```

**Comment by raboof** [comment]
That debug message looks harmless, we probably just intended to wait until that message was seen? So perhaps we should not check for excess messages here, like in #30429

**Comment by raboof** [comment]
also https://github.com/akka/akka/actions/runs/1068321962
