### ISSUE TITLE
ConsumerController must send Ack when stopped

### ISSUE THREAD

**Issue by raboof** [akka/akka#30430]
Only seen with scala3 for now, but might be generally flakey:

https://github.com/akka/akka/runs/3161386766?check_suite_focus=true

```
[info] - must send Ack when stopped *** FAILED *** (53 milliseconds)
[info]   java.lang.AssertionError: expected Ack(2), found Ack(1)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.actor.typed.delivery.ConsumerControllerSpec.f$proxy15$1(ConsumerControllerSpec.scala:498)
[info]   at akka.actor.typed.delivery.ConsumerControllerSpec.$init$$$anonfun$18$$anonfun$15(ConsumerControllerSpec.scala:476)
```

**Comment by raboof** [comment]
At the end of the logging we see:
```
2021-07-26 12:32:59,431 TRACE akka.actor.typed.delivery.ConsumerController  - Received SequencedMessage seqNr [2], delivering to consumer. MDC: {akkaAddress=akka://ConsumerControllerSpec, akkaSource=akka://ConsumerControllerSpec/user/consumerController-15, sourceActorSystem=ConsumerControllerSpec, producerId=p-15}
2021-07-26 12:32:59,431 DEBUG akka.actor.typed.delivery.ConsumerController  - Cancel all timers MDC: {akkaAddress=akka://ConsumerControllerSpec, akkaSource=akka://ConsumerControllerSpec/user/consumerController-15, sourceActorSystem=ConsumerControllerSpec}
2021-07-26 12:32:59,431 INFO  akka.actor.LocalActorRef akkaDeadLetter - Message [akka.actor.typed.delivery.ConsumerController$Confirmed$] to Actor[akka://ConsumerControllerSpec/user/consumerController-15#-2117854922] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://ConsumerControllerSpec/user/consumerController-15#-2117854922] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. MDC: {akkaAddress=akka://ConsumerControllerSpec, sourceThread=ConsumerControllerSpec-akka.actor.default-dispatcher-7, akkaSource=akka://ConsumerControllerSpec/user/consumerController-15, sourceActorSystem=ConsumerControllerSpec, akkaMessageClass=akka.actor.typed.delivery.ConsumerController$Confirmed$, akkaTimestamp=12:32:59.431UTC}
```

... which looks like either the actor stopped when receiving the `SequencedMessage seqNr [2]`, or somehow the actor 'stop' overtook the `Confirmed` (which would be odd)

**Comment by ignasi35** [comment]
This could be flakey on GHActions. Just seen it on https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:11704 I'll GHExclude it.

**Comment by andreaTP** [comment]
https://github.com/akka/akka/pull/30496/checks?check_run_id=3262963552

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/3334777227?check_suite_focus=true#step:5:8415

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/3357393061?check_suite_focus=true#step:5:8432
