### ISSUE TITLE
RemoteDeathWatchSpec: receive Terminated when system of de-serialized ActorRef is not running

### ISSUE THREAD

**Issue by raboof** [akka/akka#30454]
https://jenkins.akka.io:8498/job/akka-multi-node/4503/consoleFull

**Comment by patriknw** [comment]
Closing as old, and lack of information

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/8041738953/job/21961404759#step:5:9286

```
[WARN] [02/26/2024 00:27:51.661] [RemoteDeathWatchSpec-akka.remote.default-remote-dispatcher-7] [akka.stream.Log(akka://RemoteDeathWatchSpec/system/Materializers/StreamSupervisor-284)] [outbound connection to [akka://OtherSystem@localhost:39220], message stream] Upstream failed, cause: StreamTcpException: Tcp command [Connect(localhost:39220,None,List(),Some(5000 milliseconds),true)] failed because of java.net.ConnectException: Connection refused
[WARN] [02/26/2024 00:27:51.661] [RemoteDeathWatchSpec-akka.remote.default-remote-dispatcher-7] [Association(akka://RemoteDeathWatchSpec)] Outbound control stream to [akka://OtherSystem@localhost:39220] failed. Restarting it. java.lang.IllegalStateException: Unexpected incoming bytes in outbound connection to [akka://OtherSystem@localhost:39220]
[02-26 00:28:11.731] [info] - receive Terminated when system of de-serialized ActorRef is not running *** FAILED *** (20 seconds, 72 milliseconds)
[02-26 00:28:11.731] [info]   java.lang.AssertionError: timeout (20 seconds) waiting for 1 messages on WarningFilter(None,Left(Detected unreachable),false)
[02-26 00:28:11.732] [info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
[02-26 00:28:11.732] [info]   at akka.remote.artery.RemoteDeathWatchSpec.$anonfun$new$2(RemoteDeathWatchSpec.scala:70)
[02-26 00:28:11.733] [info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
[02-26 00:28:11.733] [info]   at akka.remote.artery.RemoteDeathWatchSpec.$anonfun$new$1(RemoteDeathWatchSpec.scala:69)
[02-26 00:28:11.733] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[02-26 00:28:11.733] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[02-26 00:28:11.733] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[02-26 00:28:11.733] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[02-26 00:28:11.733] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[02-26 00:28:11.733] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[02-26 00:28:11.733] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[02-26 00:28:11.733] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[02-26 00:28:11.733] [info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
```
