### ISSUE TITLE
EventStreamSpec: unsubscribe the actor, when it subscribes already in terminated state

### ISSUE THREAD

**Issue by raboof** [akka/akka#30460]
https://github.com/akka/akka/pull/30449/checks?check_run_id=3233378543

```
[info] - must unsubscribe the actor, when it subscribes already in terminated state *** FAILED *** (56 milliseconds)
[info]   false did not equal true (EventStreamSpec.scala:339)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:402)
[info]   at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6924)
[info]   at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[info]   at akka.testkit.AkkaSpec.should(AkkaSpec.scala:54)
[info]   at akka.event.EventStreamSpec.f$proxy17$1(EventStreamSpec.scala:339)
[info]   at akka.event.EventStreamSpec.$init$$$anonfun$15$$anonfun$14(EventStreamSpec.scala:318)```

**Comment by andreaTP** [comment]
https://github.com/akka/akka/pull/30458/checks?check_run_id=3241743617
