### ISSUE TITLE
TcpIntegrationSpec: should allow connecting to and disconnecting from the test server

### ISSUE THREAD

**Issue by raboof** [akka/akka#30474]
https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/22049/consoleFull

```
--> [The TCP transport implementation should allow connecting to and disconnecting from the test server] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for PeerClosed)]
| [DEBUG] [08/04/2021 14:32:39.876] [pool-1-thread-1-ScalaTest-running-TcpIntegrationSpec] [WithLogCapturing(akka://TcpIntegrationSpec)] Logging started for test [The TCP transport implementation should allow connecting to and disconnecting from the test server]
| [DEBUG] [08/04/2021 14:32:39.930] [TcpIntegrationSpec-akka.actor.internal-dispatcher-6] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Executing [WorkerForCommand(Bind(Actor[akka://TcpIntegrationSpec/system/testProbe-569#1037531755],/127.20.34.135:42155,100,List(),false),Actor[akka://TcpIntegrationSpec/system/testProbe-570#2109250108],akka.io.TcpManager$$anonfun$receive$1$$Lambda$1001/974046145@448fe69d)]
| [DEBUG] [08/04/2021 14:32:39.931] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Scheduling Registering channel sun.nio.ch.ServerSocketChannelImpl[/127.20.34.135:42155] with initialOps 16
| [DEBUG] [08/04/2021 14:32:39.931] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/1] Successfully bound to /127.20.34.135:42155
| [DEBUG] [08/04/2021 14:32:39.931] [TcpIntegrationSpec-akka.io.pinned-dispatcher-9] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Registering channel sun.nio.ch.ServerSocketChannelImpl[/127.20.34.135:42155] with initialOps 16
| [DEBUG] [08/04/2021 14:32:39.945] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/1] New connection accepted
| [DEBUG] [08/04/2021 14:32:39.945] [TcpIntegrationSpec-akka.io.pinned-dispatcher-9] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Enabling 16 on sun.nio.ch.SelectionKeyImpl@153b8bba
| [DEBUG] [08/04/2021 14:32:39.945] [TcpIntegrationSpec-akka.actor.internal-dispatcher-6] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Executing [WorkerForCommand(RegisterIncoming(java.nio.channels.SocketChannel[connected local=/127.20.34.135:42155 remote=/127.0.0.1:60880]),Actor[akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/1#681361039],akka.io.TcpListener$$Lambda$1011/307031176@4a48007c)]
| [DEBUG] [08/04/2021 14:32:39.945] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Scheduling Registering channel java.nio.channels.SocketChannel[connected local=/127.20.34.135:42155 remote=/127.0.0.1:60880] with initialOps 0
| [DEBUG] [08/04/2021 14:32:39.945] [TcpIntegrationSpec-akka.io.pinned-dispatcher-9] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a] Registering channel java.nio.channels.SocketChannel[connected local=/127.20.34.135:42155 remote=/127.0.0.1:60880] with initialOps 0
| [DEBUG] [08/04/2021 14:32:39.966] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] [Actor[akka://TcpIntegrationSpec/system/testProbe-573#-64326002]] registered as connection handler
| [DEBUG] [08/04/2021 14:32:39.966] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] Read [-1] bytes.
| [DEBUG] [08/04/2021 14:32:39.966] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] Read returned end-of-stream, our side not yet closed
| [DEBUG] [08/04/2021 14:32:39.966] [TcpIntegrationSpec-akka.actor.internal-dispatcher-3] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] Got Close command, closing connection.
| [WARN] [08/04/2021 14:32:39.967] [TcpIntegrationSpec-akka.actor.default-dispatcher-8] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] unhandled message from Actor[akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2#-294920485]: Unregistered
| [INFO] [akkaDeadLetter][08/04/2021 14:32:39.967] [TcpIntegrationSpec-akka.actor.default-dispatcher-7] [akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2] Message [akka.io.TcpConnection$Unregistered$] from Actor[akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2#-294920485] to Actor[akka://TcpIntegrationSpec/system/IO-TCP/selectors/$a/2#-294920485] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
| [DEBUG] [08/04/2021 14:32:42.968] [pool-1-thread-1-ScalaTest-running-TcpIntegrationSpec] [WithLogCapturing(akka://TcpIntegrationSpec)] Logging finished for test [The TCP transport implementation should allow connecting to and disconnecting from the test server]
<-- [The TCP transport implementation should allow connecting to and disconnecting from the test server] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for PeerClosed)]
[info] - should allow connecting to and disconnecting from the test server *** FAILED *** (3 seconds, 98 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for PeerClosed
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.io.TcpIntegrationSpec$$anon$1.<init>(TcpIntegrationSpec.scala:40)
[info]   at akka.io.TcpIntegrationSpec.$anonfun$new$3(TcpIntegrationSpec.scala:36)
```

**Comment by ignasi35** [comment]
https://github.com/akka/akka/runs/3264635295?check_suite_focus=true#step:5:2192

**Comment by patriknw** [comment]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/9009
