### ISSUE TITLE
LazySourceSpec: Source.lazyFutureSource must provide attributes to inner source

### ISSUE THREAD

**Issue by raboof** [akka/akka#30481]
https://github.com/akka/akka/pull/30451/checks?check_run_id=3250142552

```
[info]   The future returned an exception of type: akka.stream.StreamDetachedException, with message: Stream cancelled before Source Future completed. (LazySourceSpec.scala:439)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:259)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.stream.scaladsl.LazySourceSpec.f$proxy33$1$$anonfun$1(LazySourceSpec.scala:92)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.f$proxy33$2(LazySourceSpec.scala:441)
[info]   at akka.stream.scaladsl.LazySourceSpec.$init$$$anonfun$37$$anonfun$13(LazySourceSpec.scala:431)```

**Comment by ignasi35** [comment]
Mulitple failures in `LazySourceSpec` in https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20766:


```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:141)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$35(LazySourceSpec.scala:141)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$34(LazySourceSpec.scala:129)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```


```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:292)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$75(LazySourceSpec.scala:292)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$74(LazySourceSpec.scala:277)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

Inclñuding the one on the issue description:

```--- Stream actors debug dump ---
Stream is completed. No debug information is available
[info] - must provide attributes to inner source *** FAILED *** (2 seconds, 3 milliseconds)
[info]   The future returned an exception of type: akka.stream.StreamDetachedException, with message: Stream cancelled before Source Future completed. (LazySourceSpec.scala:438)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$114(LazySourceSpec.scala:438)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$113(LazySourceSpec.scala:430)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

**Comment by raboof** [comment]
> Mulitple failures in `LazySourceSpec` in https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20766:
> 
> ```
> [info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
> ```

That seems like a different issue AFAICS, filed #30492
