### ISSUE TITLE
[failed] StartEntitySpec while the entity is waiting for restart should restart

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30495]
refs https://github.com/akka/akka/issues/28620#issuecomment-707442372 (this failure happened rarely in the past and it still didn't have a dedicated issue)

Seen in https://github.com/akka/akka/pull/30449/checks?check_run_id=3254755116#step:5:28491

```
[info] - should restart it immediately *** FAILED *** (3 seconds, 224 milliseconds)
[info]   Set() did not equal Set("1") (StartEntitySpec.scala:145)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.cluster.sharding.StartEntitySpec.$anonfun$new$6(StartEntitySpec.scala:145)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
```

<details>
<summary>Details</summary>

```

[info] StartEntity while the entity is waiting for restart
--> [StartEntity while the entity is waiting for restart should restart it immediately] Start of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: Set() did not equal Set("1"))]
| [DEBUG] [08/05/2021 17:58:18.547] [pool-1-thread-1-ScalaTest-running-StartEntitySpec] [WithLogCapturing(akka://StartEntitySpec)] Logging started for test [StartEntity while the entity is waiting for restart should restart it immediately]
| [DEBUG] [08/05/2021 17:58:18.548] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Idle entities will not be passivated because 'rememberEntities' is enabled.
| [DEBUG] [08/05/2021 17:58:18.548] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Coordinator moved from [] to [akka://StartEntitySpec@10.1.0.49:40037]
| [DEBUG] [08/05/2021 17:58:18.548] [StartEntitySpec-akka.actor.internal-dispatcher-5] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RegisterRetry] with generation [2]
| [INFO] [akkaClusterSingletonStarted][08/05/2021 17:58:18.549] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator] Singleton manager starting singleton actor [akka://StartEntitySpec/system/sharding/start-entity-2Coordinator/singleton]
| [INFO] [08/05/2021 17:58:18.549] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator] ClusterSingletonManager state change [Start -> Oldest]
| [DEBUG] [08/05/2021 17:58:18.549] [StartEntitySpec-akka.actor.default-dispatcher-11] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Starting remember entities store from provider akka.cluster.sharding.internal.DDataRememberEntitiesProvider@127cdce7
| [DEBUG] [08/05/2021 17:58:18.549] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Request shard [1] home. Coordinator [None]
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [start-entity-2CoordinatorState].
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-all].
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator/$d] ReadMajorityPlus [start-entity-2CoordinatorState] [1] of [1].
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.default-dispatcher-6] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Initial coordinator is empty.
| [INFO] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.default-dispatcher-6] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: ShardCoordinator was moved to the active state with [0] shards
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.default-dispatcher-6] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Full ShardCoordinator initial state State(Map())
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.default-dispatcher-10] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Received [0] remembered shard ids (after state initialized)
| [DEBUG] [08/05/2021 17:58:18.550] [StartEntitySpec-akka.actor.default-dispatcher-10] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RememberEntityTimeout] with generation [1]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-16] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: ShardRegion registered: [Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491]]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-16] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Storing new coordinator state [State(Map())]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Update for key [start-entity-2CoordinatorState].
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator/$e] WriteMajorityPlus [start-entity-2CoordinatorState] [1] of [1].
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-16] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: The coordinator state was successfully updated with ShardRegionRegistered(Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491])
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-16] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: New coordinator state after [ShardRegionRegistered(Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491])]: [State(Map())]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-2] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RegisterRetry] with generation [4]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Requesting shard home for [1] from coordinator at [Actor[akka://StartEntitySpec/system/sharding/start-entity-2Coordinator/singleton/coordinator#1806216451]]. [1] buffered messages.
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-15] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Storing new coordinator state [State(Map())]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.default-dispatcher-15] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Remembering shard allocation [1]
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Update for key [start-entity-2CoordinatorState].
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Update for key [shard-start-entity-2-all].
| [DEBUG] [08/05/2021 17:58:18.815] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator/$f] WriteMajorityPlus [start-entity-2CoordinatorState] [1] of [1].
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-12] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator/RememberEntitiesStore] The coordinator shards state was successfully updated with 1
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-14] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: The coordinator state was successfully updated with ShardHomeAllocated(1,Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491]), waiting for remember shard update
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-14] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: The ShardCoordinator saw remember shard start successfully written ShardHomeAllocated(1,Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491])
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-14] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RememberEntityTimeout] with generation [3]
| [DEBUG] [akkaShardAllocated][08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-14] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: Shard [1] allocated at [Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491]]
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.default-dispatcher-14] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2Coordinator/singleton/coordinator] start-entity-2: New coordinator state after [ShardHomeAllocated(1,Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491])]: [State(Map(1 -> Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491]))]
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Host Shard [1] 
| [DEBUG] [akkaShardStarted][08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Starting shard [1] in region
| [DEBUG] [08/05/2021 17:58:18.816] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Shard [1] located at [Actor[akka://StartEntitySpec/system/sharding/start-entity-2#835777491]]
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Waiting for load of entity ids using [Actor[akka://StartEntitySpec/system/sharding/start-entity-2/1/RememberEntitiesStore#1667526960]] to complete
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.default-dispatcher-15] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1/RememberEntitiesStore] Starting up DDataRememberEntitiesStore, read timeout: [2.000 s], write timeout: [5.000 s], majority min cap: [5]
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-1-0].
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.default-dispatcher-15] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1/RememberEntitiesStore] Got request from shard, waiting for all remembered entities to arrive
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-1-1].
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-1-2].
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-1-3].
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Get for key [shard-start-entity-2-1-4].
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.default-dispatcher-14] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1/RememberEntitiesStore] Shard waiting for remembered entities, sending remembered and going idle
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RememberEntityTimeout] with generation [1]
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Shard initialized
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Shard was initialized [1]
| [DEBUG] [08/05/2021 17:58:18.817] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2] start-entity-2: Deliver [1] buffered messages for shard [1]
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Buffering message [java.lang.String] to [1] and starting actor
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Message of type [akka.cluster.sharding.StartEntitySpec$EntityEnvelope] for entity [1] buffered
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Remember update [1] and stops [] triggered
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/replicator] Received Update for key [shard-start-entity-2-1-4].
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.default-dispatcher-15] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1/RememberEntitiesStore] The DDataShard state was successfully updated for [Set(Started(1))]
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Update done for ids, started [1], stopped []. Duration 0 ms
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [TimerScheduler(akka://StartEntitySpec)] Cancel timer [RememberEntityTimeout] with generation [2]
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Started entity [Actor[akka://StartEntitySpec/system/sharding/start-entity-2/1/1#895083323]] with entity id [1] in shard [1]
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Sending message buffer for entity [1] ([1] messages)
| [DEBUG] [08/05/2021 17:58:18.818] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Delivering message of type [java.lang.String] to [1]
| [DEBUG] [08/05/2021 17:58:18.819] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Update complete, no pending updates, going to idle
| [DEBUG] [08/05/2021 17:58:18.819] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Request to start entity [1] (Already started)
| [DEBUG] [08/05/2021 17:58:18.819] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: Entity [1] stopped without passivating, will restart after backoff
| [DEBUG] [08/05/2021 17:58:18.819] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:18.920] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.021] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.122] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.224] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.325] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.425] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.526] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.628] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.729] [StartEntitySpec-akka.actor.internal-dispatcher-5] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.830] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:19.931] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.032] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.133] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.234] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.335] [StartEntitySpec-akka.actor.internal-dispatcher-4] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.436] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.537] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.637] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.738] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.839] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:20.940] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.041] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.143] [StartEntitySpec-akka.actor.internal-dispatcher-2] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.244] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.345] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.446] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.548] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.649] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.750] [StartEntitySpec-akka.actor.internal-dispatcher-3] [akka://StartEntitySpec@10.1.0.49:40037/system/sharding/start-entity-2/1] start-entity-2: GetCurrentShardState, full state: [{1=WaitingForRestart}], active: [Set()]
| [DEBUG] [08/05/2021 17:58:21.751] [pool-1-thread-1-ScalaTest-running-StartEntitySpec] [WithLogCapturing(akka://StartEntitySpec)] Logging finished for test [StartEntity while the entity is waiting for restart should restart it immediately]
<-- [StartEntity while the entity is waiting for restart should restart it immediately] End of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: Set() did not equal Set("1"))]
[info] - should restart it immediately *** FAILED *** (3 seconds, 224 milliseconds)
[info]   Set() did not equal Set("1") (StartEntitySpec.scala:145)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.cluster.sharding.StartEntitySpec.$anonfun$new$6(StartEntitySpec.scala:145)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[info]   at akka.cluster.sharding.StartEntitySpec.$anonfun$new$5(StartEntitySpec.scala:141)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at akka.testkit.WithLogCapturing.$anonfun$withFixture$1(WithLogCapturing.scala:36)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
[info]   at akka.testkit.WithLogCapturing.withFixture(WithLogCapturing.scala:34)
[info]   at akka.testkit.WithLogCapturing.withFixture$(WithLogCapturing.scala:21)
[info]   at akka.cluster.sharding.StartEntitySpec.withFixture(StartEntitySpec.scala:65)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
```

</details>

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3308519328?check_suite_focus=true#step:5:22699

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/3354993134?check_suite_focus=true
