### ISSUE TITLE
[failed] InmemPersistentActorSpec able to opt-out from stashing messages

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30498]
https://github.com/akka/akka/pull/30449/checks?check_run_id=3262134926#step:5:8234

```
[info] - must be able to opt-out from stashing messages until all events have been processed *** FAILED *** (4 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected y, found x-1
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.persistence.PersistentActorSpec.$anonfun$new$23(PersistentActorSpec.scala:1217)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
...
[info] akka.persistence.InmemPersistentActorSpec *** ABORTED *** (115 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected List(a-1, a-2), found y
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.persistence.PersistentActorSpec.beforeEach(PersistentActorSpec.scala:957)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:233)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
[info]   at akka.persistence.PersistenceSpec.runTest(PersistenceSpec.scala:22)
...
```

**Comment by ignasi35** [comment]
The description lists two issues. #30499 only focused on the first one.

```
[info] akka.persistence.InmemPersistentActorSpec *** ABORTED *** (115 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected List(a-1, a-2), found y
[info]   at scala.Predef$.assert(Predef.scala:279)
```

Still occurs. See https://github.com/akka/akka/runs/3264634773?check_suite_focus=true#step:5:563

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3308519328?check_suite_focus=true#step:5:3577

```
[info]   java.lang.AssertionError: assertion failed: expected List(a-1, a-2), found x
3579
[info]   at scala.Predef$.assert(Predef.scala:279)
3580
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
3581
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
3582
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
3583
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
3584
[info]   at akka.persistence.PersistentActorSpec.beforeEach(PersistentActorSpec.scala:957)
3585
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:233)
3586
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
3587
[info]   at akka.persistence.PersistenceSpec.runTest(PersistenceSpec.scala:22)
```

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/3340083708?check_suite_focus=true
