### ISSUE TITLE
LazySourceSpec: never construct the source when there was no demand

### ISSUE THREAD

**Issue by raboof** [akka/akka#30492]
Mulitple failures in `LazySourceSpec` in https://github.com/akka/akka/pull/30449/checks?check_run_id=3252611503#step:6:20766:

```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:141)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$35(LazySourceSpec.scala:141)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$34(LazySourceSpec.scala:129)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

```
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 13 milliseconds)
[info]   true did not equal false (LazySourceSpec.scala:292)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$75(LazySourceSpec.scala:292)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$74(LazySourceSpec.scala:277)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by patriknw** [comment]
This is probably the same as https://github.com/akka/akka/issues/28689

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3308519328?check_suite_focus=true#step:5:14901

**Comment by patriknw** [comment]
Failed again, after the fix.

https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:13496

```
[WARN] [08/13/2021 06:40:00.453] [FlowFlatMapPrefixSpec-akka.actor.default-dispatcher-10] [akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] received dead letter from Actor[akka://FlowFlatMapPrefixSpec/system/testProbe-2351#89270960]: GetChildren
13493
[INFO] [akkaDeadLetter][08/13/2021 06:40:00.454] [FlowFlatMapPrefixSpec-akka.actor.default-dispatcher-10] [akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] Message [akka.stream.impl.StreamSupervisor$GetChildren$] from Actor[akka://FlowFlatMapPrefixSpec/system/testProbe-2351#89270960] to Actor[akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://FlowFlatMapPrefixSpec/user/StreamSupervisor*] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
13494
--- Stream actors debug dump ---
13495
Stream is completed. No debug information is available
13496
[info] - must early downstream cancellation is later handed out to materialized flow *** FAILED *** (2 seconds, 15 milliseconds)
13497
[info]   Some(Failure(akka.stream.NeverMaterializedException: Downstream canceled without triggering lazy source materialization)) was not empty (FlowFlatMapPrefixSpec.scala:345)
13498
[info]   org.scalatest.exceptions.TestFailedException:
13499
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
13500
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
13501
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6834)
13502
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$79(FlowFlatMapPrefixSpec.scala:345)
13503
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
13504
[info]   at akka.stream.scaladsl.FlowFlatMapPrefixSpec.$anonfun$new$78(FlowFlatMapPrefixSpec.scala:317)
13505
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
13506
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
13507
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
13508
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
13509
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
13510
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
13511
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
13512
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
13513
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:33)
13514
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
13515
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
13516
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
13517
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
13518
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
13519
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
13520
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
13521
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
13522
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
13523
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
13524
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
13525
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
13526
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
13527
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
13528
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
13529
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
13530
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
13531
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
13532
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
13533
[info]   at org.scalatest.Suite.run(Suite.scala:1112)
13534
[info]   at org.scalatest.Suite.run$(Suite.scala:1094)
13535
[info]   at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
13536
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
13537
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
13538
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
13539
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
13540
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
13541
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
13542
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
13543
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
13544
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
13545
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
13546
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
13547
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
13548
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13549
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
13550
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
13551
[info]   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by raboof** [comment]
That looks like a different failure, though? (`early downstream cancellation is later handed out to materialized flow`) - nonetheless perhaps related.

**Comment by patriknw** [comment]
I must have copied the wrong failure. This is it: https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:14937

```
[WARN] [08/13/2021 06:42:09.362] [LazySourceSpec-akka.actor.default-dispatcher-6] [akka://LazySourceSpec/user/StreamSupervisor*] received dead letter from Actor[akka://LazySourceSpec/system/testProbe-3618#-1345851592]: GetChildren
14935
--- Stream actors debug dump ---
14936
Stream is completed. No debug information is available
14937
[info] - must never construct the source when there was no demand *** FAILED *** (2 seconds, 10 milliseconds)
14938
[info]   true did not equal false (LazySourceSpec.scala:135)
14939
[info]   org.scalatest.exceptions.TestFailedException:
14940
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
14941
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
14942
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$35(LazySourceSpec.scala:135)
14943
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
14944
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$34(LazySourceSpec.scala:125)
14945
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
14946
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
14947
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
14948
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
14949
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
14950
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
14951
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
14952
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
14953
[info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:33)
14954
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
```

**Comment by pvlugter** [comment]
Another https://github.com/akka/akka/runs/3327848584?check_suite_focus=true#step:5:14802

**Comment by pvlugter** [comment]
There's also #30321
