### ISSUE TITLE
[failed] DataCenterReplicatedShardingSpec Failed to stop

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30501]
https://github.com/akka/akka/runs/3264140786?check_suite_focus=true#step:5:4468

`Failed to stop [DataCenterReplicatedShardingSpec] within [10 seconds]`

```

[info] Replicated sharding
[info] - should form a one node cluster (1 second, 506 milliseconds)
[info] - should start replicated sharding on both nodes (25 milliseconds)
[info] - should forward to replicas (2 seconds, 33 milliseconds)
[info] akka.cluster.sharding.typed.DataCenterReplicatedShardingSpec *** ABORTED *** (14 seconds, 633 milliseconds)
[info]   java.lang.RuntimeException: Failed to stop [DataCenterReplicatedShardingSpec] within [10 seconds] 
[info] -> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
[info]    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 24 children
[info]    |   ⌊-> IO-DNS RepointableActorRef class akka.io.SimpleDnsManager status=0 1 children
[info]    |   |   ⌊-> inet-address RoutedActorRef class akka.routing.RouterPoolActor status=0 4 children
[info]    |   |       ⌊-> $a LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]    |   |       ⌊-> $b LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]    |   |       ⌊-> $c LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]    |   |       ⌊-> $d LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]    |   ⌊-> IO-TCP RepointableActorRef class akka.io.TcpManager status=0 1 children
[info]    |   |   ⌊-> selectors RoutedActorRef class akka.routing.RouterPoolActor status=0 1 children
[info]    |   |       ⌊-> $a LocalActorRef class akka.io.SelectionHandler status=0 1 children
[info]    |   |           ⌊-> 0 LocalActorRef class akka.io.TcpListener status=0 no children
[info]    |   ⌊-> IntSet%7CDC-BShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children
[info]    |   |   ⌊-> StreamSupervisor-65 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]    |   |   ⌊-> StreamSupervisor-66 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 6 children
[info]    |   |   |   ⌊-> remote-0-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-2-0-unnamed RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-3-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-4-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-5-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-6-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   ⌊-> StreamSupervisor-67 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 1 children
[info]    |   |       ⌊-> remoteControl-1-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   ⌊-> StringSet%7CDC-BShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> akka.persistence.no-snapshot-store RepointableActorRef class akka.persistence.snapshot.NoSnapshotStore status=0 no children
[info]    |   ⌊-> akka.persistence.testkit.journal RepointableActorRef class akka.persistence.testkit.PersistenceTestKitPlugin status=0 1 children
[info]    |   |   ⌊-> $a LocalActorRef class akka.persistence.journal.AsyncWriteJournal$Resequencer status=0 no children
[info]    |   ⌊-> cluster RepointableActorRef class akka.cluster.ClusterDaemon status=0 2 children
[info]    |   |   ⌊-> core LocalActorRef class akka.cluster.ClusterCoreSupervisor status=0 2 children
[info]    |   |   |   ⌊-> daemon LocalActorRef class akka.cluster.ClusterCoreDaemon status=0 2 children
[info]    |   |   |   |   ⌊-> crossDcHeartbeatSender LocalActorRef class akka.cluster.CrossDcHeartbeatSender status=0 no children
[info]    |   |   |   |   ⌊-> heartbeatSender LocalActorRef class akka.cluster.ClusterHeartbeatSender status=0 no children
[info]    |   |   |   ⌊-> publisher LocalActorRef class akka.cluster.ClusterDomainEventPublisher status=0 no children
[info]    |   |   ⌊-> heartbeatReceiver LocalActorRef class akka.cluster.ClusterHeartbeatReceiver status=0 no children
[info]    |   ⌊-> clusterCommandManager RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> clusterEventBusListener RepointableActorRef class akka.cluster.ClusterReadView$$anon$1 status=0 no children
[info]    |   ⌊-> clusterReceptionist RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 1 children
[info]    |   |   ⌊-> replicator LocalActorRef class akka.cluster.ddata.Replicator status=0 no children
[info]    |   ⌊-> clusterStateSubscriptions RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
[info]    |   ⌊-> directReplication-1 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> directReplication-2 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> eventStreamUnsubscriber-26 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[info]    |   ⌊-> eventstream RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> log1-Slf4jLogger RepointableActorRef class akka.event.slf4j.Slf4jLogger status=0 no children
[info]    |   ⌊-> log2-SilenceAllTestEventListener RepointableActorRef class akka.testkit.SilenceAllTestEventListener status=0 no children
[info]    |   ⌊-> recoveryPermitter RepointableActorRef class akka.persistence.RecoveryPermitter status=0 no children
[info]    |   ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
[info]    |   ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children
[info]    |   ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[info]    |   ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 3 children
[info]    |       ⌊-> IntSet%7CDC-BCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 2 children
[info]    |       |   ⌊-> $a LocalActorRef class akka.cluster.singleton.ClusterSingletonManager$Internal$OldestChangedBuffer status=0 no children
[info]    |       |   ⌊-> singleton LocalActorRef class akka.pattern.internal.BackoffOnStopSupervisor status=0 1 children
[info]    |       |       ⌊-> coordinator LocalActorRef class akka.cluster.sharding.DDataShardCoordinator status=0 no children
[info]    |       ⌊-> StringSet%7CDC-BCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 2 children
[info]    |       |   ⌊-> $a LocalActorRef class akka.cluster.singleton.ClusterSingletonManager$Internal$OldestChangedBuffer status=0 no children
[info]    |       |   ⌊-> singleton LocalActorRef class akka.pattern.internal.BackoffOnStopSupervisor status=0 1 children
[info]    |       |       ⌊-> coordinator LocalActorRef class akka.cluster.sharding.DDataShardCoordinator status=0 no children
[info]    |       ⌊-> replicator LocalActorRef class akka.cluster.ddata.Replicator status=0 no children
[info]    ⌊-> user LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]   at akka.actor.testkit.typed.internal.TestKitUtils$.shutdown(TestKitUtils.scala:89)
[info]   at akka.actor.testkit.typed.scaladsl.ActorTestKit$.shutdown(ActorTestKit.scala:162)
[info]   at akka.cluster.sharding.typed.ReplicatedShardingSpec.afterAll(ReplicatedShardingSpec.scala:241)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
```

**Comment by ignasi35** [comment]
https://github.com/akka/akka/runs/3264634360?check_suite_focus=true#step:5:508

**Comment by johanandren** [comment]
Again, https://github.com/akka/akka/pull/30562/checks?check_run_id=3404158246, note that the test cases in `DataCenterReplicatedShardingSpec` pass fine, it is about termination from `afterAll`

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3416768494?check_suite_focus=true#step:5:30231

**Comment by raboof** [comment]
https://github.com/akka/akka/pull/30649/checks?check_run_id=3533459607

**Comment by patriknw** [comment]
Closing since we haven't seen this in a while, and it's "only" some shutdown timeout.
