### ISSUE TITLE
[failed] NormalReplicatedShardingSpec failed to stop

### ISSUE THREAD

**Issue by ignasi35** [akka/akka#30502]
(similar to https://github.com/akka/akka/issues/30501)

https://github.com/akka/akka/runs/3264228223?check_suite_focus=true#step:5:4469

```

[info] NormalReplicatedShardingSpec:
[info] Replicated sharding
[info] - should form a one node cluster (1 second, 22 milliseconds)
[info] - should start replicated sharding on both nodes (42 milliseconds)
[info] - should forward to replicas (4 seconds, 175 milliseconds)
[info] akka.cluster.sharding.typed.NormalReplicatedShardingSpec *** ABORTED *** (15 seconds, 246 milliseconds)
[info]   java.lang.RuntimeException: Failed to stop [NormalReplicatedShardingSpec] within [10 seconds] 
[info] -> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
[info]    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 27 children
[info]        ⌊-> IO-DNS RepointableActorRef class akka.io.SimpleDnsManager status=0 1 children
[info]        |   ⌊-> inet-address RoutedActorRef class akka.routing.RouterPoolActor status=0 4 children
[info]        |       ⌊-> $a LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $b LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $c LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        |       ⌊-> $d LocalActorRef class akka.io.InetAddressDnsResolver status=0 no children
[info]        ⌊-> IO-TCP RepointableActorRef class akka.io.TcpManager status=0 1 children
[info]        |   ⌊-> selectors RoutedActorRef class akka.routing.RouterPoolActor status=0 1 children
[info]        |       ⌊-> $a LocalActorRef class akka.io.SelectionHandler status=0 3 children
[info]        |           ⌊-> 0 LocalActorRef class akka.io.TcpListener status=0 no children
[info]        |           ⌊-> 1 LocalActorRef class akka.io.TcpIncomingConnection status=0 no children
[info]        |           ⌊-> 2 LocalActorRef class akka.io.TcpIncomingConnection status=0 no children
[info]        ⌊-> IntSet%7CDC-AShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> IntSet%7CDC-BShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children
[info]        |   ⌊-> StreamSupervisor-24 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]        |   ⌊-> StreamSupervisor-25 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 5 children
[info]        |   |   ⌊-> remote-0-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]        |   |   ⌊-> remote-10-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=2 no children
[info]        |   |   ⌊-> remote-7-0-map RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]        |   |   ⌊-> remote-8-0-map RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]        |   |   ⌊-> remote-9-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=2 no children
[info]        |   ⌊-> StreamSupervisor-26 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]        ⌊-> StringSet%7CDC-AShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> StringSet%7CDC-BShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> akka.persistence.no-snapshot-store RepointableActorRef class akka.persistence.snapshot.NoSnapshotStore status=0 no children
[info]        ⌊-> akka.persistence.testkit.journal RepointableActorRef class akka.persistence.testkit.PersistenceTestKitPlugin status=0 1 children
[info]        |   ⌊-> $a LocalActorRef class akka.persistence.journal.AsyncWriteJournal$Resequencer status=0 no children
[info]        ⌊-> clusterCommandManager RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> clusterStateSubscriptions RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> directReplication-1 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> directReplication-2 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> directReplication-3 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> directReplication-4 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> eventStreamUnsubscriber-11 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[info]        ⌊-> eventstream RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> log1-Slf4jLogger RepointableActorRef class akka.event.slf4j.Slf4jLogger status=0 no children
[info]        ⌊-> log2-SilenceAllTestEventListener RepointableActorRef class akka.testkit.SilenceAllTestEventListener status=0 no children
[info]        ⌊-> recoveryPermitter RepointableActorRef class akka.persistence.RecoveryPermitter status=0 no children
[info]        ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
[info]        ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children
[info]        ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[info]        ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 no children
[info]        ⌊-> testProbe-58 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> testProbe-59 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]        ⌊-> testProbe-60 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]   at akka.actor.testkit.typed.internal.TestKitUtils$.shutdown(TestKitUtils.scala:89)
[info]   at akka.actor.testkit.typed.scaladsl.ActorTestKit$.shutdown(ActorTestKit.scala:162)
[info]   at akka.actor.testkit.typed.scaladsl.ActorTestKit.shutdownTestKit(ActorTestKit.scala:214)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.afterAll(ScalaTestWithActorTestKit.scala:80)
[info]   at akka.cluster.sharding.typed.ReplicatedShardingSpec.afterAll(ReplicatedShardingSpec.scala:237)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:962)
[info]   at org.scalatest.Status.withAfterEffect(Status.scala:373)
[info]   at org.scalatest.Status.withAfterEffect$(Status.scala:371)
[info]   at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:863)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:224)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.cluster.sharding.typed.ReplicatedShardingSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ReplicatedShardingSpec.scala:226)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[info]   at akka.cluster.sharding.typed.ReplicatedShardingSpec.run(ReplicatedShardingSpec.scala:226)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:34571

**Comment by patriknw** [comment]
Closing since we haven't seen this in a while, and it's "only" some shutdown timeout.
