### ISSUE TITLE
failed: LazySourceSpec - must provide attributes to inner source

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30519]
https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8995

```
[info] - must provide attributes to inner source *** FAILED *** (2 seconds, 28 milliseconds)
[info]   The future returned an exception of type: akka.stream.StreamDetachedException, with message: Stream cancelled before Source Future completed. (LazySourceSpec.scala:438)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$114(LazySourceSpec.scala:438)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.LazySourceSpec.$anonfun$new$113(LazySourceSpec.scala:430)
```

**Comment by patriknw** [comment]
Note that we also have https://github.com/akka/akka/issues/30492 and https://github.com/akka/akka/issues/28689 but I think this is slightly different

**Comment by raboof** [comment]
I think this is a duplicate of #30481 - https://jenkins.akka.io:8498/job/akka-nightly-jdk8/8995 was building e127d1916f772de70bd6c144a9e04e1821e3b834 which didn't have a3447b43404e311fca329c205a2b8284027863e8 yet

**Comment by patriknw** [comment]
ok, let's close
