### ISSUE TITLE
failed: UnstashingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30524]
With Scala3

https://github.com/akka/akka/pull/30523/checks?check_run_id=3301313423

```
--> [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with backoff supervision] Start of log messages of test that [Failed(java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(ERROR),None,None,Some(Supervisor RestartSupervisor saw failure: unstash-fail),None,Some(class akka.actor.testkit.typed.TestException),Map(),true,None).)]
1087
2021-08-11 13:40:45,284 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started MDC: {}
1088
2021-08-11 13:40:45,289 DEBUG UnstashingSpec  - Starting ActorTestKit MDC: {}
1089
2021-08-11 13:40:45,294 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with initial Behaviors.same] MDC: {}
1090
2021-08-11 13:40:45,297 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with initial Behaviors.same] that [Succeeded] MDC: {}
1091
2021-08-11 13:40:45,298 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with intermediate Behaviors.same] MDC: {}
1092
2021-08-11 13:40:45,299 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with intermediate Behaviors.same] that [Succeeded] MDC: {}
1093
2021-08-11 13:40:45,299 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with supervised initial Behaviors.same] MDC: {}
1094
2021-08-11 13:40:45,300 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with supervised initial Behaviors.same] that [Succeeded] MDC: {}
1095
2021-08-11 13:40:45,301 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with supervised intermediate Behaviors.same] MDC: {}
1096
2021-08-11 13:40:45,302 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with supervised intermediate Behaviors.same] that [Succeeded] MDC: {}
1097
2021-08-11 13:40:45,302 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with Behaviors.same when switching Behavior while unstashing one] MDC: {}
1098
2021-08-11 13:40:45,305 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must work with Behaviors.same when switching Behavior while unstashing one] that [Succeeded] MDC: {}
1099
2021-08-11 13:40:45,306 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PostStop to the latest unstashed behavior on failure] MDC: {}
1100
2021-08-11 13:40:45,317 ERROR akka.actor.SupervisorStrategy  - unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user, sourceActorSystem=UnstashingSpec}
1101
akka.actor.testkit.typed.TestException: unstash-fail
1102
2021-08-11 13:40:45,317 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PostStop to the latest unstashed behavior on failure] that [Succeeded] MDC: {}
1103
2021-08-11 13:40:45,317 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PostStop to the latest unstashed behavior on failure with stop supervision] MDC: {}
1104
2021-08-11 13:40:45,325 ERROR akka.actor.typed.Behavior$  - Supervisor StopSupervisor saw failure: unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user/$g, sourceActorSystem=UnstashingSpec}
1105
akka.actor.testkit.typed.TestException: unstash-fail
1106
2021-08-11 13:40:45,325 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PostStop to the latest unstashed behavior on failure with stop supervision] that [Succeeded] MDC: {}
1107
2021-08-11 13:40:45,325 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with restart supervision] MDC: {}
1108
2021-08-11 13:40:45,328 ERROR akka.actor.typed.Behavior$  - Supervisor RestartSupervisor saw failure: unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user/$h, sourceActorSystem=UnstashingSpec}
1109
akka.actor.testkit.typed.TestException: unstash-fail
1110
2021-08-11 13:40:45,333 ERROR akka.actor.typed.Behavior$  - Supervisor RestartSupervisor saw failure: unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user/$h, sourceActorSystem=UnstashingSpec}
1111
akka.actor.testkit.typed.TestException: unstash-fail
1112
2021-08-11 13:40:45,333 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with restart supervision] that [Succeeded] MDC: {}
1113
2021-08-11 13:40:45,333 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with restart supervision and slow stopping child] MDC: {}
1114
2021-08-11 13:40:45,336 ERROR akka.actor.typed.Behavior$  - Supervisor RestartSupervisor saw failure: unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user/$i, sourceActorSystem=UnstashingSpec}
1115
akka.actor.testkit.typed.TestException: unstash-fail
1116
2021-08-11 13:40:45,337 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with restart supervision and slow stopping child] that [Succeeded] MDC: {}
1117
2021-08-11 13:40:45,337 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging started for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with backoff supervision] MDC: {}
1118
2021-08-11 13:40:45,340 ERROR akka.actor.typed.Behavior$  - Supervisor RestartSupervisor saw failure [1]: unstash-fail MDC: {akkaAddress=akka://UnstashingSpec, akkaSource=akka://UnstashingSpec/user/$j, sourceActorSystem=UnstashingSpec}
1119
akka.actor.testkit.typed.TestException: unstash-fail
1120
2021-08-11 13:40:48,456 INFO  akka.actor.testkit.typed.scaladsl.LogCapturing  - Logging finished for test [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with backoff supervision] that [Failed(java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(ERROR),None,None,Some(Supervisor RestartSupervisor saw failure: unstash-fail),None,Some(class akka.actor.testkit.typed.TestException),Map(),true,None).)] MDC: {}
1121
<-- [akka.actor.typed.scaladsl.UnstashingSpec: Unstashing must signal PreRestart to the latest unstashed behavior on failure with backoff supervision] End of log messages of test that [Failed(java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(ERROR),None,None,Some(Supervisor RestartSupervisor saw failure: unstash-fail),None,Some(class akka.actor.testkit.typed.TestException),Map(),true,None).)]
1122
[info] - must signal PreRestart to the latest unstashed behavior on failure with backoff supervision *** FAILED *** (3 seconds, 123 milliseconds)
1123
[info]   java.lang.AssertionError: Timeout (3 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(ERROR),None,None,Some(Supervisor RestartSupervisor saw failure: unstash-fail),None,Some(class akka.actor.testkit.typed.TestException),Map(),true,None).
1124
[info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:103)
1125
[info]   at akka.actor.typed.scaladsl.UnstashingSpec.testPreRestart$3(StashSpec.scala:504)
1126
[info]   at akka.actor.typed.scaladsl.UnstashingSpec.f$proxy12$1(StashSpec.scala:537)
1127
[info]   at akka.actor.typed.scaladsl.UnstashingSpec.$init$$$anonfun$11$$anonfun$10(StashSpec.scala:529)
```

**Comment by patriknw** [comment]
this was probably something I changed in that PR
