### ISSUE TITLE
EventStreamSpec: An EventStream must unwatch an actor from unsubscriber when that actor unsubscribes from channels it subscribed

### ISSUE THREAD

**Issue by raboof** [akka/akka#30528]
https://github.com/akka/akka/pull/30525/checks?check_run_id=3303159197

```
[info]   java.lang.AssertionError: assertion failed: timeout (1 second) during fishForMessage, hint: expected debug message prefix: watching Actor[akka://EventStreamSpec/system/testProbe-61#1397543033]
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.recv$1(TestKit.scala:512)
[info]   at akka.testkit.TestKitBase.fishForMessage(TestKit.scala:516)
[info]   at akka.testkit.TestKitBase.fishForMessage$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:973)
[info]   at akka.event.EventStreamSpec.fishForDebugMessage(EventStreamSpec.scala:434)
[info]   at akka.event.EventStreamSpec.f$proxy18$1(EventStreamSpec.scala:402)
[info]   at akka.event.EventStreamSpec.$init$$$anonfun$18$$anonfun$17(EventStreamSpec.scala:390)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3506856659?check_suite_focus=true#step:5:1788
