### ISSUE TITLE
failed: NullEmptyStateTest - handleNullState

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30527]
https://github.com/akka/akka/runs/3308519328?check_suite_focus=true#step:5:23807

```
--> [akka.persistence.typed.javadsl.NullEmptyStateTest: handleNullState] Start of log messages of test that failed with expected eventHandler:one:two, found onRecoveryCompleted:one
23780
2021-08-12 06:56:04,088 [INFO ] [akka.actor.testkit.typed.javadsl.LogCapturing] [] [] [] [] - Logging started for test [akka.persistence.typed.javadsl.NullEmptyStateTest: handleNullState] 
23781
2021-08-12 06:56:04,091 [WARN ] [akka.persistence.Persistence] [] [Persistence(akka://NullEmptyStateTest)] [] [] - No default snapshot store configured! To configure a default snapshot-store plugin set the `akka.persistence.snapshot-store.plugin` key. For details see 'reference.conf' 
23782
2021-08-12 06:56:04,093 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [get-permit] [a] - Initializing snapshot recovery: Recovery(SnapshotSelectionCriteria(9223372036854775807,9223372036854775807,0,0),9223372036854775807,9223372036854775807) 
23783
2021-08-12 06:56:04,094 [DEBUG] [akka.persistence.typed.javadsl.NullEmptyStateTest$NullEmptyState] [] [akka://NullEmptyStateTest/user/$a] [] [] - Snapshot recovered from 0 Map() VersionVector() 
23784
2021-08-12 06:56:04,094 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [replay-evt] [a] - Replaying events: from: 1, to: 9223372036854775807 
23785
2021-08-12 06:56:04,095 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [replay-evt] [a] - Recovery successful, recovered until sequenceNr: [0] 
23786
2021-08-12 06:56:04,095 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [replay-evt] [a] - Returning recovery permit, reason: replay completed successfully 
23787
2021-08-12 06:56:04,096 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [replay-evt] [a] - Recovery for persistenceId [PersistenceId(a)] took 1.404 ms 
23788
2021-08-12 06:56:04,097 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [get-permit] [a] - Initializing snapshot recovery: Recovery(SnapshotSelectionCriteria(9223372036854775807,9223372036854775807,0,0),9223372036854775807,9223372036854775807) 
23789
2021-08-12 06:56:04,099 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$a] [running-cmd] [a] - Handled command [java.lang.String], resulting effect: [PersistNothing], side effects: [1] 
23790
2021-08-12 06:56:04,099 [DEBUG] [akka.persistence.typed.javadsl.NullEmptyStateTest$NullEmptyState] [] [akka://NullEmptyStateTest/user/$b] [] [] - Snapshot recovered from 0 Map() VersionVector() 
23791
2021-08-12 06:56:04,099 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [replay-evt] [a] - Replaying events: from: 1, to: 9223372036854775807 
23792
2021-08-12 06:56:04,100 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [replay-evt] [a] - Recovery successful, recovered until sequenceNr: [0] 
23793
2021-08-12 06:56:04,100 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [replay-evt] [a] - Returning recovery permit, reason: replay completed successfully 
23794
2021-08-12 06:56:04,100 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [replay-evt] [a] - Recovery for persistenceId [PersistenceId(a)] took 386.2 μs 
23795
2021-08-12 06:56:04,100 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [running-cmd] [a] - Handled command [java.lang.String], resulting effect: [Persist(java.lang.String)], side effects: [0] 
23796
2021-08-12 06:56:04,101 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [persist-evt] [a] - Received Journal response: WriteMessagesSuccessful after: 34900 nanos 
23797
2021-08-12 06:56:04,102 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [persist-evt] [a] - Received Journal response: WriteMessageSuccess(PersistentRepr(a,1,9c857fc5-9857-4e27-9b18-003cd5ff0992,0,None),26) after: 65200 nanos 
23798
2021-08-12 06:56:04,105 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [running-cmd] [a] - Handled command [java.lang.String], resulting effect: [Persist(java.lang.String)], side effects: [0] 
23799
2021-08-12 06:56:04,106 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$c] [get-permit] [a] - Initializing snapshot recovery: Recovery(SnapshotSelectionCriteria(9223372036854775807,9223372036854775807,0,0),9223372036854775807,9223372036854775807) 
23800
2021-08-12 06:56:04,106 [DEBUG] [akka.persistence.typed.javadsl.NullEmptyStateTest$NullEmptyState] [] [akka://NullEmptyStateTest/user/$c] [] [] - Snapshot recovered from 0 Map() VersionVector() 
23801
2021-08-12 06:56:04,106 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$c] [replay-evt] [a] - Replaying events: from: 1, to: 9223372036854775807 
23802
2021-08-12 06:56:04,107 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$b] [persist-evt] [a] - Received Journal response: WriteMessagesSuccessful after: 340602 nanos 
23803
2021-08-12 06:56:04,107 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$c] [replay-evt] [a] - Recovery successful, recovered until sequenceNr: [1] 
23804
2021-08-12 06:56:04,107 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$c] [replay-evt] [a] - Returning recovery permit, reason: replay completed successfully 
23805
2021-08-12 06:56:04,107 [DEBUG] [akka.persistence.typed.internal.EventSourcedBehaviorImpl] [] [akka://NullEmptyStateTest/user/$c] [replay-evt] [a] - Recovery for persistenceId [PersistenceId(a)] took 751.8 μs 
23806
<-- [akka.persistence.typed.javadsl.NullEmptyStateTest: handleNullState] End of log messages of test that failed with expected eventHandler:one:two, found onRecoveryCompleted:one
23807
[info] - handleNullState *** FAILED ***
23808
[info]   java.lang.AssertionError: expected eventHandler:one:two, found onRecoveryCompleted:one
23809
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
23810
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
23811
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
23812
[info]   at akka.persistence.typed.javadsl.NullEmptyStateTest.handleNullState(NullEmptyStateTest.java:105)
23813
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23814
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23815
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23816
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
23817
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
23818
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
23819
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
23820
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
23821
[info]   at akka.actor.testkit.typed.javadsl.LogCapturing$$anon$1.evaluate(LogCapturing.scala:49)
23822
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
23823
[info]   at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
23824
[info]   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
23825
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
23826
[info]   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
23827
[info]   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
23828
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
23829
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
23830
[info]   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
23831
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
23832
[info]   at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
23833
[info]   at org.junit.rules.RunRules.evaluate(RunRules.java:20)
23834
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
23835
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
23836
[info]   at org.junit.runners.Suite.runChild(Suite.java:128)
23837
[info]   at org.junit.runners.Suite.runChild(Suite.java:27)
23838
[info]   at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
23839
[info]   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
23840
[info]   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
23841
[info]   at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
23842
[info]   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
23843
[info]   at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
23844
[info]   at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
23845
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
23846
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
23847
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
23848
[info]   at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
23849
[info]   at org.scalatestplus.junit.JUnitSuiteLike.run(JUnitSuiteLike.scala:241)
23850
[info]   at org.scalatestplus.junit.JUnitSuiteLike.run$(JUnitSuiteLike.scala:229)
23851
[info]   at org.scalatestplus.junit.JUnitSuite.run(JUnitSuite.scala:71)
23852
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
23853
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
23854
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
23855
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
23856
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
23857
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
23858
[info]   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/3327848584?check_suite_focus=true#step:5:25393

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/3357979890?check_suite_focus=true#step:5:23494

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3368577663?check_suite_focus=true#step:5:23955
