### ISSUE TITLE
failed: ShutdownAfterJoinSeedNodesSpec - must be aborted after shutdown-after-unsuccessful-join-seed-nodes

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30534]
https://jenkins.akka.io:8498/job/akka-artery-cluster-tests/2809

```
Coroner Thread Count starts at 87 in akka.cluster.ShutdownAfterJoinSeedNodesSpec
[info] Joining seed nodes
[WARN] [08/13/2021 09:21:51.699] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-20] [akka://ShutdownAfterJoinSeedNodesSpec/system/cluster/core/daemon] unhandled message from Actor[akka://ShutdownAfterJoinSeedNodesSpec/deadLetters]: Leave(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:52911)
[WARN] [akkaJoinFailed][08/13/2021 09:21:55.967] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-24] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Cluster Node [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182] - Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:52911]
[WARN] [akkaJoinFailed][08/13/2021 09:21:56.391] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-5] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Cluster Node [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:47156] - Couldn't join seed nodes after [2] attempts, will try again. seed-nodes=[akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:52911, akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182]
[WARN] [08/13/2021 09:21:56.731] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-23] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Cluster Node [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:47156] - Joining of seed-nodes [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:52911, akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182] was unsuccessful after configured shutdown-after-unsuccessful-join-seed-nodes [5000 milliseconds]. Running CoordinatedShutdown.
[WARN] [08/13/2021 09:21:56.733] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-20] [akka://ShutdownAfterJoinSeedNodesSpec/system/cluster/core/daemon] unhandled message from Actor[akka://ShutdownAfterJoinSeedNodesSpec/deadLetters]: Leave(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:47156)
[WARN] [08/13/2021 09:21:56.734] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-3] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Could not unregister Cluster JMX MBean with name=akka:type=Cluster as it was not found. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
[WARN] [08/13/2021 09:21:56.739] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-19] [akka://ShutdownAfterJoinSeedNodesSpec/deadLetters] received dead letter from Actor[akka://ShutdownAfterJoinSeedNodesSpec/system/remoteFlushOnShutdown#-1019610041]: ActorSystemTerminating(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:47156#-1857818769812323086)
[WARN] [08/13/2021 09:21:56.740] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-19] [akka://ShutdownAfterJoinSeedNodesSpec/deadLetters] received dead letter from Actor[akka://ShutdownAfterJoinSeedNodesSpec/system/remoteFlushOnShutdown#-1019610041]: ActorSystemTerminating(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:47156#-1857818769812323086)
[WARN] [08/13/2021 09:21:57.586] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-21] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Cluster Node [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182] - Joining of seed-nodes [akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:52911, akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182] was unsuccessful after configured shutdown-after-unsuccessful-join-seed-nodes [5000 milliseconds]. Running CoordinatedShutdown.
[WARN] [08/13/2021 09:21:57.587] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-20] [akka://ShutdownAfterJoinSeedNodesSpec/system/cluster/core/daemon] unhandled message from Actor[akka://ShutdownAfterJoinSeedNodesSpec/deadLetters]: Leave(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182)
[WARN] [08/13/2021 09:21:57.587] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-3] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Could not unregister Cluster JMX MBean with name=akka:type=Cluster as it was not found. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
[WARN] [08/13/2021 09:21:58.607] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-20] [akka://ShutdownAfterJoinSeedNodesSpec/deadLetters] received dead letter from Actor[akka://ShutdownAfterJoinSeedNodesSpec/system/remoteFlushOnShutdown#1525062808]: ActorSystemTerminating(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182#805529606680984779)
[WARN] [08/13/2021 09:21:58.607] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-20] [akka://ShutdownAfterJoinSeedNodesSpec/deadLetters] received dead letter from Actor[akka://ShutdownAfterJoinSeedNodesSpec/system/remoteFlushOnShutdown#1525062808]: ActorSystemTerminating(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:42182#805529606680984779)
[WARN] [08/13/2021 09:22:06.752] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-3] [CoordinatedShutdown(akka://ShutdownAfterJoinSeedNodesSpec)] Coordinated shutdown phase [actor-system-terminate] timed out after 10000 milliseconds
[info] - must be aborted after shutdown-after-unsuccessful-join-seed-nodes *** FAILED *** (22 seconds, 29 milliseconds)
[info]   java.util.concurrent.TimeoutException: Future timed out after [15000 milliseconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:225)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
[info]   at scala.concurrent.Await$.result(package.scala:124)
[info]   at akka.cluster.ShutdownAfterJoinSeedNodesSpec.$anonfun$new$2(ShutdownAfterJoinSeedNodesSpec.scala:54)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
[info]   at org.scalatest.Suite.run(Suite.scala:1112)
[info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[info]   at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[WARN] [08/13/2021 09:22:13.757] [ShutdownAfterJoinSeedNodesSpec-akka.actor.default-dispatcher-7] [akka://ShutdownAfterJoinSeedNodesSpec/system/cluster/core/daemon] unhandled message from Actor[akka://ShutdownAfterJoinSeedNodesSpec/deadLetters]: Leave(akka://ShutdownAfterJoinSeedNodesSpec@127.0.1.1:49054)
[WARN] [08/13/2021 09:22:13.758] [ShutdownAfterJoinSeedNodesSpec-akka.actor.internal-dispatcher-22] [Cluster(akka://ShutdownAfterJoinSeedNodesSpec)] Could not unregister Cluster JMX MBean with name=akka:type=Cluster as it was not found. If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config
Failed to stop [ShutdownAfterJoinSeedNodesSpec] within [10 seconds] 
-> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 1 children
   ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 6 children
       ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children
       |   ⌊-> StreamSupervisor-213 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       |   ⌊-> StreamSupervisor-214 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 1 children
       |   |   ⌊-> remote-6-0-unnamed RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
       |   ⌊-> StreamSupervisor-215 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
       ⌊-> eventStreamUnsubscriber-75 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
       ⌊-> log1-TestEventListener RepointableActorRef class akka.testkit.TestEventListener status=0 no children
       ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
       ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children
       ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
Coroner Thread Count started at 87, ended at 26, peaked at 93 in akka.cluster.ShutdownAfterJoinSeedNodesSpec

```

**Comment by pvlugter** [comment]
Another failure:

https://github.com/akka/akka/actions/runs/3666546573/jobs/6198330718#step:5:2297

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5074626432/jobs/9115006644#step:5:2261

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6116021858/job/16600579115#step:5:2232

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11043104698/job/30676776092#step:5:2206

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11116174951/job/30885977069#step:5:2244

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/11197362646/job/31127237102#step:5:2285

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13665543007/job/38206028361#step:5:2179

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14208633287/job/39811550828#step:5:2244

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16130750116/job/45517563127#step:5:2222

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16208787898/job/45764803356#step:5:2248

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16307188110/job/46055665003#step:5:2257

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16405808684/job/46351576067#step:5:2236

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16610325570/job/46991938019#step:5:2300

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/21084890060/job/60646255040#step:7:2289

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/21121131371/job/60734074864#step:7:2251

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/22246338157/job/64361021905#step:7:2198

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/23774346088/job/69272734036#step:7:2291

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/24541246103/job/71747321614#step:7:2255

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/24617219971
