### ISSUE TITLE
failed: PersistentActorBoundedStashingSpec - should discard to deadletter

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30530]
https://github.com/akka/akka/runs/3319258651?check_suite_focus=true#step:5:3396

```
[info] - should discard to deadletter *** FAILED *** (114 milliseconds)
3397
[info]   java.lang.AssertionError: assertion failed: expected DeadLetter(Cmd(11),Actor[akka://SteppingInMemPersistentActorBoundedStashingSpec/system/testActor-50#472957317],Actor[akka://SteppingInMemPersistentActorBoundedStashingSpec/user/$a#-1786138833]), found DeadLetter(Cmd(10),Actor[akka://SteppingInMemPersistentActorBoundedStashingSpec/system/testActor-50#472957317],Actor[akka://SteppingInMemPersistentActorBoundedStashingSpec/user/$a#-1786138833])
3398
[info]   at scala.Predef$.assert(Predef.scala:279)
3399
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
3400
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
3401
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
3402
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
3403
[info]   at akka.persistence.DiscardStrategyPersistentActorBoundedStashingSpec.$anonfun$new$10(PersistentActorBoundedStashingSpec.scala:133)
3404
[info]   at akka.persistence.DiscardStrategyPersistentActorBoundedStashingSpec.$anonfun$new$10$adapted(PersistentActorBoundedStashingSpec.scala:133)
3405
[info]   at scala.collection.immutable.Range.foreach(Range.scala:190)
3406
[info]   at akka.persistence.DiscardStrategyPersistentActorBoundedStashingSpec.$anonfun$new$7(PersistentActorBoundedStashingSpec.scala:133)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3376123045?check_suite_focus=true#step:5:4572

**Comment by marcospereira** [comment]
https://github.com/akka/akka/runs/3462372094?check_suite_focus=true#step:5:4039
