### ISSUE TITLE
RestartSpec: A restart with backoff sink should allow using withMaxRestarts instead of minBackoff to determine the maxRestarts reset time

### ISSUE THREAD

**Issue by raboof** [akka/akka#30540]
https://github.com/akka/akka/runs/3339122220?check_suite_focus=true

```
[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(cancel),Actor[akka://RestartSpec/deadLetters]) after 49 millis
[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:769)
[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:742)
[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:973)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:678)
[info]   at akka.stream.scaladsl.RestartSpec.f$proxy21$1$$anonfun$1(RestartSpec.scala:570)
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
[info]   at akka.stream.scaladsl.RestartSpec.f$proxy21$2(RestartSpec.scala:576)
[info]   at akka.stream.scaladsl.RestartSpec.$init$$$anonfun$24$$anonfun$8(RestartSpec.scala:544)
```

**Comment by pvlugter** [comment]
Also https://github.com/akka/akka/runs/3325773970?check_suite_focus=true

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/1160214130

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3416768494?check_suite_focus=true#step:5:16763
