### ISSUE TITLE
Persistence: ClassCastException during replying events to rebalanced entities

### ISSUE THREAD

**Issue by ravkar** [akka/akka#30556]
I faced type casting issues (Integer to Long) during replying events for rebalanced entities using cluster sharding. 

**Description:** 

- there is simple counter service exposed via grpc with API described by proto:

```
	syntax = "proto3";
	service CounterService {
	    rpc Incr (Key) returns (Value) {}
	    rpc  Get (Key) returns (Value) {}
	}
	message Key {
	 string counterId = 1;
	}
	message Value {
	 int64 value = 1;
	}	
```	
- akka-persistence-jdbc with postgress db is used for persistence 
- persistent entities have simple state: Option[Long], newly created entities are initialized with State(None), first Incr command changes the state to Some(1) etc.

-  events are serialized with jackson-cbor

**Scenario to reproduce the issue:**

1.  start the single node of the cluster sharding (grpc service port 8101)
2. from external grpc client send a few Incr commands to entities 1 and 2
./grpcurl -d '{"counterId":"test-client:000000000001"}' -plaintext 127.0.0.1:8101 CounterService.Incr
./grpcurl -d '{"counterId":"test-client:000000000002"}' -plaintext 127.0.0.1:8101 CounterService.Incr
....
3. start second node of the cluster sharding (service port 8102  entity rebalance occurs to second node)
4. from external grpc client send some Incr commands to entity 1 and 2 as above.

Then I get the exception and no further operations are possible due to broken persistence (can't recover entity state from replied events):
```
> Akka.persistence.typed.internal.JournalFailureException: Exception during recovery. Last known sequence number [11]. PersistenceId [Counter|mdb-test-client:000000000002], due to: Exception during recovery while handling [com.mavoco.mdb.Counter$CounterBumped] with sequence number [11]. PersistenceId [Counter|mdb-test-client:000000000002], due to: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
> 	at akka.persistence.typed.internal.ReplayingEvents.onRecoveryFailure(ReplayingEvents.scala:267)
> 	at akka.persistence.typed.internal.ReplayingEvents.onJournalResponse(ReplayingEvents.scala:200)
> 	at akka.persistence.typed.internal.ReplayingEvents.onMessage(ReplayingEvents.scala:98)
> 	at akka.persistence.typed.internal.ReplayingEvents.onMessage(ReplayingEvents.scala:73)
> 	at akka.actor.typed.scaladsl.AbstractBehavior.receive(AbstractBehavior.scala:84)
> 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
> 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
> 	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
> 	at akka.persistence.typed.internal.EventSourcedBehaviorImpl$$anon$1.aroundReceive(EventSourcedBehaviorImpl.scala:207)
> 	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
> 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
> 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
> 	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
> 	at akka.actor.typed.internal.RestartSupervisor.aroundReceive(Supervision.scala:267)
> 	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
> 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
> 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
> 	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
> 	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:87)
> 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
> 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
> 	at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
> 	at akka.actor.typed.internal.SimpleSupervisor.aroundReceive(Supervision.scala:123)
> 	at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
> 	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
> 	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
> 	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
> 	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> Caused by: akka.persistence.typed.internal.JournalFailureException: Exception during recovery while handling [com.mavoco.mdb.Counter$CounterBumped] with sequence number [11]. PersistenceId [Counter|mdb-test-client:000000000002], due to: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
> 	at akka.persistence.typed.internal.ReplayingEvents.onRecoveryFailure(ReplayingEvents.scala:267)
> 	at akka.persistence.typed.internal.ReplayingEvents.onJournalResponse(ReplayingEvents.scala:180)
> 	... 36 common frames omitted
> Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
> 	at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:103)
> 	at com.mavoco.mdb.Counter$State.bump(Counter.scala:36)
> 	at com.mavoco.mdb.Counter$.handleEvent(Counter.scala:69)
> 	at com.mavoco.mdb.Counter$.$anonfun$updated$2(Counter.scala:91)
> 	at akka.persistence.typed.internal.ReplayingEvents.handleEvent$1(ReplayingEvents.scala:145)
> 	at akka.persistence.typed.internal.ReplayingEvents.onJournalResponse(ReplayingEvents.scala:171)
> 	... 36 common frames omitted

```
**Environment:**
>         java.version:11
>         scala.version:2.13
>         akka.version:2.6.15
>         akka.persistence-jdbc.version:5.0.1
>         akka.grpc-runtime.version:2.0.0
           Linux OS

**Comment by johanandren** [comment]
I think this is not related to persistence or rebalancing but a problem with Scala+jackson and parameterized types. Does annotating the field with `@JsonDeserialize(contentAs = classOf[Long])` as described in  https://github.com/akka/akka/issues/28566#issuecomment-583409601 help?
