### ISSUE TITLE
Failed: ShardWithLeaseSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30566]
JDK 11 nightly https://github.com/akka/akka/runs/3407948376?check_suite_focus=true#step:5:22508

```
[info] - must shutdown if lease is lost *** FAILED *** (374 milliseconds)
22509
[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(ack hello,Actor[akka://ShardWithLeaseSpec/system/sharding/type4/1/1#-1884587385]) after 49 millis
22510
[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:769)
22511
[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:733)
22512
[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:732)
22513
[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:973)
22514
[info]   at akka.cluster.sharding.ShardWithLeaseSpec$$anon$4.$anonfun$new$6(ShardWithLeaseSpec.scala:136)
22515
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
22516
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
22517
[info]   at akka.cluster.sharding.ShardWithLeaseSpec$$anon$4.<init>(ShardWithLeaseSpec.scala:133)
22518
[info]   at akka.cluster.sharding.ShardWithLeaseSpec.$anonfun$new$5(ShardWithLeaseSpec.scala:120)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/pull/30629/checks?check_run_id=3504630926#step:5:2603

**Comment by octonato** [comment]
This nightly build linked here has many errors. 

There is one exception related to `RememberEntitiesShardIdExtractorChangeSpec` that is quite surprising. The test is actually passing, but...

It's throwing this exception: 

```scala
java.lang.IllegalArgumentException                                                                                                      
  at akka.cluster.sharding.RememberEntitiesShardIdExtractorChangeSpec$$anonfun$1.applyOrElse(RememberEntitiesShardIdExtractorChangeSpec.scala:65)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)                                                      
  at akka.cluster.sharding.Shard.akka$cluster$sharding$Shard$$deliverMessage(Shard.scala:1032)                                          
  at akka.cluster.sharding.Shard$$anonfun$idle$1.applyOrElse(Shard.scala:626)                                                           
```

The surprising part is that on Shard.scala:626 we have:

```scala
case msg if extractEntityId.isDefinedAt(msg) => deliverMessage(msg, sender())
```

So the `extractEntityId` is defined for `msg`, but then it fails in: RememberEntitiesShardIdExtractorChangeSpec.scala:65

```scala
  val extractEntityId: ShardRegion.ExtractEntityId = {
    case msg @ Message(id) => (id.toString, msg)
    case _                 => throw new IllegalArgumentException() 
  }
```

where the IllegalArgumentException is on line 65

This simply doesn't make any sense. And yes, I checked that the code is a such on commit 8ad0b99 (the one in the build). 

Anyway, one more interesting puzzle / mystery to solve.

**Comment by octonato** [comment]
Renamed to `ShardWithLeaseSpec` from `RememberEntitiesShardIdExtractorChangeSpec` since this is the real failure.
