### ISSUE TITLE
Failed: NullEmptyStateSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#30618]
https://github.com/akka/akka/runs/3490479459?check_suite_focus=true#step:5:20264

in jdk-nightly-build

```scala
[info] - must persist events and update state *** FAILED *** (24 milliseconds)
[info]   java.lang.AssertionError: expected eventHandler:one:two, found onRecoveryCompleted:one
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.persistence.typed.scaladsl.NullEmptyStateSpec.$anonfun$new$2(NullEmptyStateSpec.scala:64)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by octonato** [comment]
Maybe relate to old https://github.com/akka/akka/issues/26047

**Comment by patriknw** [comment]
This is what I fixed this morning: https://github.com/akka/akka/pull/30610
