### ISSUE TITLE
Failed: StressMultiJvmSpec - must down partitioned nodes

### ISSUE THREAD

**Issue by octonato** [akka/akka#30620]
https://github.com/akka/akka/runs/3493924070?check_suite_focus=true

```scala
- must down partitioned nodes (on node 'node-13', class akka.cluster.StressMultiJvmNode9) *** FAILED *** (6 seconds, 1│
│2021-09-02T10:04:13.2401387Z [info] [JVM-13]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsgClass waiting for class akka.actor.A│
│2021-09-02T10:04:13.2403318Z [info] [JVM-13]   at scala.Predef$.assert(Predef.scala:279)                                                                           │
│2021-09-02T10:04:13.2405162Z [info] [JVM-13]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)                                              │
│2021-09-02T10:04:13.2407275Z [info] [JVM-13]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)                                                        │
│2021-09-02T10:04:13.2409343Z [info] [JVM-13]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)                                                       │
│2021-09-02T10:04:13.2411310Z [info] [JVM-13]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)                                                            ┤
│2021-09-02T10:04:13.2413513Z [info] [JVM-13]   at akka.cluster.StressSpec.clusterResultAggregator(StressSpec.scala:563)                                            │
│2021-09-02T10:04:13.2415832Z [info] [JVM-13]   at akka.cluster.StressSpec.$anonfun$createResultAggregator$2(StressSpec.scala:554)                                  │
│2021-09-02T10:04:13.2417978Z [info] [JVM-13]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:405)                                                 │
│2021-09-02T10:04:13.2420392Z [info] [JVM-13]   at akka.cluster.StressSpec.createResultAggregator(StressSpec.scala:553)                                             │
│2021-09-02T10:04:13.2423288Z [info] [JVM-13]   at akka.cluster.StressSpec.$anonfun$partitionSeveral$1(StressSpec.scala:718)                                        │
│2021-09-02T10:04:13.2425438Z [info] [JVM-13]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)                                          │
│2021-09-02T10:04:13.2427263Z [info] [JVM-13]   at akka.testkit.TestKitBase.within(TestKit.scala:418)                                                               │
│2021-09-02T10:04:13.2429383Z [info] [JVM-13]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)                                                              │
│2021-09-02T10:04:13.2431113Z [info] [JVM-13]   at akka.testkit.TestKit.within(TestKit.scala:973)                                                                   │
│2021-09-02T10:04:13.2432812Z [info] [JVM-13]   at akka.testkit.TestKitBase.within(TestKit.scala:433)                                                               ┤
│2021-09-02T10:04:13.2434547Z [info] [JVM-13]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)                                                              │
│2021-09-02T10:04:13.2436223Z [info] [JVM-13]   at akka.testkit.TestKit.within(TestKit.scala:973)                                                                   ┤
│2021-09-02T10:04:13.2438460Z [info] [JVM-13]   at akka.cluster.StressSpec.partitionSeveral(StressSpec.scala:714)                                                   ┤
│2021-09-02T10:04:13.2440424Z [info] [JVM-13]   at akka.cluster.StressSpec.$anonfun$new$19(StressSpec.scala:912)
```

**Comment by andreaTP** [comment]
I do understand those failures, running 13 JVMs on [this](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) hardware is for sure overwhelming.

`akka.cluster.Stress` runs successfully in `multi-node` on nightlies I think we should exclude it in `multi-jvm`.

**Comment by patriknw** [comment]
Marcos added some way to exclude multi-jvm tests to be able to exclude the StressSpec: https://github.com/akka/akka/commit/5e9965a12985f8da7760f42e00de883da7789bcc#diff-34bfdf7cb28fc6c66e3b0950e51614ad0cc95bbae6aba9e3ca5f4d2b3fa3de4c

It is configured here https://github.com/akka/akka/blob/master/.github/workflows/nightly-builds.yml#L96

Is that not working?

**Comment by octonato** [comment]
Apparently it's not working as expected. I'm looking into it.

**Comment by octonato** [comment]
this is a multi-node test: https://github.com/akka/akka/runs/3493924070?check_suite_focus=true

And exclusions are working as expected. I tested it locally
