### ISSUE TITLE
Failed: ClusterShardingLeaseSpec - should recover if lease lost

### ISSUE THREAD

**Issue by octonato** [akka/akka#30622]
https://github.com/akka/akka/runs/3467585761?check_suite_focus=true

```scala
│2021-08-31T00:16:49.6890798Z [info] - should recover if lease lost *** FAILED *** (27 seconds, 116 milliseconds)                                                   ┤
│2021-08-31T00:16:49.6892211Z [info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for 4                         │
│2021-08-31T00:16:49.6893498Z [info]   at scala.Predef$.assert(Predef.scala:279)                                                                                    │
│2021-08-31T00:16:49.6894814Z [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)                                                            │
│2021-08-31T00:16:49.6896372Z [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)                                                                     │
│2021-08-31T00:16:49.7036999Z [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)                                                                    │
│2021-08-31T00:16:49.7038345Z [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)                                                                         │
│2021-08-31T00:16:49.7040133Z [info]   at akka.cluster.sharding.ClusterShardingLeaseSpec.$anonfun$new$6(ClusterShardingLeaseSpec.scala:136)                         │
│2021-08-31T00:16:49.7041941Z [info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)                                                   │
│2021-08-31T00:16:49.7043202Z [info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)                                                                        │
│2021-08-31T00:16:49.7044480Z [info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)                                                                   │
│2021-08-31T00:16:49.7051340Z [info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)                                                                  │
│2021-08-31T00:16:49.7056793Z [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)                                                                       │
│2021-08-31T00:16:49.7059022Z [info]   at akka.cluster.sharding.ClusterShardingLeaseSpec.$anonfun$new$5(ClusterShardingLeaseSpec.scala:134)                         │
│2021-08-31T00:16:49.7061417Z [info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)                                                   │
│2021-08-31T00:16:49.7063230Z [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)                                                                     │
│2021-08-31T00:16:49.7064646Z [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)                                                                    │
│2021-08-31T00:16:49.7157400Z [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)                                                                   │
│2021-08-31T00:16:49.7158668Z [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)                                                                     │
│2021-08-31T00:16:49.7160141Z [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/pull/30628/checks?check_run_id=3503288638
