### ISSUE TITLE
Failed: SupervisionSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#30633]
https://github.com/akka/akka/pull/30629/checks?check_run_id=3504630926#step:5:2844

```scala
 - must allow passivation and early stop *** FAILED *** (40 seconds, 270 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (40 seconds) during expectMsgClass waiting for class akka.cluster.sharding.SupervisionSpec$Response
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:553)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:552)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
[info]   at akka.cluster.sharding.SupervisionSpec.$anonfun$new$7(SupervisionSpec.scala:157)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3531436339?check_suite_focus=true#step:5:5834

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/3565772213?check_suite_focus=true

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3593258636?check_suite_focus=true#step:5:27538

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3657782339?check_suite_focus=true#step:5:27057

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3809383637?check_suite_focus=true

**Comment by johanandren** [comment]
What is happening is that the test waits for the _child_ to have terminated before trying to send a message, but that does not mean that the backoss-supervising-parent or the shard saw that it did so there is a race where nobody knows, the test continues and the message is forwarded through the supervisor to the child inbox, but the child stops and the message is lost.
