### ISSUE TITLE
RememberEntitiesShardIdExtractorChangeSpec receiving UpdateDone after becoming idle

### ISSUE THREAD

**Issue by octonato** [akka/akka#30641]
The test passes, but prints an exception each time. 

```scala
java.lang.IllegalArgumentException                                                                                                      
  at akka.cluster.sharding.RememberEntitiesShardIdExtractorChangeSpec$$anonfun$1.applyOrElse(RememberEntitiesShardIdExtractorChangeSpec.scala:65)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)                                                      
  at akka.cluster.sharding.Shard.akka$cluster$sharding$Shard$$deliverMessage(Shard.scala:1032)                                          
  at akka.cluster.sharding.Shard$$anonfun$idle$1.applyOrElse(Shard.scala:626) 
```

The exception happens when calling the extractId. 

```scala
val extractEntityId: ShardRegion.ExtractEntityId = {
    case msg @ Message(id) => (id.toString, msg)
    case _                 => throw new IllegalArgumentException()
  }
```

I added some logging to find out which message was being sent and I saw that `UpdateDone` is causing the exception. 

In a normal scenario, the extractEntityId function won't have a catch-all like here, but that means that the message won't be handled. 

We need to look it further, because the `UpdateDone` should normally do some clean-ups. So we are potentially missing something.

**Comment by octonato** [comment]
Originally reported #30566

**Comment by pvlugter** [comment]
Having a look at this as part of #31100. Looking a little at the debug logs, this is the pattern in the test:

- the remember entities starter sends start requests for entities 1, 11, 21
- shard sends remember update for starting entity 1 (A)
- shard sends remember update for starting entity 11 (B)
- shard sends remember update for starting entity 21 (C)
- receive `UpdateDone` for starting 1 (A), pending updates for 11, 21 so send another update for starting entities 11, 21 (D)
- receive `UpdateDone` for starting 11 (B), pending updates for 21 so send another update for starting entity 21 sent (E)
- receive `UpdateDone` for starting 21 (C), no pending updates, switch to idle (which doesn't expect `UpdateDone`)
- receive `UpdateDone` for starting 11, 21 (D) which fails the extract entity id function
- receive `UpdateDone` for starting 21 (E) which fails the extract entity id function

Looks like it will be fairly easy to run into this, and would actually happen whenever multiple remembered entities are started?
