### ISSUE TITLE
ClusterShardingSpec: ClusterShardingSpec: Typed cluster sharding must EntityRef

### ISSUE THREAD

**Issue by raboof** [akka/akka#30667]
https://github.com/akka/akka/runs/3550727707?check_suite_focus=true

```
- must EntityRef - ask *** FAILED *** (10 seconds, 32 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds. (ClusterShardingSpec.scala:279)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.cluster.sharding.typed.scaladsl.ClusterShardingSpec.$anonfun$new$21(ClusterShardingSpec.scala:279)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/3773179986?check_suite_focus=true#step:5:29601
