### ISSUE TITLE
ReplicatedEventSourcingSpec: should set concurrent on replay of events

### ISSUE THREAD

**Issue by raboof** [akka/akka#30661]
https://github.com/akka/akka/pull/30651/checks?check_run_id=3533463987

```
[info]   java.lang.AssertionError: expected EventAndContext(from r2,ReplicaId(R2),true,true), found EventAndContext(from r2,ReplicaId(R2),false,false)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.$anonfun$new$21(ReplicatedEventSourcingSpec.scala:380)
```

Possibly related to #30548

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3738762268?check_suite_focus=true#step:5:21159
