### ISSUE TITLE
ReliableDeliveryShardingSpec: must deliver unconfirmed if ShardingConsumerController is terminated

### ISSUE THREAD

**Issue by raboof** [akka/akka#30664]
https://github.com/akka/akka/pull/30652/checks?check_run_id=3543444416

```
[info] - must deliver unconfirmed if ShardingConsumerController is terminated *** FAILED *** (2 seconds, 207 milliseconds)
[info]   Job(msg-3) did not equal Job(msg-4) (ReliableDeliveryShardingSpec.scala:391)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[info]   at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.$anonfun$new$15(ReliableDeliveryShardingSpec.scala:391)
```

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/3567388657?check_suite_focus=true

**Comment by pvlugter** [comment]
This one's had another failure in the nightly now, with logs:
https://github.com/akka/akka/runs/5296714473?check_suite_focus=true#step:5:34357

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/5353244228?check_suite_focus=true#step:5:34929

**Comment by raboof** [comment]
Looked into this some more, extracted logs of a successful and an unsuccessful run.

[logs-ok.txt](https://github.com/akka/akka/files/8216165/logs-ok.txt)
[logs-nok.txt](https://github.com/akka/akka/files/8216164/logs-nok.txt)

Both variations seem to try and deliver `msg-3` first at line 56, then the consumer restarts, after which it delivers it again at line 74. In the 'success' case the producer seems to redeliver an extra time, but that shouldn't make a difference.

Then on line 84 both seem to deliver `msg-4`, after which the consumer restarts again. This time, in the 'nok' case, on line 97 it redelivers `msg-3` again, while it did receive the `Confirm` for it on line 82.

Next steps: see if that confirmation should survive the consumer restart, and understand the `first` flag better.

**Comment by raboof** [comment]
Ok, so the scenario is:
* `ConsumerController` has received the `Confirmation` for msg 3 from the consumer (L82), and sends a `Request` confirming it to `ProducerController` (L83)
* `ProducerController` hasn't received the acknowledgement for msg 3 yet, so re-sends 3 and 4 (L87)
* *now* `ProducerController` receives the confirmation of msg 3 (but it has already re-sent msg 3)
* `Consumer` stops (L85), `ConsumerController` restarts (L92)
* `ConsumerController` receives msg 3 (L97), and since this `ConsumerController` instance doesn't know it was confirmed before, sends it to the consumer

@patriknw do you remember if this was supposed to be avoided, and if so how? Perhaps the `ConsumerController` should delay its shutdown until it has received confirmation from the `ProducerController` that it has processed all acknowledgements?

**Comment by patriknw** [comment]
Confirmation on the confirmation (endless cycle) doesn't sound like something we should get into.

I think that kind of duplicate is ok and we should relax the test.

**Comment by raboof** [comment]
> Confirmation on the confirmation (endless cycle) doesn't sound like something we should get into.

Of course - the producer side already re-sends messages and we could piggy-back a 'last acknowledgement processed' on that, but indeed it'd mean some additional complexity.
 
> I think that kind of duplicate is ok and we should relax the test.

Okay, will PR!
