### ISSUE TITLE
EventStreamSpec: must unwatch an actor from unsubscriber when that actor unsubscribes from channels it subscribed

### ISSUE THREAD

**Issue by raboof** [akka/akka#30675]
https://github.com/akka/akka/pull/30673/checks?check_run_id=3558344488

```
- must unwatch an actor from unsubscriber when that actor unsubscribes from channels it subscribed *** FAILED *** (6 seconds, 44 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during fishForMessage, hint: expected debug message prefix: watching Actor[akka://EventStreamSpec/system/testProbe-61#-461256783]
[info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[info]   at akka.testkit.TestKitBase.recv$1(TestKit.scala:512)
[info]   at akka.testkit.TestKitBase.fishForMessage(TestKit.scala:516)
[info]   at akka.testkit.TestKitBase.fishForMessage$(TestKit.scala:159)
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:973)
[info]   at akka.event.EventStreamSpec.fishForDebugMessage(EventStreamSpec.scala:433)
[info]   at akka.event.EventStreamSpec.f$proxy18$1(EventStreamSpec.scala:401)
[info]   at akka.event.EventStreamSpec.$init$$$anonfun$18$$anonfun$17(EventStreamSpec.scala:389)
```

**Comment by patriknw** [comment]
Failed again, after the merge.

https://github.com/akka/akka/runs/3604788234?check_suite_focus=true#step:5:1953

```
[info] - must unwatch an actor from unsubscriber when that actor unsubscribes from channels it subscribed *** FAILED *** (5 seconds, 965 milliseconds)
1954
[info]   java.lang.AssertionError: assertion failed: expected Debug(60,class akka.event.EventStreamSpec,), found Debug(55,class akka.event.EventStreamSpec,)
1955
[info]   at scala.Predef$.assert(Predef.scala:279)
1956
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
1957
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
1958
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
1959
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
1960
[info]   at akka.event.EventStreamSpec.$anonfun$waitForDebugSubscription$1(EventStreamSpec.scala:489)
1961
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
1962
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
1963
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
1964
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
1965
[info]   at akka.event.EventStreamSpec.waitForDebugSubscription(EventStreamSpec.scala:485)
1966
[info]   at akka.event.EventStreamSpec.$anonfun$new$39(EventStreamSpec.scala:441)
```

**Comment by patriknw** [comment]
I added some comments to the PR https://github.com/akka/akka/pull/30676#pullrequestreview-754699064

**Comment by patriknw** [comment]
https://github.com/akka/akka/pull/30684/checks?check_run_id=3606751301#step:5:1753

**Comment by patriknw** [comment]
Failed again after the fix: https://github.com/akka/akka/pull/30713/checks?check_run_id=3697496840#step:5:3034

```
[info] - must unwatch an actor from unsubscriber when that actor unsubscribes from channels it subscribed *** FAILED *** (7 seconds, 63 milliseconds)
1884
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during fishForMessage, hint: expected debug message prefix: unwatching Actor[akka://EventStreamSpec/system/testProbe-71#-2049784404], since has no subscriptions
1885
[info]   at scala.Predef$.assert(Predef.scala:223)
1886
[info]   at akka.testkit.TestKitBase.recv$1(TestKit.scala:512)
1887
[info]   at akka.testkit.TestKitBase.fishForMessage(TestKit.scala:516)
1888
[info]   at akka.testkit.TestKitBase.fishForMessage$(TestKit.scala:506)
1889
[info]   at akka.testkit.TestKit.fishForMessage(TestKit.scala:973)
1890
[info]   at akka.event.EventStreamSpec.fishForDebugMessage(EventStreamSpec.scala:427)
1891
[info]   at akka.event.EventStreamSpec.$anonfun$new$27(EventStreamSpec.scala:405)
1892
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
1893
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
1894
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
1895
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
1896
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
1897
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
1898
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
1899
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
1900
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
1901
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
1902
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3762030367?check_suite_focus=true#step:5:2108

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/3750584080?check_suite_focus=true#step:5:1979
