### ISSUE TITLE
GroupRouterSpec: GroupRouter must use all reachable routees if preferLocalRoutees is not enabled

### ISSUE THREAD

**Issue by raboof** [akka/akka#30671]
https://github.com/akka/akka/pull/30666/checks?check_run_id=3553179749

```
[info]   A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds. (GroupRouterSpec.scala:122)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.cluster.typed.GroupRouterSpec.checkGroupRouterBehavior(GroupRouterSpec.scala:122)
[info]   at akka.cluster.typed.GroupRouterSpec.$anonfun$new$3(GroupRouterSpec.scala:143)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at akka.cluster.typed.GroupRouterSpec.$anonfun$new$2(GroupRouterSpec.scala:142)
```

**Comment by raboof** [comment]
https://github.com/akka/akka/pull/30650/checks?check_run_id=3533461433

**Comment by johanandren** [comment]
I _think_ this could be because of the test expecting delivery guarantee across nodes, but not entirely sure.
