### ISSUE TITLE
Failed: AbstractPersistentFSMTest

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30693]
https://github.com/akka/akka/pull/30692/checks?check_run_id=3632330866#step:5:988

```
[info] - fsmTimeoutTest
987
[INFO] [akkaDeadLetter][09/17/2021 12:49:14.907] [PersistentFSMJavaTest-akka.actor.default-dispatcher-8] [akka://PersistentFSMJavaTest/user/$e] Message [akka.persistence.SaveSnapshotFailure] from Actor[akka://PersistentFSMJavaTest/system/akka.persistence.snapshot-store.local#-2090474267] to Actor[akka://PersistentFSMJavaTest/user/$e#-1207812370] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://PersistentFSMJavaTest/user/$e#-1207812370] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
988
[info] - fsmFunctionalTest *** FAILED ***
989
[info]   java.lang.AssertionError:
990
[info]   at org.junit.Assert.fail(Assert.java:87)
991
[info]   at org.junit.Assert.assertTrue(Assert.java:42)
992
[info]   at org.junit.Assert.assertTrue(Assert.java:53)
993
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest$1.<init>(AbstractPersistentFSMTest.java:90)
994
[info]   at akka.persistence.fsm.AbstractPersistentFSMTest.fsmFunctionalTest(AbstractPersistentFSMTest.java:61)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4450957638?check_suite_focus=true#step:5:4479

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4670672017?check_suite_focus=true#step:5:4503
