### ISSUE TITLE
failed: BoundedBlockingQueueSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30716]
https://github.com/akka/akka/pull/30713/checks?check_run_id=3697496840#step:5:3034

```
[info] - must check the backing queue size before polling *** FAILED *** (107 milliseconds)
3035
[info]   List(GetSize(), SignalNotEmpty(), GetSize(), AwaitNotEmpty()) did not contain all of List(GetSize(), AwaitNotEmpty(), SignalNotEmpty(), GetSize(), AwaitNotEmpty()) in sequence (BoundedBlockingQueueSpec.scala:202)
3036
[info]   org.scalatest.exceptions.TestFailedException:
3037
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:402)
3038
[info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6783)
3039
[info]   at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6823)
3040
[info]   at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
3041
[info]   at akka.util.BoundedBlockingQueueSpec.should(BoundedBlockingQueueSpec.scala:28)
3042
[info]   at akka.util.BoundedBlockingQueueSpec.f$proxy21$2(BoundedBlockingQueueSpec.scala:202)
3043
[info]   at akka.util.BoundedBlockingQueueSpec.$init$$$anonfun$34$$anonfun$5(BoundedBlockingQueueSpec.scala:186)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5225034667?check_suite_focus=true#step:5:3638
