### ISSUE TITLE
DurableState persistence plugin does not work

### ISSUE THREAD

**Issue by miladamer** [akka/akka#30729]
Hi. Im creating a test app for myself using akka and durable state with kotlin. I need to mention that I excluded all akka related dependencies from `akka-persistence-cassandra_2.13` and replaced them with akka version 2.6.16 because of binary compatibility issues. 
Here is my pom.xml dependencies:
```
<dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>1.5.31</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor-typed_2.13</artifactId>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor-testkit-typed_2.13</artifactId>
            <scope>test</scope>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <version>1.5.31</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.6.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.5.31</version>
        </dependency>

        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence-cassandra_2.13</artifactId>
            <version>1.0.5</version>
            <exclusions>
                <exclusion>
                    <groupId>com.typesafe.akka</groupId>
                    <artifactId>akka-persistence_2.13</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.typesafe.akka</groupId>
                    <artifactId>akka-persistence-query_2.13</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.typesafe.akka</groupId>
                    <artifactId>akka-cluster-tools_2.13</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence-cassandra-launcher_2.13</artifactId>
            <version>1.0.5</version>
        </dependency>

        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence_2.13</artifactId>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence-query_2.13</artifactId>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-cluster-tools_2.13</artifactId>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence-typed_2.13</artifactId>
            <version>2.6.16</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-persistence-testkit_2.13</artifactId>
            <version>2.6.16</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```
I have an actor like this
```
class TestActor(persistenceId: PersistenceId) : DurableStateBehavior<UserId.Command, Long>(persistenceId) {
    override fun emptyState(): Long? {
        return null
    }

    override fun commandHandler(): CommandHandler<UserId.Command, Long> {
        return newCommandHandlerBuilder().forAnyState().build()
    }
}
```
and my application.conf look like this
```
akka {

  extensions = [akka.persistence.Persistence]

  persistence {

    journal {
      plugin = "akka.persistence.cassandra.journal"
    }

    snapshot-store {
      plugin = "akka.persistence.cassandra.snapshot"
    }

    state {
      plugin = "akka.persistence.cassandra.journal"
    }
  }

  datastax-java-driver {
    basic {
      session-keyspace = akka
      cloud {
        secure-connect-bundle = secure-connect-database_name.zip
      }
    }
    advanced {
      auth-provider {
        class = PlainTextAuthProvider
        username = "myUsername"
        password = "MyPass"
      }
    }
  }
}
```
But when I run my actor system
```
val actorSystem = ActorSystem.create(TestActor(PersistenceId.ofUniqueId("UserIdSequence")), "SeqTest", ConfigFactory.load())
```
I get the following
```
11:32:55.446 [SeqTest-akka.actor.default-dispatcher-3] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
SLF4J: A number (1) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
11:32:55.671 [SeqTest-akka.actor.default-dispatcher-7] ERROR akka.actor.LocalActorRefProvider - guardian failed, shutting down system
java.lang.IllegalArgumentException: Unable to create read journal plugin instance for path [akka.persistence.cassandra.journal], class [akka.persistence.cassandra.journal.CassandraJournal]!
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$4.applyOrElse(PersistencePlugin.scala:97)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$4.applyOrElse(PersistencePlugin.scala:91)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:91)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:60)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:58)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.persistence.PersistencePlugin$$anon$1.apply(PersistencePlugin.scala:58)
	at akka.persistence.PersistencePlugin.pluginFor(PersistencePlugin.scala:56)
	at akka.persistence.state.DurableStateStoreRegistry.durableStateStoreFor(DurableStateStoreRegistry.scala:86)
	at akka.persistence.typed.state.internal.BehaviorSetup.<init>(BehaviorSetup.scala:50)
	at akka.persistence.typed.state.internal.DurableStateBehaviorImpl.$anonfun$apply$2(DurableStateBehaviorImpl.scala:108)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.internal.AbstractSupervisor.aroundStart(Supervision.scala:77)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.BehaviorInterceptor.aroundStart(BehaviorInterceptor.scala:55)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:275)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoSuchMethodException: akka.persistence.cassandra.journal.CassandraJournal.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:38)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$instantiate$1(PersistencePlugin.scala:80)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$3.applyOrElse(PersistencePlugin.scala:90)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$3.applyOrElse(PersistencePlugin.scala:90)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:90)
	... 38 common frames omitted
11:32:55.672 [SeqTest-akka.actor.default-dispatcher-7] ERROR akka.actor.OneForOneStrategy - Unable to create read journal plugin instance for path [akka.persistence.cassandra.journal], class [akka.persistence.cassandra.journal.CassandraJournal]!
java.lang.IllegalArgumentException: Unable to create read journal plugin instance for path [akka.persistence.cassandra.journal], class [akka.persistence.cassandra.journal.CassandraJournal]!
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$4.applyOrElse(PersistencePlugin.scala:97)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$4.applyOrElse(PersistencePlugin.scala:91)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:91)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:60)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:58)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.persistence.PersistencePlugin$$anon$1.apply(PersistencePlugin.scala:58)
	at akka.persistence.PersistencePlugin.pluginFor(PersistencePlugin.scala:56)
	at akka.persistence.state.DurableStateStoreRegistry.durableStateStoreFor(DurableStateStoreRegistry.scala:86)
	at akka.persistence.typed.state.internal.BehaviorSetup.<init>(BehaviorSetup.scala:50)
	at akka.persistence.typed.state.internal.DurableStateBehaviorImpl.$anonfun$apply$2(DurableStateBehaviorImpl.scala:108)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.internal.AbstractSupervisor.aroundStart(Supervision.scala:77)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.BehaviorInterceptor.aroundStart(BehaviorInterceptor.scala:55)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:120)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:275)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NoSuchMethodException: akka.persistence.cassandra.journal.CassandraJournal.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:38)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$instantiate$1(PersistencePlugin.scala:80)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$3.applyOrElse(PersistencePlugin.scala:90)
	at akka.persistence.PersistencePlugin$$anonfun$akka$persistence$PersistencePlugin$$createPlugin$3.applyOrElse(PersistencePlugin.scala:90)
	at scala.util.Failure.recoverWith(Try.scala:240)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:90)
	... 38 common frames omitted

Process finished with exit code 0
```
I'll be really thankful if you help me on this matter.

**Comment by patriknw** [comment]
It's not implemented in the Cassandra plugin.
It's implemented in akka-persistence-jdbc and akka-persistence-spanner

**Comment by miladamer** [comment]
Thank you very much.
