### ISSUE TITLE
Failed: JoinConfigCompatCheckerRollingUpdateSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30769]
https://github.com/akka/akka/runs/3833393859?check_suite_focus=true#step:5:2464

```
[info] - must NOT be allowed to re-join a cluster if it has a new, additional configuration the others do not have and not the old *** FAILED *** (41 seconds, 222 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout 30 seconds expired:
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
[info]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
[info]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
[info]   at akka.cluster.RollingUpgradeClusterSpec.upgradeCluster(ClusterTestKit.scala:218)
[info]   at akka.cluster.JoinConfigCompatCheckerRollingUpdateSpec.$anonfun$new$2(JoinConfigCompatCheckerRollingUpdateSpec.scala:53)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4028929070?check_suite_focus=true#step:5:2437

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4128205483?check_suite_focus=true#step:5:22590

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4232162192?check_suite_focus=true#step:9:2362

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/4245427695?check_suite_focus=true#step:9:2323

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/4258626735?check_suite_focus=true#step:9:2241
