### ISSUE TITLE
Failed: ReplicatedEventSourcingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30774]
https://github.com/akka/akka/pull/30762/checks?check_run_id=3828087160#step:5:19879

```
[info] - should replicate alternate events *** FAILED *** (24 milliseconds)
19880
[info]   java.lang.AssertionError: expected EventAndContext(from r2,ReplicaId(R2),false,false), found EventAndContext(from r1,ReplicaId(R1),false,false)
19881
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
19882
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
19883
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
19884
[info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.$anonfun$new$15(ReplicatedEventSourcingSpec.scala:269)
```

[replicatedeventsourcingspecfail.log](https://github.com/akka/akka/files/7311267/replicatedeventsourcingspecfail.log)

**Comment by octonato** [comment]
Seems to still happen. Build failure is from last night.

https://github.com/akka/akka/runs/3945836495?check_suite_focus=true#step:5:20452

```scala
<-- [akka.persistence.typed.ReplicatedEventSourcingSpec: ReplicatedEventSourcing should replicate alternate events] End of log messages of test that [Failed(java.lang.AssertionError: expected EventAndContext(from r2,ReplicaId(R2),false,false), found EventAndContext(from r1,ReplicaId(R1),false,false))]
[info] - should replicate alternate events *** FAILED *** (52 milliseconds)
[info]   java.lang.AssertionError: expected EventAndContext(from r2,ReplicaId(R2),false,false), found EventAndContext(from r1,ReplicaId(R1),false,false)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.$anonfun$new$15(ReplicatedEventSourcingSpec.scala:269)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/3876858781?check_suite_focus=true#step:5:20923

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/3864937864?check_suite_focus=true#step:5:21055
