### ISSUE TITLE
failed: ClusterShardingPreparingForShutdown

### ISSUE THREAD

**Issue by octonato** [akka/akka#30804]
https://github.com/akka/akka/runs/3945881460?check_suite_focus=true
```scala
[JVM-3] - must not rebalance but should still work preparing for shutdown (on node 'third', class akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownMultiJvmNode3) *** FAILED *** (33 seconds, 290 milliseconds)
[JVM-3]   self member: Member(akka://ClusterShardingPreparingForShutdownSpec@test-node3:5000, ReadyForShutdown) ReadyForShutdown did not equal Removed (ClusterShardingPreparingForShutdownSpec.scala:138)
[JVM-3]   org.scalatest.exceptions.TestFailedException:
[JVM-3]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[JVM-3]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)
[JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$19(ClusterShardingPreparingForShutdownSpec.scala:138)
[JVM-3]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[JVM-3]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.withClue(ClusterShardingPreparingForShutdownSpec.scala:66)
[JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$18(ClusterShardingPreparingForShutdownSpec.scala:138)
[JVM-3]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[JVM-3]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[JVM-3]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[JVM-3]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[JVM-3]   at akka.cluster.sharding.typed.ClusterShardingPreparingForShutdownSpec.$anonfun$new$3(ClusterShardingPreparingForShutdownSpec.scala:136)
[JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)

```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5014350195?check_suite_focus=true#step:5:2219

**Comment by patriknw** [comment]
This could actually be the same reason as what I fixed in https://github.com/akka/akka/pull/31144
The final Removed not updated in the selfMember on shutdown.
Closing as that.
