### ISSUE TITLE
failed: ReplicatedEventSourcingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30842]
https://github.com/akka/akka/runs/4057462489?check_suite_focus=true#step:5:20578

```
[info] - should set concurrent on replay of events *** FAILED *** (102 milliseconds)
20579
[info]   java.lang.AssertionError: expected EventAndContext(from r2,ReplicaId(R2),true,true), found EventAndContext(from r2,ReplicaId(R2),false,false)
20580
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
20581
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)
20582
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
20583
[info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.$anonfun$new$21(ReplicatedEventSourcingSpec.scala:380)
20584
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
20585
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
20586
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
20587
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
20588
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
20589
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
20590
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
20591
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
20592
[info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.withFixture(ReplicatedEventSourcingSpec.scala:91)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4184436181?check_suite_focus=true#step:5:20641

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4189021908?check_suite_focus=true#step:5:1112
