### ISSUE TITLE
failed: StreamRefsSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30844]
https://github.com/akka/akka/runs/4074388965?check_suite_focus=true#step:5:16984

```
[info] - must pass cancellation upstream across remoting before elements has been emitted *** FAILED *** (13 milliseconds)
16985
[info]   java.lang.AssertionError: assertion failed: expected Done, found Failure(akka.stream.RemoteStreamRefActorTerminatedException: Remote target receiver of data Some(Actor[akka://StreamRefsSpec/system/Materializers/StreamSupervisor-305/$$m-SourceRef-8#10354574]) terminated. Local stream terminating, message loss (on remote side) may have happened.)
16986
[info]   at scala.Predef$.assert(Predef.scala:223)
16987
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
16988
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
16989
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
16990
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
16991
[info]   at akka.stream.scaladsl.StreamRefsSpec.$anonfun$new$15(StreamRefsSpec.scala:365)
16992
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
16993
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
16994
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
16995
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
16996
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
16997
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/4184436181?check_suite_focus=true#step:5:17056

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4329062828?check_suite_focus=true#step:5:17982

**Comment by pvlugter** [comment]
I had a look through this one, but didn't see anything obvious to create or reproduce the failure. There are no logs on failure, so we could enable this test again with debug logs to get some more info.

**Comment by octonato** [comment]
@pvlugter, I assigned to you because I thought you were working on a fix, but now I see that #31183 was about adding more logging. So, I'm removing you. :-)

Feel free to pick it if you want.

**Comment by pvlugter** [comment]
I think it needs a test failure with the debug logs to figure out when and why it might fail. So leaving until that happens...

**Comment by pvlugter** [comment]
Another failure, with the debug logs enabled.

https://github.com/akka/akka/runs/7267105678?check_suite_focus=true#step:5:17873

```
[DEBUG] [07/10/2022 00:51:51.642] [RemoteSystem-akka.test.stream-dispatcher-28] [SinkRefStageImpl(akka://RemoteSystem)] [SinkRef-8] Created SinkRef with initial partner, local worker: Actor[akka://RemoteSystem/system/Materializers/StreamSupervisor-1475/$$i-SinkRef-8#1083513707], subscription timeout: 30.00 s
[DEBUG] [07/10/2022 00:51:51.657] [StreamRefsSpec-akka.test.stream-dispatcher-28] [SourceRefStageImpl(akka://StreamRefsSpec)] [SourceRef-8] Starting up with, self ref: Actor[akka://StreamRefsSpec/system/Materializers/StreamSupervisor-1472/$$m-SourceRef-8#1483818566], state: AwaitingSubscription(Actor[akka://RemoteSystem/system/Materializers/StreamSupervisor-1475/$$i-SinkRef-8#1083513707]), subscription timeout: 30.00 s
[DEBUG] [07/10/2022 00:51:51.657] [StreamRefsSpec-akka.test.stream-dispatcher-28] [SourceRefStageImpl(akka://StreamRefsSpec)] [SourceRef-8] Demanding, before subscription seen, until [0] (+32)
[DEBUG] [07/10/2022 00:51:51.657] [StreamRefsSpec-akka.test.stream-dispatcher-28] [SourceRefStageImpl(akka://StreamRefsSpec)] [SourceRef-8] Deferred stop on downstream cancel
[DEBUG] [07/10/2022 00:51:51.658] [RemoteSystem-akka.test.stream-dispatcher-32] [SinkRefStageImpl(akka://RemoteSystem)] [SinkRef-8] Received cumulative demand [CumulativeDemand(32)], consumable demand: [32]
[DEBUG] [07/10/2022 00:51:51.658] [RemoteSystem-akka.test.stream-dispatcher-32] [SinkRefStageImpl(akka://RemoteSystem)] [SinkRef-8] remote terminated [Actor[akka://StreamRefsSpec/system/Materializers/StreamSupervisor-1472/$$m-SourceRef-8#1483818566]], partnerRef: [Some(Actor[akka://StreamRefsSpec/system/Materializers/StreamSupervisor-1472/$$m-SourceRef-8#1483818566])], finishedWithAwaitingPartnerTermination: [None]
[07-10 00:51:51.675] [info] - must pass cancellation upstream across remoting before elements has been emitted *** FAILED *** (19 milliseconds)
[07-10 00:51:51.675] [info]   java.lang.AssertionError: assertion failed: expected Done, found Failure(akka.stream.RemoteStreamRefActorTerminatedException: Remote target receiver of data Some(Actor[akka://StreamRefsSpec/system/Materializers/StreamSupervisor-1472/$$m-SourceRef-8#1483818566]) terminated. Local stream terminating, message loss (on remote side) may have happened.)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3709022163/jobs/6287193880#step:5:17440

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4139565714/jobs/7157277135#step:5:17135

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5009071604/jobs/8977595616#step:5:16915

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5194564060/jobs/9366359263#step:5:17371

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5273326711/jobs/9536615069#step:5:17612

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5295215290/jobs/9585318197#step:5:17089

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6067516526/job/16459278264#step:5:17548

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6078595435/job/16489981966#step:5:16589

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6091046788/job/16527001877#step:5:17446

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6192192806/job/16811845303#step:5:16846

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6286765028/job/17070518733#step:5:17122

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6345535747/job/17237680145#step:5:17608

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6527316872/job/17722007952#step:5:17221

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6633964711/job/18022628631#step:5:17064

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/6751394995/job/18355398715#step:5:17693
