### ISSUE TITLE
failed: ClusterSingletonManagerSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30846]
in multi-node with aeron-udp

https://github.com/akka/akka/runs/4074436532?check_suite_focus=true#step:9:29613

```
[info] [JVM-8]   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsg while waiting for Pong
29614
[info] [JVM-8]   at scala.Predef$.assert(Predef.scala:279)
29615
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
29616
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:447)
29617
[info] [JVM-8]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:447)
29618
[info] [JVM-8]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
29619
[info] [JVM-8]   at akka.cluster.singleton.ClusterSingletonManagerSpec.$anonfun$verifyProxyMsg$3(ClusterSingletonManagerSpec.scala:264)
```

**Comment by patriknw** [comment]
duplicate of https://github.com/akka/akka/issues/30253
