### ISSUE TITLE
failed: RemoveInternalClusterShardingDataSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30869]
https://github.com/akka/akka/runs/4133358691?check_suite_focus=true#step:5:1160

```
Error: R] [11/08/2021 00:15:16.088] [RemoveInternalClusterShardingDataSpec-akka.persistence.dispatchers.default-stream-dispatcher-25] [akka.tcp://RemoveInternalClusterShardingDataSpec@10.1.0.53:44645/system/akka.persistence.snapshot-store.local] Error loading snapshot [SnapshotMetadata(/sharding/type2Coordinator, 5, 1636330516060, None)], remaining attempts: [0]
1161
| java.nio.file.NoSuchFileException: target/snapshots-RemoveInternalClusterShardingDataSpec/snapshot-%2Fsharding%2Ftype2Coordinator-5-1636330516060
1162
| 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
1163
| 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
1164
| 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
1165
| 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
1166
| 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
1167
| 	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
1168
| 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
1169
| 	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
1170
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.withInputStream(LocalSnapshotStore.scala:136)
1171
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.$anonfun$load$1(LocalSnapshotStore.scala:104)
1172
| 	at scala.util.Try$.apply(Try.scala:210)
1173
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.load(LocalSnapshotStore.scala:104)
1174
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.$anonfun$loadAsync$1(LocalSnapshotStore.scala:56)
1175
| 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
1176
| 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
1177
| 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
1178
| 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
1179
| 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
1180
| 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
1181
| 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
1182
| 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
1183
| 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
1184
| 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
1185
| 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
1186
| 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
1187
| 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
1188
| 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
1189
| 
1190
| [DEBUG] [11/08/2021 00:15:16.088] [RemoveInternalClusterShardingDataSpec-akka.actor.default-dispatcher-16] [akka.tcp://RemoveInternalClusterShardingDataSpec@10.1.0.53:44645/system/sharding/type2Coordinator/singleton/coordinator] type2: Persistent snapshots to [9] deleted successfully
1191
Error: R] [11/08/2021 00:15:16.089] [RemoveInternalClusterShardingDataSpec-akka.actor.default-dispatcher-22] [akka.tcp://RemoveInternalClusterShardingDataSpec@10.1.0.53:44645/user/$i] Persistence failure when replaying events for persistenceId [/sharding/type2Coordinator]. Last known sequence number [0]
1192
| java.nio.file.NoSuchFileException: target/snapshots-RemoveInternalClusterShardingDataSpec/snapshot-%2Fsharding%2Ftype2Coordinator-5-1636330516060
1193
| 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
1194
| 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
1195
| 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
1196
| 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
1197
| 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
1198
| 	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
1199
| 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
1200
| 	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
1201
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.withInputStream(LocalSnapshotStore.scala:136)
1202
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.$anonfun$load$1(LocalSnapshotStore.scala:104)
1203
| 	at scala.util.Try$.apply(Try.scala:210)
1204
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.load(LocalSnapshotStore.scala:104)
1205
| 	at akka.persistence.snapshot.local.LocalSnapshotStore.$anonfun$loadAsync$1(LocalSnapshotStore.scala:56)
1206
| 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
1207
| 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
1208
| 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
1209
| 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
1210
| 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
1211
| 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
1212
| 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
1213
| 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
1214
| 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
1215
| 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
1216
| 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
1217
| 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
1218
| 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
1219
| 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
1220
| 
1221
| [DEBUG] [11/08/2021 00:15:36.056] [pool-1-thread-1-ScalaTest-running-RemoveInternalClusterShardingDataSpec] [WithLogCapturing(akka://RemoveInternalClusterShardingDataSpec)] Logging finished for test [RemoveOnePersistenceId must remove all events and snapshots]
1222
<-- [RemoveOnePersistenceId must remove all events and snapshots] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: timeout (19977262674 nanoseconds) during expectMsgClass waiting for boolean)]
1223
[info] - must remove all events and snapshots *** FAILED *** (20 seconds, 27 milliseconds)
1224
[info]   java.lang.AssertionError: assertion failed: timeout (19977262674 nanoseconds) during expectMsgClass waiting for boolean
1225
[info]   at scala.Predef$.assert(Predef.scala:279)
1226
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
1227
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:543)
1228
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:542)
1229
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:973)
1230
[info]   at akka.cluster.sharding.RemoveInternalClusterShardingDataSpec.hasSnapshots(RemoveInternalClusterShardingDataSpec.scala:123)
1231
[info]   at akka.cluster.sharding.RemoveInternalClusterShardingDataSpec.$anonfun$new$11(RemoveInternalClusterShardingDataSpec.scala:173)
```

**Comment by pvlugter** [comment]
Reproduced the timing that fails here. This test is creating 10 events, with snapshots at 5 and 10. It then deletes the events and snapshots and checks that these have been deleted. The failure is earlier, when checking that any snapshots have been saved. The failure is that the file for a snapshot that it attempted to load doesn't exist any longer. The failing scenario is:

- snapshot @ 5 is saved
- check whether there are snapshots (by loading them)
- list snapshot files, only one file for snapshot @ 5, but pause before actually loading it
- snapshot @ 10 is saved, which then deletes previous snapshot @ 5
- continue with loading snapshot @ 5, but the file doesn't exist now

The timing for this may not be that common, and the test could be adjusted to not have two snapshots in play, but this is really a bug in `LocalSnapshotStore`. To fix it there, and given that the operations are async in futures, it could be easiest to just have a retry which circles back round to list snapshot files again specifically on `NoSuchFileException` (there's also a different retry on an older snapshot if the latest fails).
