### ISSUE TITLE
failed: multi-node tests

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#30874]
Multi-node tests are failing, with pods do "not have a host assigned". For example:

```
[info] * akka.remote.artery.FanOutThroughputSpec
[error] Error from server (BadRequest): pod test-node3-689b9bcf95-lfjct does not have a host assigned
[error] Error from server (BadRequest): pod test-node4-57c874844-tf8z6 does not have a host assigned
[error] Failed: akka.remote.artery.FanOutThroughputSpecMultiJvmNode3 sync
[error] Failed: akka.remote.artery.FanOutThroughputSpecMultiJvmNode4 sync
```

https://github.com/akka/akka/runs/4172482272?check_suite_focus=true
https://github.com/akka/akka/runs/4172482401?check_suite_focus=true

Most likely to be #30873, which increases the resource requests? There are 5 nodes, and 15 pods created. At 1800m cpu requests, some pods may not be able to be scheduled? Haven't looked at what kind of debugging is possible for the kubernetes cluster.

**Comment by pvlugter** [comment]
Looks like this is still happening for the next nightly run:

https://github.com/akka/akka/actions/runs/1451075200

**Comment by patriknw** [comment]
Latest is failing with `StackOverflowError`

```
2021-11-15T00:26:45.6006919Z [info] * akka.cluster.StreamRef
2021-11-15T00:26:54.9685327Z [info] [JVM-1] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.2356223Z [info] [JVM-2] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.5082160Z [info] [JVM-3] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.5526090Z [info] [JVM-1] [0.592s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 9.154ms
2021-11-15T00:26:55.7988430Z [info] [JVM-2] [0.570s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 11.160ms
2021-11-15T00:26:55.9663348Z [info] [JVM-1] [1.006s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 13.431ms
2021-11-15T00:26:56.0309012Z [info] [JVM-3] [0.529s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 9.992ms
2021-11-15T00:26:56.1096512Z [error] [JVM-1] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.1119470Z [error] [JVM-1] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.1131063Z [error] [JVM-1] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.1145719Z [error] [JVM-1] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.1151244Z [error] [JVM-1] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.1598079Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.116] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-3acbc99e-3d78-4e50-9448-702ea97ad11f]
2021-11-15T00:26:56.1703875Z [info] [JVM-2] [0.940s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 10.828ms
2021-11-15T00:26:56.2819626Z [error] [JVM-2] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.2846018Z [error] [JVM-2] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.2855300Z [error] [JVM-2] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.2877463Z [error] [JVM-2] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.2888291Z [error] [JVM-2] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.3355619Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.286] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-956812ac-592c-4000-9eb7-5f18b441aa62]
2021-11-15T00:26:56.4309553Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.398] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node1:6000] with UID [5962942504255699767]
2021-11-15T00:26:56.4317104Z [info] [JVM-3] [0.931s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 9.241ms
2021-11-15T00:26:56.4558930Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.423] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.5161377Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.483] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - Started up successfully
2021-11-15T00:26:56.5546966Z [error] [JVM-3] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.5556305Z [error] [JVM-3] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.5567989Z [error] [JVM-3] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.5576841Z [error] [JVM-3] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.5586545Z [error] [JVM-3] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.5595925Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.523] [StreamRef-akka.actor.internal-dispatcher-12] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:56.6026065Z [info] [JVM-1] [1.641s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 42M->10M(512M) 13.479ms
2021-11-15T00:26:56.6055855Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.574] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node2:6000] with UID [-6979541087986446429]
2021-11-15T00:26:56.6065215Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.559] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-45d5d73d-5616-411d-816e-d91914e244ed]
2021-11-15T00:26:56.6295175Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.596] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.6805196Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.648] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - Started up successfully
2021-11-15T00:26:56.7273461Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.695] [StreamRef-akka.actor.internal-dispatcher-2] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:56.7525659Z [info] [JVM-2] [1.525s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 41M->10M(512M) 13.703ms
2021-11-15T00:26:56.8809468Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.848] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node3:6000] with UID [-4276527013964994759]
2021-11-15T00:26:56.9032175Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.870] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.9643325Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.932] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - Started up successfully
2021-11-15T00:26:57.0195581Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.987] [StreamRef-akka.actor.internal-dispatcher-12] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:57.0624615Z [info] [JVM-3] [1.561s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 43M->10M(512M) 12.645ms
2021-11-15T00:26:57.5000146Z [info] [JVM-1] [INFO] [11/15/2021 00:26:57.466] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode1] Role [first] started with address [akka://StreamRef@test-node1:6000]
2021-11-15T00:26:57.5414271Z [info] [JVM-2] [INFO] [11/15/2021 00:26:57.509] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode2] Role [second] started with address [akka://StreamRef@test-node2:6000]
2021-11-15T00:26:57.5504586Z [info] [JVM-3] [INFO] [11/15/2021 00:26:57.518] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode3] Role [third] started with address [akka://StreamRef@test-node3:6000]
2021-11-15T00:26:57.5860608Z [info] [JVM-1] StreamRefMultiJvmNode1:
2021-11-15T00:26:57.5972056Z [error] [JVM-1] Coroner Thread Count starts at 30 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6055262Z [error] [JVM-1] Coroner Thread Count starts at 31 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6065831Z [error] [JVM-1] Coroner Thread Count starts at 32 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6091393Z [error] [JVM-1] Coroner Thread Count starts at 33 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6094058Z [error] [JVM-1] Coroner Thread Count starts at 34 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6105394Z [error] [JVM-1] Coroner Thread Count starts at 35 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6114368Z [error] [JVM-1] Coroner Thread Count starts at 36 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6163970Z [error] [JVM-1] Coroner Thread Count starts at 37 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6256538Z [info] [JVM-2] StreamRefMultiJvmNode2:
2021-11-15T00:26:57.6258703Z [error] [JVM-1] Coroner Thread Count starts at 38 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6294175Z [info] [JVM-3] StreamRefMultiJvmNode3:
2021-11-15T00:26:57.6376496Z [error] [JVM-3] Coroner Thread Count starts at 24 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6413798Z [error] [JVM-1] Coroner Thread Count starts at 39 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6419947Z [info] [JVM-1] [2.682s][info][gc] GC(3) Pause Young (Normal) (G1 Evacuation Pause) 50M->12M(512M) 14.220ms
2021-11-15T00:26:57.6437290Z [info] [JVM-2] [2.416s][info][gc] GC(3) Pause Young (Normal) (G1 Evacuation Pause) 47M->12M(512M) 13.402ms
2021-11-15T00:26:57.6472329Z [error] [JVM-3] Coroner Thread Count starts at 25 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6480875Z [error] [JVM-3] Coroner Thread Count starts at 26 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6483970Z [error] [JVM-2] Coroner Thread Count starts at 24 in akka.cluster.StreamRefMultiJvmNode2

...

2021-11-15T00:32:01.1776127Z [error] [JVM-2] Coroner Thread Count starts at 7574 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1779036Z [error] [JVM-2] Coroner Thread Count starts at 7575 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1782389Z [error] [JVM-2] Coroner Thread Count starts at 7576 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1785365Z [error] [JVM-2] Coroner Thread Count starts at 7577 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1788283Z [error] [JVM-2] Coroner Thread Count starts at 7578 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1791208Z [error] [JVM-2] Coroner Thread Count starts at 7579 in akka.cluster.MembershipChangeListenerExitingMultiJvmNode2
2021-11-15T00:32:01.1793268Z [info] [JVM-2] *** RUN ABORTED *** (10 seconds, 166 milliseconds)
2021-11-15T00:32:01.1794627Z [info] [JVM-2]   java.lang.StackOverflowError:
2021-11-15T00:32:01.1796463Z [info] [JVM-2]   at akka.actor.dungeon.Dispatch.handleException(Dispatch.scala:125)
2021-11-15T00:32:01.1798645Z [info] [JVM-2]   at akka.actor.dungeon.Dispatch.sendMessage(Dispatch.scala:164)
2021-11-15T00:32:01.1800570Z [info] [JVM-2]   at akka.actor.dungeon.Dispatch.sendMessage$(Dispatch.scala:157)
2021-11-15T00:32:01.1802407Z [info] [JVM-2]   at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)
2021-11-15T00:32:01.1804041Z [info] [JVM-2]   at akka.actor.Cell.sendMessage(ActorCell.scala:327)
2021-11-15T00:32:01.1805605Z [info] [JVM-2]   at akka.actor.Cell.sendMessage$(ActorCell.scala:326)
2021-11-15T00:32:01.1807257Z [info] [JVM-2]   at akka.actor.ActorCell.sendMessage(ActorCell.scala:411)
2021-11-15T00:32:01.1809306Z [info] [JVM-2]   at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:182)
2021-11-15T00:32:01.1811327Z [info] [JVM-2]   at akka.event.EventStream.publish(EventStream.scala:47)
2021-11-15T00:32:01.1813233Z [info] [JVM-2]   at akka.event.EventStream.publish(EventStream.scala:26)
2021-11-15T00:32:01.1815077Z [info] [JVM-2]   at akka.event.SubchannelClassification.$anonfun$publish$1(EventBus.scala:178)
2021-11-15T00:32:01.1817075Z [info] [JVM-2]   at akka.event.SubchannelClassification.$anonfun$publish$1$adapted(EventBus.scala:178)
2021-11-15T00:32:01.1819038Z [info] [JVM-2]   at scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
2021-11-15T00:32:01.1821651Z [info] [JVM-2]   at akka.event.SubchannelClassification.publish(EventBus.scala:178)
2021-11-15T00:32:01.1824482Z [info] [JVM-2]   at akka.event.SubchannelClassification.publish$(EventBus.scala:166)
2021-11-15T00:32:01.1826329Z [info] [JVM-2]   at akka.event.EventStream.publish(EventStream.scala:26)
2021-11-15T00:32:01.1828444Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$muteLog$1(MultiNodeClusterSpec.scala:122)
2021-11-15T00:32:01.1831059Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$muteLog$1$adapted(MultiNodeClusterSpec.scala:121)
2021-11-15T00:32:01.1833319Z [info] [JVM-2]   at scala.collection.immutable.List.foreach(List.scala:333)
2021-11-15T00:32:01.1835593Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.muteLog(MultiNodeClusterSpec.scala:121)
2021-11-15T00:32:01.1838129Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.muteLog$(MultiNodeClusterSpec.scala:114)
2021-11-15T00:32:01.1841073Z [info] [JVM-2]   at akka.cluster.MembershipChangeListenerExitingSpec.muteLog(MembershipChangeListenerExitingSpec.scala:27)
2021-11-15T00:32:01.1844061Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:103)
2021-11-15T00:32:01.1846443Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:32:01.1849484Z [info] [JVM-2]   at akka.cluster.MembershipChangeListenerExitingSpec.atStartup(MembershipChangeListenerExitingSpec.scala:27)
2021-11-15T00:32:01.1852476Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:104)
2021-11-15T00:32:01.1855522Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:32:01.1860636Z [info] [JVM-2]   at akka.cluster.MembershipChangeListenerExitingSpec.atStartup(MembershipChangeListenerExitingSpec.scala:27)
2021-11-15T00:32:01.1867684Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:104)
2021-11-15T00:32:01.1870196Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:32:01.1873359Z [info] [JVM-2]   at akka.cluster.MembershipChangeListenerExitingSpec.atStartup(MembershipChangeListenerExitingSpec.scala:27)
```

**Comment by patriknw** [comment]
The StackOverflowError is a new regression unrelated to this issue. Closing this, and continuing that in https://github.com/akka/akka/issues/30885
