### ISSUE TITLE
failed: StackOverflowError in multi-node tests with Scala 2.13.7

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30885]
https://github.com/akka/akka/pull/30870 introduced some regression. I can reproduce with latest on `main` with:
```
sbt:akka-cluster> multi-jvm:testOnly akka.cluster.StreamRef
```

and it works after revert of 523b5b7f43

```
2021-11-15T00:26:45.6006919Z [info] * akka.cluster.StreamRef
2021-11-15T00:26:54.9685327Z [info] [JVM-1] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.2356223Z [info] [JVM-2] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.5082160Z [info] [JVM-3] [0.007s][info][gc] Using G1
2021-11-15T00:26:55.5526090Z [info] [JVM-1] [0.592s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 9.154ms
2021-11-15T00:26:55.7988430Z [info] [JVM-2] [0.570s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 11.160ms
2021-11-15T00:26:55.9663348Z [info] [JVM-1] [1.006s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 13.431ms
2021-11-15T00:26:56.0309012Z [info] [JVM-3] [0.529s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 29M->6M(512M) 9.992ms
2021-11-15T00:26:56.1096512Z [error] [JVM-1] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.1119470Z [error] [JVM-1] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.1131063Z [error] [JVM-1] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.1145719Z [error] [JVM-1] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.1151244Z [error] [JVM-1] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.1598079Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.116] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-3acbc99e-3d78-4e50-9448-702ea97ad11f]
2021-11-15T00:26:56.1703875Z [info] [JVM-2] [0.940s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 10.828ms
2021-11-15T00:26:56.2819626Z [error] [JVM-2] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.2846018Z [error] [JVM-2] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.2855300Z [error] [JVM-2] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.2877463Z [error] [JVM-2] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.2888291Z [error] [JVM-2] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.3355619Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.286] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-956812ac-592c-4000-9eb7-5f18b441aa62]
2021-11-15T00:26:56.4309553Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.398] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node1:6000] with UID [5962942504255699767]
2021-11-15T00:26:56.4317104Z [info] [JVM-3] [0.931s][info][gc] GC(1) Pause Young (Normal) (G1 Evacuation Pause) 29M->8M(512M) 9.241ms
2021-11-15T00:26:56.4558930Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.423] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.5161377Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.483] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - Started up successfully
2021-11-15T00:26:56.5546966Z [error] [JVM-3] WARNING: An illegal reflective access operation has occurred
2021-11-15T00:26:56.5556305Z [error] [JVM-3] WARNING: Illegal reflective access by org.agrona.nio.TransportPoller (file:/home/runner/work/akka/akka/target/1460089487/akka-cluster_2.13.7-2.6.17+48-86b000c3-SNAPSHOT-multi-jvm-assembly.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
2021-11-15T00:26:56.5567989Z [error] [JVM-3] WARNING: Please consider reporting this to the maintainers of org.agrona.nio.TransportPoller
2021-11-15T00:26:56.5576841Z [error] [JVM-3] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-11-15T00:26:56.5586545Z [error] [JVM-3] WARNING: All illegal access operations will be denied in a future release
2021-11-15T00:26:56.5595925Z [info] [JVM-1] [INFO] [11/15/2021 00:26:56.523] [StreamRef-akka.actor.internal-dispatcher-12] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node1:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:56.6026065Z [info] [JVM-1] [1.641s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 42M->10M(512M) 13.479ms
2021-11-15T00:26:56.6055855Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.574] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node2:6000] with UID [-6979541087986446429]
2021-11-15T00:26:56.6065215Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.559] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Started embedded media driver in directory [/opt/volumes/media-driver-StreamRef-45d5d73d-5616-411d-816e-d91914e244ed]
2021-11-15T00:26:56.6295175Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.596] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.6805196Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.648] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - Started up successfully
2021-11-15T00:26:56.7273461Z [info] [JVM-2] [INFO] [11/15/2021 00:26:56.695] [StreamRef-akka.actor.internal-dispatcher-2] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node2:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:56.7525659Z [info] [JVM-2] [1.525s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 41M->10M(512M) 13.703ms
2021-11-15T00:26:56.8809468Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.848] [ScalaTest-main] [ArteryTransport(akka://StreamRef)] Remoting started with transport [Artery aeron-udp]; listening on address [akka://StreamRef@test-node3:6000] with UID [-4276527013964994759]
2021-11-15T00:26:56.9032175Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.870] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - Starting up, Akka version [2.6.17+48-86b000c3-SNAPSHOT] ...
2021-11-15T00:26:56.9643325Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.932] [ScalaTest-main] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - Started up successfully
2021-11-15T00:26:57.0195581Z [info] [JVM-3] [INFO] [11/15/2021 00:26:56.987] [StreamRef-akka.actor.internal-dispatcher-12] [Cluster(akka://StreamRef)] Cluster Node [akka://StreamRef@test-node3:6000] - No seed-nodes configured, manual cluster join required, see https://doc.akka.io/docs/akka/current/typed/cluster.html#joining
2021-11-15T00:26:57.0624615Z [info] [JVM-3] [1.561s][info][gc] GC(2) Pause Young (Normal) (G1 Evacuation Pause) 43M->10M(512M) 12.645ms
2021-11-15T00:26:57.5000146Z [info] [JVM-1] [INFO] [11/15/2021 00:26:57.466] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode1] Role [first] started with address [akka://StreamRef@test-node1:6000]
2021-11-15T00:26:57.5414271Z [info] [JVM-2] [INFO] [11/15/2021 00:26:57.509] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode2] Role [second] started with address [akka://StreamRef@test-node2:6000]
2021-11-15T00:26:57.5504586Z [info] [JVM-3] [INFO] [11/15/2021 00:26:57.518] [ScalaTest-main] [akka.cluster.StreamRefMultiJvmNode3] Role [third] started with address [akka://StreamRef@test-node3:6000]
2021-11-15T00:26:57.5860608Z [info] [JVM-1] StreamRefMultiJvmNode1:
2021-11-15T00:26:57.5972056Z [error] [JVM-1] Coroner Thread Count starts at 30 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6055262Z [error] [JVM-1] Coroner Thread Count starts at 31 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6065831Z [error] [JVM-1] Coroner Thread Count starts at 32 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6091393Z [error] [JVM-1] Coroner Thread Count starts at 33 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6094058Z [error] [JVM-1] Coroner Thread Count starts at 34 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6105394Z [error] [JVM-1] Coroner Thread Count starts at 35 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6114368Z [error] [JVM-1] Coroner Thread Count starts at 36 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6163970Z [error] [JVM-1] Coroner Thread Count starts at 37 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6256538Z [info] [JVM-2] StreamRefMultiJvmNode2:
2021-11-15T00:26:57.6258703Z [error] [JVM-1] Coroner Thread Count starts at 38 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6294175Z [info] [JVM-3] StreamRefMultiJvmNode3:
2021-11-15T00:26:57.6376496Z [error] [JVM-3] Coroner Thread Count starts at 24 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6413798Z [error] [JVM-1] Coroner Thread Count starts at 39 in akka.cluster.StreamRefMultiJvmNode1
2021-11-15T00:26:57.6419947Z [info] [JVM-1] [2.682s][info][gc] GC(3) Pause Young (Normal) (G1 Evacuation Pause) 50M->12M(512M) 14.220ms
2021-11-15T00:26:57.6437290Z [info] [JVM-2] [2.416s][info][gc] GC(3) Pause Young (Normal) (G1 Evacuation Pause) 47M->12M(512M) 13.402ms
2021-11-15T00:26:57.6472329Z [error] [JVM-3] Coroner Thread Count starts at 25 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6480875Z [error] [JVM-3] Coroner Thread Count starts at 26 in akka.cluster.StreamRefMultiJvmNode3
2021-11-15T00:26:57.6483970Z [error] [JVM-2] Coroner Thread Count starts at 24 in akka.cluster.StreamRefMultiJvmNode2

...

2021-11-15T00:27:05.7344564Z [error] [JVM-2] Coroner Thread Count starts at 8158 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7359567Z [error] [JVM-2] Coroner Thread Count starts at 8159 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7371822Z [error] [JVM-2] Coroner Thread Count starts at 8160 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7383965Z [error] [JVM-2] Coroner Thread Count starts at 8161 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7392136Z [error] [JVM-2] Coroner Thread Count starts at 8162 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7403532Z [error] [JVM-2] Coroner Thread Count starts at 8163 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7415494Z [error] [JVM-2] Coroner Thread Count starts at 8164 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7428747Z [error] [JVM-2] Coroner Thread Count starts at 8165 in akka.cluster.StreamRefMultiJvmNode2
2021-11-15T00:27:05.7855873Z [info] [JVM-2] *** RUN ABORTED *** (10 seconds, 127 milliseconds)
2021-11-15T00:27:05.7859774Z [info] [JVM-2]   java.lang.StackOverflowError:
2021-11-15T00:27:05.7864757Z [info] [JVM-2]   at java.base/java.util.regex.PatternSyntaxException.<init>(PatternSyntaxException.java:59)
2021-11-15T00:27:05.7870431Z [info] [JVM-2]   at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
2021-11-15T00:27:05.7875849Z [info] [JVM-2]   at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
2021-11-15T00:27:05.7882763Z [info] [JVM-2]   at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
2021-11-15T00:27:05.7888720Z [info] [JVM-2]   at scala.util.matching.Regex.<init>(Regex.scala:234)
2021-11-15T00:27:05.7896614Z [info] [JVM-2]   at akka.testkit.EventFilter$.$anonfun$info$1(TestEventListener.scala:257)
2021-11-15T00:27:05.7902304Z [info] [JVM-2]   at scala.Option.map(Option.scala:242)
2021-11-15T00:27:05.7907693Z [info] [JVM-2]   at akka.testkit.EventFilter$.info(TestEventListener.scala:257)
2021-11-15T00:27:05.7915133Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$muteLog$1(MultiNodeClusterSpec.scala:122)
2021-11-15T00:27:05.7923085Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$muteLog$1$adapted(MultiNodeClusterSpec.scala:121)
2021-11-15T00:27:05.7931621Z [info] [JVM-2]   at scala.collection.immutable.List.foreach(List.scala:333)
2021-11-15T00:27:05.7939476Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.muteLog(MultiNodeClusterSpec.scala:121)
2021-11-15T00:27:05.7948198Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.muteLog$(MultiNodeClusterSpec.scala:114)
2021-11-15T00:27:05.7955925Z [info] [JVM-2]   at akka.cluster.StreamRefSpec.muteLog(StreamRefSpec.scala:144)
2021-11-15T00:27:05.7963950Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:103)
2021-11-15T00:27:05.7972872Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:27:05.7981959Z [info] [JVM-2]   at akka.cluster.StreamRefSpec.atStartup(StreamRefSpec.scala:144)
2021-11-15T00:27:05.7990369Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:104)
2021-11-15T00:27:05.7998398Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:27:05.8007481Z [info] [JVM-2]   at akka.cluster.StreamRefSpec.atStartup(StreamRefSpec.scala:144)
2021-11-15T00:27:05.8015700Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:104)
2021-11-15T00:27:05.8025870Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
2021-11-15T00:27:05.8035765Z [info] [JVM-2]   at akka.cluster.StreamRefSpec.atStartup(StreamRefSpec.scala:144)
2021-11-15T00:27:05.8049833Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup(MultiNodeClusterSpec.scala:104)
2021-11-15T00:27:05.8060209Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.atStartup$(MultiNodeClusterSpec.scala:101)
```

**Comment by raboof** [comment]
Seems like we saw something similar in #30689

**Comment by patriknw** [comment]
Thanks, I'll try changing that
