### ISSUE TITLE
Failed: OutOfMemoryError in cluster tests

### ISSUE THREAD

**Issue by johanandren** [akka/akka#30903]
https://github.com/akka/akka/runs/4195738468?check_suite_focus=true#step:5:10079
https://github.com/akka/akka/runs/4195738419?check_suite_focus=true#step:5:10906
https://github.com/akka/akka/runs/4195738273?check_suite_focus=true#step:5:8509

```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at java.base/java.lang.Thread.start0(Native Method)
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at java.base/java.lang.Thread.start(Thread.java:798)
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at akka.testkit.Coroner$.watch(Coroner.scala:122)
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at akka.testkit.WatchedByCoroner.startCoroner(Coroner.scala:270)
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at akka.testkit.WatchedByCoroner.startCoroner$(Coroner.scala:264)
[info] [JVM-4-ClusterMetricsDisabledMultiJvmNode4]   at akka.cluster.metrics.ClusterMetricsDisabledSpec.startCoroner(ClusterMetricsExtensionSpec.scala:141)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/4195738419?check_suite_focus=true
https://github.com/akka/akka/runs/4195738273?check_suite_focus=true
https://github.com/akka/akka/runs/4195738468?check_suite_focus=true

**Comment by johanandren** [comment]
These were all a few days ago, I wonder if it perhaps got fixed by @patriknw s tweaking of k8 resources and/or passing params to Aeron?

**Comment by johanandren** [comment]
This is the newest one, 3 days ago: 
https://github.com/akka/akka/runs/4206126131?check_suite_focus=true

Could also be related to #30905 because I see those logs as well

**Comment by johanandren** [comment]
I think @patriknw is right in #30905, let's close this as well.
