### ISSUE TITLE
failed: JoinConfigCompatCheckerRollingUpdateSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30939]
https://github.com/akka/akka/runs/4329062976?check_suite_focus=true#step:5:2386

```
[info] - must NOT be allowed to re-join a cluster if it has a new, additional configuration the others do not have and not the old *** FAILED *** (41 seconds, 475 milliseconds)
2387
[info]   java.lang.AssertionError: assertion failed: timeout 39999934200 nanoseconds expired: awaiting node [akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.1.187:33579] to be 'Removed'. Current status: [Up]
2388
[info]   at scala.Predef$.assert(Predef.scala:279)
2389
[info]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
2390
[info]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
2391
[info]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
2392
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
2393
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.quitAndRestart(ClusterTestKit.scala:123)
2394
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$7(ClusterTestKit.scala:213)
2395
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2396
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:418)
2397
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)
2398
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
2399
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:433)
2400
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)
2401
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
2402
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$6(ClusterTestKit.scala:212)
2403
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$6$adapted(ClusterTestKit.scala:211)
2404
[info]   at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
2405
[info]   at akka.cluster.RollingUpgradeClusterSpec.upgradeCluster(ClusterTestKit.scala:211)
2406
[info]   at akka.cluster.JoinConfigCompatCheckerRollingUpdateSpec.$anonfun$new$2(JoinConfigCompatCheckerRollingUpdateSpec.scala:54)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4329100079?check_suite_focus=true#step:9:3102
