### ISSUE TITLE
failed: ClusterReceptionistSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30940]
https://github.com/akka/akka/runs/4318491689?check_suite_focus=true

We had https://github.com/akka/akka/issues/30906 but then said it was because of the /dev/shm issue.
This is still with aeron-udp, but now it's not using /dev/shm

```
2021-11-25T01:49:07.4205570Z [info] - must notify subscribers when registering and joining simultaneously *** FAILED *** (1 minute, 48 seconds)
2021-11-25T01:49:07.4207007Z [info]   3 did not equal 6 (ClusterReceptionistSpec.scala:822)
2021-11-25T01:49:07.4208517Z [info]   org.scalatest.exceptions.TestFailedException:
2021-11-25T01:49:07.4210343Z [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
2021-11-25T01:49:07.4212254Z [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
2021-11-25T01:49:07.4214835Z [info]   at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$55(ClusterReceptionistSpec.scala:822)
2021-11-25T01:49:07.4217530Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:374)
2021-11-25T01:49:07.4219923Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:391)
2021-11-25T01:49:07.4222519Z [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:350)
2021-11-25T01:49:07.4225596Z [info]   at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$54(ClusterReceptionistSpec.scala:823)
2021-11-25T01:49:07.4228845Z [info]   at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$54$adapted(ClusterReceptionistSpec.scala:820)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/4280998437?check_suite_focus=true

**Comment by pvlugter** [comment]
With aeron tests re-enabled (#31010), this one has failed. Slightly different failure, but also a timeout when waiting for all state on all 6 nodes:

```
[info] - must notify subscribers when registering and joining simultaneously *** FAILED *** (1 minute, 29 seconds)
[info]   java.lang.AssertionError: timeout (20 seconds) during fishForMessage, seen messages List(...)
```

Gets up to 5 of the 6 expected actors.

Are the timeouts simply not long enough?

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/5328075936?check_suite_focus=true

Same as the first report.

```
2022-02-25T03:46:10.0559129Z [0m[[0m[0minfo[0m] [0m[0m[31m- must notify subscribers when registering and joining simultaneously *** FAILED *** (1 minute, 18 seconds)[0m[0m
2022-02-25T03:46:10.0559604Z [0m[[0m[0minfo[0m] [0m[0m[31m  3 did not equal 6 (ClusterReceptionistSpec.scala:822)[0m[0m
2022-02-25T03:46:10.0560084Z [0m[[0m[0minfo[0m] [0m[0m[31m  org.scalatest.exceptions.TestFailedException:[0m[0m
2022-02-25T03:46:10.0560653Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)[0m[0m
2022-02-25T03:46:10.0561248Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)[0m[0m
2022-02-25T03:46:10.0562000Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$55(ClusterReceptionistSpec.scala:822)[0m[0m
2022-02-25T03:46:10.0562608Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:374)[0m[0m
2022-02-25T03:46:10.0563346Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:391)[0m[0m
2022-02-25T03:46:10.0563940Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:350)[0m[0m
2022-02-25T03:46:10.0564822Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$54(ClusterReceptionistSpec.scala:823)[0m[0m
2022-02-25T03:46:10.0565586Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$54$adapted(ClusterReceptionistSpec.scala:820)[0m[0m
2022-02-25T03:46:10.0568262Z [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.Range.foreach(Range.scala:190)[0m[0m
2022-02-25T03:46:10.0569091Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.$anonfun$new$45(ClusterReceptionistSpec.scala:820)[0m[0m
2022-02-25T03:46:10.0569752Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
2022-02-25T03:46:10.0570257Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
2022-02-25T03:46:10.0570722Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
2022-02-25T03:46:10.0571211Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
2022-02-25T03:46:10.0571691Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
2022-02-25T03:46:10.0572268Z [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)[0m[0m
2022-02-25T03:46:10.0572870Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)[0m[0m
2022-02-25T03:46:10.0573483Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)[0m[0m
2022-02-25T03:46:10.0574268Z [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.typed.internal.receptionist.ClusterReceptionistSpec.withFixture(ClusterReceptionistSpec.scala:76)[0m[0m
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5442403089?check_suite_focus=true

**Comment by johanandren** [comment]
I see quite a bit of "Scheduled sending of heartbeat was delayed." and nodes marked UNREACHABLE.

This is a test where each test case starts forms a cluster that is then shutdown, the other test cases only start two though, while this test case start 6 nodes. When I tried to run this test repeatedly many times in the same sbt test invocation it relatively quickly OOM:ed, I wonder if the github CI node is simply to resource constrained to run 6 aeron-udp cluster nodes in the same JVM?

**Comment by patriknw** [comment]
This isn't a multi-node test itself. Does that mean that it's running in the github CI node and not in Kubernetes?

**Comment by patriknw** [comment]
Closing, reason might be https://github.com/akka/akka/pull/31217
This test has now been excluded when running with Aeron, in https://github.com/akka/akka/pull/31218
