### ISSUE TITLE
failed: StageActorRefSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30942]
https://github.com/akka/akka/runs/4331747855?check_suite_focus=true#step:5:9555

```
[info] - must ignore and log warnings for PoisonPill and Kill messages *** FAILED *** (4 seconds, 38 milliseconds)
9556
[info]   2 did not equal 42 (StageActorRefSpec.scala:169)
9557
[info]   org.scalatest.exceptions.TestFailedException:
9558
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
9559
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
9560
[info]   at akka.stream.scaladsl.StageActorRefSpec.$anonfun$new$9(StageActorRefSpec.scala:169)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka/runs/5133864067?check_suite_focus=true
