### ISSUE TITLE
failed: ClusterShardingQueriesSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#30961]
https://github.com/akka/akka/runs/4402426734?check_suite_focus=true

```scala
2021-12-03T00:15:22.1151176Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1] - must return shard stats of cluster sharding regions if one or more shards timeout, versus all as empty (on node 'controller', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode1) *** FAILED ***�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1154742Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   java.lang.RuntimeException: barrier failed: received failed stats from timed out shards vs empty�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1157341Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:245)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1160111Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.remote.testconductor.ClientFSM$$anonfun$3.applyOrElse(Player.scala:219)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1162946Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1167096Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.actor.FSM.processEvent(FSM.scala:851)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1169090Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.actor.FSM.processEvent$(FSM.scala:848)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1171454Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.remote.testconductor.ClientFSM.akka$actor$LoggingFSM$$super$processEvent(Player.scala:172)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1174230Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.actor.LoggingFSM.processEvent(FSM.scala:991)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1176412Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.actor.LoggingFSM.processEvent$(FSM.scala:973)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1178890Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.remote.testconductor.ClientFSM.processEvent(Player.scala:172)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m
2021-12-03T00:15:22.1181232Z [info] [JVM-1-ClusterShardingQueriesSpecMultiJvmNode1]   at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:845)�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m�[0m

```

but also 

```scala
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] - must return shard stats of cluster sharding regions if one or more shards timeout, versus all as empty (on node 'busy', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode2) *** FAILED ***
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2]   5 did not equal 4 (ClusterShardingQueriesSpec.scala:123)
[info] [JVM-4-ClusterShardingQueriesSpecMultiJvmNode4] - must return shard stats of cluster sharding regions if one or more shards timeout, versus all as empty (on node 'third', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode4) *** FAILED ***
[info] [JVM-4-ClusterShardingQueriesSpecMultiJvmNode4]   5 did not equal 4 (ClusterShardingQueriesSpec.scala:123)
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'busy', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode2) !!! CANCELED !!!
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2]   Previous step failed (MultiNodeClusterSpec.scala:187)
[info] [JVM-4-ClusterShardingQueriesSpecMultiJvmNode4] - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'third', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode4) !!! CANCELED !!!
[info] [JVM-4-ClusterShardingQueriesSpecMultiJvmNode4]   Previous step failed (MultiNodeClusterSpec.scala:187)
[info] [JVM-3-ClusterShardingQueriesSpecMultiJvmNode3] - must return shard stats of cluster sharding regions if one or more shards timeout, versus all as empty (on node 'second', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode3) *** FAILED ***
[info] [JVM-3-ClusterShardingQueriesSpecMultiJvmNode3]   5 did not equal 4 (ClusterShardingQueriesSpec.scala:123)
[info] [JVM-3-ClusterShardingQueriesSpecMultiJvmNode3] - must return shard state of sharding regions if one or more shards timeout, versus all as empty (on node 'second', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode3) !!! CANCELED !!!
[info] [JVM-3-ClusterShardingQueriesSpecMultiJvmNode3]   Previous step failed (MultiNodeClusterSpec.scala:187)
```

**Comment by octonato** [comment]
This one is puzzling. 

Also in the logs, we see...

```scala
- must return shard stats of cluster sharding regions if one or more shards timeout, versus all as empty (on node 'busy', class akka.cluster.sharding.ClusterShardingQueriesSpecMultiJvmNode2) *** FAILED ***
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2]   5 did not equal 4 (ClusterShardingQueriesSpec.scala:123)
```

Actually, the above is the real failure in the tests. 

If I understand the test correctly, we have 3 nodes, each with 2 shards. One node, the `busy` one, is configured with `shard-region-query-timeout = 0ms` to force it to timeout when querying shard. Still, we receive 5 stats when querying.

**Comment by octonato** [comment]
Ok, may have found something...

In a passing tests we see the following:

```
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [02/21/2022 14:47:18.628] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-3] [akka.tcp://ClusterShardingQueriesSpec@localhost:43715/system/sharding/DatatypeA] DatatypeA: Queried [2] shards: [0] responsive, [2] failed after 0 milliseconds.
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [02/21/2022 14:47:18.640] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-4] [akka.tcp://ClusterShardingQueriesSpec@localhost:43715/system/sharding/DatatypeA] DatatypeA: Queried [2] shards: [0] responsive, [2] failed after 0 milliseconds.
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [02/21/2022 14:47:18.713] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-5] [akka.tcp://ClusterShardingQueriesSpec@localhost:43715/system/sharding/DatatypeA] DatatypeA: Queried [2] shards: [0] responsive, [2] failed after 0 milliseconds.
```

but in the failing one we see...

```scala
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [12/03/2021 00:15:20.955] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-3] [akka.tcp://ClusterShardingQueriesSpec@localhost:33487/system/sharding/DatatypeA] DatatypeA: Queried [1] shards: [0] responsive, [1] failed after 0 milliseconds.
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [12/03/2021 00:15:20.977] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-5] [akka.tcp://ClusterShardingQueriesSpec@localhost:33487/system/sharding/DatatypeA] DatatypeA: Queried [1] shards: [0] responsive, [1] failed after 0 milliseconds.
[info] [JVM-2-ClusterShardingQueriesSpecMultiJvmNode2] [WARN] [12/03/2021 00:15:20.993] [ClusterShardingQueriesSpec-akka.actor.internal-dispatcher-3] [akka.tcp://ClusterShardingQueriesSpec@localhost:33487/system/sharding/DatatypeA] DatatypeA: Queried [1] shards: [0] responsive, [1] failed after 0 milliseconds.
```

It seems the `busy` one has only one shard allocated to it while we expect 2 shards. 

I will make the rebalance settings more aggressive to ensure that we get everything evenly distributed as fast as possible.

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5276807795?check_suite_focus=true#step:5:2421
