### ISSUE TITLE
failed: OutboundIdleShutdownSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30984]
multi-node with aeron-udp

https://github.com/akka/akka/runs/4500485510?check_suite_focus=true

```
2021-12-13T02:04:12.0455829Z [info]   The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-4@localhost:42137/), Path(/user/echo)]. (OutboundIdleShutdownSpec.scala:198)
2021-12-13T02:04:12.0461246Z [info]   org.scalatest.exceptions.TestFailedException:
2021-12-13T02:04:12.0466128Z [info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
2021-12-13T02:04:12.0470696Z [info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
2021-12-13T02:04:12.0475510Z [info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
2021-12-13T02:04:12.0482611Z [info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
2021-12-13T02:04:12.0485677Z [info]   at akka.remote.artery.OutboundIdleShutdownSpec.withAssociation$1(OutboundIdleShutdownSpec.scala:198)
2021-12-13T02:04:12.0488597Z [info]   at akka.remote.artery.OutboundIdleShutdownSpec.$anonfun$new$20(OutboundIdleShutdownSpec.scala:141)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4495316564?check_suite_focus=true

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4554855749?check_suite_focus=true

**Comment by patriknw** [comment]
If this fails again we can switch to retry as discussed in PR

**Comment by pvlugter** [comment]
Failed in https://github.com/akka/akka/runs/5802653929?check_suite_focus=true#step:5:2275

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/6890950812?check_suite_focus=true

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6951601688?check_suite_focus=true#step:5:2224

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/6995218784?check_suite_focus=true#step:5:2351

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/7224937888?check_suite_focus=true

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7331485740?check_suite_focus=true#step:5:2434

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7708433816?check_suite_focus=true#step:5:2784

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/8046410206?check_suite_focus=true#step:5:2372

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8165683316?check_suite_focus=true#step:5:2229

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8172943395?check_suite_focus=true#step:5:2358

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8239618394?check_suite_focus=true#step:5:2396

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3056918371/jobs/4931539053

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3124231250/jobs/5067396421#step:5:2386

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3139903168/jobs/5100752068#step:5:2271

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3170648683/jobs/5163372446#step:5:2128

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3178443393/jobs/5179936204#step:5:2285

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3193592614/jobs/5212304332#step:5:2274

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3201361974/jobs/5229253627#step:5:2301

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3246562917/jobs/5325442015#step:5:2205

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3261479772/jobs/5356458261#step:5:2430

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3277859636/jobs/5395610387#step:5:2223

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3333504126/jobs/5515491830#step:5:2183

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2267

```
[info] - should remove inbound compression after restart with same host:port *** FAILED *** (2 seconds, 796 milliseconds)
[2267](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2268)
[info]   The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-4@localhost:44142/), Path(/user/echo)]. (OutboundIdleShutdownSpec.scala:200)
[2268](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2269)
[info]   org.scalatest.exceptions.TestFailedException:
[2269](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2270)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[2270](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2271)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[2271](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2272)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[2272](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2273)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[2273](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2274)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.withAssociation$1(OutboundIdleShutdownSpec.scala:200)
[2274](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2275)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.$anonfun$new$20(OutboundIdleShutdownSpec.scala:142)
[2275](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2276)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[2276](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2277)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[2277](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2278)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[2278](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2279)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[2279](https://github.com/akka/akka/actions/runs/3424254041/jobs/5703719021#step:5:2280)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3441439293/jobs/5740977407#step:5:2230

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3453087566/jobs/5763405183#step:5:2871

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3501155899/jobs/5864511602#step:5:2533

```
[info] - should still be resumable after they have been stopped *** FAILED *** (19 seconds, 872 milliseconds)
[info]   The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-1@localhost:58332/), Path(/user/echo)]. (OutboundIdleShutdownSpec.scala:200)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.withAssociation$1(OutboundIdleShutdownSpec.scala:200)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.$anonfun$new$6(OutboundIdleShutdownSpec.scala:79)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3528120611/jobs/5917878187#step:5:2188

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5019402466/jobs/8999848092#step:5:1686

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5273326711/jobs/9536614544#step:5:1939

```
[info] - should remove inbound compression after restart with same host:port *** FAILED *** (23 seconds, 105 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 20 times over 20.155365965 seconds. Last failure message: The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-4@localhost:60495/), Path(/user/echo2)].. (OutboundIdleShutdownSpec.scala:162)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:219)
[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:226)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:415)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:414)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.eventually(OutboundIdleShutdownSpec.scala:25)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5366869791/jobs/9736544836#step:5:1669

```scala
[info] - should remove inbound compression after restart with same host:port *** FAILED *** (20 seconds, 35 milliseconds)
[info]   The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-4@localhost:44207/), Path(/user/echo)]. (OutboundIdleShutdownSpec.scala:200)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.withAssociation$1(OutboundIdleShutdownSpec.scala:200)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.$anonfun$new$20(OutboundIdleShutdownSpec.scala:142)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/6140268261/job/16659007653#step:5:1584

```scala
[1583](https://github.com/akka/akka/actions/runs/6140268261/job/16659007653#step:5:1584)
[info] - should remove inbound compression after quarantine *** FAILED *** (20 seconds, 28 milliseconds)
[info]   The future returned an exception of type: akka.actor.ActorNotFound, with message: Actor not found for: ActorSelection[Anchor(akka://OutboundIdleShutdownSpec-remote-3@localhost:49242/), Path(/user/echo)]. (OutboundIdleShutdownSpec.scala:200)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.withAssociation$1(OutboundIdleShutdownSpec.scala:200)
[info]   at akka.remote.artery.OutboundIdleShutdownSpec.$anonfun$new$16(OutboundIdleShutdownSpec.scala:122)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6462983479/job/17545453173#step:5:1804
