### ISSUE TITLE
failed: LargeMessagesStreamSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#30985]
multi-node with aeron-udp

https://github.com/akka/akka/runs/4495316564?check_suite_focus=true

```
2021-12-12T02:04:30.2862821Z [WARN] [12/12/2021 02:04:30.285] [pool-1-thread-1] [akka.actor.ActorSystemImpl(LargeMessagesStreamSpec)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
2021-12-12T02:04:30.2868066Z [WARN] [12/12/2021 02:04:30.286] [pool-1-thread-1] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
2021-12-12T02:04:30.3295818Z [info] LargeMessagesStreamSpec:
2021-12-12T02:04:30.3319869Z Coroner Thread Count starts at 24 in akka.remote.artery.LargeMessagesStreamSpec
2021-12-12T02:04:30.3321961Z [info] The large message support
2021-12-12T02:04:30.3424221Z [WARN] [12/12/2021 02:04:30.341] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.actor.ActorSystemImpl(LargeMessagesStreamSpec-remote-0)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
2021-12-12T02:04:30.3431990Z [WARN] [12/12/2021 02:04:30.342] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
2021-12-12T02:04:35.6443109Z [WARN] [12/12/2021 02:04:35.642] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$a] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-0@localhost:54647/user/regular#-2075868826]))
2021-12-12T02:04:35.6449617Z [WARN] [12/12/2021 02:04:35.643] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$b] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-0@localhost:54647/user/regular#-2075868826]))
2021-12-12T02:04:35.6455627Z [WARN] [12/12/2021 02:04:35.643] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/_user_regular$c] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-0@localhost:54647/user/regular#-2075868826]))
2021-12-12T02:04:35.6461681Z [WARN] [12/12/2021 02:04:35.643] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/_user_regular$d] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-0@localhost:54647/user/regular#-2075868826]))
2021-12-12T02:04:35.6667436Z [info] - should not affect regular communication (5 seconds, 335 milliseconds)
2021-12-12T02:04:35.6926325Z [WARN] [12/12/2021 02:04:35.688] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.actor.ActorSystemImpl(LargeMessagesStreamSpec-remote-1)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
2021-12-12T02:04:35.6933108Z [WARN] [12/12/2021 02:04:35.688] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
2021-12-12T02:04:43.5551293Z [WARN] [12/12/2021 02:04:43.269] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-6] [akka://LargeMessagesStreamSpec/temp/$f] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:55321/user/large#-1563587700]))
2021-12-12T02:04:43.5558400Z [WARN] [12/12/2021 02:04:43.269] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-6] [akka://LargeMessagesStreamSpec/temp/$g] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:55321/user/large#-1563587700]))
2021-12-12T02:04:43.5573571Z [WARN] [12/12/2021 02:04:43.269] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-6] [akka://LargeMessagesStreamSpec/temp/$h] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:55321/user/large#-1563587700]))
2021-12-12T02:04:43.5577816Z [info] - should pass small regular messages over the large-message stream *** FAILED *** (6 seconds, 602 milliseconds)
2021-12-12T02:04:43.6213598Z [info]   java.util.concurrent.TimeoutException: Future timed out after [1 second]
2021-12-12T02:04:43.6216291Z [info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
2021-12-12T02:04:43.6227917Z [info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
2021-12-12T02:04:43.6230438Z [info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
2021-12-12T02:04:43.6233518Z [info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
2021-12-12T02:04:43.6235673Z [info]   at scala.concurrent.Await$.result(package.scala:124)
2021-12-12T02:04:43.6238544Z [info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$awaitResolve$1(LargeMessagesStreamSpec.scala:154)
2021-12-12T02:04:43.6241180Z [info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
2021-12-12T02:04:43.6243249Z [info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
2021-12-12T02:04:43.6246664Z [info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
2021-12-12T02:04:43.6248607Z [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
2021-12-12T02:04:43.6251322Z [info]   at akka.remote.artery.LargeMessagesStreamSpec.awaitResolve(LargeMessagesStreamSpec.scala:153)
2021-12-12T02:04:43.6254659Z [info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$new$4(LargeMessagesStreamSpec.scala:75)
2021-12-12T02:04:43.6318406Z [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
2021-12-12T02:04:43.6320937Z [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
2021-12-12T02:04:43.6322841Z [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
2021-12-12T02:04:43.6325212Z [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
2021-12-12T02:04:43.6327478Z [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
2021-12-12T02:04:43.6329683Z [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
2021-12-12T02:04:43.6332302Z [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
2021-12-12T02:04:43.6334470Z [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
2021-12-12T02:04:43.6337029Z [info]   at akka.remote.artery.ArteryMultiNodeSpec.withFixture(ArteryMultiNodeSpec.scala:48)
2021-12-12T02:04:43.6340215Z [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
2021-12-12T02:04:43.6343100Z [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
2021-12-12T02:04:43.6345353Z [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
2021-12-12T02:04:43.6347736Z [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
2021-12-12T02:04:43.6350420Z [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
2021-12-12T02:04:43.6352647Z [info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
2021-12-12T02:04:43.6354797Z [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/4571864373?check_suite_focus=true

**Comment by patriknw** [comment]
Closing, reason might be #31217

**Comment by patriknw** [comment]
Again, now in the Aeron job in nightly-builds: https://github.com/akka/akka/runs/5476047197?check_suite_focus=true#step:5:1897

```
[WARN] [03/09/2022 06:37:10.246] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.actor.ActorSystemImpl(LargeMessagesStreamSpec-remote-1)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
1892
[WARN] [03/09/2022 06:37:10.246] [pool-1-thread-1-ScalaTest-running-LargeMessagesStreamSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
1893
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$e] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
1894
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$f] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
1895
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$g] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
1896
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/_user_large$h] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
1897
[info] - should pass small regular messages over the large-message stream *** FAILED *** (6 seconds, 162 milliseconds)
1898
[info]   java.util.concurrent.TimeoutException: Future timed out after [1 second]
1899
[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
1900
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
1901
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
1902
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
1903
[info]   at scala.concurrent.Await$.result(package.scala:124)
1904
[info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$awaitResolve$1(LargeMessagesStreamSpec.scala:154)
1905
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
1906
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
1907
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
1908
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
1909
[info]   at akka.remote.artery.LargeMessagesStreamSpec.awaitResolve(LargeMessagesStreamSpec.scala:153)
1910
[info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$new$4(LargeMessagesStreamSpec.scala:75)
```

**Comment by johanandren** [comment]
Looks like the resolve timeout of 1 s is simply too short, because we see the actor identity coming back but ending up in dead letters:

```
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$e] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
[1894](https://github.com/akka/akka/runs/5476047197?check_suite_focus=true#step:5:1894)
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$f] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
[1895](https://github.com/akka/akka/runs/5476047197?check_suite_focus=true#step:5:1895)
[WARN] [03/09/2022 06:37:16.782] [LargeMessagesStreamSpec-akka.actor.default-dispatcher-13] [akka://LargeMessagesStreamSpec/temp/$g] received dead letter: ActorIdentity(None,Some(Actor[akka://LargeMessagesStreamSpec-remote-1@localhost:58629/user/large#-1011103790]))
```

**Comment by patriknw** [comment]
> Looks like the resolve timeout of 1 s is simply too short

but it's within an `awaitAssert` (6 seconds) so strange if that isn't enough

**Comment by johanandren** [comment]
If each lookup takes more than 1s, so it doesn't matter how many times it tries (but why on earth does each lookup take longer than 1s with aeron-udp?)

**Comment by patriknw** [comment]
yeah, that is what I mean, I can understand that once in a while it could be as slow as 1 second but 5-6 attempts in a row sounds so strange. What I could see, the resolve were all before the actual "heavy" message sending started.

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5488805502?check_suite_focus=true#step:5:1928

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5504441498?check_suite_focus=true#step:5:1849

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5518509786?check_suite_focus=true#step:5:1938

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5599839394?check_suite_focus=true#step:5:1882

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5608122325?check_suite_focus=true#step:5:1908

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5620460679?check_suite_focus=true#step:5:1885

**Comment by jrudolph** [comment]
https://github.com/akka/akka/runs/5636607048?check_suite_focus=true
