### ISSUE TITLE
failed: AccountExampleTest with Scala3

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31000]
https://github.com/akka/akka/runs/4554787955?check_suite_focus=true#step:5:1461

```
--> [jdocs.akka.cluster.sharding.typed.AccountExampleTest: verifySerialization] Start of log messages of test that failed with No serializer found for class jdocs.akka.cluster.sharding.typed.AccountExampleWithEventHandlersInState$AccountEntity$AccountClosed and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
1459
2021-12-17 00:13:58,849 INFO  akka.actor.testkit.typed.javadsl.LogCapturing  - Logging started for test [jdocs.akka.cluster.sharding.typed.AccountExampleTest: verifySerialization] MDC: {}
1460
<-- [jdocs.akka.cluster.sharding.typed.AccountExampleTest: verifySerialization] End of log messages of test that failed with No serializer found for class jdocs.akka.cluster.sharding.typed.AccountExampleWithEventHandlersInState$AccountEntity$AccountClosed and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
1461
[info] - verifySerialization *** FAILED ***
1462
[info]   com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class jdocs.akka.cluster.sharding.typed.AccountExampleWithEventHandlersInState$AccountEntity$AccountClosed and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
1463
[info]   at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
1464
[info]   at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
1465
[info]   at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
1466
[info]   at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
1467
[info]   at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
1468
[info]   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
1469
[info]   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
1470
[info]   at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4514)
1471
[info]   at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3790)
1472
[info]   at akka.serialization.jackson.JacksonSerializer.toBinary(JacksonSerializer.scala:283)
1473
[info]   at akka.serialization.Serialization.serialize$$anonfun$1$$anonfun$1(Serialization.scala:167)
1474
[info]   at scala.util.Try$.apply(Try.scala:210)
1475
[info]   at akka.serialization.Serialization.serialize$$anonfun$1(Serialization.scala:167)
1476
[info]   at akka.serialization.Serialization.withTransportInformation(Serialization.scala:157)
1477
[info]   at akka.serialization.Serialization.serialize(Serialization.scala:167)
1478
[info]   at akka.actor.testkit.typed.scaladsl.SerializationTestKit.roundtrip(SerializationTestKit.scala:55)
1479
[info]   at akka.actor.testkit.typed.scaladsl.SerializationTestKit.verifySerialization(SerializationTestKit.scala:41)
1480
[info]   at akka.actor.testkit.typed.javadsl.SerializationTestKit.verifySerialization(SerializationTestKit.scala:27)
1481
[info]   at jdocs.akka.cluster.sharding.typed.AccountExampleTest.verifySerialization(AccountExampleTest.java:183)
```

**Comment by patriknw** [comment]
there are a few more similar, such as:
```
<-- [jdocs.akka.cluster.sharding.typed.AccountExampleDocTest: handleGetBalance] End of log messages of test that failed with Empty State [jdocs.akka.cluster.sharding.typed.AccountExampleWithEventHandlersInState$AccountEntity$EmptyAccount@624dd1b2] isn't serializable.
869
[info] - handleGetBalance *** FAILED ***
870
[info]   java.lang.IllegalArgumentException: Empty State [jdocs.akka.cluster.sharding.typed.AccountExampleWithEventHandlersInState$AccountEntity$EmptyAccount@624dd1b2] isn't serializable.
871
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.verifySerializationAndThrow(EventSourcedBehaviorTestKitImpl.scala:232)
872
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.preCommandCheck(EventSourcedBehaviorTestKitImpl.scala:188)
873
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.runCommand(EventSourcedBehaviorTestKitImpl.scala:135)
874
[info]   at akka.persistence.testkit.javadsl.EventSourcedBehaviorTestKit.runCommand(EventSourcedBehaviorTestKit.scala:221)
875
[info]   at jdocs.akka.cluster.sharding.typed.AccountExampleDocTest.handleGetBalance(AccountExampleDocTest.java:111)
```

**Comment by patriknw** [comment]
I guess this has been fixed
