### ISSUE TITLE
failed: HubSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31028]
https://github.com/akka/akka/runs/4676576193?check_suite_focus=true#step:5:18116

```
[WARN] [01/01/2022 00:49:46.181] [HubSpec-akka.actor.default-dispatcher-6] [akka://HubSpec/user/StreamSupervisor*] received dead letter from Actor[akka://HubSpec/system/testProbe-3171#887757638]: GetChildren
18114
--- Stream actors debug dump ---
18115
Stream is completed. No debug information is available
18116
[info] - must properly signal error to consumers *** FAILED *** (10 seconds, 157 milliseconds)
18117
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for OnNext(15)
18118
[info]   at scala.Predef$.assert(Predef.scala:223)
18119
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
18120
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
18121
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
18122
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
18123
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.$anonfun$expectNextN$1(StreamTestKit.scala:451)
18124
[info]   at scala.collection.Iterator.foreach(Iterator.scala:943)
18125
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:943)
18126
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
18127
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
18128
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
18129
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
18130
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:451)
18131
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:420)
18132
[info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$104(HubSpec.scala:702)
18133
[info]   at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
18134
[info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$103(HubSpec.scala:681)
```

**Comment by octonato** [comment]
Once again: https://github.com/akka/akka/runs/4903561211?check_suite_focus=true#step:5:17041

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5267581313?check_suite_focus=true#step:5:17789

**Comment by johanandren** [comment]
I thought at first it might be about that thread.sleep to wait for subscriptions but curiously it is always failing on the last of 8 expected events for one of the subscribers, after successfully getting the first 7, so there must be something else at play here.

**Comment by johanandren** [comment]
Looks like a legit bug, I think demand can be lost when buffer is full.

**Comment by johanandren** [comment]
I think this is the scenario: Consumer(1) consumed a bunch of elements, after the last demand from it the buffer got full, with only elements for the _other_ partition, but when that partition runs it only asks for 4 elements, and is happy to just consume those 4 and not talk to the hub more, so there is nothing triggering pulling more elements that can be emitted to consumer(1).

Not sure what to do about it yet though.
