### ISSUE TITLE
Issue when using EventSourcedBehaviorTestKit for testing

### ISSUE THREAD

**Issue by albertoadami** [akka/akka#31031]
Hello, I'm following [the guide](https://doc.akka.io/docs/akka/current/typed/persistence-testing.html#) and the sample to use the EventSourcedBehaviorTestKit to test a custom`EventSourcedBehavior` akka-typed actor.

My spec looks like the following:
```
class UserBehaviorSpec
    extends ScalaTestWithActorTestKit(s"""
      akka.persistence.journal.plugin = "akka.persistence.journal.inmem"
      akka.persistence.snapshot-store.plugin = "akka.persistence.snapshot-store.local"
      akka.persistence.snapshot-store.local.dir = "target/snapshot-${UUID.randomUUID().toString}"
    """)
    with AnyWordSpecLike
    with BeforeAndAfterEach {

  private def eventSourcedTestKit =
    EventSourcedBehaviorTestKit[UserCommand, UserEvent, State[UserState]](
      system,
      UserBehavior(PersistenceId("User", "test"))
    )

  override protected def beforeEach(): Unit = {
    super.beforeEach()
    eventSourcedTestKit.clear()
  }

  "UserBehavior" must {

    val createUserCommand = CreateUserCommand(
      username = "test",
      firstName = "test",
      lastName = "test",
      email = "test@test.it",
      password = "password",
      dateOfBirth = LocalDate.of(1990, 1, 1),
      gender = "MALE"
    )

    "create a new user in disabled state" in {
      val result = eventSourcedTestKit.runCommand(createUserCommand)
      result.event shouldBe a[UserEvent]
      result.stateOfType[State[UserState]].value.isDefined shouldBe true

    }
  }

}
```
When executing the test I'm getting the following error:
```
[info] it.adami.blog.actor.akka.UserBehaviorSpec *** ABORTED ***
[info]   java.lang.IllegalArgumentException: requirement failed: The test persistence plugin is not configured.
[info]   at scala.Predef$.require(Predef.scala:277)
[info]   at akka.persistence.testkit.scaladsl.PersistenceTestKit.<init>(PersistenceTestKit.scala:441)
[info]   at akka.persistence.testkit.scaladsl.PersistenceTestKit$.apply(PersistenceTestKit.scala:517)
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.<init>(EventSourcedBehaviorTestKitImpl.scala:95)
[info]   at akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKit$.apply(EventSourcedBehaviorTestKit.scala:112)
[info]   at akka.persistence.testkit.scaladsl.EventSourcedBehaviorTestKit$.apply(EventSourcedBehaviorTestKit.scala:100)
[info]   at it.adami.blog.actor.akka.UserBehaviorSpec.eventSourcedTestKit(UserBehaviorSpec.scala:28)
[info]   at it.adami.blog.actor.akka.UserBehaviorSpec.beforeEach(UserBehaviorSpec.scala:33)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:233)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
```

I'm using scala 2.12.6 and 2.6.18 akka libraries. Any idea?

**Comment by johanandren** [comment]
Could be something with that custom config, did you try `extends ScalaTestWithActorTestKit(EventSourcedBehaviorTestKit.config)` like the docs recommend?

**Comment by albertoadami** [comment]
@johanandren I tried also with `ScalaTestWithActorTestKit(EventSourcedBehaviorTestKit.config)`, but in this way I'm getting:
```
[info]   java.lang.IllegalArgumentException: Command [CreateUserCommand(test,test,test,test@test.it,password,1990-01-01,MALE)] isn't serializable.
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.verifySerializationAndThrow(EventSourcedBehaviorTestKitImpl.scala:232)
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.preCommandCheck(EventSourcedBehaviorTestKitImpl.scala:184)
[info]   at akka.persistence.testkit.internal.EventSourcedBehaviorTestKitImpl.runCommand(EventSourcedBehaviorTestKitImpl.scala:119)
[info]   at it.adami.blog.actor.akka.UserBehaviorSpec.$anonfun$new$2(UserBehaviorSpec.scala:45)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
[info]   ...
[info]   Cause: akka.serialization.DisabledJavaSerializer$JavaSerializationException: Attempted to serialize message using Java serialization while `akka.actor.allow-java-serialization` was disabled. Check WARNING logs for more details.
[info]   ...
[info] Create
```

My command trait is extending `CborSerializable`.

```
/**
 * Marker trait for serialization with Jackson CBOR
 */
trait CborSerializable
sealed trait UserCommand extends CborSerializable

object UserCommand {
  case class CreateUserCommand(
      username: String,
      firstName: String,
      lastName: String,
      email: String,
      password: String,
      dateOfBirth: LocalDate,
      gender: String
  ) extends UserCommand
}


```

**Comment by johanandren** [comment]
That is probably because the testkit uses its own separate `application-test.conf` file and the serializer mappings are in your `application.conf`.

Try falling back to default application config as shown here: https://doc.akka.io/docs/akka/current/typed/persistence-testing.html#persistence-testkit

**Comment by johanandren** [comment]
Since the EventSourcedTestKit checks serialization by default I think that the snippets showing how to enable it will never work, we should fix the docs to either disable serialization checking or show how to fallback to `application.conf` to pick up serializer.

**Comment by albertoadami** [comment]
@johanandren using `ScalaTestWithActorTestKit(EventSourcedBehaviorTestKit.config.withFallback(ConfigFactory.load()))` my tests are working now, thank you.

I only needed to add also the `"org.fusesource.leveldbjni" % "leveldbjni-all" % "1.8"` dependency to my project BTW, otherwise was not working and throwing the following exception:
```
[info] it.adami.blog.actor.akka.UserBehaviorSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: org/iq80/leveldb/DBFactory
[info]   at java.lang.Class.getDeclaredConstructors0(Native Method)
[info]   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[info]   at java.lang.Class.getDeclaredConstructors(Class.java:2020)
[info]   at akka.util.Reflect$.findConstructor(Reflect.scala:97)
[info]   at akka.persistence.Persistence.akka$persistence$Persistence$$createPlugin(Persistence.scala:404)
[info]   at akka.persistence.Persistence$PluginHolderExtensionId.$anonfun$createExtension$2(Persistence.scala:439)
[info]   at akka.persistence.Persistence$PluginHolder.actor$lzycompute(Persistence.scala:160)
[info]   at akka.persistence.Persistence$PluginHolder.actor(Persistence.scala:160)
[info]   at akka.persistence.Persistence.journalFor(Persistence.scala:360)
[info]   at akka.persistence.Persistence$$anon$1.accept(Persistence.scala:262)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.iq80.leveldb.DBFactory
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[info]   at java.lang.Class.getDeclaredConstructors0(Native Method)
[info]   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[info]   at java.lang.Class.getDeclaredConstructors(Class.java:2020)
[info]   at akka.util.Reflect$.findConstructor(Reflect.scala:97)
[info]   at akka.persistence.Persistence.akka$persistence$Persistence$$createPlugin(Persistence.scala:404)
[info]   at akka.persistence.Persistence$PluginHolderExtensionId.$anonfun$createExtension$2(Persistence.scala:439)
[info]   ...
```

Is it expected? I don't see that from the docs

**Comment by johanandren** [comment]
It is not expected, the persistence testkit should work on an in-memory db so if you see something tries to start the level-db journal some config is incorrectly pulling that in. Calling `akka.actor.ActorSystem#logConfiguration` could be useful to figure out why it is loaded.

**Comment by albertoadami** [comment]
@johanandren fixed issue, I don't know if has some sense to update the docs about using the TestKit.

**Comment by johanandren** [comment]
I think we should make the example work out of the box, so let's leave this issue open for tracking that.
