### ISSUE TITLE
Failed: PubSubSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31073]
https://github.com/akka/akka/runs/4875703083?check_suite_focus=true#step:5:19772

```
[info] PubSub.sink
[info] - should publish messages *** FAILED *** (6 seconds, 14 milliseconds)
[info]   java.lang.AssertionError: timeout (6 seconds) during expectMessage while waiting for published
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:171)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.stream.typed.scaladsl.PubSubSpec.$anonfun$new$5(PubSubSpec.scala:59)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5225034502?check_suite_focus=true#step:5:19746
