### ISSUE TITLE
Jackson version too old which lead to version conflict.

### ISSUE THREAD

**Issue by counter2015** [akka/akka#31097]
Now used jackson version is `2.11.4`
https://github.com/akka/akka/blob/9b97614b959a37dbffb3b4579b258d3e0d2e7055/project/Dependencies.scala#L28

I'm using akka projection with many akka commponts, it will lead error to 

```
╥
╠══╦══╗
║  ║  ║
║  ║  ╠─A checked error was not handled.
║  ║  ║ com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0
║  ║  ║ 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
║  ║  ║ 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
║  ║  ║ 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
║  ║  ║ 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
║  ║  ║ 	at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:242)
║  ║  ║ 	at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:241)
║  ║  ║ 	at scala.collection.immutable.List.foreach(List.scala:333)
```

My Dependencies
```scala

object Versions {
    val akka = "2.6.18"
    val akkaManagement = "1.1.3"
    val akkaProjection = "1.2.3"
  }

val akka = Seq(
    "com.typesafe.akka" %% "akka-persistence"           % Versions.akka,
    "com.typesafe.akka" %% "akka-persistence-cassandra" % "1.0.5",
    "com.typesafe.akka" %% "akka-persistence-query"     % Versions.akka,
    "com.typesafe.akka" %% "akka-persistence-typed"     % Versions.akka,
    "com.typesafe.akka" %% "akka-persistence-testkit"   % Versions.akka % Test,
    "com.typesafe.akka" %% "akka-serialization-jackson" % Versions.akka
  )

  val akkaActor = Seq(
    "com.typesafe.akka" %% "akka-actor-typed"            % Versions.akka,
    "com.typesafe.akka" %% "akka-cluster-sharding-typed" % Versions.akka,
    "com.typesafe.akka" %% "akka-cluster-tools"          % Versions.akka,
    "com.typesafe.akka" %% "akka-discovery"              % Versions.akka
  )

  val akkaStream = Seq(
    "com.typesafe.akka" %% "akka-stream"       % Versions.akka,
    "com.typesafe.akka" %% "akka-stream-kafka" % "3.0.0"
  )

  val akkaManagement = Seq(
    "com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % Versions.akkaManagement,
    "com.lightbend.akka.discovery" %% "akka-discovery-kubernetes-api"      % Versions.akkaManagement
  )

  val akkaProjection = Seq(
    "com.lightbend.akka" %% "akka-projection-cassandra"     % Versions.akkaProjection,
    "com.lightbend.akka" %% "akka-projection-core"          % Versions.akkaProjection,
    "com.lightbend.akka" %% "akka-projection-durable-state" % Versions.akkaProjection,
    "com.lightbend.akka" %% "akka-projection-eventsourced"  % Versions.akkaProjection,
    "com.lightbend.akka" %% "akka-projection-kafka"         % Versions.akkaProjection,
    "com.lightbend.akka" %% "akka-projection-testkit"       % Versions.akkaProjection % Test
  )
```

And latest version is `2.13.1`
https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

Is scala-steward still works or there is other reason for stay jackson verison to 2.11.4?
 
 How about update jackson dependcy to latest version ?

**Comment by raboof** [comment]
> is other reason for stay jackson verison to 2.11.4

Yes: jackson changed between 2.11.4 and 2.13.1. While we don't rely on any of the parts that changed, so Akka works fine with 2.13.1, there could be projects using Akka that do rely on the 2.11 behavior. For that reason we're reluctant to update jackson in Akka, since that might force projects to also update, which might not be easy.

It's fine to update jackson in your project though. To fix the problem you're running into, make sure you also upgrade the `"com.fasterxml.jackson.module" % "jackson-module-scala"` dependency.

Let's keep this issue open until we have added a page to the docs describing this.
