### ISSUE TITLE
ShardsUpdated causes problem with HashCodeNoEnvelopeMessageExtractor after the update to Akka Version 2.6.17 to 2.6.18

### ISSUE THREAD

**Issue by mehmetsalgar** [akka/akka#31091]
Hi,

I made a version upgrade in my Akka project but the code that is working perfectly for 2.6.17 causing problem with 2.6.18.

I am getting the following exception from sharding system after remember entities triggered.

`[2022-01-26 15:57:36,366] [ERROR] [a.a.OneForOneStrategy] [example-akka.actor.default-dispatcher-23] [akka://example/system/sharding/testactor/21] - class akka.cluster.sharding.ShardRegion$ShardsUpdated cannot be cast to class org.example.TestActor$TestEvent  (akka.cluster.sharding.ShardRegion$ShardsUpdated and org.example.TestActor$TestEvent  are in unnamed module of loader 'app')
java.lang.ClassCastException: class akka.cluster.sharding.ShardRegion$ShardsUpdated cannot be cast to class org.example.TestActor$TestEvent (akka.cluster.sharding.ShardRegion$ShardsUpdated and org.example.TestActor$TestEvent are in unnamed module of loader 'app')
	at org.example.TestActorGuardian$$anon$1.entityId(TestActorGuardian.scala:197)
	at akka.cluster.sharding.typed.internal.ExtractorAdapter.entityId(ClusterShardingImpl.scala:58)
	at akka.cluster.sharding.typed.internal.ClusterShardingImpl$$anonfun$1.isDefinedAt(ClusterShardingImpl.scala:168)
	at akka.cluster.sharding.Shard$$anonfun$waitingForRememberEntitiesStore$1.applyOrElse(Shard.scala:703)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.cluster.sharding.Shard.akka$actor$Timers$$super$aroundReceive(Shard.scala:410)
	at akka.actor.Timers.aroundReceive(Timers.scala:56)
	at akka.actor.Timers.aroundReceive$(Timers.scala:41)
	at akka.cluster.sharding.Shard.aroundReceive(Shard.scala:410)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

I have a very standard MessageExtractor

`new HashCodeNoEnvelopeMessageExtractor[TestEvent](
          numberOfShards = 30
        ) {
          override def entityId(message: TestEvent): String = message.key
        }`

which works fine with 2.6.17.

I have a feeling this class is causing the problem

com.typesafe.akka/akka-cluster-sharding-typed_2.13/2.6.18/akka-cluster-sharding-typed_2.13-2.6.18.jar!/akka/cluster/sharding/typed/internal/ExtractorAdapter.class

`  override def unwrapMessage(message: Any): M = {
    message match {
      case ShardingEnvelope(_, msg: M @unchecked) =>
        //also covers ClassicStartEntity in ShardingEnvelope
        msg
      case msg: ClassicStartEntity =>
        // not really of type M, but erased and StartEntity is only handled internally, not delivered to the entity
        msg.asInstanceOf[M]
      case msg =>
        delegate.unwrapMessage(msg.asInstanceOf[E])
    }
  }
`

I think this needs another case statement for ShardsUpdated

`case ShardsUpdated =>
     something

I think think something changed with the behaviour of ShardsUpdated between 2.6.17 and 2.6.18 but I can't tell for sure what...
`

**Comment by johanandren** [comment]
`ShardsUpdated` is a message between the region and the shard and is not intended to ever end up in the shard/id-extractor to start with. 

Looks like it could perhaps be a bug around stashing/unstashing when waiting for remember-entities data to load.
