### ISSUE TITLE
Failed: Cluster Metrics with Sigar -> many tests with TCP binding issues

### ISSUE THREAD

**Issue by octonato** [akka/akka#31103]
I'm reporting this just for the record. This is probably an issue on the build machine. Let's see if it happens again in the future. 

This build has a few `*** ABORTED ***` tests with message `Failed to bind TCP to [10.1.0.97:25520] due to: Bind failed because of java.net.BindException: [/10.1.0.97:25520] Cannot assign requested address` 

https://github.com/akka/akka/runs/4909769872?check_suite_focus=true#step:5:248

```scala
[info] akka.cluster.metrics.MetricsCollectorSpec *** ABORTED *** (9 milliseconds)
[info]   akka.remote.RemoteTransportException: Failed to bind TCP to [10.1.0.97:25520] due to: Bind failed because of java.net.BindException: [/10.1.0.97:25520] Cannot assign requested address
[info]   at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:273)
[info]   at akka.remote.artery.tcp.ArteryTcpTransport$$anonfun$4.applyOrElse(ArteryTcpTransport.scala:267)
[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
[info]   at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
[info]   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
[info]   at scala.concurrent.Promise.complete(Promise.scala:57)

```

**Comment by octonato** [comment]
Found another one https://github.com/akka/akka/runs/4915607697?check_suite_focus=true#step:5:246
