### ISSUE TITLE
Failed: PubSubSpec - PubSub.source

### ISSUE THREAD

**Issue by octonato** [akka/akka#31102]
https://github.com/akka/akka/runs/4903561285?check_suite_focus=true#step:5:13875

(Maybe related to #31073?)

```scala
[info] PubSub.source
[info] - should emit messages from the topic *** FAILED *** (6 seconds, 26 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for OnNext(published)
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:399)
[info]   at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:840)
[info]   at akka.stream.typed.scaladsl.PubSubSpec.$anonfun$new$2(PubSubSpec.scala:37)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)```

**Comment by octonato** [comment]
Once more https://github.com/akka/akka/runs/4909770206?check_suite_focus=true#step:5:13544

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5170432398?check_suite_focus=true#step:5:13952

**Comment by johanandren** [comment]
Looks like a bug in `Topic`: It drops a published message if `topicInstances` is empty and doesn't look at `localSubscribers` at all.

```
2022-02-13 00:47:10,870 DEBUG akka.actor.typed.pubsub.Topic$  - Starting up pub-sub topic [my-topic-1] for messages of type [java.lang.String] MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/user/$a, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,878 DEBUG akka.actor.typed.pubsub.Topic$  - Local subscriber [Actor[akka://PubSubSpec/system/Materializers/StreamSupervisor-9/$$a-actorRefSource#-1225593817]] added, went from no subscribers to one, subscribing to receptionist MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/user/$a, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,881 DEBUG akka.actor.typed.internal.receptionist.LocalReceptionist  - Actor was registered: ServiceKey[akka.actor.typed.internal.pubsub.TopicImpl$Command](my-topic-1) Actor[akka://PubSubSpec/user/$a#1354613488] MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/system/localReceptionist, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,883 DEBUG akka.actor.typed.pubsub.Topic$  - Topic list updated [Set()] MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/user/$a, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,886 TRACE akka.actor.typed.pubsub.Topic$  - Publishing message of type [class akka.actor.typed.internal.pubsub.TopicImpl$Publish] but no subscribers, dropping MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/user/$a, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,889 DEBUG akka.actor.typed.pubsub.Topic$  - Topic list updated [Set(Actor[akka://PubSubSpec/user/$a#1354613488])] MDC: {akkaAddress=akka://PubSubSpec, akkaSource=akka://PubSubSpec/user/$a, sourceActorSystem=PubSubSpec}
2022-02-13 00:47:10,895 INFO  akka.actor.DeadLetterActorRef akkaDeadLetter - Message [java.lang.String] wrapped in [akka.actor.Dropped] to Actor[akka://PubSubSpec/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://PubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. MDC: {akkaAddress=akka://PubSubSpec, akkaUid=-6539465398320243795, sourceThread=PubSubSpec-akka.actor.default-dispatcher-7, akkaSource=akka://PubSubSpec/deadLetters, sourceActorSystem=PubSubSpec, akkaMessageClass=java.lang.String, akkaTimestamp=00:47:10.893UTC}
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5209079216?check_suite_focus=true#step:5:13660

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5245638537?check_suite_focus=true#step:5:20156
