### ISSUE TITLE
failed: ForkJoinPoolStarvationSpec on JDK 17

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31117]
https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3680

https://github.com/akka/akka/runs/5118048171?check_suite_focus=true#step:5:3526

https://github.com/akka/akka/runs/5086535435?check_suite_focus=true#step:5:3591

https://github.com/akka/akka/runs/5086535594?check_suite_focus=true#step:5:3594

and probably many more

```
[info] - must not starve tasks arriving from external dispatchers under high internal traffic *** FAILED *** (6 seconds, 13 milliseconds)
[3681](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3681)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for All fine
[3682](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3682)
[info]   at scala.Predef$.assert(Predef.scala:223)
[3683](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3683)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[3684](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3684)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[3685](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3685)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[3686](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3686)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[3687](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3687)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$6(ForkJoinPoolStarvationSpec.scala:64)
[3688](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3688)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$6$adapted(ForkJoinPoolStarvationSpec.scala:61)
[3689](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3689)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:158)
[3690](https://github.com/akka/akka/runs/5118047872?check_suite_focus=true#step:5:3690)
[info]   at akka.dispatch.ForkJoinPoolStarvationSpec.$anonfun$new$2(ForkJoinPoolStarvationSpec.scala:61)
```

**Comment by jrudolph** [comment]
https://github.com/akka/akka/runs/5133864147?check_suite_focus=true

**Comment by jrudolph** [comment]
I tried finding out what changed with ForkJoinPool in JDK 17. The answer is "Yes" and it could mean anything. E.g. https://github.com/openjdk/jdk17u-dev/commit/5cfa8c94d6765b93f910fc01cd1ac2a56b16d78a?w=1#diff-e398beb49cd8d3e6c2f3a8ca8eee97172c57d7f88f3ccd8a3c704632cab32f5f

**Comment by jrudolph** [comment]
See #17413 for more info why this was added in the first place.

**Comment by jrudolph** [comment]
It seems ForkJoinPool does not make any public guarantees on scheduling, though, the internal documentation clearly states that internal tasks are preferred over external submissions.

I guess, you could say that this is a fairness issue that only matters in high load or overload scenarios anyway, so in that case giving advantage to local tasks is the best thing to do because this way you can do strictly less work than trying to steal work from the external queue in those cases. In consequence, in absence of any blocking (or busy-polling) on the pool (which is a bad idea anyway), this should not be a problem as long as the application can make *some* progress.

On the other hand, @viktorklang and @drewhk considered this to be a problem, so maybe I'm missing a critical scenario? In the meantime we added the internal dispatcher which should at least prevent that more critical internal workloads are completely starved. (Also OSs implement preemption for a reason you would think...)

**Comment by patriknw** [comment]
I agree with your reasoning and I think we can remove the test.

**Comment by drewhk** [comment]
My two cents: I generally freak out of any fairness issue because they are the silent killer. In fact, the problem is exactly that they come out usually in high-load scenarios and then instead of graceful degradation the system suddenly enters unpredictable failure modes that are very hard to diagnose and debug. If you have read the Roblox post-mortem, one of the main causes was a fairness issue. 

In this case, if I recall correctly the original issue was cross-dispatcher submissions.

**Comment by drewhk** [comment]
This was the original ticket: https://github.com/akka/akka/issues/17341

**Comment by jrudolph** [comment]
Thanks for chiming in, Endre.

I agree that graceful degradation is a worthwhile goal in many cases. On the other hand, it's not a clear black-and-white scenario. After all, Akka already is a cooperative multitasking system. It's tempting to foresee all possible failure scenarios and provide solutions but often enough critical failure results in a chaotic spiral out of control that couldn't been foreseen. That kind of amplification of failures is hard to control on this micro-level. When you run different workloads together on a shared scheduler (or any other shared resource like a cpu or memory, or a machine, or a cluster, or a dc, or against shared infrastructure like consul) will always have the risk of aggravating failures... Only bulk-heading and redundancy (and leaving headroom in the first place) will make a system resilient under stress.

More concretely, we know that thrashing (e.g. when swap is enabled or with extra context switching due to preemption) can be a serious problem leading to heavy throughput reductions. Even in our case it could be the case, that the system makes better throughput e.g. when a smaller set of actors or streams is serviced (especially under the scenario that roblox mentioned of NUMA architectures) even if that starves out other parts of the workload. In the best case, blocking one part of the workload will also reduce traffic on the other part of the workload. In the worst case, the work done is worthless and the worked starved out of resources would have been the important one. In that case, running both workloads together would have been a risk from the start (though not necessarily obviously so).

Anyway, I'm also asking on the concurrency-interest mailing list if there's any advice for a fairer mode of operation.

**Comment by drewhk** [comment]
> It's tempting to foresee all possible failure scenarios and provide solutions but often enough critical failure results in a chaotic spiral out of control that couldn't been foreseen.

I don't know this particular case (JDK17), you might have a better understanding how it behaves now. In the original ticket though there were several reproducible scenarios, one is involving self-messages, the other one was the cross-dispatcher scenario. I recommend looking into them and see if they still apply. Forseeing is hard, but there was a failure report here, originally.

> Only bulk-heading and redundancy (and leaving headroom in the first place) will make a system resilient under stress.

It only works if the failure scenarios are uncorrelated, otherwise the whole system goes down together, bulkheading or not. In this case, actually using multiple dispatchers (one way of bulkheading) will exercise this exact fairness problem.

So, yes, cooperative multi-threading can have such issues, but in this case the library/framework itself has one such behavior that is truly hard to reason about for the user. You cannot just say "increase granularity of concurrency" (the Roblox Consul/Go issue was caused by partly this), they have no way of debugging this and mitigating. In the original ticket there were cases where messages had no chance of getting through. You can at least look into the naive yielding strategy discussed there, that at least allows external submissions to trickle through (not sure it applies to JDK17 though).

**Comment by jrudolph** [comment]
> actually using multiple dispatchers (one way of bulkheading) will exercise this exact fairness problem

Not sure when that was the case. The actual test and also the case described in #17341 only uses a single dispatcher for all actors in question. There's a set of actors that spin-loops using self messages and another actor that lives on that same dispatcher but which gets a message from a foreign thread. This external submission never gets to be executed as long as the spin-loop is going on. There's only a single dispatcher involved (the shared resource) which is blocked in that case.

> where messages had no chance of getting through

Of course, this example is extreme but when your competition is N tasks spinning, also many systems that are more fair don't really offer useful fairness. You will at least need a priority system and grouping of tasks into logical group to make a real impact.

> you can at least look into the naive yielding strategy discussed there

I think what we could try to do is to try to use `externalPush` whenever an actor mailbox is *re*scheduled after handling `throughput` messages.

**Comment by drewhk** [comment]
> There's a set of actors that spin-loops using self messages and another actor that lives on that same dispatcher but which gets a message from a foreign thread. This external submission never gets to be executed as long as the spin-loop is going on. There's only a single dispatcher involved (the shared resource) which is blocked in that case.

Yeah, but that foreign thread could be another dispatcher, it just so that the test case does not construct one. Also, there is one ping-pong case with no self-messages. Anyway, I rest my case.

**Comment by jrudolph** [comment]
Here's an attempt at using external submission for reschedulings of a mailbox: https://github.com/akka/akka/pull/31156#pullrequestreview-888883748

Probably wouldn't help the ping/pong case in which case we would have to use external submission for all scheduling of mailboxes.

**Comment by viktorklang** [comment]
@jrudolph Changing the scheduling requires quite a bit of benching to make sure it doesn't regress performance in a noticeable way (since that logic is not controlled by end user)—sorry for stating the obvious :P. Since potential issues are completely depending of the *implementation* of FJP used in the application, I think it will be not feasible to fix in the general sense.

My vision was always to write a bespoke (minimal) work-stealing scalable thread pool to use as a default Dispatcher implementation. FJP is a bit overkill for what Akka uses (scalable submissions, workstealing, and managed blocking).
Alas I never could prioritize to write one. :S

Great to hear from you Endre/@drewhk, I hope you and the family is doing well!

**Comment by drewhk** [comment]
> Great to hear from you Endre/@drewhk, I hope you and the family is doing well!

While I don't want to spam the ticket with smalltalk, yeah, we are all fine, and hopefully we will visit Uppsala this summer - to show my older son where he was born and also because it is nice :)

**Comment by viktorklang** [comment]
Great to hear, Endre!

Let me know if you pass by southern Sweden, and give my best regards to
your family 😊
-- 
Cheers,
√

**Comment by jrudolph** [comment]
> @jrudolph Changing the scheduling requires quite a bit of benching to make sure it doesn't regress performance in a noticeable way (since that logic is not controlled by end user)—sorry for stating the obvious :P. Since potential issues are completely depending of the _implementation_ of FJP used in the application, I think it will be not feasible to fix in the general sense.

Thanks for chiming in, @viktorklang. I agree, if people want to experiment with the PR I added that's now at least possible.
