### ISSUE TITLE
failed: SendQueueSpec - deliver first message

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31165]
https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10350

```
[info] - must deliver first message *** FAILED *** (11 seconds, 372 milliseconds)
[10351](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10351)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for OnNext(b)
[10352](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10352)
[info]   at scala.Predef$.assert(Predef.scala:223)
[10353](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10353)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[10354](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10354)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[10355](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10355)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[10356](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10356)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[10357](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10357)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:399)
[10358](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10358)
[info]   at akka.remote.artery.SendQueueSpec.$anonfun$new$24(SendQueueSpec.scala:174)
[10359](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10359)
[info]   at akka.remote.artery.SendQueueSpec.$anonfun$new$24$adapted(SendQueueSpec.scala:165)
[10360](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10360)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:158)
[10361](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10361)
[info]   at akka.remote.artery.SendQueueSpec.test$1(SendQueueSpec.scala:165)
[10362](https://github.com/akka/akka/runs/5276807176?check_suite_focus=true#step:5:10362)
[info]   at akka.remote.artery.SendQueueSpec.$anonfun$new$23(SendQueueSpec.scala:210)
```

**Comment by johanandren** [comment]
Ran it some good 100 000 runs locally without any fail.

Trying to deduce what could go wrong from reading it, I have one suspicion about `logic.wakeup` from `queue.offer` being dropped/ignored if it happens before `out` is available/ready after the first pull-push has happened. But if that is the case, I'm not sure what we can do about it (without a timer or something, much like the not so great timer based fix for PartitionHub in #31158 which has a similar design with a shared queue)

**Comment by johanandren** [comment]
The failing scenario is:
```scala
downstream.request(10)
sendQueue.inject(queue)
sendQueue.offer("a")
downstream.expect("a") // succeeds
sendQueue.offer("b")
downstream.expect("b") // times out
```

I have been trying to trace a scenario that could end up with this failure but I can't figure out a sequence of operations in the two threads that would drop demand/miss picking the element up. 

The case where the stage executed `consumerQueue.poll()`, but haven't set `needWakeUp` yet when the producing thread calls `.offer()` is covered by a retry which means it should always either see the enqueued element or trigger async callback wakeup from the producing thread.

**Comment by pvlugter** [comment]
I read through this one as well, and also don't see a way to create that failure. Looks like different orderings are all covered with the retry to handle `offer`/`needWakeup`, and when out is not available it will be followed by a pull.

Is this just a one-off failure with some long slowdowns?

**Comment by patriknw** [comment]
Thanks for additional code review. We also looked at the approach when the new Streams queue was added, since that is using a very similar design. Let's close until we see more of it.

**Comment by pvlugter** [comment]
Failed again in https://github.com/akka/akka/runs/6853426847?check_suite_focus=true#step:5:8135

**Comment by octonato** [comment]
is back 
https://github.com/akka/akka/actions/runs/3809732990/jobs/6481295392#step:5:9794
