### ISSUE TITLE
failed: CircuitBreakerMTSpec - allow a single call through in half-open state

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31166]
This was after the changes to the test that were merged yesterday.

https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3551

```
[info] - must allow a single call through in half-open state *** FAILED *** (6 seconds, 19 milliseconds)
[3552](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3552)
[info]   false was not equal to true (CircuitBreakerMTSpec.scala:100)
[3553](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3553)
[info]   org.scalatest.exceptions.TestFailedException:
[3554](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3554)
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[3555](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3555)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
[3556](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3556)
[info]   at akka.pattern.CircuitBreakerMTSpec.$anonfun$new$9(CircuitBreakerMTSpec.scala:100)
[3557](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3557)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[3558](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3558)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[3559](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3559)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[3560](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3560)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[3561](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3561)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[3562](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3562)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[3563](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3563)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[3564](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3564)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[3565](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3565)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
[3566](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3566)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[3567](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3567)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[3568](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3568)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[3569](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3569)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[3570](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3570)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[3571](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3571)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[3572](https://github.com/akka/akka/runs/5281392381?check_suite_focus=true#step:5:3572)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
```

**Comment by octonato** [comment]
I reverted it. I didn't look further to understand how it's failing. 
It's failing after when calling `breaker.isClosed shouldBe true`, but the assertion before it passed and therefore I don't see how that could be possible. 

At that moment the CB must be closed. Unless it didn't open after the first successful call.

**Comment by octonato** [comment]
Anyway, I don't want to spent time on this. Fine to revert if proves to work.
