### ISSUE TITLE
Failed: JoinConfigCompatCheckerRollingUpdateSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31196]
In the Aeron UDP tests. 

Different from the previous fails for this test.

```
[info] - must be allowed to re-join a cluster if it has a new, additional configuration the others do not have and configured to NOT enforce it *** FAILED *** (2 minutes, 27 seconds)
[3398](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3398)
[info]   java.lang.AssertionError: assertion failed: timeout 2 minutes expired:
[3399](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3399)
[info]   at scala.Predef$.assert(Predef.scala:279)
[3400](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3400)
[info]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
[3401](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3401)
[info]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
[3402](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3402)
[info]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
[3403](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3403)
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
[3404](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3404)
[info]   at akka.cluster.RollingUpgradeClusterSpec.upgradeCluster(ClusterTestKit.scala:225)
[3405](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3405)
[info]   at akka.cluster.JoinConfigCompatCheckerRollingUpdateSpec.$anonfun$new$4(JoinConfigCompatCheckerRollingUpdateSpec.scala:58)
[3406](https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3406)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

https://github.com/akka/akka/runs/5385324000?check_suite_focus=true#step:9:3397

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/5416700122?check_suite_focus=true#step:9:3130

**Comment by patriknw** [comment]
Another one, now in classic remoting tests: https://github.com/akka/akka/runs/5476046877?check_suite_focus=true#step:5:2324

```
[info] - must NOT be allowed to re-join a cluster if it has a new, additional configuration the others do not have and not the old *** FAILED *** (51 seconds, 412 milliseconds)
2325
[info]   java.lang.AssertionError: awaiting node [akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:35965] to be removed, still member in [akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:44249]: CurrentClusterState(TreeSet(Member(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:35965, Leaving), Member(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:44249, Up)), Set(Member(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:35965, Leaving)), Set(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:44249), Some(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:44249), Map(dc-default -> Some(akka.tcp://JoinConfigCompatCheckerRollingUpdateSpec@10.1.0.191:44249)))
2326
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.$anonfun$quitAndRestart$4(ClusterTestKit.scala:128)
2327
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.$anonfun$quitAndRestart$4$adapted(ClusterTestKit.scala:122)
2328
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
2329
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.$anonfun$quitAndRestart$3(ClusterTestKit.scala:122)
2330
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2331
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
2332
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
2333
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
2334
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
2335
[info]   at akka.cluster.ClusterTestKit$ClusterTestUtil.quitAndRestart(ClusterTestKit.scala:121)
2336
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$7(ClusterTestKit.scala:220)
2337
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
2338
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:418)
2339
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)
2340
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
2341
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:433)
2342
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)
2343
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
2344
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$6(ClusterTestKit.scala:219)
2345
[info]   at akka.cluster.RollingUpgradeClusterSpec.$anonfun$upgradeCluster$6$adapted(ClusterTestKit.scala:218)
2346
[info]   at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
2347
[info]   at akka.cluster.RollingUpgradeClusterSpec.upgradeCluster(ClusterTestKit.scala:218)
2348
[info]   at akka.cluster.JoinConfigCompatCheckerRollingUpdateSpec.$anonfun$new$2(JoinConfigCompatCheckerRollingUpdateSpec.scala:56)
```
