### ISSUE TITLE
failed: CircuitBreakerSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31229]
https://github.com/akka/akka/runs/5488806191?check_suite_focus=true#step:5:2338

```
[info] - must reset failure count after success *** FAILED *** (8 seconds, 5 milliseconds)
2339
[info]   java.lang.AssertionError: assertion failed: timeout 8 seconds expired:
2340
[info]   at scala.Predef$.assert(Predef.scala:223)
2341
[info]   at akka.testkit.TestKitBase.poll$1(TestKit.scala:300)
2342
[info]   at akka.testkit.TestKitBase.awaitCond(TestKit.scala:306)
2343
[info]   at akka.testkit.TestKitBase.awaitCond$(TestKit.scala:289)
2344
[info]   at akka.testkit.TestKit.awaitCond(TestKit.scala:973)
2345
[info]   at akka.pattern.CircuitBreakerSpec.$anonfun$new$233(CircuitBreakerSpec.scala:645)
```

I haven't looked into this specific failure but we might want to mark CircuitBreakerSpec as timing sensitive test.

**Comment by patriknw** [comment]
in timing sensitive tests https://github.com/akka/akka/runs/5981852992?check_suite_focus=true#step:5:832

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/5957936130?check_suite_focus=true#step:5:907

**Comment by raboof** [comment]
possibly the same in https://github.com/akka/akka/runs/6890950812?check_suite_focus=true ?

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/8218477393?check_suite_focus=true

Not sure if it is the same, in timing sensitive tests:
```
[09-07 00:14:31.338] [info] - must reset failure count after success *** FAILED *** (7 seconds, 945 milliseconds)
[926](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:927)
[09-07 00:14:31.338] [info]   1 was not equal to 4 (CircuitBreakerSpec.scala:674)
[927](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:928)
[09-07 00:14:31.339] [info]   org.scalatest.exceptions.TestFailedException:
[928](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:929)
[09-07 00:14:31.339] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[929](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:930)
[09-07 00:14:31.340] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
[930](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:931)
[09-07 00:14:31.340] [info]   at akka.pattern.CircuitBreakerSpec.$anonfun$new$239(CircuitBreakerSpec.scala:674)
[931](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:932)
[09-07 00:14:31.341] [info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[932](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:933)
[09-07 00:14:31.341] [info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[933](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:934)
[09-07 00:14:31.341] [info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[934](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:935)
[09-07 00:14:31.342] [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[935](https://github.com/akka/akka/runs/8218477393?check_suite_focus=true#step:5:936)
[09-07 00:14:31.342] [info]   at akka.pattern.CircuitBreakerSpec.$anonfun$new$233(CircuitBreakerSpec.scala:674)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3033853818/jobs/4882353574#step:5:888

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6242211073/job/16945756973#step:5:801

```
[09-20 00:12:05.989] [info] - must reset failure count after success *** FAILED *** (7 seconds, 943 milliseconds)
[09-20 00:12:05.991] [info]   2 was not equal to 4 (CircuitBreakerSpec.scala:675)
[09-20 00:12:05.992] [info]   org.scalatest.exceptions.TestFailedException:
[09-20 00:12:05.992] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[09-20 00:12:05.992] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7539)
[09-20 00:12:05.992] [info]   at akka.pattern.CircuitBreakerSpec.$anonfun$new$239(CircuitBreakerSpec.scala:675)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6514207059/job/17695073101#step:5:1081
