### ISSUE TITLE
failed: RemoteFailureSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31250]
With Aeron: https://github.com/akka/akka/runs/5546435083?check_suite_focus=true#step:5:3117

```
[WARN] [03/15/2022 00:22:50.638] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.actor.ActorSystemImpl(RemoteFailureSpec-remote-0)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
3105
[WARN] [03/15/2022 00:22:50.638] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
3106
[WARN] [03/15/2022 00:22:50.685] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.actor.ActorSystemImpl(RemoteFailureSpec-remote-1)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
3107
[WARN] [03/15/2022 00:22:50.685] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
3108
[WARN] [03/15/2022 00:22:50.725] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.actor.ActorSystemImpl(RemoteFailureSpec-remote-2)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
3109
[WARN] [03/15/2022 00:22:50.726] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
3110
[WARN] [03/15/2022 00:22:50.769] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.actor.ActorSystemImpl(RemoteFailureSpec-remote-3)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
3111
[WARN] [03/15/2022 00:22:50.769] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
3112
[WARN] [03/15/2022 00:22:50.827] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.actor.ActorSystemImpl(RemoteFailureSpec-remote-4)] Failed to load JFR flight recorder, falling back to noop. Exception: java.lang.ClassNotFoundException: akka.remote.artery.jfr.JFRRemotingFlightRecorder
3113
[WARN] [03/15/2022 00:22:50.827] [pool-1-thread-1-ScalaTest-running-RemoteFailureSpec] [akka.remote.RemoteActorRefProvider] Akka Cluster not in use - Using Akka Cluster is recommended if you need remote watch and deploy.
3114
[WARN] [03/15/2022 00:23:12.469] [RemoteFailureSpec-akka.remote.default-remote-dispatcher-7] [Association(akka://RemoteFailureSpec)] Outbound control stream to [akka://RemoteFailureSpec-remote-2@localhost:55981] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://RemoteFailureSpec-remote-2@localhost:55981] did not complete within 20000 ms
3115
[WARN] [03/15/2022 00:23:13.425] [RemoteFailureSpec-akka.remote.default-remote-dispatcher-13] [Association(akka://RemoteFailureSpec)] Outbound message stream to [akka://RemoteFailureSpec-remote-2@localhost:55981] failed. Restarting it. akka.remote.artery.OutboundHandshake$HandshakeTimeoutException: Handshake with [akka://RemoteFailureSpec-remote-2@localhost:55981] did not complete within 20000 ms
3116
[WARN] [03/15/2022 00:23:13.839] [RemoteFailureSpec-remote-2-akka.remote.default-remote-dispatcher-12] [ArteryTransport(akka://RemoteFailureSpec-remote-2)] Inbound message stream failed. Restarting it. java.lang.IllegalStateException: outboundControlIngress for [akka://RemoteFailureSpec@localhost:51581] not initialized yet
3117
[info] - should not be exhausted by sending to broken connections *** FAILED *** (31 seconds, 861 milliseconds)
3118
[info]   java.lang.AssertionError: assertion failed: timeout (9999977000 nanoseconds) while expecting 200 messages (got 180)
3119
[info]   at scala.Predef$.assert(Predef.scala:279)
3120
[info]   at akka.testkit.TestKitBase.$anonfun$receiveN_internal$1(TestKit.scala:841)
3121
[info]   at akka.testkit.TestKitBase.$anonfun$receiveN_internal$1$adapted(TestKit.scala:838)
3122
[info]   at scala.collection.immutable.Range.map(Range.scala:59)
3123
[info]   at akka.testkit.TestKitBase.receiveN_internal(TestKit.scala:838)
3124
[info]   at akka.testkit.TestKitBase.receiveN(TestKit.scala:829)
3125
[info]   at akka.testkit.TestKitBase.receiveN$(TestKit.scala:829)
3126
[info]   at akka.testkit.TestKit.receiveN(TestKit.scala:973)
3127
[info]   at akka.remote.artery.RemoteFailureSpec.$anonfun$new$7(RemoteFailureSpec.scala:50)
3128
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
3129
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:418)
3130
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)
3131
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
3132
[info]   at akka.testkit.TestKitBase.within(TestKit.scala:433)
3133
[info]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)
3134
[info]   at akka.testkit.TestKit.within(TestKit.scala:973)
3135
[info]   at akka.remote.artery.RemoteFailureSpec.$anonfun$new$2(RemoteFailureSpec.scala:50)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/6087180402?check_suite_focus=true#step:5:28489

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/6220701685?check_suite_focus=true

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/6250681859?check_suite_focus=true#step:5:3134

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/6741586189?check_suite_focus=true#step:5:3187

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/6928227359?check_suite_focus=true#step:5:3162

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/7477258113?check_suite_focus=true#step:5:3207

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/7531298044?check_suite_focus=true#step:5:3216

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8180351191?check_suite_focus=true#step:5:3155

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3166708955/jobs/5156610999#step:5:3237

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3178443393/jobs/5179936204#step:5:14776

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3246562917/jobs/5325442015#step:5:14658
