### ISSUE TITLE
failed: ActorSystemSpec - log dead letters

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31305]
https://github.com/akka/akka/runs/5780258482?check_suite_focus=true#step:5:946

```
[04-01 00:20:20.326] [info] - must log dead letters *** FAILED *** (6 seconds, 56 milliseconds)
947
[04-01 00:20:20.326] [info]   java.lang.AssertionError: timeout (6 seconds) waiting for 1 messages on InfoFilter(None,Right(from Actor\[akka://LogDeadLetters/system/testProbe.*not delivered),false)
948
[04-01 00:20:20.326] [info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
949
[04-01 00:20:20.326] [info]   at akka.actor.ActorSystemSpec.$anonfun$new$6(ActorSystemSpec.scala:161)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6243205299?check_suite_focus=true#step:5:1088

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6846529467?check_suite_focus=true#step:5:1047

**Comment by raboof** [comment]
https://github.com/akka/akka/runs/6910163523?check_suite_focus=true

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/7312253426?check_suite_focus=true#step:5:480

**Comment by octonato** [comment]
https://github.com/akka/akka/runs/7531298861?check_suite_focus=true#step:5:1010

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/7736842790?check_suite_focus=true#step:5:1094

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3139903168/jobs/5100752713#step:5:1052

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3897856744/jobs/6655968177#step:5:905
