### ISSUE TITLE
recoverWith behavior should be fixed?

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31364]
I think the currently `recoverWith` behavior is a little unexpected, should make it a retry only once?
refs:https://github.com/akka/akka/issues/20123
And I just tested with Reactor whitch works as expected with :
```java
public class Test {
    public static void main(String[] args) throws Exception {
        Flux.error(new Exception("test"))
            .onErrorResume(e -> Flux.just(10).concatWith(Flux.error(new Exception("test2"))))
            .subscribe(System.out::println);

        System.in.read();

    }
}
```
gives:
```
23:56:31.691 [main] DEBUG reactor.util.Loggers - Using Slf4j logging framework
10
23:56:31.751 [main] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.Exception: test2
Caused by: java.lang.Exception: test2
	at ***.Test.lambda$main$0(Test.java:13)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.Operators.error(Operators.java:198)
	at reactor.core.publisher.FluxError.subscribe(FluxError.java:43)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8642)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8439)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8363)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8306)
	at ***.Test.main(Test.java:14)
```
But 

```java
public class Test2 {
    public static void main(String[] args) throws Exception{
        ActorSystem actorSystem = ActorSystem.create("test");
        Source.<Integer>failed(new Exception("test"))
            .recoverWith(Throwable.class, new Supplier<Graph<SourceShape<Integer>, NotUsed>>() {
                @Override
                public Graph<SourceShape<Integer>, NotUsed> get() {
                    System.out.println("recover");
                    return Source.single(10)
                        .concat(Source.failed(new Exception("test2")));
                }
            })
            .runForeach(System.out::println,actorSystem);
        System.in.read();
    }
}
```
only gives:

```
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
recover
```

**Comment by hepin1989** [comment]
Ok, the scala docs say it will retry infinitely

**Comment by hepin1989** [comment]
Keep recoverWith as-is and also introduce fallbackTo?


_最初由 viktorklang 在 https://github.com/akka/akka/issues/20123#issuecomment-200757981 发布_

**Comment by hepin1989** [comment]
I just think it should not be deprecated, it has a good name. and I do expect:
```scala
recover
10
recover
10
recover
...
