### ISSUE TITLE
failed: HandshakeRetrySpec - must be retried during handshake-timeout (no message loss) 

### ISSUE THREAD

**Issue by octonato** [akka/akka#31367]
https://github.com/akka/akka/runs/6136665537?check_suite_focus=true#step:5:247

```scala
[info] - must be retried during handshake-timeout (no message loss) *** FAILED *** (8 seconds, 424 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for hello
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info]   at akka.remote.artery.HandshakeRetrySpec.$anonfun$new$2(HandshakeRetrySpec.scala:38)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
```

Not same as #29347, which was a `NullPointerException` and already fixed in #29244

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6476201087/job/17584535393#step:5:184

**Comment by patriknw** [comment]
Might be fixed by https://github.com/akka/akka/pull/32242, but I'm not sure if this is something else

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/7228336973/job/19697600526#step:5:182

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/7245862223/job/19736693118#step:5:182

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/7294508883/job/19879482101

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/8088859087/job/22103734341#step:5:209

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/8932158652/job/24535533858#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9183199769/job/25253464836#step:5:209

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/9589534311/job/26443464323#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9983265781/job/27590542172#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9900229116/job/27350622810#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10436227835/job/28901027008#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10674402415/job/29584842543#step:5:214

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/10692659910/job/29641490671#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11097087058/job/30827758260#step:5:209

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11245779659/job/31266441216#step:5:210

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11318855501/job/31474011344#step:5:209

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/12091913014/job/33720939723#step:5:209

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/14392755212/job/40362969087

with Aeron

**Comment by franciscolopezsancho** [comment]
[Akka Artery Aeron Tests (akka-remote/test akka-remote-tests/test)](https://github.com/akka/akka/actions/runs/15789986842/job/44513993747#step:5:190)

```
- must be retried during handshake-timeout (no message loss) *** FAILED *** (7 seconds, 493 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for hello
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:459)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:436)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:436)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:953)
[info]   at akka.remote.artery.HandshakeRetrySpec.$anonfun$new$2(HandshakeRetrySpec.scala:38)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:55)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:55)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:334)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:334)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
[info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:55)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1354)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1354)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1352)
[info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:55)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:55)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15789986842/job/44513993747#step:5:190

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16610325570/job/46991938065#step:5:186

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16924046523/job/47956189427#step:5:186

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16987603428/job/48159787149#step:5:186

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/18607823750/job/53060595254#step:5:186

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/19603207357/job/56137709293#step:7:163

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/20117505841/job/57730331986#step:7:168

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/21014679458/job/60417241820#step:7:170

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/22081518453/job/63807525720#step:7:172

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/22930357852/job/66550273047#step:7:168

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/23928164261/job/69789382324#step:7:168

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/24270172042/job/70873396522#step:7:172

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/25893668660/job/76102113971#step:7:168
