### ISSUE TITLE
failed: FileSink - must allow overriding the dispatcher using Attributes 

### ISSUE THREAD

**Issue by octonato** [akka/akka#31366]
https://github.com/akka/akka/runs/6136665905?check_suite_focus=true#step:5:18418

```scala
[04-23 00:46:33.275] [info] - must allow overriding the dispatcher using Attributes *** FAILED *** (4 seconds, 11 milliseconds)
[04-23 00:46:33.276] [info]   java.lang.AssertionError: Expected Actor[akka://FileSinkSpec/system/Materializers/StreamSupervisor-1840/flow-20-2-fileSink#158914944] to use dispatcher [akka.actor.default-dispatcher], yet used: [akka.stream.materializer.blocking-io-dispatcher]
[04-23 00:46:33.276] [info]   at akka.stream.testkit.Utils$.assertDispatcher(Utils.scala:26)
[04-23 00:46:33.277] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$27(FileSinkSpec.scala:192)
[04-23 00:46:33.277] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$27$adapted(FileSinkSpec.scala:182)
[04-23 00:46:33.277] [info]   at akka.stream.io.FileSinkSpec.targetFile(FileSinkSpec.scala:244)
[04-23 00:46:33.279] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$26(FileSinkSpec.scala:182)
[04-23 00:46:33.279] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[04-23 00:46:33.279] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[04-23 00:46:33.279] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[04-23 00:46:33.279] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[04-23 00:46:33.279] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[04-23 00:46:33.279] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6547186775?check_suite_focus=true#step:5:19066

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/6741586379?check_suite_focus=true

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6846529522?check_suite_focus=true#step:5:18246

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6944430648?check_suite_focus=true#step:5:18579

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/7083637091?check_suite_focus=true#step:5:18369

**Comment by patriknw** [comment]
https://github.com/akka/akka/runs/7830220918?check_suite_focus=true#step:5:18500

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/8172943647?check_suite_focus=true#step:5:18670

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3257655849/jobs/5349063878#step:5:19021

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3615722687/jobs/6093014148#step:5:5610
