### ISSUE TITLE
Failed: TcpSpec

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#31434]
https://github.com/akka/akka/runs/6839595055?check_suite_focus=true#step:5:5666

```
[06-11 00:24:52.649] [info] TcpSpec:
Coroner Thread Count starts at 53 in akka.stream.io.TcpSpec
[06-11 00:24:52.652] [info] Outgoing TCP stream
[06-11 00:24:52.699] [info] - must work in the happy case (45 milliseconds)
[06-11 00:24:52.729] [info] - must be able to write a sequence of ByteStrings (29 milliseconds)
[06-11 00:24:52.781] [info] - must be able to read a sequence of ByteStrings (52 milliseconds)
--> [Outgoing TCP stream must fail the materialized future when the connection fails] Start of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: The future returned an exception of type: scala.concurrent.Future$$anon$3, with message: Future.failed not completed with a throwable..)]
| [DEBUG] [06/11/2022 00:24:52.781] [pool-1-thread-1-ScalaTest-running-TcpSpec] [WithLogCapturing(akka://TcpSpec)] Logging started for test [Outgoing TCP stream must fail the materialized future when the connection fails]
| [DEBUG] [06/11/2022 00:24:52.792] [TcpSpec-akka.actor.internal-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a] Executing [WorkerForCommand(Connect(example.com:666,None,List(),Some(1 second),true),Actor[akka://TcpSpec/system/Materializers/StreamSupervisor-1889/$$d#1039795441],akka.io.TcpManager$$anon$1$$Lambda$787/0x0000000800880840@1796398)]
| [DEBUG] [06/11/2022 00:24:52.792] [TcpSpec-akka.actor.internal-dispatcher-5] [akka://TcpSpec/system/IO-TCP/selectors/$a] Scheduling Registering channel java.nio.channels.SocketChannel[unconnected] with initialOps 0
| [DEBUG] [06/11/2022 00:24:52.792] [TcpSpec-akka.io.pinned-dispatcher-15] [akka://TcpSpec/system/IO-TCP/selectors/$a] Registering channel java.nio.channels.SocketChannel[unconnected] with initialOps 0
| [DEBUG] [06/11/2022 00:24:52.793] [TcpSpec-akka.actor.internal-dispatcher-5] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] Resolving example.com before connecting
| [DEBUG] [06/11/2022 00:24:52.796] [TcpSpec-akka.actor.internal-dispatcher-4] [akka://TcpSpec/system/IO-DNS] Resolution request for example.com from Actor[akka://TcpSpec/system/IO-TCP/selectors/$a/9#663576921]
| [DEBUG] [06/11/2022 00:24:52.801] [TcpSpec-akka.actor.default-blocking-io-dispatcher-31] [akka://TcpSpec/system/IO-DNS/inet-address/$b] Request for [example.com] was not yet cached
| [DEBUG] [06/11/2022 00:24:52.805] [TcpSpec-akka.actor.internal-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] Attempting connection to [example.com/93.184.216.34:666]
| [DEBUG] [06/11/2022 00:24:52.805] [TcpSpec-akka.io.pinned-dispatcher-15] [akka://TcpSpec/system/IO-TCP/selectors/$a] Enabling 8 on channel=java.nio.channels.SocketChannel[connection-pending remote=example.com/93.184.216.34:666], selector=sun.nio.ch.EPollSelectorImpl@2e4905f3, interestOps=0, readyOps=0
| [DEBUG] [06/11/2022 00:24:52.806] [TcpSpec-akka.actor.internal-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] Connection established to [example.com:666]
| [DEBUG] [06/11/2022 00:24:52.806] [TcpSpec-akka.actor.internal-dispatcher-2] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] [Actor[akka://TcpSpec/system/Materializers/StreamSupervisor-1889/$$d#1039795441]] registered as connection handler
| [DEBUG] [06/11/2022 00:24:52.807] [TcpSpec-akka.actor.internal-dispatcher-2] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] Read [0] bytes.
| [DEBUG] [06/11/2022 00:24:52.807] [TcpSpec-akka.io.pinned-dispatcher-15] [akka://TcpSpec/system/IO-TCP/selectors/$a] Enabling 1 on channel=java.nio.channels.SocketChannel[connected local=/10.1.1.2:54252 remote=example.com/93.184.216.34:666], selector=sun.nio.ch.EPollSelectorImpl@2e4905f3, interestOps=0, readyOps=8
| [DEBUG] [06/11/2022 00:24:52.807] [TcpSpec-akka.actor.internal-dispatcher-4] [akka://TcpSpec/system/IO-TCP/selectors/$a/9] Closing connection due to IO error java.io.IOException: Connection reset by peer
| [DEBUG] [06/11/2022 00:24:52.808] [pool-1-thread-1-ScalaTest-running-TcpSpec] [WithLogCapturing(akka://TcpSpec)] Logging finished for test [Outgoing TCP stream must fail the materialized future when the connection fails]
<-- [Outgoing TCP stream must fail the materialized future when the connection fails] End of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: The future returned an exception of type: scala.concurrent.Future$$anon$3, with message: Future.failed not completed with a throwable..)]
[06-11 00:24:52.831] [info] - must fail the materialized future when the connection fails *** FAILED *** (34 milliseconds)
[06-11 00:24:52.831] [info]   The future returned an exception of type: scala.concurrent.Future$$anon$3, with message: Future.failed not completed with a throwable.. (TcpSpec.scala:169)
[06-11 00:24:52.831] [info]   org.scalatest.exceptions.TestFailedException:
[06-11 00:24:52.831] [info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[06-11 00:24:52.831] [info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[06-11 00:24:52.831] [info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:259)
[06-11 00:24:52.831] [info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[06-11 00:24:52.831] [info]   at akka.stream.io.TcpSpec.f$proxy4$1(TcpSpec.scala:169)
[06-11 00:24:52.832] [info]   at akka.stream.io.TcpSpec.$init$$$anonfun$1$$anonfun$4(TcpSpec.scala:159)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6839609072?check_suite_focus=true#step:5:18739

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/6839609112?check_suite_focus=true#step:5:18459
