### ISSUE TITLE
Abrupt upstream cancellation

### ISSUE THREAD

**Issue by jonathan-neufeld-asurion** [akka/akka#31454]
This issue was [first reported](https://github.com/akka/akka-grpc/issues/1624) on _Akka-gRPC_ because it's not clear which sub-system is instigating this behaviour.

### Versions used 

(More details available in the project's `build.sbt` file)

Akka version: 2.6.19
Akka HTTP version: 10.2.7

### Expected Behavior

All events pump from the emitter endpoint to the sink endpoint without any errors and without any events being dropped

### Actual Behavior

Most events are dropped and the sink endpoint reports that the upstream cancelled the stream abruptly, sometimes more than once per gRPC call.  This has only been mitigated by _dramatically_ throttling the emission of events to an unacceptable degree, and there is no proof this resolves the issue.

### Relevant logs

The most pertinent error that occurs in the logs generated by the receiving side:
```
Error in stage [akka.stream.scaladsl.MergeHub$$anon$2$$anon$3]: Upstream producer failed with exception, removing from MergeHub now
akka.stream.scaladsl.MergeHub$ProducerFailed: Upstream producer failed with exception, removing from MergeHub now
	at akka.stream.scaladsl.MergeHub$$anon$2$$anon$3.onUpstreamFailure(Hub.scala:352)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:525)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: akka.http.scaladsl.model.http2.PeerClosedStreamException: Stream with ID [???] was closed by peer with code CANCEL(0x08)
```

### Reproducible Test Case

The issue is complex and requires configuration, so here is a link to a GitHub project that reproduces the issue: [mergehub-streaming-repo](https://github.com/jonathan-neufeld-asurion/mergehub-streaming-repro)

**Comment by jonathan-neufeld-asurion** [comment]
This was programmer error, a misunderstanding of how gRPC with Akka Streams works, sending a gRPC reply immediately after _queuing_ the passed `Source` effectively causes the upstream to close it before the `MergeHub` can process it:

```
  override def publish(
      in: Source[FooEvent, NotUsed],
      metadata: Metadata
  ): Future[Received] = {
    in runWith sink
    Future.successful(Received())
  }
```
The resolution was to watch for termination and send a gRPC reply only upon termination.
```
  override def publish(
      in: Source[FooEvent, NotUsed],
      metadata: Metadata
  ): Future[Received] = {
    ((in watchTermination ()) {
        case (_, terminationFuture) =>
          terminationFuture.map (_ => Received())
      } toMat sink)(Keep.left) run
  }
```
