### ISSUE TITLE
failed: LargeMessagesStreamSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#31477]
https://github.com/akka/akka/runs/7491496387?check_suite_focus=true#step:5:2032

This was reported before and fixed, but this time failing on a different test method. 

```scala
[info] LargeMessagesStreamSpec:
Coroner Thread Count starts at 38 in akka.remote.artery.LargeMessagesStreamSpec
[info] The large message support
[2031](https://github.com/akka/akka/runs/7491496387?check_suite_focus=true#step:5:2032)
[info] - should not affect regular communication *** FAILED *** (6 seconds, 700 milliseconds)
[info]   java.util.concurrent.TimeoutException: Future timed out after [1 second]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
[info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
[info]   at scala.concurrent.Await$.result(package.scala:124)
[info]   at akka.remote.artery.LargeMessagesStreamSpec.$anonfun$awaitResolve$1(LargeMessagesStreamSpec.scala:146)
[info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/runs/7708449972?check_suite_focus=true#step:5:1997

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3166708955/jobs/5156610999#step:5:2015
