### ISSUE TITLE
failed: EventSourcedBehaviorStashSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31493]
https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23100

```
[08-18 00:51:50.026] [info] - must handle many stashed *** FAILED *** (6 seconds, 130 milliseconds)
[23100](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23101)
[08-18 00:51:50.030] [info]   java.lang.AssertionError: timeout (6 seconds) while expecting 10 messages (got 0)
[23101](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23102)
[08-18 00:51:50.030] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[23102](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23103)
[08-18 00:51:50.030] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1(TestProbeImpl.scala:262)
[23103](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23104)
[08-18 00:51:50.031] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1$adapted(TestProbeImpl.scala:257)
[23104](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23105)
[08-18 00:51:50.031] [info]   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[23105](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23106)
[08-18 00:51:50.031] [info]   at scala.collection.immutable.Range.foreach(Range.scala:158)
[23106](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23107)
[08-18 00:51:50.031] [info]   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[23107](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23108)
[08-18 00:51:50.031] [info]   at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[23108](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23109)
[08-18 00:51:50.031] [info]   at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[23109](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23110)
[08-18 00:51:50.031] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages_internal(TestProbeImpl.scala:257)
[23110](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23111)
[08-18 00:51:50.031] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages(TestProbeImpl.scala:244)
[23111](https://github.com/akka/akka/runs/7889844884?check_suite_focus=true#step:5:23112)
[08-18 00:51:50.031] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorStashSpec.$anonfun$new$5(EventSourcedBehaviorStashSpec.scala:326)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3116393445/jobs/5054172889#step:5:23425

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3484194539/jobs/5828481094#step:5:24686

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3588181922/jobs/6039294825#step:5:3674

**Comment by pvlugter** [comment]
Original failure again: https://github.com/akka/akka/actions/runs/5850300015/job/15859550802#step:5:23524

```
[08-14 00:48:30.770] [info] - must handle many stashed *** FAILED *** (6 seconds, 99 milliseconds)
[08-14 00:48:30.771] [info]   java.lang.AssertionError: timeout (6 seconds) while expecting 10 messages (got 0)
[08-14 00:48:30.771] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[08-14 00:48:30.771] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1(TestProbeImpl.scala:262)
[08-14 00:48:30.771] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1$adapted(TestProbeImpl.scala:257)
[08-14 00:48:30.771] [info]   at scala.collection.immutable.Range.map(Range.scala:59)
[08-14 00:48:30.771] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages_internal(TestProbeImpl.scala:257)
[08-14 00:48:30.771] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages(TestProbeImpl.scala:244)
[08-14 00:48:30.771] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorStashSpec.$anonfun$new$5(EventSourcedBehaviorStashSpec.scala:328)
```
