### ISSUE TITLE
failed: ActorContextDelegateSpec

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31497]
https://github.com/akka/akka/runs/7987568376?check_suite_focus=true#step:5:4000

```
[08-24 04:47:50.888] [info] - must publish unhandled message to eventStream as UnhandledMessage and switch to delegator behavior *** FAILED *** (12 seconds, 11 milliseconds)
[08-24 04:47:50.889] [info]   java.lang.AssertionError: timeout (12 seconds) during fishForMessage, seen messages List(), hint:
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.loop$1(TestProbeImpl.scala:316)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.fishForMessage_internal(TestProbeImpl.scala:320)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.fishForMessage(TestProbeImpl.scala:268)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.fishForMessage(TestProbeImpl.scala:275)
[08-24 04:47:50.889] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.$anonfun$new$4(ActorContextDelegateSpec.scala:85)
[08-24 04:47:50.889] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[08-24 04:47:50.889] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[08-24 04:47:50.889] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[08-24 04:47:50.889] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[08-24 04:47:50.889] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
[08-24 04:47:50.889] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
[08-24 04:47:50.889] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.withFixture(ActorContextDelegateSpec.scala:52)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[08-24 04:47:50.889] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[08-24 04:47:50.889] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.runTest(ActorContextDelegateSpec.scala:52)
[08-24 04:47:50.889] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
[08-24 04:47:50.889] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[08-24 04:47:50.889] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[08-24 04:47:50.889] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[08-24 04:47:50.889] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[08-24 04:47:50.889] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[08-24 04:47:50.890] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[08-24 04:47:50.890] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[08-24 04:47:50.890] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[08-24 04:47:50.890] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[08-24 04:47:50.890] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
[08-24 04:47:50.890] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
[08-24 04:47:50.890] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.runTests(ActorContextDelegateSpec.scala:52)
[08-24 04:47:50.890] [info]   at org.scalatest.Suite.run(Suite.scala:1112)
[08-24 04:47:50.890] [info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[08-24 04:47:50.890] [info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:31)
[08-24 04:47:50.890] [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[08-24 04:47:50.890] [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[08-24 04:47:50.890] [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[08-24 04:47:50.890] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ActorContextDelegateSpec.scala:52)
[08-24 04:47:50.890] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[08-24 04:47:50.890] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[08-24 04:47:50.890] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[08-24 04:47:50.890] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[08-24 04:47:50.890] [info]   at akka.actor.typed.scaladsl.ActorContextDelegateSpec.run(ActorContextDelegateSpec.scala:52)
[08-24 04:47:50.890] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[08-24 04:47:50.890] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[08-24 04:47:50.890] [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[08-24 04:47:50.890] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08-24 04:47:50.890] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08-24 04:47:50.890] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08-24 04:47:50.932] [info]   at java.lang.Thread.run(Thread.java:748)
[08-24 04:47:50.939] [info] ActorLoggingTest:
[WARN] [08/24/2022 04:47:50.941] [ActorLoggingTest-akka.actor.default-dispatcher-10] [akka://ActorLoggingTest/user/$a] unhandled message from Actor[akka://ActorLoggingTest/deadLetters]: Hello
[INFO] [akkaDeadLetter][08/24/2022 04:47:50.943] [ActorLoggingTest-akka.actor.default-dispatcher-11] [akka://ActorLoggingTest/user/$a] Message [java.lang.String] to Actor[akka://ActorLoggingTest/user/$a#711066292] was unhandled. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by He-Pin** [comment]
@GreyPlane CC

**Comment by GreyPlane** [comment]
> @GreyPlane CC

it looks like bcs the essence of asynchronous communication, sometimes unhandled message happened before the subscription.
changed it to the testKit.createUnhandledMessageProbe.
sry for the inconvenience .
