### ISSUE TITLE
Failed: FlowMergeAllSpec——must merge all elements of the first completed source to its downstream

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31546]
```
[09-03 14:35:32.382] [info] - must merge all elements of the first completed source to its downstream  *** FAILED *** (26 milliseconds)
[09-03 14:35:32.382] [info]   HashSet(5, 1, 6, 7, 3, 4) did not contain all elements of List(1, 2) (FlowMergeAllSpec.scala:34)
[09-03 14:35:32.382] [info]   org.scalatest.exceptions.TestFailedException:
[09-03 14:35:32.382] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[09-03 14:35:32.382] [info]   at org.scalatest.matchers.dsl.ResultOfContainWord.allElementsOf(ResultOfContainWord.scala:319)
[09-03 14:35:32.382] [info]   at akka.stream.scaladsl.FlowMergeAllSpec.$anonfun$new$4(FlowMergeAllSpec.scala:34)
[09-03 14:35:32.382] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[09-03 14:35:32.382] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[09-03 14:35:32.382] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[09-03 14:35:32.382] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[09-03 14:35:32.382] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[09-03 14:35:32.383] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[09-03 14:35:32.383] [info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:64)
[09-03 14:35:32.383] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[09-03 14:35:32.383] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[09-03 14:35:32.383] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[09-03 14:35:32.404] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[09-03 14:35:32.404] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[09-03 14:35:32.404] [info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[09-03 14:35:32.404] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[09-03 14:35:32.404] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[09-03 14:35:32.404] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[09-03 14:35:32.404] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[09-03 14:35:32.404] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
[09-03 14:35:32.404] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
[09-03 14:35:32.404] [info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
[09-03 14:35:32.404] [info]   at org.scalatest.Suite.run(Suite.scala:1112)
[09-03 14:35:32.405] [info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[09-03 14:35:32.405] [info]   at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
[09-03 14:35:32.405] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[09-03 14:35:32.405] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[09-03 14:35:32.405] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[09-03 14:35:32.405] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[09-03 14:35:32.405] [info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
[09-03 14:35:32.405] [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[09-03 14:35:32.405] [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[09-03 14:35:32.405] [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[09-03 14:35:32.405] [info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
[09-03 14:35:32.405] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[09-03 14:35:32.405] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[09-03 14:35:32.405] [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[09-03 14:35:32.405] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09-03 14:35:32.405] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09-03 14:35:32.405] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09-03 14:35:32.405] [info]   at java.lang.Thread.run(Thread.java:748)
```
`2` from the first completed source is lost.

**Comment by He-Pin** [comment]
I think this should be the expected behavior,the test need update

**Comment by He-Pin** [comment]
I think this is an expected behavior anyway, because the merge order is undefined.
HashSet(10, 1, 9, 7, 3, 8) did not contain all elements of List(1, 2)
I will update the tests to fix it.

**Comment by johanandren** [comment]
https://github.com/akka/akka/runs/8218549653?check_suite_focus=true

**Comment by He-Pin** [comment]
Yes hope this get merged asap
