### ISSUE TITLE
Failed: MapWithResourceSpec.MapWithResource must fail when close throws exception

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31585]
```
sbt.ForkMain$ForkError: java.lang.AssertionError: assertion failed: expected OnNext(a), found OnError(akka.stream.testkit.Utils$TE: 
)
	at scala.Predef$.assert(Predef.scala:279)
	at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
	at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
	at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
	at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
	at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:399)
	at akka.stream.scaladsl.MapWithResourceSpec.$anonfun$new$33(MapWithResourceSpec.scala:247)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:36)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/akka/akka/runs/8341017910

**Comment by He-Pin** [comment]
I think the maybe cause by `upstreamFinished` need to check if the input has elemt to emit in StatefulMap?

**Comment by He-Pin** [comment]
Will try to look into this.

**Comment by He-Pin** [comment]
https://github.com/akka/akka/issues/31587

**Comment by He-Pin** [comment]
```scala
    "fail when close throws exception" in {
      (1 to 100000).foreach {_ =>
        val out = TestSubscriber.probe[String]()
        Source
          .single(1)
          .mapWithResource(() => Iterator("a"))((it, _) => if (it.hasNext) Some(it.next()) else None, _ => throw TE(""))
          .collect { case Some(line) => line }
          .runWith(Sink.fromSubscriber(out))

        out.request(61)
        out.expectNext("a")
        out.expectError(TE(""))
      }
    }

```
I reproduced it only once and can not get another one.

**Comment by He-Pin** [comment]
`unfoldResource` failed too

```scala
    "unfoldResource fail when close throws exception" in {
      (1 to 100000).foreach { _ =>
        val sub = Source
          .unfoldResource[String, Iterator[String]](
            () => Iterator("a"),
            it => if (it.hasNext) Some(it.next()) else None,
            _ => throw TE(""))
          .map(identity)
          .runWith(TestSink.probe)

        sub.ensureSubscription()
          .request(61)
          .expectNext("a")
          .expectError(TE(""))
      }
    }
```

**Comment by He-Pin** [comment]
I think this should be fine, as: 

<html>
<body>


A Publisher MAY signal fewer onNext than requested and terminate the Subscription by calling onComplete or onError.
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by johanandren** [comment]
There is no guarantee that the stream interpreter processes one element all the way through the stream at a time when you request many like that, and an error is not signalled as a stream element but will tear the stream down regardless of if elements have been processed in downstream operators. 

To do the last test snippet you'd either have to request 1, expect next, request another element and expect the failure or turn the failure into an element with recover to put it into the stream as an element.

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3058750908/jobs/4935311415#step:5:16034
