### ISSUE TITLE
Failed: mapWithResource must use dedicated blocking-io-dispatcher by default

### ISSUE THREAD

**Issue by He-Pin** [akka/akka#31584]
```
[09-14 04:46:23.868] [info] - must use dedicated blocking-io-dispatcher by default *** FAILED *** (34 milliseconds)
[09-14 04:46:23.868] [info]   java.lang.AssertionError: Expected Actor[akka://MapWithResourceSpec/system/Materializers/StreamSupervisor-1176/flow-8-2-mapWithResource#1912087400] to use dispatcher [akka.stream.materializer.blocking-io-dispatcher], yet used: [akka.actor.default-dispatcher]
[09-14 04:46:23.868] [info]   at akka.stream.testkit.Utils$.assertDispatcher(Utils.scala:26)
[09-14 04:46:23.868] [info]   at akka.stream.scaladsl.MapWithResourceSpec.$anonfun$new$23(MapWithResourceSpec.scala:217)
[09-14 04:46:23.868] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[09-14 04:46:23.868] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[09-14 04:46:23.868] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[09-14 04:46:23.868] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[09-14 04:46:23.868] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[09-14 04:46:23.869] [info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:64)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
[09-14 04:46:23.869] [info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[09-14 04:46:23.869] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[09-14 04:46:23.869] [info]   at scala.collection.immutable.List.foreach(List.scala:333)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[09-14 04:46:23.869] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
[09-14 04:46:23.869] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
[09-14 04:46:23.870] [info]   at akka.testkit.AkkaSpec.runTests(AkkaSpec.scala:54)
[09-14 04:46:23.870] [info]   at org.scalatest.Suite.run(Suite.scala:1112)
[09-14 04:46:23.870] [info]   at org.scalatest.Suite.run$(Suite.scala:1094)
[09-14 04:46:23.870] [info]   at akka.testkit.AkkaSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AkkaSpec.scala:54)
[09-14 04:46:23.870] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
[09-14 04:46:23.870] [info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[09-14 04:46:23.870] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
[09-14 04:46:23.870] [info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
[09-14 04:46:23.870] [info]   at akka.testkit.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:54)
[09-14 04:46:23.870] [info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[09-14 04:46:23.870] [info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[09-14 04:46:23.870] [info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[09-14 04:46:23.870] [info]   at akka.testkit.AkkaSpec.run(AkkaSpec.scala:54)
[09-14 04:46:23.870] [info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[09-14 04:46:23.870] [info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[09-14 04:46:23.870] [info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[09-14 04:46:23.870] [info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09-14 04:46:23.870] [info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09-14 04:46:23.870] [info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09-14 04:46:23.870] [info]   at java.lang.Thread.run(Thread.java:748)
```
https://github.com/akka/akka/actions/runs/3050072836/jobs/4916838243

**Comment by He-Pin** [comment]
I ran it twenty times and not fail locally , seems like a bug in the materializer?

**Comment by johanandren** [comment]
Possibly related failure (verifying dispatcher taking effect): https://github.com/akka/akka/issues/31366

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3773495991/jobs/6414981558

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/4119430289/jobs/7113083804#step:5:15535

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/4158916751/jobs/7194476076#step:5:17436

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/4248142127/jobs/7386971901#step:5:15078

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/4457970335/jobs/7829369548#step:5:15073

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4559171130/jobs/8042827584#step:5:15958

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5449501344/jobs/9913783933

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5481342567/jobs/9985519831#step:5:15385

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5873019170/job/15925610619#step:5:15856

**Comment by He-Pin** [comment]
This one and the FileSinkSpec,both sometimes field on this.

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5993976014/job/16255002466#step:5:15824

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6673426500/job/18138982269#step:5:15221
