### ISSUE TITLE
PersistentActorRecoveryTimeoutSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#31624]
https://github.com/akka/akka/actions/runs/3124231250/jobs/5067396750#step:5:3926

```scala
[09-26 00:29:26.736] [info] - should should not interfere with receive timeouts *** FAILED *** (6 seconds, 26 milliseconds)
[09-26 00:29:26.736] [info]   java.util.concurrent.TimeoutException: Future timed out after [6 seconds]
[09-26 00:29:26.736] [info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
[09-26 00:29:26.739] [info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
[09-26 00:29:26.739] [info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
[09-26 00:29:26.739] [info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
[09-26 00:29:26.739] [info]   at scala.concurrent.Await$.result(package.scala:124)
[09-26 00:29:26.739] [info]   at akka.persistence.journal.SteppingInmemJournal$.step(SteppingInmemJournal.scala:32)
[09-26 00:29:26.740] [info]   at akka.persistence.PersistentActorRecoveryTimeoutSpec.$anonfun$new$4(PersistentActorRecoveryTimeoutSpec.scala:141)
[09-26 00:29:26.740] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[09-26 00:29:26.740] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[09-26 00:29:26.740] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[09-26 00:29:26.740] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[09-26 00:29:26.740] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3147770388/jobs/5117595752#step:5:4356

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3212274629/jobs/5250998941#step:5:3977

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3238780413/jobs/5307375731#step:5:3971

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3528120611/jobs/5917878767#step:5:3977

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3597644602/jobs/6059603744#step:5:3387

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3606013738/jobs/6076938654#step:5:4410

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3615730434/jobs/6093029935#step:5:4022

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3671466916/jobs/6206699866#step:5:3367

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3753783438/jobs/6377368943#step:5:4008

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3920900421/jobs/6702801645#step:5:4192

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/4333492773/jobs/7566651551#step:5:3870

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/4452622920/jobs/7820419899#step:5:4136

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4537822418/jobs/7996074642#step:5:4179

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5384316701/jobs/9772085066#step:5:4257

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5395822032/jobs/9798721426#step:5:4285

**Comment by He-Pin** [comment]
https://github.com/akka/akka/actions/runs/5488472819/jobs/10001374520?pr=32005#step:5:3819

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5559358682/job/15060389742#step:5:3889

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5651106055/job/15308632906#step:5:4276

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5720948828/job/15501757050#step:5:4294
