### ISSUE TITLE
Failed: EventSourcedBehaviorRetentionSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#31623]
Have been reported before, but then marked as fixed. 
This is slightly different than previous reports, so opening a new one.

https://github.com/akka/akka/actions/runs/3120281053/jobs/5060740827#step:5:23326

```scala
[09-25 01:00:25.535] [info] - must be possible to snapshot every event *** FAILED *** (117 milliseconds)
[09-25 01:00:25.536] [info]   SnapshotCompleted(SnapshotMetadata(c9),6,1664067625407)) was not an instance of akka.persistence.typed.DeleteSnapshotsCompleted, but an instance of akka.persistence.typed.SnapshotCompleted (EventSourcedBehaviorRetentionSpec.scala:106)
[09-25 01:00:25.542] [info]   org.scalatest.exceptions.TestFailedException:
[09-25 01:00:25.543] [info]   at org.scalatest.matchers.MatchersHelper$.newTestFailedException(MatchersHelper.scala:137)
[09-25 01:00:25.543] [info]   at org.scalatest.matchers.TypeMatcherHelper$.assertAType(TypeMatcherHelper.scala:162)
[09-25 01:00:25.543] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$WrappedSignalProbeAssert.expectDeleteSnapshotCompleted(EventSourcedBehaviorRetentionSpec.scala:106)
[09-25 01:00:25.543] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.$anonfun$new$40(EventSourcedBehaviorRetentionSpec.scala:480)
[09-25 01:00:25.543] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[09-25 01:00:25.543] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[09-25 01:00:25.543] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[09-25 01:00:25.543] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[09-25 01:00:25.543] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[09-25 01:00:25.543] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[09-25 01:00:25.544] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
[09-25 01:00:25.544] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
[09-25 01:00:25.544] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.withFixture(EventSourcedBehaviorRetentionSpec.scala:117)
[09-25 01:00:25.544] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
[09-25 01:00:25.544] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3139903168/jobs/5100752477#step:5:23546

Debug logs: 
[5_Compile and Test.txt](https://github.com/akka/akka/files/9664259/5_Compile.and.Test.txt)

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3162450786/jobs/5149054074#step:5:1556

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3166708955/jobs/5156611376#step:5:23154

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3216094805/jobs/5257649485#step:5:22937

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3253736278/jobs/5341274259#step:5:22988

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3261479772/jobs/5356458662#step:5:22855

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3277859636/jobs/5399661949#step:5:23926

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3293845210/jobs/5430747594#step:5:23665

**Comment by octonato** [comment]
Quite some failures in this particular test recently.

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3301239607/jobs/5446489680#step:5:22838

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3309135445/jobs/5462015912#step:5:22866

We definitely introduced a regression or a flakiness recently. This is failing quite often now.

**Comment by leviramsey** [comment]
#31598 or #31645 seem like candidates?

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3317205741/jobs/5479817414#step:5:23806

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/3432880859/jobs/5722606408#step:5:22927
