### ISSUE TITLE
Failed: docs.stream.cookbook.RecipeAdhocSource

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#31674]
https://github.com/akka/akka/actions/runs/3253711477/jobs/5341219952#step:5:10973
https://github.com/akka/akka/actions/runs/3257634599/jobs/5349020934#step:5:10894
https://github.com/akka/akka/actions/runs/3261455837/jobs/5356374302#step:5:10942

```
[10-15 00:34:04.347] [info] - must restart up to specified maxRetries *** FAILED *** (2 seconds, 532 milliseconds)
[10-15 00:34:04.347] [info]   class akka.stream.BackpressureTimeoutException was not equal to class java.util.concurrent.TimeoutException (RecipeAdhocSource.scala:121)
[10-15 00:34:04.353] [info]   org.scalatest.exceptions.TestFailedException:
[10-15 00:34:04.353] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[10-15 00:34:04.353] [info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
[10-15 00:34:04.353] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
[10-15 00:34:04.354] [info]   at docs.stream.cookbook.RecipeAdhocSource.$anonfun$new$12(RecipeAdhocSource.scala:121)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3257634599/jobs/5349020934#step:5:10894
