### ISSUE TITLE
Failed: AeronStreamLatencySpec

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#31778]
https://github.com/akka/akka/actions/runs/3579775018/jobs/6021293486#step:9:1500

```
- must be low for rate-100-size-100, at 100 msg/s, payloadSize = 100 (on node 'first', class akka.remote.artery.aeron.AeronStreamLatencySpecMultiJvmNode1) *** FAILED *** (6 seconds, 177 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for Done
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:279)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
[info] [JVM-1]   at akka.remote.artery.aeron.AeronStreamLatencySpec.$anonfun$test$3(AeronStreamLatencySpec.scala:225)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:418)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:406)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:973)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:433)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:433)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:973)
[info] [JVM-1]   at akka.remote.artery.aeron.AeronStreamLatencySpec.$anonfun$test$1(AeronStreamLatencySpec.scala:207)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:412)
[info] [JVM-1]   at akka.remote.artery.aeron.AeronStreamLatencySpec.test(AeronStreamLatencySpec.scala:170)
[info] [JVM-1]   at akka.remote.artery.aeron.AeronStreamLatencySpec.$anonfun$new$6(AeronStreamLatencySpec.scala:321)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/3598318538/jobs/6060962137#step:9:1485

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3616332581/jobs/6094183927#step:9:1543

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3635279128/jobs/6134229588

**Comment by patriknw** [comment]
Probably because the removal of classic remoting. Well, this test had `artery.enabled = false` before that, but that isn't allowed at runtime anymore. Will have to look into how to make that work again.
