### ISSUE TITLE
Failed: ClusterSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31772]
https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23764

JDK 17, Scala 2.12 Nightly

```
[11-27 01:01:38.585] [info] - must leave via CoordinatedShutdown.run when member status is Joining *** FAILED *** (1 second, 45 milliseconds)
[23764](https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23765)
[11-27 01:01:38.587] [info]   Leaving did not equal Exiting (ClusterSpec.scala:275)
[23765](https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23766)
[11-27 01:01:38.588] [info]   org.scalatest.exceptions.TestFailedException:
[23766](https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23767)
[11-27 01:01:38.588] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[23767](https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23768)
[11-27 01:01:38.589] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6922)
[23768](https://github.com/akka/akka/actions/runs/3555943136/jobs/5972924273#step:5:23769)
[11-27 01:01:38.589] [info]   at akka.cluster.ClusterSpec.$anonfun$new$29(ClusterSpec.scala:275)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/17718611080/job/50347068101#step:5:23827

Not quite the same?

```
[09-15 00:55:00.755] [info] - must leave via CoordinatedShutdown.run *** FAILED *** (1 second, 35 milliseconds)
[09-15 00:55:00.755] [info]   Leaving did not equal Exiting (ClusterSpec.scala:202)
[09-15 00:55:00.755] [info]   org.scalatest.exceptions.TestFailedException:
[09-15 00:55:00.755] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[09-15 00:55:00.755] [info]   at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6956)
[09-15 00:55:00.755] [info]   at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[09-15 00:55:00.755] [info]   at akka.testkit.AkkaSpec.should(AkkaSpec.scala:55)
[09-15 00:55:00.755] [info]   at akka.cluster.ClusterSpec.f$proxy16$1(ClusterSpec.scala:202)
[09-15 00:55:00.755] [info]   at akka.cluster.ClusterSpec.$init$$$anonfun$1$$anonfun$14(ClusterSpec.scala:179)
```
