### ISSUE TITLE
Failed: EventSourcedBehaviorRetentionSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31796]
https://github.com/akka/akka/actions/runs/3709022163/jobs/6287193701

```
[12-16 00:49:16.125] [info] - must delete snapshots automatically, based on criteria *** FAILED *** (6 seconds, 70 milliseconds)
[12-16 00:49:16.125] [info]   java.lang.AssertionError: Timeout (6 seconds) during expectMessageClass waiting for class akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$WrappedSignal
[12-16 00:49:16.125] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[12-16 00:49:16.126] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:239)
[12-16 00:49:16.127] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:218)
[12-16 00:49:16.127] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$WrappedSignalProbeAssert.expectSnapshotCompleted(EventSourcedBehaviorRetentionSpec.scala:98)
[12-16 00:49:16.127] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.$anonfun$new$17(EventSourcedBehaviorRetentionSpec.scala:287)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3740940330/jobs/6349908422#step:5:786

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346723#step:5:21622

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3745180846/jobs/6359338294#step:5:21348

**Comment by octonato** [comment]
Happened twice on the same build.

https://github.com/akka/akka/actions/runs/3773495991/jobs/6414981409#step:5:21125 (Scala 2.12)
https://github.com/akka/akka/actions/runs/3773495991/jobs/6414981506#step:5:22042 (Scala 2.13)

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/3814312404/jobs/6488510336#step:5:13768

**Comment by johanandren** [comment]
Looks like it correlates with #31786 being merged (dec 14, first failure dec 16)
