### ISSUE TITLE
Failed: SnapshotSerializeSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31803]
https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30225

```
[12-20 01:02:20.033] [info] - should test snapshot events with RetentionCriteria after sending commands *** FAILED *** (2 seconds, 30 milliseconds)
[30225](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30226)
[12-20 01:02:20.033] [info]   java.lang.AssertionError: assertion failed: Failed to persist NonEmptyState(abcdefgh), got Some(NonEmptyState(abcdefghij)) instead
[30226](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30227)
[12-20 01:02:20.033] [info]   at scala.Predef$.assert(Predef.scala:279)
[30227](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30228)
[12-20 01:02:20.033] [info]   at akka.persistence.testkit.scaladsl.ExpectOps.$anonfun$expectNextPersisted$1(TestOps.scala:148)
[30228](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30229)
[12-20 01:02:20.033] [info]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:332)
[30229](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30230)
[12-20 01:02:20.033] [info]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:349)
[30230](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30231)
[12-20 01:02:20.033] [info]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:321)
[30231](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30232)
[12-20 01:02:20.034] [info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:973)
[30232](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30233)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.ExpectOps.expectNextPersisted(TestOps.scala:150)
[30233](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30234)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.ExpectOps.expectNextPersisted$(TestOps.scala:143)
[30234](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30235)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.SnapshotTestKit.expectNextPersisted(PersistenceTestKit.scala:318)
[30235](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30236)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.ExpectOps.expectNextPersisted(TestOps.scala:135)
[30236](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30237)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.ExpectOps.expectNextPersisted$(TestOps.scala:134)
[30237](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30238)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.SnapshotTestKit.expectNextPersisted(PersistenceTestKit.scala:336)
[30238](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30239)
[12-20 01:02:20.034] [info]   at akka.persistence.testkit.scaladsl.CommonSnapshotTests.$anonfun$$init$$36(CommonSnapshotTests.scala:555)
[30239](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30240)
[12-20 01:02:20.034] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[30240](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30241)
[12-20 01:02:20.034] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[30241](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30242)
[12-20 01:02:20.035] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[30242](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30243)
[12-20 01:02:20.035] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[30243](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30244)
[12-20 01:02:20.035] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[30244](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30245)
[12-20 01:02:20.035] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[30245](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30246)
[12-20 01:02:20.035] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[30246](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30247)
[12-20 01:02:20.035] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[30247](https://github.com/akka/akka/actions/runs/3736246858/jobs/6340346829#step:5:30248)
[12-20 01:02:20.035] [info]   at akka.persistence.testkit.scaladsl.SnapshotSerializeSpec.withFixture(SnapshotSerializeSpec.scala:13)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3745180846/jobs/6359338421#step:5:30706

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/3757683206/jobs/6385157677#step:5:1585

**Comment by johanandren** [comment]
Looks like this test was simply never deterministic, but something with the changes in sequencing the snapshot deletes in https://github.com/akka/akka/pull/31786 makes it fail consistently.
