### ISSUE TITLE
Fail: akka.stream.io.FileSinkSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31835]
https://github.com/akka/akka/actions/runs/4179274173/jobs/7239028718#step:5:18284

Seems similar to #31584 

```
[02-15 00:49:05.554] [info] - must allow overriding the dispatcher using Attributes *** FAILED *** (18 milliseconds)
[02-15 00:49:05.554] [info]   java.lang.AssertionError: Expected Actor[akka://FileSinkSpec/system/Materializers/StreamSupervisor-1876/flow-21-2-fileSink#752598869] to use dispatcher [akka.actor.default-dispatcher], yet used: [akka.stream.materializer.blocking-io-dispatcher]
[02-15 00:49:05.554] [info]   at akka.stream.testkit.Utils$.assertDispatcher(Utils.scala:26)
[02-15 00:49:05.554] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$27(FileSinkSpec.scala:190)
[02-15 00:49:05.554] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$27$adapted(FileSinkSpec.scala:180)
[02-15 00:49:05.554] [info]   at akka.stream.io.FileSinkSpec.targetFile(FileSinkSpec.scala:242)
[02-15 00:49:05.555] [info]   at akka.stream.io.FileSinkSpec.$anonfun$new$26(FileSinkSpec.scala:180)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4442797121/jobs/7799393340#step:5:18440

Could it be a "leak" from previous test, if that has not fully terminated the stream yet. Using same materializer and just looking for child "fileSink".

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/4452622920/jobs/7820419822#step:5:17394

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4506399211/jobs/7933128662#step:5:17589

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/4580165310/jobs/8088624593#step:5:17699

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5107107666/jobs/9179705910#step:5:18004

**Comment by He-Pin** [comment]
https://github.com/akka/akka/runs/15894197757

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/5861971593/job/15893013023#step:5:17943

**Comment by He-Pin** [comment]
https://github.com/akka/akka/actions/runs/5935609182/job/16094382250?pr=32053#step:5:5515

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9931758360/job/27432083762#step:5:18164

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9883249590/job/27297645642#step:5:18168

**Comment by johanandren** [comment]
I think this problem caused by multiple tests cases spawn streams but not waiting for the stream to complete before moving on, so a previous test case stream is seen in the next test, with the wrong dispatcher.

**Comment by johanandren** [comment]
Hmm, maybe not, we do have `assertNoChildren` in a fixture that should be used.
