### ISSUE TITLE
Failed: ReliableDeliveryShardingSpec:

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31870]
https://github.com/akka/akka/actions/runs/4338698262/jobs/7575589158

```
023-03-06T01:07:25.3759649Z <-- [[34makka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec: ReliableDelivery with sharding must illustrate sharding usage with several producers[0m] End of log messages of test that [Failed(org.scalatest.exceptions.TestFailedException: Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal Set("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1"))]
2023-03-06T01:07:25.3760888Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m- must illustrate sharding usage with several producers *** FAILED *** (4 seconds, 239 milliseconds)[0m[0m
2023-03-06T01:07:25.3761992Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  Set("p1-2-entity-1", "p2-2-entity-1", "p1-2-entity-2", "p2-2-entity-2") did not equal Set("p1-2-entity-2", "p1-2-entity-1", "p2-2-entity-2", "p1-2-entity-0", "p2-2-entity-0", "p2-2-entity-1") (ReliableDeliveryShardingSpec.scala:160)[0m[0m
2023-03-06T01:07:25.3762829Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  org.scalatest.exceptions.TestFailedException:[0m[0m
2023-03-06T01:07:25.3763553Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)[0m[0m
2023-03-06T01:07:25.3764357Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6951)[0m[0m
2023-03-06T01:07:25.3765290Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.$anonfun$new$6(ReliableDeliveryShardingSpec.scala:160)[0m[0m
2023-03-06T01:07:25.3766140Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m[0m
2023-03-06T01:07:25.3766798Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
2023-03-06T01:07:25.3767438Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
2023-03-06T01:07:25.3768081Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
2023-03-06T01:07:25.3768704Z [03-06 01:07:24.704] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
2023-03-06T01:07:25.3769333Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
2023-03-06T01:07:25.3770028Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)[0m[0m
2023-03-06T01:07:25.3770938Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)[0m[0m
2023-03-06T01:07:25.3771771Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)[0m[0m
2023-03-06T01:07:25.3772767Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.withFixture(ReliableDeliveryShardingSpec.scala:90)[0m[0m
2023-03-06T01:07:25.3773730Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)[0m[0m
2023-03-06T01:07:25.3774550Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)[0m[0m
2023-03-06T01:07:25.3775248Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)[0m[0m
2023-03-06T01:07:25.3775972Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)[0m[0m
2023-03-06T01:07:25.3776790Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)[0m[0m
2023-03-06T01:07:25.3777718Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.runTest(ReliableDeliveryShardingSpec.scala:90)[0m[0m
2023-03-06T01:07:25.3778647Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)[0m[0m
2023-03-06T01:07:25.3779373Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)[0m[0m
2023-03-06T01:07:25.3780038Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:431)[0m[0m
2023-03-06T01:07:25.3780717Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
2023-03-06T01:07:25.3781416Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)[0m[0m
2023-03-06T01:07:25.3782093Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)[0m[0m
2023-03-06T01:07:25.3782740Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:431)[0m[0m
2023-03-06T01:07:25.3783412Z [03-06 01:07:24.705] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)[0m[0m
2023-03-06T01:07:25.3784102Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)[0m[0m
2023-03-06T01:07:25.3784770Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)[0m[0m
2023-03-06T01:07:25.3785487Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)[0m[0m
2023-03-06T01:07:25.3786249Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)[0m[0m
2023-03-06T01:07:25.3787250Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.runTests(ReliableDeliveryShardingSpec.scala:90)[0m[0m
2023-03-06T01:07:25.3788066Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run(Suite.scala:1114)[0m[0m
2023-03-06T01:07:25.3788633Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run$(Suite.scala:1096)[0m[0m
2023-03-06T01:07:25.3789563Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:31)[0m[0m
2023-03-06T01:07:25.3790473Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m[0m
2023-03-06T01:07:25.3791203Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)[0m[0m
2023-03-06T01:07:25.3791886Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)[0m[0m
2023-03-06T01:07:25.3792878Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ReliableDeliveryShardingSpec.scala:90)[0m[0m
2023-03-06T01:07:25.3793829Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)[0m[0m
2023-03-06T01:07:25.3794579Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:535)[0m[0m
2023-03-06T01:07:25.3795300Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)[0m[0m
2023-03-06T01:07:25.3796029Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)[0m[0m
2023-03-06T01:07:25.3796920Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at akka.cluster.sharding.typed.delivery.ReliableDeliveryShardingSpec.run(ReliableDeliveryShardingSpec.scala:90)[0m[0m
2023-03-06T01:07:25.3797820Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)[0m[0m
2023-03-06T01:07:25.3798557Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:516)[0m[0m
2023-03-06T01:07:25.3799199Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)[0m[0m
2023-03-06T01:07:25.3799822Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.FutureTask.run(FutureTask.java:266)[0m[0m
2023-03-06T01:07:25.3800553Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m[0m
2023-03-06T01:07:25.3801413Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m[0m
2023-03-06T01:07:25.3802047Z [03-06 01:07:24.706] [0m[[0m[0minfo[0m] [0m[0m[31m  at java.lang.Thread.run(Thread.java:750)[0m[0m
2023-03-06T01:07:25.3802678Z [03-06 01:07:25.350] [0m[[0m[0minfo[0m] [0m[0m[32m- must reply to MessageWithConfirmation (635 milliseconds)[0m[0m
2023-03-06T01:07:25.9611058Z [03-06 01:07:25.960] [0m[[0m[0minfo[0m] [0m[0m[32m- must include demand information in RequestNext (609 milliseconds)[0m[0m
2023-03-06T01:07:25.9640333Z [03-06 01:07:25.963] [0m[[0m[0minfo[0m] [0m[0m[32m- must allow restart of producer (2 milliseconds)[0m[0m
2023-03-06T01:07:29.0125381Z [03-06 01:07:29.012] [0m[[0m[0minfo[0m] [0m[0m[32m- must deliver unconfirmed if ShardingConsumerController is terminated (3 seconds, 48 milliseconds)[0m[0m
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5897180541/job/15996393293
