### ISSUE TITLE
When I use apache flink1.12.2 version, the following akka error often occurs.

### ISSUE THREAD

**Issue by liuzhuang2017** [akka/akka#31881]
java.util.concurrent.TimeoutException: Remote system has been silent for too
long. (more than 48.0 hours)
at
akka.remote.ReliableDeliverySupervisor$$anonfun$idle$1.applyOrElse(Endpoint.scala:375)
at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
at akka.remote.ReliableDeliverySupervisor.aroundReceive(Endpoint.scala:203)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
at akka.actor.ActorCell.invoke(ActorCell.scala:495)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

---------------------------------------------------------------------------------------------------------------------------
I checked that 48 hours ago, there was indeed a process hang inside flink, and the flink job was restarted.How to deal with this? Is this a bug in akka?  Thank you !

**Comment by johanandren** [comment]
Seems like a quite old version of Flink (from 2016), I'd recommend start with upgrading to Flink a recent and see if there is any fix or dependency bump in Flink that sorts it.
