### ISSUE TITLE
Failed: RememberEntitiesStarterSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#31884]
https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27725

```
[03-15 00:58:35.700] [info] - must try start all entities in a throttled way with entity-recovery-strategy = constant *** FAILED *** (2 seconds, 61 milliseconds)
[27725](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27726)
[03-15 00:58:35.700] [info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(StartEntity(1),Actor[akka://RememberEntitiesStarterSpec/user/$d#142423395]) after 0 millis
[27726](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27727)
[03-15 00:58:35.700] [info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:752)
[27727](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27728)
[03-15 00:58:35.700] [info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:716)
[27728](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27729)
[03-15 00:58:35.700] [info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:715)
[27729](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27730)
[03-15 00:58:35.700] [info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:956)
[27730](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27731)
[03-15 00:58:35.700] [info]   at akka.cluster.sharding.internal.RememberEntitiesStarterSpec.$anonfun$new$8(RememberEntitiesStarterSpec.scala:179)
[27731](https://github.com/akka/akka/actions/runs/4421377403/jobs/7752102844#step:5:27732)
[03-15 00:58:35.700] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

**Comment by patriknw** [comment]
not exactly the same: https://github.com/akka/akka-core/actions/runs/28373477357/job/84057106903?pr=32938#step:7:3372
