### ISSUE TITLE
failed: HubSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31908]
BroadCastHub
```
[04-04 00:42:42.691] [info] - must broadcast all elements to all consumers with hot upstream even some subscriber unsubscribe *** FAILED *** (1 second, 19 milliseconds)
[04-04 00:42:42.691] [info]   Vector() was not equal to Range$Inclusive(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) (HubSpec.scala:341)
[04-04 00:42:42.691] [info]   Analysis:
[04-04 00:42:42.691] [info]   Vector0$(0: -> 1, 1: -> 2, 2: -> 3, 3: -> 4, 4: -> 5, 5: -> 6, 6: -> 7, 7: -> 8, 8: -> 9, 9: -> 10)
[04-04 00:42:42.691] [info]   org.scalatest.exceptions.TestFailedException:
[04-04 00:42:42.691] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:397)
[04-04 00:42:42.691] [info]   at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6781)
[04-04 00:42:42.691] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6829)
[04-04 00:42:42.691] [info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$32(HubSpec.scala:341)
```

https://github.com/akka/akka/actions/runs/4602517126/jobs/8131560641#step:5:16468

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/4856177177/jobs/8655457782#step:5:16462
