### ISSUE TITLE
failed: LoggerSourceTest

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31909]
```
[04-11 00:58:23.678] [info] - verifyLogging *** FAILED ***
[04-11 00:58:23.678] [info]   java.lang.AssertionError: Received 1 excess messages on LoggingTestKitImpl(1,Some(INFO),None,None,Some(event-received),None,None,Map(persistencePhase -> running-cmd, persistenceId -> 1),true,Some(akka.persistence.typed.javadsl.LoggerSourceTest$$Lambda$568/1018670363@583e4f31)).
[04-11 00:58:23.679] [info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:105)
[04-11 00:58:23.679] [info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:114)
[04-11 00:58:23.679] [info]   at akka.persistence.typed.javadsl.LoggerSourceTest.verifyLogging(LoggerSourceTest.java:145)
```

https://github.com/akka/akka/actions/runs/4662428070/jobs/8252760680#step:5:29723

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/4662428070/jobs/8252760680#step:5:29723

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14918611071/job/41909572730#step:5:29579

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/17567734077/job/49897895816#step:5:29934

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/18209038347/job/51845812478#step:5:27382

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/19414355127/job/55540369249#step:7:30031

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/22163227288/job/64084658857#step:7:30569

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/27658048425/job/81796378340#step:7:29795
