### ISSUE TITLE
failed: ShardedDaemonProcessRescaleSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#31911]
https://github.com/akka/akka/actions/runs/4695664510/jobs/8325031285

```
2023-04-14T03:57:13.2206066Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m- must rescale to 2 workers (on node 'second', class akka.cluster.sharding.typed.ShardedDaemonProcessRescaleMultiJvmNode2) *** FAILED *** (17 milliseconds)[0m[0m
2023-04-14T03:57:13.2207130Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  java.lang.AssertionError: expected Success(Done), found Error(Rescale in progress, retry later)[0m[0m
2023-04-14T03:57:13.2208348Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)[0m[0m
2023-04-14T03:57:13.2209400Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:170)[0m[0m
2023-04-14T03:57:13.2210623Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:151)[0m[0m
2023-04-14T03:57:13.2211758Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.typed.ShardedDaemonProcessRescaleSpec.$anonfun$new$12(ShardedDaemonProcessRescaleSpec.scala:128)[0m[0m
2023-04-14T03:57:13.2212846Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:412)[0m[0m
2023-04-14T03:57:13.2213942Z [0m[[0m[0minfo[0m] [0m[0m[[34mJVM-2[0m] [31m  at akka.cluster.sharding.typed.ShardedDaemonProcessRescaleSpec.$anonfun$new$11(ShardedDaemonProcessRescaleSpec.scala:125)[0m[0m
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5041099754/jobs/9040480008

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5757665599/job/15609041930
