### ISSUE TITLE
Fail: LateConnectSpec - Connection must be established after initial lazy restart

### ISSUE THREAD

**Issue by octonato** [akka/akka#31920]
https://github.com/akka/akka/actions/runs/4769814426/jobs/8480508098#step:5:12903

```scala
[04-22 00:34:51.839] [info] - must be established after initial lazy restart *** FAILED *** (24 seconds, 70 milliseconds)
[04-22 00:34:51.840] [info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg while waiting for ping2
[04-22 00:34:51.840] [info]   at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
[04-22 00:34:51.841] [info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:461)
[04-22 00:34:51.841] [info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:447)
[04-22 00:34:51.842] [info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:159)
[04-22 00:34:51.842] [info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:956)
[04-22 00:34:51.842] [info]   at akka.remote.artery.LateConnectSpec.f$proxy1$1(LateConnectSpec.scala:49)
[04-22 00:34:51.843] [info]   at akka.remote.artery.LateConnectSpec.$init$$$anonfun$1$$anonfun$1(LateConnectSpec.scala:34)
[04-22 00:34:51.843] [info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[04-22 00:34:51.844] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[04-22 00:34:51.844] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[04-22 00:34:51.845] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[04-22 00:34:51.845] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[04-22 00:34:51.846] [info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[04-22 00:34:51.846] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1105)
[04-22 00:34:51.848] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[04-22 00:34:51.850] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:138)
[04-22 00:34:51.851] [info]   at akka.testkit.AkkaSpec.withFixture(AkkaSpec.scala:54)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/6751394995/job/18355398033#step:5:12433

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16557091628/job/46820143453#step:5:11228

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/16952485086/job/48048019543#step:5:12804

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/18298075399/job/52100473346#step:5:12680

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/21379262384/job/61542434824#step:7:12937

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/31285735823/job/93174079240#step:6:12799
https://github.com/akka/akka-core/actions/runs/31445391540/job/93638373420#step:6:12649

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/33030044819/job/98380218614#step:6:12644
