### ISSUE TITLE
possible incorrect jnr-ffi version in Akka 2.8.2

### ISSUE THREAD

**Issue by Zhen-hao** [akka/akka#31943]
hi Akka team, 

I don't have an easy way to make a reproducible example. Feel free to close this one if you think it is not an issue. 

With Akka 2.8.2, I have the following runtime error:

```
[info] [2023-05-18 14:08:37,358] [ERROR] [akka.actor.ActorSystemImpl] [SECURITY] [nt-ui-akka.actor.default-dispatcher-27] - Uncaught error from thread [nt-ui-akka.cluster.distributed-data.durable.pinned-store-35]: 'com.kenai.jffi.CallContext com.kenai.jffi.CallContextCache.getCallContext(com.kenai.jffi.Type, int, com.kenai.jffi.Type[], com.kenai.jffi.CallingConvention, boolean)', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[nt-ui] {akkaAddress=akka://nt-ui@127.0.0.1:2551, akkaUid=-1592212477611512617, sourceThread=nt-ui-akka.cluster.distributed-data.durable.pinned-store-35, akkaSource=akka.actor.ActorSystemImpl(nt-ui), sourceActorSystem=nt-ui, akkaTimestamp=12:08:37.357UTC}
[info] java.lang.NoSuchMethodError: 'com.kenai.jffi.CallContext com.kenai.jffi.CallContextCache.getCallContext(com.kenai.jffi.Type, int, com.kenai.jffi.Type[], com.kenai.jffi.CallingConvention, boolean)'
[info]  at jnr.ffi.provider.jffi.InvokerUtil.getCallContext(InvokerUtil.java:206)
[info]  at jnr.ffi.provider.jffi.InvokerUtil.getCallContext(InvokerUtil.java:192)
[info]  at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:154)
[info]  at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:87)
[info]  at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
[info]  at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)
[info]  at jnr.ffi.LibraryLoader.load(LibraryLoader.java:399)
[info]  at org.lmdbjava.Library.<clinit>(Library.java:125)
[info]  at org.lmdbjava.Env$Builder.open(Env.java:521)
[info]  at org.lmdbjava.Env$Builder.open(Env.java:547)
[info]  at akka.cluster.ddata.LmdbDurableStore.akka$cluster$ddata$LmdbDurableStore$$lmdb(DurableStore.scala:155)
[info]  at akka.cluster.ddata.LmdbDurableStore$$anonfun$init$1.applyOrElse(DurableStore.scala:211)
[info]  at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info]  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info]  at akka.cluster.ddata.LmdbDurableStore.aroundReceive(DurableStore.scala:122)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[info]  at java.base/java.lang.Thread.run(Thread.java:1589)
```

Override the `jnr-ffi` dependency with version "2.1.9" got rid of this error.

**Comment by patriknw** [comment]
Thanks for reporting. We have tests that run successfully with the dependency so would be good to know more about what other dependencies you have and when you see it.

Maybe you can share dependency-tree of your project?

For Akka it looks like:

```
[info]   | +-org.lmdbjava:lmdbjava:0.8.3
[info]   |   +-com.github.jnr:jnr-constants:0.10.4
[info]   |   +-com.github.jnr:jnr-ffi:2.2.13
[info]   |     +-com.github.jnr:jffi:1.3.10
[info]   |     +-com.github.jnr:jnr-a64asm:1.0.0
[info]   |     +-com.github.jnr:jnr-x86asm:1.0.2
[info]   |     +-org.ow2.asm:asm-analysis:9.2
[info]   |     | +-org.ow2.asm:asm-tree:9.2
[info]   |     |   +-org.ow2.asm:asm:9.2
[info]   |     |
[info]   |     +-org.ow2.asm:asm-commons:9.2
[info]   |     | +-org.ow2.asm:asm-analysis:9.2
[info]   |     | | +-org.ow2.asm:asm-tree:9.2
[info]   |     | |   +-org.ow2.asm:asm:9.2
[info]   |     | |
[info]   |     | +-org.ow2.asm:asm-tree:9.2
[info]   |     | | +-org.ow2.asm:asm:9.2
[info]   |     | |
[info]   |     | +-org.ow2.asm:asm:9.2
[info]   |     |
[info]   |     +-org.ow2.asm:asm-tree:9.2
[info]   |     | +-org.ow2.asm:asm:9.2
[info]   |     |
[info]   |     +-org.ow2.asm:asm-util:9.2
[info]   |     | +-org.ow2.asm:asm-analysis:9.2
[info]   |     | | +-org.ow2.asm:asm-tree:9.2
[info]   |     | |   +-org.ow2.asm:asm:9.2
[info]   |     | |
[info]   |     | +-org.ow2.asm:asm-tree:9.2
[info]   |     | | +-org.ow2.asm:asm:9.2
[info]   |     | |
[info]   |     | +-org.ow2.asm:asm:9.2
[info]   |     |
[info]   |     +-org.ow2.asm:asm:9.2
```

> I don't have an easy way to make a reproducible example.

Does that mean that it doesn't happen every time or that you can't share the full application and can't minimize it into a smaller example?

**Comment by Zhen-hao** [comment]
> Does that mean that it doesn't happen every time or that you can't share the full application and can't minimize it into a smaller example?

It is always reproducible but I have a lot of dependencies in my project. It would take too much time. At least I have the workaround of using a lower version of `jnr-ffi`. 

Here is my `dependency-tree` related to `jnr-ffi`:

```

+-com.lightbend.akka.management:akka-management-cluster-http_2.13:1.4.0
| ...
| +-com.typesafe.akka:akka-cluster-sharding_2.13:2.8.2 [S]
| | ...  
| | +-com.typesafe.akka:akka-cluster_2.13:2.8.2 [S]
| | | ...
| | | +-org.lmdbjava:lmdbjava:0.8.3
| | |   +-com.github.jnr:jnr-constants:0.10.4
| | |   +-com.github.jnr:jnr-ffi:2.2.13
| | |     +-com.github.jnr:jffi:1.2.19
| | |     +-com.github.jnr:jnr-a64asm:1.0.0
| | |     +-com.github.jnr:jnr-x86asm:1.0.2
| | |     +-org.ow2.asm:asm-analysis:9.2
| | |     | +-org.ow2.asm:asm-tree:9.2
| | |     |   +-org.ow2.asm:asm:9.2
| | |     |   
+-com.lightbend.akka:akka-projection-cassandra_2.13:1.4.0 [S]
| ...
| +-com.lightbend.akka:akka-stream-alpakka-cassandra_2.13:6.0.1 [S]
| | +-com.datastax.oss:java-driver-core:4.14.1
| | | ...
| | | +-com.github.jnr:jnr-posix:3.1.15
| | | | +-com.github.jnr:jnr-constants:0.10.4
| | | | +-com.github.jnr:jnr-ffi:2.2.11 (evicted by: 2.2.13)
| | | | +-com.github.jnr:jnr-ffi:2.2.13
| | | |   +-com.github.jnr:jffi:1.2.19
| | | |   +-com.github.jnr:jnr-a64asm:1.0.0
| | | |   +-com.github.jnr:jnr-x86asm:1.0.2
| | | |   +-org.ow2.asm:asm-analysis:9.2
| | | |   | +-org.ow2.asm:asm-tree:9.2
| | | |   |   +-org.ow2.asm:asm:9.2
| ...
+-com.lightbend.akka:akka-stream-alpakka-cassandra_2.13:6.0.1 [S]
| +-com.datastax.oss:java-driver-core:4.14.1
| | ...
| | +-com.github.jnr:jnr-posix:3.1.15
| | | +-com.github.jnr:jnr-constants:0.10.4
| | | +-com.github.jnr:jnr-ffi:2.2.11 (evicted by: 2.2.13)
| | | +-com.github.jnr:jnr-ffi:2.2.13
| | |   +-com.github.jnr:jffi:1.2.19
| | |   +-com.github.jnr:jnr-a64asm:1.0.0
| | |   +-com.github.jnr:jnr-x86asm:1.0.2
| | |   +-org.ow2.asm:asm-analysis:9.2
| | |   | +-org.ow2.asm:asm-tree:9.2
| | |   |   +-org.ow2.asm:asm:9.2
| ...
+-com.typesafe.akka:akka-cluster-sharding-typed_2.13:2.8.2 [S]
| | ...
| +-com.typesafe.akka:akka-cluster-sharding_2.13:2.8.2 [S]
| | | ...
| | +-com.typesafe.akka:akka-distributed-data_2.13:2.8.2 [S]
| | | ...  
| | | +-org.lmdbjava:lmdbjava:0.8.3
| | |   +-com.github.jnr:jnr-constants:0.10.4
| | |   +-com.github.jnr:jnr-ffi:2.2.13
| | |     +-com.github.jnr:jffi:1.2.19
| | |     +-com.github.jnr:jnr-a64asm:1.0.0
| | |     +-com.github.jnr:jnr-x86asm:1.0.2
| | |     +-org.ow2.asm:asm-analysis:9.2
| | |     | +-org.ow2.asm:asm-tree:9.2
| | |     |   +-org.ow2.asm:asm:9.2
| ...
| +-com.typesafe.akka:akka-cluster-typed_2.13:2.8.2 [S]
| | ...
| | +-com.typesafe.akka:akka-distributed-data_2.13:2.8.2 [S]   
| |   +-org.lmdbjava:lmdbjava:0.8.3
| |     +-com.github.jnr:jnr-constants:0.10.4
| |     +-com.github.jnr:jnr-ffi:2.2.13
| |       +-com.github.jnr:jffi:1.2.19
| |       +-com.github.jnr:jnr-a64asm:1.0.0
| |       +-com.github.jnr:jnr-x86asm:1.0.2
| |       +-org.ow2.asm:asm-analysis:9.2
| |       | +-org.ow2.asm:asm-tree:9.2
| |       |   +-org.ow2.asm:asm:9.2
...    
+-com.typesafe.akka:akka-cluster-typed_2.13:2.8.2 [S]
| ...
| +-com.typesafe.akka:akka-distributed-data_2.13:2.8.2 [S]
|   ...  
|   +-org.lmdbjava:lmdbjava:0.8.3
|     +-com.github.jnr:jnr-constants:0.10.4
|     +-com.github.jnr:jnr-ffi:2.2.13
|       +-com.github.jnr:jffi:1.2.19
|       +-com.github.jnr:jnr-a64asm:1.0.0
|       +-com.github.jnr:jnr-x86asm:1.0.2
|       +-org.ow2.asm:asm-analysis:9.2
|       | +-org.ow2.asm:asm-tree:9.2
|       |   +-org.ow2.asm:asm:9.2
...
+-com.typesafe.akka:akka-persistence-cassandra_2.13:1.1.1 [S]
| +-com.datastax.oss:java-driver-core:4.14.1
| | ...
| | +-com.github.jnr:jnr-posix:3.1.15
| | | +-com.github.jnr:jnr-constants:0.10.4
| | | +-com.github.jnr:jnr-ffi:2.2.11 (evicted by: 2.2.13)
| | | +-com.github.jnr:jnr-ffi:2.2.13
| | |   +-com.github.jnr:jffi:1.2.19
| | |   +-com.github.jnr:jnr-a64asm:1.0.0
| | |   +-com.github.jnr:jnr-x86asm:1.0.2
| | |   +-org.ow2.asm:asm-analysis:9.2
| | |   | +-org.ow2.asm:asm-tree:9.2
| | |   |   +-org.ow2.asm:asm:9.2
...
| +-com.lightbend.akka:akka-stream-alpakka-cassandra_2.13:6.0.1 [S]
| | +-com.datastax.oss:java-driver-core:4.14.1
| | | ...
| | | | 
| | | +-com.github.jnr:jnr-posix:3.1.15
| | | | +-com.github.jnr:jnr-constants:0.10.4
| | | | +-com.github.jnr:jnr-ffi:2.2.11 (evicted by: 2.2.13)
| | | | +-com.github.jnr:jnr-ffi:2.2.13
| | | |   +-com.github.jnr:jffi:1.2.19
| | | |   +-com.github.jnr:jnr-a64asm:1.0.0
| | | |   +-com.github.jnr:jnr-x86asm:1.0.2
| | | |   +-org.ow2.asm:asm-analysis:9.2
| | | |   | +-org.ow2.asm:asm-tree:9.2
| | | |   |   +-org.ow2.asm:asm:9.2
| | | |   ...  
```

**Comment by patriknw** [comment]
Thanks, I can see that there is a different `com.github.jnr:jffi`
In Akka:
```
com.github.jnr:jffi:1.3.10
```
In your project with the Cassandra dependency:
```
com.github.jnr:jffi:1.2.19
```

We should probably update the Cassandra driver dependency soon, and then it might (I don't know) come with later jnr dependencies that aligns better. Anyway, just reporting this so that others can find it is very useful.

**Comment by He-Pin** [comment]
@Zhen-hao You can use Arthas  `sc` to get the runtime class info.
