### ISSUE TITLE
Failed: LeaseMajority5NodeSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32009]
https://github.com/akka/akka/actions/runs/5459886326/jobs/9936318139#step:10:6066

```
[info] [JVM-4] - should keep the side that can acquire the lease (on node 'node4', class akka.cluster.sbr.LeaseMajority5NodeSpecMultiJvmNode4) *** FAILED *** (13 seconds, 119 milliseconds)
[info] [JVM-4]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsgClass waiting for class akka.coordination.lease.TestLease$AcquireReq
[info] [JVM-4]   at scala.Predef$.assert(Predef.scala:279)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:570)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:542)
[info] [JVM-4]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:541)
[info] [JVM-4]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:955)
[info] [JVM-4]   at akka.cluster.sbr.LeaseMajority5NodeSpec.$anonfun$new$21(LeaseMajority5NodeSpec.scala:148)
[info] [JVM-4]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:414)
[info] [JVM-4]   at akka.cluster.sbr.LeaseMajority5NodeSpec.$anonfun$new$19(LeaseMajority5NodeSpec.scala:148)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5549828711/job/15033388563#step:10:6021

```scala
[info] [JVM-1] - should keep the side that can acquire the lease (on node 'node1', class akka.cluster.sbr.LeaseMajority5NodeSpecMultiJvmNode1) *** FAILED *** (4 seconds, 273 milliseconds)
[info] [JVM-1]   java.lang.AssertionError: assertion failed: expected class akka.coordination.lease.TestLease$ReleaseReq, found class akka.coordination.lease.TestLease$AcquireReq (AcquireReq(LeaseMajority5NodeSpec@test-node1:6000))
[info] [JVM-1]   at scala.Predef$.assert(Predef.scala:279)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:552)
[info] [JVM-1]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:551)
[info] [JVM-1]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:955)
[info] [JVM-1]   at akka.cluster.sbr.LeaseMajority5NodeSpec.$anonfun$new$17(LeaseMajority5NodeSpec.scala:139)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:414)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5804096385/job/15733161585

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/5828150200/job/15805340526

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/5851050126/job/15861266105#step:10:5981

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6116845404/job/16602610256#step:10:6283

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6346373095/job/17239773121#step:10:6486

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6375118218/job/17300501922#step:10:6641

**Comment by johanandren** [comment]
Huh, not very frequent before this, but failing the last three nightlies (I don't think anything related changed).

https://github.com/akka/akka/actions/runs/6400706109/job/17374685045#step:10:6475

**Comment by johanandren** [comment]
(Aeron UDP)
https://github.com/akka/akka/actions/runs/6477099549/job/17586766256#step:10:6556

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6899001768/job/18769897045#step:10:6474

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6951995128/job/18914864777#step:10:6582

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6999744856/job/19039432042#step:10:6453

**Comment by patriknw** [comment]
Probably fixed by https://github.com/akka/akka/pull/32242
