### ISSUE TITLE
Failed: SplitBrainWithAccrualFailureDetector - must detect network partition and mark nodes on other side as unreachable and form new cluster

### ISSUE THREAD

**Issue by octonato** [akka/akka#32011]
https://github.com/akka/akka/actions/runs/5482102344/jobs/9987102179#step:10:21963

```scala
[info] [JVM-2] - must detect network partition and mark nodes on other side as unreachable and form new cluster (on node 'second', class akka.cluster.SplitBrainWithAccrualFailureDetectorMultiJvmNode2) *** FAILED *** (49 seconds, 999 milliseconds)
[info] [JVM-2]   0 did not equal 2 (MultiNodeClusterSpec.scala:306)
[info] [JVM-2]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-2]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info] [JVM-2]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7469)
[info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$5(MultiNodeClusterSpec.scala:306)
[info] [JVM-2]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:331)
[info] [JVM-2]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:348)
[info] [JVM-2]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:320)
[info] [JVM-2]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:955)
[info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$1(MultiNodeClusterSpec.scala:306)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:417)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:405)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:432)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:432)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.awaitMembersUp(MultiNodeClusterSpec.scala:303)
[info] [JVM-2]   at akka.cluster.SplitBrainSpec.$anonfun$new$8(SplitBrainSpec.scala:83)
[info] [JVM-2]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:414)
[info] [JVM-2]   at akka.cluster.SplitBrainSpec.$anonfun$new$4(SplitBrainSpec.scala:80)
[info] [JVM-2]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:417)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:405)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:432)
[info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:432)
[info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-2]   at akka.cluster.SplitBrainSpec.$anonfun$new$3(SplitBrainSpec.scala:69)
[info] [JVM-2]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-2]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info] [JVM-2]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info] [JVM-2]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/5617888065/job/15222639984#step:10:21447

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/5851050126/job/15861266105#step:10:20987

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6044589550/job/16403381058

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6269260723/job/17025418649
