### ISSUE TITLE
failed: Multi Node Test Nonzero exit value

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32038]
https://github.com/akka/akka/actions/runs/5851050126/job/15861265964

Note that this is before the Netty 4 migration.

```
2023-08-14T03:10:17.9220167Z [0m[[0m[31merror[0m] [0m[0mjava.lang.RuntimeException: Nonzero exit value: 1[0m
2023-08-14T03:10:17.9221019Z [0m[[0m[31merror[0m] [0m[0m	at scala.sys.package$.error(package.scala:30)[0m
2023-08-14T03:10:17.9222257Z [0m[[0m[31merror[0m] [0m[0m	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:138)[0m
2023-08-14T03:10:17.9223932Z [0m[[0m[31merror[0m] [0m[0m	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:108)[0m
2023-08-14T03:10:17.9224963Z [0m[[0m[31merror[0m] [0m[0m	at com.typesafe.sbt.multijvm.Jvm$.getPodName(Jvm.scala:50)[0m
2023-08-14T03:10:17.9225959Z [0m[[0m[31merror[0m] [0m[0m	at com.typesafe.sbt.multijvm.Jvm$.syncJar(Jvm.scala:56)[0m
2023-08-14T03:10:17.9226889Z [0m[[0m[31merror[0m] [0m[0m	at com.typesafe.sbt.MultiJvmPlugin$.$anonfun$multiNode$3(SbtMultiJvm.scala:490)[0m
```

**Comment by johanandren** [comment]
Also in the logs:

```
Run gcloud container clusters delete "akka-multi-node-$***GITHUB_RUN_ID***" --quiet
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - ResponseError: code=400, message=Operation operation-1692155995629-76c0bd5d-5885-4271-8442-17d9eea82c51 is currently repairing cluster akka-multi-node-5873846885. Please wait and try again once it is done.
```

**Comment by johanandren** [comment]
One more thing, also k8 related: 
```
[error] Error from server: error dialing backend: No agent available
``

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/5897995634/job/15998389252
