### ISSUE TITLE
Failed: DownAllIndirectlyConnected5NodeSpec

### ISSUE THREAD

**Issue by pvlugter** [akka/akka#32036]
https://github.com/akka/akka/actions/runs/5851050126/job/15861266105#step:10:22693

```
[info] [JVM-1] - should down all when indirectly connected combined with clean partition (on node 'node1', class akka.cluster.sbr.DownAllIndirectlyConnected5NodeSpecMultiJvmNode1) *** FAILED *** (49 seconds, 945 milliseconds)
[info] [JVM-1]   TreeSet() did not equal Set(akka://DownAllIndirectlyConnected5NodeSpec@test-node1:6000) (DownAllIndirectlyConnected5NodeSpec.scala:107)
[info] [JVM-1]   org.scalatest.exceptions.TestFailedException:
[info] [JVM-1]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info] [JVM-1]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7469)
[info] [JVM-1]   at akka.cluster.sbr.DownAllIndirectlyConnected5NodeSpec.$anonfun$new$28(DownAllIndirectlyConnected5NodeSpec.scala:107)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-1]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:331)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:348)
[info] [JVM-1]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:320)
[info] [JVM-1]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:955)
[info] [JVM-1]   at akka.cluster.sbr.DownAllIndirectlyConnected5NodeSpec.$anonfun$new$27(DownAllIndirectlyConnected5NodeSpec.scala:106)
[info] [JVM-1]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:417)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:405)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-1]   at akka.testkit.TestKitBase.within(TestKit.scala:432)
[info] [JVM-1]   at akka.testkit.TestKitBase.within$(TestKit.scala:432)
[info] [JVM-1]   at akka.testkit.TestKit.within(TestKit.scala:955)
[info] [JVM-1]   at akka.cluster.sbr.DownAllIndirectlyConnected5NodeSpec.$anonfun$new$26(DownAllIndirectlyConnected5NodeSpec.scala:106)
[info] [JVM-1]   at akka.remote.testkit.MultiNodeSpec.runOn(MultiNodeSpec.scala:414)
[info] [JVM-1]   at akka.cluster.sbr.DownAllIndirectlyConnected5NodeSpec.$anonfun$new$2(DownAllIndirectlyConnected5NodeSpec.scala:105)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6924656445/job/18834177298

**Comment by patriknw** [comment]
Probably fixed by https://github.com/akka/akka/pull/32242
