### ISSUE TITLE
failed: LeaderDowningAllOtherNodes

### ISSUE THREAD

**Issue by octonato** [akka/akka#32096]
https://github.com/akka/akka/actions/runs/6141065748/job/16660822120

```scala
023-09-11T03:20:09.4937015Z [info] [JVM-2] - must setup (on node 'second', class akka.cluster.LeaderDowningAllOtherNodesMultiJvmNode2) *** FAILED *** (50 seconds, 10 milliseconds)
2023-09-11T03:20:09.4938780Z [info] [JVM-2]   1 did not equal 6 (MultiNodeClusterSpec.scala:306)
2023-09-11T03:20:09.4960457Z [info] [JVM-2]   org.scalatest.exceptions.TestFailedException:
2023-09-11T03:20:09.4963450Z [info] [JVM-2]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
2023-09-11T03:20:09.4964788Z [info] [JVM-2]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7469)
2023-09-11T03:20:09.4966092Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$5(MultiNodeClusterSpec.scala:306)
2023-09-11T03:20:09.4967439Z [info] [JVM-2]   at akka.testkit.TestKitBase.poll$2(TestKit.scala:331)
2023-09-11T03:20:09.4968447Z [info] [JVM-2]   at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:348)
2023-09-11T03:20:09.4969490Z [info] [JVM-2]   at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:320)
2023-09-11T03:20:09.4970498Z [info] [JVM-2]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:955)
2023-09-11T03:20:09.4971724Z [info] [JVM-2]   at akka.cluster.MultiNodeClusterSpec.$anonfun$awaitMembersUp$1(MultiNodeClusterSpec.scala:306)
2023-09-11T03:20:09.4972831Z [info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:417)
2023-09-11T03:20:09.4973893Z [info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:405)
2023-09-11T03:20:09.4974866Z [info] [JVM-2]   at akka.testkit.TestKit.within(TestKit.scala:955)
2023-09-11T03:20:09.4975818Z [info] [JVM-2]   at akka.testkit.TestKitBase.within(TestKit.scala:432)
2023-09-11T03:20:09.4976777Z [info] [JVM-2]   at akka.testkit.TestKitBase.within$(TestKit.scala:432)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6607863798/job/17945773867
