### ISSUE TITLE
Failed: ClusterSingletonManagerSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32098]
https://github.com/akka/akka/actions/runs/6167095988/job/16737547153#step:10:33912

```
[info] [JVM-6] - must startup 6 node cluster (on node 'fourth', class akka.cluster.singleton.ClusterSingletonManagerMultiJvmNode6) *** FAILED ***
[info] [JVM-6]   java.lang.AssertionError: assertion failed: timeout (2 seconds) during expectMsg while waiting for Pong
[info] [JVM-6]   at scala.Predef$.assert(Predef.scala:279)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:460)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:446)
[info] [JVM-6]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:446)
[info] [JVM-6]   at akka.testkit.TestKit.expectMsg(TestKit.scala:955)
[info] [JVM-6]   at akka.cluster.singleton.ClusterSingletonManagerSpec.$anonfun$verifyProxyMsg$3(ClusterSingletonManagerSpec.scala:264)
```

**Comment by johanandren** [comment]
(Aeron)

https://github.com/akka/akka/actions/runs/6294029708/job/17085292840#step:10:31157

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6844817881/job/18609153800#step:10:30310

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/6872046806/job/18689873104#step:10:1678
