### ISSUE TITLE
failed: LineNumberSpec (jdk 17)

### ISSUE THREAD

**Issue by octonato** [akka/akka#32105]
https://github.com/akka/akka/actions/runs/6203959191/job/16845381696#step:5:3573

```scala

[09-16 00:19:36.028] [info]   - must work for larger functions *** FAILED *** (3 milliseconds)
[09-16 00:19:36.034] [info]     LineNumberSpecCodeForScala.scala:16-17 did not equal LineNumberSpecCodeForScala.scala:15-17 (LineNumberSpec.scala:23)
[09-16 00:19:36.034] [info]     org.scalatest.exceptions.TestFailedException:
[09-16 00:19:36.034] [info]     at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[09-16 00:19:36.034] [info]     at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6956)
[09-16 00:19:36.034] [info]     at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[09-16 00:19:36.034] [info]     at akka.testkit.AkkaSpec.should(AkkaSpec.scala:54)
[09-16 00:19:36.034] [info]     at akka.util.LineNumberSpec.f$proxy2$1(LineNumberSpec.scala:23)
[09-16 00:19:36.034] [info]     at akka.util.LineNumberSpec.f$proxy8$1$$anonfun$1$$anonfun$2(LineNumberSpec.scala:21)
[09-16 00:19:36.034] [info]     at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[09-16 00:19:36.034] [info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[09-16 00:19:36.034] [info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[09-16 00:19:36.034] [info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[09-16 00:19:36.034] [info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[09-16 00:19:36.034] [info]     at org.scalatest.Transformer.apply(Transformer.scala:21)
```

and also 
https://github.com/akka/akka/actions/runs/6203959191/job/16845381696#step:5:3641

```scala
[3640](https://github.com/akka/akka/actions/runs/6203959191/job/16845381696#step:5:3641)
[09-16 00:19:36.045] [info]   - must work for `def` *** FAILED *** (1 millisecond)
[09-16 00:19:36.045] [info]     LineNumberSpecCodeForScala.scala:26-27 did not equal LineNumberSpecCodeForScala.scala:25-27 (LineNumberSpec.scala:32)
[09-16 00:19:36.045] [info]     org.scalatest.exceptions.TestFailedException:
[09-16 00:19:36.045] [info]     at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[09-16 00:19:36.045] [info]     at org.scalatest.matchers.should.Matchers.should(Matchers.scala:6956)
[09-16 00:19:36.045] [info]     at org.scalatest.matchers.should.Matchers.should$(Matchers.scala:1808)
[09-16 00:19:36.045] [info]     at akka.testkit.AkkaSpec.should(AkkaSpec.scala:54)
[09-16 00:19:36.045] [info]     at akka.util.LineNumberSpec.f$proxy4$1(LineNumberSpec.scala:32)
[09-16 00:19:36.045] [info]     at akka.util.LineNumberSpec.f$proxy8$1$$anonfun$1$$anonfun$4(LineNumberSpec.scala:30)
[09-16 00:19:36.045] [info]     at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[09-16 00:19:36.045] [info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by octonato** [comment]
I'm doubled surprised by this. I didn't know we had such a think in Akka. 

Also surprised that this is now failing. Doesn't seem to be a test sensible to time or concurrency issue. Should not be flaky.

**Comment by octonato** [comment]
Definitely not flaky. Failing consistently it seems. 

https://github.com/akka/akka/actions/runs/6210348929/job/16858468475#step:5:3545
https://github.com/akka/akka/actions/runs/6216636455/job/16870715708#step:5:3375

Something got updated and we didn't notice it breaking. Path JDK version in CI?

**Comment by octonato** [comment]
I guess it's a combination of JDK 17 and Scala 3.3.1. And the job is not run on the PR, but only nightly. So we didn't catch it.
