### ISSUE TITLE
failed: SupervisorSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32128]
Strange, this is not looking good

https://github.com/akka/akka/actions/runs/6273505512/job/17037092542?pr=32127#step:5:1771

```
Uncaught error from thread [SupervisorSpec-akka.actor.default-dispatcher-6]: Update to non-static final field akka.actor.SupervisorSpec$$anon$1.context attempted from a different method (akka$actor$Actor$_setter_$context_$eq) than the initializer method <init> , shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[SupervisorSpec]
java.lang.IllegalAccessError: Update to non-static final field akka.actor.SupervisorSpec$$anon$1.context attempted from a different method (akka$actor$Actor$_setter_$context_$eq) than the initializer method <init> 
	at akka.actor.SupervisorSpec$$anon$1.akka$actor$Actor$_setter_$context_$eq(SupervisorSpec.scala:222)
	at akka.actor.Actor.$init$(Actor.scala:495)
	at akka.actor.SupervisorSpec$$anon$1.<init>(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec.childInstance$lzycompute$1(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec.akka$actor$SupervisorSpec$$childInstance$1(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec$$anon$2.$anonfun$child$1(SupervisorSpec.scala:242)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:615)
	at akka.actor.ActorCell.create(ActorCell.scala:642)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
Error:  [SECURITY][09/22/2023 11:18:20.658] [SupervisorSpec-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(SupervisorSpec)] Uncaught error from thread [SupervisorSpec-akka.actor.default-dispatcher-6]: Update to non-static final field akka.actor.SupervisorSpec$$anon$1.context attempted from a different method (akka$actor$Actor$_setter_$context_$eq) than the initializer method <init> , shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[SupervisorSpec]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
java.lang.IllegalAccessError: Update to non-static final field akka.actor.SupervisorSpec$$anon$1.context attempted from a different method (akka$actor$Actor$_setter_$context_$eq) than the initializer method <init> 
	at akka.actor.SupervisorSpec$$anon$1.akka$actor$Actor$_setter_$context_$eq(SupervisorSpec.scala:222)
	at akka.actor.Actor.$init$(Actor.scala:495)
	at akka.actor.SupervisorSpec$$anon$1.<init>(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec.childInstance$lzycompute$1(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec.akka$actor$SupervisorSpec$$childInstance$1(SupervisorSpec.scala:222)
	at akka.actor.SupervisorSpec$$anon$2.$anonfun$child$1(SupervisorSpec.scala:242)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:615)
	at akka.actor.ActorCell.create(ActorCell.scala:642)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by patriknw** [comment]
ok, so it has to do with the jdk 11 target

**Comment by pvlugter** [comment]
It's this Scala issue: https://github.com/scala/scala-dev/issues/408. Follow-up for anonymous class covered by https://github.com/scala/bug/issues/12340. In this case it's anonymous and lazy val. Could work around for now by not using anonymous child actor class:

```scala
class Child extends Actor {
  ...
}
lazy val childInstance = new Child
```

**Comment by pvlugter** [comment]
Reported as Scala bug: https://github.com/scala/bug/issues/12881

**Comment by patriknw** [comment]
thanks
