### ISSUE TITLE
Failed: RemoteConnectionSpec (aeron udp)

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32169]
https://github.com/akka/akka/actions/runs/6476201087/job/17584535393#step:5:922

```
[info] - should handle uid collision when connection TO two systems with same uid *** FAILED *** (3 seconds, 651 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (1 second) during expectMsg while waiting for ping1a
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:460)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:446)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:446)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:955)
[info]   at akka.remote.artery.RemoteConnectionSpec.$anonfun$new$2(RemoteConnectionSpec.scala:68)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6502286756/job/17661064180#step:5:867

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6502286756/job/17661064180#step:5:867

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/6489461147/job/17623760245#step:5:870
