### ISSUE TITLE
failed: Native image tests - NoSuchElementException

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32329]
https://github.com/akka/akka/actions/runs/7989482895/job/21816139834

```
java.util.NoSuchElementException: key not found: groupId
	at scala.collection.MapOps.default(Map.scala:274)
	at scala.collection.MapOps.default$(Map.scala:273)
	at scala.collection.AbstractMap.default(Map.scala:405)
	at scala.collection.MapOps.apply(Map.scala:176)
	at scala.collection.MapOps.apply$(Map.scala:175)
	at scala.collection.AbstractMap.apply(Map.scala:405)
	at com.fasterxml.jackson.module.scala.JacksonModule$.version$lzycompute(JacksonModule.scala:27)
```

@johanandren maybe this is already fixed?

**Comment by johanandren** [comment]
Yeah, it's fixed already 👍
