### ISSUE TITLE
failed: EventSourcedBehaviorRetentionSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32340]
https://github.com/akka/akka/actions/runs/8118729218/job/22193513083#step:5:21248

```
[03-02 00:44:43.423] [info] - must be possible to combine snapshotWhen withDeleteEventsOnSnapshot and retention criteria withDeleteEventsOnSnapshot *** FAILED *** (6 seconds, 454 milliseconds)
[03-02 00:44:43.423] [info]   java.lang.AssertionError: Timeout (6 seconds) during expectMessageClass waiting for class akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$WrappedSignal
[03-02 00:44:43.423] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[03-02 00:44:43.423] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:239)
[03-02 00:44:43.423] [info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:218)
[03-02 00:44:43.423] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec$WrappedSignalProbeAssert.expectSnapshotCompleted(EventSourcedBehaviorRetentionSpec.scala:100)
[03-02 00:44:43.423] [info]   at akka.persistence.typed.scaladsl.EventSourcedBehaviorRetentionSpec.$anonfun$new$47(EventSourcedBehaviorRetentionSpec.scala:598)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/8289252826/job/22685340169#step:5:21828

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/8319292097/job/22762371993#step:5:21711

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/8460345497/job/23178370464#step:5:13818

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/8768659699/job/24063252238#step:5:13947

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9143570797/job/25140386452#step:5:21824

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9375966322/job/25815071749#step:5:22171

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/9412714034/job/25928095427#step:5:2679

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9531813810/job/26273175007#step:5:21970

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9531813810/job/26273175259#step:5:21854

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10171616378/job/28132909612#step:5:22070

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10103384882/job/27940664015#step:5:21935

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9848729595/job/27191205270#step:5:13825

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10427826941/job/28883134468#step:5:22391

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10427826941/job/28883134568#step:5:22110

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10499433606/job/29086197921#step:5:21917

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/10932059300/job/30348222886#step:5:21927

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11135503217/job/30945644817#step:5:22399

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11356422700/job/31587573879#step:5:21823

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11751444846/job/32741480328#step:5:22335

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11847766400/job/33018090894#step:5:21582

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11883429231/job/33110177355#step:5:22999

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/12267061216/job/34226445164#step:5:13916

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/12520497970/job/34926248662?pr=32621#step:5:21337

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/12497683038/job/34870583751#step:5:16581

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13253082503/job/36994918331#step:5:14013

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13349876411/job/37284960597#step:5:14197

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13598759103/job/38021152679#step:5:22066

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/13688208889/job/38276287985#step:5:22251

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13935982027/job/39003843391#step:5:22936

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13847090003/job/38747654053#step:5:22632

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13959196104/job/39077231978#step:5:22867

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14150730467/job/39643504715#step:5:22498

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14287110421/job/40043490531#step:5:21954

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14786004390/job/41514408936#step:5:23400

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14805450004/job/41572863655#step:5:23105

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14815869478/job/41596189921#step:5:22481

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15405547049/job/43347437491#step:5:22202

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15864240206/job/44727956681#step:5:22825

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15657499699/job/44110462233#step:5:21992

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16510649961/job/46691801847#step:5:22367

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16610325570/job/46991938054#step:5:22219

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16636625753/job/47078721932#step:5:22266

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16764280021/job/47466236412#step:5:22873

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16855223045/job/47747123631#step:5:22013

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16855223045/job/47747123635#step:5:22708

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/16843058817/job/47717842129#step:5:21884

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/17113478542/job/48539737490#step:5:22200

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/17224141433/job/48865422867#step:5:22340

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/17479931743/job/49648237492#step:5:23459
