### ISSUE TITLE
Failed: ReplicatedMetricsSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32400]
https://github.com/akka/akka/actions/runs/8781761287/job/24094456887#step:12:708

```
[JVM-3] - must replicate metrics *** FAILED ***
[JVM-3]   java.lang.AssertionError: Timeout (3 seconds) during expectMessageClass waiting for class sample.distributeddata.ReplicatedMetrics$UsedHeap
[JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:239)
[JVM-3]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:218)
[JVM-3]   at sample.distributeddata.ReplicatedMetricsSpec.$anonfun$new$6(ReplicatedMetricsSpec.scala:77)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka/actions/runs/10444381666/job/28918846712#step:13:682

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/18933166141/job/54053877804#step:14:403

**Comment by patriknw** [comment]
https://github.com/akka/akka-core/actions/runs/23604044031/job/68741733970#step:14:310
