### ISSUE TITLE
failed: MetricsBasedResizerSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka#32401]
```scala
[04-22 00:21:08.495] [info] - must update the underutilizationStreak highestUtilization if current utilization is higher *** FAILED *** (1 millisecond)
[04-22 00:21:08.495] [info]   1 was not equal to 2 (MetricsBasedResizerSpec.scala:184)
[04-22 00:21:08.495] [info]   org.scalatest.exceptions.TestFailedException:
[04-22 00:21:08.495] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[04-22 00:21:08.495] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7539)
[04-22 00:21:08.496] [info]   at akka.routing.MetricsBasedResizerSpec.$anonfun$new$12(MetricsBasedResizerSpec.scala:184)
[04-22 00:21:08.496] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[04-22 00:21:08.496] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[04-22 00:21:08.496] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[04-22 00:21:08.496] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[04-22 00:21:08.496] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[04-22 00:21:08.496] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

https://github.com/akka/akka/actions/runs/8776509517/job/24080112235#step:5:3523

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/8903275603/job/24450743617#step:5:3534

Different error though:
```
[05-01 00:20:33.284] [info] - must record the performance log with the correct pool size *** FAILED *** (1 millisecond)
[05-01 00:20:33.284] [info]   None was empty (MetricsBasedResizerSpec.scala:226)
[05-01 00:20:33.284] [info]   org.scalatest.exceptions.TestFailedException:
[05-01 00:20:33.284] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[05-01 00:20:33.284] [info]   at org.scalatest.matchers.dsl.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:670)
[05-01 00:20:33.284] [info]   at akka.routing.MetricsBasedResizerSpec.$anonfun$new$15(MetricsBasedResizerSpec.scala:226)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/9556655096/job/26342363386#step:5:3587

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/10189553277/job/28187806094#step:5:3543

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10913123167/job/30289058398#step:5:3546

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11079345367/job/30788227090#step:5:3495

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11097087058/job/30827758858#step:5:3515

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11135503217/job/30945644617#step:5:3625

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11226110264/job/31206024294#step:5:3688

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13610186507/job/38046318514#step:5:4069

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13867428355/job/38809182786#step:5:3585

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13981845470/job/39148535216#step:5:3515

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14095981824/job/39483297160#step:5:3564

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14140109321/job/39619929551#step:5:3765

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14161404165/job/39667395797#step:5:3689

A different one though:
```
[03-31 00:25:50.569] [info] - must record the performance log with the correct pool size *** FAILED *** (1 millisecond)
[03-31 00:25:50.570] [info]   None was empty (MetricsBasedResizerSpec.scala:226)
[03-31 00:25:50.570] [info]   org.scalatest.exceptions.TestFailedException:
[03-31 00:25:50.570] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[03-31 00:25:50.570] [info]   at org.scalatest.matchers.dsl.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:670)
[03-31 00:25:50.570] [info]   at akka.routing.MetricsBasedResizerSpec.$anonfun$new$15(MetricsBasedResizerSpec.scala:226)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/14255227021/job/39956588663#step:5:3603

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14310308674/job/40103444591?pr=32690#step:5:3600

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14414128616/job/40427893288#step:5:3599

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14458368969/job/40546231389#step:5:3881

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14481868437/job/40620287879#step:5:3652

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14481868437/job/40620288360#step:5:3655

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14675624268/job/41191253418#step:5:3750

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/14895774673/job/41837897611#step:5:3566

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15502107451/job/43651493519#step:5:3562

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15455411478/job/43506626318#step:5:3610

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15864240206/job/44727956682#step:5:3626

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15746336999/job/44383208085#step:5:3420

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15720798003/job/44301159965#step:5:3529

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15657499699/job/44110462226#step:5:3694

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15646264603/job/44084227127#step:5:3578

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/15623456803/job/44013151228#step:5:4051

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/17718611080/job/50347068113#step:5:3832

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/19996268379/job/57344243927#step:7:3709

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/29790418875/job/88510803561#step:6:4017

**Comment by johanandren** [comment]
https://github.com/akka/akka-core/actions/runs/31852765715/job/94931563031#step:6:3801
