### ISSUE TITLE
Java DSL throws exception when using `akka.persistence.typed.javadsl.EventSourcedBehavior#lastSequenceNumber`

### ISSUE THREAD

**Issue by aludwiko** [akka/akka#32433]
When handling the first event in the event handler:
```
java.lang.IllegalStateException: Cannot extract the lastSequenceNumber in state akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1
	at akka.persistence.typed.scaladsl.EventSourcedBehavior$.lastSequenceNumber(EventSourcedBehavior.scala:115)
	at akka.persistence.typed.javadsl.EventSourcedBehavior.lastSequenceNumber(EventSourcedBehavior.scala:263)
	at perf.test.iot.DeviceEntity.eventHandler(DeviceEntity.java:82)
	at akka.persistence.typed.javadsl.EventSourcedBehavior.createEventSourcedBehavior(EventSourcedBehavior.scala:224)
	at akka.persistence.typed.javadsl.EventSourcedBehavior.apply(EventSourcedBehavior.scala:207)
```

I think that pattern matching should also cover Deferred wrapper:
<img width="1043" alt="image" src="https://github.com/akka/akka/assets/2954053/6ea2fde9-26f6-4da1-94c0-348286903dc4">

**Comment by johanandren** [comment]
> When handling the first event in the event handler

On replay, or after handling a command?

**Comment by aludwiko** [comment]
> > When handling the first event in the event handler
> 
> On replay, or after handling a command?

After handling a command.

**Comment by leviramsey** [comment]
> When handling the first event in the event handler
>
> On replay, or after handling a command?
>
> After handling a command.
>

From the looks of that stack trace, it was while the event-sourced behavior
was being constructed (maybe a log?), before handling an event.
