### ISSUE TITLE
failed: HubSpec - BroadcastHub must ensure that subsequent consumers see subsequent elements without gap

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32474]
https://github.com/akka/akka/actions/runs/10240357858/job/28327078753#step:5:16604

```
[08-05 00:47:06.590] [info] - must ensure that subsequent consumers see subsequent elements without gap *** FAILED *** (12 milliseconds)
[08-05 00:47:06.611] [info]   Vector(9, 10, 11, 12, 13, 14, 15, 16, 17, 18) did not equal Range$Inclusive(11, 12, 13, 14, 15, 16, 17, 18, 19, 20) (HubSpec.scala:360)
[08-05 00:47:06.611] [info]   org.scalatest.exceptions.TestFailedException:
[08-05 00:47:06.611] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[08-05 00:47:06.612] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7469)
[08-05 00:47:06.612] [info]   at akka.stream.scaladsl.HubSpec.$anonfun$new$34(HubSpec.scala:360)
[08-05 00:47:06.612] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[08-05 00:47:06.612] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[08-05 00:47:06.612] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[08-05 00:47:06.612] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[08-05 00:47:06.612] [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[08-05 00:47:06.612] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[08-05 00:47:06.613] [info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[08-05 00:47:06.613] [info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[08-05 00:47:06.613] [info]   at akka.stream.testkit.StreamSpec.withFixture(StreamSpec.scala:35)
[08-05 00:47:06.613] [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[08-05 00:47:06.613] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[08-05 00:47:06.613] [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[08-05 00:47:06.613] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[08-05 00:47:06.613] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[08-05 00:47:06.614] [info]   at akka.testkit.AkkaSpec.runTest(AkkaSpec.scala:54)
[08-05 00:47:06.614] [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[08-05 00:47:06.614] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[08-05 00:47:06.614] [info]   at scala.collection.immutable.List.foreach(List.scala:334)
[08-05 00:47:06.614] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[08-05 00:47:06.614] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[08-05 00:47:06.614] [info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[08-05 00:47:06.614] [info]   at scala.collection.immutable.List.foreach(List.scala:334)
[08-05 00:47:06.615] [info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[08-05 00:47:06.615] [info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[08-05 00:47:06.615] [info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[08-05 00:47:06.615] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[08-05 00:47:06.615] [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10436227835/job/28901027490

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10462900591/job/28973991509#step:5:17064

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/10624512986/job/29452959886#step:5:17134

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/13753969970/job/38458522189#step:5:16973
