### ISSUE TITLE
Failed: EventSourcedBehaviorLoggingSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka#32554]
https://github.com/akka/akka/actions/runs/11116174951/job/30885977668#step:5:21725

```
[10-01 00:52:07.613] [info] - must always log user message in context.log *** FAILED *** (6 seconds, 10 milliseconds)
[10-01 00:52:07.613] [info]   java.lang.AssertionError: Timeout (6 seconds) waiting for 1 messages on LoggingTestKitImpl(1,Some(INFO),Some(akka.persistence.typed.EventSourcedBehaviorLoggingSpec$ChattyEventSourcingBehavior$),None,Some(received message 'Mary'),None,None,Map(),true,None).
[10-01 00:52:07.613] [info]   at akka.actor.testkit.typed.internal.LoggingTestKitImpl.expect(LoggingTestKitImpl.scala:103)
[10-01 00:52:07.613] [info]   at akka.persistence.typed.EventSourcedBehaviorLoggingSpec.f$proxy1$1(EventSourcedBehaviorLoggingSpec.scala:75)
[10-01 00:52:07.613] [info]   at akka.persistence.typed.EventSourcedBehaviorLoggingSpec.$init$$$anonfun$1$$anonfun$1(EventSourcedBehaviorLoggingSpec.scala:76)
[10-01 00:52:07.613] [info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[10-01 00:52:07.613] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[10-01 00:52:07.613] [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[10-01 00:52:07.613] [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[10-01 00:52:07.613] [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[10-01 00:52:07.613] [info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[10-01 00:52:07.613] [info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
[10-01 00:52:07.613] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:79)
[10-01 00:52:07.613] [info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:33)
[10-01 00:52:07.613] [info]   at akka.persistence.typed.EventSourcedBehaviorLoggingSpec.withFixture(EventSourcedBehaviorLoggingSpec.scala:54)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka/actions/runs/11153558077/job/31001293695#step:5:22047

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/11188700877/job/31107926556#step:5:21918

**Comment by octonato** [comment]
Happening all the time.

https://github.com/akka/akka/actions/runs/11197362646/job/31127237595#step:5:21960

**Comment by octonato** [comment]
https://github.com/akka/akka/actions/runs/11206353997/job/31146984590#step:5:22237

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11226110264/job/31206025324#step:5:22206

**Comment by johanandren** [comment]
Possibly something that broke after merging the logback classic 1.5.8 bump (sep 30, this stated failing oct 1)

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11245779659/job/31266442261#step:5:21919

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11265045919/job/31326187020#step:5:21561

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11300945513/job/31434598859#step:5:21954

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11336907629/job/31527628152#step:5:21762

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11318855501/job/31474012134#step:5:21975

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11309820947/job/31454103265#step:5:22081

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11356422700/job/31587574210#step:5:22108

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11412766065/job/31759295379#step:5:22342

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11421815226/job/31779033485#step:5:22665

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11470573327/job/31919995426#step:5:22091

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11450763951/job/31858824817#step:5:22630

**Comment by johanandren** [comment]
BTW I think this is a mix of the two tests `EventSourcedBehaviorLoggingInternalLoggerSpec` and `EventSourcedBehaviorLoggingContextLoggerSpec` failing pretty consistently on JDK 17, Scala 3. `EventSourcedBehaviorLoggingSpec` being a common supertype.

**Comment by patriknw** [comment]
Fails frequently, or always. Same locally. I'll take a look.
