### ISSUE TITLE
fail: ReplicatedEventSourcingSpec interceptor

### ISSUE THREAD

**Issue by patriknw** [akka/akka#32564]
https://github.com/akka/akka/actions/runs/11342612762/job/31543407718?pr=32558#step:5:11617

```
[10-15 09:10:55.166] [info] - should intercept and delay replicated events between two entities *** FAILED *** (206 milliseconds)
[10-15 09:10:55.175] [info]   Set(Intercepted(R1, 1, "from r1"), Intercepted(R2, 2, "from r2")) did not equal Set(Intercepted(R1, 2, "from r1"), Intercepted(R2, 2, "from r2")) (ReplicatedEventSourcingSpec.scala:594)
[10-15 09:10:55.175] [info]   Analysis:
[10-15 09:10:55.175] [info]   Set(missingInLeft: [Intercepted(R1, 2, "from r1")], missingInRight: [Intercepted(R1, 1, "from r1")])
[10-15 09:10:55.175] [info]   org.scalatest.exceptions.TestFailedException:
[10-15 09:10:55.176] [info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:397)
[10-15 09:10:55.176] [info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:7394)
[10-15 09:10:55.177] [info]   at akka.persistence.typed.ReplicatedEventSourcingSpec.$anonfun$new$36(ReplicatedEventSourcingSpec.scala:594)
```

**Comment by patriknw** [comment]
@johanandren still some nightly fails for this test

**Comment by johanandren** [comment]
https://github.com/akka/akka/actions/runs/11490186746/job/31980423578#step:5:14056

Huh, I thought I explicitly fixed not checking the sequence number but just that the event payload was in there:

```
[10-24 00:37:22.399] [info] - should intercept replicated events between two entities *** FAILED *** (42 milliseconds)
[10-24 00:37:22.399] [info]   Set(Intercepted(R1, 1, "from r1"), Intercepted(R2, 2, "from r2")) did not equal Set(Intercepted(R1, 2, "from r1"), Intercepted(R2, 2, "from r2")) (ReplicatedEventSourcingSpec.scala:563)
```

**Comment by johanandren** [comment]
Better luck this time 🤞
